import EtingofRepresentationTheory.Chapter4.Problem4_12_5

/-!
# Concrete icosahedral models for Problem 4.12.5

`Chapter4/Problem4_12_5.lean` proves the three decomposition theorems
(`vertices_decomposition`, `faces_decomposition`, `edges_decomposition`) for *any* transitive
action `act : A₅ →* Equiv.Perm (Fin N)` with point stabilizers of order `5`, `3`, `2`
(`N = 12, 20, 30`). It never exhibits such an action, so the three theorems are conditional and
their non-vacuity rests on an unformalized appeal to the geometry of the icosahedron.

This file removes that gap. It constructs the actions, verifies the hypotheses, and derives
unconditional corollaries.

## The models

The rotation group of the regular icosahedron is `A₅`, acting transitively on the `12` vertices,
the `20` faces and the `30` edges. The stabilizer of a vertex is the cyclic group of order `5`
generated by the rotation about that vertex; of a face, the cyclic group of order `3`; of an
edge, the cyclic group of order `2` generated by the half-turn about the edge's midpoint. Each
of these actions is therefore the left-translation action of `A₅` on the coset space `A₅ ⧸ H`
for `H` cyclic of order `5`, `3`, `2` respectively, and those coset spaces have
`60 / 5 = 12`, `60 / 3 = 20`, `60 / 2 = 30` elements.

We build exactly those coset models, taking `H` to be `⟨classRepA5 3⟩`, `⟨classRepA5 1⟩`,
`⟨classRepA5 2⟩` — the cyclic subgroups generated by the class representatives of orders `5`,
`3`, `2` already fixed in `Chapter4/Example4_8_1/A5Classes.lean` — and transport along a
bijection with `Fin N`.

## Why the coset model is *the* icosahedral action

`transitiveEquivQuotient` shows every transitive `act` on `Fin N` is equivariantly isomorphic to
the coset action on `A₅ ⧸ stabSub act i₀`, and `quotientEquivOfConjSubgroup` shows conjugate
subgroups give equivariantly isomorphic coset spaces. Since all Sylow `5`-subgroups, all Sylow
`3`-subgroups and all involutions of `A₅` are conjugate, this gives
`unique_transitive_model`: any two transitive `A₅`-actions on `Fin N` with point stabilizers of
the same prime order `5`, `3` or `2` are equivariantly isomorphic. So whichever concrete model
of the icosahedron one starts from, its vertex/face/edge action *is* the model built here, and
the decompositions below are statements about the genuine icosahedral representations rather
than about one arbitrary choice.

## Main results

* `verticesAct`, `facesAct`, `edgesAct` — the constructed actions on `Fin 12`, `Fin 20`,
  `Fin 30`, with their transitivity and stabilizer-order lemmas.
* `vertices_decomposition_icosahedral`, `faces_decomposition_icosahedral`,
  `edges_decomposition_icosahedral` — the three decompositions with no hypotheses.
* `unique_transitive_model` — model independence.
-/

noncomputable section

namespace Etingof.Problem4_12_5

open Finset MulAction

/-! ## Orbit-stabilizer: transitivity forces the stabilizer order

The point-stabilizer order is not an extra assumption on top of transitivity, it is determined
by the degree: for a transitive action of `G` on `Fin n`, `n * |stabilizer| = |G|`. This is the
`g = 1` case of the orbit-stabilizer identity `fix_mul_stab_card` already proved in
`Problem4_12_5.lean`. -/

section OrbitStabilizer

variable {G : Type*} [Group G] [Fintype G] [DecidableEq G] {n : ℕ}

set_option linter.unusedSectionVars false
set_option linter.unusedDecidableInType false
set_option linter.unusedFintypeInType false

/-- **Orbit-stabilizer**, in `Finset.filter` form: for a transitive action on `Fin n`, the degree
times the order of a point stabilizer is the order of the group. -/
lemma card_mul_stab_filter_card (act : G →* Equiv.Perm (Fin n)) (i₀ : Fin n)
    (htrans : ∀ j : Fin n, ∃ x : G, act x i₀ = j) :
    n * (univ.filter (fun x : G => act x i₀ = i₀)).card = Fintype.card G := by
  have h := fix_mul_stab_card act 1 i₀ htrans
  have hfix : (univ.filter (fun i : Fin n => act 1 i = i)).card = n := by
    rw [Finset.filter_true_of_mem (fun i _ => by simp), Finset.card_univ, Fintype.card_fin]
  have hconj : (univ.filter (fun x : G => act (x⁻¹ * 1 * x) i₀ = i₀)).card = Fintype.card G := by
    rw [Finset.filter_true_of_mem (fun x _ => by simp), Finset.card_univ]
  rwa [hfix, hconj] at h

/-- **Orbit-stabilizer**, in `Nat.card` form — the shape the decomposition theorems take their
`hstab` hypothesis in. -/
lemma card_mul_card_stab (act : G →* Equiv.Perm (Fin n)) (i₀ : Fin n)
    (htrans : ∀ j : Fin n, ∃ x : G, act x i₀ = j) :
    n * Nat.card {g : G // act g i₀ = i₀} = Nat.card G := by
  rw [Nat.card_eq_fintype_card (α := {g : G // act g i₀ = i₀}), Fintype.card_subtype,
    Nat.card_eq_fintype_card (α := G)]
  exact card_mul_stab_filter_card act i₀ htrans

end OrbitStabilizer

/-! ## Transporting a coset action to `Fin N` -/

section CosetModel

/-- Transport of permutations along a bijection of the underlying sets, as a group
homomorphism. -/
def permCongrHom {X Y : Type*} (e : X ≃ Y) : Equiv.Perm X →* Equiv.Perm Y where
  toFun := e.permCongr
  map_one' := by ext y; simp [Equiv.permCongr_def]
  map_mul' p q := by ext y; simp [Equiv.permCongr_def]

variable {G : Type*} [Group G] (H : Subgroup G) {N : ℕ}

/-- The action of `G` on `Fin N` obtained from the left-translation action on the coset space
`G ⧸ H`, transported along a bijection `e : (G ⧸ H) ≃ Fin N`. -/
def cosetAct (e : (G ⧸ H) ≃ Fin N) : G →* Equiv.Perm (Fin N) :=
  (permCongrHom e).comp (MulAction.toPermHom G (G ⧸ H))

@[simp] lemma cosetAct_apply (e : (G ⧸ H) ≃ Fin N) (g : G) (i : Fin N) :
    cosetAct H e g i = e (g • e.symm i) := rfl

/-- The coset action is transitive: `G` acts transitively on `G ⧸ H` by left translation. -/
lemma cosetAct_transitive (e : (G ⧸ H) ≃ Fin N) (i j : Fin N) :
    ∃ g : G, cosetAct H e g i = j := by
  obtain ⟨g, hg⟩ := MulAction.exists_smul_eq G (e.symm i) (e.symm j)
  exact ⟨g, by rw [cosetAct_apply, hg, Equiv.apply_symm_apply]⟩

/-- The coset space `G ⧸ H` has `|G| / |H|` elements. -/
lemma card_quotient_mul_card (H : Subgroup G) : Nat.card (G ⧸ H) * Nat.card H = Nat.card G := by
  rw [← Subgroup.index_eq_card]; exact H.index_mul_card

end CosetModel

/-! ## Model independence

Two ingredients. First, every transitive action of `A₅` on `Fin N` *is* a coset action: the orbit
map `a ↦ act a i₀` descends to an equivariant bijection `A₅ ⧸ stabSub act i₀ ≃ Fin N`. Second,
conjugate subgroups have equivariantly isomorphic coset spaces. Together they say that a
transitive action is determined, up to equivariant isomorphism, by the conjugacy class of its
point stabilizer. -/

section ModelIndependence

variable {N : ℕ} (act : A5 →* Equiv.Perm (Fin N)) (i₀ : Fin N)

/-- The orbit map `a ↦ act a i₀`, descended to the coset space of the point stabilizer. -/
def quotStabToFin : (A5 ⧸ stabSub act i₀) → Fin N := fun x =>
  Quotient.liftOn' x (fun a => act a i₀) <| by
    intro a b hab
    have hmem : a⁻¹ * b ∈ stabSub act i₀ := QuotientGroup.leftRel_apply.mp hab
    have h1 : act (a⁻¹ * b) i₀ = i₀ := hmem
    rw [map_mul, map_inv, Equiv.Perm.mul_apply, Equiv.Perm.inv_def,
      Equiv.symm_apply_eq] at h1
    exact h1.symm

@[simp] lemma quotStabToFin_mk (a : A5) :
    quotStabToFin act i₀ (a : A5 ⧸ stabSub act i₀) = act a i₀ := rfl

lemma quotStabToFin_injective : Function.Injective (quotStabToFin act i₀) := by
  intro x y h
  induction x using Quotient.inductionOn' with | _ a =>
  induction y using Quotient.inductionOn' with | _ b =>
  have h' : act a i₀ = act b i₀ := h
  refine QuotientGroup.eq.mpr ?_
  change act (a⁻¹ * b) i₀ = i₀
  rw [map_mul, map_inv, Equiv.Perm.mul_apply, ← h', Equiv.Perm.inv_def,
    Equiv.symm_apply_apply]

lemma quotStabToFin_surjective (htrans : ∀ j : Fin N, ∃ x : A5, act x i₀ = j) :
    Function.Surjective (quotStabToFin act i₀) := by
  intro j
  obtain ⟨x, hx⟩ := htrans j
  exact ⟨(x : A5 ⧸ stabSub act i₀), hx⟩

/-- **Every transitive action is a coset action.** For a transitive `act`, the orbit map is an
equivariant bijection `A₅ ⧸ stabSub act i₀ ≃ Fin N` (see `quotStabEquivFin_smul`). -/
def quotStabEquivFin (htrans : ∀ j : Fin N, ∃ x : A5, act x i₀ = j) :
    (A5 ⧸ stabSub act i₀) ≃ Fin N :=
  Equiv.ofBijective _ ⟨quotStabToFin_injective act i₀, quotStabToFin_surjective act i₀ htrans⟩

@[simp] lemma quotStabEquivFin_mk (htrans : ∀ j : Fin N, ∃ x : A5, act x i₀ = j) (a : A5) :
    quotStabEquivFin act i₀ htrans (a : A5 ⧸ stabSub act i₀) = act a i₀ := rfl

/-- The orbit bijection intertwines left translation on cosets with `act`. -/
lemma quotStabEquivFin_smul (htrans : ∀ j : Fin N, ∃ x : A5, act x i₀ = j)
    (g : A5) (x : A5 ⧸ stabSub act i₀) :
    quotStabEquivFin act i₀ htrans (g • x) = act g (quotStabEquivFin act i₀ htrans x) := by
  induction x using Quotient.inductionOn' with | _ a =>
  change act (g * a) i₀ = act g (act a i₀)
  rw [map_mul, Equiv.Perm.mul_apply]

/-- The inverse form of `quotStabEquivFin_smul`, in the shape needed downstream. -/
lemma quotStabEquivFin_symm_act (htrans : ∀ j : Fin N, ∃ x : A5, act x i₀ = j)
    (g : A5) (i : Fin N) :
    (quotStabEquivFin act i₀ htrans).symm (act g i)
      = g • (quotStabEquivFin act i₀ htrans).symm i := by
  apply (quotStabEquivFin act i₀ htrans).injective
  rw [Equiv.apply_symm_apply, quotStabEquivFin_smul, Equiv.apply_symm_apply]

variable {act i₀}

/-- **Conjugate subgroups give equivariantly isomorphic coset spaces.** If `H₂ = c H₁ c⁻¹`
(written pointwise as `y ∈ H₂ ↔ c⁻¹ y c ∈ H₁`), then `a H₁ ↦ a c⁻¹ H₂` is an `A₅`-equivariant
bijection `A₅ ⧸ H₁ ≃ A₅ ⧸ H₂`. -/
def quotientEquivOfConjSubgroup {H₁ H₂ : Subgroup A5} (c : A5)
    (hc : ∀ y : A5, y ∈ H₂ ↔ c⁻¹ * y * c ∈ H₁) : (A5 ⧸ H₁) ≃ (A5 ⧸ H₂) where
  toFun x := Quotient.liftOn' x (fun a => ((a * c⁻¹ : A5) : A5 ⧸ H₂)) <| by
    intro a b hab
    have hmem : a⁻¹ * b ∈ H₁ := QuotientGroup.leftRel_apply.mp hab
    refine QuotientGroup.eq.mpr ?_
    rw [hc]
    rw [show c⁻¹ * ((a * c⁻¹)⁻¹ * (b * c⁻¹)) * c = a⁻¹ * b by group]
    exact hmem
  invFun x := Quotient.liftOn' x (fun a => ((a * c : A5) : A5 ⧸ H₁)) <| by
    intro a b hab
    have hmem : a⁻¹ * b ∈ H₂ := QuotientGroup.leftRel_apply.mp hab
    rw [hc] at hmem
    refine QuotientGroup.eq.mpr ?_
    rw [show (a * c)⁻¹ * (b * c) = c⁻¹ * (a⁻¹ * b) * c by group]
    exact hmem
  left_inv x := by
    induction x using Quotient.inductionOn' with | _ a =>
    change ((a * c⁻¹ * c : A5) : A5 ⧸ H₁) = (a : A5 ⧸ H₁)
    rw [inv_mul_cancel_right]
  right_inv x := by
    induction x using Quotient.inductionOn' with | _ a =>
    change ((a * c * c⁻¹ : A5) : A5 ⧸ H₂) = (a : A5 ⧸ H₂)
    rw [mul_inv_cancel_right]

@[simp] lemma quotientEquivOfConjSubgroup_mk {H₁ H₂ : Subgroup A5} (c : A5)
    (hc : ∀ y : A5, y ∈ H₂ ↔ c⁻¹ * y * c ∈ H₁) (a : A5) :
    quotientEquivOfConjSubgroup c hc (a : A5 ⧸ H₁) = ((a * c⁻¹ : A5) : A5 ⧸ H₂) := rfl

lemma quotientEquivOfConjSubgroup_smul {H₁ H₂ : Subgroup A5} (c : A5)
    (hc : ∀ y : A5, y ∈ H₂ ↔ c⁻¹ * y * c ∈ H₁) (g : A5) (x : A5 ⧸ H₁) :
    quotientEquivOfConjSubgroup c hc (g • x) = g • quotientEquivOfConjSubgroup c hc x := by
  induction x using Quotient.inductionOn' with | _ a =>
  change ((g * a * c⁻¹ : A5) : A5 ⧸ H₂) = ((g * (a * c⁻¹) : A5) : A5 ⧸ H₂)
  rw [mul_assoc]

/-- **Model independence.** A transitive action of `A₅` on `Fin N` whose point stabilizer at `0`
is conjugate to `H` is equivariantly isomorphic to the coset model `cosetAct H e`. -/
theorem exists_equivariant_equiv_cosetAct [NeZero N] {H : Subgroup A5} (e : (A5 ⧸ H) ≃ Fin N)
    (act : A5 →* Equiv.Perm (Fin N)) (htrans : ∀ i j : Fin N, ∃ g : A5, act g i = j)
    (c : A5) (hc : ∀ y : A5, y ∈ H ↔ c⁻¹ * y * c ∈ stabSub act 0) :
    ∃ φ : Fin N ≃ Fin N, ∀ (g : A5) (i : Fin N), φ (act g i) = cosetAct H e g (φ i) := by
  have htrans0 : ∀ j : Fin N, ∃ x : A5, act x 0 = j := fun j => htrans 0 j
  set ψ := quotStabEquivFin act 0 htrans0 with hψ
  set χ := quotientEquivOfConjSubgroup c hc with hχ
  refine ⟨(ψ.symm.trans χ).trans e, fun g i => ?_⟩
  change e (χ (ψ.symm (act g i))) = cosetAct H e g (e (χ (ψ.symm i)))
  rw [quotStabEquivFin_symm_act act 0 htrans0, hχ, quotientEquivOfConjSubgroup_smul,
    cosetAct_apply, Equiv.symm_apply_apply]

end ModelIndependence

/-! ## The three icosahedral models

`classRepA5 3`, `classRepA5 1`, `classRepA5 2` have orders `5`, `3`, `2` (`ord_cr3`, `ord_cr1`,
`ord_cr2` in `Problem4_12_5.lean`), so the cyclic subgroups they generate are the vertex, face
and edge stabilizers of the icosahedron. -/

section Icosahedron

open Etingof.Example4_8_1.A5

/-- The vertex stabilizer of the icosahedron: a cyclic subgroup of `A₅` of order `5`. -/
def vertexStab : Subgroup A5 := Subgroup.zpowers (classRepA5 3)

/-- The face stabilizer of the icosahedron: a cyclic subgroup of `A₅` of order `3`. -/
def faceStab : Subgroup A5 := Subgroup.zpowers (classRepA5 1)

/-- The edge stabilizer of the icosahedron: a cyclic subgroup of `A₅` of order `2`, generated by
the half-turn about the edge's midpoint. -/
def edgeStab : Subgroup A5 := Subgroup.zpowers (classRepA5 2)

lemma card_vertexStab : Nat.card vertexStab = 5 := by
  rw [vertexStab, Nat.card_zpowers, ord_cr3]

lemma card_faceStab : Nat.card faceStab = 3 := by
  rw [faceStab, Nat.card_zpowers, ord_cr1]

lemma card_edgeStab : Nat.card edgeStab = 2 := by
  rw [edgeStab, Nat.card_zpowers, ord_cr2]

/-- The icosahedron has `12` vertices: `[A₅ : ⟨5-cycle⟩] = 60 / 5 = 12`. -/
lemma card_quotient_vertexStab : Nat.card (A5 ⧸ vertexStab) = 12 := by
  have h := card_quotient_mul_card vertexStab
  rw [card_vertexStab, card_A5] at h
  omega

/-- The icosahedron has `20` faces: `[A₅ : ⟨3-cycle⟩] = 60 / 3 = 20`. -/
lemma card_quotient_faceStab : Nat.card (A5 ⧸ faceStab) = 20 := by
  have h := card_quotient_mul_card faceStab
  rw [card_faceStab, card_A5] at h
  omega

/-- The icosahedron has `30` edges: `[A₅ : ⟨involution⟩] = 60 / 2 = 30`. -/
lemma card_quotient_edgeStab : Nat.card (A5 ⧸ edgeStab) = 30 := by
  have h := card_quotient_mul_card edgeStab
  rw [card_edgeStab, card_A5] at h
  omega

/-- A labelling of the `12` vertices of the icosahedron by `Fin 12`. -/
def vertexEquiv : (A5 ⧸ vertexStab) ≃ Fin 12 := Finite.equivFinOfCardEq card_quotient_vertexStab

/-- A labelling of the `20` faces of the icosahedron by `Fin 20`. -/
def faceEquiv : (A5 ⧸ faceStab) ≃ Fin 20 := Finite.equivFinOfCardEq card_quotient_faceStab

/-- A labelling of the `30` edges of the icosahedron by `Fin 30`. -/
def edgeEquiv : (A5 ⧸ edgeStab) ≃ Fin 30 := Finite.equivFinOfCardEq card_quotient_edgeStab

/-- **The vertex action of `A₅` on the icosahedron**, as a permutation action on `Fin 12`. -/
def verticesAct : A5 →* Equiv.Perm (Fin 12) := cosetAct vertexStab vertexEquiv

/-- **The face action of `A₅` on the icosahedron**, as a permutation action on `Fin 20`. -/
def facesAct : A5 →* Equiv.Perm (Fin 20) := cosetAct faceStab faceEquiv

/-- **The edge action of `A₅` on the icosahedron**, as a permutation action on `Fin 30`. -/
def edgesAct : A5 →* Equiv.Perm (Fin 30) := cosetAct edgeStab edgeEquiv

lemma verticesAct_transitive : ∀ i j : Fin 12, ∃ g : A5, verticesAct g i = j :=
  cosetAct_transitive vertexStab vertexEquiv

lemma facesAct_transitive : ∀ i j : Fin 20, ∃ g : A5, facesAct g i = j :=
  cosetAct_transitive faceStab faceEquiv

lemma edgesAct_transitive : ∀ i j : Fin 30, ∃ g : A5, edgesAct g i = j :=
  cosetAct_transitive edgeStab edgeEquiv

/-- Vertex stabilizers have order `5`, as required by `vertices_decomposition`. -/
lemma verticesAct_stab (i : Fin 12) : Nat.card {g : A5 // verticesAct g i = i} = 5 := by
  have h := card_mul_card_stab verticesAct i (fun j => verticesAct_transitive i j)
  rw [card_A5] at h
  omega

/-- Face stabilizers have order `3`, as required by `faces_decomposition`. -/
lemma facesAct_stab (i : Fin 20) : Nat.card {g : A5 // facesAct g i = i} = 3 := by
  have h := card_mul_card_stab facesAct i (fun j => facesAct_transitive i j)
  rw [card_A5] at h
  omega

/-- Edge stabilizers have order `2`, as required by `edges_decomposition`. -/
lemma edgesAct_stab (i : Fin 30) : Nat.card {g : A5 // edgesAct g i = i} = 2 := by
  have h := card_mul_card_stab edgesAct i (fun j => edgesAct_transitive i j)
  rw [card_A5] at h
  omega

/-! ### Every icosahedral model is *this* model

The three lemmas below discharge the hypothesis of `exists_equivariant_equiv_cosetAct` using the
conjugacy results already in `Problem4_12_5.lean`: Sylow's second theorem for the vertex and face
stabilizers (orders `5` and `3`, the full `5`- and `3`-parts of `|A₅| = 60`), and the conjugacy of
involutions for the edge stabilizers. The upshot is that *any* transitive `A₅`-action of the right
degree and stabilizer order — in particular the vertex/face/edge action of any concrete
realization of the regular icosahedron — is equivariantly isomorphic to the model built above, so
the decompositions below are statements about the genuine icosahedral representations. -/

/-- Repackage the decomposition theorems' `hstab` hypothesis as a statement about `stabSub`. -/
lemma card_stabSub_of_hstab {N p : ℕ} (act : A5 →* Equiv.Perm (Fin N)) (i₀ : Fin N)
    (hstab : Nat.card {g : A5 // act g i₀ = i₀} = p) : Nat.card (stabSub act i₀) = p := by
  rw [← hstab]
  exact Nat.card_congr (Equiv.subtypeEquivRight (mem_stabSub act i₀))

/-- **Uniqueness of the vertex model.** Any transitive action of `A₅` on `12` points with point
stabilizers of order `5` is equivariantly isomorphic to `verticesAct`. -/
theorem verticesAct_unique (act : A5 →* Equiv.Perm (Fin 12))
    (htrans : ∀ i j : Fin 12, ∃ g : A5, act g i = j)
    (hstab : ∀ i : Fin 12, Nat.card {g : A5 // act g i = i} = 5) :
    ∃ φ : Fin 12 ≃ Fin 12, ∀ (g : A5) (i : Fin 12), φ (act g i) = verticesAct g (φ i) := by
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  obtain ⟨c, hc⟩ := exists_conj_stab_sylow act (classRepA5 3) ord_cr3 fact5
    (card_stabSub_of_hstab act 0 (hstab 0))
  exact exists_equivariant_equiv_cosetAct vertexEquiv act htrans c hc

/-- **Uniqueness of the face model.** Any transitive action of `A₅` on `20` points with point
stabilizers of order `3` is equivariantly isomorphic to `facesAct`. -/
theorem facesAct_unique (act : A5 →* Equiv.Perm (Fin 20))
    (htrans : ∀ i j : Fin 20, ∃ g : A5, act g i = j)
    (hstab : ∀ i : Fin 20, Nat.card {g : A5 // act g i = i} = 3) :
    ∃ φ : Fin 20 ≃ Fin 20, ∀ (g : A5) (i : Fin 20), φ (act g i) = facesAct g (φ i) := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  obtain ⟨c, hc⟩ := exists_conj_stab_sylow act (classRepA5 1) ord_cr1 fact3
    (card_stabSub_of_hstab act 0 (hstab 0))
  exact exists_equivariant_equiv_cosetAct faceEquiv act htrans c hc

/-- **Uniqueness of the edge model.** Any transitive action of `A₅` on `30` points with point
stabilizers of order `2` is equivariantly isomorphic to `edgesAct`. -/
theorem edgesAct_unique (act : A5 →* Equiv.Perm (Fin 30))
    (htrans : ∀ i j : Fin 30, ∃ g : A5, act g i = j)
    (hstab : ∀ i : Fin 30, Nat.card {g : A5 // act g i = i} = 2) :
    ∃ φ : Fin 30 ≃ Fin 30, ∀ (g : A5) (i : Fin 30), φ (act g i) = edgesAct g (φ i) := by
  obtain ⟨c, hc⟩ := exists_conj_stab_invol act (card_stabSub_of_hstab act 0 (hstab 0))
  exact exists_equivariant_equiv_cosetAct edgeEquiv act htrans c hc

/-! ## The unconditional decompositions -/

/-- **Problem 4.12.5(a), unconditionally.** The representation of `A₅` on the space of complex
functions on the `12` vertices of the regular icosahedron decomposes as `1 ⊕ 3 ⊕ 3' ⊕ 5`. -/
theorem vertices_decomposition_icosahedral :
    ∃ (S : Fin 4 → Submodule ℂ (Fin 12 → ℂ))
      (hS : ∀ k, ∀ g : A5, ∀ v ∈ S k, permRep verticesAct g v ∈ S k),
      DirectSum.IsInternal S ∧
      (∀ k, IsIrredSub (permRep verticesAct) (S k)) ∧
      Module.finrank ℂ (S 0) = 1 ∧ Module.finrank ℂ (S 1) = 3 ∧
      Module.finrank ℂ (S 2) = 3 ∧ Module.finrank ℂ (S 3) = 5 ∧
      ∃ g : A5, subChar (permRep verticesAct) (S 1) (hS 1) g
        ≠ subChar (permRep verticesAct) (S 2) (hS 2) g :=
  vertices_decomposition verticesAct verticesAct_transitive verticesAct_stab

/-- **Problem 4.12.5(b), faces, unconditionally.** The representation of `A₅` on the space of
complex functions on the `20` faces decomposes as `1 ⊕ 3 ⊕ 3' ⊕ 4² ⊕ 5`. -/
theorem faces_decomposition_icosahedral :
    ∃ (S : Fin 6 → Submodule ℂ (Fin 20 → ℂ))
      (hS : ∀ k, ∀ g : A5, ∀ v ∈ S k, permRep facesAct g v ∈ S k),
      DirectSum.IsInternal S ∧
      (∀ k, IsIrredSub (permRep facesAct) (S k)) ∧
      Module.finrank ℂ (S 0) = 1 ∧ Module.finrank ℂ (S 1) = 3 ∧
      Module.finrank ℂ (S 2) = 3 ∧ Module.finrank ℂ (S 3) = 4 ∧
      Module.finrank ℂ (S 4) = 4 ∧ Module.finrank ℂ (S 5) = 5 ∧
      ∃ g : A5, subChar (permRep facesAct) (S 1) (hS 1) g
        ≠ subChar (permRep facesAct) (S 2) (hS 2) g :=
  faces_decomposition facesAct facesAct_transitive facesAct_stab

/-- **Problem 4.12.5(b), edges, unconditionally.** The representation of `A₅` on the space of
complex functions on the `30` edges decomposes as `1 ⊕ 3 ⊕ 3' ⊕ 4² ⊕ 5³`. -/
theorem edges_decomposition_icosahedral :
    ∃ (S : Fin 8 → Submodule ℂ (Fin 30 → ℂ))
      (hS : ∀ k, ∀ g : A5, ∀ v ∈ S k, permRep edgesAct g v ∈ S k),
      DirectSum.IsInternal S ∧
      (∀ k, IsIrredSub (permRep edgesAct) (S k)) ∧
      Module.finrank ℂ (S 0) = 1 ∧ Module.finrank ℂ (S 1) = 3 ∧
      Module.finrank ℂ (S 2) = 3 ∧ Module.finrank ℂ (S 3) = 4 ∧
      Module.finrank ℂ (S 4) = 4 ∧ Module.finrank ℂ (S 5) = 5 ∧
      Module.finrank ℂ (S 6) = 5 ∧ Module.finrank ℂ (S 7) = 5 ∧
      ∃ g : A5, subChar (permRep edgesAct) (S 1) (hS 1) g
        ≠ subChar (permRep edgesAct) (S 2) (hS 2) g :=
  edges_decomposition edgesAct edgesAct_transitive edgesAct_stab

end Icosahedron

end Etingof.Problem4_12_5
