import Mathlib

/-!
# Problem 4.1.4: Irreducible representations of `p`-groups in characteristic `p`

**Problem 4.1.4.** Let `G` be a group of order `pⁿ`. Show that every irreducible
representation of `G` over a field `k` of characteristic `p` is trivial.

Here "trivial" means that every group element acts as the identity operator. Combined
with irreducibility (simplicity), this forces the representation to be one-dimensional:
if the action is trivial then every `k`-subspace is a subrepresentation, so a simple
module must have no proper nonzero subspaces, i.e. dimension one.

## Formalization

We model an irreducible representation as a `Representation k G V` whose associated
`MonoidAlgebra k G`-module `ρ.asModule` is simple. The faithful statement of "trivial"
is that `ρ g` is the identity linear map for every `g : G`.

The key ingredient is the char-`p` fixed-vector theorem: a finite `p`-group acting
`k`-linearly on a nonzero vector space over a field of characteristic `p` has a nonzero
fixed vector. This is proved here (`Etingof.Problem4_1_4.exists_fixed_vector`) by strong
induction on `Nat.card G` using the nontrivial center of a `p`-group: a nontrivial
central element `z` gives a nilpotent operator `ρ z - 1` (since `(ρ z)^{p^j} = 1` and
`(x - 1)^{p^j} = x^{p^j} - 1` in characteristic `p`), whose kernel is a nonzero
subrepresentation on which `z` acts trivially, so the action factors through the smaller
`p`-group `G ⧸ ⟨z⟩`.
-/

namespace Etingof.Problem4_1_4

open Representation MonoidAlgebra

/-- **Char-`p` fixed-vector theorem for `p`-groups.** A finite `p`-group acting
`k`-linearly on a nonzero vector space over a field of characteristic `p` has a nonzero
fixed vector. Proved by strong induction on `Nat.card G`. -/
theorem exists_fixed_vector {p : ℕ} [Fact p.Prime] {k : Type*} [Field k] [CharP k p] :
    ∀ (N : ℕ) {G : Type*} [Group G] [Finite G], IsPGroup p G → Nat.card G = N →
      ∀ {V : Type*} [AddCommGroup V] [Module k V], Nontrivial V →
        ∀ (ρ : Representation k G V), ∃ x : V, x ≠ 0 ∧ ∀ g : G, ρ g x = x := by
  intro N
  induction N using Nat.strong_induction_on with
  | _ N IH =>
    intro G _ _ hG hN V _ _ hVnt ρ
    rcases eq_or_ne (Nat.card G) 1 with hcard1 | hcard1
    · -- `G` is trivial: every element acts as the identity, any nonzero vector works.
      have hsub : Subsingleton G := Nat.card_eq_one_iff_unique.mp hcard1 |>.1
      obtain ⟨x, hx⟩ := exists_ne (0 : V)
      refine ⟨x, hx, fun g => ?_⟩
      rw [Subsingleton.elim g 1, map_one]
      rfl
    · -- `G` is nontrivial, so it has a nontrivial center.
      have hpos : 0 < Nat.card G := Nat.card_pos
      haveI hNtriv : Nontrivial G := by
        rw [← Finite.one_lt_card_iff_nontrivial]
        omega
      haveI : Nontrivial (Subgroup.center G) := IsPGroup.center_nontrivial hG
      obtain ⟨z₀, hz₀⟩ := exists_ne (1 : Subgroup.center G)
      set z : G := (z₀ : G) with hzdef
      have hzcentral : ∀ g : G, g * z = z * g := by
        rw [hzdef]; exact Subgroup.mem_center_iff.mp z₀.2
      have hz1 : z ≠ 1 := by
        rw [hzdef]
        exact fun h => hz₀ (Subtype.ext (h.trans (OneMemClass.coe_one _).symm))
      -- The subgroup generated by `z` is normal (since `z` is central).
      have hSnormal : (Subgroup.zpowers z).Normal := by
        constructor
        intro x hx g
        obtain ⟨n, rfl⟩ := Subgroup.mem_zpowers_iff.mp hx
        have hcomm : Commute (z ^ n) g := Commute.zpow_left (h := (hzcentral g).symm) n
        rw [Subgroup.mem_zpowers_iff]
        exact ⟨n, by rw [← hcomm.eq, mul_assoc, mul_inv_cancel, mul_one]⟩
      set S : Subgroup G := Subgroup.zpowers z with hSdef
      -- `ρ z - 1` is nilpotent: `(ρ z)^{orderOf z} = 1` and `orderOf z = p^j`.
      obtain ⟨j, hj⟩ := (IsPGroup.iff_orderOf.mp hG) z
      -- Characteristic `p` on the endomorphism ring.
      have htorsion : ∃ x : V, Ideal.torsionOf k V x = ⊥ := by
        obtain ⟨x, hx⟩ := exists_ne (0 : V)
        refine ⟨x, ?_⟩
        rw [Submodule.eq_bot_iff]
        intro r hr
        rw [Ideal.mem_torsionOf_iff] at hr
        exact (smul_eq_zero.mp hr).resolve_right hx
      haveI : CharP (Module.End k V) p := Module.charP_end htorsion
      have hσpow : (ρ z) ^ (orderOf z) = 1 := by
        rw [← map_pow, pow_orderOf_eq_one, map_one]
      have hnil : IsNilpotent (ρ z - 1) := by
        refine ⟨p ^ j, ?_⟩
        rw [sub_pow_expChar_pow_of_commute _ _ (Commute.one_right (ρ z)), one_pow, ← hj,
          hσpow, sub_self]
      -- The fixed subspace `W = ker (ρ z - 1)` is nonzero.
      have hWne : LinearMap.ker (ρ z - 1) ≠ ⊥ := by
        intro hbot
        obtain ⟨m, hm⟩ := hnil
        have hbase : Function.Injective ⇑(ρ z - 1) := LinearMap.ker_eq_bot.mp hbot
        have hpow : Function.Injective ⇑(((ρ z - 1) : Module.End k V) ^ m) := by
          rw [Module.End.coe_pow]
          exact hbase.iterate m
        rw [hm] at hpow
        obtain ⟨a, b, hab⟩ := exists_pair_ne V
        exact hab (hpow (a₁ := a) (a₂ := b) (by simp))
      haveI hWnt : Nontrivial (LinearMap.ker (ρ z - 1)) :=
        Submodule.nontrivial_iff_ne_bot.mpr hWne
      -- `W` is `G`-invariant.
      have hle : ∀ g : G, LinearMap.ker (ρ z - 1) ≤
          (LinearMap.ker (ρ z - 1)).comap (ρ g) := by
        intro g w hw
        rw [LinearMap.mem_ker, LinearMap.sub_apply, Module.End.one_apply, sub_eq_zero] at hw
        rw [Submodule.mem_comap, LinearMap.mem_ker, LinearMap.sub_apply, Module.End.one_apply,
          sub_eq_zero, ← Module.End.mul_apply, ← map_mul, ← hzcentral g, map_mul,
          Module.End.mul_apply, hw]
      set ρW : Representation k G (LinearMap.ker (ρ z - 1)) :=
        ρ.subrepresentation _ hle with hρW
      -- `z` (hence `⟨z⟩`) acts trivially on `W`.
      have hztriv : ρW z = 1 := by
        ext w
        have hw2 : ρ z (w : V) = (w : V) := by
          have := LinearMap.mem_ker.mp w.2
          rw [LinearMap.sub_apply, Module.End.one_apply, sub_eq_zero] at this
          exact this
        simpa [hρW, Representation.subrepresentation_apply, LinearMap.coe_restrict_apply]
          using hw2
      haveI : IsTrivial (ρW.comp S.subtype) := by
        refine ⟨fun s => ?_⟩
        have hz_ker : z ∈ (ρW : G →* Module.End k (LinearMap.ker (ρ z - 1))).ker :=
          MonoidHom.mem_ker.mpr hztriv
        exact MonoidHom.mem_ker.mp ((Subgroup.zpowers_le.mpr hz_ker) s.2)
      -- Pass to the quotient `G ⧸ ⟨z⟩`, a smaller `p`-group.
      set ρQ : Representation k (G ⧸ S) (LinearMap.ker (ρ z - 1)) :=
        ρW.ofQuotient S with hρQ
      have hGQ : IsPGroup p (G ⧸ S) := hG.to_quotient S
      have hcardS : 1 < Nat.card S := by
        have hSnt : Nontrivial S := by
          rw [Subgroup.nontrivial_iff_ne_bot, hSdef, Ne, Subgroup.zpowers_eq_bot]
          exact hz1
        exact Finite.one_lt_card_iff_nontrivial.mpr hSnt
      have hcardlt : Nat.card (G ⧸ S) < N := by
        have hmul : Nat.card G = Nat.card (G ⧸ S) * Nat.card S :=
          Subgroup.card_eq_card_quotient_mul_card_subgroup S
        have hqpos : 0 < Nat.card (G ⧸ S) := Nat.card_pos
        rw [← hN, hmul]
        exact (Nat.lt_mul_iff_one_lt_right hqpos).mpr hcardS
      obtain ⟨w, hw_ne, hw_fix⟩ :=
        IH (Nat.card (G ⧸ S)) hcardlt hGQ rfl hWnt ρQ
      -- Push the fixed vector down to `V`.
      refine ⟨(w : V), ?_, fun g => ?_⟩
      · exact fun h => hw_ne (Submodule.coe_eq_zero.mp h)
      · have hfix := hw_fix (g : G ⧸ S)
        rw [hρQ, Representation.ofQuotient_coe_apply] at hfix
        have hval := congrArg (Subtype.val) hfix
        simpa [hρW, Representation.subrepresentation_apply, LinearMap.coe_restrict_apply]
          using hval

/-- **Problem 4.1.4.** If `G` has order `pⁿ` (with `p` prime) and `k` has characteristic
`p`, then every irreducible representation of `G` over `k` is trivial: every group
element acts as the identity. -/
theorem _root_.Etingof.Problem4_1_4 {p n : ℕ} [Fact p.Prime]
    {k : Type*} [Field k] [CharP k p]
    {G : Type*} [Group G] [Fintype G] (hG : Fintype.card G = p ^ n)
    {V : Type*} [AddCommGroup V] [Module k V]
    (ρ : Representation k G V)
    (hV : IsSimpleModule (MonoidAlgebra k G) ρ.asModule) :
    ∀ g : G, ρ g = LinearMap.id := by
  haveI : Nontrivial V := IsSimpleModule.nontrivial (MonoidAlgebra k G) ρ.asModule
  have hGp : IsPGroup p G := IsPGroup.of_card (by rw [Nat.card_eq_fintype_card]; exact hG)
  -- Obtain a nonzero `G`-fixed vector.
  obtain ⟨v, hv0, hvfix⟩ := exists_fixed_vector (Nat.card G) hGp rfl inferInstance ρ
  -- For fixed `v`, the `k[G]`-action `asAlgebraHom r` sends `v` to a `k`-scalar multiple of `v`.
  have key : ∀ r : MonoidAlgebra k G, ∃ c : k, ρ.asAlgebraHom r v = c • v := by
    intro r
    induction r using MonoidAlgebra.induction_on with
    | hM g =>
        refine ⟨1, ?_⟩
        change ρ.asAlgebraHom (single g 1) v = (1 : k) • v
        rw [Representation.asAlgebraHom_single, LinearMap.smul_apply, one_smul, hvfix g, one_smul]
    | hadd f h hf hh =>
        obtain ⟨c1, h1⟩ := hf
        obtain ⟨c2, h2⟩ := hh
        exact ⟨c1 + c2, by rw [map_add, LinearMap.add_apply, h1, h2, add_smul]⟩
    | hsmul s f hf =>
        obtain ⟨c1, h1⟩ := hf
        exact ⟨s * c1, by rw [map_smul, LinearMap.smul_apply, h1, smul_smul]⟩
  -- The `k[G]`-submodule generated by `v` is everything.
  set vM : ρ.asModule := ρ.asModuleEquiv.symm v with hvM
  have hvM0 : vM ≠ 0 := by rw [hvM]; simpa using hv0
  have hspan : Submodule.span (MonoidAlgebra k G) {vM} = ⊤ :=
    IsSimpleModule.span_singleton_eq_top (MonoidAlgebra k G) hvM0
  intro g
  ext w
  have hx : ρ.asModuleEquiv.symm w ∈ Submodule.span (MonoidAlgebra k G) {vM} := by
    rw [hspan]; trivial
  rw [Submodule.mem_span_singleton] at hx
  obtain ⟨r, hr⟩ := hx
  obtain ⟨c, hc⟩ := key r
  -- Transport `r • vM = asModuleEquiv.symm w` through `asModuleEquiv` to land in `V`.
  have hrV : ρ.asAlgebraHom r v = w := by
    have hh := congrArg ρ.asModuleEquiv hr
    rw [Representation.asModuleEquiv_map_smul, hvM] at hh
    simpa using hh
  have hwc : w = c • v := by rw [← hrV, hc]
  rw [LinearMap.id_apply, hwc, map_smul, hvfix g]

end Etingof.Problem4_1_4
