import EtingofRepresentationTheory.Chapter6.Problem6_1_1
import Mathlib

/-!
# Problem 6.1.5, the `−1` strict refinement: scale-invariant images lose a dimension

This file is part of the orbit-counting redirect for the Chapter 6 infinite-type
direction (directive #4777). It supplies the **reusable abstract algebra core** of
the `−1` strict refinement of the orbit-dimension bound (#4824): the strict
analogue of `dim_le_of_injective_comorphism_isLocalization_index`
(`Problem6_1_5_DimBound`).

## The mathematics

The non-strict bound says: an injective `k`-algebra comorphism `k[xσ] → B` into a
domain localization `B` of `k[xτ]` gives `card σ ≤ card τ`, because the images of
the `X s` are `card σ` algebraically independent elements of `K = Frac(k[τ])`,
whose transcendence degree over `k` is `card τ`.

The strict refinement gains **one extra transcendental**. In the orbit picture the
global scalars `k* ⊆ G` act trivially on the representation space `W`, so the orbit
comorphism lands in the *degree-0 part* of `k[G]`: every image coordinate is fixed
by the scaling action `X t ↦ λ • X t`. The distinguished coordinate `g = X t*`
itself is **not** degree 0 — it scales by `λ`. Hence `g` is transcendental over the
subfield generated by the (scale-fixed) image, giving `card σ + 1` algebraically
independent elements and `card σ + 1 ≤ trdeg = card τ`, i.e. `card σ < card τ`.

## The crux (transcendence via the scaling action)

`g` transcendental over `R' = adjoin k (range (f ∘ X))`: suppose
`∑_d c_d g^d = 0` with `c_d ∈ R'`. Each `c_d` is fixed by every scaling
automorphism `scale λ` (it lies in the scale-fixed subalgebra), while `g ↦ λ • g`.
Applying `scale λ` gives `∑_d c_d λ^d g^d = 0` for **every** `λ ∈ kˣ`. The
single-variable polynomial `∑_d (c_d g^d) Y^d ∈ K[Y]` therefore has every nonzero
`λ ∈ k` (embedded in `K`) as a root; over the infinite field `k` that is infinitely
many roots, so the polynomial is `0`, forcing each `c_d g^d = 0` and hence (since
`g ≠ 0` in the field `K`) each `c_d = 0`. So `g` is transcendental.

## What this file provides

* `card_lt_of_scaleInvariant_image`: the abstract core. Given an injective
  `k`-algebra hom `f : k[xσ] → K` into a field `K`, a nonzero `g : K`, a family of
  `k`-algebra automorphisms `scale : kˣ → (K ≃ₐ[k] K)` scaling `g` by `λ` and
  fixing each `f (X s)`, and a transcendence-degree bound `trdeg k K ≤ card τ`,
  the conclusion is the strict inequality `card σ < card τ`.

The consumer (#4824 sub-A) supplies `K = Frac(k[τ])`, `f = ι ∘ orbitComorphism`,
`g = ι (X t*)`, and the scaling automorphism lifted from `X t ↦ λ • X t`; the
degree-0 fact (`scale λ` fixes the image) comes from `k*`-triviality on `W`.
-/

open MvPolynomial Polynomial Cardinal

namespace Etingof.Problem6_1_5

/-- The transcendence degree of `k(τ) = FractionRing (MvPolynomial τ k)` over `k`
is `card τ`, for any finite index type `τ`. This is the `τ`-general companion of
`Etingof.trdeg_fractionRing_mvPolynomial` (phrased over `Fin m`): the fraction
field is algebraic over the polynomial ring, so the tower formula collapses its
transcendence degree to that of `k[τ]`, namely `#τ = card τ`. -/
theorem trdeg_fractionRing_mvPolynomial_card {k : Type} [Field k] (τ : Type) [Fintype τ] :
    Algebra.trdeg k (FractionRing (MvPolynomial τ k)) = (Fintype.card τ : Cardinal) := by
  haveI halg : Algebra.IsAlgebraic (MvPolynomial τ k) (FractionRing (MvPolynomial τ k)) :=
    IsLocalization.isAlgebraic _ (nonZeroDivisors (MvPolynomial τ k))
  have hz : Algebra.trdeg (MvPolynomial τ k) (FractionRing (MvPolynomial τ k)) = 0 :=
    trdeg_eq_zero
  have htower := trdeg_add_eq k (MvPolynomial τ k)
    (A := FractionRing (MvPolynomial τ k))
  rw [hz, add_zero, MvPolynomial.trdeg_of_isDomain, Cardinal.mk_fintype, Cardinal.lift_natCast]
    at htower
  exact htower.symm

/-- **The `−1` strict bound (abstract core).** Let `K` be a field and `k`-algebra
over an infinite field `k`. Suppose

* `f : k[xσ] → K` is an injective `k`-algebra hom (the image coordinates),
* `g : K` is nonzero (the distinguished coordinate `X t*`),
* `scale : kˣ → (K ≃ₐ[k] K)` is a family of `k`-algebra automorphisms with
  `scale μ g = μ • g` (it scales the distinguished coordinate) and
  `scale μ (f (X s)) = f (X s)` for every `s` (it fixes the image: "degree 0"),
* `trdeg k K ≤ card τ`.

Then `card σ < card τ`. The image coordinates together with `g` form `card σ + 1`
algebraically independent elements of `K`, so `card σ + 1 ≤ trdeg k K ≤ card τ`. -/
theorem card_lt_of_scaleInvariant_image
    {k : Type} [Field k] [Infinite k] {σ τ : Type} [Fintype σ] [Fintype τ]
    {K : Type} [Field K] [Algebra k K]
    (f : MvPolynomial σ k →ₐ[k] K) (hf : Function.Injective f)
    (g : K) (hg : g ≠ 0)
    (scale : kˣ → (K ≃ₐ[k] K))
    (hscale_g : ∀ μ : kˣ, scale μ g = (μ : k) • g)
    (hscale_f : ∀ (μ : kˣ) (s : σ), scale μ (f (X s)) = f (X s))
    (htr : Algebra.trdeg k K ≤ (Fintype.card τ : Cardinal)) :
    Fintype.card σ < Fintype.card τ := by
  classical
  -- the image coordinates are algebraically independent
  have hf_indep : AlgebraicIndependent k (fun s : σ => f (X s)) := by
    simpa [Function.comp_def] using (MvPolynomial.algebraicIndependent_X σ k).map' hf
  set x : σ → K := fun s => f (X s) with hx
  set R' : Subalgebra k K := Algebra.adjoin k (Set.range x) with hR'
  -- `scale μ` fixes every element of the subalgebra generated by the image
  have hfix : ∀ (μ : kˣ) {c : K}, c ∈ R' → scale μ c = c := by
    intro μ c hc
    induction hc using Algebra.adjoin_induction with
    | mem y hy => obtain ⟨s, rfl⟩ := hy; exact hscale_f μ s
    | algebraMap r => exact (scale μ).commutes r
    | add a b _ _ iha ihb => rw [map_add, iha, ihb]
    | mul a b _ _ iha ihb => rw [map_mul, iha, ihb]
  -- the inclusion `R' ↪ K` is injective
  have hRinj : Function.Injective (algebraMap (↥R') K) := Subtype.val_injective
  -- **the crux**: `g` is transcendental over `R'`
  have htrans : Transcendental (↥R') g := by
    rw [transcendental_iff]
    intro p hp
    -- push `p` into `K[Y]` along the inclusion
    set pK : K[X] := p.map (algebraMap (↥R') K) with hpK
    -- the scaled single-variable polynomial whose roots we control
    set Q : K[X] := pK.comp (Polynomial.C g * Polynomial.X) with hQ
    -- for every unit `μ`, `algebraMap k K μ` is a root of `Q`
    have hroot : ∀ μ : kˣ, Q.eval (algebraMap k K (μ : k)) = 0 := by
      intro μ
      have hcomp : (scale μ).toRingHom.comp (algebraMap (↥R') K) = algebraMap (↥R') K := by
        ext c
        exact hfix μ (SetLike.coe_mem c)
      -- apply `scale μ` to `aeval g p = 0`
      have hzero : scale μ (aeval g p) = 0 := by rw [hp, map_zero]
      -- rewrite the LHS as `eval (algebraMap k K μ * g) pK`
      have hpush : scale μ (aeval g p)
          = pK.eval ((algebraMap k K (μ : k)) * g) := by
        rw [Polynomial.aeval_def]
        rw [show (scale μ) (Polynomial.eval₂ (algebraMap (↥R') K) g p)
            = (scale μ).toRingHom (Polynomial.eval₂ (algebraMap (↥R') K) g p) from rfl]
        rw [Polynomial.hom_eval₂, hcomp]
        have hg' : (scale μ).toRingHom g = (algebraMap k K (μ : k)) * g := by
          change scale μ g = _
          rw [hscale_g, Algebra.smul_def]
        rw [hg', Polynomial.eval₂_eq_eval_map, ← hpK]
      rw [hzero] at hpush
      -- and `eval (a*g) pK = eval a Q`
      have hQeval : Q.eval (algebraMap k K (μ : k))
          = pK.eval ((algebraMap k K (μ : k)) * g) := by
        rw [hQ, Polynomial.eval_comp, Polynomial.eval_mul, Polynomial.eval_C,
          Polynomial.eval_X, mul_comm]
      rw [hQeval, ← hpush]
    -- `Q` has infinitely many roots, hence is `0`
    have hQ0 : Q = 0 := by
      apply Polynomial.eq_zero_of_infinite_isRoot
      apply Set.infinite_of_injOn_mapsTo (f := algebraMap k K)
        (s := {μ : k | μ ≠ 0}) (t := {z | Q.IsRoot z})
      · exact (algebraMap k K).injective.injOn
      · intro μ hμ
        have := hroot (Units.mk0 μ hμ)
        simpa [Set.mem_setOf_eq, Polynomial.IsRoot.def] using this
      · have : {μ : k | μ ≠ 0} = ({0} : Set k)ᶜ := by ext z; simp
        rw [this]
        exact (Set.finite_singleton (0 : k)).infinite_compl
    -- recover `pK = 0` from `Q = 0` by undoing the invertible substitution
    have hpK0 : pK = 0 := by
      have hback : pK = Q.comp (Polynomial.C g⁻¹ * Polynomial.X) := by
        rw [hQ, Polynomial.comp_assoc]
        have hsub : (Polynomial.C g * Polynomial.X).comp
            (Polynomial.C g⁻¹ * Polynomial.X) = Polynomial.X := by
          rw [Polynomial.mul_comp, Polynomial.C_comp, Polynomial.X_comp, ← mul_assoc,
            ← Polynomial.C_mul, mul_inv_cancel₀ hg, map_one, one_mul]
        rw [hsub, Polynomial.comp_X]
      rw [hback, hQ0, Polynomial.zero_comp]
    -- and `p = 0` from injectivity of the coefficient map
    exact (Polynomial.map_eq_zero_iff hRinj).mp hpK0
  -- assemble: `card σ + 1 ≤ trdeg k K ≤ card τ`
  have hoption : AlgebraicIndependent k (fun o : Option σ => o.elim g x) :=
    (hf_indep.option_iff_transcendental g).mpr htrans
  have hcard : (#(Option σ) : Cardinal) ≤ Algebra.trdeg k K := hoption.cardinalMk_le_trdeg
  rw [Cardinal.mk_option, Cardinal.mk_fintype σ] at hcard
  have hchain : ((Fintype.card σ : Cardinal) + 1) ≤ (Fintype.card τ : Cardinal) :=
    le_trans hcard htr
  have : (Fintype.card σ + 1 : ℕ) ≤ (Fintype.card τ : ℕ) := by
    exact_mod_cast hchain
  omega

/-- **The `−1` strict bound at `K = k(τ)`.** The specialisation of
`card_lt_of_scaleInvariant_image` to the concrete fraction field
`K = FractionRing (MvPolynomial τ k)`, where the transcendence-degree hypothesis
is discharged automatically by `trdeg_fractionRing_mvPolynomial_card`. The
consumer (#4824 sub-A / #4830) supplies only the injective image hom `f`, the
nonzero distinguished coordinate `g`, and the scaling automorphism family with
its two invariance properties (the "degree 0" fact `hscale_f` coming from
`k*`-triviality on the representation space). -/
theorem card_lt_of_scaleInvariant_image_fractionRing
    {k : Type} [Field k] [Infinite k] {σ τ : Type} [Fintype σ] [Fintype τ]
    (f : MvPolynomial σ k →ₐ[k] FractionRing (MvPolynomial τ k))
    (hf : Function.Injective f)
    (g : FractionRing (MvPolynomial τ k)) (hg : g ≠ 0)
    (scale : kˣ → (FractionRing (MvPolynomial τ k) ≃ₐ[k] FractionRing (MvPolynomial τ k)))
    (hscale_g : ∀ μ : kˣ, scale μ g = (μ : k) • g)
    (hscale_f : ∀ (μ : kˣ) (s : σ), scale μ (f (X s)) = f (X s)) :
    Fintype.card σ < Fintype.card τ :=
  card_lt_of_scaleInvariant_image f hf g hg scale hscale_g hscale_f
    (le_of_eq (trdeg_fractionRing_mvPolynomial_card τ))

end Etingof.Problem6_1_5
