import EtingofRepresentationTheory.Chapter6.Problem6_1_5_OrbitInjective
import EtingofRepresentationTheory.Chapter6.Problem6_1_5_DimBound
import EtingofRepresentationTheory.Chapter6.Problem6_1_1
import Mathlib

/-!
# Problem 6.1.5, Step 2(c): the strict dimension bound `dim W(m) < dim G(m)`

This file is part of the orbit-counting redirect for the Chapter 6 infinite-type
direction (directive #4777). It upgrades the **non-strict** bound
`dim W(m) ≤ dim G(m)` of `Problem6_1_5_DimBound` to the **strict** bound
`dim W(m) < dim G(m)` for nonzero `m` — the `−1` refinement that distinguishes
finite type (`q > 0`) from the borderline affine/extended Dynkin diagrams
(`q ≥ 0`), and the genuine remaining geometric crux of the Gabriel forward
direction.

## The `−1` (global scalars act trivially)

The single copy of global scalars `k*` embeds diagonally into
`repGroup k m = ∏ᵢ GL(Fin mᵢ) k` as `λ ↦ (fun i => λ • 1)` and acts **trivially**
on `repSpace m`: on the `i⟶j` block the action is `G_j · x · G_i⁻¹` and the
scalar `λ` cancels (`G_j ↦ λ G_j`, `G_i⁻¹ ↦ λ⁻¹ G_i⁻¹`). Concretely, the
*scaling* `k`-algebra automorphism of `K = k(GIdx m) = FractionRing (k[gₚᵩ])`
that sends each coordinate generator `g ↦ λ·g` (`scalingFieldEquiv`) fixes the
image of the orbit-map comorphism.

## The argument

Let `φ : k[WIdx m] → K` be the (injective) orbit-map comorphism composed into the
fraction field, with image fixed by every `scalingFieldEquiv lam`. Pick any single
group coordinate `g₀ = X t₀` (`GIdx m` is nonempty exactly when `m ≠ 0`). Then `g₀`
is **transcendental over the subfield generated by the image** of `φ`: a polynomial
relation with image-coefficients would, after applying `scalingFieldEquiv lam`
(which fixes the coefficients but sends `g₀ ↦ λ·g₀`), make every `λ·g₀`
(`λ ∈ k*`, infinitely many over an infinite field) a root — forcing the polynomial
to vanish. Adjoining the transcendental `g₀` to the algebraically-independent image
of `φ` keeps algebraic independence (`AlgebraicIndependent.option_iff_transcendental`),
so

`card (WIdx m) + 1 = trdeg k k[WIdx m ⊕ *] ≤ trdeg k K = card (GIdx m)`,

i.e. `card (WIdx m) < card (GIdx m)`.

## What this file provides

* `scalingAlgEquiv` / `scalingFieldEquiv`: the scaling automorphism of `k[τ]` and
  its lift to `K = FractionRing (k[τ])`.
* `Etingof.trdeg_fractionRing_mvPolynomial'`: the index-agnostic transcendence
  degree `trdeg k (FractionRing (k[τ])) = card τ`.
* `card_lt_of_injective_scalingInvariant`: the reusable abstract lemma — an
  injective `k[σ] → K` with scaling-invariant image forces `card σ < card τ`.
* `card_wIdx_lt_card_gIdx` and `repSpace_finrank_lt_repGroup_ambient_finrank`: the
  concrete strict bounds for `W(m)` / `G(m)`, the directly-consumable `hstrict`
  hook for `Etingof.isDynkinDiagram_of_strict_finrank` (`Problem6_1_5_TitsBridge`).
-/

open MvPolynomial Cardinal

namespace Etingof.Problem6_1_5

/-! ## The scaling automorphism -/

variable {k : Type} [Field k]

/-- The **scaling automorphism** of `k[τ]`: each coordinate generator scales,
`X t ↦ λ • X t`. -/
noncomputable def scalingAlgEquiv {τ : Type} (lam : kˣ) :
    MvPolynomial τ k ≃ₐ[k] MvPolynomial τ k :=
  AlgEquiv.ofAlgHom
    (aeval (fun t : τ => (lam : k) • X t))
    (aeval (fun t : τ => ((lam⁻¹ : kˣ) : k) • X t))
    (by
      apply MvPolynomial.algHom_ext; intro t
      simp only [AlgHom.comp_apply, aeval_X, map_smul, AlgHom.id_apply, smul_smul]
      rw [Units.inv_mul, one_smul])
    (by
      apply MvPolynomial.algHom_ext; intro t
      simp only [AlgHom.comp_apply, aeval_X, map_smul, AlgHom.id_apply, smul_smul]
      rw [Units.mul_inv, one_smul])

@[simp]
theorem scalingAlgEquiv_X {τ : Type} (lam : kˣ) (t : τ) :
    scalingAlgEquiv (k := k) lam (X t) = (lam : k) • X t := by
  rw [scalingAlgEquiv, AlgEquiv.ofAlgHom_apply, aeval_X]

/-- The lift of the scaling automorphism to `K = FractionRing (k[τ])`. -/
noncomputable def scalingFieldEquiv (τ : Type) (lam : kˣ) :
    FractionRing (MvPolynomial τ k) ≃ₐ[k] FractionRing (MvPolynomial τ k) :=
  IsFractionRing.algEquivOfAlgEquiv (scalingAlgEquiv (k := k) (τ := τ) lam)

@[simp]
theorem scalingFieldEquiv_g (τ : Type) (lam : kˣ) (t : τ) :
    scalingFieldEquiv (k := k) τ lam
        (algebraMap (MvPolynomial τ k) (FractionRing (MvPolynomial τ k)) (X t))
      = (lam : k) • algebraMap (MvPolynomial τ k) (FractionRing (MvPolynomial τ k)) (X t) := by
  rw [scalingFieldEquiv, IsFractionRing.algEquivOfAlgEquiv_algebraMap, scalingAlgEquiv_X]
  simp only [Algebra.smul_def, map_mul, ← IsScalarTower.algebraMap_apply]

end Etingof.Problem6_1_5

/-! ## Index-agnostic transcendence degree of `k(τ)` -/

namespace Etingof

open Cardinal

variable {k : Type} [Field k]

/-- The transcendence degree of `k(τ) = FractionRing (k[τ])` over `k` is `card τ`,
for any finite index type `τ`. The fraction field is algebraic over the polynomial
ring, so by the tower formula its transcendence degree equals that of `k[τ]`. This
is the index-agnostic version of `trdeg_fractionRing_mvPolynomial`. -/
theorem trdeg_fractionRing_mvPolynomial' (τ : Type) [Fintype τ] :
    Algebra.trdeg k (FractionRing (MvPolynomial τ k)) = (Fintype.card τ : Cardinal) := by
  haveI halg : Algebra.IsAlgebraic (MvPolynomial τ k)
      (FractionRing (MvPolynomial τ k)) :=
    IsLocalization.isAlgebraic _ (nonZeroDivisors (MvPolynomial τ k))
  have hz : Algebra.trdeg (MvPolynomial τ k)
      (FractionRing (MvPolynomial τ k)) = 0 := trdeg_eq_zero
  have htower := trdeg_add_eq k (MvPolynomial τ k)
      (A := FractionRing (MvPolynomial τ k))
  rw [hz, add_zero, MvPolynomial.trdeg_of_isDomain, mk_fintype, lift_natCast] at htower
  exact htower.symm

end Etingof

/-! ## The abstract strict-bound lemma -/

namespace Etingof.Problem6_1_5

open Cardinal

variable {k : Type} [Field k] [Infinite k]

/-- **The reusable strict-bound lemma.** Let `K = FractionRing (k[τ])` (`τ` finite,
with a distinguished generator index `t₀`). An injective `k`-algebra hom
`φ : k[σ] → K` (`σ` finite) whose image is invariant under every scaling
automorphism `scalingFieldEquiv τ lam` forces `card σ < card τ`.

This is the `−1` refinement: the distinguished generator `g₀ = X t₀` is
transcendental over the scaling-fixed image, so it can be adjoined while preserving
algebraic independence, giving `card σ + 1 ≤ trdeg k K = card τ`. -/
theorem card_lt_of_injective_scalingInvariant {σ τ : Type} [Fintype σ] [Fintype τ]
    (t₀ : τ)
    (φ : MvPolynomial σ k →ₐ[k] FractionRing (MvPolynomial τ k))
    (hφ : Function.Injective φ)
    (hfix : ∀ lam : kˣ, ∀ w : σ, scalingFieldEquiv τ lam (φ (X w)) = φ (X w)) :
    Fintype.card σ < Fintype.card τ := by
  classical
  set K := FractionRing (MvPolynomial τ k) with hKdef
  set v : σ → K := fun w => φ (X w) with hvdef
  set g₀ : K := algebraMap (MvPolynomial τ k) K (X t₀) with hg₀def
  -- `g₀ ≠ 0`: the localization map is injective and `X t₀ ≠ 0`.
  have hg₀ne : g₀ ≠ 0 := by
    rw [hg₀def]
    exact (map_ne_zero_iff _ (IsFractionRing.injective (MvPolynomial τ k) K)).mpr
      (MvPolynomial.X_ne_zero t₀)
  -- `v` is algebraically independent: `φ = aeval v` is injective.
  have heqφ : (MvPolynomial.aeval v : MvPolynomial σ k →ₐ[k] K) = φ := by
    apply MvPolynomial.algHom_ext; intro w; rw [aeval_X]
  have halg : AlgebraicIndependent k v := by
    rw [algebraicIndependent_iff_injective_aeval, heqφ]; exact hφ
  -- `g₀` is transcendental over the (scaling-fixed) image `F = adjoin k (range v)`.
  set F := Algebra.adjoin k (Set.range v) with hFdef
  have htrans : Transcendental F g₀ := by
    rw [transcendental_iff]
    intro p hp
    by_contra hpne
    have hFinj : Function.Injective (algebraMap F K) :=
      FaithfulSMul.algebraMap_injective F K
    -- `p.eval₂ (algebraMap F K) g₀ = aeval g₀ p = 0`.
    have hp0 : p.eval₂ (algebraMap F K) g₀ = 0 := by
      rw [← Polynomial.aeval_def]; exact hp
    -- every `λ • g₀` (`λ ∈ k*`) is a root of `p.map (algebraMap F K)`.
    have hroot : ∀ lam : kˣ, (p.map (algebraMap F K)).IsRoot ((lam : k) • g₀) := by
      intro lam
      -- the scaling automorphism fixes `F` pointwise
      have hFfix : ∀ x ∈ F, scalingFieldEquiv τ lam x = x := by
        have hle : F ≤ AlgHom.equalizer (scalingFieldEquiv τ lam).toAlgHom (AlgHom.id k K) := by
          rw [hFdef]
          apply Algebra.adjoin_le
          rintro _ ⟨w, rfl⟩
          simp only [SetLike.mem_coe, AlgHom.mem_equalizer, AlgEquiv.coe_algHom]
          exact hfix lam w
        intro x hx
        have h2 := hle hx
        rw [AlgHom.mem_equalizer] at h2
        simpa using h2
      -- hence it fixes the coefficients of `p`
      have hcompfix :
          ((scalingFieldEquiv τ lam).toAlgHom.toRingHom).comp (algebraMap F K)
            = algebraMap F K := by
        ext y
        rw [RingHom.comp_apply, Subalgebra.algebraMap_apply]
        exact hFfix _ y.2
      -- and sends `g₀ ↦ λ • g₀`
      have heg : scalingFieldEquiv τ lam g₀ = (lam : k) • g₀ := by
        rw [hg₀def]; exact scalingFieldEquiv_g τ lam t₀
      -- push the automorphism through the evaluation
      have hcalc : scalingFieldEquiv τ lam (p.eval₂ (algebraMap F K) g₀)
          = p.eval₂ (algebraMap F K) ((lam : k) • g₀) := by
        have h := Polynomial.hom_eval₂ p (algebraMap F K)
          ((scalingFieldEquiv τ lam).toAlgHom.toRingHom) g₀
        rw [hcompfix] at h
        simp only [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, AlgEquiv.coe_algHom] at h
        rw [heg] at h
        exact h
      rw [hp0, map_zero] at hcalc
      rw [Polynomial.IsRoot, Polynomial.eval_map]
      exact hcalc.symm
    -- infinitely many roots force `p.map (algebraMap F K) = 0`, contradicting `p ≠ 0`.
    have hpKne : p.map (algebraMap F K) ≠ 0 := (Polynomial.map_ne_zero_iff hFinj).mpr hpne
    haveI : Infinite kˣ := by
      have hcinf : Set.Infinite ({0}ᶜ : Set k) :=
        Set.Finite.infinite_compl (Set.finite_singleton 0)
      haveI := hcinf.to_subtype
      exact Infinite.of_injective
        (β := ↥({0}ᶜ : Set k))
        (fun x => Units.mk0 (x : k)
          (by have hx := x.2; rwa [Set.mem_compl_iff, Set.mem_singleton_iff] at hx))
        (fun a b hab => Subtype.ext (by simpa using congrArg Units.val hab))
    have hinj : Function.Injective (fun lam : kˣ => (lam : k) • g₀) := by
      intro a b hab
      simp only [Algebra.smul_def] at hab
      exact Units.ext ((algebraMap k K).injective (mul_right_cancel₀ hg₀ne hab))
    have hinf : Set.Infinite {x : K | (p.map (algebraMap F K)).IsRoot x} :=
      Set.infinite_of_injective_forall_mem hinj (fun lam => hroot lam)
    exact hpKne (Polynomial.eq_zero_of_infinite_isRoot _ hinf)
  -- adjoin the transcendental `g₀`: algebraic independence is preserved.
  have hAI : AlgebraicIndependent k (fun o : Option σ => o.elim g₀ v) :=
    (halg.option_iff_transcendental g₀).mpr htrans
  -- transcendence-degree count: `card σ + 1 ≤ trdeg k K = card τ`.
  have hle : Algebra.trdeg k (MvPolynomial (Option σ) k) ≤ Algebra.trdeg k K :=
    trdeg_le_of_injective (MvPolynomial.aeval (fun o : Option σ => o.elim g₀ v)) hAI
  rw [MvPolynomial.trdeg_of_isDomain, Etingof.trdeg_fractionRing_mvPolynomial',
    Cardinal.mk_option, Cardinal.mk_fintype] at hle
  simp only [Cardinal.lift_add, Cardinal.lift_natCast, Cardinal.lift_one] at hle
  have hlt : (Fintype.card σ : Cardinal) < (Fintype.card τ : Cardinal) :=
    Cardinal.natCast_add_one_le_iff.mp hle
  exact_mod_cast hlt

end Etingof.Problem6_1_5
