import Mathlib.RingTheory.AdjoinRoot
import Mathlib.RingTheory.KrullDimension.Basic
import Mathlib.RingTheory.Jacobson.Semiprimary

/-!
# Example 3.5.6: Radicals of k[x]/(x^n) and Upper Triangular Matrices

1. Let A = k[x]/(xⁿ). This algebra has a unique irreducible representation, which is a
   1-dimensional space k, in which x acts by zero. So Rad(A) is the ideal (x).

2. Let A be the algebra of upper triangular n × n matrices. The irreducible representations
   are Vᵢ, i = 1, …, n, which are 1-dimensional, and any matrix x acts by xᵢᵢ. So Rad(A)
   is the ideal of strictly upper triangular matrices.
-/

open Polynomial

namespace Etingof

section TruncatedPolynomial

variable (k : Type*) [Field k] (n : ℕ)

/-- Evaluation at `0`, viewed as a `k`-algebra map `k[x]/(xⁿ) → k`. This is the character
by which `x` acts as zero: it is the algebra map underlying the unique irreducible
representation of `k[x]/(xⁿ)` in Etingof Example 3.5.6(1). -/
noncomputable def truncPolyResidue (hn : 0 < n) : AdjoinRoot (X ^ n : k[X]) →ₐ[k] k :=
  AdjoinRoot.liftAlgHom _ (AlgHom.id k k) 0 (by simp [eval₂_pow, zero_pow hn.ne'])

/-- The residue character sends the adjoined root to zero. -/
@[simp]
theorem truncPolyResidue_root (hn : 0 < n) :
    truncPolyResidue k n hn (AdjoinRoot.root (X ^ n : k[X])) = 0 :=
  AdjoinRoot.liftAlgHom_root _ _ _ _

/-- On polynomial representatives, the residue character is evaluation at zero. -/
@[simp]
theorem truncPolyResidue_mk (hn : 0 < n) (p : k[X]) :
    truncPolyResidue k n hn (AdjoinRoot.mk (X ^ n : k[X]) p) = p.eval 0 := by
  simp [truncPolyResidue, eval₂_eq_eval_map]

/-- The residue character onto `k` is surjective. -/
theorem truncPolyResidue_surjective (hn : 0 < n) :
    Function.Surjective (truncPolyResidue k n hn) := fun c =>
  ⟨AdjoinRoot.of _ c, by simp [truncPolyResidue]⟩

/-- The kernel of evaluation at `0` is the ideal `(x)`. -/
theorem ker_truncPolyResidue (hn : 0 < n) :
    RingHom.ker (truncPolyResidue k n hn) =
      Ideal.span {AdjoinRoot.root (X ^ n : k[X])} := by
  apply le_antisymm
  · intro a ha
    obtain ⟨p, rfl⟩ := AdjoinRoot.mk_surjective a
    rw [RingHom.mem_ker, truncPolyResidue_mk] at ha
    obtain ⟨q, rfl⟩ := X_dvd_iff.mpr (by simpa [coeff_zero_eq_eval_zero] using ha)
    exact Ideal.mem_span_singleton.mpr ⟨AdjoinRoot.mk _ q, by
      rw [← AdjoinRoot.mk_X, ← map_mul]⟩
  · rw [Ideal.span_le]
    rintro _ rfl
    simp [RingHom.mem_ker]

/-- `(x)` is a maximal ideal of `k[x]/(xⁿ)` — indeed the only one. -/
theorem isMaximal_span_root (hn : 0 < n) :
    (Ideal.span {AdjoinRoot.root (X ^ n : k[X])}).IsMaximal :=
  ker_truncPolyResidue k n hn ▸
    RingHom.ker_isMaximal_of_surjective _ (truncPolyResidue_surjective k n hn)

/-- The radical of k[x]/(xⁿ) is the ideal generated by x.
Etingof Example 3.5.6(1). -/
theorem radical_truncated_polynomial (hn : 0 < n) :
    Ring.jacobson (AdjoinRoot (X ^ n : k[X])) =
      Ideal.span {AdjoinRoot.root (X ^ n : k[X])} := by
  set f := (X ^ n : k[X])
  set A := AdjoinRoot f
  set r := AdjoinRoot.root f
  -- Direction ≥: root is nilpotent → root ∈ nilradical ≤ jacobson
  have hr_nil : IsNilpotent r := ⟨n, by
    change (AdjoinRoot.mk f X) ^ n = 0
    rw [← map_pow, AdjoinRoot.mk_self]⟩
  have h_ge : Ideal.span {r} ≤ Ring.jacobson A := by
    rw [Ideal.span_le]
    intro x hx
    simp only [Set.mem_singleton_iff] at hx
    subst hx
    exact nilradical_le_jacobson A (mem_nilradical.mpr hr_nil)
  -- Direction ≤: Ideal.span {r} is maximal, so jacobson ≤ it
  haveI : (Ideal.span {r}).IsMaximal := isMaximal_span_root k n hn
  exact le_antisymm (Ring.jacobson_le_of_isMaximal (Ideal.span {r})) h_ge

/-! ### The irreducible representation of `k[x]/(xⁿ)`

The book classifies the irreducible representations *before* computing the radical:
`k[x]/(xⁿ)` has a unique irreducible representation, the one-dimensional space `k` on which
`x` acts by zero. -/

/-- The irreducible representation of `k[x]/(xⁿ)`: the quotient by the maximal ideal `(x)`.
It is one-dimensional over `k` (`Etingof.finrank_truncPolySimple`), `x` acts on it by zero
(`Etingof.root_smul_truncPolySimple`), and every irreducible representation is isomorphic to
it (`Etingof.nonempty_linearEquiv_truncPolySimple`). Etingof Example 3.5.6(1). -/
abbrev TruncPolySimple : Type _ :=
  AdjoinRoot (X ^ n : k[X]) ⧸ Ideal.span {AdjoinRoot.root (X ^ n : k[X])}

/-- The irreducible representation of `k[x]/(xⁿ)` is indeed irreducible. -/
theorem isSimpleModule_truncPolySimple (hn : 0 < n) :
    IsSimpleModule (AdjoinRoot (X ^ n : k[X])) (TruncPolySimple k n) :=
  isSimpleModule_iff_isCoatom.mpr (Ideal.isMaximal_def.mp (isMaximal_span_root k n hn))

/-- `x` acts by zero on the irreducible representation of `k[x]/(xⁿ)`. -/
theorem root_smul_truncPolySimple (m : TruncPolySimple k n) :
    AdjoinRoot.root (X ^ n : k[X]) • m = 0 := by
  induction m using Submodule.Quotient.induction_on with
  | H a =>
    exact (Submodule.Quotient.mk_eq_zero _).mpr
      (Ideal.mul_mem_right a _ (Ideal.mem_span_singleton_self _))

/-- The irreducible representation of `k[x]/(xⁿ)` is the one-dimensional space `k`. -/
noncomputable def truncPolySimpleEquiv (hn : 0 < n) : TruncPolySimple k n ≃ₐ[k] k :=
  (Ideal.quotientEquivAlgOfEq k (ker_truncPolyResidue k n hn).symm).trans
    (Ideal.quotientKerAlgEquivOfSurjective (truncPolyResidue_surjective k n hn))

/-- The irreducible representation of `k[x]/(xⁿ)` is one-dimensional. -/
theorem finrank_truncPolySimple (hn : 0 < n) :
    Module.finrank k (TruncPolySimple k n) = 1 := by
  rw [(truncPolySimpleEquiv k n hn).toLinearEquiv.finrank_eq, Module.finrank_self]

/-- **Uniqueness**: every irreducible representation of `k[x]/(xⁿ)` is isomorphic to
`Etingof.TruncPolySimple`. Together with `Etingof.isSimpleModule_truncPolySimple` this is the
classification asserted by Etingof Example 3.5.6(1). -/
theorem nonempty_linearEquiv_truncPolySimple (hn : 0 < n) (M : Type*) [AddCommGroup M]
    [Module (AdjoinRoot (X ^ n : k[X])) M] [IsSimpleModule (AdjoinRoot (X ^ n : k[X])) M] :
    Nonempty (M ≃ₗ[AdjoinRoot (X ^ n : k[X])] TruncPolySimple k n) := by
  obtain ⟨I, hI, ⟨e⟩⟩ := isSimpleModule_iff_quot_maximal.mp ‹_›
  haveI := hI
  have hle : Ideal.span {AdjoinRoot.root (X ^ n : k[X])} ≤ I := by
    rw [← radical_truncated_polynomial k n hn]
    exact Ring.jacobson_le_of_isMaximal I
  exact ⟨e.trans (Submodule.quotEquivOfEq _ _
    ((isMaximal_span_root k n hn).eq_of_le hI.ne_top hle).symm)⟩

end TruncatedPolynomial

end Etingof

section UpperTriangular

/-- The subalgebra of upper triangular matrices in Mₙ(k). -/
def Etingof.upperTriangularSubalgebra (k : Type*) [Field k] (n : ℕ) :
    Subalgebra k (Matrix (Fin n) (Fin n) k) where
  carrier := {M | ∀ i j, j < i → M i j = 0}
  mul_mem' {a b} ha hb i j hij := by
    simp only [Matrix.mul_apply]
    apply Finset.sum_eq_zero
    intro l _
    by_cases hlj : l < i
    · simp [ha i l hlj]
    · push Not at hlj
      simp [hb l j (lt_of_lt_of_le hij hlj)]
  one_mem' i j hij := by
    rw [Matrix.one_apply, if_neg (ne_of_gt hij)]
  add_mem' {a b} ha hb i j hij := by simp [ha i j hij, hb i j hij]
  zero_mem' _ _ _ := by simp
  algebraMap_mem' r i j hij := by
    rw [Algebra.algebraMap_eq_smul_one, Matrix.smul_apply, Matrix.one_apply,
      if_neg (ne_of_gt hij), smul_zero]

/-- The ideal of strictly upper triangular matrices within the upper triangular subalgebra. -/
def Etingof.strictlyUpperTriangularIdeal (k : Type*) [Field k] (n : ℕ) :
    Ideal (↥(Etingof.upperTriangularSubalgebra k n)) where
  carrier := {M | ∀ i j, j ≤ i → (M : Matrix (Fin n) (Fin n) k) i j = 0}
  add_mem' {a b} ha hb i j hij := by simp [ha i j hij, hb i j hij]
  zero_mem' _ _ _ := by simp
  smul_mem' c x hx i j hij := by
    have : (c • x).val = (c : Matrix (Fin n) (Fin n) k) * (x : Matrix (Fin n) (Fin n) k) := rfl
    rw [this, Matrix.mul_apply]
    apply Finset.sum_eq_zero
    intro l _
    by_cases hli : i ≤ l
    · simp [hx l j (le_trans hij hli)]
    · push Not at hli
      simp [c.2 i l hli]

/-- The strictly upper triangular ideal is closed under multiplication on both sides. -/
instance Etingof.strictlyUpperTriangularIdeal.isTwoSided (k : Type*) [Field k] (n : ℕ) :
    (Etingof.strictlyUpperTriangularIdeal k n).IsTwoSided where
  mul_mem_of_left b ha i j hij := by
    have hmul : ∀ (a b : ↥(Etingof.upperTriangularSubalgebra k n)),
        (a * b).val = (a : Matrix (Fin n) (Fin n) k) * (b : Matrix (Fin n) (Fin n) k) :=
      fun _ _ => rfl
    rw [hmul]
    simp only [Matrix.mul_apply]
    apply Finset.sum_eq_zero
    intro l _
    by_cases hli : l ≤ i
    · simp [ha i l hli]
    · push Not at hli
      simp [b.2 l j (lt_of_le_of_lt hij hli)]

/-- The `i`-th diagonal character of the algebra of upper triangular matrices: `x ↦ xᵢᵢ`.
This is the character by which the `i`-th irreducible representation of Etingof
Example 3.5.6(2) is given. -/
def Etingof.diagonalHom (k : Type*) [Field k] (n : ℕ) (i : Fin n) :
    Etingof.upperTriangularSubalgebra k n →ₐ[k] k where
  toFun M := M.val i i
  map_one' := by simp
  map_mul' a b := by
    change (a.1 * b.1) i i = a.1 i i * b.1 i i
    simp only [Matrix.mul_apply]
    apply Finset.sum_eq_single i
    · intro l _ hli
      rcases lt_or_gt_of_ne hli with h | h
      · simp [a.2 i l h]
      · simp [b.2 l i h]
    · intro h; exact absurd (Finset.mem_univ i) h
  map_zero' := by simp
  map_add' a b := by simp
  commutes' c := by
    change (algebraMap k (Matrix (Fin n) (Fin n) k) c) i i = c
    simp [Matrix.algebraMap_matrix_apply]

/-- The diagonal character evaluates a matrix at its `i`-th diagonal entry. -/
@[simp]
theorem Etingof.diagonalHom_apply (k : Type*) [Field k] (n : ℕ) (i : Fin n)
    (M : Etingof.upperTriangularSubalgebra k n) :
    Etingof.diagonalHom k n i M = M.val i i := rfl

/-- Every diagonal character is surjective. -/
theorem Etingof.diagonalHom_surjective (k : Type*) [Field k] (n : ℕ) (i : Fin n) :
    Function.Surjective (Etingof.diagonalHom k n i) := fun c =>
  ⟨algebraMap k _ c, (Etingof.diagonalHom k n i).commutes c⟩

/-- The radical of the algebra of upper triangular n × n matrices is the ideal of strictly
upper triangular matrices. Etingof Example 3.5.6(2). -/
theorem Etingof.radical_upper_triangular (k : Type*) [Field k] (n : ℕ) :
    Ring.jacobson (↥(Etingof.upperTriangularSubalgebra k n)) =
      Etingof.strictlyUpperTriangularIdeal k n := by
  set S := Etingof.upperTriangularSubalgebra k n
  set I := Etingof.strictlyUpperTriangularIdeal k n
  apply le_antisymm
  · -- ≤: jacobson ≤ I (via diagonal extraction homomorphisms)
    intro x hx
    change ∀ i j : Fin n, j ≤ i → (x : Matrix (Fin n) (Fin n) k) i j = 0
    intro i j hij
    rcases hij.eq_or_lt with rfl | hlt
    · -- j = i: show x.val j j = 0 via the diagonal character `S →ₐ[k] k`
      let π : ↥S →+* k := (Etingof.diagonalHom k n j).toRingHom
      haveI : (RingHom.ker π).IsMaximal :=
        RingHom.ker_isMaximal_of_surjective _ (Etingof.diagonalHom_surjective k n j)
      exact Ring.jacobson_le_of_isMaximal (RingHom.ker π) hx
    · -- j < i: upper triangular property
      exact x.2 i j hlt
  · -- ≥: I ≤ jacobson (strictly upper triangular elements are nilpotent)
    -- Helper: elements of I are nilpotent (z^n = 0)
    have nil_of_mem : ∀ z : ↥S, z ∈ I → IsNilpotent z := by
      intro z hz
      refine ⟨n, Subtype.ext ?_⟩
      change ((z ^ n : ↥S) : Matrix (Fin n) (Fin n) k) = 0
      ext p q; simp only [Matrix.zero_apply]
      suffices ∀ (m : ℕ) (p q : Fin n), (q : ℕ) < (p : ℕ) + m →
          ((z ^ m : ↥S) : Matrix (Fin n) (Fin n) k) p q = 0 by
        exact this n p q (by omega)
      intro m; induction m with
      | zero =>
        intro p q h; simp only [pow_zero]
        change (1 : Matrix (Fin n) (Fin n) k) p q = 0
        rw [Matrix.one_apply, if_neg (Fin.ne_of_val_ne (by omega))]
      | succ m ih =>
        intro p q h
        have : ((z ^ (m + 1) : ↥S) : Matrix _ _ k) p q =
            ∑ l, ((z ^ m : ↥S) : Matrix _ _ k) p l * z.val l q := by
          change ((z ^ m).val * z.val) p q = _
          rw [Matrix.mul_apply]
        rw [this]
        apply Finset.sum_eq_zero; intro l _
        by_cases hl : (l : ℕ) < (p : ℕ) + m
        · simp [ih p l hl]
        · push Not at hl; simp [hz l q (show (q : ℕ) ≤ (l : ℕ) by omega)]
    -- x ∈ I → x ∈ every maximal ideal → x ∈ jacobson
    rw [Ring.jacobson_eq_sInf_isMaximal]
    intro x hx
    simp only [Ideal.mem_sInf, Set.mem_setOf_eq]
    intro J hJ
    -- If x ∉ J, then J < J ⊔ Ideal.span {x}, so J ⊔ Ideal.span {x} = ⊤ by maximality.
    -- Then 1 = a + r*x with a ∈ J. Since r*x ∈ I is nilpotent, a = 1-r*x is a unit.
    -- Unit in J → J = ⊤, contradicting maximality.
    by_contra hxJ
    apply hJ.ne_top
    have hlt : J < J ⊔ Ideal.span {x} := by
      refine lt_of_le_of_ne le_sup_left fun heq => hxJ ?_
      exact heq ▸ SetLike.le_def.mp le_sup_right (Ideal.mem_span_singleton_self x)
    have htop := hJ.1.2 _ hlt
    rw [Ideal.eq_top_iff_one] at htop
    obtain ⟨a, ha, b, hb, hab⟩ := Submodule.mem_sup.mp htop
    obtain ⟨r, rfl⟩ := Ideal.mem_span_singleton'.mp hb
    have ha_eq : a = 1 - r * x := (eq_sub_iff_add_eq).mpr hab
    exact J.eq_top_of_isUnit_mem ha (ha_eq ▸ (nil_of_mem _ (I.smul_mem r hx)).isUnit_one_sub)

/-! ### The irreducible representations of the upper triangular algebra

The book classifies the irreducible representations *before* computing the radical: they are
the `n` one-dimensional representations `Vᵢ`, `i = 1, …, n`, on which a matrix `x` acts by the
scalar `xᵢᵢ`. -/

namespace Etingof

variable (k : Type*) [Field k] (n : ℕ)

/-- The `i`-th irreducible representation `Vᵢ` of the algebra of upper triangular matrices:
the one-dimensional space `k` on which a matrix `x` acts by the scalar `xᵢᵢ`.
Etingof Example 3.5.6(2). -/
@[nolint unusedArguments]
def UpperTriangularSimple (_i : Fin n) : Type _ := k

namespace UpperTriangularSimple

variable {k n}

instance (i : Fin n) : AddCommGroup (UpperTriangularSimple k n i) :=
  inferInstanceAs (AddCommGroup k)

/-- Each diagonal-character representation has a nonzero vector. -/
instance (i : Fin n) : Nontrivial (UpperTriangularSimple k n i) :=
  inferInstanceAs (Nontrivial k)

instance (i : Fin n) : Module k (UpperTriangularSimple k n i) :=
  inferInstanceAs (Module k k)

instance (i : Fin n) : Module (upperTriangularSubalgebra k n) (UpperTriangularSimple k n i) :=
  Module.compHom (UpperTriangularSimple k n i) (diagonalHom k n i).toRingHom

/-- A matrix acts on `Vᵢ` by its `i`-th diagonal entry. -/
theorem smul_def (i : Fin n) (s : upperTriangularSubalgebra k n)
    (v : UpperTriangularSimple k n i) :
    s • v = (show k from s.val i i) * (show k from v) := rfl

end UpperTriangularSimple

/-- `Vᵢ` is one-dimensional. -/
theorem finrank_upperTriangularSimple (i : Fin n) :
    Module.finrank k (UpperTriangularSimple k n i) = 1 :=
  Module.finrank_self k

/-- Each `Vᵢ` is irreducible. -/
theorem isSimpleModule_upperTriangularSimple (i : Fin n) :
    IsSimpleModule (upperTriangularSubalgebra k n) (UpperTriangularSimple k n i) := by
  rw [isSimpleModule_iff_toSpanSingleton_surjective]
  refine ⟨inferInstance, fun x hx z => ?_⟩
  have hx' : (show k from x) ≠ 0 := hx
  obtain ⟨s, hs⟩ := diagonalHom_surjective k n i ((show k from z) * (show k from x)⁻¹)
  refine ⟨s, ?_⟩
  change s • x = z
  rw [UpperTriangularSimple.smul_def]
  change s.val i i * (show k from x) = (show k from z)
  rw [show s.val i i = diagonalHom k n i s from rfl, hs]
  field_simp

/-- The diagonal idempotent `Eᵢᵢ`, viewed inside the algebra of upper triangular matrices. -/
def diagIdem (i : Fin n) : upperTriangularSubalgebra k n :=
  ⟨Matrix.single i i 1, fun p q hpq => by
    rw [Matrix.single_apply, if_neg]
    rintro ⟨rfl, rfl⟩
    exact absurd hpq (lt_irrefl _)⟩

/-- The value of a diagonal idempotent in the ambient matrix algebra. -/
@[simp]
theorem diagIdem_val (i : Fin n) :
    (diagIdem k n i).val = Matrix.single i i (1 : k) := rfl

/-- Evaluating a diagonal character on a diagonal idempotent gives a Kronecker delta. -/
theorem diagonalHom_diagIdem (i j : Fin n) :
    diagonalHom k n j (diagIdem k n i) = if j = i then 1 else 0 := by
  rcases eq_or_ne j i with rfl | h
  · simp [diagonalHom_apply]
  · simp [diagonalHom_apply, h, Ne.symm h]

/-- Left multiplication by `Eᵢᵢ` picks out the `i`-th row. -/
theorem single_diag_mul_apply (i : Fin n) (T : Matrix (Fin n) (Fin n) k) (p q : Fin n) :
    (Matrix.single i i (1 : k) * T) p q = if p = i then T i q else 0 := by
  rcases eq_or_ne p i with rfl | hp
  · simp
  · simp [hp]

/-- Right multiplication by `Eᵢᵢ` picks out the `i`-th column. -/
theorem mul_single_diag_apply (i : Fin n) (T : Matrix (Fin n) (Fin n) k) (p q : Fin n) :
    (T * Matrix.single i i (1 : k)) p q = if q = i then T p i else 0 := by
  rcases eq_or_ne q i with rfl | hq
  · simp
  · simp [hq]

/-- **Pairwise non-isomorphic**: `Vᵢ ≇ Vⱼ` for `i ≠ j`, since `Eᵢᵢ` acts as the identity on
`Vᵢ` and as zero on `Vⱼ`. Etingof Example 3.5.6(2). -/
theorem not_nonempty_linearEquiv_upperTriangularSimple {i j : Fin n} (hij : i ≠ j) :
    ¬ Nonempty (UpperTriangularSimple k n i ≃ₗ[upperTriangularSubalgebra k n]
      UpperTriangularSimple k n j) := by
  rintro ⟨e⟩
  let one' : UpperTriangularSimple k n i := (1 : k)
  have hL : diagIdem k n i • one' = one' := by
    rw [UpperTriangularSimple.smul_def]
    change Matrix.single i i (1 : k) i i * (1 : k) = (1 : k)
    simp
  have hR : diagIdem k n i • e one' = 0 := by
    rw [UpperTriangularSimple.smul_def]
    change Matrix.single i i (1 : k) j j * (show k from e one') = 0
    simp [hij]
  have h0 : e one' = 0 := by rw [← hR, ← e.map_smul, hL]
  exact one_ne_zero (α := k) (e.injective (h0.trans (map_zero e).symm))

/-- The diagonal idempotents sum to the identity. -/
theorem sum_diagIdem : ∑ i : Fin n, diagIdem k n i = 1 := by
  refine Subtype.ext ?_
  have hval : ((∑ i : Fin n, diagIdem k n i : upperTriangularSubalgebra k n) :
      Matrix (Fin n) (Fin n) k) = ∑ i : Fin n, Matrix.single i i (1 : k) := by
    push_cast [diagIdem_val]
    rfl
  rw [hval, show ((1 : upperTriangularSubalgebra k n) : Matrix (Fin n) (Fin n) k) = 1 from rfl]
  ext p q
  simp only [Matrix.sum_apply, Matrix.one_apply, Matrix.single_apply]
  rcases eq_or_ne p q with rfl | h
  · rw [if_pos rfl, Finset.sum_eq_single p]
    · simp
    · intro b _ hb; simp [hb]
    · intro hp; exact absurd (Finset.mem_univ p) hp
  · rw [if_neg h]
    exact Finset.sum_eq_zero fun b _ => if_neg (by rintro ⟨rfl, rfl⟩; exact h rfl)

/-- `Eᵢᵢ` commutes with every upper triangular matrix modulo the strictly upper triangular
ideal. This is the key congruence making `m ↦ Eᵢᵢ • m` a module map on any module killed by
the radical. -/
theorem diagIdem_commutator_mem (i : Fin n) (s : upperTriangularSubalgebra k n) :
    diagIdem k n i * s - s * diagIdem k n i ∈ strictlyUpperTriangularIdeal k n := by
  intro p q hqp
  have hval : ((diagIdem k n i * s - s * diagIdem k n i : upperTriangularSubalgebra k n) :
      Matrix (Fin n) (Fin n) k) =
      Matrix.single i i (1 : k) * s.val - s.val * Matrix.single i i (1 : k) := rfl
  rw [hval, Matrix.sub_apply, single_diag_mul_apply, mul_single_diag_apply]
  split_ifs with hp hq hq'
  · rw [hp, hq, sub_self]
  · rw [s.2 i q (lt_of_le_of_ne (hp ▸ hqp) hq), sub_zero]
  · rw [s.2 p i (lt_of_le_of_ne (hq' ▸ hqp) (Ne.symm hp)), sub_zero]
  · rw [sub_zero]

/-- Modulo the strictly upper triangular ideal, `s · Eᵢᵢ` is the scalar `sᵢᵢ` times `Eᵢᵢ`. -/
theorem sub_algebraMap_mul_diagIdem_mem (i : Fin n) (s : upperTriangularSubalgebra k n) :
    (s - algebraMap k _ (diagonalHom k n i s)) * diagIdem k n i ∈
      strictlyUpperTriangularIdeal k n := by
  intro p q hqp
  have hval : (((s - algebraMap k _ (diagonalHom k n i s)) * diagIdem k n i :
      upperTriangularSubalgebra k n) : Matrix (Fin n) (Fin n) k) =
      (s.val - algebraMap k (Matrix (Fin n) (Fin n) k) (s.val i i)) *
        Matrix.single i i (1 : k) := rfl
  rw [hval, mul_single_diag_apply]
  split_ifs with hq
  · rw [Matrix.sub_apply, Matrix.algebraMap_matrix_apply]
    by_cases hp : p = i
    · rw [if_pos hp, hp]; simp
    · rw [if_neg hp, s.2 p i (lt_of_le_of_ne (hq ▸ hqp) (Ne.symm hp)), sub_zero]
  · rfl

section Classification

variable {k n} (M : Type*) [AddCommGroup M] [Module (upperTriangularSubalgebra k n) M]
  [IsSimpleModule (upperTriangularSubalgebra k n) M]

/-- The radical acts by zero on any irreducible representation. -/
theorem strictlyUpperTriangular_smul_eq_zero {z : upperTriangularSubalgebra k n}
    (hz : z ∈ strictlyUpperTriangularIdeal k n) (m : M) : z • m = 0 := by
  have hle : Ring.jacobson (upperTriangularSubalgebra k n) ≤
      Module.annihilator (upperTriangularSubalgebra k n) M :=
    IsSemisimpleModule.jacobson_le_annihilator (upperTriangularSubalgebra k n) M
  exact Module.mem_annihilator.mp (hle (by rwa [radical_upper_triangular])) m

/-- **Exhaustiveness**: every irreducible representation of the algebra of upper triangular
matrices is isomorphic to one of the `n` diagonal characters `Vᵢ`.
Etingof Example 3.5.6(2). -/
theorem exists_linearEquiv_upperTriangularSimple :
    ∃ i : Fin n, Nonempty (M ≃ₗ[upperTriangularSubalgebra k n] UpperTriangularSimple k n i) := by
  haveI : Nontrivial M := IsSimpleModule.nontrivial (upperTriangularSubalgebra k n) M
  obtain ⟨m₀, hm₀⟩ := exists_ne (0 : M)
  -- some diagonal idempotent acts nontrivially on `m₀`
  have hsum : ∑ i : Fin n, diagIdem k n i • m₀ = m₀ := by
    rw [← Finset.sum_smul, sum_diagIdem, one_smul]
  obtain ⟨i, -, hi⟩ : ∃ i ∈ Finset.univ, diagIdem k n i • m₀ ≠ 0 := by
    by_contra h
    push Not at h
    exact hm₀ (by rw [← hsum, Finset.sum_eq_zero h])
  refine ⟨i, ?_⟩
  -- `Eᵢᵢ` acts as an idempotent module endomorphism, hence (being nonzero) as the identity
  let φ : M →ₗ[upperTriangularSubalgebra k n] M :=
    { toFun := fun m => diagIdem k n i • m
      map_add' := fun a b => smul_add _ _ _
      map_smul' := fun s m => by
        have h := strictlyUpperTriangular_smul_eq_zero M (diagIdem_commutator_mem k n i s) m
        rw [sub_smul, sub_eq_zero, mul_smul, mul_smul] at h
        exact h }
  have hidem : diagIdem k n i * diagIdem k n i = diagIdem k n i := by
    refine Subtype.ext ?_
    change Matrix.single i i (1 : k) * Matrix.single i i 1 = Matrix.single i i 1
    simp
  have hker : LinearMap.ker φ = ⊥ := by
    rcases eq_bot_or_eq_top (LinearMap.ker φ) with h | h
    · exact h
    · exact absurd (LinearMap.mem_ker.mp (h ▸ Submodule.mem_top : m₀ ∈ LinearMap.ker φ)) hi
  have hφid : ∀ m : M, diagIdem k n i • m = m := fun m =>
    LinearMap.ker_eq_bot.mp hker (show φ (φ m) = φ m by
      change diagIdem k n i • diagIdem k n i • m = diagIdem k n i • m
      rw [← mul_smul, hidem])
  -- consequently every matrix acts through its `i`-th diagonal entry
  have hact : ∀ (s : upperTriangularSubalgebra k n) (m : M),
      s • m = (algebraMap k (upperTriangularSubalgebra k n) (diagonalHom k n i s)) • m := by
    intro s m
    have h := strictlyUpperTriangular_smul_eq_zero M (sub_algebraMap_mul_diagIdem_mem k n i s) m
    rw [sub_mul, sub_smul, sub_eq_zero, mul_smul, mul_smul, hφid] at h
    exact h
  -- `c ↦ c • m₀` is an isomorphism `Vᵢ ≃ M`
  let g : UpperTriangularSimple k n i →ₗ[upperTriangularSubalgebra k n] M :=
    { toFun := fun c => (algebraMap k (upperTriangularSubalgebra k n) (show k from c)) • m₀
      map_add' := fun a b => by
        change (algebraMap k _ ((show k from a) + (show k from b))) • m₀ = _
        rw [map_add, add_smul]
      map_smul' := fun s c => by
        change (algebraMap k _ (show k from s • c)) • m₀ =
          s • ((algebraMap k _ (show k from c)) • m₀)
        rw [UpperTriangularSimple.smul_def, map_mul, mul_smul]
        exact (hact s _).symm }
  let one' : UpperTriangularSimple k n i := (1 : k)
  have hg1 : g one' = m₀ := by
    change (algebraMap k (upperTriangularSubalgebra k n) (1 : k)) • m₀ = m₀
    rw [map_one, one_smul]
  haveI := isSimpleModule_upperTriangularSimple k n i
  have hinj : Function.Injective g := by
    rcases eq_bot_or_eq_top (LinearMap.ker g) with h | h
    · exact LinearMap.ker_eq_bot.mp h
    · exact absurd (hg1 ▸ LinearMap.mem_ker.mp (h ▸ Submodule.mem_top : one' ∈ LinearMap.ker g))
        hm₀
  have hsurj : Function.Surjective g := by
    rcases eq_bot_or_eq_top (LinearMap.range g) with h | h
    · exact absurd (hg1 ▸ (Submodule.mem_bot _).mp (h ▸ LinearMap.mem_range_self g one')) hm₀
    · exact LinearMap.range_eq_top.mp h
  exact ⟨(LinearEquiv.ofBijective g ⟨hinj, hsurj⟩).symm⟩

end Classification

end Etingof

end UpperTriangular
