import Mathlib.Tactic.NoncommRing
import Mathlib.FieldTheory.PurelyInseparable.Basic
import Mathlib.RingTheory.SimpleModule.WedderburnArtin
import Mathlib.RingTheory.TensorProduct.Pi

/-!
# The Jacobson radical of a tensor product of algebras

The proof of Theorem 3.10.2(ii) in Etingof reduces to finite-dimensional algebras and then
asserts, for `A`, `B` finite dimensional over the (algebraically closed) ground field `k`,

  `Rad(A ⊗ B) = Rad(A) ⊗ B + A ⊗ Rad(B)`,

together with the resulting identification

  `(A ⊗ B)/Rad(A ⊗ B) = (A/Rad(A)) ⊗ (B/Rad(B))`.

This file formalizes both.

## Book statement (Etingof, proof of Theorem 3.10.2)

> Indeed, denote the latter by `J`. Then `J` is a nilpotent ideal in `A ⊗ B`, as `Rad(A)` and
> `Rad(B)` are nilpotent. On the other hand, `(A ⊗ B)/J = (A/Rad(A)) ⊗ (B/Rad(B))`, which is a
> product of two semisimple algebras, hence semisimple. This implies `J ⊃ Rad(A ⊗ B)`.
> Altogether, by Proposition 3.5.3, we see that `J = Rad(A ⊗ B)`.

## Scope

The book's ambient algebras in Theorem 3.10.2 need not be finite dimensional; the proof first
replaces them by their finite-dimensional image algebras (see `Theorem3_10_2.lean`, which takes
a different density/Artinian route to the same theorem). The radical formula proved here is for
finite-dimensional algebras, and the `⊇` inclusion additionally needs semisimplicity of
`(A/Rad A) ⊗ (B/Rad B)`, which is where algebraic closure of `k` enters: over a general field
the tensor product of two semisimple algebras need not be semisimple (e.g.
`ℂ ⊗_ℝ ℂ` is semisimple but `𝔽_p(t^{1/p}) ⊗_{𝔽_p(t)} 𝔽_p(t^{1/p})` is not).

The two inclusions are therefore proved under different hypotheses and packaged separately:

* `Etingof.radTensorSum_le_jacobson` — the easy inclusion, needs only nilpotence of the two
  radicals (so: finite dimensionality, no hypothesis on `k`).
* `Etingof.jacobson_le_radTensorSum` — the hard inclusion, needs `(A/Rad A) ⊗ (B/Rad B)`
  semisimple.
* `Etingof.jacobson_tensorProduct_eq` — the book's identity, over an algebraically closed `k`.

## Main declarations

* `Etingof.radTensorLeft`, `Etingof.radTensorRight` — the ideals `Rad(A) ⊗ B` and `A ⊗ Rad(B)`
  of `A ⊗[k] B`, defined as the ideals generated by the images of the two radicals.
* `Etingof.radTensorSum` — their sum `J`.
* `Etingof.tensorRadQuot` — the surjection `A ⊗ B ↠ (A/Rad A) ⊗ (B/Rad B)`.
* `Etingof.radTensorSum_eq_ker` — `J` is exactly the kernel of that surjection.
* `Etingof.quotientRadTensorSumEquiv` — `(A ⊗ B)/J ≃ₐ[k] (A/Rad A) ⊗ (B/Rad B)`.
* `Etingof.jacobson_tensorProduct_eq` — `Rad(A ⊗ B) = J` for finite-dimensional `A`, `B` over an
  algebraically closed `k`.
* `Etingof.quotientJacobsonTensorEquiv` — the displayed quotient identification
  `(A ⊗ B)/Rad(A ⊗ B) ≃ₐ[k] (A/Rad A) ⊗ (B/Rad B)`.
-/

namespace Etingof

open scoped TensorProduct

section Defs

variable (k A B : Type*) [Field k] [Ring A] [Ring B] [Algebra k A] [Algebra k B]

/-- The canonical surjection `A ⊗ B ↠ (A/Rad A) ⊗ (B/Rad B)`, the tensor product of the two
quotient maps. Its kernel is `Rad(A) ⊗ B + A ⊗ Rad(B)` (`Etingof.radTensorSum_eq_ker`). -/
noncomputable def tensorRadQuot :
    A ⊗[k] B →ₐ[k] (A ⧸ Ring.jacobson A) ⊗[k] (B ⧸ Ring.jacobson B) :=
  Algebra.TensorProduct.map (Ideal.Quotient.mkₐ k (Ring.jacobson A))
    (Ideal.Quotient.mkₐ k (Ring.jacobson B))

/-- The ideal `Rad(A) ⊗ B` of `A ⊗[k] B`: the ideal generated by `{a ⊗ 1 | a ∈ Rad A}`. -/
noncomputable def radTensorLeft : Ideal (A ⊗[k] B) :=
  Ideal.map (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := B))
    (Ring.jacobson A)

/-- The ideal `A ⊗ Rad(B)` of `A ⊗[k] B`: the ideal generated by `{1 ⊗ b | b ∈ Rad B}`. -/
noncomputable def radTensorRight : Ideal (A ⊗[k] B) :=
  Ideal.map (Algebra.TensorProduct.includeRight (R := k) (A := A) (B := B)) (Ring.jacobson B)

/-- The ideal `J = Rad(A) ⊗ B + A ⊗ Rad(B)` of `A ⊗[k] B` appearing in the proof of
Theorem 3.10.2. -/
noncomputable def radTensorSum : Ideal (A ⊗[k] B) :=
  radTensorLeft k A B ⊔ radTensorRight k A B

end Defs

section Basic

variable {k A B : Type*} [Field k] [Ring A] [Ring B] [Algebra k A] [Algebra k B]

@[simp]
theorem tensorRadQuot_tmul (a : A) (b : B) :
    tensorRadQuot k A B (a ⊗ₜ[k] b) =
      (Ideal.Quotient.mk (Ring.jacobson A) a) ⊗ₜ[k] (Ideal.Quotient.mk (Ring.jacobson B) b) :=
  rfl

theorem tensorRadQuot_surjective : Function.Surjective (tensorRadQuot k A B) :=
  Algebra.TensorProduct.map_surjective _ _ Ideal.Quotient.mk_surjective
    Ideal.Quotient.mk_surjective

/-- `J` is exactly the kernel of `A ⊗ B ↠ (A/Rad A) ⊗ (B/Rad B)`. This is the precise form of
the book's `(A ⊗ B)/J = (A/Rad(A)) ⊗ (B/Rad(B))`. -/
theorem radTensorSum_eq_ker :
    radTensorSum k A B = RingHom.ker (tensorRadQuot k A B) := by
  have hA : RingHom.ker (Ideal.Quotient.mkₐ k (Ring.jacobson A)) = Ring.jacobson A :=
    Ideal.mk_ker
  have hB : RingHom.ker (Ideal.Quotient.mkₐ k (Ring.jacobson B)) = Ring.jacobson B :=
    Ideal.mk_ker
  rw [tensorRadQuot, Algebra.TensorProduct.map_ker _ _ Ideal.Quotient.mk_surjective
    Ideal.Quotient.mk_surjective, hA, hB]
  rfl

instance : (radTensorSum k A B).IsTwoSided := by
  rw [radTensorSum_eq_ker]; infer_instance

/-- The book's displayed identification `(A ⊗ B)/J ≅ (A/Rad A) ⊗ (B/Rad B)`. -/
noncomputable def quotientRadTensorSumEquiv :
    ((A ⊗[k] B) ⧸ radTensorSum k A B) ≃ₐ[k]
      (A ⧸ Ring.jacobson A) ⊗[k] (B ⧸ Ring.jacobson B) :=
  (Ideal.quotientEquivAlgOfEq k radTensorSum_eq_ker).trans
    (Ideal.quotientKerAlgEquivOfSurjective tensorRadQuot_surjective)

end Basic

section Nilpotent

/-- **A nilpotent ideal is contained in the Jacobson radical.** Mathlib has this only for
commutative rings (`Ideal.radical_le_jacobson`, `nilradical_le_jacobson`); the argument here is
the usual one and works over any ring: for `x ∈ I` and any `y`, the product `y * x` lies in the
left ideal `I`, hence is nilpotent, so `1 + y * x` is a unit, which is exactly the unit
criterion `Ideal.mem_jacobson_iff` for membership in `Ring.jacobson`. -/
theorem le_jacobson_of_isNilpotent {R : Type*} [Ring R] {I : Ideal R} (h : IsNilpotent I) :
    I ≤ Ring.jacobson R := by
  obtain ⟨n, hn⟩ := h
  intro x hx
  rw [← Ideal.jacobson_bot, Ideal.mem_jacobson_iff]
  intro y
  have hyx : y * x ∈ I := I.mul_mem_left y hx
  have hpow : (y * x) ^ n ∈ I ^ n := Ideal.pow_mem_pow hyx n
  rw [hn] at hpow
  have hnil : IsNilpotent (-(y * x)) :=
    IsNilpotent.neg (⟨n, by simpa using hpow⟩ : IsNilpotent (y * x))
  obtain ⟨u, hu⟩ := IsNilpotent.isUnit_one_sub hnil
  refine ⟨(↑u⁻¹ : R), ?_⟩
  have h1 : (↑u⁻¹ : R) * (1 + y * x) = 1 := by
    rw [show (1 : R) + y * x = (u : R) by rw [hu, sub_neg_eq_add]]
    exact u.inv_mul
  have h2 : (↑u⁻¹ : R) * y * x + (↑u⁻¹ : R) = (↑u⁻¹ : R) * (1 + y * x) := by noncomm_ring
  rw [h2, h1, sub_self]
  exact Ideal.zero_mem _

variable {k A B : Type*} [Field k] [Ring A] [Ring B] [Algebra k A] [Algebra k B]

/-- Embedding an ideal of `A` into `A ⊗ B` along `a ↦ a ⊗ 1` is submultiplicative: the product
of the embedded ideals is contained in the embedding of the product. -/
theorem map_includeLeft_mul_le (I J : Ideal A) :
    Ideal.map (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := B)) I *
        Ideal.map (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := B)) J ≤
      Ideal.map (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := B))
        (I * J) := by
  rw [Ideal.mul_le]
  have key : ∀ x ∈ Ideal.map
      (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := B)) I,
      ∀ y ∈ Ideal.map
        (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := B)) J,
      x * y ∈ Ideal.map
        (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := B)) (I * J) := by
    intro x hx y hy
    have hx' : x ∈ LinearMap.range
        (LinearMap.rTensor B (Submodule.subtype (I.restrictScalars k))) := by
      rw [← Ideal.map_includeLeft_eq]; exact hx
    have hy' : y ∈ LinearMap.range
        (LinearMap.rTensor B (Submodule.subtype (J.restrictScalars k))) := by
      rw [← Ideal.map_includeLeft_eq]; exact hy
    obtain ⟨s, rfl⟩ := hx'
    obtain ⟨t, rfl⟩ := hy'
    clear hx hy
    induction s with
    | zero => simp
    | add s₁ s₂ h₁ h₂ => rw [map_add, add_mul]; exact Ideal.add_mem _ h₁ h₂
    | tmul a b =>
      induction t with
      | zero => simp
      | add t₁ t₂ h₁ h₂ => rw [map_add, mul_add]; exact Ideal.add_mem _ h₁ h₂
      | tmul a' b' =>
        simp only [LinearMap.rTensor_tmul, Submodule.coe_subtype,
          Algebra.TensorProduct.tmul_mul_tmul]
        have hmem : (a : A) * (a' : A) ∈ I * J :=
          Ideal.mul_mem_mul a.2 a'.2
        have : ((a : A) * (a' : A)) ⊗ₜ[k] ((b : B) * b') =
            ((1 : A) ⊗ₜ[k] ((b : B) * b')) *
              (((a : A) * (a' : A)) ⊗ₜ[k] (1 : B)) := by
          simp [Algebra.TensorProduct.tmul_mul_tmul]
        rw [this]
        exact Ideal.mul_mem_left _ _ (Ideal.mem_map_of_mem _ hmem)
  exact key

/-- Powers of the embedded ideal: `(Rad(A) ⊗ B)^n ⊆ (Rad(A)^n) ⊗ B`. -/
theorem map_includeLeft_pow_le (I : Ideal A) (n : ℕ) :
    Ideal.map (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := B)) I ^ n ≤
      Ideal.map (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := B))
        (I ^ n) := by
  induction n with
  | zero =>
    rw [Submodule.pow_zero, Submodule.pow_zero, Ideal.one_eq_top, Ideal.one_eq_top,
      Ideal.map_top]
  | succ n ih =>
    rw [Submodule.pow_succ, Submodule.pow_succ]
    exact le_trans (Ideal.mul_mono ih le_rfl) (map_includeLeft_mul_le _ _)

/-- `Rad(A) ⊗ B` is a nilpotent ideal of `A ⊗ B`, because `Rad(A)` is. -/
theorem isNilpotent_radTensorLeft [FiniteDimensional k A] :
    IsNilpotent (radTensorLeft k A B) := by
  haveI : IsArtinianRing A := IsArtinianRing.of_finite k A
  obtain ⟨n, hn⟩ := IsSemiprimaryRing.isNilpotent (R := A)
  refine ⟨n, le_bot_iff.mp ?_⟩
  refine le_trans (map_includeLeft_pow_le (B := B) (Ring.jacobson A) n) ?_
  rw [show Ring.jacobson A ^ n = ⊥ from hn, Ideal.map_bot]

/-- Mirror image of `Etingof.map_includeLeft_mul_le` for the embedding `b ↦ 1 ⊗ b`. -/
theorem map_includeRight_mul_le (I J : Ideal B) :
    Ideal.map (Algebra.TensorProduct.includeRight (R := k) (A := A) (B := B)) I *
        Ideal.map (Algebra.TensorProduct.includeRight (R := k) (A := A) (B := B)) J ≤
      Ideal.map (Algebra.TensorProduct.includeRight (R := k) (A := A) (B := B)) (I * J) := by
  rw [Ideal.mul_le]
  intro x hx y hy
  have hx' : x ∈ LinearMap.range
      (LinearMap.lTensor A (Submodule.subtype (I.restrictScalars k))) := by
    rw [← Ideal.map_includeRight_eq]; exact hx
  have hy' : y ∈ LinearMap.range
      (LinearMap.lTensor A (Submodule.subtype (J.restrictScalars k))) := by
    rw [← Ideal.map_includeRight_eq]; exact hy
  obtain ⟨s, rfl⟩ := hx'
  obtain ⟨t, rfl⟩ := hy'
  clear hx hy
  induction s with
  | zero => simp
  | add s₁ s₂ h₁ h₂ => rw [map_add, add_mul]; exact Ideal.add_mem _ h₁ h₂
  | tmul a b =>
    induction t with
    | zero => simp
    | add t₁ t₂ h₁ h₂ => rw [map_add, mul_add]; exact Ideal.add_mem _ h₁ h₂
    | tmul a' b' =>
      simp only [LinearMap.lTensor_tmul, Submodule.coe_subtype,
        Algebra.TensorProduct.tmul_mul_tmul]
      have hmem : (b : B) * (b' : B) ∈ I * J := Ideal.mul_mem_mul b.2 b'.2
      have : (a * a') ⊗ₜ[k] ((b : B) * (b' : B)) =
          ((a * a') ⊗ₜ[k] (1 : B)) * ((1 : A) ⊗ₜ[k] ((b : B) * (b' : B))) := by
        simp [Algebra.TensorProduct.tmul_mul_tmul]
      rw [this]
      exact Ideal.mul_mem_left _ _ (Ideal.mem_map_of_mem _ hmem)

/-- Mirror image of `Etingof.map_includeLeft_pow_le`. -/
theorem map_includeRight_pow_le (I : Ideal B) (n : ℕ) :
    Ideal.map (Algebra.TensorProduct.includeRight (R := k) (A := A) (B := B)) I ^ n ≤
      Ideal.map (Algebra.TensorProduct.includeRight (R := k) (A := A) (B := B)) (I ^ n) := by
  induction n with
  | zero =>
    rw [Submodule.pow_zero, Submodule.pow_zero, Ideal.one_eq_top, Ideal.one_eq_top,
      Ideal.map_top]
  | succ n ih =>
    rw [Submodule.pow_succ, Submodule.pow_succ]
    exact le_trans (Ideal.mul_mono ih le_rfl) (map_includeRight_mul_le _ _)

/-- `A ⊗ Rad(B)` is a nilpotent ideal of `A ⊗ B`, because `Rad(B)` is. Same argument as
`Etingof.isNilpotent_radTensorLeft` with the two tensor factors exchanged. -/
theorem isNilpotent_radTensorRight [FiniteDimensional k B] :
    IsNilpotent (radTensorRight k A B) := by
  haveI : IsArtinianRing B := IsArtinianRing.of_finite k B
  obtain ⟨n, hn⟩ := IsSemiprimaryRing.isNilpotent (R := B)
  refine ⟨n, le_bot_iff.mp ?_⟩
  refine le_trans (map_includeRight_pow_le (A := A) (Ring.jacobson B) n) ?_
  rw [show Ring.jacobson B ^ n = ⊥ from hn, Ideal.map_bot]

/-- The easy inclusion `Rad(A) ⊗ B + A ⊗ Rad(B) ⊆ Rad(A ⊗ B)`: each summand is a nilpotent
ideal, so each is contained in the Jacobson radical, hence so is their sum. This is all the
book's nilpotence argument is actually used for. No hypothesis on `k` beyond finite
dimensionality. -/
theorem radTensorSum_le_jacobson [FiniteDimensional k A] [FiniteDimensional k B] :
    radTensorSum k A B ≤ Ring.jacobson (A ⊗[k] B) :=
  sup_le (le_jacobson_of_isNilpotent isNilpotent_radTensorLeft)
    (le_jacobson_of_isNilpotent isNilpotent_radTensorRight)

/-- "`J` is a nilpotent ideal in `A ⊗ B`, as `Rad(A)` and `Rad(B)` are nilpotent."

The book gets this from nilpotence of the two summands directly; here it is cheaper to go
through `Etingof.radTensorSum_le_jacobson` (which is proved summand-by-summand and does *not*
use this lemma, so there is no circularity) and the nilpotence of the Jacobson radical of the
Artinian ring `A ⊗ B`. -/
theorem isNilpotent_radTensorSum [FiniteDimensional k A] [FiniteDimensional k B] :
    IsNilpotent (radTensorSum k A B) := by
  haveI : IsArtinianRing (A ⊗[k] B) := IsArtinianRing.of_finite k (A ⊗[k] B)
  obtain ⟨n, hn⟩ := IsSemiprimaryRing.isNilpotent (R := A ⊗[k] B)
  refine ⟨n, le_bot_iff.mp ?_⟩
  refine le_trans (Ideal.pow_right_mono radTensorSum_le_jacobson n) ?_
  rw [show Ring.jacobson (A ⊗[k] B) ^ n = ⊥ from hn]

end Nilpotent

section Semisimple

variable {k A B : Type*} [Field k] [Ring A] [Ring B] [Algebra k A] [Algebra k B]

/-- The hard inclusion `Rad(A ⊗ B) ⊆ J`: "`(A ⊗ B)/J = (A/Rad A) ⊗ (B/Rad B)`, which is
semisimple. This implies `J ⊃ Rad(A ⊗ B)`." Stated with the semisimplicity as an explicit
hypothesis, since over a general field it can fail. Note that no finiteness is needed here:
all the finiteness is in the other inclusion. -/
theorem jacobson_le_radTensorSum
    (h : IsSemisimpleRing ((A ⧸ Ring.jacobson A) ⊗[k] (B ⧸ Ring.jacobson B))) :
    Ring.jacobson (A ⊗[k] B) ≤ radTensorSum k A B := by
  have hq : IsSemisimpleRing ((A ⊗[k] B) ⧸ radTensorSum k A B) :=
    (quotientRadTensorSumEquiv (k := k) (A := A) (B := B)).symm.toRingEquiv.isSemisimpleRing
  exact Ring.jacobson_le_of_eq_bot (IsSemisimpleRing.jacobson_eq_bot _)

end Semisimple

section AlgClosed

variable {k : Type*} [Field k] [IsAlgClosed k]

/-- Over an algebraically closed field, a finite-dimensional semisimple algebra is a finite
product of matrix algebras over `k` itself: Wedderburn–Artin plus the fact that a
finite-dimensional division algebra over an algebraically closed field is the field. -/
theorem exists_algEquiv_pi_matrix (A : Type*) [Ring A] [Algebra k A] [FiniteDimensional k A]
    [IsSemisimpleRing A] :
    ∃ (n : ℕ) (d : Fin n → ℕ), (∀ i, NeZero (d i)) ∧
      Nonempty (A ≃ₐ[k] ∀ i, Matrix (Fin (d i)) (Fin (d i)) k) := by
  obtain ⟨n, D, d, _, _, hDfin, hd, ⟨e⟩⟩ :=
    IsSemisimpleRing.exists_algEquiv_pi_matrix_divisionRing_finite (R₀ := k) (R := A)
  refine ⟨n, d, hd, ⟨e.trans (AlgEquiv.piCongrRight fun i => ?_)⟩⟩
  haveI := hDfin i
  -- every element of a finite-dimensional division algebra over an algebraically closed field
  -- generates a finite field extension of `k`, hence lies in `k`
  have hbij : Function.Bijective (algebraMap k (D i)) :=
    IsAlgClosed.algebraMap_bijective_of_isIntegral
  exact (AlgEquiv.ofBijective (Algebra.ofId k (D i)) hbij).symm.mapMatrix

/-- **Over an algebraically closed field, the tensor product of two finite-dimensional
semisimple algebras is semisimple.** This is the "product of two semisimple algebras, hence
semisimple" step of the book's proof; it is exactly where algebraic closure is used. -/
theorem isSemisimpleRing_tensorProduct
    (A B : Type*) [Ring A] [Algebra k A] [FiniteDimensional k A] [IsSemisimpleRing A]
    [Ring B] [Algebra k B] [FiniteDimensional k B] [IsSemisimpleRing B] :
    IsSemisimpleRing (A ⊗[k] B) := by
  classical
  obtain ⟨n, d, hd, ⟨eA⟩⟩ := exists_algEquiv_pi_matrix (k := k) A
  obtain ⟨m, c, hc, ⟨eB⟩⟩ := exists_algEquiv_pi_matrix (k := k) B
  -- `(∏ᵢ Mat_{dᵢ}) ⊗ Mat_{cⱼ} ≅ ∏ᵢ (Mat_{cⱼ} ⊗ Mat_{dᵢ}) ≅ ∏ᵢ Mat_{cⱼdᵢ}` — the Kronecker
  -- product is where "matrix algebras over `k` itself" is used.
  haveI model : ∀ (j : Fin m),
      IsSemisimpleRing ((∀ i, Matrix (Fin (d i)) (Fin (d i)) k) ⊗[k]
        Matrix (Fin (c j)) (Fin (c j)) k) := by
    intro j
    haveI : ∀ i, IsSemisimpleRing
        (Matrix (Fin (c j)) (Fin (c j)) k ⊗[k] Matrix (Fin (d i)) (Fin (d i)) k) := fun i =>
      (Matrix.kroneckerAlgEquiv (Fin (c j)) (Fin (d i)) k).symm.toRingEquiv.isSemisimpleRing
    have e1 : (∀ i, Matrix (Fin (d i)) (Fin (d i)) k) ⊗[k]
        Matrix (Fin (c j)) (Fin (c j)) k ≃ₐ[k]
        ∀ i, Matrix (Fin (c j)) (Fin (c j)) k ⊗[k] Matrix (Fin (d i)) (Fin (d i)) k :=
      (Algebra.TensorProduct.comm k _ _).trans (Algebra.TensorProduct.piRight k k _ _)
    exact e1.symm.toRingEquiv.isSemisimpleRing
  haveI : IsSemisimpleRing ((∀ i, Matrix (Fin (d i)) (Fin (d i)) k) ⊗[k]
      (∀ j, Matrix (Fin (c j)) (Fin (c j)) k)) :=
    (Algebra.TensorProduct.piRight k k (∀ i, Matrix (Fin (d i)) (Fin (d i)) k)
      (fun j => Matrix (Fin (c j)) (Fin (c j)) k)).symm.toRingEquiv.isSemisimpleRing
  exact (Algebra.TensorProduct.congr eA eB).symm.toRingEquiv.isSemisimpleRing

end AlgClosed

section Main

variable {k A B : Type*} [Field k] [IsAlgClosed k]
variable [Ring A] [Ring B] [Algebra k A] [Algebra k B]
variable [FiniteDimensional k A] [FiniteDimensional k B]

/-- **The radical of a tensor product** (Etingof, proof of Theorem 3.10.2):
`Rad(A ⊗ B) = Rad(A) ⊗ B + A ⊗ Rad(B)` for finite-dimensional algebras over an algebraically
closed field. -/
theorem jacobson_tensorProduct_eq :
    Ring.jacobson (A ⊗[k] B) = radTensorSum k A B := by
  -- `IsArtinianRing` does not fire from `FiniteDimensional k A` by instance search.
  haveI : IsArtinianRing A := IsArtinianRing.of_finite k A
  haveI : IsArtinianRing B := IsArtinianRing.of_finite k B
  haveI : FiniteDimensional k (A ⧸ Ring.jacobson A) :=
    Module.Finite.of_surjective (Ideal.Quotient.mkₐ k (Ring.jacobson A)).toLinearMap
      Ideal.Quotient.mk_surjective
  haveI : FiniteDimensional k (B ⧸ Ring.jacobson B) :=
    Module.Finite.of_surjective (Ideal.Quotient.mkₐ k (Ring.jacobson B)).toLinearMap
      Ideal.Quotient.mk_surjective
  exact le_antisymm (jacobson_le_radTensorSum (isSemisimpleRing_tensorProduct _ _))
    radTensorSum_le_jacobson

/-- **The displayed quotient identification** (Etingof, proof of Theorem 3.10.2):
`(A ⊗ B)/Rad(A ⊗ B) ≅ (A/Rad A) ⊗ (B/Rad B)`. -/
noncomputable def quotientJacobsonTensorEquiv :
    ((A ⊗[k] B) ⧸ Ring.jacobson (A ⊗[k] B)) ≃ₐ[k]
      (A ⧸ Ring.jacobson A) ⊗[k] (B ⧸ Ring.jacobson B) :=
  (Ideal.quotientEquivAlgOfEq k jacobson_tensorProduct_eq).trans quotientRadTensorSumEquiv

end Main

section ImageAlgebras

/-- If two algebra representations commute, their images act on the same module through the
tensor product of the image algebras.  This packages the module-descent step used in the
opening reduction of the book's proof of Theorem 3.10.2(ii). -/
noncomputable def tensorProductRangeRep
    {k A B M : Type*} [CommSemiring k] [Semiring A] [Semiring B]
    [Algebra k A] [Algebra k B] [AddCommMonoid M] [Module k M]
    (rhoA : A →ₐ[k] Module.End k M) (rhoB : B →ₐ[k] Module.End k M)
    (hcomm : ∀ a b, Commute (rhoA a) (rhoB b)) :
    rhoA.range ⊗[k] rhoB.range →ₐ[k] Module.End k M :=
  Algebra.TensorProduct.lift (Subalgebra.val rhoA.range) (Subalgebra.val rhoB.range) fun x y => by
    obtain ⟨a, ha⟩ := x.property
    obtain ⟨b, hb⟩ := y.property
    change Commute (x : Module.End k M) (y : Module.End k M)
    rw [← ha, ← hb]
    exact hcomm a b

@[simp]
theorem tensorProductRangeRep_tmul
    {k A B M : Type*} [CommSemiring k] [Semiring A] [Semiring B]
    [Algebra k A] [Algebra k B] [AddCommMonoid M] [Module k M]
    (rhoA : A →ₐ[k] Module.End k M) (rhoB : B →ₐ[k] Module.End k M)
    (hcomm : ∀ a b, Commute (rhoA a) (rhoB b)) (a : A) (b : B) :
    tensorProductRangeRep rhoA rhoB hcomm (rhoA.rangeRestrict a ⊗ₜ[k] rhoB.rangeRestrict b) =
      rhoA a * rhoB b := by
  exact Algebra.TensorProduct.lift_tmul _ _ _ _ _

/-- The induced module structure on `M` over the tensor product of the two image algebras. -/
@[reducible]
noncomputable def tensorProductRangeModule
    {k A B M : Type*} [CommSemiring k] [Semiring A] [Semiring B]
    [Algebra k A] [Algebra k B] [AddCommMonoid M] [Module k M]
    (rhoA : A →ₐ[k] Module.End k M) (rhoB : B →ₐ[k] Module.End k M)
    (hcomm : ∀ a b, Commute (rhoA a) (rhoB b)) :
    Module (rhoA.range ⊗[k] rhoB.range) M :=
  Module.compHom M (tensorProductRangeRep rhoA rhoB hcomm).toRingHom

variable (k : Type*) (A B M : Type*) [Field k] [IsAlgClosed k]
variable [Ring A] [Algebra k A] [Ring B] [Algebra k B]
variable [AddCommGroup M] [Module k M] [FiniteDimensional k M]
variable [Module A M] [IsScalarTower k A M] [Module B M] [IsScalarTower k B M]

/-- **The radical formula in the situation Theorem 3.10.2 actually uses it.**

The book's proof of part (ii) opens with the image-algebra reduction: "Let `A'`, `B'` be the
images of `A`, `B` in `End M`. Then `A'`, `B'` are finite dimensional algebras, and `M` is a
representation of `A' ⊗ B'`, so we may assume without loss of generality that `A` and `B` are
finite dimensional." Applying `Etingof.jacobson_tensorProduct_eq` to those images gives the
radical formula with **no** finiteness hypothesis on `A` or `B` themselves — only on the
module `M`, which is exactly the hypothesis Theorem 3.10.2 carries.

`EtingofRepresentationTheory/Chapter3/Theorem3_10_2.lean` proves the theorem itself by a
different density/Artinian route, so this is a parallel formalization of the book's own
argument rather than a lemma that route consumes. -/
theorem jacobson_tensorProduct_range_eq :
    Ring.jacobson
        (↥(Algebra.lsmul k k M : A →ₐ[k] Module.End k M).range ⊗[k]
          ↥(Algebra.lsmul k k M : B →ₐ[k] Module.End k M).range) =
      radTensorSum k _ _ :=
  jacobson_tensorProduct_eq

end ImageAlgebras

end Etingof
