import EtingofRepresentationTheory.Chapter9.PathAlgebraProjectiveCover
import EtingofRepresentationTheory.Chapter9.PathAlgebraLowerBound
import EtingofRepresentationTheory.Chapter9.Problem9_4_6
import EtingofRepresentationTheory.Chapter9.Definition9_2_2
import Mathlib.LinearAlgebra.Projection
import Mathlib.LinearAlgebra.Finsupp.Pi
import Mathlib.RingTheory.SimpleModule.Basic
import Mathlib.LinearAlgebra.FiniteDimensional.Basic

import Mathlib.Tactic.LinearCombination

set_option backward.isDefEq.respectTransparency false

/-!
# The vertex simple modules and their projective covers

For the path algebra `A = PathAlgebra k Q` of a finite quiver, the vertex simple module at a
vertex `i` is the one-dimensional module `Sᵢ = augModule k Q i`, on which `a ∈ A` acts by its
augmentation `ε_i(a)`, the coefficient of the trivial path `eᵢ`. This file proves that the
principal left ideals `Pᵢ = A · eᵢ` are the projective covers of the `Sᵢ`:

* `Sᵢ` is a simple `A`-module, and for acyclic `Q` the `Sᵢ` are pairwise non-isomorphic and
  exhaust the simple modules, so the vertices index the simple modules exactly;
* `Pᵢ` is projective, being a direct summand of `A` cut out by the idempotent `eᵢ`;
* `Pᵢ` is indecomposable when `Q` is acyclic, because `End_A(Pᵢ) ≅ (paths i → i) →₀ k` is then
  one-dimensional over `k`, so its only idempotents are `0` and the identity;
* the augmentation `π : Pᵢ → Sᵢ` is a surjection with superfluous kernel.

Acyclicity enters twice, both times through the fact that the only path from `i` to itself is
the trivial one: it makes `eᵢ A eᵢ` the line spanned by `eᵢ`, which gives both the
one-dimensionality of `End_A(Pᵢ)` and the essentiality of `π`.

Packaging this data as `Etingof.ProjectiveCover` certifies the family
`Etingof.PathAlgebra.pathAlgebraProj k Q` used in Problem 9.4.6 (ii): the matrix computed there
is the Cartan matrix of `A` in the sense of Definition 9.3.1, not merely a matrix of Hom-space
dimensions for an arbitrary family of modules.

## Main results

* `Etingof.PathAlgebra.augModule_isSimpleModule`: `Sᵢ` is simple.
* `Etingof.PathAlgebra.pathAlgebraProj_projective`: `Pᵢ` is projective.
* `Etingof.PathAlgebra.pathAlgebraProj_isIndecomposable`: `Pᵢ` is indecomposable for acyclic `Q`.
* `Etingof.PathAlgebra.projToSimple_essential`: the kernel of `π` is superfluous.
* `Etingof.PathAlgebra.vertexProjectiveCover`: the projective cover `Pᵢ ↠ Sᵢ`.
* `Etingof.PathAlgebra.exists_augModule_iso`: every simple module is some `Sᵢ`.
* `Etingof.PathAlgebra.augModule_not_isomorphic_of_ne`: distinct vertices give non-isomorphic
  simple modules.
* `Etingof.Problem946.cartanMatrix_pathAlgebra_eq_pathCount_of_projectiveCovers`: the matrix of
  Problem 9.4.6 (ii) is the Cartan matrix of `A` in the sense of Definition 9.3.1.
-/

universe u w

open Etingof

namespace Etingof.PathAlgebra

variable {k : Type u} {Q : Type u} [Field k] [Quiver.{u + 1} Q] [DecidableEq Q] [Fintype Q]

/-! ## The augmentation on the trivial-path idempotents -/

/-- The augmentation at `i` sends the trivial-path idempotent `eᵢ` to `1`. -/
theorem augHom_eIdem (i : Q) : augHom i (eIdem (k := k) i) = 1 := by
  rw [eIdem, ofPath, augHom_apply, coeffAt_single, if_pos rfl]

/-- The augmentation at `i` restricts to the identity on scalars. -/
theorem augHom_algebraMap (i : Q) (c : k) :
    augHom i (algebraMap k (PathAlgebra k Q) c) = c := by
  rw [Algebra.algebraMap_eq_smul_one, augHom_apply, map_smul, ← augHom_apply, map_one,
    smul_eq_mul, mul_one]

/-- The trivial-path idempotent is nonzero: its coefficient at the trivial path is `1`. -/
theorem eIdem_ne_zero (i : Q) : (eIdem i : PathAlgebra k Q) ≠ 0 := by
  intro h
  have h1 : augHom i (eIdem (k := k) i) = 1 := augHom_eIdem i
  rw [h, map_zero] at h1
  exact zero_ne_one h1

/-- The generator of `Pᵢ = A · eᵢ` is nonzero. -/
theorem eIdemMem_ne_zero (i : Q) : (eIdemMem k Q i : pathAlgebraProj k Q i) ≠ 0 := fun h =>
  eIdem_ne_zero i (congrArg Subtype.val h)

instance (i : Q) : Nontrivial (pathAlgebraProj k Q i) :=
  ⟨⟨eIdemMem k Q i, 0, eIdemMem_ne_zero i⟩⟩

/-- `Pᵢ = A · eᵢ` is generated by `eᵢ`. -/
theorem span_eIdemMem_eq_top (i : Q) :
    Submodule.span (PathAlgebra k Q) {eIdemMem k Q i} = ⊤ := by
  refine eq_top_iff.mpr fun y _ => ?_
  obtain ⟨a, ha⟩ := Submodule.mem_span_singleton.mp y.2
  exact Submodule.mem_span_singleton.mpr ⟨a, Subtype.ext ha⟩

/-! ## Simplicity of the vertex simple modules -/

instance (i : Q) : Nontrivial (augModule k Q i) :=
  inferInstanceAs (Nontrivial (ULift.{u + 1} k))

/-- **The vertex simple module.** `Sᵢ = augModule k Q i` is a simple `A`-module: it is
one-dimensional over `k`, and the `k`-action is obtained from the `A`-action by restricting
along `algebraMap k A`. -/
theorem augModule_isSimpleModule (i : Q) :
    IsSimpleModule (PathAlgebra k Q) (augModule k Q i) := by
  refine { exists_pair_ne := exists_pair_ne _, eq_bot_or_eq_top := fun N => ?_ }
  rcases eq_or_ne N ⊥ with h | h
  · exact Or.inl h
  refine Or.inr (eq_top_iff.mpr fun w _ => ?_)
  obtain ⟨v, hvN, hv⟩ := (Submodule.ne_bot_iff N).mp h
  have hvd : (v : augModule k Q i).down ≠ 0 := fun hc => hv (by apply ULift.ext; exact hc)
  have hw : (algebraMap k (PathAlgebra k Q) (w.down / v.down)) • v = w := by
    apply ULift.ext
    rw [augModule_down_smul, augHom_algebraMap, div_mul_cancel₀ _ hvd]
  exact hw ▸ N.smul_mem _ hvN

/-! ## Projectivity of `Pᵢ = A · eᵢ`

`eᵢ` is idempotent, so right multiplication by `eᵢ` retracts `A` onto `A · eᵢ`. A retract of a
free module is projective. -/

/-- Right multiplication by `eᵢ`, corestricted to `Pᵢ = A · eᵢ`. It is a retraction of the
inclusion `Pᵢ ↪ A`. -/
noncomputable def projSection (i : Q) :
    PathAlgebra k Q →ₗ[PathAlgebra k Q] pathAlgebraProj k Q i :=
  LinearMap.codRestrict (Submodule.span (PathAlgebra k Q) {eIdem (k := k) i})
    (LinearMap.mulRight (PathAlgebra k Q) (eIdem i))
    (fun a => Submodule.mem_span_singleton.mpr ⟨a, by rw [smul_eq_mul]; rfl⟩)

@[simp] theorem projSection_apply_val (i : Q) (a : PathAlgebra k Q) :
    ((projSection i a : pathAlgebraProj k Q i) : PathAlgebra k Q) = a * eIdem i := rfl

/-- **`Pᵢ = A · eᵢ` is projective**, being the image of the idempotent right multiplication by
`eᵢ`, hence a direct summand of the free module `A`. -/
instance pathAlgebraProj_projective (i : Q) :
    Module.Projective (PathAlgebra k Q) (pathAlgebraProj k Q i) :=
  Module.Projective.of_split
    (Submodule.span (PathAlgebra k Q) {eIdem (k := k) i}).subtype (projSection i)
    (LinearMap.ext fun y => Subtype.ext (mul_eIdem_of_mem_span y.2))

/-! ## Indecomposability of `Pᵢ` over an acyclic quiver -/

omit [DecidableEq Q] [Fintype Q] in
/-- In an acyclic quiver the only path from a vertex to itself is the trivial one. -/
theorem subsingleton_path_self
    (hacyclic : ∀ (v : Q) (p : Quiver.Path v v), p = Quiver.Path.nil) (i : Q) :
    Subsingleton (Quiver.Path i i) :=
  ⟨fun p q => by rw [hacyclic i p, hacyclic i q]⟩

/-- For an acyclic quiver, `End_A(Pᵢ) ≅ eᵢ A eᵢ` is the line spanned by `eᵢ`, so it is
one-dimensional over `k`. -/
theorem finrank_end_pathAlgebraProj
    (hacyclic : ∀ (v : Q) (p : Quiver.Path v v), p = Quiver.Path.nil) (i : Q) :
    Module.finrank k
        (pathAlgebraProj k Q i →ₗ[PathAlgebra k Q] pathAlgebraProj k Q i) = 1 := by
  haveI := subsingleton_path_self hacyclic i
  rw [(pathAlgebraHomEquiv k Q i i).finrank_eq,
    (Finsupp.uniqueLinearEquiv k k (Quiver.Path.nil : Quiver.Path i i)).finrank_eq,
    Module.finrank_self]

/-- The identity endomorphism of `Pᵢ` is nonzero. -/
theorem id_ne_zero (i : Q) :
    (LinearMap.id : pathAlgebraProj k Q i →ₗ[PathAlgebra k Q] pathAlgebraProj k Q i) ≠ 0 := by
  intro h
  exact eIdemMem_ne_zero i (by simpa using congrArg (fun f => f (eIdemMem k Q i)) h)

/-- **`Pᵢ = A · eᵢ` is indecomposable** for an acyclic quiver. Any decomposition
`Pᵢ = W₁ ⊕ W₂` produces an idempotent endomorphism, but `End_A(Pᵢ)` is the one-dimensional
`k`-algebra spanned by the identity, whose only idempotents are `0` and the identity. -/
theorem pathAlgebraProj_isIndecomposable
    (hacyclic : ∀ (v : Q) (p : Quiver.Path v v), p = Quiver.Path.nil) (i : Q) :
    Etingof.IsIndecomposable (PathAlgebra k Q) (pathAlgebraProj k Q i) := by
  refine ⟨inferInstance, fun W₁ W₂ hc => ?_⟩
  set P := W₁.projection W₂ hc with hPdef
  obtain ⟨c, hcP⟩ :=
    (finrank_eq_one_iff_of_nonzero' (LinearMap.id :
        pathAlgebraProj k Q i →ₗ[PathAlgebra k Q] pathAlgebraProj k Q i)
      (id_ne_zero i)).mp (finrank_end_pathAlgebraProj hacyclic i) P
  -- `P` is idempotent, so `c` is an idempotent scalar, hence `0` or `1`.
  have hidem : ∀ x, P (P x) = P x := fun x =>
    Submodule.projection_apply_of_mem_left hc (Submodule.projection_apply_mem hc x)
  have hc2 : (c * c) • (LinearMap.id :
      pathAlgebraProj k Q i →ₗ[PathAlgebra k Q] pathAlgebraProj k Q i)
      = c • LinearMap.id := by
    refine LinearMap.ext fun x => ?_
    have hx := hidem x
    rw [← hcP] at hx
    simpa [mul_smul] using hx
  have hcc : c * c = c := by
    have h0 : (c * c - c) • (LinearMap.id :
        pathAlgebraProj k Q i →ₗ[PathAlgebra k Q] pathAlgebraProj k Q i) = 0 := by
      exact (sub_smul (c * c) c (LinearMap.id :
        pathAlgebraProj k Q i →ₗ[PathAlgebra k Q] pathAlgebraProj k Q i)).trans
          (sub_eq_zero.mpr hc2)
    rcases smul_eq_zero.mp h0 with h | h
    · exact sub_eq_zero.mp h
    · exact absurd h (id_ne_zero i)
  rcases mul_eq_zero.mp (show c * (c - 1) = 0 by linear_combination hcc) with h | h
  · -- `P = 0`, so `W₁ = ⊥`.
    left
    refine eq_bot_iff.mpr fun x hx => ?_
    rw [Submodule.mem_bot]
    have hx1 : P x = x := Submodule.projection_apply_of_mem_left hc hx
    rw [← hx1, ← hcP, h, zero_smul, LinearMap.zero_apply]
  · -- `P = id`, so `W₂ = ⊥`.
    right
    have hc1 : c = 1 := sub_eq_zero.mp h
    refine eq_bot_iff.mpr fun x hx => ?_
    rw [Submodule.mem_bot]
    have hx1 : P x = 0 := Submodule.projection_apply_of_mem_right hc hx
    rw [← hcP, hc1, one_smul, LinearMap.id_apply] at hx1
    exact hx1

/-! ## The projective cover map `Pᵢ ↠ Sᵢ` -/

/-- The augmentation `π : Pᵢ → Sᵢ`, sending `y ∈ A · eᵢ` to its coefficient at the trivial
path `eᵢ`. -/
noncomputable def projToSimple (i : Q) :
    pathAlgebraProj k Q i →ₗ[PathAlgebra k Q] augModule k Q i where
  toFun y := ULift.up (augHom i (y : PathAlgebra k Q))
  map_add' y z := by apply ULift.ext; exact map_add (augHom i) _ _
  map_smul' a y := by
    apply ULift.ext
    rw [augModule_down_smul]
    exact map_mul (augHom i) a (y : PathAlgebra k Q)

@[simp] theorem projToSimple_apply_down (i : Q) (y : pathAlgebraProj k Q i) :
    (projToSimple i y).down = augHom i (y : PathAlgebra k Q) := rfl

theorem projToSimple_eIdemMem (i : Q) :
    projToSimple i (eIdemMem k Q i) = augGen (k := k) (Q := Q) i := by
  apply ULift.ext
  rw [projToSimple_apply_down, eIdemMem_val, augHom_eIdem, augGen_down]

theorem projToSimple_surjective (i : Q) :
    Function.Surjective (projToSimple (k := k) (Q := Q) i) := by
  intro w
  refine ⟨(algebraMap k (PathAlgebra k Q) w.down) • eIdemMem k Q i, ?_⟩
  apply ULift.ext
  rw [projToSimple_apply_down, Submodule.coe_smul, eIdemMem_val, smul_eq_mul, map_mul,
    augHom_eIdem, mul_one, augHom_algebraMap]

/-- **The augmentation is a left inverse on `eᵢ`.** In an acyclic quiver, if `n ∈ A · eᵢ` has
augmentation `1` at `i`, then `eᵢ n = eᵢ`. This is where acyclicity does its work: the two-sided
cut `eᵢ A eᵢ` is spanned by the trivial path alone, so `eᵢ n` is determined by its single
coefficient there. -/
theorem eIdem_mul_eq_self_of_augHom_eq_one
    (hacyclic : ∀ (v : Q) (p : Quiver.Path v v), p = Quiver.Path.nil) {i : Q}
    {n : PathAlgebra k Q} (hn : n ∈ Submodule.span (PathAlgebra k Q) {eIdem (k := k) i})
    (haug : augHom i n = 1) :
    eIdem i * n = eIdem i := by
  obtain ⟨a, rfl⟩ := Submodule.mem_span_singleton.mp hn
  rw [smul_eq_mul] at haug ⊢
  refine coeff_ext fun x => ?_
  by_cases hx : x = (⟨i, i, Quiver.Path.nil⟩ : QuiverPathIndex Q)
  · subst hx
    rw [coeff_eIdem_mul, if_pos rfl, eIdem, ofPath, coeff_single, if_pos rfl]
    exact haug
  · -- Off the trivial path, both sides vanish: `eᵢ a eᵢ` is supported on paths `i → i`, and
    -- acyclicity leaves only the trivial one.
    have hcut : eIdem i * (a * eIdem i) ∈ eCut k Q i i :=
      mem_eCut_iff.mpr ⟨a, by rw [mul_assoc]⟩
    rw [coeff_eq_zero_of_mem_eCut hcut ?_, eIdem, ofPath, coeff_single, if_neg (Ne.symm hx)]
    rintro ⟨h1, h2⟩
    refine hx ?_
    obtain ⟨s, t, p⟩ := x
    cases h1
    cases h2
    rw [hacyclic _ p]

/-- **The kernel of `π` is superfluous.** If a submodule `N` of `Pᵢ` together with `ker π`
spans `Pᵢ`, then `N = Pᵢ`: writing `eᵢ = n + r` with `n ∈ N` and `r ∈ ker π`, the element `n`
has augmentation `1`, so `eᵢ n = eᵢ` puts the generator `eᵢ` back inside `N`. -/
theorem projToSimple_essential
    (hacyclic : ∀ (v : Q) (p : Quiver.Path v v), p = Quiver.Path.nil) (i : Q)
    (N : Submodule (PathAlgebra k Q) (pathAlgebraProj k Q i))
    (hN : N ⊔ LinearMap.ker (projToSimple i) = ⊤) : N = ⊤ := by
  have hmem : eIdemMem k Q i ∈ N ⊔ LinearMap.ker (projToSimple (k := k) (Q := Q) i) := by
    rw [hN]; exact Submodule.mem_top
  obtain ⟨n, hn, r, hr, hnr⟩ := Submodule.mem_sup.mp hmem
  -- The `N`-component of `eᵢ` has augmentation `1`.
  have haug : augHom i (n : PathAlgebra k Q) = 1 := by
    have h1 : projToSimple i n + projToSimple i r = augGen (k := k) (Q := Q) i := by
      rw [← map_add, hnr, projToSimple_eIdemMem]
    rw [LinearMap.mem_ker.mp hr, add_zero] at h1
    simpa using congrArg ULift.down h1
  -- Hence `eᵢ • n = eᵢ`, so the generator lies in `N`.
  have hgen : (eIdem i : PathAlgebra k Q) • n = eIdemMem k Q i :=
    Subtype.ext (eIdem_mul_eq_self_of_augHom_eq_one hacyclic n.2 haug)
  have : eIdemMem k Q i ∈ N := hgen ▸ N.smul_mem _ hn
  rw [eq_top_iff, ← span_eIdemMem_eq_top i, Submodule.span_le, Set.singleton_subset_iff]
  exact this

/-- **The projective cover of the vertex simple module** `Sᵢ` of the path algebra of a finite
acyclic quiver: the principal left ideal `Pᵢ = A · eᵢ`, with the augmentation `π : Pᵢ ↠ Sᵢ`. -/
noncomputable def vertexProjectiveCover
    (hacyclic : ∀ (v : Q) (p : Quiver.Path v v), p = Quiver.Path.nil) (i : Q) :
    Etingof.ProjectiveCover (PathAlgebra k Q) (augModule k Q i) where
  P := pathAlgebraProj k Q i
  indecomposable := pathAlgebraProj_isIndecomposable hacyclic i
  surjection := projToSimple i
  surjection_surjective := projToSimple_surjective i
  surjection_essential := projToSimple_essential hacyclic i

/-! ## The vertex simple modules exhaust the simple modules -/

/-- The trivial-path idempotents sum to the unit of the path algebra. -/
theorem sum_eIdem_eq_one : (∑ i : Q, (eIdem i : PathAlgebra k Q)) = 1 :=
  sum_trivialPaths_eq_one k Q

/-- The augmentation at `j` kills the trivial-path idempotent at any other vertex. -/
theorem augHom_eIdem_of_ne {i j : Q} (h : i ≠ j) : augHom j (eIdem (k := k) i) = 0 := by
  rw [eIdem, ofPath, augHom_apply, coeffAt_single, if_neg]
  intro hc
  exact h (congrArg Sigma.fst hc)

/-- **The vertex simple modules are pairwise non-isomorphic.** The idempotent `eᵢ` acts as the
identity on `Sᵢ` and as zero on `Sⱼ` for `j ≠ i`. -/
theorem augModule_not_isomorphic_of_ne {i j : Q} (h : i ≠ j)
    (e : augModule k Q i ≃ₗ[PathAlgebra k Q] augModule k Q j) : False := by
  have h1 : (eIdem i : PathAlgebra k Q) • augGen (k := k) (Q := Q) i = augGen i := by
    apply ULift.ext
    rw [augModule_down_smul, augHom_eIdem, one_mul]
  have h2 : (eIdem i : PathAlgebra k Q) • e (augGen (k := k) (Q := Q) i) = 0 := by
    apply ULift.ext
    rw [augModule_down_smul, augHom_eIdem_of_ne h, zero_mul]
    rfl
  rw [← map_smul, h1] at h2
  have h3 : augGen (k := k) (Q := Q) i = 0 := e.injective (h2.trans (map_zero e).symm)
  exact one_ne_zero (congrArg ULift.down h3)

/-- **Exhaustiveness.** Every simple module over the path algebra of a finite acyclic quiver is
isomorphic to one of the vertex simple modules `Sᵢ`.

Since the `eᵢ` sum to `1`, some `eᵢ` acts nontrivially on a simple module `M`, and then
`y ↦ y · m` is a surjection `Pᵢ ↠ M`. Its kernel is contained in `ker π`, because otherwise the
two together would span `Pᵢ` and superfluousness of `ker π` would force the kernel to be all of
`Pᵢ`. Comparing the two quotients of `Pᵢ` identifies `M` with `Sᵢ`. -/
theorem exists_augModule_iso
    (hacyclic : ∀ (v : Q) (p : Quiver.Path v v), p = Quiver.Path.nil)
    (M : Type w) [AddCommGroup M] [Module (PathAlgebra k Q) M]
    [IsSimpleModule (PathAlgebra k Q) M] :
    ∃ i : Q, Nonempty (M ≃ₗ[PathAlgebra k Q] augModule k Q i) := by
  haveI : Nontrivial M := IsSimpleModule.nontrivial (PathAlgebra k Q) M
  obtain ⟨m, hm⟩ := exists_ne (0 : M)
  -- Some trivial-path idempotent acts nontrivially on `m`.
  obtain ⟨i, hi⟩ : ∃ i : Q, (eIdem (k := k) i : PathAlgebra k Q) • m ≠ 0 := by
    by_contra hcon
    refine hm ?_
    have h0 : (∑ i : Q, (eIdem (k := k) i : PathAlgebra k Q)) • m = 0 := by
      rw [Finset.sum_smul]
      refine Finset.sum_eq_zero fun j _ => ?_
      by_contra hne
      exact hcon ⟨j, hne⟩
    rwa [sum_eIdem_eq_one, one_smul] at h0
  -- Evaluation at `m` is a surjection `Pᵢ ↠ M`.
  set f : pathAlgebraProj k Q i →ₗ[PathAlgebra k Q] M :=
    { toFun := fun y => (y : PathAlgebra k Q) • m
      map_add' := fun y z => by rw [Submodule.coe_add, add_smul]
      map_smul' := fun a y => by
        rw [RingHom.id_apply, Submodule.coe_smul, smul_eq_mul, mul_smul] } with hfdef
  have hfne : f (eIdemMem k Q i) ≠ 0 := hi
  have hfsurj : Function.Surjective f := by
    rcases IsSimpleOrder.eq_bot_or_eq_top (LinearMap.range f) with h | h
    · refine absurd ?_ hfne
      have hmem : f (eIdemMem k Q i) ∈ LinearMap.range f := LinearMap.mem_range_self f _
      rw [h, Submodule.mem_bot] at hmem
      exact hmem
    · exact LinearMap.range_eq_top.mp h
  -- Its kernel sits inside `ker π`, by superfluousness of `ker π`.
  have hker : LinearMap.ker f ≤ LinearMap.ker (projToSimple i) := by
    by_contra hcon
    obtain ⟨y, hyf, hyp⟩ := SetLike.not_le_iff_exists.mp hcon
    have hyp' : projToSimple i y ≠ 0 := fun hc => hyp (LinearMap.mem_ker.mpr hc)
    haveI := augModule_isSimpleModule (k := k) (Q := Q) i
    have hspan : Submodule.span (PathAlgebra k Q) {projToSimple i y} = ⊤ := by
      rcases IsSimpleOrder.eq_bot_or_eq_top
        (Submodule.span (PathAlgebra k Q) {projToSimple i y}) with h | h
      · refine absurd ?_ hyp'
        have hmem := Submodule.mem_span_singleton_self (R := PathAlgebra k Q)
          (projToSimple (k := k) (Q := Q) i y)
        rw [h, Submodule.mem_bot] at hmem
        exact hmem
      · exact h
    have htop : LinearMap.ker f ⊔ LinearMap.ker (projToSimple i) = ⊤ := by
      refine eq_top_iff.mpr fun z _ => ?_
      have hz : projToSimple i z ∈ Submodule.span (PathAlgebra k Q) {projToSimple i y} := by
        rw [hspan]; exact Submodule.mem_top
      obtain ⟨a, ha⟩ := Submodule.mem_span_singleton.mp hz
      have h1 : a • y ∈ LinearMap.ker f := (LinearMap.ker f).smul_mem a hyf
      have h2 : z - a • y ∈ LinearMap.ker (projToSimple i) := by
        rw [LinearMap.mem_ker, map_sub, map_smul, ha, sub_self]
      simpa using Submodule.add_mem_sup h1 h2
    have hfull := projToSimple_essential hacyclic i (LinearMap.ker f) htop
    refine hfne ?_
    have hgen : eIdemMem k Q i ∈ LinearMap.ker f := by rw [hfull]; exact Submodule.mem_top
    exact LinearMap.mem_ker.mp hgen
  -- The two kernels agree, so the two quotients of `Pᵢ` identify `M` with `Sᵢ`.
  have hkereq : LinearMap.ker f = LinearMap.ker (projToSimple i) := by
    refine le_antisymm hker ?_
    rcases IsSimpleOrder.eq_bot_or_eq_top
      (Submodule.map f (LinearMap.ker (projToSimple (k := k) (Q := Q) i))) with h | h
    · intro z hz
      have hfz : f z ∈ Submodule.map f (LinearMap.ker (projToSimple (k := k) (Q := Q) i)) :=
        Submodule.mem_map_of_mem hz
      rw [h, Submodule.mem_bot] at hfz
      exact LinearMap.mem_ker.mpr hfz
    · exfalso
      have hpitop : LinearMap.ker (projToSimple (k := k) (Q := Q) i) = ⊤ := by
        refine eq_top_iff.mpr fun z _ => ?_
        have hz : f z ∈ Submodule.map f (LinearMap.ker (projToSimple (k := k) (Q := Q) i)) := by
          rw [h]; exact Submodule.mem_top
        obtain ⟨y, hy, hfy⟩ := hz
        have hzy : z - y ∈ LinearMap.ker f := by
          rw [LinearMap.mem_ker, map_sub, hfy, sub_self]
        have hzy' : z - y ∈ LinearMap.ker (projToSimple (k := k) (Q := Q) i) := hker hzy
        have hsplit : z = (z - y) + y := by abel
        rw [hsplit]
        exact (LinearMap.ker _).add_mem hzy' hy
      obtain ⟨y, hy⟩ := projToSimple_surjective (k := k) (Q := Q) i (augGen i)
      have hyk : y ∈ LinearMap.ker (projToSimple (k := k) (Q := Q) i) := by
        rw [hpitop]; exact Submodule.mem_top
      have hzero : projToSimple i y = 0 := LinearMap.mem_ker.mp hyk
      rw [hy] at hzero
      exact one_ne_zero (congrArg ULift.down hzero)
  exact ⟨i, ⟨((f.quotKerEquivOfSurjective hfsurj).symm.trans
    (Submodule.quotEquivOfEq _ _ hkereq)).trans
    ((projToSimple i).quotKerEquivOfSurjective (projToSimple_surjective i))⟩⟩

/-- The carrier of the projective cover of `Sᵢ` is the principal left ideal `A · eᵢ`. -/
theorem vertexProjectiveCover_P
    (hacyclic : ∀ (v : Q) (p : Quiver.Path v v), p = Quiver.Path.nil) (i : Q) :
    (vertexProjectiveCover (k := k) hacyclic i).P = pathAlgebraProj k Q i := rfl

end Etingof.PathAlgebra

namespace Etingof.Problem946

open Etingof.PathAlgebra

variable {k : Type u} {Q : Type u} [Field k] [Quiver.{u + 1} Q] [Fintype Q] [DecidableEq Q]

/-- **Problem 9.4.6 (ii), with certified projective covers.** For a finite acyclic quiver `Q`,
the matrix computed by `cartanMatrix_pathAlgebra_eq_pathCount'` is the Cartan matrix of the path
algebra in the sense of Definition 9.3.1, not merely a matrix of Hom-space dimensions for an
arbitrary family of modules. The four conjuncts say, in order:

* the vertex modules `Sᵢ` are simple;
* they are pairwise non-isomorphic, so the vertices index them without repetition;
* they exhaust the simple modules, so the vertices index all of them;
* the projective cover of `Sᵢ` is the principal left ideal `Pᵢ = A · eᵢ` that the matrix is
  computed from, whose `(i, j)` entry is the number of oriented paths from `i` to `j`. -/
theorem cartanMatrix_pathAlgebra_eq_pathCount_of_projectiveCovers
    (hacyclic : ∀ (i : Q) (p : Quiver.Path i i), p = Quiver.Path.nil)
    [∀ i j : Q, Finite (i ⟶ j)] :
    (∀ i : Q, IsSimpleModule (Etingof.PathAlgebra k Q) (augModule k Q i)) ∧
      (∀ i j : Q,
        Nonempty (augModule k Q i ≃ₗ[Etingof.PathAlgebra k Q] augModule k Q j) → i = j) ∧
      (∀ (M : Type w) [AddCommGroup M] [Module (Etingof.PathAlgebra k Q) M]
          [IsSimpleModule (Etingof.PathAlgebra k Q) M],
        ∃ i : Q, Nonempty (M ≃ₗ[Etingof.PathAlgebra k Q] augModule k Q i)) ∧
      (∀ i : Q, (vertexProjectiveCover (k := k) hacyclic i).P = pathAlgebraProj k Q i) ∧
      Etingof.algebraCartanMatrix (k := k) (A := Etingof.PathAlgebra k Q)
        (Etingof.PathAlgebra.pathAlgebraProj k Q) = pathCountMatrix Q :=
  ⟨fun i => augModule_isSimpleModule i,
    fun i j ⟨e⟩ => by
      by_contra hne
      exact augModule_not_isomorphic_of_ne hne e,
    fun M => exists_augModule_iso hacyclic M,
    fun _ => rfl,
    cartanMatrix_pathAlgebra_eq_pathCount' hacyclic⟩

end Etingof.Problem946
