import EtingofRepresentationTheory.Chapter5.AlgIrrepGLNonIso
import EtingofRepresentationTheory.Chapter5.AlgIrrepGLRep
import EtingofRepresentationTheory.Chapter5.CleanCharacterExtractionBase
import EtingofRepresentationTheory.Chapter5.Corollary5_12_4
import EtingofRepresentationTheory.Chapter5.Corollary5_15_4
import EtingofRepresentationTheory.Chapter5.Corollary5_19_2
import EtingofRepresentationTheory.Chapter5.Corollary5_1_6
import EtingofRepresentationTheory.Chapter5.Corollary5_26_3
import EtingofRepresentationTheory.Chapter5.Definition5_12_1
import EtingofRepresentationTheory.Chapter5.Definition5_14_2
import EtingofRepresentationTheory.Chapter5.Definition5_1_1
import EtingofRepresentationTheory.Chapter5.Definition5_1_4

/-!
# Claim-ledger declaration pointers

Generated by `scripts/validate_lean_decls.py --apply`.
-/

set_option linter.style.longLine false

-- Provider: EtingofRepresentationTheory.Chapter5.AlgIrrepGLNonIso
-- Chapter5/Discussion_after_Definition5.23.1.claim_coverage.claims[2].lean_decl, derived-
-- from:Chapter5/Discussion_after_Definition5.23.1.lean_ref
#check @Etingof.algIrrepGLRepρ_iso_iff_eq

-- Provider: EtingofRepresentationTheory.Chapter5.AlgIrrepGLRep
-- Chapter5/Discussion_after_Definition5.23.1.claim_coverage.claims[1].lean_decl
#check @Etingof.AlgIrrepGLRep
-- derived-from:Chapter5/Discussion_after_Definition5.23.1.lean_ref
#check @Etingof.algIrrepGLRepρ

-- Provider: EtingofRepresentationTheory.Chapter5.CleanCharacterExtractionBase
-- derived-from:Chapter5/Discussion_after_Definition5.23.1.lean_ref
#check @Etingof.schurModule_isSimple_general

-- Provider: EtingofRepresentationTheory.Chapter5.Corollary5_12_4
-- Chapter5/Corollary5.12.4.claim_coverage.claims[1].lean_decl
#check @Etingof.Corollary5_12_4
-- Chapter5/Corollary5.12.4.claim_coverage.claims[1].lean_decl
#check @Etingof.SpechtModule_complexification

-- Provider: EtingofRepresentationTheory.Chapter5.Corollary5_15_4
-- Chapter5/Corollary5.15.4.claim_coverage.claims[1].lean_decl
#check @Etingof.Corollary5_15_4

-- Provider: EtingofRepresentationTheory.Chapter5.Corollary5_19_2
-- Chapter5/Corollary5.19.2.claim_coverage.claims[1].lean_decl,
-- Chapter5/Corollary5.19.2.claim_coverage.claims[2].lean_decl,
-- Chapter5/Corollary5.19.2.claim_coverage.claims[3].lean_decl
#check @Etingof.Corollary5_19_2

-- Provider: EtingofRepresentationTheory.Chapter5.Corollary5_1_6
-- Chapter5/Corollary5.1.6.claim_coverage.claims[1].lean_decl
#check @Etingof.Corollary5_1_6_realType

-- Provider: EtingofRepresentationTheory.Chapter5.Corollary5_26_3
-- Chapter5/Corollary5.26.3.claim_coverage.claims[1].lean_decl, Chapter5/Corollary5.26.3.lean_ref
#check @Etingof.Corollary5_26_3

-- Provider: EtingofRepresentationTheory.Chapter5.Definition5_12_1
-- Chapter5/Definition5.12.1.claim_coverage.claims[2].lean_decl
#check @Etingof.ColumnSubgroup
-- Chapter5/Definition5.12.1.claim_coverage.claims[2].lean_decl
#check @Etingof.RowSubgroup
-- Chapter5/Definition5.12.1.claim_coverage.claims[1].lean_decl
#check @Etingof.YoungTableau
-- Chapter5/Definition5.12.1.claim_coverage.claims[1].lean_decl
#check @Etingof.canonicalStandardYoungTableau
-- Chapter5/Definition5.12.1.claim_coverage.claims[1].lean_decl
#check @Etingof.canonicalYoungTableau
-- Chapter5/Discussion_Young_projectors.claim_coverage.claims[1].lean_decl,
-- Chapter5/Discussion_Young_projectors.lean_ref
#check @Etingof.youngProjector
-- Chapter5/Discussion_Young_projectors.claim_coverage.claims[1].lean_decl,
-- Chapter5/Discussion_Young_projectors.lean_ref
#check @Etingof.youngProjectorCol
-- Chapter5/Discussion_Young_projectors.claim_coverage.claims[1].lean_decl,
-- Chapter5/Discussion_Young_projectors.lean_ref
#check @Etingof.youngProjectorRow

-- Provider: EtingofRepresentationTheory.Chapter5.Definition5_14_2
-- Chapter5/Definition5.14.2.claim_coverage.claims[1].lean_decl
#check @Etingof.KostkaNumber

-- Provider: EtingofRepresentationTheory.Chapter5.Definition5_1_1
-- Chapter5/Definition5.1.1.claim_coverage.claims[1].lean_decl,
-- Chapter5/Introduction.claim_coverage.claims[1].lean_decl
#check @Etingof.IsComplexType
-- Chapter5/Definition5.1.1.claim_coverage.claims[3].lean_decl,
-- Chapter5/Introduction.claim_coverage.claims[1].lean_decl
#check @Etingof.IsQuaternionicType
-- Chapter5/Definition5.1.1.claim_coverage.claims[2].lean_decl,
-- Chapter5/Introduction.claim_coverage.claims[1].lean_decl
#check @Etingof.IsRealType

-- Provider: EtingofRepresentationTheory.Chapter5.Definition5_1_4
-- Chapter5/Definition5.1.4.claim_coverage.claims[1].lean_decl,
-- Chapter5/Introduction.claim_coverage.claims[1].lean_decl
#check @Etingof.frobeniusSchurIndicator
