import Mathlib.Algebra.Algebra.Basic
import Mathlib.Algebra.Algebra.Defs
import Mathlib.Algebra.Algebra.Subalgebra.Basic
import Mathlib.Algebra.Algebra.Subalgebra.Lattice
import Mathlib.Algebra.Category.ModuleCat.Abelian
import Mathlib.Algebra.CharP.Defs
import Mathlib.Algebra.CharP.Lemmas
import Mathlib.Algebra.DirectSum.Ring
import Mathlib.Algebra.FreeAlgebra
import Mathlib.Algebra.Group.Action.Defs
import Mathlib.Algebra.Homology.HomologicalComplex
import Mathlib.Algebra.Homology.ShortComplex.HomologicalComplex

/-!
# Claim-ledger declaration pointers

Generated by `scripts/validate_lean_decls.py --apply`.
-/

set_option linter.style.longLine false

-- Provider: Mathlib.Algebra.Algebra.Basic
-- Chapter2/Discussion_2.1_overview.claim_coverage.claims[3].lean_decl,
-- Chapter2/Example2.2.4.claim_coverage.claims[3].lean_decl
#check @Module.End.instAlgebra

-- Provider: Mathlib.Algebra.Algebra.Defs
-- Chapter2/Example2.2.4.claim_coverage.claims[1].lean_decl
#check @Algebra.id

-- Provider: Mathlib.Algebra.Algebra.Subalgebra.Basic
-- Chapter2/Problem2.3.16.claim_coverage.claims[1].lean_decl
#check @Subalgebra.center

-- Provider: Mathlib.Algebra.Algebra.Subalgebra.Lattice
-- Chapter2/Problem2.3.16.claim_coverage.claims[2].lean_decl
#check @Subalgebra.center_eq_top

-- Provider: Mathlib.Algebra.Category.ModuleCat.Abelian
-- Chapter7/Example7.7.2.claim_coverage.claims[1].lean_decl
#check @ModuleCat.abelian

-- Provider: Mathlib.Algebra.CharP.Defs
-- Chapter3/Theorem3.7.1.claim_coverage.claims[9].lean_decl
#check @CharP.cast_eq_zero

-- Provider: Mathlib.Algebra.CharP.Lemmas
-- Chapter4/Example4.1.3.claim_coverage.claims[5].lean_decl
#check @sub_pow_char_of_commute

-- Provider: Mathlib.Algebra.DirectSum.Ring
-- Chapter3/Theorem3.2.2.claim_coverage.claims[7].lean_decl
#check @DirectSum.GNonUnitalNonAssocSemiring

-- Provider: Mathlib.Algebra.FreeAlgebra
-- Chapter2/Example2.2.4.claim_coverage.claims[5].lean_decl
#check @FreeAlgebra.equivMonoidAlgebraFreeMonoid
-- Chapter2/Example2.2.4.claim_coverage.claims[4].lean_decl
#check @FreeAlgebra.instAlgebra
-- Chapter2/Example2.3.3.claim_coverage.claims[5].lean_decl
#check @FreeAlgebra.lift
-- Chapter2/Example2.3.3.claim_coverage.claims[6].lean_decl
#check @FreeAlgebra.lift_symm_apply
-- Chapter2/Example2.3.3.claim_coverage.claims[6].lean_decl
#check @FreeAlgebra.lift_ι_apply

-- Provider: Mathlib.Algebra.Group.Action.Defs
-- Chapter2/Problem2.11.6.claim_coverage.claims[1].lean_decl
#check @SMulCommClass

-- Provider: Mathlib.Algebra.Homology.HomologicalComplex
-- Chapter7/Discussion_after_Definition7.8.1.claim_coverage.claims[1].lean_decl
#check @HomologicalComplex
-- Chapter7/Discussion_after_Definition7.8.1.claim_coverage.claims[1].lean_decl
#check @HomologicalComplex.Hom

-- Provider: Mathlib.Algebra.Homology.ShortComplex.HomologicalComplex
-- Chapter7/Discussion_after_Definition7.8.1.claim_coverage.claims[1].lean_decl
#check @HomologicalComplex.homology
