import EtingofRepresentationTheory.Chapter6.Problem6_1_3
import EtingofRepresentationTheory.Chapter6.Problem6_1_3_continued_E7_E8
import EtingofRepresentationTheory.Chapter6.Problem6_1_3_continued_tildeE
import EtingofRepresentationTheory.Chapter6.Problem6_1_5_theorem
import EtingofRepresentationTheory.Chapter6.Problem6_1_6
import EtingofRepresentationTheory.Chapter6.Problem6_9_1
import EtingofRepresentationTheory.Chapter6.Problem6_9_1_Classification
import EtingofRepresentationTheory.Chapter6.Problem6_9_2
import EtingofRepresentationTheory.Chapter6.Problem6_9_2_RootSystem
import EtingofRepresentationTheory.Chapter6.Problem6_9_3
import EtingofRepresentationTheory.Chapter6.Problem6_9_3_JordanHolder
import EtingofRepresentationTheory.Chapter6.Proposition6_6_5

/-!
# Claim-ledger declaration pointers

Generated by `scripts/validate_lean_decls.py --apply`.
-/

set_option linter.style.longLine false

-- Provider: EtingofRepresentationTheory.Chapter6.Problem6_1_3
-- Chapter6/Problem6.1.3.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem6_1_3.cartanMatrix

-- Provider: EtingofRepresentationTheory.Chapter6.Problem6_1_3_continued_E7_E8
-- Chapter6/Problem6.1.3_continued_E7_E8.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem6_1_3_E7E8.cycle_cartan_det_zero
-- Chapter6/Problem6.1.3_continued_E7_E8.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem6_1_3_E7E8.det_cartan_A
-- Chapter6/Problem6.1.3_continued_E7_E8.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem6_1_3_E7E8.det_cartan_D
-- Chapter6/Problem6.1.3_continued_E7_E8.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem6_1_3_E7E8.det_cartan_E6
-- Chapter6/Problem6.1.3_continued_E7_E8.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem6_1_3_E7E8.det_cartan_E7
-- Chapter6/Problem6.1.3_continued_E7_E8.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem6_1_3_E7E8.det_cartan_E8
-- Chapter6/Problem6.1.3_continued_E7_E8.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem6_1_3_E7E8.isDynkinDiagram_A
-- Chapter6/Problem6.1.3_continued_E7_E8.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem6_1_3_E7E8.isDynkinDiagram_D
-- Chapter6/Problem6.1.3_continued_E7_E8.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem6_1_3_E7E8.isDynkinDiagram_E
-- Chapter6/Problem6.1.3_continued_E7_E8.claim_coverage.claims[4].lean_decl
#check @Etingof.Problem6_1_3_E7E8.isDynkinDiagram_degree_le_three
-- Chapter6/Problem6.1.3_continued_E7_E8.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem6_1_3_E7E8.isDynkinDiagram_isTree
-- Chapter6/Problem6.1.3_continued_E7_E8.claim_coverage.claims[4].lean_decl
#check @Etingof.Problem6_1_3_E7E8.isDynkinDiagram_unique_degree_three

-- Provider: EtingofRepresentationTheory.Chapter6.Problem6_1_3_continued_tildeE
-- Chapter6/Problem6.1.3_continued_tildeE.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem6_1_3_tildeE.affine_dynkin_classification
-- Chapter6/Problem6.1.3_continued_E7_E8.claim_coverage.claims[5].lean_decl,
-- Chapter6/Problem6.1.3_continued_tildeE.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem6_1_3_tildeE.cartan_det_zero
-- Chapter6/Problem6.1.3_continued_E7_E8.claim_coverage.claims[5].lean_decl,
-- Chapter6/Problem6.1.3_continued_tildeE.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem6_1_3_tildeE.cartan_mulVec_marks_eq_zero
-- Chapter6/Problem6.1.3_continued_tildeE.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem6_1_3_tildeE.dynkin_classification
-- Chapter6/Problem6.1.3_continued_tildeE.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem6_1_3_tildeE.isAffineDynkinDiagram_of_type

-- Provider: EtingofRepresentationTheory.Chapter6.Problem6_1_5_theorem
-- Chapter6/Problem6.1.5.claim_coverage.claims[1].lean_decl, Chapter6/Problem6.1.5.lean_decl,
-- Chapter6/Problem6.1.5_parts.claim_coverage.claims[3].lean_decl,
-- Chapter6/Problem6.1.5_theorem.claim_coverage.claims[1].lean_decl,
-- Chapter6/Problem6.1.5_theorem.lean_ref
#check @Etingof.Theorem_6_1_5
-- Chapter6/Problem6.1.5_parts.claim_coverage.claims[1].lean_decl
#check @Etingof.titsForm_pos_on_nonzero_of_finite_type
-- Chapter6/Problem6.1.5_parts.claim_coverage.claims[2].lean_decl
#check @Etingof.titsForm_real_posDef_of_finite_type

-- Provider: EtingofRepresentationTheory.Chapter6.Problem6_1_6
-- Chapter6/Problem6.1.6.claim_coverage.claims[2].lean_decl,
-- Chapter6/Problem6.1.6.claim_coverage.claims[4].lean_decl,
-- Chapter6/Problem6.1.6.claim_coverage.claims[5].lean_decl,
-- Chapter6/Problem6.1.6.claim_coverage.claims[7].lean_decl, Chapter6/Problem6.1.6.lean_decl
#check @Etingof.Problem6_1_6.mckay_connected
-- Chapter6/Problem6.1.6.claim_coverage.claims[4].lean_decl,
-- Chapter6/Problem6.1.6.claim_coverage.claims[5].lean_decl,
-- Chapter6/Problem6.1.6.claim_coverage.claims[6].lean_decl,
-- Chapter6/Problem6.1.6.claim_coverage.claims[7].lean_decl, Chapter6/Problem6.1.6.lean_decl
#check @Etingof.Problem6_1_6.mckay_dims_are_marks
-- Chapter6/Problem6.1.6.claim_coverage.claims[3].lean_decl,
-- Chapter6/Problem6.1.6.claim_coverage.claims[4].lean_decl,
-- Chapter6/Problem6.1.6.claim_coverage.claims[5].lean_decl,
-- Chapter6/Problem6.1.6.claim_coverage.claims[7].lean_decl, Chapter6/Problem6.1.6.lean_decl
#check @Etingof.Problem6_1_6.mckay_isAffineDynkin
-- Chapter6/Problem6.1.6.claim_coverage.claims[1].lean_decl,
-- Chapter6/Problem6.1.6.claim_coverage.claims[4].lean_decl,
-- Chapter6/Problem6.1.6.claim_coverage.claims[5].lean_decl,
-- Chapter6/Problem6.1.6.claim_coverage.claims[7].lean_decl, Chapter6/Problem6.1.6.lean_decl
#check @Etingof.Problem6_1_6.mult_symm

-- Provider: EtingofRepresentationTheory.Chapter6.Problem6_9_1
-- Chapter6/Problem6.9.1.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem6_9_1c
-- Chapter6/Problem6.9.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Q₂Family.eq_of_rep_iso
-- Chapter6/Problem6.9.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Q₂Family.rep_indecomposable

-- Provider: EtingofRepresentationTheory.Chapter6.Problem6_9_1_Classification
-- Chapter6/Problem6.9.1.claim_coverage.claims[4].lean_decl,
-- Chapter6/Section6.9_heading.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem6_9_1
-- Chapter6/Problem6.9.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem6_9_1_unique
-- Chapter6/Problem6.9.1.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem6_9_1b_directSummand
-- Chapter6/Problem6.9.1.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem6_9_1c_exists_compatibleChainBasis

-- Provider: EtingofRepresentationTheory.Chapter6.Problem6_9_2
-- Chapter6/Problem6.9.2.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem6_9_2.E6Lattice
-- Chapter6/Problem6.9.2.claim_coverage.claims[4].lean_decl
#check @Etingof.Problem6_9_2.E6_root_count
-- Chapter6/Problem6.9.2.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem6_9_2.E7Lattice
-- Chapter6/Problem6.9.2.claim_coverage.claims[4].lean_decl
#check @Etingof.Problem6_9_2.E7_root_count
-- Chapter6/Problem6.9.2.claim_coverage.claims[4].lean_decl
#check @Etingof.Problem6_9_2.E8_root_count
-- Chapter6/Problem6.9.2.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem6_9_2.α_isBasis

-- Provider: EtingofRepresentationTheory.Chapter6.Problem6_9_2_RootSystem
-- Chapter6/Problem6.9.2.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem6_9_2.E6Simple_gram_type
-- Chapter6/Problem6.9.2.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem6_9_2.E7Simple_gram_type
-- Chapter6/Problem6.9.2.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem6_9_2.rootsOf_E8_isRootSystem
-- Chapter6/Problem6.9.2.claim_coverage.claims[2].lean_decl,
-- Chapter6/Section6.9_heading.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem6_9_2.rootsOf_E8_type_E8

-- Provider: EtingofRepresentationTheory.Chapter6.Problem6_9_3
-- Chapter6/Problem6.9.3.claim_coverage.claims[3].lean_decl,
-- Chapter6/Section6.9_heading.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem6_9_3.exists_jordanHolderSeries
-- Chapter6/Problem6.9.3.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem6_9_3.ext1_sink
-- Chapter6/Problem6.9.3.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem6_9_3.ext1_source

-- Provider: EtingofRepresentationTheory.Chapter6.Problem6_9_3_JordanHolder
-- Chapter6/Problem6.9.3.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem6_9_3.exists_compositionSeries_of_positiveRoot

-- Provider: EtingofRepresentationTheory.Chapter6.Proposition6_6_5
-- Chapter6/Proposition6.6.5.claim_coverage.claims[1].lean_decl
#check @Etingof.Proposition6_6_5_sink
-- Chapter6/Proposition6.6.5.claim_coverage.claims[1].lean_decl
#check @Etingof.Proposition6_6_5_source
