import EtingofRepresentationTheory.Chapter2.Problem2_16_3_Layers
import EtingofRepresentationTheory.Chapter2.Problem2_16_4
import EtingofRepresentationTheory.Chapter2.Problem2_16_5
import EtingofRepresentationTheory.Chapter2.Problem2_3_15
import EtingofRepresentationTheory.Chapter2.Problem2_3_16
import EtingofRepresentationTheory.Chapter2.Problem2_3_17
import EtingofRepresentationTheory.Chapter2.Problem2_3_18
import EtingofRepresentationTheory.Chapter2.Problem2_4_1
import EtingofRepresentationTheory.Chapter2.Problem2_5_1
import EtingofRepresentationTheory.Chapter2.Problem2_5_2
import EtingofRepresentationTheory.Chapter2.Problem2_7_4
import EtingofRepresentationTheory.Chapter2.Problem2_7_4_Family

/-!
# Claim-ledger declaration pointers

Generated by `scripts/validate_lean_decls.py --apply`.
-/

-- Provider: EtingofRepresentationTheory.Chapter2.Problem2_16_3_Layers
-- Chapter2/Problem2.16.3.claim_coverage.claims[7].lean_decl
#check @Etingof.Problem2_16_3.card_loopIdx_deg_even
-- Chapter2/Problem2.16.3.claim_coverage.claims[7].lean_decl
#check @Etingof.Problem2_16_3.card_loopIdx_deg_odd
-- Chapter2/Problem2.16.3.claim_coverage.claims[7].lean_decl
#check @Etingof.Problem2_16_3.card_loopIdx_deg_zero
-- Chapter2/Problem2.16.3.claim_coverage.claims[7].lean_decl
#check @Etingof.Problem2_16_3.loopFam₄

-- Provider: EtingofRepresentationTheory.Chapter2.Problem2_16_4
-- Chapter2/Problem2.16.4.claim_coverage.claims[2].lean_decl, Chapter2/Problem2.16.4.lean_decl
#check @Etingof.Problem2_16_4.exists_irreducible_dim_char
-- Chapter2/Problem2.16.4.claim_coverage.claims[2].lean_decl, Chapter2/Problem2.16.4.lean_decl
#check @Etingof.Problem2_16_4.finrank_irreducible_le_char
-- Chapter2/Problem2.16.4.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem2_16_4.irrep_finrank
-- Chapter2/Problem2.16.4.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem2_16_4.irrep_isIrreducible

-- Provider: EtingofRepresentationTheory.Chapter2.Problem2_16_5
-- Chapter2/Problem2.16.5.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem2_16_5.KL_rel
-- Chapter2/Problem2.16.5.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem2_16_5.Ke_rel
-- Chapter2/Problem2.16.5.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem2_16_5.Kf_rel
-- Chapter2/Problem2.16.5.claim_coverage.claims[7].lean_decl, Chapter2/Problem2.16.5.lean_decl
#check @Etingof.Problem2_16_5.Kop_isSemisimple_and_eigenvalues
-- Chapter2/Problem2.16.5.claim_coverage.claims[7].lean_decl
#check @Etingof.Problem2_16_5.Kpow_orderOf_isScalar
-- Chapter2/Problem2.16.5.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem2_16_5.LK_rel
-- Chapter2/Problem2.16.5.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem2_16_5.Rel
-- Chapter2/Problem2.16.5.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem2_16_5.Uqsl2
-- Chapter2/Problem2.16.5.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem2_16_5.augmentation_surjective
-- Chapter2/Problem2.16.5.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem2_16_5.ef_rel
-- Chapter2/Problem2.16.5.claim_coverage.claims[8].lean_decl
#check @Etingof.Problem2_16_5.epow_orderOf_isScalar
-- Chapter2/Problem2.16.5.claim_coverage.claims[4].lean_decl
#check @Etingof.Problem2_16_5.exists_highest_weight_vector
-- Chapter2/Problem2.16.5.claim_coverage.claims[8].lean_decl, Chapter2/Problem2.16.5.lean_decl
#check @Etingof.Problem2_16_5.finrank_irreducible_le_of_isOfFinOrder
-- Chapter2/Problem2.16.5.claim_coverage.claims[8].lean_decl
#check @Etingof.Problem2_16_5.fpow_orderOf_isScalar
-- Chapter2/Problem2.16.5.claim_coverage.claims[5].lean_decl, Chapter2/Problem2.16.5.lean_decl
#check @Etingof.Problem2_16_5.highest_weight_eigenvalue_of_not_isOfFinOrder

-- Provider: EtingofRepresentationTheory.Chapter2.Problem2_3_15
-- Chapter2/Problem2.3.15.claim_coverage.claims[1].lean_decl,
-- Chapter3/Proposition3.1.4.claim_coverage.claims[3].lean_decl
#check @Etingof.exists_isSimpleModule_of_finite
-- Chapter2/Problem2.3.15.claim_coverage.claims[2].lean_decl
#check @Etingof.not_exists_isSimpleModule_polynomial

-- Provider: EtingofRepresentationTheory.Chapter2.Problem2_3_16
-- Chapter2/Problem2.3.16.claim_coverage.claims[5].lean_decl
#check @Etingof.centralAction_sub_smul_isNilpotent
-- Chapter2/Problem2.3.16.claim_coverage.claims[4].lean_decl
#check @Etingof.centralCharacter
-- Chapter2/Problem2.3.16.claim_coverage.claims[3].lean_decl
#check @Etingof.centralCharacter_smul
-- Chapter2/Problem2.3.16.claim_coverage.claims[7].lean_decl
#check @Etingof.eps_smul_not_scalar
-- Chapter2/Problem2.3.16.claim_coverage.claims[3].lean_decl
#check @Etingof.exists_central_scalar
-- Chapter2/Problem2.3.16.claim_coverage.claims[6].lean_decl
#check @Etingof.exists_irreducibleSubrepresentation_centralCharacter
-- Chapter2/Problem2.3.16.claim_coverage.claims[5].lean_decl
#check @Etingof.indecEigenvalue_unique

-- Provider: EtingofRepresentationTheory.Chapter2.Problem2_3_17
-- Chapter2/Problem2.3.17.claim_coverage.claims[2].lean_decl
#check @Etingof.EndSelfEquivOp
-- Chapter2/Problem2.3.17.claim_coverage.claims[3].lean_decl
#check @Etingof.EndSelfEquivOp_apply
-- Chapter2/Problem2.3.17.claim_coverage.claims[3].lean_decl
#check @Etingof.EndSelfEquivOp_symm_op_apply

-- Provider: EtingofRepresentationTheory.Chapter2.Problem2_3_18
-- Chapter2/Problem2.3.18.claim_coverage.claims[1].lean_decl,
-- Chapter2/Problem2.3.18.claim_coverage.claims[2].lean_decl,
-- Chapter2/Problem2.3.18.claim_coverage.claims[3].lean_decl,
-- Chapter2/Problem2.3.18.claim_coverage.claims[4].lean_decl, Chapter2/Problem2.3.18.lean_decl
#check @Etingof.Problem_2_3_18

-- Provider: EtingofRepresentationTheory.Chapter2.Problem2_4_1
-- Chapter2/Problem2.4.1.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem2_4_1.exists_maximal_left_ideal
-- Chapter2/Problem2.4.1.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem2_4_1.exists_maximal_right_ideal
-- Chapter2/Problem2.4.1.claim_coverage.claims[4].lean_decl
#check @Etingof.Problem2_4_1.exists_maximal_twoSided_ideal

-- Provider: EtingofRepresentationTheory.Chapter2.Problem2_5_1
-- Chapter2/Problem2.5.1.claim_coverage.claims[1].lean_decl,
-- Chapter2/Problem2.5.1.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem2_5_1.quotient_isIndecomposable

-- Provider: EtingofRepresentationTheory.Chapter2.Problem2_5_2
-- Chapter2/Problem2.5.2.claim_coverage.claims[8].lean_decl
#check @Etingof.Coregular
-- Chapter2/Problem2.5.2.claim_coverage.claims[9].lean_decl
#check @Etingof.Coregular.toDual_smul
-- Chapter2/Problem2.5.2.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem2_5_2.IsCyclic
-- Chapter2/Problem2.5.2.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem2_5_2.IsCyclicVector
-- Chapter2/Problem2.5.2.claim_coverage.claims[5].lean_decl
#check @Etingof.Problem2_5_2.PartC.I₂_eq_span_homogeneous_ge_two
-- Chapter2/Problem2.5.2.claim_coverage.claims[6].lean_decl
#check @Etingof.Problem2_5_2.PartC.algEquiv
-- Chapter2/Problem2.5.2.claim_coverage.claims[7].lean_decl
#check @Etingof.Problem2_5_2.PartC.basis
-- Chapter2/Problem2.5.2.claim_coverage.claims[10].lean_decl
#check @Etingof.Problem2_5_2.PartC.indecomposable_not_cyclic
-- Chapter2/Problem2.5.2.claim_coverage.claims[4].lean_decl
#check @Etingof.Problem2_5_2.cyclic_iff_isoQuotient
-- Chapter2/Problem2.5.2.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem2_5_2.irreducible_iff_forall_cyclic

-- Provider: EtingofRepresentationTheory.Chapter2.Problem2_7_4
-- Chapter2/Problem2.7.4.claim_coverage.claims[4].lean_decl
#check @Etingof.Problem2_7_4.center_charP
-- Chapter2/Problem2.7.4.claim_coverage.claims[5].lean_decl
#check @Etingof.Problem2_7_4.exists_normalForm
-- Chapter2/Problem2.7.4.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem2_7_4.finrank_eq_zero_of_charZero
-- Chapter2/Problem2.7.4.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem2_7_4.isSimpleRing_charZero
-- Chapter2/Problem2.7.4.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem2_7_4.x_pow_char_mem_center
-- Chapter2/Problem2.7.4.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem2_7_4.y_pow_char_mem_center

-- Provider: EtingofRepresentationTheory.Chapter2.Problem2_7_4_Family
-- Chapter2/Problem2.7.4.claim_coverage.claims[7].lean_decl
#check @Etingof.Problem2_7_4.existsUnique_toFamEquiv
-- Chapter2/Problem2.7.4.claim_coverage.claims[6].lean_decl
#check @Etingof.Problem2_7_4.exists_toFamEquiv
-- Chapter2/Problem2.7.4.claim_coverage.claims[7].lean_decl
#check @Etingof.Problem2_7_4.famEquiv_nonempty_iff
-- Chapter2/Problem2.7.4.claim_coverage.claims[6].lean_decl
#check @Etingof.Problem2_7_4.famModule_finrank
-- Chapter2/Problem2.7.4.claim_coverage.claims[6].lean_decl
#check @Etingof.Problem2_7_4.famModule_isSimpleModule
