import EtingofRepresentationTheory.Chapter8.Problem8_2_5
import EtingofRepresentationTheory.Chapter8.Problem8_2_6
import EtingofRepresentationTheory.Chapter8.Problem8_2_7_ExtInt
import EtingofRepresentationTheory.Chapter8.Problem8_2_7_ExtPoly
import EtingofRepresentationTheory.Chapter8.Problem8_2_7_TorInt
import EtingofRepresentationTheory.Chapter8.Problem8_2_7_TorPoly
import EtingofRepresentationTheory.Chapter8.Problem8_2_8
import EtingofRepresentationTheory.Chapter8.Problem8_2_8Counterexample
import EtingofRepresentationTheory.Chapter8.Theorem8_1_1
import EtingofRepresentationTheory.Chapter8.Theorem8_1_5
import EtingofRepresentationTheory.Chapter9.Exercise9_6_3
import EtingofRepresentationTheory.Chapter9.FiniteProjectiveResolution

/-!
# Claim-ledger declaration pointers

Generated by `scripts/validate_lean_decls.py --apply`.
-/

set_option linter.style.longLine false

-- Provider: EtingofRepresentationTheory.Chapter8.Problem8_2_5
-- Chapter8/Problem8.2.5.claim_coverage.claims[5].lean_decl
#check @Etingof.Problem825.extCochainMap
-- Chapter8/Problem8.2.5.claim_coverage.claims[5].lean_decl
#check @Etingof.Problem825.extComparison
-- Chapter8/Problem8.2.5.claim_coverage.claims[5].lean_decl
#check @Etingof.Problem825.extLiftMap
-- Chapter8/Problem8.2.5.claim_coverage.claims[5].lean_decl
#check @Etingof.Problem825.extLiftMap_eq_comparison
-- Chapter8/Problem8.2.5.claim_coverage.claims[5].lean_decl
#check @Etingof.Problem825.extLiftMap_independent
-- Chapter8/Problem8.2.5.claim_coverage.claims[4].lean_decl
#check @Etingof.Problem825.torComparison
-- Chapter8/Problem8.2.5.claim_coverage.claims[4].lean_decl
#check @Etingof.Problem825.torComparison_refl
-- Chapter8/Problem8.2.5.claim_coverage.claims[4].lean_decl
#check @Etingof.Problem825.torComparison_trans
-- Chapter8/Problem8.2.5.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem825.torLiftMap
-- Chapter8/Problem8.2.5.claim_coverage.claims[4].lean_decl
#check @Etingof.Problem825.torLiftMap_eq_comparison
-- Chapter8/Problem8.2.5.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem825.torLiftMap_independent
-- Chapter8/Problem8.2.5.claim_coverage.claims[1].lean_decl,
-- Chapter8/Problem8.2.5.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem_8_2_5_morphism_of_resolutions

-- Provider: EtingofRepresentationTheory.Chapter8.Problem8_2_6
-- Chapter8/Problem8.2.6.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem_8_2_6_i_ext
-- Chapter8/Problem8.2.6.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem_8_2_6_i_tor
-- Chapter8/Problem8.2.6.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem_8_2_6_ii
-- Chapter8/Problem8.2.6.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem_8_2_6_iii_ext
-- Chapter8/Problem8.2.6.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem_8_2_6_iii_tor
-- Chapter8/Problem8.2.6.claim_coverage.claims[4].lean_decl
#check @Etingof.Problem_8_2_6_iv
-- Chapter8/Problem8.2.6.claim_coverage.claims[6].lean_decl
#check @Etingof.Problem_8_2_6_v_ext
-- Chapter8/Problem8.2.6.claim_coverage.claims[6].lean_decl
#check @Etingof.Problem_8_2_6_v_tor
-- Chapter8/Problem8.2.6.claim_coverage.claims[2].lean_decl
#check @Etingof.extOneAddEquivProblem3Ext1

-- Provider: EtingofRepresentationTheory.Chapter8.Problem8_2_7_ExtInt
-- Chapter8/Problem8.2.7.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem_8_2_7_i_ext_fg

-- Provider: EtingofRepresentationTheory.Chapter8.Problem8_2_7_ExtPoly
-- Chapter8/Problem8.2.7.claim_coverage.claims[4].lean_decl
#check @Etingof.Problem_8_2_7_ii_ext_fg

-- Provider: EtingofRepresentationTheory.Chapter8.Problem8_2_7_TorInt
-- Chapter8/Problem8.2.7.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem_8_2_7_i_tor_fg

-- Provider: EtingofRepresentationTheory.Chapter8.Problem8_2_7_TorPoly
-- Chapter8/Problem8.2.7.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem_8_2_7_ii_tor_fg

-- Provider: EtingofRepresentationTheory.Chapter8.Problem8_2_8
-- Chapter8/Problem8.2.8.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem_8_2_8_ext
-- Chapter8/Problem8.2.8.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem_8_2_8_extₖ
-- Chapter8/Problem8.2.8.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem_8_2_8_tor

-- Provider: EtingofRepresentationTheory.Chapter8.Problem8_2_8Counterexample
-- Chapter8/Problem8.2.8.claim_coverage.claims[2].lean_decl
#check @TensorProduct.dualDistrib_not_surjective

-- Provider: EtingofRepresentationTheory.Chapter8.Theorem8_1_1
-- Chapter8/Theorem8.1.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Theorem_8_1_1_i_iff_ii
-- Chapter8/Theorem8.1.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Theorem_8_1_1_i_iff_iii
-- Chapter8/Theorem8.1.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Theorem_8_1_1_i_iff_iv

-- Provider: EtingofRepresentationTheory.Chapter8.Theorem8_1_5
-- Chapter8/Discussion_after_Exercise8.1.4.claim_coverage.claims[1].lean_decl,
-- Chapter8/Theorem8.1.5.claim_coverage.claims[1].lean_decl
#check @Etingof.Theorem_8_1_5_i_iff_ii
-- Chapter8/Discussion_after_Exercise8.1.4.claim_coverage.claims[1].lean_decl,
-- Chapter8/Theorem8.1.5.claim_coverage.claims[1].lean_decl
#check @Etingof.Theorem_8_1_5_i_iff_iii

-- Provider: EtingofRepresentationTheory.Chapter9.Exercise9_6_3
-- Chapter9/Exercise9.6.3.claim_coverage.claims[2].lean_decl
#check @Etingof.Exercise963.exists_progenerator
-- Chapter9/Exercise9.6.3.claim_coverage.claims[1].lean_decl
#check @Etingof.Exercise963.isProgenerator_iff_hom_simple_ne_zero

-- Provider: EtingofRepresentationTheory.Chapter9.FiniteProjectiveResolution
-- Chapter9/Problem9.4.2.claim_coverage.claims[5].lean_decl
#check @Etingof.FiniteProjectiveResolution.exists_finite_projectiveResolution
