import EtingofRepresentationTheory.Chapter5.Problem5_16_3
import EtingofRepresentationTheory.Chapter5.Problem5_1_2
import EtingofRepresentationTheory.Chapter5.Problem5_24_1
import EtingofRepresentationTheory.Chapter5.Problem5_24_1_b
import EtingofRepresentationTheory.Chapter5.Problem5_24_2
import EtingofRepresentationTheory.Chapter5.Problem5_24_2_Core
import EtingofRepresentationTheory.Chapter5.Problem5_2_7
import EtingofRepresentationTheory.Chapter5.Problem5_8_4
import EtingofRepresentationTheory.Chapter5.Proposition5_14_1
import EtingofRepresentationTheory.Chapter5.Proposition5_19_1
import EtingofRepresentationTheory.Chapter5.Proposition5_21_1
import EtingofRepresentationTheory.Chapter5.Proposition5_21_2

/-!
# Claim-ledger declaration pointers

Generated by `scripts/validate_lean_decls.py --apply`.
-/

-- Provider: EtingofRepresentationTheory.Chapter5.Problem5_16_3
-- Chapter5/Problem5.16.3.claim_coverage.claims[2].lean_decl
#check @Etingof.content_const_removeSquare_iff_rectangular
-- Chapter5/Problem5.16.3.claim_coverage.claims[2].lean_decl
#check @Etingof.sumTranspositionsStab_acts_scalar_iff_content_const
-- Chapter5/Problem5.16.3.claim_coverage.claims[1].lean_decl
#check @Etingof.sumTranspositionsWith1
-- Chapter5/Problem5.16.3.claim_coverage.claims[2].lean_decl
#check @Etingof.sumTranspositionsWith1_acts_scalar_iff_rectangular
-- Chapter5/Problem5.16.3.claim_coverage.claims[1].lean_decl
#check @Etingof.sumTranspositionsWith1_diagonalizable_integer_eigenvalues
-- Chapter5/Problem5.16.3.claim_coverage.claims[1].lean_decl
#check @Etingof.sumTranspositionsWith1_eq_sub
-- Chapter5/Problem5.16.3.claim_coverage.claims[1].lean_decl
#check @Etingof.sumTranspositionsWith1_hasEigenvalue_integer
-- Chapter5/Problem5.16.3.claim_coverage.claims[3].lean_decl
#check @Etingof.sumTranspositionsWith1_scalar_on_rectangular

-- Provider: EtingofRepresentationTheory.Chapter5.Problem5_1_2
-- Chapter5/Problem5.1.2.claim_coverage.claims[4].lean_decl
#check @Etingof.exists_real_form_of_isRealType
-- Chapter5/Problem5.1.2.claim_coverage.claims[4].lean_decl
#check @Etingof.isRealType_iff_exists_real_form
-- Chapter5/Problem5.1.2.claim_coverage.claims[4].lean_decl
#check @Etingof.isRealType_of_exists_real_form
-- Chapter5/Problem5.1.2.claim_coverage.claims[1].lean_decl,
-- Chapter5/Problem5.1.2.claim_coverage.claims[2].lean_decl,
-- Chapter5/Problem5.1.2.claim_coverage.claims[3].lean_decl
#check @Etingof.realGEndAlgebra
-- Chapter5/Problem5.1.2.claim_coverage.claims[1].lean_decl
#check @Etingof.realGEndAlgebra_equiv_complex_of_isComplexType
-- Chapter5/Problem5.1.2.claim_coverage.claims[2].lean_decl
#check @Etingof.realGEndAlgebra_equiv_matrix_of_isRealType
-- Chapter5/Problem5.1.2.claim_coverage.claims[3].lean_decl
#check @Etingof.realGEndAlgebra_equiv_quaternion_of_isQuaternionicType

-- Provider: EtingofRepresentationTheory.Chapter5.Problem5_24_1
-- Chapter5/Problem5.24.1.claim_coverage.claims[1].lean_decl
#check @Etingof.rowColIdeal
-- Chapter5/Problem5.24.1.claim_coverage.claims[1].lean_decl
#check @Etingof.rowColIdeal_iso_spechtModule

-- Provider: EtingofRepresentationTheory.Chapter5.Problem5_24_1_b
-- Chapter5/Problem5.24.1.claim_coverage.claims[3].lean_decl
#check @Etingof.conjugatePartition
-- Chapter5/Problem5.24.1.claim_coverage.claims[2].lean_decl
#check @Etingof.signTwist
-- Chapter5/Problem5.24.1.claim_coverage.claims[2].lean_decl
#check @Etingof.signTwist_bijective
-- Chapter5/Problem5.24.1.claim_coverage.claims[2].lean_decl
#check @Etingof.signTwist_map_leftIdeal
-- Chapter5/Problem5.24.1.claim_coverage.claims[2].lean_decl
#check @Etingof.signTwist_of
-- Chapter5/Problem5.24.1.claim_coverage.claims[2].lean_decl
#check @Etingof.signTwist_smul_of
-- Chapter5/Problem5.24.1.claim_coverage.claims[3].lean_decl
#check @Etingof.spechtModule_signTwist_iso_conjugate

-- Provider: EtingofRepresentationTheory.Chapter5.Problem5_24_2
-- Chapter5/Problem5.24.2.claim_coverage.claims[1].lean_decl, Chapter5/Problem5.24.2.lean_decl
#check @Etingof.invariantSubalgebra_eq_adjoin_traceWord

-- Provider: EtingofRepresentationTheory.Chapter5.Problem5_24_2_Core
-- Chapter5/Problem5.24.2.claim_coverage.claims[1].lean_decl
#check @Etingof.invariantSubalgebra
-- Chapter5/Problem5.24.2.claim_coverage.claims[1].lean_decl
#check @Etingof.traceWord

-- Provider: EtingofRepresentationTheory.Chapter5.Problem5_2_7
-- derived-from:Chapter5/Problem5.2.7.lean_ref
#check @Etingof.Problem5_2_7.beta_lt_one
-- Chapter5/Problem5.2.7.claim_coverage.claims[2].lean_decl, derived-
-- from:Chapter5/Problem5.2.7.lean_ref
#check @Etingof.Problem5_2_7.exists_character_eq_zero
-- Chapter5/Problem5.2.7.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem5_2_7.exists_finite_galois_field_of_definition

-- Provider: EtingofRepresentationTheory.Chapter5.Problem5_8_4
-- Chapter5/Problem5.8.4.claim_coverage.claims[1].lean_decl, Chapter5/Problem5.8.4.lean_decl
#check @Etingof.ind_ind_iso_ind

-- Provider: EtingofRepresentationTheory.Chapter5.Proposition5_14_1
-- Chapter5/Discussion_proof_of_Proposition5.14.1.claim_coverage.claims[1].lean_decl,
-- Chapter5/Proposition5.14.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Proposition5_14_1_diagonal
-- Chapter5/Discussion_proof_of_Proposition5.14.1.claim_coverage.claims[1].lean_decl,
-- Chapter5/Proposition5.14.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Proposition5_14_1_vanishing_general

-- Provider: EtingofRepresentationTheory.Chapter5.Proposition5_19_1
-- Chapter5/Proposition5.19.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Proposition5_19_1
-- Chapter5/Proposition5.19.1.claim_coverage.claims[2].lean_decl
#check @Etingof.Proposition5_19_1_centralizer

-- Provider: EtingofRepresentationTheory.Chapter5.Proposition5_21_1
-- Chapter5/Proposition5.21.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Proposition5_21_1
-- Chapter5/Discussion_Schur_polynomials.claim_coverage.claims[1].lean_decl
#check @Etingof.alternantMatrix
-- Chapter5/Discussion_Schur_polynomials.claim_coverage.claims[2].lean_decl
#check @Etingof.schurPoly
-- Chapter5/Discussion_Schur_polynomials.claim_coverage.claims[2].lean_decl
#check @Etingof.schurPoly_mul_vandermonde
-- Chapter5/Discussion_Schur_polynomials.claim_coverage.claims[1].lean_decl
#check @Etingof.shiftedExps
-- Chapter5/Discussion_Schur_polynomials.claim_coverage.claims[1].lean_decl
#check @Etingof.vandermondeExps

-- Provider: EtingofRepresentationTheory.Chapter5.Proposition5_21_2
-- Chapter5/Proposition5.21.2.claim_coverage.claims[2].lean_decl
#check @Etingof.Proposition5_21_2_dimension
-- Chapter5/Proposition5.21.2.claim_coverage.claims[1].lean_decl
#check @Etingof.Proposition5_21_2_geometric_complex_zpow
-- Chapter5/Proposition5.21.2.claim_coverage.claims[1].lean_decl
#check @Etingof.Proposition5_21_2_geometric_field
