import EtingofRepresentationTheory.Chapter5.Proposition5_19_1
import EtingofRepresentationTheory.Chapter5.Proposition5_21_1
import EtingofRepresentationTheory.Chapter5.Proposition5_21_2
import EtingofRepresentationTheory.Chapter5.Proposition5_25_1
import EtingofRepresentationTheory.Chapter5.Proposition5_2_3
import EtingofRepresentationTheory.Chapter5.Proposition5_2_4
import EtingofRepresentationTheory.Chapter5.Proposition5_2_5
import EtingofRepresentationTheory.Chapter5.Proposition5_3_2
import EtingofRepresentationTheory.Chapter5.Remark5_15_2
import EtingofRepresentationTheory.Chapter5.Remark5_15_5
import EtingofRepresentationTheory.Chapter5.Remark5_23_3
import EtingofRepresentationTheory.Chapter5.Remark5_26_2

/-!
# Claim-ledger declaration pointers

Generated by `scripts/validate_lean_decls.py --apply`.
-/

set_option linter.style.longLine false

-- Provider: EtingofRepresentationTheory.Chapter5.Proposition5_19_1
-- Chapter5/Proposition5.19.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Proposition5_19_1
-- Chapter5/Proposition5.19.1.claim_coverage.claims[2].lean_decl
#check @Etingof.Proposition5_19_1_centralizer

-- Provider: EtingofRepresentationTheory.Chapter5.Proposition5_21_1
-- Chapter5/Proposition5.21.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Proposition5_21_1
-- Chapter5/Discussion_Schur_polynomials.claim_coverage.claims[1].lean_decl
#check @Etingof.alternantMatrix
-- Chapter5/Discussion_hook_length_derivation.claim_coverage.claims[1].lean_decl
#check @Etingof.charValue
-- Chapter5/Discussion_Schur_polynomials.claim_coverage.claims[2].lean_decl
#check @Etingof.schurPoly
-- Chapter5/Discussion_Schur_polynomials.claim_coverage.claims[2].lean_decl
#check @Etingof.schurPoly_mul_vandermonde
-- Chapter5/Discussion_Schur_polynomials.claim_coverage.claims[1].lean_decl
#check @Etingof.shiftedExps
-- Chapter5/Discussion_Schur_polynomials.claim_coverage.claims[1].lean_decl
#check @Etingof.vandermondeExps

-- Provider: EtingofRepresentationTheory.Chapter5.Proposition5_21_2
-- Chapter5/Proposition5.21.2.claim_coverage.claims[2].lean_decl
#check @Etingof.Proposition5_21_2_dimension
-- Chapter5/Proposition5.21.2.claim_coverage.claims[1].lean_decl
#check @Etingof.Proposition5_21_2_geometric_complex_zpow
-- Chapter5/Proposition5.21.2.claim_coverage.claims[1].lean_decl
#check @Etingof.Proposition5_21_2_geometric_field

-- Provider: EtingofRepresentationTheory.Chapter5.Proposition5_25_1
-- Chapter5/Proposition5.25.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Proposition5_25_1

-- Provider: EtingofRepresentationTheory.Chapter5.Proposition5_2_3
-- Chapter5/Proposition5.2.3.claim_coverage.claims[3].lean_decl
#check @Etingof.Proposition5_2_3.charpoly_companionMatrix
-- Chapter5/Proposition5.2.3.claim_coverage.claims[3].lean_decl
#check @Etingof.Proposition5_2_3.charpoly_map_companionMatrix_isRoot
-- Chapter5/Proposition5.2.3.claim_coverage.claims[3].lean_decl
#check @Etingof.Proposition5_2_3.companionMatrix
-- Chapter5/Proposition5.2.3.claim_coverage.claims[1].lean_decl
#check @Etingof.Proposition5_2_3_algebraic
-- Chapter5/Proposition5.2.3.claim_coverage.claims[3].lean_decl
#check @Etingof.Proposition5_2_3_companion_algebraic
-- Chapter5/Proposition5.2.3.claim_coverage.claims[3].lean_decl
#check @Etingof.Proposition5_2_3_companion_integer
-- Chapter5/Proposition5.2.3.claim_coverage.claims[2].lean_decl
#check @Etingof.Proposition5_2_3_integer

-- Provider: EtingofRepresentationTheory.Chapter5.Proposition5_2_4
-- Chapter5/Proposition5.2.4.claim_coverage.claims[2].lean_decl
#check @Etingof.Proposition5_2_4_field
-- Chapter5/Proposition5.2.4.claim_coverage.claims[2].lean_decl
#check @Etingof.Proposition5_2_4_isAlgClosed
-- Chapter5/Proposition5.2.4.claim_coverage.claims[2].lean_decl
#check @Etingof.Proposition5_2_4_isAlgClosure
-- Chapter5/Proposition5.2.4.claim_coverage.claims[2].lean_decl
#check @Etingof.Proposition5_2_4_isAlgebraic
-- Chapter5/Proposition5.2.4.claim_coverage.claims[1].lean_decl
#check @Etingof.Proposition5_2_4_ring
-- Chapter5/Discussion_after_Proposition5.2.3.claim_coverage.claims[1].lean_decl,
-- Chapter5/Proposition5.2.4.claim_coverage.claims[1].lean_decl
#check @Etingof.algebraicIntegers
-- Chapter5/Discussion_after_Proposition5.2.3.claim_coverage.claims[1].lean_decl,
-- Chapter5/Proposition5.2.4.claim_coverage.claims[2].lean_decl
#check @Etingof.algebraicNumbers
-- Chapter5/Discussion_after_Proposition5.2.3.claim_coverage.claims[1].lean_decl
#check @Etingof.mem_algebraicIntegers
-- Chapter5/Discussion_after_Proposition5.2.3.claim_coverage.claims[1].lean_decl
#check @Etingof.mem_algebraicNumbers

-- Provider: EtingofRepresentationTheory.Chapter5.Proposition5_2_5
-- Chapter5/Discussion_proof_of_Theorem5.3.1.claim_coverage.claims[3].lean_decl,
-- Chapter5/Proposition5.2.5.claim_coverage.claims[1].lean_decl
#check @Etingof.Proposition5_2_5

-- Provider: EtingofRepresentationTheory.Chapter5.Proposition5_3_2
-- Chapter5/Discussion_proof_of_Theorem5.3.1.claim_coverage.claims[1].lean_decl,
-- Chapter5/Proposition5.3.2.claim_coverage.claims[1].lean_decl,
-- Chapter5/Proposition5.3.2.claim_coverage.claims[2].lean_decl,
-- Chapter5/Theorem5.3.1.claim_coverage.claims[2].lean_decl
#check @Etingof.Proposition5_3_2

-- Provider: EtingofRepresentationTheory.Chapter5.Remark5_15_2
-- Chapter5/Remark5.15.2.claim_coverage.claims[1].lean_decl
#check @Etingof.Remark5_15_2
-- Chapter5/Remark5.15.2.claim_coverage.claims[1].lean_decl
#check @Etingof.Remark5_15_2_equiv_Theorem5_15_1
-- Chapter5/Remark5.15.2.claim_coverage.claims[1].lean_decl
#check @Etingof.rho_monomial_mul_frobeniusLaurentFactor

-- Provider: EtingofRepresentationTheory.Chapter5.Remark5_15_5
-- Chapter5/Remark5.15.5.claim_coverage.claims[2].lean_decl
#check @Etingof.inverseKostkaMatrix_eq_zero_of_not_rootLe
-- Chapter5/Remark5.15.5.claim_coverage.claims[1].lean_decl
#check @Etingof.rootLe_isPartialOrder
-- Chapter5/Remark5.15.5.claim_coverage.claims[2].lean_decl
#check @Etingof.spechtCharacter_eq_sum_inverseKostka_rootLe
-- Chapter5/Remark5.15.5.claim_coverage.claims[3].lean_decl
#check @Etingof.spechtMultiplicity_vanishing_rootOrder
-- Chapter5/Remark5.15.5.claim_coverage.claims[1].lean_decl
#check @Nat.Partition.rootLe_iff_dominates

-- Provider: EtingofRepresentationTheory.Chapter5.Remark5_23_3
-- Chapter5/Remark5.23.3.claim_coverage.claims[1].lean_decl
#check @Etingof.algIrrepGL_slEquiv_constShift
-- Chapter5/Remark5.23.3.claim_coverage.claims[3].lean_decl
#check @Etingof.slIrrepEquiv
-- Chapter5/Remark5.23.3.claim_coverage.claims[2].lean_decl
#check @Etingof.slIso_shiftEquiv

-- Provider: EtingofRepresentationTheory.Chapter5.Remark5_26_2
-- Chapter5/Remark5.26.2.claim_coverage.claims[1].lean_decl,
-- Chapter5/Remark5.26.2.claim_coverage.claims[2].lean_decl
#check @Etingof.Remark5_26_2
