import EtingofRepresentationTheory.Chapter3.CommutatorMatrixTraceless
import EtingofRepresentationTheory.Chapter3.Corollary3_2_1
import EtingofRepresentationTheory.Chapter3.Corollary3_5_5
import EtingofRepresentationTheory.Chapter3.Definition3_1_1
import EtingofRepresentationTheory.Chapter3.Definition3_3_2
import EtingofRepresentationTheory.Chapter3.Definition3_4_1
import EtingofRepresentationTheory.Chapter3.Definition3_5_1
import EtingofRepresentationTheory.Chapter3.Definition3_5_7
import EtingofRepresentationTheory.Chapter3.Discussion_after_Theorem3_7_1
import EtingofRepresentationTheory.Chapter3.Discussion_alternative_proof_of_Proposition3_1_4
import EtingofRepresentationTheory.Chapter3.Discussion_footnote_3_7_1
import EtingofRepresentationTheory.Chapter3.Example3_1_2

/-!
# Claim-ledger declaration pointers

Generated by `scripts/validate_lean_decls.py --apply`.
-/

set_option linter.style.longLine false

-- Provider: EtingofRepresentationTheory.Chapter3.CommutatorMatrixTraceless
-- Chapter3/Theorem3.6.2.claim_coverage.claims[5].lean_decl,
-- Chapter3/Theorem3.6.2.claim_coverage.claims[6].lean_decl,
-- Chapter3/Theorem3.6.2.claim_coverage.claims[8].lean_decl,
-- Chapter3/Theorem3.6.2.claim_coverage.claims[9].lean_decl
#check @Etingof.commutatorSubmodule_matrix_eq_ker_trace
-- Chapter3/Theorem3.6.2.claim_coverage.claims[11].lean_decl,
-- Chapter3/Theorem3.6.2.claim_coverage.claims[5].lean_decl
#check @Etingof.commutatorSubmodule_matrix_fin_eq_ker_trace

-- Provider: EtingofRepresentationTheory.Chapter3.Corollary3_2_1
-- Chapter3/Corollary3.2.1.claim_coverage.claims[1].lean_decl, Chapter3/Corollary3.2.1.lean_decl,
-- Chapter3/Introduction_to_3.2.claim_coverage.claims[2].lean_decl,
-- Chapter3/Theorem3.2.2.claim_coverage.claims[2].lean_decl
#check @Etingof.irreducible_interpolation

-- Provider: EtingofRepresentationTheory.Chapter3.Corollary3_5_5
-- Chapter3/Corollary3.5.5.claim_coverage.claims[1].lean_decl
#check @Etingof.sum_dim_sq_le_dim

-- Provider: EtingofRepresentationTheory.Chapter3.Definition3_1_1
-- Chapter3/Definition3.1.1.claim_coverage.claims[1].lean_decl
#check @Etingof.IsSemisimpleRepresentation

-- Provider: EtingofRepresentationTheory.Chapter3.Definition3_3_2
-- Chapter3/Definition3.3.2.claim_coverage.claims[1].lean_decl
#check @Etingof.DualRepresentation
-- Chapter3/Definition3.3.2.claim_coverage.claims[3].lean_decl
#check @Etingof.dualRepresentation_smul_apply
-- Chapter3/Definition3.3.2.claim_coverage.claims[2].lean_decl
#check @Etingof.instModuleMulOppositeDual
-- Chapter3/Definition3.3.2.claim_coverage.claims[2].lean_decl
#check @Etingof.instSMulMulOppositeDual

-- Provider: EtingofRepresentationTheory.Chapter3.Definition3_4_1
-- Chapter3/Definition3.4.1.claim_coverage.claims[1].lean_decl,
-- Chapter3/Definition3.4.1.claim_coverage.claims[2].lean_decl,
-- Chapter3/Definition3.4.1.claim_coverage.claims[4].lean_decl
#check @Etingof.Filtration.chain
-- Chapter3/Definition3.4.1.claim_coverage.claims[3].lean_decl
#check @Etingof.Filtration.head_eq_bot
-- Chapter3/Definition3.4.1.claim_coverage.claims[5].lean_decl
#check @Etingof.Filtration.last_eq_top

-- Provider: EtingofRepresentationTheory.Chapter3.Definition3_5_1
-- Chapter3/Definition3.5.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Radical
-- Chapter3/Definition3.5.1.claim_coverage.claims[1].lean_decl
#check @Etingof.mem_radical_iff

-- Provider: EtingofRepresentationTheory.Chapter3.Definition3_5_7
-- Chapter3/Definition3.5.7.claim_coverage.claims[1].lean_decl
#check @Etingof.IsSemisimpleAlgebra
-- Chapter3/Definition3.5.7.claim_coverage.claims[1].lean_decl
#check @Etingof.isSemisimpleAlgebra_iff_isSemisimpleRing

-- Provider: EtingofRepresentationTheory.Chapter3.Discussion_after_Theorem3_7_1
-- Chapter3/Discussion_after_Theorem3.7.1.claim_coverage.claims[3].lean_decl
#check @Etingof.jordanHolder_length_isGreatest_strict

-- Provider: EtingofRepresentationTheory.Chapter3.Discussion_alternative_proof_of_Proposition3_1_4
-- Chapter3/Discussion_alternative_proof_of_Proposition3.1.4.claim_coverage.claims[5].lean_decl
#check @Etingof.bijective_iff
-- Chapter3/Discussion_alternative_proof_of_Proposition3.1.4.claim_coverage.claims[1].lean_decl
#check @Etingof.homPiHomEquiv
-- Chapter3/Discussion_alternative_proof_of_Proposition3.1.4.claim_coverage.claims[2].lean_decl
#check @Etingof.homPiHomEquiv_apply
-- Chapter3/Discussion_alternative_proof_of_Proposition3.1.4.claim_coverage.claims[3].lean_decl
#check @Etingof.injective_iff
-- Chapter3/Discussion_after_Lemma3.1.6.claim_coverage.claims[3].lean_decl
#check @Etingof.mem_ker_iff_components
-- Chapter3/Discussion_alternative_proof_of_Proposition3.1.4.claim_coverage.claims[2].lean_decl
#check @Etingof.postcompHom
-- Chapter3/Discussion_after_Lemma3.1.6.claim_coverage.claims[2].lean_decl,
-- Chapter3/Discussion_alternative_proof_of_Proposition3.1.4.claim_coverage.claims[2].lean_decl
#check @Etingof.postcompHom_apply
-- Chapter3/Discussion_alternative_proof_of_Proposition3.1.4.claim_coverage.claims[6].lean_decl
#check @Etingof.postcompHom_comp
-- Chapter3/Discussion_alternative_proof_of_Proposition3.1.4.claim_coverage.claims[6].lean_decl
#check @Etingof.postcompHom_id
-- Chapter3/Discussion_after_Lemma3.1.6.claim_coverage.claims[2].lean_decl
#check @Etingof.restrictScalars_eq
-- Chapter3/Discussion_alternative_proof_of_Proposition3.1.4.claim_coverage.claims[4].lean_decl
#check @Etingof.surjective_iff

-- Provider: EtingofRepresentationTheory.Chapter3.Discussion_footnote_3_7_1
-- Chapter3/Theorem3.7.1.claim_coverage.claims[6].lean_decl,
-- Chapter3/Theorem3.7.1.claim_coverage.claims[9].lean_decl
#check @Etingof.character_fin_pi
-- Chapter3/Theorem3.7.1.claim_coverage.claims[10].lean_decl,
-- Chapter3/Theorem3.7.1.claim_coverage.claims[9].lean_decl
#check @Etingof.character_pcopies_eq_zero

-- Provider: EtingofRepresentationTheory.Chapter3.Example3_1_2
-- Chapter3/Example3.1.2.claim_coverage.claims[1].lean_decl
#check @Etingof.endEquivPi
-- Chapter3/Example3.1.2.claim_coverage.claims[1].lean_decl
#check @Etingof.endEquivPiOfBasis
-- Chapter3/Example3.1.2.claim_coverage.claims[1].lean_decl
#check @Etingof.endEquivPiOfBasis_apply
-- Chapter3/Example3.1.2.claim_coverage.claims[1].lean_decl
#check @Etingof.endEquivPi_apply
-- Chapter3/Example3.1.2.claim_coverage.claims[2].lean_decl
#check @Etingof.endomorphism_semisimple
