import EtingofRepresentationTheory.Chapter4.Example4_8_1.A5Reps
import EtingofRepresentationTheory.Chapter4.Example4_8_1.S4
import EtingofRepresentationTheory.Chapter4.Example4_8_1.S4Quotient
import EtingofRepresentationTheory.Chapter4.Example4_9_1
import EtingofRepresentationTheory.Chapter4.Exercise4_2_3_Assembly
import EtingofRepresentationTheory.Chapter4.Exercise4_3_1
import EtingofRepresentationTheory.Chapter4.Introduction_4_2
import EtingofRepresentationTheory.Chapter4.Introduction_4_8
import EtingofRepresentationTheory.Chapter4.Introduction_4_9
import EtingofRepresentationTheory.Chapter4.Lemma4_10_3
import EtingofRepresentationTheory.Chapter4.Problem4_12_1
import EtingofRepresentationTheory.Chapter4.Problem4_12_10

/-!
# Claim-ledger declaration pointers

Generated by `scripts/validate_lean_decls.py --apply`.
-/

set_option linter.style.longLine false

-- Provider: EtingofRepresentationTheory.Chapter4.Example4_8_1.A5Reps
-- Chapter4/Example4.8.1.claim_coverage.claims[5].lean_decl
#check @Etingof.Example4_8_1.A5.repC4
-- Chapter4/Example4.8.1.claim_coverage.claims[5].lean_decl
#check @Etingof.Example4_8_1.A5.repC5

-- Provider: EtingofRepresentationTheory.Chapter4.Example4_8_1.S4
-- Chapter4/Example4.8.1.claim_coverage.claims[3].lean_decl
#check @Etingof.Example4_8_1.S4.repStdPlus

-- Provider: EtingofRepresentationTheory.Chapter4.Example4_8_1.S4Quotient
-- Chapter4/Example4.8.1.claim_coverage.claims[3].lean_decl
#check @Etingof.Example4_3_S4.quotientKleinFourEquivS3
-- Chapter4/Example4.8.1.claim_coverage.claims[3].lean_decl
#check @Etingof.Example4_8_1.S4.repC2_iso_s3StandardPullback

-- Provider: EtingofRepresentationTheory.Chapter4.Example4_9_1
-- Chapter4/Example4.9.1.claim_coverage.claims[3].lean_decl
#check @Etingof.Example4_9_1.A5_tensor_iso
-- Chapter4/Example4.9.1.claim_coverage.claims[3].lean_decl
#check @Etingof.Example4_9_1.A5_tensor_iso_biproduct
-- Chapter4/Example4.9.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Example4_9_1.S3_tensor_iso
-- Chapter4/Example4.9.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Example4_9_1.S3_tensor_iso_biproduct
-- Chapter4/Example4.9.1.claim_coverage.claims[2].lean_decl
#check @Etingof.Example4_9_1.S4_tensor_iso
-- Chapter4/Example4.9.1.claim_coverage.claims[2].lean_decl
#check @Etingof.Example4_9_1.S4_tensor_iso_biproduct
-- Chapter4/Example4.9.1.claim_coverage.claims[4].lean_decl
#check @Etingof.Example4_9_1.stdRep_tensor_stdRep_iso

-- Provider: EtingofRepresentationTheory.Chapter4.Exercise4_2_3_Assembly
-- Chapter4/Exercise4.2.3.claim_coverage.claims[1].lean_decl
#check @Etingof.Exercise4_2_3
-- Chapter4/Exercise4.2.3.claim_coverage.claims[1].lean_decl
#check @Etingof.natCard_irrepClasses_lt_conjClasses_of_isAlgClosed

-- Provider: EtingofRepresentationTheory.Chapter4.Exercise4_3_1
-- Chapter4/Exercise4.3.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Exercise4_3_1.covariantSubspace_finrank
-- Chapter4/Exercise4.3.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Exercise4_3_1.covariantSubspace_invariant
-- Chapter4/Exercise4.3.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Exercise4_3_1.covariantSubspace_irreducible

-- Provider: EtingofRepresentationTheory.Chapter4.Introduction_4_2
-- Chapter4/Introduction_4.2.claim_coverage.claims[2].lean_decl
#check @Etingof.FDRep.character_eq_algebraCharacter
-- Chapter4/Introduction_4.2.claim_coverage.claims[3].lean_decl
#check @Etingof.FDRep.character_mem_classFunctionSubmodule
-- Chapter4/Introduction_4.2.claim_coverage.claims[4].lean_decl
#check @Etingof.FunctionSpace
-- Chapter4/Introduction_4.2.claim_coverage.claims[5].lean_decl
#check @Etingof.classFunctionSubmodule
-- Chapter4/Introduction_4.2.claim_coverage.claims[5].lean_decl
#check @Etingof.mem_classFunctionSubmodule_iff

-- Provider: EtingofRepresentationTheory.Chapter4.Introduction_4_8
-- Chapter4/Introduction_4.8.claim_coverage.claims[3].lean_decl
#check @Etingof.Introduction_4_8_A4_character
-- Chapter4/Introduction_4.8.claim_coverage.claims[3].lean_decl
#check @Etingof.Introduction_4_8_A4_class_sizes
-- Chapter4/Introduction_4.8.claim_coverage.claims[3].lean_decl
#check @Etingof.Introduction_4_8_A4_complete
-- Chapter4/Introduction_4.8.claim_coverage.claims[3].lean_decl
#check @Etingof.Introduction_4_8_A4_pairwise
-- Chapter4/Introduction_4.8.claim_coverage.claims[3].lean_decl
#check @Etingof.Introduction_4_8_A4_quotient
-- Chapter4/Introduction_4.8.claim_coverage.claims[3].lean_decl
#check @Etingof.Introduction_4_8_A4_simple

-- Provider: EtingofRepresentationTheory.Chapter4.Introduction_4_9
-- Chapter4/Introduction_4.9.claim_coverage.claims[2].lean_decl
#check @Etingof.exists_tensorDecomposition
-- Chapter4/Introduction_4.9.claim_coverage.claims[2].lean_decl
#check @Etingof.tensorDecomposition
-- Chapter4/Introduction_4.9.claim_coverage.claims[1].lean_decl
#check @Etingof.tensorMultiplicity
-- Chapter4/Introduction_4.9.claim_coverage.claims[1].lean_decl
#check @Etingof.tensorMultiplicity_eq_inner

-- Provider: EtingofRepresentationTheory.Chapter4.Lemma4_10_3
-- Chapter4/Lemma4.10.3.claim_coverage.claims[1].lean_decl,
-- Chapter4/Lemma4.10.3.claim_coverage.claims[2].lean_decl
#check @Etingof.Lemma4_10_3

-- Provider: EtingofRepresentationTheory.Chapter4.Problem4_12_1
-- Chapter4/Problem4.12.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem4_12_1.Vrep
-- Chapter4/Problem4.12.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem4_12_1.Vrep_irreducible
-- Chapter4/Problem4.12.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem4_12_1.Vrep_not_iso
-- Chapter4/Problem4.12.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem4_12_1.charEquiv
-- Chapter4/Problem4.12.1.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem4_12_1.chiRot2
-- Chapter4/Problem4.12.1.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem4_12_1.chiRot2_eq_Vrep2_character
-- Chapter4/Problem4.12.1.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem4_12_1.chiSign
-- Chapter4/Problem4.12.1.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem4_12_1.chiStd
-- Chapter4/Problem4.12.1.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem4_12_1.chiStd_eq_Vrep1_character
-- Chapter4/Problem4.12.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem4_12_1.irreducible_dim
-- Chapter4/Problem4.12.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem4_12_1.irreps_sum_sq
-- Chapter4/Problem4.12.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem4_12_1.one_dim_reps_card_even
-- Chapter4/Problem4.12.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem4_12_1.one_dim_reps_card_odd
-- Chapter4/Problem4.12.1.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem4_12_1.rhsRep
-- Chapter4/Problem4.12.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem4_12_1.simple_iso_char_or_Vrep
-- Chapter4/Problem4.12.1.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem4_12_1.tensor_square_character
-- Chapter4/Problem4.12.1.claim_coverage.claims[2].lean_decl
#check @Etingof.Problem4_12_1.tensor_square_decomposition
-- Chapter4/Problem4.12.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem4_12_1.total_irreps_card_even
-- Chapter4/Problem4.12.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem4_12_1.total_irreps_card_odd
-- Chapter4/Problem4.12.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem4_12_1.two_dim_simples_card_even
-- Chapter4/Problem4.12.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Problem4_12_1.two_dim_simples_card_odd

-- Provider: EtingofRepresentationTheory.Chapter4.Problem4_12_10
-- Chapter4/Problem4.12.10.claim_coverage.claims[3].lean_decl
#check @Etingof.Problem4_12_10
