import EtingofRepresentationTheory.Chapter6.Proposition6_6_8
import EtingofRepresentationTheory.Chapter6.Remark6_4_11
import EtingofRepresentationTheory.Chapter6.Remark6_4_4
import EtingofRepresentationTheory.Chapter6.Theorem6_5_2
import EtingofRepresentationTheory.Chapter6.Theorem6_8_1
import EtingofRepresentationTheory.Chapter6.Theorem_Dynkin_classification
import EtingofRepresentationTheory.Chapter7.Definition7_1_1
import EtingofRepresentationTheory.Chapter7.Definition7_1_4
import EtingofRepresentationTheory.Chapter7.Definition7_2_1
import EtingofRepresentationTheory.Chapter7.Definition7_3_1
import EtingofRepresentationTheory.Chapter7.Definition7_4_1
import EtingofRepresentationTheory.Chapter7.Definition7_6_1

/-!
# Claim-ledger declaration pointers

Generated by `scripts/validate_lean_decls.py --apply`.
-/

set_option linter.style.longLine false

-- Provider: EtingofRepresentationTheory.Chapter6.Proposition6_6_8
-- Chapter6/Proposition6.6.8.claim_coverage.claims[1].lean_decl
#check @Etingof.Proposition6_6_8_sink
-- Chapter6/Proposition6.6.8.claim_coverage.claims[1].lean_decl
#check @Etingof.Proposition6_6_8_source

-- Provider: EtingofRepresentationTheory.Chapter6.Remark6_4_11
-- Chapter6/Remark6.4.11.claim_coverage.claims[2].lean_decl
#check @Etingof.Remark_6_4_11_weylGroup_finite
-- Chapter6/Remark6.4.11.claim_coverage.claims[1].lean_decl
#check @Etingof.rootReflection_apply_of_orthogonal
-- Chapter6/Remark6.4.11.claim_coverage.claims[1].lean_decl
#check @Etingof.rootReflection_apply_self
-- Chapter6/Remark6.4.11.claim_coverage.claims[1].lean_decl
#check @Etingof.rootReflection_dotProduct
-- Chapter6/Remark6.4.11.claim_coverage.claims[2].lean_decl
#check @Etingof.weylRootPerm_injective

-- Provider: EtingofRepresentationTheory.Chapter6.Remark6_4_4
-- Chapter6/Remark6.4.4.claim_coverage.claims[1].lean_decl
#check @Etingof.Remark_6_4_4_roots_finite

-- Provider: EtingofRepresentationTheory.Chapter6.Theorem6_5_2
-- Chapter6/Discussion_after_Example6.3.1.claim_coverage.claims[1].lean_decl,
-- Chapter6/Theorem6.5.2.claim_coverage.claims[3].lean_decl, Chapter6/Theorem6.5.2.lean_ref
#check @Etingof.Theorem_6_5_2_Gabriels_theorem
-- Chapter6/Theorem6.5.2.claim_coverage.claims[1].lean_decl, Chapter6/Theorem6.5.2.lean_ref
#check @Etingof.Theorem_6_5_2a_finiteness
-- Chapter6/Theorem6.5.2.claim_coverage.claims[2].lean_decl, Chapter6/Theorem6.5.2.lean_ref
#check @Etingof.Theorem_6_5_2b_dimvec_is_positive_root
-- Chapter6/Theorem6.5.2.claim_coverage.claims[3].lean_decl, Chapter6/Theorem6.5.2.lean_ref
#check @Etingof.Theorem_6_5_2c_bijection

-- Provider: EtingofRepresentationTheory.Chapter6.Theorem6_8_1
-- Chapter6/Theorem6.8.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Theorem6_8_1

-- Provider: EtingofRepresentationTheory.Chapter6.Theorem_Dynkin_classification
-- Chapter2/Theorem2.1.2.claim_coverage.claims[3].lean_decl,
-- Chapter6/Theorem_Dynkin_classification.claim_coverage.claims[1].lean_decl
#check @Etingof.Theorem_Dynkin_classification

-- Provider: EtingofRepresentationTheory.Chapter7.Definition7_1_1
-- Chapter7/Definition7.1.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Category

-- Provider: EtingofRepresentationTheory.Chapter7.Definition7_1_4
-- Chapter7/Definition7.1.4.claim_coverage.claims[1].lean_decl
#check @Etingof.FullSubcategory

-- Provider: EtingofRepresentationTheory.Chapter7.Definition7_2_1
-- Chapter7/Definition7.2.1.claim_coverage.claims[1].lean_decl,
-- Chapter7/Introduction_7.2.claim_coverage.claims[1].lean_decl
#check @Etingof.Functor

-- Provider: EtingofRepresentationTheory.Chapter7.Definition7_3_1
-- Chapter7/Definition7.3.1.claim_coverage.claims[1].lean_decl
#check @Etingof.NatTrans

-- Provider: EtingofRepresentationTheory.Chapter7.Definition7_4_1
-- Chapter7/Definition7.4.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Equivalence

-- Provider: EtingofRepresentationTheory.Chapter7.Definition7_6_1
-- Chapter7/Definition7.6.1.claim_coverage.claims[1].lean_decl
#check @Etingof.Adjunction
