/-
Copyright (c) 2026 mathlib-initiative. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/
import Mathlib.Algebra.FreeAlgebra
import Mathlib.Algebra.RingQuot
import Mathlib.LinearAlgebra.Basis.VectorSpace
import Mathlib.Algebra.Polynomial.Derivative
import Mathlib.Algebra.Polynomial.AlgebraMap
import Mathlib.Algebra.CharP.Basic
import RepresentationTheory.Alignment.Attribute

/-! # Polynomial operator algebra -/

namespace RepresentationTheory.FreeAlgebra.PolynomialOperators

variable (k : Type*) [CommRing k]

/-- The type of generators for the free algebra appearing in this construction. -/
abbrev freeAlgebraGenerator := Fin 2

/-- One distinguished element of the free algebra on the displayed generator type. -/
noncomputable abbrev freeAlgebraGeneratorLeft : FreeAlgebra k freeAlgebraGenerator := FreeAlgebra.ι k (0 : Fin 2)

/-- Another distinguished element of the free algebra on the displayed generator type. -/
noncomputable abbrev freeAlgebraGeneratorRight : FreeAlgebra k freeAlgebraGenerator := FreeAlgebra.ι k (1 : Fin 2)

/-- The binary proposition on the free algebra used in the construction. -/
def freeAlgebraRelation : FreeAlgebra k freeAlgebraGenerator → FreeAlgebra k freeAlgebraGenerator → Prop :=
  fun a b => a = freeAlgebraGeneratorRight k * freeAlgebraGeneratorLeft k ∧ b = freeAlgebraGeneratorLeft k * freeAlgebraGeneratorRight k + 1

/-- The algebra generated by the displayed polynomial operators. -/
@[source_ref "Chapter2/Discussion_2.7_intro" (role := supporting)]
noncomputable abbrev OperatorAlgebra : Type _ := RingQuot (freeAlgebraRelation k)

/-- The algebra homomorphism from the free algebra into the operator algebra. -/
noncomputable def OperatorAlgebra.fromFreeAlgebra : FreeAlgebra k freeAlgebraGenerator →ₐ[k] OperatorAlgebra k :=
  RingQuot.mkAlgHom k (freeAlgebraRelation k)

/-- The first distinguished element of the operator algebra. -/
noncomputable def OperatorAlgebra.firstOperator : OperatorAlgebra k := OperatorAlgebra.fromFreeAlgebra k (freeAlgebraGeneratorLeft k)

/-- The second distinguished element of the operator algebra. -/
noncomputable def OperatorAlgebra.secondOperator : OperatorAlgebra k := OperatorAlgebra.fromFreeAlgebra k (freeAlgebraGeneratorRight k)

/-- The operator-algebra element indexed by a pair of natural numbers. -/
noncomputable def OperatorAlgebra.monomialOperator (i j : ℕ) : OperatorAlgebra k :=
  OperatorAlgebra.firstOperator k ^ i * OperatorAlgebra.secondOperator k ^ j

/-- The distinguished operators satisfy the displayed commutation relation. -/
@[source_ref "Chapter2/Discussion_2.7_intro" (role := supporting)]
lemma OperatorAlgebra.secondOperator_mul_firstOperator :
    OperatorAlgebra.secondOperator k * OperatorAlgebra.firstOperator k = OperatorAlgebra.firstOperator k * OperatorAlgebra.secondOperator k + 1 := by
  have h := RingQuot.mkAlgHom_rel k
    (show freeAlgebraRelation k (freeAlgebraGeneratorRight k * freeAlgebraGeneratorLeft k) (freeAlgebraGeneratorLeft k * freeAlgebraGeneratorRight k + 1) from ⟨rfl, rfl⟩)
  simp only [map_mul, map_add, map_one] at h
  exact h

private noncomputable abbrev monomialSpan : Submodule k (OperatorAlgebra k) :=
  Submodule.span k (Set.range (fun p : ℕ × ℕ => OperatorAlgebra.monomialOperator k p.1 p.2))

private lemma monomialOperator_mem_span (i j : ℕ) : OperatorAlgebra.monomialOperator k i j ∈ monomialSpan k :=
  Submodule.subset_span ⟨(i, j), rfl⟩

private lemma firstOperator_mul_mem_span {a : OperatorAlgebra k} (ha : a ∈ monomialSpan k) :
    OperatorAlgebra.firstOperator k * a ∈ monomialSpan k := by
  apply Submodule.span_induction
    (p := fun a (_ : a ∈ monomialSpan k) => OperatorAlgebra.firstOperator k * a ∈ monomialSpan k)
  · intro z hz
    obtain ⟨⟨i, j⟩, rfl⟩ := hz
    have : OperatorAlgebra.firstOperator k * OperatorAlgebra.monomialOperator k i j = OperatorAlgebra.monomialOperator k (i + 1) j := by
      simp only [OperatorAlgebra.monomialOperator, pow_succ', mul_assoc]
    rw [this]; exact monomialOperator_mem_span k (i + 1) j
  · rw [mul_zero]; exact (monomialSpan k).zero_mem
  · intro _ _ _ _ ha hb; rw [mul_add]; exact (monomialSpan k).add_mem ha hb
  · intro c _ _ ha; rw [mul_smul_comm]; exact (monomialSpan k).smul_mem c ha
  · exact ha

private lemma mul_secondOperator_mem_span {a : OperatorAlgebra k} (ha : a ∈ monomialSpan k) :
    a * OperatorAlgebra.secondOperator k ∈ monomialSpan k := by
  apply Submodule.span_induction
    (p := fun a (_ : a ∈ monomialSpan k) => a * OperatorAlgebra.secondOperator k ∈ monomialSpan k)
  · intro z hz
    obtain ⟨⟨i, j⟩, rfl⟩ := hz
    have : OperatorAlgebra.monomialOperator k i j * OperatorAlgebra.secondOperator k = OperatorAlgebra.monomialOperator k i (j + 1) := by
      simp only [OperatorAlgebra.monomialOperator, pow_succ, mul_assoc]
    rw [this]; exact monomialOperator_mem_span k i (j + 1)
  · rw [zero_mul]; exact (monomialSpan k).zero_mem
  · intro _ _ _ _ ha hb; rw [add_mul]; exact (monomialSpan k).add_mem ha hb
  · intro c _ _ ha; rw [smul_mul_assoc]; exact (monomialSpan k).smul_mem c ha
  · exact ha

private lemma monomialOperator_mul_firstOperator_mem_span (i j : ℕ) :
    OperatorAlgebra.monomialOperator k i j * OperatorAlgebra.firstOperator k ∈ monomialSpan k := by
  induction j with
  | zero =>
    have : OperatorAlgebra.monomialOperator k i 0 * OperatorAlgebra.firstOperator k = OperatorAlgebra.monomialOperator k (i + 1) 0 := by
      simp only [OperatorAlgebra.monomialOperator, pow_zero, mul_one, pow_succ]
    rw [this]; exact monomialOperator_mem_span k (i + 1) 0
  | succ n ih =>

    have key : OperatorAlgebra.monomialOperator k i (n + 1) * OperatorAlgebra.firstOperator k =
        OperatorAlgebra.monomialOperator k i n * OperatorAlgebra.firstOperator k * OperatorAlgebra.secondOperator k +
        OperatorAlgebra.monomialOperator k i n := by
      simp only [OperatorAlgebra.monomialOperator, pow_succ, mul_assoc]
      rw [OperatorAlgebra.secondOperator_mul_firstOperator k, mul_add, mul_one, mul_add]
    rw [key]
    exact (monomialSpan k).add_mem (mul_secondOperator_mem_span k ih) (monomialOperator_mem_span k i n)

private lemma mul_firstOperator_mem_span {a : OperatorAlgebra k} (ha : a ∈ monomialSpan k) :
    a * OperatorAlgebra.firstOperator k ∈ monomialSpan k := by
  apply Submodule.span_induction
    (p := fun a (_ : a ∈ monomialSpan k) => a * OperatorAlgebra.firstOperator k ∈ monomialSpan k)
  · intro z hz
    obtain ⟨⟨i, j⟩, rfl⟩ := hz
    exact monomialOperator_mul_firstOperator_mem_span k i j
  · rw [zero_mul]; exact (monomialSpan k).zero_mem
  · intro _ _ _ _ ha hb; rw [add_mul]; exact (monomialSpan k).add_mem ha hb
  · intro c _ _ ha; rw [smul_mul_assoc]; exact (monomialSpan k).smul_mem c ha
  · exact ha

private lemma secondOperator_mul_monomialOperator_mem_span (i j : ℕ) :
    OperatorAlgebra.secondOperator k * OperatorAlgebra.monomialOperator k i j ∈ monomialSpan k := by
  induction i with
  | zero =>
    have : OperatorAlgebra.secondOperator k * OperatorAlgebra.monomialOperator k 0 j = OperatorAlgebra.monomialOperator k 0 (j + 1) := by
      simp only [OperatorAlgebra.monomialOperator, pow_zero, one_mul, pow_succ']
    rw [this]; exact monomialOperator_mem_span k 0 (j + 1)
  | succ n ih =>

    have key : OperatorAlgebra.secondOperator k * OperatorAlgebra.monomialOperator k (n + 1) j =
        OperatorAlgebra.firstOperator k * (OperatorAlgebra.secondOperator k * OperatorAlgebra.monomialOperator k n j) +
        OperatorAlgebra.monomialOperator k n j := by
      simp only [OperatorAlgebra.monomialOperator, pow_succ', mul_assoc]
      rw [← mul_assoc (OperatorAlgebra.secondOperator k) (OperatorAlgebra.firstOperator k),
          OperatorAlgebra.secondOperator_mul_firstOperator k, add_mul, one_mul, mul_assoc]
    rw [key]
    exact (monomialSpan k).add_mem (firstOperator_mul_mem_span k ih) (monomialOperator_mem_span k n j)

private lemma secondOperator_mul_mem_span {a : OperatorAlgebra k} (ha : a ∈ monomialSpan k) :
    OperatorAlgebra.secondOperator k * a ∈ monomialSpan k := by
  apply Submodule.span_induction
    (p := fun a (_ : a ∈ monomialSpan k) => OperatorAlgebra.secondOperator k * a ∈ monomialSpan k)
  · intro z hz
    obtain ⟨⟨i, j⟩, rfl⟩ := hz
    exact secondOperator_mul_monomialOperator_mem_span k i j
  · rw [mul_zero]; exact (monomialSpan k).zero_mem
  · intro _ _ _ _ ha hb; rw [mul_add]; exact (monomialSpan k).add_mem ha hb
  · intro c _ _ ha; rw [mul_smul_comm]; exact (monomialSpan k).smul_mem c ha
  · exact ha

private lemma mul_mem_monomialSpan {a b : OperatorAlgebra k} (ha : a ∈ monomialSpan k) (hb : b ∈ monomialSpan k) :
    a * b ∈ monomialSpan k := by
  apply Submodule.span_induction
    (p := fun b (_ : b ∈ monomialSpan k) => a * b ∈ monomialSpan k)
  · intro z hz
    obtain ⟨⟨p, q⟩, rfl⟩ := hz
    simp only [OperatorAlgebra.monomialOperator, ← mul_assoc]

    have haxp : a * OperatorAlgebra.firstOperator k ^ p ∈ monomialSpan k := by
      induction p with
      | zero => simpa [pow_zero] using ha
      | succ m ih => rw [pow_succ, ← mul_assoc]; exact mul_firstOperator_mem_span k ih

    induction q with
    | zero => simpa [pow_zero] using haxp
    | succ m ih => rw [pow_succ, ← mul_assoc]; exact mul_secondOperator_mem_span k ih
  · rw [mul_zero]; exact (monomialSpan k).zero_mem
  · intro _ _ _ _ hx hy; rw [mul_add]; exact (monomialSpan k).add_mem hx hy
  · intro c _ _ hx; rw [mul_smul_comm]; exact (monomialSpan k).smul_mem c hx
  · exact hb

/-- The indexed operator family spans the whole operator algebra. -/
@[source_ref "Chapter2/Proposition2.7.1" (role := primary)]
theorem OperatorAlgebra.span_monomialOperator :
    ⊤ ≤ Submodule.span k (Set.range (fun p : ℕ × ℕ => OperatorAlgebra.monomialOperator k p.1 p.2)) := by
  intro w _
  obtain ⟨a, rfl⟩ := RingQuot.mkAlgHom_surjective k (freeAlgebraRelation k) w
  have ha : a ∈ Algebra.adjoin k (Set.range (FreeAlgebra.ι k : freeAlgebraGenerator → _)) := by
    rw [FreeAlgebra.adjoin_range_ι]; exact Algebra.mem_top
  induction ha using Algebra.adjoin_induction with
  | mem x hx =>
    obtain ⟨i, rfl⟩ := hx
    fin_cases i
    · convert monomialOperator_mem_span k 1 0 using 1
      simp [OperatorAlgebra.monomialOperator, OperatorAlgebra.firstOperator, OperatorAlgebra.fromFreeAlgebra]
    · convert monomialOperator_mem_span k 0 1 using 1
      simp [OperatorAlgebra.monomialOperator, OperatorAlgebra.secondOperator, OperatorAlgebra.fromFreeAlgebra]
  | algebraMap r =>
    convert (monomialSpan k).smul_mem r (monomialOperator_mem_span k 0 0) using 1
    simp [OperatorAlgebra.monomialOperator, Algebra.algebraMap_eq_smul_one]
  | add x y _ _ ihx ihy => rw [map_add]; exact (monomialSpan k).add_mem (ihx trivial) (ihy trivial)
  | mul x y _ _ ihx ihy => rw [map_mul]; exact mul_mem_monomialSpan k (ihx trivial) (ihy trivial)

/-- The linear endomorphism of polynomials given by multiplication by the polynomial variable. -/
noncomputable def polynomialMulX : Module.End k (Polynomial k) where
  toFun p := Polynomial.X * p
  map_add' := mul_add _
  map_smul' c p := by
    simp only [RingHom.id_apply]
    exact Algebra.mul_smul_comm c Polynomial.X p

/-- The polynomial multiplication endomorphism sends a polynomial to its product with the variable. -/
lemma polynomialMulX_apply (p : Polynomial k) :
    polynomialMulX k p = Polynomial.X * p := rfl

private lemma derivative_mul_polynomialMulX :
    (Polynomial.derivative (R := k)) * polynomialMulX k =
    polynomialMulX k * Polynomial.derivative + 1 := by
  apply LinearMap.ext; intro p
  change Polynomial.derivative (polynomialMulX k p) =
    polynomialMulX k (Polynomial.derivative p) + (1 : Module.End k (Polynomial k)) p
  simp only [polynomialMulX_apply, Module.End.one_apply]
  rw [Polynomial.derivative_mul, Polynomial.derivative_X, one_mul, add_comm]

private noncomputable def polynomialRepresentationGenerator : Fin 2 → Module.End k (Polynomial k) :=
  ![polynomialMulX k, Polynomial.derivative]

private noncomputable def freeAlgebraToPolynomialEnd :
    FreeAlgebra k (Fin 2) →ₐ[k] Module.End k (Polynomial k) :=
  FreeAlgebra.lift k (polynomialRepresentationGenerator k)

private lemma freeAlgebraToPolynomialEnd_rel :
    ∀ ⦃a b⦄, freeAlgebraRelation k a b → freeAlgebraToPolynomialEnd k a = freeAlgebraToPolynomialEnd k b := by
  intro a b ⟨ha, hb⟩
  subst ha; subst hb
  simp only [freeAlgebraToPolynomialEnd, map_mul, map_add, map_one, FreeAlgebra.lift_ι_apply,
    polynomialRepresentationGenerator, Matrix.cons_val_zero, Matrix.cons_val_one]
  exact derivative_mul_polynomialMulX k

/-- The algebra homomorphism from the operator algebra to polynomial endomorphisms. -/
noncomputable def toPolynomialEnd :
    OperatorAlgebra k →ₐ[k] Module.End k (Polynomial k) :=
  RingQuot.liftAlgHom k ⟨freeAlgebraToPolynomialEnd k, freeAlgebraToPolynomialEnd_rel k⟩

/-- The first distinguished operator maps to multiplication by the polynomial variable. -/
lemma toPolynomialEnd_firstOperator :
    toPolynomialEnd k (OperatorAlgebra.firstOperator k) = polynomialMulX k := by
  simp [toPolynomialEnd, OperatorAlgebra.firstOperator, OperatorAlgebra.fromFreeAlgebra, RingQuot.liftAlgHom_mkAlgHom_apply,
    freeAlgebraToPolynomialEnd, FreeAlgebra.lift_ι_apply, polynomialRepresentationGenerator]

/-- The second distinguished operator maps to polynomial differentiation. -/
lemma toPolynomialEnd_secondOperator :
    toPolynomialEnd k (OperatorAlgebra.secondOperator k) =
    (Polynomial.derivative : Module.End k (Polynomial k)) := by
  simp [toPolynomialEnd, OperatorAlgebra.secondOperator, OperatorAlgebra.fromFreeAlgebra, RingQuot.liftAlgHom_mkAlgHom_apply,
    freeAlgebraToPolynomialEnd, FreeAlgebra.lift_ι_apply, polynomialRepresentationGenerator]

private lemma polynomialMulX_pow_apply (i : ℕ) (p : Polynomial k) :
    (polynomialMulX k ^ i) p = Polynomial.X ^ i * p := by
  induction i generalizing p with
  | zero => simp
  | succ n ih =>
    rw [pow_succ, Module.End.mul_apply, ih, polynomialMulX_apply, ← mul_assoc, ← pow_succ]

private lemma toPolynomialEnd_monomialOperator_apply (i j n : ℕ) :
    toPolynomialEnd k (OperatorAlgebra.monomialOperator k i j) (Polynomial.X ^ n) =
    Polynomial.C (↑(n.descFactorial j) : k) * Polynomial.X ^ (i + (n - j)) := by
  simp only [OperatorAlgebra.monomialOperator, map_mul, map_pow, toPolynomialEnd_firstOperator, toPolynomialEnd_secondOperator]
  rw [Module.End.mul_apply, Module.End.pow_apply (Polynomial.derivative (R := k)) j,
    Polynomial.iterate_derivative_X_pow_eq_C_mul, polynomialMulX_pow_apply]
  ring

private lemma toPolynomialEnd_monomialOperator_eq_zero_of_lt (i j n : ℕ) (hjn : n < j) :
    toPolynomialEnd k (OperatorAlgebra.monomialOperator k i j) (Polynomial.X ^ n) = 0 := by
  rw [toPolynomialEnd_monomialOperator_apply]
  simp [Nat.descFactorial_eq_zero_iff_lt.mpr hjn]

private lemma toPolynomialEnd_monomialOperator_diagonal (i j : ℕ) :
    toPolynomialEnd k (OperatorAlgebra.monomialOperator k i j) (Polynomial.X ^ j) =
    Polynomial.C (↑(j.factorial) : k) * Polynomial.X ^ i := by
  rw [toPolynomialEnd_monomialOperator_apply, Nat.descFactorial_self, Nat.sub_self, add_zero]

private lemma polynomialImages_linearIndependent [CharZero k] [NoZeroDivisors k] :
    LinearIndependent k (fun p : ℕ × ℕ => toPolynomialEnd k (OperatorAlgebra.monomialOperator k p.1 p.2)) := by
  rw [linearIndependent_iff']
  intro s g hg

  have hpoly : toPolynomialEnd k (∑ r ∈ s, g r • OperatorAlgebra.monomialOperator k r.1 r.2) = 0 := by
    rw [map_sum]; simp_rw [map_smul]; exact hg

  have hcoeff : ∀ (n m : ℕ),
      ∑ r ∈ s, g r *
        (toPolynomialEnd k (OperatorAlgebra.monomialOperator k r.1 r.2) (Polynomial.X ^ n)).coeff m = 0 := by
    intro n m

    have h1 : (toPolynomialEnd k (∑ r ∈ s, g r • OperatorAlgebra.monomialOperator k r.1 r.2)) (Polynomial.X ^ n)
        = 0 := by rw [hpoly, LinearMap.zero_apply]

    have h2 : ∀ r, toPolynomialEnd k (g r • OperatorAlgebra.monomialOperator k r.1 r.2) (Polynomial.X ^ n) =
        g r • (toPolynomialEnd k (OperatorAlgebra.monomialOperator k r.1 r.2) (Polynomial.X ^ n)) := by
      intro r
      rw [Algebra.smul_def, map_mul, AlgHom.commutes]
      simp [Module.End.mul_apply, Algebra.smul_def]
    rw [map_sum] at h1
    simp only [LinearMap.coe_sum, Finset.sum_apply] at h1
    simp_rw [h2] at h1

    have hc : (∑ r ∈ s, g r •
        (toPolynomialEnd k (OperatorAlgebra.monomialOperator k r.1 r.2) (Polynomial.X ^ n))).coeff m = 0 :=
      congr_arg (Polynomial.coeff · m) h1
    rw [Polynomial.finsetSum_coeff] at hc
    simp only [Polynomial.coeff_smul, smul_eq_mul] at hc
    exact hc

  suffices key : ∀ j i, (i, j) ∈ s → g (i, j) = 0 by
    intro ⟨i, j⟩ hp; exact key j i hp
  intro j
  induction j using Nat.strongRecOn with
  | ind j ih =>
    intro i hij

    have hXj := hcoeff j i

    have hterm : ∀ r ∈ s, r ≠ (i, j) →
        g r * (toPolynomialEnd k (OperatorAlgebra.monomialOperator k r.1 r.2)
          (Polynomial.X ^ j)).coeff i = 0 := by
      intro ⟨ri, rj⟩ hr hne
      by_cases hjrj : j < rj
      · rw [toPolynomialEnd_monomialOperator_eq_zero_of_lt k ri rj j hjrj, Polynomial.coeff_zero, mul_zero]
      · push Not at hjrj
        by_cases heq : rj = j
        · subst heq
          have hri : ri ≠ i := fun h => hne (Prod.ext h rfl)
          rw [toPolynomialEnd_monomialOperator_diagonal, Polynomial.coeff_C_mul_X_pow,
            if_neg (Ne.symm hri), mul_zero]
        · rw [ih rj (lt_of_le_of_ne hjrj heq) ri hr, zero_mul]

    have honly : g (i, j) * (toPolynomialEnd k (OperatorAlgebra.monomialOperator k i j)
        (Polynomial.X ^ j)).coeff i = 0 := by
      have := Finset.sum_eq_single (i, j) (fun r hr hne => hterm r hr hne)
        (fun h => absurd hij h) |>.symm.trans hXj
      exact this
    rw [toPolynomialEnd_monomialOperator_diagonal, Polynomial.coeff_C_mul_X_pow, if_pos rfl] at honly
    exact (mul_eq_zero.mp honly).resolve_right
      (Nat.cast_ne_zero.mpr (Nat.factorial_ne_zero j))

private lemma monomialOperator_linearIndependent [CharZero k] [NoZeroDivisors k] :
    LinearIndependent k (fun p : ℕ × ℕ => OperatorAlgebra.monomialOperator k p.1 p.2) :=
  (polynomialImages_linearIndependent k).of_comp (toPolynomialEnd k).toLinearMap

/-- The displayed homomorphism from the operator algebra to polynomial endomorphisms is injective. -/
@[source_ref "Chapter2/Discussion_faithful_example" (role := primary)]
theorem OperatorAlgebra.toPolynomialEnd_injective [CharZero k] [NoZeroDivisors k] :
    Function.Injective (toPolynomialEnd k) := by
  classical
  set mono : ℕ × ℕ → OperatorAlgebra k := fun p => OperatorAlgebra.monomialOperator k p.1 p.2 with hmono

  have hsurj : Function.Surjective (Finsupp.linearCombination k mono) := by
    rw [← LinearMap.range_eq_top, Finsupp.range_linearCombination]
    exact top_le_iff.mp (OperatorAlgebra.span_monomialOperator k)

  have hli : LinearIndependent k (fun p : ℕ × ℕ => toPolynomialEnd k (mono p)) :=
    polynomialImages_linearIndependent k
  rw [injective_iff_map_eq_zero (toPolynomialEnd k)]
  intro w hw
  obtain ⟨f, rfl⟩ := hsurj w
  have h0 : Finsupp.linearCombination k (fun p => toPolynomialEnd k (mono p)) f = 0 := by
    have hap : toPolynomialEnd k (Finsupp.linearCombination k mono f)
        = Finsupp.linearCombination k (fun p => toPolynomialEnd k (mono p)) f := by
      rw [Finsupp.linearCombination_apply, Finsupp.linearCombination_apply, map_finsuppSum]
      simp only [map_smul]
    rw [← hap]; exact hw
  have hf : f = 0 :=
    hli.finsuppLinearCombination_injective (h0.trans (map_zero _).symm)
  rw [hf, map_zero]

/-- In prime characteristic, the indicated number of iterated polynomial derivatives is zero. -/
@[source_ref "Chapter2/Discussion_faithful_example" (role := primary)]
theorem derivative_iterate_prime_eq_zero (p : ℕ) [Fact p.Prime] [CharP k p]
    (Q : Polynomial k) : (Polynomial.derivative (R := k))^[p] Q = 0 := by
  ext m
  rw [Polynomial.coeff_iterate_derivative, Polynomial.coeff_zero]
  have hdvd : p ∣ (m + p).descFactorial p :=
    (Nat.dvd_factorial (Fact.out : p.Prime).pos le_rfl).trans
      (Nat.factorial_dvd_descFactorial (m + p) p)
  rw [nsmul_eq_mul, (CharP.cast_eq_zero_iff k p _).mpr hdvd, zero_mul]

/-- In prime characteristic, the image of the stated power of the second operator is zero. -/
@[source_ref "Chapter2/Discussion_faithful_example" (role := supporting)]
theorem OperatorAlgebra.toPolynomialEnd_power_second_eq_zero (p : ℕ) [Fact p.Prime] [CharP k p] :
    toPolynomialEnd k (OperatorAlgebra.secondOperator k ^ p) = 0 := by
  rw [map_pow, toPolynomialEnd_secondOperator]
  apply LinearMap.ext
  intro Q
  rw [Module.End.pow_apply, LinearMap.zero_apply]
  exact derivative_iterate_prime_eq_zero k p Q

/-- The displayed family of elements is linearly independent and spans the operator algebra. -/
theorem polynomialOperators_basis [CharZero k] [NoZeroDivisors k] :
    LinearIndependent k (fun p : ℕ × ℕ => OperatorAlgebra.monomialOperator k p.1 p.2) ∧
    ⊤ ≤ Submodule.span k (Set.range (fun p : ℕ × ℕ => OperatorAlgebra.monomialOperator k p.1 p.2)) := by
  exact ⟨monomialOperator_linearIndependent k, OperatorAlgebra.span_monomialOperator k⟩

end RepresentationTheory.FreeAlgebra.PolynomialOperators
