import EtingofRepresentationTheory.Chapter4.Example4_8_1.A5Classes

/-!
# Example 4.8.1 — `A₅`: the representations `ℂ`, `ℂ⁴`, `ℂ⁵` and their simplicity

Split out of `Example4_8_1.lean` for CI memory (issue #5852); see there for the umbrella.
The norm-one character sums proving simplicity are evaluated by class decomposition
(`sum_fixCard_classfn`): the 60-term group sums collapse to the five class representatives
weighted by the class sizes `(1, 20, 15, 12, 12)`, so the kernel only ever evaluates the
fixed-point counts at five elements.
-/

namespace Etingof.Example4_8_1

open Q5

namespace A5

open Equiv CategoryTheory

noncomputable section

set_option linter.unusedSectionVars false
set_option linter.unusedFintypeInType false
set_option linter.unusedDecidableInType false

/-- Class decomposition of a fixed-point-count sum over `A₅`: since `fixCardM` is a class
function (`S4.fixCardM_conj`) and every element is conjugate to its `classIdxA5`
representative (`classIdxA5_spec`), the 60-term group sum collapses to the five class
representatives weighted by the class sizes `(1, 20, 15, 12, 12)` (`classIdxA5_card`). -/
lemma sum_fixCard_classfn {α : Type} [Fintype α] [DecidableEq α] [Nonempty α] [MulAction G α]
    (f : ℕ → ℤ) :
    ∑ g : G, f (S4.fixCardM (G := G) (α := α) g)
      = ∑ j : Fin 5, ((![1, 20, 15, 12, 12] j : ℕ) : ℤ)
          * f (S4.fixCardM (G := G) (α := α) (classRepA5 j)) := by
  rw [← Finset.sum_fiberwise Finset.univ (fun g => classIdxA5 g)
    (fun g => f (S4.fixCardM (G := G) (α := α) g))]
  refine Finset.sum_congr rfl fun j _ => ?_
  have hconst : ∀ g ∈ Finset.univ.filter (fun g => classIdxA5 g = j),
      f (S4.fixCardM (G := G) (α := α) g)
        = f (S4.fixCardM (G := G) (α := α) (classRepA5 j)) := by
    intro g hg
    have hj : classIdxA5 g = j := (Finset.mem_filter.mp hg).2
    obtain ⟨c, hc⟩ := classIdxA5_spec g
    conv_lhs => rw [← hc]
    rw [S4.fixCardM_conj, hj]
  rw [Finset.sum_congr rfl hconst, Finset.sum_const, classIdxA5_card j, nsmul_eq_mul]
/-! #### The trivial representation `ℂ` -/

/-- The trivial representation `ℂ` of `A₅`. -/
def repTriv : FDRep ℂ G := FDRep.of (S4.charRep (1 : G →* ℂˣ))

lemma repTriv_char (g : G) : repTriv.character g = 1 := by
  rw [repTriv, S4.charRep_character]; simp

lemma repTriv_simple : Simple repTriv := S4.charRep_simple _

/-! #### The 4-dimensional representation `ℂ⁴` (deleted natural permutation rep on `Fin 5`) -/

/-- `ℂ⁴`, the deleted natural permutation representation of `A₅` on `Fin 5`. -/
def repC4 : FDRep ℂ G := S4.stdRepM (G := G) (α := Fin 5)

lemma repC4_char (g : G) :
    repC4.character g = (S4.fixCardM (G := G) (α := Fin 5) g : ℂ) - 1 := by
  rw [repC4, S4.stdRepM_character]

set_option maxRecDepth 8000 in
set_option maxHeartbeats 4000000 in
-- class-decomposed norm sum: kernel `decide` only at the five class representatives; no `native_decide`
lemma repC4_simple : Simple repC4 := by
  rw [repC4, FDRep.simple_iff_char_is_norm_one]
  have hterm : ∀ g : G,
      (S4.stdRepM (G := G) (α := Fin 5)).character g
        * (S4.stdRepM (G := G) (α := Fin 5)).character g⁻¹
      = ((((S4.fixCardM (G := G) (α := Fin 5) g : ℤ) - 1) ^ 2 : ℤ) : ℂ) := by
    intro g
    rw [S4.stdRepM_character, S4.stdRepM_character, S4.fixCardM_inv]; push_cast; ring
  rw [Finset.sum_congr rfl (fun g _ => hterm g), ← Int.cast_sum]
  have hsum : ∑ g : G, (((S4.fixCardM (G := G) (α := Fin 5) g : ℤ) - 1) ^ 2) = 60 :=
    calc ∑ g : G, (((S4.fixCardM (G := G) (α := Fin 5) g : ℤ) - 1) ^ 2)
        = ∑ j : Fin 5, ((![1, 20, 15, 12, 12] j : ℕ) : ℤ)
            * (((S4.fixCardM (G := G) (α := Fin 5) (classRepA5 j) : ℤ) - 1) ^ 2) :=
          sum_fixCard_classfn (α := Fin 5) (fun n => ((n : ℤ) - 1) ^ 2)
      _ = 60 := by decide
  rw [hsum, card_G]; norm_num

/-! #### The 5-dimensional representation `ℂ⁵`

`A₅` has six Sylow-5 subgroups; each is generated by a 5-cycle, and the six 5-cycles sending
`0 ↦ 1` are exactly one generator per subgroup.  `A₅` permutes the six subgroups by
conjugation, a 2-transitive action on a 6-element set; the deleted permutation representation
of this action is `ℂ⁵`.  We model the six subgroups by the `Finset`s of their four non-identity
elements; conjugation maps such a `Finset` to another of the six exactly, so the conjugation
permutation index `conjIdx5` defines a genuine `MulAction G (Fin 6)`. -/

/-- The 5-cycle `(0 1 a b c)` of `Fin 5`. -/
def cyc (a b c : Fin 5) : Equiv.Perm (Fin 5) :=
  Equiv.swap 0 c * Equiv.swap 0 b * Equiv.swap 0 a * Equiv.swap 0 1

/-- Representative 5-cycles, one per Sylow-5 subgroup of `A₅` (each sends `0 ↦ 1`). -/
def c5rep : Fin 6 → Equiv.Perm (Fin 5) :=
  ![cyc 2 3 4, cyc 2 4 3, cyc 3 2 4, cyc 3 4 2, cyc 4 2 3, cyc 4 3 2]

/-- The carrier of the `i`-th Sylow-5 subgroup: its four non-identity elements. -/
def carrier (i : Fin 6) : Finset (Equiv.Perm (Fin 5)) :=
  {c5rep i, (c5rep i) ^ 2, (c5rep i) ^ 3, (c5rep i) ^ 4}

/-- Conjugation of a permutation by an element of `A₅`. -/
def conjPerm (g : G) (x : Equiv.Perm (Fin 5)) : Equiv.Perm (Fin 5) :=
  (g : Equiv.Perm (Fin 5)) * x * (g : Equiv.Perm (Fin 5))⁻¹

lemma conjPerm_one : conjPerm 1 = id := by
  funext x; simp [conjPerm]

lemma conjPerm_mul (g h : G) (x : Equiv.Perm (Fin 5)) :
    conjPerm g (conjPerm h x) = conjPerm (g * h) x := by
  simp only [conjPerm, Subgroup.coe_mul]; group

/-- The index of the subgroup `g · (subgroup i) · g⁻¹` among the six subgroups. -/
def conjIdx5 (g : G) (i : Fin 6) : Fin 6 :=
  if carrier 0 = (carrier i).image (conjPerm g) then 0
  else if carrier 1 = (carrier i).image (conjPerm g) then 1
  else if carrier 2 = (carrier i).image (conjPerm g) then 2
  else if carrier 3 = (carrier i).image (conjPerm g) then 3
  else if carrier 4 = (carrier i).image (conjPerm g) then 4 else 5

lemma carrier_injective : Function.Injective carrier := by decide

set_option maxRecDepth 8000 in
set_option maxHeartbeats 4000000 in
-- honest `decide` over the 60×6 conjugation table of A₅ on its Sylow-5 subgroups
/-- Conjugation by any `g ∈ A₅` permutes the six Sylow-5 subgroups: the conjugate of the
`i`-th carrier is exactly the `conjIdx5 g i`-th carrier (honest `decide` over the `60 × 6`
conjugation table, no `native_decide`). -/
lemma conjIdx5_spec (g : G) (i : Fin 6) :
    carrier (conjIdx5 g i) = (carrier i).image (conjPerm g) := by
  revert g i; decide

/-- `A₅` acts on the six Sylow-5 subgroups (`Fin 6`) by conjugation. -/
instance instMulActionFin6 : MulAction G (Fin 6) where
  smul := conjIdx5
  one_smul i := carrier_injective (by
    change carrier (conjIdx5 1 i) = carrier i
    rw [conjIdx5_spec, conjPerm_one, Finset.image_id])
  mul_smul g h i := carrier_injective (by
    have hcomp : conjPerm g ∘ conjPerm h = conjPerm (g * h) := by
      funext x; exact conjPerm_mul g h x
    change carrier (conjIdx5 (g * h) i) = carrier (conjIdx5 g (conjIdx5 h i))
    rw [conjIdx5_spec, conjIdx5_spec, conjIdx5_spec, Finset.image_image, hcomp])

/-- `ℂ⁵`, the deleted permutation representation on the six Sylow-5 subgroups. -/
def repC5 : FDRep ℂ G := S4.stdRepM (G := G) (α := Fin 6)

lemma repC5_char (g : G) :
    repC5.character g = (S4.fixCardM (G := G) (α := Fin 6) g : ℂ) - 1 := by
  rw [repC5, S4.stdRepM_character]

set_option maxRecDepth 8000 in
set_option maxHeartbeats 4000000 in
-- class-decomposed norm sum: kernel `decide` only at the five class representatives; no `native_decide`
lemma repC5_simple : Simple repC5 := by
  rw [repC5, FDRep.simple_iff_char_is_norm_one]
  have hterm : ∀ g : G,
      (S4.stdRepM (G := G) (α := Fin 6)).character g
        * (S4.stdRepM (G := G) (α := Fin 6)).character g⁻¹
      = ((((S4.fixCardM (G := G) (α := Fin 6) g : ℤ) - 1) ^ 2 : ℤ) : ℂ) := by
    intro g
    rw [S4.stdRepM_character, S4.stdRepM_character, S4.fixCardM_inv]; push_cast; ring
  rw [Finset.sum_congr rfl (fun g _ => hterm g), ← Int.cast_sum]
  have hsum : ∑ g : G, (((S4.fixCardM (G := G) (α := Fin 6) g : ℤ) - 1) ^ 2) = 60 :=
    calc ∑ g : G, (((S4.fixCardM (G := G) (α := Fin 6) g : ℤ) - 1) ^ 2)
        = ∑ j : Fin 5, ((![1, 20, 15, 12, 12] j : ℕ) : ℤ)
            * (((S4.fixCardM (G := G) (α := Fin 6) (classRepA5 j) : ℤ) - 1) ^ 2) :=
          sum_fixCard_classfn (α := Fin 6) (fun n => ((n : ℤ) - 1) ^ 2)
      _ = 60 := by decide
  rw [hsum, card_G]; norm_num

end

end A5

end Etingof.Example4_8_1
