import Mathlib.CategoryTheory.Abelian.LeftDerived
import Mathlib.Algebra.Category.ModuleCat.Abelian
import Mathlib.Algebra.Category.ModuleCat.Projective
import Mathlib.Algebra.Category.Grp.Abelian
import Mathlib.LinearAlgebra.TensorProduct.Basic
import Mathlib.GroupTheory.QuotientGroup.Defs
import Mathlib.Algebra.Module.Opposite

/-!
# Definition 8.2.3: Tor functors

Let `A` be a unital ring, `M` a right `A`-module, `P•` a projective resolution of `M`, and
`N` a left `A`-module. For `i ≥ 0` we define `Torᵢᴬ(M, N)` to be the `i`-th homology of the
complex
  ⋯ → P₂ ⊗_A N → P₁ ⊗_A N → P₀ ⊗_A N → 0
induced by the resolution `P•`.

## Faithfulness note

This definition is genuinely asymmetric: `M` is a **right** `A`-module and `N` is a **left**
`A`-module, and `⊗_A` is the tensor product over the (possibly non-commutative) ring `A`.
Mathlib's `CategoryTheory.Tor C n : C ⥤ C ⥤ C` left-derives the tensor product of a *single*
monoidal abelian category, where both factors live in the same category `C`; it can model the
book's `Tor` only in the commutative/bimodule case. It cannot express the general-ring setting
of the book, where the two arguments live in different module categories. See issue #5628.

We therefore build the construction directly:

* Right `A`-modules are `ModuleCat Aᵐᵒᵖ` (a right `A`-action on `M` is a left `Aᵐᵒᵖ`-action,
  with `m * a = MulOpposite.op a • m`).
* The tensor product `M ⊗_A N` over the non-commutative ring `A` is **not** available in
  Mathlib (its `TensorProduct R` requires `R` commutative). We construct it here as the
  quotient of the underlying additive tensor product `M ⊗_ℤ N` by the balancing relation
  `(m * a) ⊗ n = m ⊗ (a • n)`.
* `tensorRightFunctor A N : ModuleCat Aᵐᵒᵖ ⥤ AddCommGrpCat` sends `M ↦ M ⊗_A N`.
* `Etingof.TorFunctor A N n` is its `n`-th left derived functor, and `Etingof.Tor A M N n` is
  the value at `M`. By the standard balancing theorem this agrees with the book's homology of
  `P• ⊗_A N`; here we take the (equivalent) derived-functor definition, which makes the
  independence of the projective resolution (Problem 8.2.5) automatic.
-/

open CategoryTheory TensorProduct

namespace Etingof

universe u

variable (A : Type u) [Ring A]
variable (N : Type u) [AddCommGroup N] [Module A N]

/-- The balancing subgroup of `M ⊗_ℤ N` whose quotient is the tensor product `M ⊗_A N` over the
ring `A`. It is generated by `(m * a) ⊗ n - m ⊗ (a • n)`, where `m * a = MulOpposite.op a • m`
is the right `A`-action on `M`. -/
def balancedSubgroup (M : Type u) [AddCommGroup M] [Module Aᵐᵒᵖ M] :
    AddSubgroup (TensorProduct ℤ M N) :=
  AddSubgroup.closure
    {x | ∃ (a : A) (m : M) (n : N),
      x = (MulOpposite.op a • m) ⊗ₜ[ℤ] n - m ⊗ₜ[ℤ] (a • n)}

/-- The tensor product `M ⊗_A N` of a right `A`-module `M` with the fixed left `A`-module `N`,
over the (possibly non-commutative) ring `A`, realised as a quotient of the additive tensor
product. -/
abbrev tensorOver (M : Type u) [AddCommGroup M] [Module Aᵐᵒᵖ M] : Type u :=
  TensorProduct ℤ M N ⧸ balancedSubgroup A N M

/-- The canonical map `M ⊗_ℤ N → M ⊗_A N` is additive. -/
private lemma tensorOver_mk_add {M : Type u} [AddCommGroup M] [Module Aᵐᵒᵖ M]
    (p q : TensorProduct ℤ M N) :
    ((p + q : TensorProduct ℤ M N) : tensorOver A N M)
      = (p : tensorOver A N M) + (q : tensorOver A N M) :=
  map_add (QuotientAddGroup.mk' _) p q

/-- The additive map `M ⊗_A N → M' ⊗_A N` induced by a right `A`-module map `f : M → M'`. -/
noncomputable def tensorRightMap {M M' : ModuleCat.{u} Aᵐᵒᵖ} (f : M ⟶ M') :
    tensorOver A N M →+ tensorOver A N M' :=
  QuotientAddGroup.map (balancedSubgroup A N M) (balancedSubgroup A N M')
    (TensorProduct.map f.hom.toAddMonoidHom.toIntLinearMap (LinearMap.id)).toAddMonoidHom
    (by
      -- the induced additive map sends the balancing relation of `M` into that of `M'`
      refine AddSubgroup.closure_le _ |>.mpr ?_
      rintro x ⟨a, m, n, rfl⟩
      apply AddSubgroup.subset_closure
      refine ⟨a, f.hom m, n, ?_⟩
      simp only [map_sub, TensorProduct.map_tmul,
        LinearMap.toAddMonoidHom_coe, AddMonoidHom.coe_toIntLinearMap, LinearMap.id_coe, id_eq,
        map_smul])

@[simp]
private lemma tensorRightMap_mk {M M' : ModuleCat.{u} Aᵐᵒᵖ} (f : M ⟶ M')
    (m : M) (n : N) :
    tensorRightMap A N f (TensorProduct.tmul ℤ m n : tensorOver A N M)
      = (TensorProduct.tmul ℤ (f.hom m) n : tensorOver A N M') :=
  rfl

/-- The functor `M ↦ M ⊗_A N` from right `A`-modules to abelian groups. This is the functor that
the book tensors a projective resolution of `M` with. -/
noncomputable def tensorRightFunctor : ModuleCat.{u} Aᵐᵒᵖ ⥤ AddCommGrpCat.{u} where
  obj M := AddCommGrpCat.of (tensorOver A N M)
  map {M M'} f := AddCommGrpCat.ofHom (tensorRightMap A N f)
  map_id M := by
    ext x
    induction x with
    | zero => simp
    | tmul m n => simp
    | add a b ha hb => simp only [map_add, ha, hb]
  map_comp {M M' M''} f g := by
    ext x
    induction x with
    | zero => simp
    | tmul m n => simp
    | add a b ha hb => simp only [map_add, ha, hb]

/-- The functor `M ↦ M ⊗_A N` is additive in `M`, so it can be left-derived. -/
instance : (tensorRightFunctor A N).Additive where
  map_add {M M' f g} := by
    ext x
    obtain ⟨y, rfl⟩ := QuotientAddGroup.mk_surjective x
    induction y with
    | zero => simp
    | tmul m n =>
      simp only [tensorRightFunctor, AddCommGrpCat.hom_ofHom, AddCommGrpCat.hom_add,
        AddMonoidHom.add_apply, tensorRightMap_mk, ModuleCat.hom_add, LinearMap.add_apply,
        add_tmul]
      exact tensorOver_mk_add A N _ _
    | add a b ha hb =>
      rw [tensorOver_mk_add, map_add, map_add, ha, hb]

/-- The `n`-th Tor functor `Torₙᴬ(-, N) : (right A-modules) ⥤ Ab`, defined as the `n`-th left
derived functor of `- ⊗_A N`, in the sense of Etingof Definition 8.2.3. -/
noncomputable def TorFunctor (n : ℕ) : ModuleCat.{u} Aᵐᵒᵖ ⥤ AddCommGrpCat.{u} :=
  Functor.leftDerived (tensorRightFunctor A N) n

/-- `Torₙᴬ(M, N)`, the `n`-th Tor group of a right `A`-module `M` and a left `A`-module `N`, in
the sense of Etingof Definition 8.2.3. It is the `n`-th homology of `P• ⊗_A N` for any
projective resolution `P•` of `M`; we define it as the `n`-th left derived functor of `- ⊗_A N`
evaluated at `M`, which is canonically independent of the resolution (Problem 8.2.5). -/
noncomputable def Tor (M : ModuleCat.{u} Aᵐᵒᵖ) (n : ℕ) : AddCommGrpCat.{u} :=
  (TorFunctor A N n).obj M

end Etingof
