import Mathlib.RingTheory.Flat.Basic
import Mathlib.RingTheory.Flat.Localization
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.Algebra.Module.Projective
import Mathlib.Data.Complex.Basic

/-!
# Problem 8.1.3: Flat modules

A right `A`-module `M` is **flat** if the functor `M ⊗_A -` on the category of left `A`-modules
is exact. This problem asks to show:

* (i) any projective module is flat;
* (ii) for a commutative ring `A` and a multiplicatively closed subset `S`, the localization
  `S⁻¹A` is a flat `A`-module;
* (iii) for `A = ℂ[x]` and `M = ℂ[x, x⁻¹]`, `M` is flat but not projective.

## Formalization notes

We use Mathlib's `Module.Flat R M`, which is the exactness of `- ⊗_R M`. Mathlib develops
flatness over a commutative (semi)ring, so parts (ii) and (iii), which are stated for
commutative `A` in the book, are formalized verbatim, and part (i) is formalized over a
commutative ring (the book states it for a general ring; over a commutative ring
`Module.Flat` is the tensor-exactness condition of the book).

For (iii), `ℂ[x, x⁻¹]` is the ring of Laurent polynomials, i.e. the localization of `ℂ[x]`
at the powers of `x`; we model it as `Localization.Away (Polynomial.X : Polynomial ℂ)`.

The mathematical content of (iii) is that flat does not imply projective. Flatness follows
from (ii). Non-projectivity uses the dual-basis characterization of projective modules: a
projective module `P` is generated by its "coordinate functionals" `P → A`, so if
`Hom_A(P, A) = 0` and `P ≠ 0` then `P` is not projective. Here every `ℂ[x]`-linear map
`ℂ[x, x⁻¹] → ℂ[x]` vanishes, because the image of `1` would be divisible by `xⁿ` for all `n`
(as `1 = xⁿ · x⁻ⁿ`), forcing it to be `0`.
-/

namespace Etingof

open scoped Polynomial

/-- **Problem 8.1.3(i).** Any projective module is flat. -/
theorem Problem_8_1_3_i (A : Type*) [CommRing A] (M : Type*) [AddCommGroup M] [Module A M]
    [Module.Projective A M] : Module.Flat A M :=
  Module.Flat.of_projective

/-- **Problem 8.1.3(ii).** For a commutative ring `A` and a multiplicatively closed subset `S`,
the localization `S⁻¹A` is a flat `A`-module. -/
theorem Problem_8_1_3_ii (A : Type*) [CommRing A] (S : Submonoid A) :
    Module.Flat A (Localization S) :=
  IsLocalization.flat (Localization S) S

/-- Every `ℂ[x]`-linear map from the Laurent polynomials `ℂ[x, x⁻¹]` to `ℂ[x]` is zero:
`Hom_{ℂ[x]}(ℂ[x, x⁻¹], ℂ[x]) = 0`.

The key point is that `f 1` is divisible by `xⁿ` for every `n` (because `1 = xⁿ · x⁻ⁿ`),
and a nonzero polynomial cannot be divisible by arbitrarily high powers of `x`. -/
theorem homToBase_eq_zero
    (f : Localization.Away (Polynomial.X : ℂ[X]) →ₗ[ℂ[X]] ℂ[X]) : f = 0 := by
  set L := Localization.Away (Polynomial.X : ℂ[X]) with hL
  -- Step 1: `f 1 = 0`, because `xⁿ ∣ f 1` for every `n`.
  have hf1 : f 1 = 0 := by
    have hdvd : ∀ n : ℕ, (Polynomial.X : ℂ[X]) ^ n ∣ f 1 := by
      intro n
      -- `xⁿ` maps to a unit in the localization, so it has a right inverse `y`.
      have hu : IsUnit (algebraMap ℂ[X] L ((Polynomial.X : ℂ[X]) ^ n)) :=
        IsLocalization.map_units L
          (⟨(Polynomial.X : ℂ[X]) ^ n, n, rfl⟩ : Submonoid.powers (Polynomial.X : ℂ[X]))
      obtain ⟨y, hy⟩ := isUnit_iff_exists_inv.mp hu
      -- Then `1 = xⁿ • y` in `L`, so `f 1 = xⁿ • f y = xⁿ * f y`.
      refine ⟨f y, ?_⟩
      have h1 : (1 : L) = (Polynomial.X : ℂ[X]) ^ n • y := by
        rw [Algebra.smul_def, hy]
      calc f 1 = f ((Polynomial.X : ℂ[X]) ^ n • y) := by rw [← h1]
        _ = (Polynomial.X : ℂ[X]) ^ n • f y := by rw [map_smul]
        _ = (Polynomial.X : ℂ[X]) ^ n * f y := by rw [smul_eq_mul]
    by_contra h
    have hle := Polynomial.natDegree_le_of_dvd (hdvd ((f 1).natDegree + 1)) h
    rw [Polynomial.natDegree_X_pow] at hle
    omega
  -- Step 2: for a general `m`, `s • f m = a • f 1 = 0` with `s` a nonzero power of `x`.
  refine LinearMap.ext fun m => ?_
  obtain ⟨⟨a, s⟩, hms⟩ := IsLocalization.surj (Submonoid.powers (Polynomial.X : ℂ[X])) m
  obtain ⟨k, hk⟩ := s.2
  have hs0 : (s : ℂ[X]) ≠ 0 := by
    rw [← hk]; exact pow_ne_zero k Polynomial.X_ne_zero
  have key : (s : ℂ[X]) * f m = 0 := by
    have : (s : ℂ[X]) • f m = a • f 1 := by
      rw [← map_smul, ← map_smul, Algebra.smul_def, Algebra.smul_def, mul_one,
        mul_comm (algebraMap ℂ[X] L s) m, hms]
    rw [smul_eq_mul, smul_eq_mul] at this
    rw [this, hf1, mul_zero]
  simpa [hs0] using mul_eq_zero.mp key

/-- **Problem 8.1.3(iii).** For `A = ℂ[x]` and `M = ℂ[x, x⁻¹]` (Laurent polynomials, realised as
the localization of `ℂ[x]` at the powers of `x`), `M` is flat but not projective. -/
theorem Problem_8_1_3_iii :
    Module.Flat ℂ[X] (Localization.Away (Polynomial.X : ℂ[X])) ∧
      ¬ Module.Projective ℂ[X] (Localization.Away (Polynomial.X : ℂ[X])) := by
  refine ⟨Problem_8_1_3_ii ℂ[X] (Submonoid.powers (Polynomial.X : ℂ[X])), ?_⟩
  set L := Localization.Away (Polynomial.X : ℂ[X]) with hL
  intro hproj
  rw [Module.projective_def] at hproj
  obtain ⟨s, hs⟩ := hproj
  -- Each coordinate functional `L → ℂ[x]` is zero, so `s 1 = 0`, hence `1 = 0` in `L`.
  have hs1 : s (1 : L) = 0 := by
    refine Finsupp.ext fun q => ?_
    have hzero : (Finsupp.lapply q ∘ₗ s : L →ₗ[ℂ[X]] ℂ[X]) = 0 :=
      homToBase_eq_zero (Finsupp.lapply q ∘ₗ s)
    have := LinearMap.congr_fun hzero (1 : L)
    simpa [Finsupp.lapply_apply] using this
  have h1 : (1 : L) = 0 := by
    have := hs (1 : L)
    rw [hs1, map_zero] at this
    exact this.symm
  -- `algebraMap ℂ[x] → L` is injective (localization at powers of `x ≠ 0` in a domain),
  -- so `1 = 0` in `L` would force `1 = 0` in `ℂ[x]`, contradiction.
  have hle : Submonoid.powers (Polynomial.X : ℂ[X]) ≤ nonZeroDivisors ℂ[X] :=
    Submonoid.powers_le.mpr (mem_nonZeroDivisors_of_ne_zero Polynomial.X_ne_zero)
  have hinj := IsLocalization.injective L hle
  exact one_ne_zero (hinj (by rw [map_one, map_zero]; exact h1))

end Etingof
