import Mathlib.RingTheory.Jacobson.Radical
import Mathlib.RingTheory.AdjoinRoot
import Mathlib.RingTheory.KrullDimension.Basic
import Mathlib.RingTheory.LocalRing.MaximalIdeal.Basic
import Mathlib.LinearAlgebra.Matrix.Block
import Mathlib.RingTheory.Nilpotent.Lemmas
import Mathlib.RingTheory.Ideal.Quotient.Nilpotent

/-!
# Example 3.5.6: Radicals of k[x]/(x^n) and Upper Triangular Matrices

1. Let A = k[x]/(xⁿ). This algebra has a unique irreducible representation, which is a
   1-dimensional space k, in which x acts by zero. So Rad(A) is the ideal (x).

2. Let A be the algebra of upper triangular n × n matrices. The irreducible representations
   are Vᵢ, i = 1, …, n, which are 1-dimensional, and any matrix x acts by xᵢᵢ. So Rad(A)
   is the ideal of strictly upper triangular matrices.
-/

open Polynomial in
/-- The evaluation homomorphism AdjoinRoot (X^n) → k sending root to 0.
This is the quotient by the maximal ideal. -/
noncomputable def Etingof.truncPolyEval₀ (k : Type*) [Field k] (n : ℕ) (hn : 0 < n) :
    AdjoinRoot (X ^ n : k[X]) →+* k :=
  AdjoinRoot.lift (RingHom.id k) 0 (by simp [Polynomial.eval₂_pow]; omega)

open Polynomial in
/-- The radical of k[x]/(xⁿ) is the ideal generated by x.
Etingof Example 3.5.6(1). -/
theorem Etingof.radical_truncated_polynomial (k : Type*) [Field k] (n : ℕ) (hn : 0 < n) :
    Ring.jacobson (AdjoinRoot (X ^ n : k[X])) =
      Ideal.span {AdjoinRoot.root (X ^ n : k[X])} := by
  sorry

/-- The subalgebra of upper triangular matrices in Mₙ(k). -/
def Etingof.upperTriangularSubalgebra (k : Type*) [Field k] (n : ℕ) :
    Subalgebra k (Matrix (Fin n) (Fin n) k) where
  carrier := {M | ∀ i j, j < i → M i j = 0}
  mul_mem' {a b} ha hb i j hij := by
    simp only [Matrix.mul_apply]
    apply Finset.sum_eq_zero
    intro l _
    by_cases hlj : l < i
    · simp [ha i l hlj]
    · push_neg at hlj
      simp [hb l j (lt_of_lt_of_le hij hlj)]
  one_mem' i j hij := by
    simp [Matrix.one_apply]
    intro h
    exact absurd (h ▸ hij) (lt_irrefl _)
  add_mem' {a b} ha hb i j hij := by simp [ha i j hij, hb i j hij]
  zero_mem' _ _ _ := by simp
  algebraMap_mem' r i j hij := by
    simp [Algebra.algebraMap_eq_smul_one, Matrix.one_apply]
    intro h
    exact absurd (h ▸ hij) (lt_irrefl _)

/-- The radical of the algebra of upper triangular n × n matrices is the ideal of strictly
upper triangular matrices. Etingof Example 3.5.6(2). -/
theorem Etingof.radical_upper_triangular (k : Type*) [Field k] (n : ℕ) :
    Ring.jacobson (Etingof.upperTriangularSubalgebra k n) =
      Ideal.comap (Etingof.upperTriangularSubalgebra k n).val
        (Ideal.span {M : Matrix (Fin n) (Fin n) k | ∀ i j, j ≤ i → M i j = 0}) := by
  sorry
