import Mathlib
import EtingofRepresentationTheory.Chapter3.Problem3_8_4_Functoriality

/-!
# Problem 3.8.4: descent of a base-change isomorphism to a finitely generated subalgebra

The general-`L` half of Problem 3.8.4(i) starts from an `L ⊗[K] A`-linear isomorphism
`L ⊗[K] V ≃ L ⊗[K] W` over an **arbitrary** field extension `L / K` and must reduce it to a
*finitely generated* subextension before Zariski's lemma and the finite-degree Krull–Schmidt
argument (`Problem3_8_4_Finite.lean`) can be applied.

This file supplies the **descent** step: such an isomorphism already lives over a finitely
generated `K`-subalgebra `R ⊆ L`.

## The argument

`V` and `W` are finite dimensional over `K`, so after choosing `K`-bases the isomorphism `e`
and its inverse `e.symm` are represented by finite matrices over `L`. Let `R ⊆ L` be the
`K`-subalgebra generated by the (finitely many) entries of both matrices. Then:

* `R` is finitely generated over `K` (`Subalgebra.FG`);
* the relations `e ∘ e.symm = id`, `e.symm ∘ e = id` and the `L ⊗[K] A`-linearity of `e`
  (its intertwining with the `A`-action, whose matrix has `K`-entries) are polynomial
  identities in the entries, hence already hold inside `R`;

so `e` descends to an `R ⊗[K] A`-linear isomorphism `R ⊗[K] V ≃ R ⊗[K] W`. Because both `e`
and `e.symm` have their entries adjoined, no localization is needed — invertibility is built
into `R` directly.

The pushforward `Etingof.Problem3_8_4.Functoriality.pushEquiv` along the inclusion
`R →ₐ[K] L` (`Subalgebra.val`) recovers `e` up to the canonical base-change comparison; the
assembly issue only consumes the *existence* recorded here.

The `R ⊗[K] A`-module structure on `R ⊗[K] V` is the one built for an arbitrary commutative
`K`-algebra in `Problem3_8_4_Functoriality.lean` (`Etingof.Problem3_8_4.Functoriality.bcMod`).
-/

open scoped TensorProduct

namespace Etingof.Problem3_8_4.Descent

open Etingof.Problem3_8_4.Functoriality

variable {K A V W L : Type*}
  [Field K] [Ring A] [Algebra K A]
  [AddCommGroup V] [Module K V] [Module A V] [IsScalarTower K A V]
  [AddCommGroup W] [Module K W] [Module A W] [IsScalarTower K A W]
  [Field L] [Algebra K L]

/-- **Descent of a base-change isomorphism to a finitely generated subalgebra.**

An `L ⊗[K] A`-linear isomorphism `L ⊗[K] V ≃ L ⊗[K] W` over a field extension `L / K` (with
`V`, `W` finite dimensional over `K`) already exists over a finitely generated `K`-subalgebra
`R ⊆ L`: there is `R : Subalgebra K L` with `R.FG` carrying an `R ⊗[K] A`-linear isomorphism
`R ⊗[K] V ≃ R ⊗[K] W`.

Pushing this forward along the inclusion `R →ₐ[K] L` (`pushEquiv`) returns to the isomorphism
over `L`; the follow-up assembly (Zariski's lemma to a residue field and the finite-degree
case) only needs the existence stated here. -/
theorem exists_fg_subalgebra_baseChange_iso
    [FiniteDimensional K V] [FiniteDimensional K W]
    (e : (L ⊗[K] V) ≃ₗ[L ⊗[K] A] (L ⊗[K] W)) :
    ∃ R : Subalgebra K L, R.FG ∧
      Nonempty ((R ⊗[K] V) ≃ₗ[R ⊗[K] A] (R ⊗[K] W)) := by
  sorry

end Etingof.Problem3_8_4.Descent
