import EtingofRepresentationTheory.Chapter3.Problem3_9_2
import Mathlib.Algebra.DualNumber
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas
import Mathlib.LinearAlgebra.Projection

/-!
# Two-dimensional representations of `ℂ[x₁, …, xₙ]` up to isomorphism

Problem 3.9.2(a) asks for the classification of the 2-dimensional representations of
`A = ℂ[x₁, …, xₙ]`. `Etingof.Problem3_9_2.two_dim_is_extension` supplies the reduction step:
every 2-dimensional representation is an extension of two 1-dimensional ones. This file turns
that reduction into a classification: it exhibits explicit normal forms, proves every
2-dimensional representation is isomorphic to one of them, and decides when two normal forms
are isomorphic.

Two families of normal forms occur.

* For a pair of weights `a ≠ b` the extension splits, because `Ext¹(Vₐ, V_b) = 0`
  (`ext1_subsingleton_of_ne`), and the module is the direct sum `V_b × Vₐ`.
* For a single weight `a` the extensions of `Vₐ` by itself are classified by
  `Ext¹(Vₐ, Vₐ) ≅ ℂⁿ` (`ext1_self`). The module attached to `c : Fin n → ℂ` is `Jrep a c`,
  the algebra of dual numbers `ℂ[ε]` with `xᵢ` acting as `aᵢ + cᵢ ε`. The class `c = 0` gives the
  split module `Vₐ × Vₐ`, and `Jrep a c ≅ Jrep a c'` exactly when `c` and `c'` are proportional,
  so the nonsplit self-extensions are parametrized by the projective space of `ℂⁿ`.

The two families are disjoint: a module in the first family has two distinct weights, one in the
second family has a single weight.
-/

namespace Etingof.Problem3_9_2

open Etingof.Problem3_9_1
open MvPolynomial
open DualNumber

/-! ## The generators as `ℂ`-linear endomorphisms -/

section GenEnd

variable {n : ℕ} {M : Type*} [AddCommGroup M] [Module ℂ M] [Module (polyAlg n) M]
  [IsScalarTower ℂ (polyAlg n) M]

/-- The `polyAlg n`-action commutes with the `ℂ`-action, since `ℂ` is central in `polyAlg n`. -/
lemma smulCommClass_polyAlg : SMulCommClass (polyAlg n) ℂ M :=
  ⟨fun q r m => by
    rw [← algebraMap_smul (polyAlg n) r m, ← mul_smul, ← algebraMap_smul (polyAlg n) r (q • m),
      ← mul_smul, Algebra.commutes]⟩

/-- The action of the generator `xᵢ` as a `ℂ`-linear endomorphism. -/
noncomputable def genEnd (i : Fin n) : Module.End ℂ M :=
  letI := smulCommClass_polyAlg (n := n) (M := M)
  { toFun := fun m => (X i : polyAlg n) • m
    map_add' := fun x y => smul_add _ _ _
    map_smul' := fun r m => by
      simp only [RingHom.id_apply]
      exact smul_comm (X i : polyAlg n) r m }

@[simp] lemma genEnd_apply (i : Fin n) (m : M) : genEnd i m = (X i : polyAlg n) • m := rfl

end GenEnd

/-! ## `ℂ`-linear equivalences commuting with the generators are `A`-linear -/

/-- A `ℂ`-linear equivalence between two `A`-modules that commutes with the action of every
generator `xᵢ` is `A`-linear. Since `A` is generated by the `xᵢ` over `ℂ`, the multiplicative
structure is determined by the generators. -/
theorem nonempty_linearEquiv_of_comm_X {n : ℕ} {M N : Type*}
    [AddCommGroup M] [Module ℂ M] [Module (polyAlg n) M] [IsScalarTower ℂ (polyAlg n) M]
    [AddCommGroup N] [Module ℂ N] [Module (polyAlg n) N] [IsScalarTower ℂ (polyAlg n) N]
    (e : M ≃ₗ[ℂ] N)
    (h : ∀ (i : Fin n) (m : M), e ((X i : polyAlg n) • m) = (X i : polyAlg n) • e m) :
    Nonempty (M ≃ₗ[polyAlg n] N) := by
  have key : ∀ (p : polyAlg n) (m : M), e (p • m) = p • e m := by
    intro p
    induction p using MvPolynomial.induction_on with
    | C r =>
      intro m
      rw [← MvPolynomial.algebraMap_eq, algebraMap_smul, algebraMap_smul, map_smul]
    | add p q hp hq => intro m; rw [add_smul, map_add, hp, hq, add_smul]
    | mul_X p i hp => intro m; rw [mul_smul, hp, h, ← mul_smul]
  exact ⟨{ e with map_smul' := key }⟩

/-- To check that a `ℂ`-linear equivalence commutes with the generators it suffices to check it
on a `ℂ`-basis. -/
theorem nonempty_linearEquiv_of_comm_X_basis {n : ℕ} {M N : Type*}
    [AddCommGroup M] [Module ℂ M] [Module (polyAlg n) M] [IsScalarTower ℂ (polyAlg n) M]
    [AddCommGroup N] [Module ℂ N] [Module (polyAlg n) N] [IsScalarTower ℂ (polyAlg n) N]
    {ι : Type*} (B : Module.Basis ι ℂ M) (e : M ≃ₗ[ℂ] N)
    (h : ∀ (i : Fin n) (j : ι), e ((X i : polyAlg n) • B j) = (X i : polyAlg n) • e (B j)) :
    Nonempty (M ≃ₗ[polyAlg n] N) := by
  refine nonempty_linearEquiv_of_comm_X e fun i m => ?_
  have hmaps : (e.toLinearMap ∘ₗ genEnd (M := M) i) = (genEnd (M := N) i ∘ₗ e.toLinearMap) :=
    B.ext fun j => by simpa using h i j
  simpa using LinearMap.congr_fun hmaps m

/-! ## The dual-number normal form `Jrep a c` -/

/-- Carrier of the normal form attached to a weight `a` and an extension class `c`: the algebra
`ℂ[ε]` of dual numbers. The parameters appear in the type so that distinct parameters carry
distinct `polyAlg n`-module structures. -/
def Jrep {n : ℕ} (_a _c : Fin n → ℂ) : Type := DualNumber ℂ

namespace Jrep

variable {n : ℕ} (a c : Fin n → ℂ)

instance : CommRing (Jrep a c) := inferInstanceAs (CommRing (DualNumber ℂ))
instance : Algebra ℂ (Jrep a c) := inferInstanceAs (Algebra ℂ (DualNumber ℂ))
instance : Module.Finite ℂ (Jrep a c) := inferInstanceAs (Module.Finite ℂ (ℂ × ℂ))
instance : Nontrivial (Jrep a c) := inferInstanceAs (Nontrivial (ℂ × ℂ))
instance : FiniteDimensional ℂ (Jrep a c) := inferInstanceAs (FiniteDimensional ℂ (ℂ × ℂ))

/-- The nilpotent dual number `ε`, spanning the unique one-dimensional submodule. -/
def eps : Jrep a c := (ε : DualNumber ℂ)

@[simp] theorem eps_mul_eps : eps a c * eps a c = 0 := DualNumber.eps_mul_eps

/-- First dual-number coordinate. -/
def fst (x : Jrep a c) : ℂ := TrivSqZeroExt.fst (x : DualNumber ℂ)

/-- Second dual-number coordinate. -/
def snd (x : Jrep a c) : ℂ := TrivSqZeroExt.snd (x : DualNumber ℂ)

@[simp] theorem fst_zero : fst a c 0 = 0 := rfl
@[simp] theorem snd_zero : snd a c 0 = 0 := rfl
@[simp] theorem fst_one : fst a c 1 = 1 := rfl
@[simp] theorem snd_one : snd a c 1 = 0 := rfl
@[simp] theorem fst_eps : fst a c (eps a c) = 0 := rfl
@[simp] theorem snd_eps : snd a c (eps a c) = 1 := rfl

@[simp] theorem fst_add (x y : Jrep a c) : fst a c (x + y) = fst a c x + fst a c y := rfl
@[simp] theorem snd_add (x y : Jrep a c) : snd a c (x + y) = snd a c x + snd a c y := rfl
@[simp] theorem fst_smul (r : ℂ) (x : Jrep a c) : fst a c (r • x) = r * fst a c x := rfl
@[simp] theorem snd_smul (r : ℂ) (x : Jrep a c) : snd a c (r • x) = r * snd a c x := rfl

theorem ext {x y : Jrep a c} (h1 : fst a c x = fst a c y) (h2 : snd a c x = snd a c y) : x = y :=
  TrivSqZeroExt.ext h1 h2

/-- Every dual number is a `ℂ`-combination of `1` and `ε`. -/
theorem eq_smul_one_add_smul_eps (x : Jrep a c) :
    x = fst a c x • (1 : Jrep a c) + snd a c x • eps a c := by
  refine ext a c ?_ ?_ <;> simp

end Jrep

/-- Multiplying a dual number by `ε` retains only its scalar part. -/
private theorem dualNumber_eps_mul (x : DualNumber ℂ) :
    (ε : DualNumber ℂ) * x = TrivSqZeroExt.fst x • (ε : DualNumber ℂ) := by
  refine TrivSqZeroExt.ext ?_ ?_ <;>
    simp [TrivSqZeroExt.fst_mul, TrivSqZeroExt.snd_mul]

theorem Jrep.eps_mul {n : ℕ} (a c : Fin n → ℂ) (x : Jrep a c) :
    eps a c * x = fst a c x • eps a c :=
  dualNumber_eps_mul x

/-- The algebra map sending `xᵢ` to the dual number `aᵢ + cᵢ ε`. -/
noncomputable def jHom {n : ℕ} (a c : Fin n → ℂ) : polyAlg n →ₐ[ℂ] Jrep a c :=
  MvPolynomial.aeval fun i => algebraMap ℂ (Jrep a c) (a i) + c i • Jrep.eps a c

@[simp] theorem jHom_X {n : ℕ} (a c : Fin n → ℂ) (i : Fin n) :
    jHom a c (X i) = algebraMap ℂ (Jrep a c) (a i) + c i • Jrep.eps a c := by
  simp [jHom]

noncomputable instance jrepModule {n : ℕ} (a c : Fin n → ℂ) : Module (polyAlg n) (Jrep a c) :=
  Module.compHom (Jrep a c) (jHom a c).toRingHom

theorem jrep_smul_def {n : ℕ} (a c : Fin n → ℂ) (p : polyAlg n) (x : Jrep a c) :
    p • x = jHom a c p * x := rfl

instance {n : ℕ} (a c : Fin n → ℂ) : IsScalarTower ℂ (polyAlg n) (Jrep a c) :=
  ⟨fun r p x => by rw [jrep_smul_def, jrep_smul_def, map_smul, smul_mul_assoc]⟩

theorem jrep_finrank {n : ℕ} (a c : Fin n → ℂ) : Module.finrank ℂ (Jrep a c) = 2 := by
  show Module.finrank ℂ (ℂ × ℂ) = 2
  rw [Module.finrank_prod, Module.finrank_self]

/-- The generator `xᵢ` acts on `Jrep a c` as `aᵢ + cᵢ ε`. -/
theorem jrep_X_smul {n : ℕ} (a c : Fin n → ℂ) (i : Fin n) (x : Jrep a c) :
    (X i : polyAlg n) • x = a i • x + c i • (Jrep.eps a c * x) := by
  rw [jrep_smul_def, jHom_X, add_mul, Algebra.algebraMap_eq_smul_one, smul_mul_assoc, one_mul,
    smul_mul_assoc]

@[simp] theorem jrep_X_smul_one {n : ℕ} (a c : Fin n → ℂ) (i : Fin n) :
    (X i : polyAlg n) • (1 : Jrep a c) = a i • (1 : Jrep a c) + c i • Jrep.eps a c := by
  rw [jrep_X_smul, mul_one]

@[simp] theorem jrep_X_smul_eps {n : ℕ} (a c : Fin n → ℂ) (i : Fin n) :
    (X i : polyAlg n) • Jrep.eps a c = a i • Jrep.eps a c := by
  rw [jrep_X_smul, Jrep.eps_mul_eps, smul_zero, add_zero]

/-- `ε` is a weight vector of weight `a`. -/
theorem jrep_eps_ne_zero {n : ℕ} (a c : Fin n → ℂ) : Jrep.eps a c ≠ 0 := by
  intro h
  have := congrArg (Jrep.snd a c) h
  simp at this

/-- The `ℂ`-basis `1, ε` of `Jrep a c`. -/
noncomputable def jrepBasis {n : ℕ} (a c : Fin n → ℂ) :
    Module.Basis (Fin 2) ℂ (Jrep a c) := by
  refine basisOfLinearIndependentOfCardEqFinrank
    (b := ![(1 : Jrep a c), Jrep.eps a c]) ?_ ?_
  · rw [LinearIndependent.pair_iff]
    intro s t hst
    have h1 := congrArg (Jrep.fst a c) hst
    have h2 := congrArg (Jrep.snd a c) hst
    simp only [Jrep.fst_add, Jrep.snd_add, Jrep.fst_smul, Jrep.snd_smul, Jrep.fst_one,
      Jrep.snd_one, Jrep.fst_eps, Jrep.snd_eps, mul_one, mul_zero, add_zero, zero_add,
      Jrep.fst_zero, Jrep.snd_zero] at h1 h2
    exact ⟨h1, h2⟩
  · rw [Fintype.card_fin, jrep_finrank]

@[simp] theorem jrepBasis_apply {n : ℕ} (a c : Fin n → ℂ) (j : Fin 2) :
    jrepBasis a c j = ![(1 : Jrep a c), Jrep.eps a c] j := by
  rw [jrepBasis, coe_basisOfLinearIndependentOfCardEqFinrank]

/-! ## Exhaustiveness of the normal forms -/

/-- **Every 2-dimensional representation is a normal form.** A 2-dimensional representation of
`ℂ[x₁, …, xₙ]` is isomorphic either to a direct sum `V_b × Vₐ` of two 1-dimensional
representations with distinct weights, or to a dual-number module `Jrep a c`. -/
theorem two_dim_normal_form {n : ℕ} (U : Type)
    [AddCommGroup U] [Module ℂ U] [Module (polyAlg n) U] [IsScalarTower ℂ (polyAlg n) U]
    [FiniteDimensional ℂ U] (hdim : Module.finrank ℂ U = 2) :
    (∃ b a : Fin n → ℂ, b ≠ a ∧ Nonempty (U ≃ₗ[polyAlg n] Vrep b × Vrep a)) ∨
      (∃ a c : Fin n → ℂ, Nonempty (U ≃ₗ[polyAlg n] Jrep a c)) := by
  sorry

/-! ## The isomorphism criterion -/

/-- Two dual-number normal forms are isomorphic exactly when they share the weight and their
extension classes are proportional. So the nonzero classes contribute the projective space of
`ℂⁿ`, and the zero class the split module. -/
theorem jrep_iso_iff {n : ℕ} (a c a' c' : Fin n → ℂ) :
    Nonempty (Jrep a c ≃ₗ[polyAlg n] Jrep a' c') ↔
      a = a' ∧ ∃ lam : ℂ, lam ≠ 0 ∧ c' = lam • c := by
  sorry

/-- The split normal forms are isomorphic exactly when their weights agree as unordered pairs. -/
theorem split_iso_iff {n : ℕ} (b a b' a' : Fin n → ℂ) (hba : b ≠ a) (hba' : b' ≠ a') :
    Nonempty ((Vrep b × Vrep a) ≃ₗ[polyAlg n] Vrep b' × Vrep a') ↔
      (b = b' ∧ a = a') ∨ (b = a' ∧ a = b') := by
  sorry

/-- A split module with distinct weights is never a dual-number module: it has two weights,
whereas `Jrep a' c'` has only the weight `a'`. -/
theorem split_not_iso_jrep {n : ℕ} (b a a' c' : Fin n → ℂ) (hba : b ≠ a) :
    ¬ Nonempty ((Vrep b × Vrep a) ≃ₗ[polyAlg n] Jrep a' c') := by
  sorry

end Etingof.Problem3_9_2
