import EtingofRepresentationTheory.Chapter3.Problem3_9_1
import EtingofRepresentationTheory.Chapter2.Definition2_3_8
import Mathlib.Data.Complex.Basic
import Mathlib.RingTheory.MvPolynomial.Basic
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.Algebra.FreeAlgebra
import Mathlib.Algebra.RingQuot
import Mathlib.LinearAlgebra.FiniteDimensional.Defs

/-!
# Problem 3.9.2: `Ext¹` for polynomial algebras and algebras with zero multiplication

**(a)** Let `A = ℂ[x₁, …, xₙ]` and let `Vₐ, V_b` be the 1-dimensional representations in which
`xᵢ` acts by `aᵢ`, `bᵢ` respectively. Compute `Ext¹(Vₐ, V_b)` and classify the 2-dimensional
representations of `A`.

**(b)** Let `B = ℂ⟨x₁, …, xₙ⟩ / (xᵢxⱼ = 0)`. Show that for `n > 1`, `B` has infinitely many
nonisomorphic indecomposable representations.

We model the 1-dimensional representation `Vₐ` as the quotient `A ⧸ 𝔪ₐ` by the maximal
ideal `𝔪ₐ = (x₁ − a₁, …, xₙ − aₙ)`. This is a genuine `A`-module and `ℂ`-module with the
scalar tower `ℂ → A → A⧸𝔪ₐ`, on which `xᵢ` acts by the scalar `aᵢ`, so it fits the
`Ext¹` framework of Problem 3.9.1 (`Etingof.Problem3_9_1.Ext1`). The convention there is that
`Ext1 k A V W` classifies extensions `0 → V → U → W → 0`, i.e. `Ext¹(W, V)`; so the book's
`Ext¹(Vₐ, V_b)` — extensions `0 → V_b → U → Vₐ → 0` — is `Ext1 ℂ A V_b Vₐ`.

The answer to (a): `Ext¹(Vₐ, V_b) ≅ ℂⁿ` if `a = b` and `= 0` if `a ≠ b`. Every 2-dimensional
representation is an extension of two 1-dimensional ones, so is classified by the pair
`(a, b)` together with a class in `Ext¹(Vₐ, V_b)`.

For (b) the algebra `B` is the free algebra `ℂ⟨x₁,…,xₙ⟩` modulo the two-sided relations
`xᵢxⱼ = 0`, constructed as a `RingQuot`.

Statement pass: the modules and algebras are genuinely constructed; proofs are `sorry`.
-/

namespace Etingof.Problem3_9_2

open Etingof.Problem3_9_1 (Ext1)

/-! ## Part (a): the polynomial algebra `ℂ[x₁, …, xₙ]` -/

/-- The polynomial algebra `A = ℂ[x₁, …, xₙ]`. -/
abbrev polyAlg (n : ℕ) : Type := MvPolynomial (Fin n) ℂ

/-- The maximal ideal `𝔪ₐ = (x₁ − a₁, …, xₙ − aₙ)` of `ℂ[x₁, …, xₙ]` at the point `a`. -/
noncomputable def maxIdeal {n : ℕ} (a : Fin n → ℂ) : Ideal (polyAlg n) :=
  Ideal.span (Set.range fun i => MvPolynomial.X i - MvPolynomial.C (a i))

/-- The 1-dimensional representation `Vₐ`, in which `xᵢ` acts by the scalar `aᵢ`, modelled as
the quotient `A ⧸ 𝔪ₐ`. A genuine `A`-module and `ℂ`-module with scalar tower. -/
abbrev Vrep {n : ℕ} (a : Fin n → ℂ) : Type := polyAlg n ⧸ maxIdeal a

/-- **Problem 3.9.2(a), equal weights.** `Ext¹(Vₐ, Vₐ) ≅ ℂⁿ`: self-extensions of the
1-dimensional rep are classified by the `n` "nilpotent directions" `xᵢ`. -/
theorem ext1_self {n : ℕ} (a : Fin n → ℂ) :
    Nonempty (Ext1 ℂ (polyAlg n) (Vrep a) (Vrep a) ≃ₗ[ℂ] (Fin n → ℂ)) := by
  sorry

/-- **Problem 3.9.2(a), distinct weights.** `Ext¹(Vₐ, V_b) = 0` when `a ≠ b`: any extension
splits because some `xⱼ` has distinct eigenvalues `aⱼ ≠ bⱼ`. -/
theorem ext1_subsingleton_of_ne {n : ℕ} (a b : Fin n → ℂ) (hab : a ≠ b) :
    Subsingleton (Ext1 ℂ (polyAlg n) (Vrep b) (Vrep a)) := by
  sorry

/-- **Problem 3.9.2(a), classification of 2-dimensional representations.** Every
2-dimensional representation `U` of `ℂ[x₁, …, xₙ]` is an extension of two 1-dimensional
representations: there is a pair of weights `a, b` and a subrepresentation `S ≅ V_b` with
quotient `U ⧸ S ≅ Vₐ`. Combined with the `Ext¹` computation above, this classifies the
2-dimensional representations. -/
theorem two_dim_is_extension {n : ℕ} (U : Type)
    [AddCommGroup U] [Module ℂ U] [Module (polyAlg n) U] [IsScalarTower ℂ (polyAlg n) U]
    [FiniteDimensional ℂ U] (hdim : Module.finrank ℂ U = 2) :
    ∃ (a b : Fin n → ℂ) (S : Submodule (polyAlg n) U),
      Nonempty (S ≃ₗ[polyAlg n] Vrep b) ∧ Nonempty ((U ⧸ S) ≃ₗ[polyAlg n] Vrep a) := by
  sorry

/-! ## Part (b): the algebra with zero multiplication `B = ℂ⟨x₁,…,xₙ⟩/(xᵢxⱼ)` -/

/-- The defining relations of `B`: every product `xᵢ xⱼ` of generators is zero. -/
inductive BRel (n : ℕ) : FreeAlgebra ℂ (Fin n) → FreeAlgebra ℂ (Fin n) → Prop
  | mul (i j : Fin n) :
      BRel n (FreeAlgebra.ι ℂ i * FreeAlgebra.ι ℂ j) 0

/-- The algebra `B = ℂ⟨x₁, …, xₙ⟩ / (xᵢxⱼ = 0)`, the free algebra on `n` generators modulo
the two-sided ideal generated by all products of generators. Genuinely constructed via
`RingQuot`. -/
abbrev zeroMulAlg (n : ℕ) : Type := RingQuot (BRel n)

/-- **Problem 3.9.2(b).** For `n > 1`, the algebra `B` has infinitely many nonisomorphic
indecomposable representations: there is a family `M : ℕ → Type` of pairwise nonisomorphic
indecomposable `B`-modules. -/
theorem infinitely_many_indecomposables {n : ℕ} (hn : 1 < n) :
    ∃ (M : ℕ → Type) (_ : ∀ k, AddCommGroup (M k)) (_ : ∀ k, Module (zeroMulAlg n) (M k)),
      (∀ k, Etingof.IsIndecomposable (zeroMulAlg n) (M k)) ∧
      (∀ k l, Nonempty ((M k) ≃ₗ[zeroMulAlg n] (M l)) → k = l) := by
  sorry

end Etingof.Problem3_9_2
