import Mathlib.LinearAlgebra.CliffordAlgebra.Contraction
import Mathlib.LinearAlgebra.BilinearForm.Properties
import Mathlib.LinearAlgebra.ExteriorAlgebra.Basis
import Mathlib.LinearAlgebra.Trace
import Mathlib.RingTheory.Artinian.Algebra
import Mathlib.RingTheory.Artinian.Ring
import Mathlib.LinearAlgebra.Dimension.OrzechProperty
import Mathlib.RingTheory.SimpleModule.IsAlgClosed
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.Algebra.Algebra.Subalgebra.Pi
import Mathlib.Algebra.Central.Matrix

/-!
# Problem 3.9.5: The Clifford algebra

Let `V` be a finite dimensional complex vector space with a symmetric bilinear form
`(·,·) = B`. The **Clifford algebra** `Cl(V)` is the quotient of the tensor algebra `TV`
by the ideal generated by `v ⊗ v − (v,v)·1`. Equivalently, for a basis `xᵢ` with
`(xᵢ, xⱼ) = aᵢⱼ`, it is generated by the `xᵢ` with relations
`xᵢ xⱼ + xⱼ xᵢ = 2aᵢⱼ`, `xᵢ² = aᵢᵢ`. If `(·,·) = 0`, then `Cl(V) = ⋀ V`.

We model `Cl(V)` as Mathlib's `CliffordAlgebra Q` for the quadratic form
`Q(v) = B(v, v)` (`LinearMap.BilinMap.toQuadraticMap B`). Its defining relation
`ι(v)² = Q(v)` polarises to `ι(v)ι(w) + ι(w)ι(v) = B(v,w) + B(w,v) = 2B(v,w)` when `B`
is symmetric, matching the book's relations with `aᵢⱼ = B(xᵢ, xⱼ)`.

* **(i)** If `B` is nondegenerate then `Cl(V)` is semisimple. If `dim V = 2n` it is a
  matrix algebra, with a single irreducible representation `S` (the spinor module) of
  dimension `2ⁿ`; if `dim V = 2n+1` it is a direct sum of two matrix algebras, with two
  non-isomorphic irreducible representations `S₊, S₋` of dimension `2ⁿ`.
* **(ii)** `Cl(V)` is semisimple iff `B` is nondegenerate. When `B` is degenerate, the
  semisimple quotient `Cl(V) / Rad(Cl(V))` is the (nondegenerate) Clifford algebra of the
  induced form on `V` modulo the radical of `B`.

A "matrix algebra" is phrased as `Module.End ℂ S` for a finite dimensional `S`: the
endomorphism algebra of its `2ⁿ`-dimensional spinor representation, which is exactly the
statement that `S` is the unique irreducible module.

The quadratic form and Clifford algebra are constructed and both parts are proved.
-/

namespace Etingof.Problem3_9_5

variable {V : Type*} [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V]
  (B : LinearMap.BilinForm ℂ V)

/-- The quadratic form `Q(v) = (v, v) = B v v` attached to the symmetric bilinear form `B`.
Constructed via `LinearMap.BilinMap.toQuadraticMap`. -/
noncomputable abbrev quadForm : QuadraticForm ℂ V :=
  LinearMap.BilinMap.toQuadraticMap B

/-- The Clifford algebra `Cl(V)` of the form, as `CliffordAlgebra Q`. -/
abbrev CliffAlg : Type _ := CliffordAlgebra (quadForm B)

/-- `Cl(V)` is finite-dimensional over `ℂ`. Transport the finite basis of `⋀ V` (indexed by
`Finset` of a basis of `V`, `Module.Basis.ExteriorAlgebra`) across the characteristic-≠-2 linear
equivalence `CliffordAlgebra.equivExterior`. This underlies every part of the problem: it makes
`Cl(V)` an Artinian ring, so `IsSemisimpleRing`/Jacobson-radical machinery applies. -/
instance : Module.Finite ℂ (CliffAlg B) := by
  haveI : Invertible (2 : ℂ) := invertibleOfNonzero two_ne_zero
  haveI : Module.Finite ℂ (ExteriorAlgebra ℂ V) :=
    Module.Finite.of_basis (Module.Basis.ExteriorAlgebra (Module.finBasis ℂ V))
  exact Module.Finite.equiv (CliffordAlgebra.equivExterior (quadForm B)).symm

omit [FiniteDimensional ℂ V] in
/-- **Parenthetical.** If the form is zero, `Cl(V)` is the exterior algebra `⋀ V`. -/
theorem cliffordAlgebra_zero_eq_exterior :
    Nonempty (CliffordAlgebra (quadForm (0 : LinearMap.BilinForm ℂ V)) ≃ₐ[ℂ]
      ExteriorAlgebra ℂ V) := by
  -- `ExteriorAlgebra ℂ V` is *defined* as `CliffordAlgebra (0 : QuadraticForm ℂ V)`, so it
  -- suffices to see that the quadratic form of the zero bilinear form is the zero form.
  have hq : quadForm (0 : LinearMap.BilinForm ℂ V) = (0 : QuadraticForm ℂ V) := by
    ext v
    simp [quadForm]
  rw [hq]
  exact ⟨AlgEquiv.refl⟩

/-- **Dickson's semisimplicity criterion (characteristic zero).** A finite-dimensional `ℂ`-algebra
`A` is semisimple as soon as its trace form `(x, y) ↦ tr(L_{xy})` (where `L_z` is left
multiplication by `z`) is nondegenerate.

`A` is Artinian, so its Jacobson radical `J` is a nilpotent ideal. For `x ∈ J` and any `y`, the
element `y * x` again lies in `J`, hence is nilpotent, so `L_{y*x}` is a nilpotent operator and its
trace vanishes. Since `tr(L_{x*y}) = tr(L_x L_y) = tr(L_y L_x) = tr(L_{y*x}) = 0` for every `y`,
nondegeneracy forces `x = 0`; thus `J = 0` and `A` is semisimple. -/
theorem isSemisimpleRing_of_traceForm_nondegenerate
    {A : Type*} [Ring A] [Algebra ℂ A] [Module.Finite ℂ A]
    (hnd : ∀ x : A, (∀ y : A, LinearMap.trace ℂ A (LinearMap.mulLeft ℂ (x * y)) = 0) → x = 0) :
    IsSemisimpleRing A := by
  haveI : IsArtinianRing A := IsArtinianRing.of_finite ℂ A
  rw [IsArtinianRing.isSemisimpleRing_iff_jacobson, eq_bot_iff]
  intro x hx
  rw [Ideal.mem_bot]
  apply hnd
  intro y
  -- Symmetry of the trace form: `tr(L_{x*y}) = tr(L_{y*x})`.
  have hsymm : LinearMap.trace ℂ A (LinearMap.mulLeft ℂ (x * y))
      = LinearMap.trace ℂ A (LinearMap.mulLeft ℂ (y * x)) := by
    rw [LinearMap.mulLeft_mul, LinearMap.mulLeft_mul,
      ← Module.End.mul_eq_comp, ← Module.End.mul_eq_comp, LinearMap.trace_mul_comm]
  rw [hsymm]
  -- `y * x` lies in the (nilpotent) Jacobson radical, so it is a nilpotent element.
  have hyx : y * x ∈ Ring.jacobson A := (Ring.jacobson A).mul_mem_left y hx
  obtain ⟨n, hn⟩ := IsArtinianRing.isNilpotent_jacobson_bot (R := A)
  rw [Ideal.jacobson_bot] at hn
  have hnil : IsNilpotent (y * x) := by
    refine ⟨n, ?_⟩
    have hmem : (y * x) ^ n ∈ (Ring.jacobson A) ^ n := Ideal.pow_mem_pow hyx n
    rw [hn] at hmem
    simpa using hmem
  -- Left multiplication by a nilpotent element is a nilpotent operator, hence has zero trace.
  have hmul : IsNilpotent (LinearMap.mulLeft ℂ (y * x)) :=
    hnil.map (Algebra.lmul ℂ A).toRingHom
  exact (LinearMap.isNilpotent_trace_of_isNilpotent hmul).eq_zero

/-!
### Orthogonal monomial basis of `Cl(V)`

For an orthogonal basis `v` of `V` (with respect to `B`), the `2^N` ordered products
`e S = ∏_{i ∈ S} ι(vᵢ)` (the product taken in increasing order of `i`) form a basis of `Cl(V)`.
Because the basis is orthogonal, the generators satisfy the clean relations
`ι(vᵢ) ι(vⱼ) = - ι(vⱼ) ι(vᵢ)` for `i ≠ j` and `ι(vᵢ)² = B(vᵢ,vᵢ)`, with no lower-order
correction terms. This makes left multiplication by `e S` a signed permutation of the monomial
basis, from which `tr(L_{e S})` and the nondegeneracy of the trace form drop out.
-/

section Monomial

variable {N : ℕ} (v : Module.Basis (Fin N) ℂ V)

open CliffordAlgebra in
/-- The Clifford generator `ι(vᵢ)` attached to the `i`-th orthogonal basis vector. -/
noncomputable def gen (i : Fin N) : CliffAlg B := CliffordAlgebra.ι (quadForm B) (v i)

open scoped Classical in
/-- Ordered monomial `e S = ∏_{i ∈ S} ι(vᵢ)`, the product taken in increasing order of `i`. -/
noncomputable def e (S : Finset (Fin N)) : CliffAlg B :=
  ((S.sort (· ≤ ·)).map (gen B v)).prod

omit [FiniteDimensional ℂ V] in
@[simp] theorem e_empty : e B v ∅ = 1 := by
  simp [e]

omit [FiniteDimensional ℂ V] in
@[simp] theorem e_singleton (i : Fin N) : e B v {i} = gen B v i := by
  simp [e, Finset.sort_singleton]

omit [FiniteDimensional ℂ V] in
/-- If `i` is strictly below every element of `S`, then `e (insert i S) = ι(vᵢ) · e S`
(no reordering needed since `i` is the new minimum). -/
theorem e_insert_of_lt {i : Fin N} {S : Finset (Fin N)} (h : ∀ j ∈ S, i < j) :
    e B v (insert i S) = gen B v i * e B v S := by
  have hi : i ∉ S := fun hmem => (lt_irrefl i (h i hmem))
  rw [e, Finset.sort_insert (· ≤ ·) (fun j hj => (h j hj).le) hi, List.map_cons, List.prod_cons, e]

omit [FiniteDimensional ℂ V] in
/-- Peeling off the minimum: `e S = ι(v (min S)) · e (S.erase (min S))`. -/
theorem e_minPeel {S : Finset (Fin N)} (hS : S.Nonempty) :
    e B v S = gen B v (S.min' hS) * e B v (S.erase (S.min' hS)) := by
  have hmem : S.min' hS ∈ S := S.min'_mem hS
  have hlt : ∀ j ∈ S.erase (S.min' hS), S.min' hS < j := by
    intro j hj
    rw [Finset.mem_erase] at hj
    exact lt_of_le_of_ne (S.min'_le j hj.2) (Ne.symm hj.1)
  conv_lhs => rw [← Finset.insert_erase hmem]
  exact e_insert_of_lt B v hlt

omit [FiniteDimensional ℂ V] in
/-- `ι(vᵢ)² = B(vᵢ,vᵢ)` as a scalar. -/
theorem gen_sq (i : Fin N) :
    gen B v i * gen B v i = algebraMap ℂ (CliffAlg B) (B (v i) (v i)) := by
  unfold gen
  rw [CliffordAlgebra.ι_sq_scalar]
  rfl

omit [FiniteDimensional ℂ V] in
/-- For an orthogonal basis, distinct generators anticommute. -/
theorem gen_anticomm (hv : B.IsOrthoᵢ v) {i j : Fin N} (hij : i ≠ j) :
    gen B v i * gen B v j = - (gen B v j * gen B v i) := by
  have h := CliffordAlgebra.ι_mul_ι_add_swap (Q := quadForm B) (v i) (v j)
  have hpolar : QuadraticMap.polar (quadForm B) (v i) (v j) = 0 := by
    rw [LinearMap.BilinMap.polar_toQuadraticMap,
      LinearMap.isOrthoᵢ_def.mp hv i j hij, LinearMap.isOrthoᵢ_def.mp hv j i hij.symm, add_zero]
  rw [hpolar, map_zero] at h
  unfold gen
  exact eq_neg_of_add_eq_zero_left h

omit [FiniteDimensional ℂ V] in
/-- On a nondegenerate orthogonal basis, every diagonal entry `B(vᵢ,vᵢ)` is nonzero. -/
theorem diag_ne_zero (hv : B.IsOrthoᵢ v) (hnd : B.Nondegenerate) (i : Fin N) :
    B (v i) (v i) ≠ 0 := by
  intro hz
  refine v.ne_zero i (hnd.1 (v i) ?_)
  intro y
  have hzero : B (v i) = 0 := by
    apply v.ext
    intro j
    rcases eq_or_ne i j with rfl | hij
    · simpa using hz
    · simpa using LinearMap.isOrthoᵢ_def.mp hv i j hij
  rw [hzero, LinearMap.zero_apply]

omit [FiniteDimensional ℂ V] in
/-- Each generator is a unit (its inverse is `B(vᵢ,vᵢ)⁻¹ · ι(vᵢ)`). -/
theorem isUnit_gen (hv : B.IsOrthoᵢ v) (hnd : B.Nondegenerate) (i : Fin N) :
    IsUnit (gen B v i) := by
  have ha := diag_ne_zero B v hv hnd i
  refine ⟨⟨gen B v i, (B (v i) (v i))⁻¹ • gen B v i, ?_, ?_⟩, rfl⟩
  · rw [mul_smul_comm, gen_sq, Algebra.smul_def, ← map_mul, inv_mul_cancel₀ ha, map_one]
  · rw [smul_mul_assoc, gen_sq, Algebra.smul_def, ← map_mul, inv_mul_cancel₀ ha, map_one]

omit [FiniteDimensional ℂ V] in
open scoped Classical in
/-- The monomial `e S` is a unit (a product of units). -/
theorem isUnit_e (hv : B.IsOrthoᵢ v) (hnd : B.Nondegenerate) (S : Finset (Fin N)) :
    IsUnit (e B v S) := by
  rw [e]
  apply List.prod_isUnit
  intro x hx
  rw [List.mem_map] at hx
  obtain ⟨i, _, rfl⟩ := hx
  exact isUnit_gen B v hv hnd i

open scoped symmDiff

omit [FiniteDimensional ℂ V] in
/-- **Generator × monomial reduction.** `ι(vⱼ) · e U` is a scalar multiple of the monomial on
`U ∆ {j}`. Proved by strong induction on `U`: peel the minimum `k` of `U`, and recurse on the
same index `j` with the smaller set `U.erase k` (valid since `j > k`), handling `j < min U` and
`j = min U` directly. Because the basis is orthogonal, no lower-order terms appear. -/
theorem gen_mul_mem (hv : B.IsOrthoᵢ v) (j : Fin N) (U : Finset (Fin N)) :
    gen B v j * e B v U ∈ Submodule.span ℂ {e B v (U ∆ {j})} := by
  induction U using Finset.strongInductionOn with
  | _ U ih =>
    rcases U.eq_empty_or_nonempty with rfl | hU
    · have h0 : (∅ : Finset (Fin N)) ∆ {j} = {j} := by ext a; simp [Finset.mem_symmDiff]
      rw [e_empty, mul_one, h0, e_singleton]
      exact Submodule.mem_span_singleton_self _
    · rcases lt_trichotomy j (U.min' hU) with hjk | hjk | hjk
      · -- `j < min U`: `ι(vⱼ)` prepends directly and `U ∆ {j} = insert j U`.
        have hjnotU : j ∉ U := fun hmem => absurd (U.min'_le j hmem) (not_le.mpr hjk)
        have hlt : ∀ i ∈ U, j < i := fun i hi => lt_of_lt_of_le hjk (U.min'_le i hi)
        have hset : U ∆ {j} = insert j U := by
          ext a
          simp only [Finset.mem_symmDiff, Finset.mem_singleton, Finset.mem_insert]
          constructor
          · rintro (⟨ha, _⟩ | ⟨rfl, _⟩)
            · exact Or.inr ha
            · exact Or.inl rfl
          · rintro (rfl | ha)
            · exact Or.inr ⟨rfl, hjnotU⟩
            · exact Or.inl ⟨ha, fun h => hjnotU (h ▸ ha)⟩
        rw [hset, ← e_insert_of_lt B v hlt]
        exact Submodule.mem_span_singleton_self _
      · -- `j = min U`: `ι(vⱼ)² = B(vⱼ,vⱼ)` collapses and `U ∆ {j} = U.erase j`.
        have hjU : j ∈ U := hjk ▸ U.min'_mem hU
        have hset : U ∆ {j} = U.erase j := by
          ext a
          simp only [Finset.mem_symmDiff, Finset.mem_singleton, Finset.mem_erase]
          constructor
          · rintro (⟨ha, hne⟩ | ⟨rfl, hn⟩)
            · exact ⟨hne, ha⟩
            · exact absurd hjU hn
          · rintro ⟨hne, ha⟩; exact Or.inl ⟨ha, hne⟩
        rw [hset, e_minPeel B v hU, ← hjk, ← mul_assoc, gen_sq, ← Algebra.smul_def]
        exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self _)
      · -- `j > min U =: k`: anticommute past `ι(v k)` and recurse on `U.erase k`.
        set k := U.min' hU with hkdef
        have hkU : k ∈ U := U.min'_mem hU
        have hjne : j ≠ k := ne_of_gt hjk
        obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp
          (ih (U.erase k) (Finset.erase_ssubset hkU))
        have hltW : ∀ i ∈ (U.erase k) ∆ {j}, k < i := by
          intro i hi
          simp only [Finset.mem_symmDiff, Finset.mem_erase, Finset.mem_singleton] at hi
          rcases hi with ⟨⟨hik, hiU⟩, _⟩ | ⟨rfl, _⟩
          · have hle : k ≤ i := U.min'_le i hiU
            exact lt_of_le_of_ne hle (Ne.symm hik)
          · exact hjk
        have hset : insert k ((U.erase k) ∆ {j}) = U ∆ {j} := by
          ext a
          simp only [Finset.mem_insert, Finset.mem_symmDiff, Finset.mem_erase,
            Finset.mem_singleton]
          by_cases hak : a = k <;> by_cases haj : a = j <;> by_cases haU : a ∈ U <;>
            simp_all
        rw [e_minPeel B v hU, ← hkdef, ← mul_assoc, gen_anticomm B v hv hjne, neg_mul,
          mul_assoc, ← hc, mul_smul_comm, ← e_insert_of_lt B v hltW, hset]
        exact Submodule.neg_mem _ (Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self _))

omit [FiniteDimensional ℂ V] in
/-- **Monomial × monomial reduction.** `e S · e T` is a scalar multiple of the monomial on
`S ∆ T`. Proved by strong induction on `S` (peel the minimum) using `gen_mul_mem`. -/
theorem e_mul_mem (hv : B.IsOrthoᵢ v) (S T : Finset (Fin N)) :
    e B v S * e B v T ∈ Submodule.span ℂ {e B v (S ∆ T)} := by
  induction S using Finset.strongInductionOn with
  | _ S ih =>
    rcases S.eq_empty_or_nonempty with rfl | hS
    · have h0 : (∅ : Finset (Fin N)) ∆ T = T := by ext a; simp [Finset.mem_symmDiff]
      rw [e_empty, one_mul, h0]
      exact Submodule.mem_span_singleton_self _
    · set k := S.min' hS with hkdef
      have hkS : k ∈ S := S.min'_mem hS
      obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp
        (ih (S.erase k) (Finset.erase_ssubset hkS))
      have hset : ((S.erase k) ∆ T) ∆ {k} = S ∆ T := by
        ext a
        simp only [Finset.mem_symmDiff, Finset.mem_erase, Finset.mem_singleton]
        by_cases hak : a = k <;> by_cases haS : a ∈ S <;> by_cases haT : a ∈ T <;>
          simp_all
      have hg := gen_mul_mem B v hv k ((S.erase k) ∆ T)
      rw [hset] at hg
      rw [e_minPeel B v hS, ← hkdef, mul_assoc, ← hc, mul_smul_comm]
      exact Submodule.smul_mem _ _ hg

end Monomial

section CliffBasis

variable {N : ℕ} (v : Module.Basis (Fin N) ℂ V)

open scoped symmDiff

omit [FiniteDimensional ℂ V] in
/-- The monomials `e S` span `Cl(V)`. Every element reduces to a linear combination of ordered
monomials: the span is a subalgebra (closed under multiplication by `e_mul_mem`) containing every
generator `ι(vᵢ) = e {i}`, hence all of `Cl(V)` by `CliffordAlgebra.induction`. -/
theorem span_e_eq_top (hv : B.IsOrthoᵢ v) :
    Submodule.span ℂ (Set.range (e B v)) = ⊤ := by
  set W := Submodule.span ℂ (Set.range (e B v)) with hWdef
  have hmem : ∀ S, e B v S ∈ W := fun S => Submodule.subset_span ⟨S, rfl⟩
  have h1 : (1 : CliffAlg B) ∈ W := e_empty B v ▸ hmem ∅
  have hbmul : ∀ S T, e B v S * e B v T ∈ W := fun S T =>
    Submodule.span_mono (by rintro _ rfl; exact ⟨S ∆ T, rfl⟩) (e_mul_mem B v hv S T)
  have hWmul : ∀ x ∈ W, ∀ y ∈ W, x * y ∈ W := by
    have hle : W * W ≤ W := by
      rw [hWdef, Submodule.span_mul_span, Submodule.span_le]
      rintro _ ⟨_, ⟨S, rfl⟩, _, ⟨T, rfl⟩, rfl⟩
      exact hbmul S T
    exact fun x hx y hy => hle (Submodule.mul_mem_mul hx hy)
  rw [eq_top_iff]
  rintro x -
  induction x using CliffordAlgebra.induction with
  | algebraMap r => rw [Algebra.algebraMap_eq_smul_one]; exact W.smul_mem r h1
  | ι w =>
      have hexp : CliffordAlgebra.ι (quadForm B) w = ∑ i, v.repr w i • gen B v i := by
        conv_lhs => rw [← v.sum_repr w]
        rw [map_sum]; simp only [map_smul, gen]
      rw [hexp]
      exact W.sum_mem (fun i _ => W.smul_mem _ (e_singleton B v i ▸ hmem {i}))
  | mul a b ha hb => exact hWmul a ha b hb
  | add a b ha hb => exact W.add_mem ha hb

omit [FiniteDimensional ℂ V] in
include v in
/-- `Cl(V)` has dimension `2^N` over `ℂ`: transport the exterior-algebra basis (indexed by
`Finset (Fin N)`) across `CliffordAlgebra.equivExterior`. -/
theorem finrank_cliffAlg : Module.finrank ℂ (CliffAlg B) = 2 ^ N := by
  haveI : Invertible (2 : ℂ) := invertibleOfNonzero two_ne_zero
  rw [(CliffordAlgebra.equivExterior (quadForm B)).finrank_eq,
    Module.finrank_eq_card_basis (Module.Basis.ExteriorAlgebra v),
    Fintype.card_finset, Fintype.card_fin]

/-- The `2^N` monomials `e S` form a basis of `Cl(V)` (spanning family of the right cardinality). -/
noncomputable def cliffBasis (hv : B.IsOrthoᵢ v) :
    Module.Basis (Finset (Fin N)) ℂ (CliffAlg B) :=
  basisOfTopLeSpanOfCardEqFinrank (e B v) (span_e_eq_top B v hv).ge
    (by rw [Fintype.card_finset, Fintype.card_fin, finrank_cliffAlg B v])

omit [FiniteDimensional ℂ V] in
@[simp] theorem cliffBasis_apply (hv : B.IsOrthoᵢ v) (S : Finset (Fin N)) :
    cliffBasis B v hv S = e B v S := by
  simp only [cliffBasis, coe_basisOfTopLeSpanOfCardEqFinrank]

end CliffBasis

section TraceForm

variable {N : ℕ} (v : Module.Basis (Fin N) ℂ V)

open scoped symmDiff

omit [FiniteDimensional ℂ V] in
/-- Left multiplication is `ℂ`-linear in the multiplier: `L_{c·z} = c·L_z`. -/
theorem mulLeft_smul (c : ℂ) (z : CliffAlg B) :
    LinearMap.mulLeft ℂ (c • z) = c • LinearMap.mulLeft ℂ z := by
  ext w; simp

omit [FiniteDimensional ℂ V] in
/-- **Trace of `L_{e R}`.** Left multiplication by the monomial `e R` permutes the monomial basis
`e T ↦ ± scalar · e_{R ∆ T}`, so it has a nonzero diagonal entry only when `R ∆ T = T`, i.e.
`R = ∅`. Hence `tr(L_{e R}) = 2^N` if `R = ∅` and `0` otherwise. -/
theorem tr_mulLeft_e (hv : B.IsOrthoᵢ v) (R : Finset (Fin N)) :
    LinearMap.trace ℂ (CliffAlg B) (LinearMap.mulLeft ℂ (e B v R))
      = if R = ∅ then (2 ^ N : ℂ) else 0 := by
  classical
  have htr : Matrix.trace (LinearMap.toMatrix (cliffBasis B v hv) (cliffBasis B v hv)
      (LinearMap.mulLeft ℂ (e B v R)))
      = ∑ T, (cliffBasis B v hv).repr (e B v R * e B v T) T := by
    simp only [Matrix.trace, Matrix.diag, LinearMap.toMatrix_apply, LinearMap.mulLeft_apply,
      cliffBasis_apply]
  rw [LinearMap.trace_eq_matrix_trace ℂ (cliffBasis B v hv), htr]
  by_cases hR : R = ∅
  · subst hR
    rw [if_pos rfl]
    have hone : ∀ T : Finset (Fin N),
        (cliffBasis B v hv).repr (e B v ∅ * e B v T) T = 1 := by
      intro T
      rw [e_empty, one_mul, ← cliffBasis_apply B v hv T, Module.Basis.repr_self_apply, if_pos rfl]
    rw [Finset.sum_congr rfl (fun T _ => hone T), Finset.sum_const, Finset.card_univ,
      Fintype.card_finset, Fintype.card_fin, nsmul_eq_mul, mul_one, Nat.cast_pow, Nat.cast_ofNat]
  · rw [if_neg hR]
    refine Finset.sum_eq_zero (fun T _ => ?_)
    obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp (e_mul_mem B v hv R T)
    rw [← hc, ← cliffBasis_apply B v hv (R ∆ T), map_smul, Finsupp.smul_apply,
      Module.Basis.repr_self_apply, if_neg, smul_zero]
    intro h
    exact hR (by rw [← Finset.bot_eq_empty]; exact symmDiff_eq_right.mp h)

omit [FiniteDimensional ℂ V] in
/-- **Off-diagonal trace form vanishes.** For `S ≠ T`, `tr(L_{e S · e T}) = 0`, because
`e S · e T` is a scalar multiple of `e_{S ∆ T}` with `S ∆ T ≠ ∅`. -/
theorem tr_mulLeft_e_mul_of_ne (hv : B.IsOrthoᵢ v) {S T : Finset (Fin N)} (hST : S ≠ T) :
    LinearMap.trace ℂ (CliffAlg B) (LinearMap.mulLeft ℂ (e B v S * e B v T)) = 0 := by
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp (e_mul_mem B v hv S T)
  rw [← hc, mulLeft_smul, map_smul, tr_mulLeft_e B v hv, if_neg, smul_zero]
  intro h
  exact hST (symmDiff_eq_bot.mp (Finset.bot_eq_empty ▸ h))

omit [FiniteDimensional ℂ V] in
/-- The diagonal trace form value `tr(L_{e T · e T})` is nonzero: `e T` is a unit, so `e T · e T`
is a unit, hence `tr(L_{e T · e T}) = c · 2^N` with `c ≠ 0`. -/
theorem tr_mulLeft_e_mul_self_ne_zero (hv : B.IsOrthoᵢ v) (hnd : B.Nondegenerate)
    (T : Finset (Fin N)) :
    LinearMap.trace ℂ (CliffAlg B) (LinearMap.mulLeft ℂ (e B v T * e B v T)) ≠ 0 := by
  haveI : Nontrivial (CliffAlg B) :=
    Module.nontrivial_of_finrank_pos (by rw [finrank_cliffAlg B v]; exact pow_pos (by norm_num) N)
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp (e_mul_mem B v hv T T)
  have hunit : IsUnit (e B v T * e B v T) :=
    (isUnit_e B v hv hnd T).mul (isUnit_e B v hv hnd T)
  have hcne : c ≠ 0 := by
    rintro rfl
    rw [zero_smul] at hc
    exact hunit.ne_zero hc.symm
  have hTT : T ∆ T = (∅ : Finset (Fin N)) := by rw [symmDiff_self, Finset.bot_eq_empty]
  rw [← hc, mulLeft_smul, map_smul, tr_mulLeft_e B v hv, if_pos hTT, smul_eq_mul]
  exact mul_ne_zero hcne (pow_ne_zero N two_ne_zero)

end TraceForm

/-- **Problem 3.9.5(i), semisimplicity.** If `B` is nondegenerate then `Cl(V)` is a
semisimple ring.

By Dickson's criterion (`isSemisimpleRing_of_traceForm_nondegenerate`) it suffices that the trace
form of `Cl(V)` is nondegenerate. That is the content of the spinor construction from the book: a
direct computation on the `2^{dim V}` monomial basis `∏_{i∈S} ι(bᵢ)` shows `tr(L_{e_S e_T})` is a
nonzero multiple of `∏` of the pairings `B` exactly when `S = T`, which is nondegenerate precisely
when `B` is. -/
theorem isSemisimpleRing_of_nondegenerate
    (hsymm : ∀ x y, B x y = B y x) (hnd : B.Nondegenerate) :
    IsSemisimpleRing (CliffAlg B) := by
  classical
  haveI : Invertible (2 : ℂ) := invertibleOfNonzero two_ne_zero
  -- Choose an orthogonal basis of `V` for `B`.
  obtain ⟨v, hv⟩ := LinearMap.BilinForm.exists_orthogonal_basis
    (LinearMap.BilinForm.isSymm_iff.mp ⟨hsymm⟩)
  apply isSemisimpleRing_of_traceForm_nondegenerate
  -- The trace form is nondegenerate: in the monomial basis it is diagonal with nonzero diagonal.
  intro x hx
  -- The linear functional `z ↦ tr(L_z)`.
  let τ : CliffAlg B →ₗ[ℂ] ℂ :=
    (LinearMap.trace ℂ (CliffAlg B)).comp (Algebra.lmul ℂ (CliffAlg B)).toLinearMap
  have hτ : ∀ z, τ z = LinearMap.trace ℂ (CliffAlg B) (LinearMap.mulLeft ℂ z) := fun _ => rfl
  -- Every basis coordinate of `x` vanishes.
  have hcoord : ∀ T, (cliffBasis B v hv).repr x T = 0 := by
    intro T
    have hexp : x = ∑ S, (cliffBasis B v hv).repr x S • e B v S := by
      conv_lhs => rw [← (cliffBasis B v hv).sum_repr x]
      simp only [cliffBasis_apply]
    have hsum : τ (x * e B v T)
        = (cliffBasis B v hv).repr x T • τ (e B v T * e B v T) := by
      conv_lhs => rw [hexp, Finset.sum_mul, map_sum]
      rw [Finset.sum_eq_single T]
      · rw [smul_mul_assoc, map_smul]
      · intro S _ hST
        rw [smul_mul_assoc, map_smul, hτ, tr_mulLeft_e_mul_of_ne B v hv hST, smul_zero]
      · intro hT; exact absurd (Finset.mem_univ T) hT
    have hzero : (cliffBasis B v hv).repr x T • τ (e B v T * e B v T) = 0 := by
      rw [← hsum, hτ]; exact hx (e B v T)
    have hne : τ (e B v T * e B v T) ≠ 0 := by
      rw [hτ]; exact tr_mulLeft_e_mul_self_ne_zero B v hv hnd T
    exact (smul_eq_zero.mp hzero).resolve_right hne
  -- Hence `x = 0`.
  apply (cliffBasis B v hv).repr.injective
  rw [map_zero]
  ext T
  rw [hcoord T, Finsupp.zero_apply]

/-!
### The center of `Cl(V)` in the even nondegenerate case

For an orthogonal basis `v`, left/right multiplication of a monomial `e S` by a generator `gen i`
differ only by a sign: `gen i * e S = (-1)^{|S \ {i}|} • (e S * gen i)`. Consequently, conjugation
by `gen i` scales each monomial `e S` by `(-1)^{|S \ {i}|}`, and a central element must have
vanishing coordinate on every monomial `e S` for which some generator gives sign `-1`. When
`dim V = N` is **even**, the only monomial fixed by *all* conjugations is `e ∅ = 1`, so the center
is `ℂ · 1`. (In the odd case the top monomial `e univ` survives, giving a `2`-dimensional center.)
-/

section CenterEven

variable {N : ℕ} (v : Module.Basis (Fin N) ℂ V)

open scoped symmDiff

omit [FiniteDimensional ℂ V] in
/-- If `i ∉ T`, the generator `gen i` anticommutes with each of the `|T|` generators making up
`e T`, so moving it across `e T` produces the sign `(-1)^{|T|}`. -/
theorem gen_comm_notMem (hv : B.IsOrthoᵢ v) {i : Fin N} :
    ∀ T : Finset (Fin N), i ∉ T →
      gen B v i * e B v T = (-1 : ℂ) ^ T.card • (e B v T * gen B v i) := by
  intro T
  induction T using Finset.strongInductionOn with
  | _ T ih =>
    intro hiT
    rcases T.eq_empty_or_nonempty with rfl | hT
    · simp
    · have hkT : T.min' hT ∈ T := T.min'_mem hT
      set k := T.min' hT with hk
      have hik : i ≠ k := fun h => hiT (h ▸ hkT)
      have hiT' : i ∉ T.erase k := fun h => hiT (Finset.mem_of_mem_erase h)
      have hcard : T.card = (T.erase k).card + 1 := by
        rw [Finset.card_erase_of_mem hkT, Nat.sub_add_cancel (Finset.card_pos.mpr hT)]
      have hpeel : e B v T = gen B v k * e B v (T.erase k) := by
        rw [e_minPeel B v hT, ← hk]
      calc gen B v i * e B v T
          = gen B v i * (gen B v k * e B v (T.erase k)) := by rw [hpeel]
        _ = (gen B v i * gen B v k) * e B v (T.erase k) := by rw [mul_assoc]
        _ = (-(gen B v k * gen B v i)) * e B v (T.erase k) := by rw [gen_anticomm B v hv hik]
        _ = -(gen B v k * (gen B v i * e B v (T.erase k))) := by rw [neg_mul, mul_assoc]
        _ = -(gen B v k * ((-1 : ℂ) ^ (T.erase k).card • (e B v (T.erase k) * gen B v i))) := by
              rw [ih (T.erase k) (Finset.erase_ssubset hkT) hiT']
        _ = (-1 : ℂ) ^ T.card • (gen B v k * (e B v (T.erase k) * gen B v i)) := by
              rw [mul_smul_comm, ← neg_smul, hcard, pow_succ, mul_neg_one]
        _ = (-1 : ℂ) ^ T.card • (e B v T * gen B v i) := by rw [hpeel, mul_assoc]

omit [FiniteDimensional ℂ V] in
/-- **Left/right commutation of a generator through a monomial.** For an orthogonal basis and a
nondegenerate form, `gen i * e S = (-1)^{|S \ {i}|} • (e S * gen i)`. The exponent `|S \ {i}|` is
`(S.erase i).card`; conjugation by `gen i` therefore fixes `e S` up to this sign. -/
theorem gen_conj (hv : B.IsOrthoᵢ v) (hnd : B.Nondegenerate) (i : Fin N) (S : Finset (Fin N)) :
    gen B v i * e B v S = (-1 : ℂ) ^ (S.erase i).card • (e B v S * gen B v i) := by
  by_cases hiS : i ∈ S
  · -- `i ∈ S`: put `T = S.erase i` (so `i ∉ T`, `T ∆ {i} = S`); then `e S = δ⁻¹ • (gen i * e T)`.
    set T := S.erase i with hT
    have hiT : i ∉ T := Finset.notMem_erase i S
    have hset : T ∆ ({i} : Finset (Fin N)) = S := by
      ext a
      simp only [hT, Finset.mem_symmDiff, Finset.mem_singleton, Finset.mem_erase]
      by_cases hai : a = i <;> simp [hai, hiS]
    obtain ⟨δ, hδ⟩ := Submodule.mem_span_singleton.mp (gen_mul_mem B v hv i T)
    rw [hset] at hδ
    -- `δ ≠ 0` because `gen i * e T` is a unit while `e S` is a unit (hence nonzero).
    haveI : Nontrivial (CliffAlg B) :=
      Module.nontrivial_of_finrank_pos (by rw [finrank_cliffAlg B v]; positivity)
    have hδne : δ ≠ 0 := by
      rintro rfl
      rw [zero_smul] at hδ
      exact ((isUnit_gen B v hv hnd i).mul (isUnit_e B v hv hnd T)).ne_zero hδ.symm
    have hSeq : e B v S = δ⁻¹ • (gen B v i * e B v T) := by
      rw [← hδ, smul_smul, inv_mul_cancel₀ hδne, one_smul]
    -- The sign `c := (-1)^{|T|}` for moving `gen i` past `e T` (`i ∉ T`), which squares to `1`.
    set c : ℂ := (-1 : ℂ) ^ T.card with hc
    have hcc : c * c = 1 := by rw [hc, ← pow_add, ← two_mul, pow_mul]; simp
    have hcomm : e B v T * gen B v i = c • (gen B v i * e B v T) := by
      rw [gen_comm_notMem B v hv T hiT, ← hc, smul_smul, hcc, one_smul]
    -- Both products are scalar multiples of `P := gen i * gen i * e T`, differing by the sign `c`.
    have hL : gen B v i * e B v S = δ⁻¹ • (gen B v i * gen B v i * e B v T) := by
      rw [hSeq, mul_smul_comm, ← mul_assoc]
    have hR : e B v S * gen B v i = (δ⁻¹ * c) • (gen B v i * gen B v i * e B v T) := by
      rw [hSeq, smul_mul_assoc, mul_assoc, hcomm, mul_smul_comm, ← mul_assoc, smul_smul]
    rw [hL, hR, smul_smul]
    congr 1
    rw [mul_left_comm, hcc, mul_one]
  · -- `i ∉ S`: `(S.erase i) = S`, and this is exactly `gen_comm_notMem`.
    rw [Finset.erase_eq_of_notMem hiS]
    exact gen_comm_notMem B v hv S hiS

omit [FiniteDimensional ℂ V] in
/-- An element commuting with every generator `gen i` is central: the generators together with the
scalars generate `Cl(V)`, so `CliffordAlgebra.induction` propagates commutation everywhere. -/
theorem central_of_commutes_gen {x : CliffAlg B}
    (h : ∀ i : Fin N, x * gen B v i = gen B v i * x) (y : CliffAlg B) :
    x * y = y * x := by
  induction y using CliffordAlgebra.induction with
  | algebraMap r => rw [Algebra.commutes]
  | ι w =>
      have hexp : CliffordAlgebra.ι (quadForm B) w = ∑ i, v.repr w i • gen B v i := by
        conv_lhs => rw [← v.sum_repr w]
        rw [map_sum]; simp only [map_smul, gen]
      rw [hexp, Finset.mul_sum, Finset.sum_mul]
      exact Finset.sum_congr rfl (fun i _ => by rw [mul_smul_comm, smul_mul_assoc, h i])
  | mul a b ha hb => rw [← mul_assoc, ha, mul_assoc, hb, ← mul_assoc]
  | add a b ha hb => rw [mul_add, add_mul, ha, hb]

omit [FiniteDimensional ℂ V] in
/-- **The center of `Cl(V)` is `ℂ · 1` when `dim V = N` is even.** Every central element `x`
commutes with all generators; expanding `x = ∑ c_S e_S` in the monomial basis and using
`gen_conj`, commutation with `gen i` forces `c_S ((-1)^{|S \ {i}|} - 1) = 0` for every `i`. For any
`S ≠ ∅` some index `i` makes `|S \ {i}|` odd (pick `i ∈ S` if `|S|` is even; pick `i ∉ S`, which
exists because `S ≠ univ` since `|S|` odd and `N` even, if `|S|` is odd), giving the factor `-2`
and hence `c_S = 0`. So `x = c_∅ • 1`. -/
theorem center_le_bot (hv : B.IsOrthoᵢ v) (hnd : B.Nondegenerate) (hN : Even N) :
    Subalgebra.center ℂ (CliffAlg B) ≤ ⊥ := by
  intro x hx
  have hcomm : ∀ i, gen B v i * x = x * gen B v i := fun i =>
    Subalgebra.mem_center_iff.mp hx (gen B v i)
  set c := (cliffBasis B v hv).repr x with hcdef
  have hxexp : x = ∑ S, c S • e B v S := by
    conv_lhs => rw [← (cliffBasis B v hv).sum_repr x]
    simp only [cliffBasis_apply, hcdef]
  -- Commutation with `gen i` forces `c S * ((-1)^{|S \ {i}|} - 1) = 0` for every `S`.
  have key : ∀ i : Fin N, ∀ S : Finset (Fin N),
      c S * ((-1 : ℂ) ^ (S.erase i).card - 1) = 0 := by
    intro i
    have hexpand : (∑ S, (c S * (-1 : ℂ) ^ (S.erase i).card) • (e B v S * gen B v i))
        = ∑ S, c S • (e B v S * gen B v i) := by
      have e1 : gen B v i * x
          = ∑ S, (c S * (-1 : ℂ) ^ (S.erase i).card) • (e B v S * gen B v i) := by
        rw [hxexp, Finset.mul_sum]
        exact Finset.sum_congr rfl (fun S _ => by
          rw [mul_smul_comm, gen_conj B v hv hnd i S, smul_smul])
      have e2 : x * gen B v i = ∑ S, c S • (e B v S * gen B v i) := by
        rw [hxexp, Finset.sum_mul]
        exact Finset.sum_congr rfl (fun S _ => by rw [smul_mul_assoc])
      rw [← e1, ← e2, hcomm i]
    have hsum0 : (∑ S, (c S * ((-1 : ℂ) ^ (S.erase i).card - 1)) • (e B v S * gen B v i)) = 0 := by
      rw [← sub_eq_zero.mpr hexpand, ← Finset.sum_sub_distrib]
      exact Finset.sum_congr rfl (fun S _ => by rw [mul_sub, mul_one, sub_smul])
    -- Right-multiply by the inverse of `gen i` to strip the trailing `gen i`.
    set w : CliffAlg B := (B (v i) (v i))⁻¹ • gen B v i with hwdef
    have hw : gen B v i * w = 1 := by
      rw [hwdef, mul_smul_comm, gen_sq, Algebra.smul_def, ← map_mul,
        inv_mul_cancel₀ (diag_ne_zero B v hv hnd i), map_one]
    have happly := congrArg (LinearMap.mulRight ℂ w) hsum0
    rw [map_zero, map_sum] at happly
    simp only [map_smul, LinearMap.mulRight_apply, mul_assoc, hw, mul_one] at happly
    -- `happly : ∑ S, (c S * ((-1)^{|S\{i}|} - 1)) • e B v S = 0`; conclude via basis independence.
    have hli := (cliffBasis B v hv).linearIndependent
    rw [Fintype.linearIndependent_iff] at hli
    exact hli (fun S => c S * ((-1 : ℂ) ^ (S.erase i).card - 1))
      (by simpa only [cliffBasis_apply] using happly)
  -- For `S ≠ ∅` pick `i` making `|S \ {i}|` odd, forcing `c S = 0`.
  have hcS : ∀ S : Finset (Fin N), S ≠ ∅ → c S = 0 := by
    intro S hS
    obtain ⟨i, hodd⟩ : ∃ i, Odd (S.erase i).card := by
      rcases Nat.even_or_odd S.card with hpar | hpar
      · obtain ⟨i, hi⟩ := Finset.nonempty_iff_ne_empty.mpr hS
        refine ⟨i, ?_⟩
        rw [Finset.card_erase_of_mem hi]
        obtain ⟨k, hk⟩ := hpar
        have hpos : 1 ≤ S.card := Finset.card_pos.mpr ⟨i, hi⟩
        exact ⟨k - 1, by omega⟩
      · have hne_univ : S ≠ Finset.univ := by
          intro h
          rw [h, Finset.card_univ, Fintype.card_fin] at hpar
          exact (Nat.not_odd_iff_even.mpr hN) hpar
        obtain ⟨i, hi⟩ : ∃ i, i ∉ S := by
          by_contra hcon
          exact hne_univ (Finset.eq_univ_iff_forall.mpr (by simpa using hcon))
        exact ⟨i, by rw [Finset.erase_eq_of_notMem hi]; exact hpar⟩
    have hval : (-1 : ℂ) ^ (S.erase i).card - 1 = -2 := by rw [hodd.neg_one_pow]; ring
    have hk := key i S
    rw [hval] at hk
    exact (mul_eq_zero.mp hk).resolve_right (by norm_num)
  -- Hence `x = c ∅ • 1 = algebraMap (c ∅) ∈ ⊥`.
  have hxval : x = c ∅ • (1 : CliffAlg B) := by
    rw [hxexp, Finset.sum_eq_single (∅ : Finset (Fin N))]
    · rw [e_empty]
    · exact fun S _ hS => by rw [hcS S hS, zero_smul]
    · exact fun h => absurd (Finset.mem_univ _) h
  rw [Algebra.mem_bot]
  exact ⟨c ∅, by rw [Algebra.algebraMap_eq_smul_one]; exact hxval.symm⟩

end CenterEven

section CenterOdd

variable {N : ℕ} (v : Module.Basis (Fin N) ℂ V)

open scoped symmDiff

omit [FiniteDimensional ℂ V] in
/-- **The volume element is central in the odd case.** When `N` is odd, `gen_conj` moves each
generator `gen i` across `e univ` with sign `(-1)^{|univ \ {i}|} = (-1)^{N-1} = 1`, so `e univ`
commutes with every generator and hence (by `central_of_commutes_gen`) with all of `Cl(V)`. -/
theorem eUniv_mem_center (hv : B.IsOrthoᵢ v) (hnd : B.Nondegenerate) (hN : Odd N) :
    e B v Finset.univ ∈ Subalgebra.center ℂ (CliffAlg B) := by
  rw [Subalgebra.mem_center_iff]
  intro y
  refine (central_of_commutes_gen B v (fun i => ?_) y).symm
  -- goal: `e univ * gen i = gen i * e univ`
  have hcard : (Finset.univ.erase i).card = N - 1 := by
    rw [Finset.card_erase_of_mem (Finset.mem_univ i), Finset.card_univ, Fintype.card_fin]
  have heven : Even (Finset.univ.erase i).card := by
    rw [hcard]; rcases hN with ⟨k, hk⟩; exact ⟨k, by omega⟩
  have hgc := gen_conj B v hv hnd i Finset.univ
  rw [heven.neg_one_pow, one_smul] at hgc
  exact hgc.symm

omit [FiniteDimensional ℂ V] in
/-- **The center of `Cl(V)` is `span{1, e univ}` when `dim V = N` is odd.** The coefficient
argument is the same as the even case: commutation with `gen i` forces
`c_S ((-1)^{|S \ {i}|} - 1) = 0` for every `i`, so a surviving `S` must have `|S \ {i}|` even for
all `i`. For `∅ ≠ S ≠ univ` some index makes it odd (pick `i ∈ S` if `|S|` is even, else `i ∉ S`,
which exists since `S ≠ univ`), forcing `c_S = 0`. Thus only `S = ∅` and `S = univ` survive. -/
theorem center_le_span_eUniv (hv : B.IsOrthoᵢ v) (hnd : B.Nondegenerate) :
    (Subalgebra.center ℂ (CliffAlg B)).toSubmodule ≤
      Submodule.span ℂ {e B v ∅, e B v Finset.univ} := by
  intro x hx
  have hxc : x ∈ Subalgebra.center ℂ (CliffAlg B) := hx
  have hcomm : ∀ i, gen B v i * x = x * gen B v i := fun i =>
    Subalgebra.mem_center_iff.mp hxc (gen B v i)
  set c := (cliffBasis B v hv).repr x with hcdef
  have hxexp : x = ∑ S, c S • e B v S := by
    conv_lhs => rw [← (cliffBasis B v hv).sum_repr x]
    simp only [cliffBasis_apply, hcdef]
  -- Commutation with `gen i` forces `c S * ((-1)^{|S \ {i}|} - 1) = 0` for every `S` (parity-free).
  have key : ∀ i : Fin N, ∀ S : Finset (Fin N),
      c S * ((-1 : ℂ) ^ (S.erase i).card - 1) = 0 := by
    intro i
    have hexpand : (∑ S, (c S * (-1 : ℂ) ^ (S.erase i).card) • (e B v S * gen B v i))
        = ∑ S, c S • (e B v S * gen B v i) := by
      have e1 : gen B v i * x
          = ∑ S, (c S * (-1 : ℂ) ^ (S.erase i).card) • (e B v S * gen B v i) := by
        rw [hxexp, Finset.mul_sum]
        exact Finset.sum_congr rfl (fun S _ => by
          rw [mul_smul_comm, gen_conj B v hv hnd i S, smul_smul])
      have e2 : x * gen B v i = ∑ S, c S • (e B v S * gen B v i) := by
        rw [hxexp, Finset.sum_mul]
        exact Finset.sum_congr rfl (fun S _ => by rw [smul_mul_assoc])
      rw [← e1, ← e2, hcomm i]
    have hsum0 : (∑ S, (c S * ((-1 : ℂ) ^ (S.erase i).card - 1)) • (e B v S * gen B v i)) = 0 := by
      rw [← sub_eq_zero.mpr hexpand, ← Finset.sum_sub_distrib]
      exact Finset.sum_congr rfl (fun S _ => by rw [mul_sub, mul_one, sub_smul])
    set w : CliffAlg B := (B (v i) (v i))⁻¹ • gen B v i with hwdef
    have hw : gen B v i * w = 1 := by
      rw [hwdef, mul_smul_comm, gen_sq, Algebra.smul_def, ← map_mul,
        inv_mul_cancel₀ (diag_ne_zero B v hv hnd i), map_one]
    have happly := congrArg (LinearMap.mulRight ℂ w) hsum0
    rw [map_zero, map_sum] at happly
    simp only [map_smul, LinearMap.mulRight_apply, mul_assoc, hw, mul_one] at happly
    have hli := (cliffBasis B v hv).linearIndependent
    rw [Fintype.linearIndependent_iff] at hli
    exact hli (fun S => c S * ((-1 : ℂ) ^ (S.erase i).card - 1))
      (by simpa only [cliffBasis_apply] using happly)
  -- For `∅ ≠ S ≠ univ` pick `i` making `|S \ {i}|` odd, forcing `c S = 0`.
  have hcS : ∀ S : Finset (Fin N), S ≠ ∅ → S ≠ Finset.univ → c S = 0 := by
    intro S hS hSu
    obtain ⟨i, hodd⟩ : ∃ i, Odd (S.erase i).card := by
      rcases Nat.even_or_odd S.card with hpar | hpar
      · obtain ⟨i, hi⟩ := Finset.nonempty_iff_ne_empty.mpr hS
        refine ⟨i, ?_⟩
        rw [Finset.card_erase_of_mem hi]
        obtain ⟨k, hk⟩ := hpar
        have hpos : 1 ≤ S.card := Finset.card_pos.mpr ⟨i, hi⟩
        exact ⟨k - 1, by omega⟩
      · obtain ⟨i, hi⟩ : ∃ i, i ∉ S := by
          by_contra hcon
          exact hSu (Finset.eq_univ_iff_forall.mpr (by simpa using hcon))
        exact ⟨i, by rw [Finset.erase_eq_of_notMem hi]; exact hpar⟩
    have hval : (-1 : ℂ) ^ (S.erase i).card - 1 = -2 := by rw [hodd.neg_one_pow]; ring
    have hk := key i S
    rw [hval] at hk
    exact (mul_eq_zero.mp hk).resolve_right (by norm_num)
  -- Hence `x` is a combination of `e ∅` and `e univ`.
  rw [hxexp]
  refine Submodule.sum_mem _ (fun S _ => ?_)
  by_cases hS : S = ∅
  · exact hS ▸ Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_insert _ _))
  by_cases hSu : S = Finset.univ
  · exact hSu ▸ Submodule.smul_mem _ _
      (Submodule.subset_span (Set.mem_insert_of_mem _ rfl))
  · rw [hcS S hS hSu, zero_smul]; exact Submodule.zero_mem _

omit [FiniteDimensional ℂ V] in
/-- The two monomials `e ∅ = 1` and `e univ` are linearly independent (distinct basis vectors),
so they form a basis of the center, which therefore has dimension `2` when `N` is odd. -/
theorem finrank_center_odd (hv : B.IsOrthoᵢ v) (hnd : B.Nondegenerate) (hN : Odd N) :
    Module.finrank ℂ (Subalgebra.center ℂ (CliffAlg B)) = 2 := by
  have hne : (∅ : Finset (Fin N)) ≠ Finset.univ := by
    intro h
    have hc : (Finset.univ : Finset (Fin N)).card = 0 := by rw [← h]; rfl
    rw [Finset.card_univ, Fintype.card_fin] at hc
    rcases hN with ⟨k, hk⟩; omega
  set idx : Fin 2 → Finset (Fin N) := ![∅, Finset.univ] with hidx
  have hidxinj : Function.Injective idx := by
    intro a b hab
    fin_cases a <;> fin_cases b <;> simp_all
  set w : Fin 2 → CliffAlg B := fun i => e B v (idx i) with hwdef
  have hwli : LinearIndependent ℂ w := by
    have hb := ((cliffBasis B v hv).linearIndependent).comp idx hidxinj
    have hfun : w = ⇑(cliffBasis B v hv) ∘ idx := by
      funext i; simp [hwdef, cliffBasis_apply]
    rw [hfun]; exact hb
  have hrange : Set.range w = {e B v ∅, e B v Finset.univ} := by
    ext z
    simp only [Set.mem_range, Set.mem_insert_iff, Set.mem_singleton_iff]
    constructor
    · rintro ⟨i, rfl⟩; fin_cases i <;> simp [hwdef, hidx]
    · rintro (rfl | rfl)
      · exact ⟨0, by simp [hwdef, hidx]⟩
      · exact ⟨1, by simp [hwdef, hidx]⟩
  -- span of `w` is the center, so its dimension is `card (Fin 2) = 2`.
  have hspan : Submodule.span ℂ (Set.range w) = (Subalgebra.center ℂ (CliffAlg B)).toSubmodule := by
    apply le_antisymm
    · rw [hrange, Submodule.span_le]
      rintro z (rfl | rfl)
      · rw [e_empty]; exact Subalgebra.one_mem _
      · exact eUniv_mem_center B v hv hnd hN
    · rw [hrange]; exact center_le_span_eUniv B v hv hnd
  have hcard : Module.finrank ℂ (Submodule.span ℂ (Set.range w)) = 2 := by
    rw [finrank_span_eq_card hwli, Fintype.card_fin]
  rw [← Subalgebra.finrank_toSubmodule, ← hspan, hcard]

end CenterOdd

section GradeInvolution

variable {N : ℕ} (v : Module.Basis (Fin N) ℂ V)

open scoped symmDiff

omit [FiniteDimensional ℂ V] in
/-- **The grade involution on monomials.** The main involution `involute` (which sends each
generator `ι x` to `-ι x`) scales the monomial `e S` by `(-1)^{|S|}`, since `e S` is a product of
`|S|` generators. Proved by peeling the minimum. -/
theorem involute_e (S : Finset (Fin N)) :
    CliffordAlgebra.involute (e B v S) = (-1 : ℂ) ^ S.card • e B v S := by
  induction S using Finset.strongInductionOn with
  | _ S ih =>
    rcases S.eq_empty_or_nonempty with rfl | hS
    · simp
    · set k := S.min' hS with hkdef
      have hkS : k ∈ S := S.min'_mem hS
      have hpeel : e B v S = gen B v k * e B v (S.erase k) := by rw [e_minPeel B v hS, ← hkdef]
      have hcard : S.card = (S.erase k).card + 1 := by
        rw [Finset.card_erase_of_mem hkS, Nat.sub_add_cancel (Finset.card_pos.mpr hS)]
      have hgk : CliffordAlgebra.involute (gen B v k) = - gen B v k := by
        rw [gen]; exact CliffordAlgebra.involute_ι _
      rw [hpeel, map_mul, hgk, ih (S.erase k) (Finset.erase_ssubset hkS),
        neg_mul, mul_smul_comm, ← neg_smul, ← hpeel, hcard, pow_succ]
      congr 1
      ring

omit [FiniteDimensional ℂ V] in
/-- **The volume element squares to a nonzero scalar.** `e univ · e univ` lies in the span of
`e (univ ∆ univ) = e ∅ = 1`, and it is a unit (product of units), so the scalar is nonzero. -/
theorem exists_eUniv_sq (hv : B.IsOrthoᵢ v) (hnd : B.Nondegenerate) :
    ∃ μ : ℂ, μ ≠ 0 ∧ e B v Finset.univ * e B v Finset.univ = μ • (1 : CliffAlg B) := by
  have hmem := e_mul_mem B v hv Finset.univ Finset.univ
  have hset : (Finset.univ : Finset (Fin N)) ∆ Finset.univ = ∅ := by
    ext a; simp
  rw [hset, e_empty] at hmem
  obtain ⟨μ, hμ⟩ := Submodule.mem_span_singleton.mp hmem
  refine ⟨μ, ?_, hμ.symm⟩
  intro hμ0
  haveI : Nontrivial (CliffAlg B) :=
    Module.nontrivial_of_finrank_pos (by rw [finrank_cliffAlg B v]; positivity)
  have hunit : IsUnit (e B v Finset.univ * e B v Finset.univ) :=
    (isUnit_e B v hv hnd Finset.univ).mul (isUnit_e B v hv hnd Finset.univ)
  rw [← hμ, hμ0, zero_smul] at hunit
  exact (not_isUnit_zero) hunit

end GradeInvolution

set_option maxHeartbeats 400000 in
-- The proof threads a Wedderburn–Artin decomposition, a linear-independence dimension bound, and a
-- `Fin 1` product collapse through several large algebra isomorphisms, so it needs a higher limit.
/-- **Problem 3.9.5(i), even case.** If `B` is nondegenerate and `dim V = 2n`, then
`Cl(V)` is a matrix algebra: it is isomorphic to `End(S)` for a `2ⁿ`-dimensional space
`S`, the unique (spinor) irreducible representation. -/
theorem even_isMatrixAlgebra
    (hsymm : ∀ x y, B x y = B y x) (hnd : B.Nondegenerate)
    (n : ℕ) (hdim : Module.finrank ℂ V = 2 * n) :
    ∃ (S : Type) (_ : AddCommGroup S) (_ : Module ℂ S),
      Module.finrank ℂ S = 2 ^ n ∧ Nonempty (CliffAlg B ≃ₐ[ℂ] Module.End ℂ S) := by
  classical
  haveI : Invertible (2 : ℂ) := invertibleOfNonzero two_ne_zero
  -- Orthogonal basis of `V`; its size is `N = dim V = 2n`, which is even.
  obtain ⟨v, hv⟩ := LinearMap.BilinForm.exists_orthogonal_basis
    (LinearMap.BilinForm.isSymm_iff.mp ⟨hsymm⟩)
  have hNeven : Even (Module.finrank ℂ V) := ⟨n, by rw [hdim]; ring⟩
  -- `Cl(V)` is a finite-dimensional semisimple ℂ-algebra with `1`-dimensional center.
  haveI hss : IsSemisimpleRing (CliffAlg B) := isSemisimpleRing_of_nondegenerate B hsymm hnd
  have hcent : Subalgebra.center ℂ (CliffAlg B) = ⊥ :=
    le_antisymm (center_le_bot B v hv hnd hNeven) bot_le
  have hcf : Module.finrank ℂ (Subalgebra.center ℂ (CliffAlg B)) = 1 := by
    rw [hcent]; exact Subalgebra.finrank_bot
  haveI : Nontrivial (CliffAlg B) :=
    Module.nontrivial_of_finrank_pos (by rw [finrank_cliffAlg B v]; positivity)
  -- Wedderburn–Artin over `ℂ`: `Cl(V) ≃ₐ ∏ᵢ Mₐᵢ(ℂ)`.
  obtain ⟨m, d, hd, ⟨eiso⟩⟩ :=
    IsSemisimpleRing.exists_algEquiv_pi_matrix_of_isAlgClosed ℂ (CliffAlg B)
  haveI hmatnt : ∀ i : Fin m, Nontrivial (Matrix (Fin (d i)) (Fin (d i)) ℂ) := by
    intro i
    haveI := hd i
    haveI : Nonempty (Fin (d i)) := ⟨⟨0, Nat.pos_of_ne_zero (NeZero.ne _)⟩⟩
    infer_instance
  -- The `m` "coordinate units" `Pi.single i 1` are central and linearly independent, so `m ≤ 1`.
  set P := (Π i : Fin m, Matrix (Fin (d i)) (Fin (d i)) ℂ) with hPdef
  have hsingle_cent : ∀ i : Fin m,
      (Pi.single i 1 : P) ∈ Subalgebra.center ℂ P := by
    intro i
    rw [Subalgebra.mem_center_iff]
    intro b
    funext j
    simp only [Pi.mul_apply]
    rcases eq_or_ne j i with rfl | hji
    · rw [Pi.single_eq_same, mul_one, one_mul]
    · rw [Pi.single_eq_of_ne hji, mul_zero, zero_mul]
  let g : Fin m → CliffAlg B := fun i => eiso.symm (Pi.single i 1)
  have hg_cent : ∀ i, g i ∈ Subalgebra.center ℂ (CliffAlg B) := by
    intro i
    rw [Subalgebra.mem_center_iff]
    intro y
    have hs := Subalgebra.mem_center_iff.mp (hsingle_cent i) (eiso y)
    calc y * g i = eiso.symm (eiso y) * eiso.symm (Pi.single i 1) := by
            rw [AlgEquiv.symm_apply_apply]
      _ = eiso.symm (eiso y * Pi.single i 1) := by rw [← map_mul]
      _ = eiso.symm (Pi.single i 1 * eiso y) := by rw [hs]
      _ = eiso.symm (Pi.single i 1) * eiso.symm (eiso y) := by rw [map_mul]
      _ = g i * y := by rw [AlgEquiv.symm_apply_apply]
  have hbase : LinearIndependent ℂ (fun i : Fin m => (Pi.single i 1 : P)) := by
    rw [Fintype.linearIndependent_iff]
    intro a ha j
    have hj := congrFun ha j
    rw [Finset.sum_apply, Pi.zero_apply, Finset.sum_eq_single j] at hj
    · rw [Pi.smul_apply, Pi.single_eq_same] at hj
      exact (smul_eq_zero.mp hj).resolve_right one_ne_zero
    · intro b _ hbj
      rw [Pi.smul_apply, Pi.single_eq_of_ne (Ne.symm hbj), smul_zero]
    · intro h; exact absurd (Finset.mem_univ j) h
  have hg_li : LinearIndependent ℂ g :=
    hbase.map' eiso.symm.toLinearMap (LinearMap.ker_eq_bot.mpr eiso.symm.injective)
  -- The span of the `g i` lies in the center, so `m = finrank (span g) ≤ finrank center = 1`.
  have hspan_le : Submodule.span ℂ (Set.range g) ≤
      (Subalgebra.center ℂ (CliffAlg B)).toSubmodule := by
    rw [Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    exact hg_cent i
  have hmle : m ≤ 1 := by
    have h1 : Module.finrank ℂ (Submodule.span ℂ (Set.range g)) = m := by
      rw [finrank_span_eq_card hg_li, Fintype.card_fin]
    calc m = Module.finrank ℂ (Submodule.span ℂ (Set.range g)) := h1.symm
      _ ≤ Module.finrank ℂ (Subalgebra.center ℂ (CliffAlg B)).toSubmodule :=
          Submodule.finrank_mono hspan_le
      _ = 1 := hcf
  -- `m ≥ 1` since the empty product would make `Cl(V)` a subsingleton.
  have hm : m = 1 := by
    rcases Nat.eq_zero_or_pos m with h0 | hpos
    · exfalso
      subst h0
      haveI : Subsingleton P := by rw [hPdef]; infer_instance
      haveI : Subsingleton (CliffAlg B) := eiso.injective.subsingleton
      exact false_of_nontrivial_of_subsingleton (CliffAlg B)
    · omega
  subst hm
  -- With one factor, `Cl(V) ≃ₐ M_{d 0}(ℂ) ≃ₐ End ℂ (Fin (d 0) → ℂ)`.
  set k := d default with hkdef
  let piU : P ≃ₐ[ℂ] Matrix (Fin k) (Fin k) ℂ :=
    AlgEquiv.ofRingEquiv (f := RingEquiv.piUnique fun i : Fin 1 =>
      Matrix (Fin (d i)) (Fin (d i)) ℂ) (fun r => rfl)
  let mEnd : Matrix (Fin k) (Fin k) ℂ ≃ₐ[ℂ] Module.End ℂ (Fin k → ℂ) :=
    LinearMap.toMatrixAlgEquiv'.symm
  refine ⟨Fin k → ℂ, inferInstance, inferInstance, ?_,
    ⟨eiso.trans (piU.trans mEnd)⟩⟩
  -- Dimension count: `(dim S)^2 = dim End(S) = dim Cl(V) = 2^{2n}`, so `dim S = 2^n`.
  have hfr_iso : Module.finrank ℂ (CliffAlg B) = Module.finrank ℂ (Module.End ℂ (Fin k → ℂ)) :=
    (eiso.trans (piU.trans mEnd)).toLinearEquiv.finrank_eq
  have hfrS : Module.finrank ℂ (Fin k → ℂ) = k := by simp
  have hsq : k ^ 2 = (2 ^ n) ^ 2 := by
    have h1 : Module.finrank ℂ (Module.End ℂ (Fin k → ℂ)) = k ^ 2 := by
      rw [Module.finrank_linearMap, hfrS, sq]
    have h2 : Module.finrank ℂ (CliffAlg B) = (2 ^ n) ^ 2 := by
      rw [finrank_cliffAlg B v, hdim, ← pow_mul, mul_comm]
    rw [← h1, ← hfr_iso, h2]
  have hk : k = 2 ^ n := Nat.pow_left_injective (by norm_num) hsq
  rw [hfrS, hk]

set_option maxHeartbeats 400000 in
/-- **Two Wedderburn factors in the odd case.** If `B` is nondegenerate and `dim V = 2n+1`, then
`Cl(V) ≃ₐ ∏_{i : Fin 2} M_{dᵢ}(ℂ)` with each `dᵢ > 0`. The count `2` is exactly the dimension of the
center (`finrank_center_odd`): the `m` coordinate central units span the center, so `m = 2`. -/
theorem odd_exists_pi_matrix
    (hsymm : ∀ x y, B x y = B y x) (hnd : B.Nondegenerate)
    (n : ℕ) (hdim : Module.finrank ℂ V = 2 * n + 1) :
    ∃ (d : Fin 2 → ℕ), (∀ i, 0 < d i) ∧
      Nonempty (CliffAlg B ≃ₐ[ℂ] (Π i : Fin 2, Matrix (Fin (d i)) (Fin (d i)) ℂ)) := by
  classical
  haveI : Invertible (2 : ℂ) := invertibleOfNonzero two_ne_zero
  obtain ⟨v, hv⟩ := LinearMap.BilinForm.exists_orthogonal_basis
    (LinearMap.BilinForm.isSymm_iff.mp ⟨hsymm⟩)
  have hNodd : Odd (Module.finrank ℂ V) := ⟨n, by rw [hdim]⟩
  haveI hss : IsSemisimpleRing (CliffAlg B) := isSemisimpleRing_of_nondegenerate B hsymm hnd
  haveI : Nontrivial (CliffAlg B) :=
    Module.nontrivial_of_finrank_pos (by rw [finrank_cliffAlg B v]; positivity)
  -- Wedderburn–Artin over `ℂ`: `Cl(V) ≃ₐ ∏ᵢ Mₐᵢ(ℂ)`.
  obtain ⟨m, d, hd, ⟨eiso⟩⟩ :=
    IsSemisimpleRing.exists_algEquiv_pi_matrix_of_isAlgClosed ℂ (CliffAlg B)
  set P := (Π i : Fin m, Matrix (Fin (d i)) (Fin (d i)) ℂ) with hPdef
  -- The `m` "coordinate units" `Pi.single i 1` are central and linearly independent.
  have hsingle_cent : ∀ i : Fin m, (Pi.single i 1 : P) ∈ Subalgebra.center ℂ P := by
    intro i
    rw [Subalgebra.mem_center_iff]
    intro b
    funext j
    simp only [Pi.mul_apply]
    rcases eq_or_ne j i with rfl | hji
    · rw [Pi.single_eq_same, mul_one, one_mul]
    · rw [Pi.single_eq_of_ne hji, mul_zero, zero_mul]
  let g : Fin m → CliffAlg B := fun i => eiso.symm (Pi.single i 1)
  have hg_cent : ∀ i, g i ∈ Subalgebra.center ℂ (CliffAlg B) := by
    intro i
    rw [Subalgebra.mem_center_iff]
    intro y
    have hs := Subalgebra.mem_center_iff.mp (hsingle_cent i) (eiso y)
    calc y * g i = eiso.symm (eiso y) * eiso.symm (Pi.single i 1) := by
            rw [AlgEquiv.symm_apply_apply]
      _ = eiso.symm (eiso y * Pi.single i 1) := by rw [← map_mul]
      _ = eiso.symm (Pi.single i 1 * eiso y) := by rw [hs]
      _ = eiso.symm (Pi.single i 1) * eiso.symm (eiso y) := by rw [map_mul]
      _ = g i * y := by rw [AlgEquiv.symm_apply_apply]
  have hbase : LinearIndependent ℂ (fun i : Fin m => (Pi.single i 1 : P)) := by
    rw [Fintype.linearIndependent_iff]
    intro a ha j
    have hj := congrFun ha j
    rw [Finset.sum_apply, Pi.zero_apply, Finset.sum_eq_single j] at hj
    · rw [Pi.smul_apply, Pi.single_eq_same] at hj
      exact (smul_eq_zero.mp hj).resolve_right one_ne_zero
    · intro b _ hbj
      rw [Pi.smul_apply, Pi.single_eq_of_ne (Ne.symm hbj), smul_zero]
    · intro h; exact absurd (Finset.mem_univ j) h
  have hg_li : LinearIndependent ℂ g :=
    hbase.map' eiso.symm.toLinearMap (LinearMap.ker_eq_bot.mpr eiso.symm.injective)
  -- The span of the `g i` lies in the center.
  have hspan_le : Submodule.span ℂ (Set.range g) ≤
      (Subalgebra.center ℂ (CliffAlg B)).toSubmodule := by
    rw [Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    exact hg_cent i
  -- Conversely every central element is a combination of the `g i`: transport to `P`, where a
  -- central element is a tuple of scalars (each matrix factor is central over `ℂ`).
  have hg_span_center : (Subalgebra.center ℂ (CliffAlg B)).toSubmodule ≤
      Submodule.span ℂ (Set.range g) := by
    intro x hx
    have hxc : x ∈ Subalgebra.center ℂ (CliffAlg B) := hx
    have hpc : eiso x ∈ Subalgebra.center ℂ P := by
      rw [Subalgebra.mem_center_iff]
      intro b
      have hs := Subalgebra.mem_center_iff.mp hxc (eiso.symm b)
      calc b * eiso x = eiso (eiso.symm b) * eiso x := by rw [AlgEquiv.apply_symm_apply]
        _ = eiso (eiso.symm b * x) := by rw [← map_mul]
        _ = eiso (x * eiso.symm b) := by rw [hs]
        _ = eiso x * eiso (eiso.symm b) := by rw [map_mul]
        _ = eiso x * b := by rw [AlgEquiv.apply_symm_apply]
    have hscalar : ∀ i : Fin m, ∃ c : ℂ, algebraMap ℂ (Matrix (Fin (d i)) (Fin (d i)) ℂ) c
        = (eiso x) i := by
      intro i
      have hpc' : eiso x ∈
          Subalgebra.center ℂ (Π j : Fin m, Matrix (Fin (d j)) (Fin (d j)) ℂ) := hpc
      rw [Subalgebra.center_pi] at hpc'
      have hcoord : (eiso x) i ∈ Subalgebra.center ℂ (Matrix (Fin (d i)) (Fin (d i)) ℂ) :=
        Subalgebra.mem_pi.mp hpc' i (Set.mem_univ i)
      have hbot : (eiso x) i ∈ (⊥ : Subalgebra ℂ (Matrix (Fin (d i)) (Fin (d i)) ℂ)) :=
        Algebra.IsCentral.out hcoord
      exact Algebra.mem_bot.mp hbot
    choose c hc using hscalar
    have hsum : eiso x = ∑ i, c i • (Pi.single i 1 : P) := by
      conv_lhs => rw [← Finset.univ_sum_single (eiso x)]
      refine Finset.sum_congr rfl (fun i _ => ?_)
      rw [← hc i, Algebra.algebraMap_eq_smul_one, Pi.single_smul]
    have hx_eq : x = ∑ i, c i • g i := by
      have h2 := congrArg eiso.symm hsum
      rw [AlgEquiv.symm_apply_apply, map_sum] at h2
      simp only [map_smul] at h2
      exact h2
    rw [hx_eq]
    exact Submodule.sum_mem _
      (fun i _ => Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩))
  -- So the span equals the center, whose dimension is `2`; hence `m = 2`.
  have hspan_eq : Submodule.span ℂ (Set.range g)
      = (Subalgebra.center ℂ (CliffAlg B)).toSubmodule :=
    le_antisymm hspan_le hg_span_center
  have hcenter2 : Module.finrank ℂ (Submodule.span ℂ (Set.range g)) = 2 := by
    rw [hspan_eq]; exact finrank_center_odd B v hv hnd hNodd
  have hm : m = 2 := by
    have hfs := finrank_span_eq_card hg_li
    rw [hcenter2, Fintype.card_fin] at hfs
    exact hfs.symm
  subst hm
  exact ⟨d, fun i => by haveI := hd i; exact Nat.pos_of_ne_zero (NeZero.ne _), ⟨eiso⟩⟩

set_option maxHeartbeats 1600000 in
-- The proof threads the two-factor Wedderburn decomposition, a grade-involution transport
-- proving `d₀ = d₁`, and several large algebra isomorphisms, so it needs a higher limit.
/-- **Problem 3.9.5(i), odd case.** If `B` is nondegenerate and `dim V = 2n+1`, then
`Cl(V)` is a direct sum of two matrix algebras: `End(S) × End(S)` with `dim S = 2ⁿ`. The
two factors are the two non-isomorphic irreducible representations `S₊, S₋`. -/
theorem odd_isSumMatrixAlgebra
    (hsymm : ∀ x y, B x y = B y x) (hnd : B.Nondegenerate)
    (n : ℕ) (hdim : Module.finrank ℂ V = 2 * n + 1) :
    ∃ (S : Type) (_ : AddCommGroup S) (_ : Module ℂ S),
      Module.finrank ℂ S = 2 ^ n ∧
      Nonempty (CliffAlg B ≃ₐ[ℂ] (Module.End ℂ S × Module.End ℂ S)) := by
  classical
  haveI : Invertible (2 : ℂ) := invertibleOfNonzero two_ne_zero
  -- Orthogonal basis of `V`, indexed by `Fin (finrank ℂ V)`.
  obtain ⟨v, hv⟩ := LinearMap.BilinForm.exists_orthogonal_basis
    (LinearMap.BilinForm.isSymm_iff.mp ⟨hsymm⟩)
  have hNodd : Odd (Module.finrank ℂ V) := ⟨n, by rw [hdim]⟩
  haveI : Nontrivial (CliffAlg B) :=
    Module.nontrivial_of_finrank_pos (by rw [finrank_cliffAlg B v]; positivity)
  -- Two-factor Wedderburn decomposition `Cl(V) ≃ₐ P = ∏ᵢ M_{dᵢ}(ℂ)`.
  obtain ⟨d, hdpos, ⟨eiso⟩⟩ := odd_exists_pi_matrix B hsymm hnd n hdim
  set P := (Π i : Fin 2, Matrix (Fin (d i)) (Fin (d i)) ℂ) with hPdef
  haveI hmatnt : ∀ i : Fin 2, Nontrivial (Matrix (Fin (d i)) (Fin (d i)) ℂ) := by
    intro i
    haveI : Nonempty (Fin (d i)) := ⟨⟨0, hdpos i⟩⟩
    infer_instance
  -- The two complementary central idempotents `e0, e1 ∈ P` and their preimages `g0, g1`.
  set e0 : P := Pi.single 0 1 with he0
  set e1 : P := Pi.single 1 1 with he1
  set g0 : CliffAlg B := eiso.symm e0 with hg0
  set g1 : CliffAlg B := eiso.symm e1 with hg1
  -- Basic algebra of `e0, e1` in `P`.
  have he01 : e0 + e1 = 1 := by
    funext i; fin_cases i <;> simp +zetaDelta [Pi.add_apply]
  have he0e1 : e0 * e1 = 0 := by
    funext i; fin_cases i <;> simp +zetaDelta [Pi.mul_apply]
  have he0sq : e0 * e0 = e0 := by
    funext i; fin_cases i <;> simp +zetaDelta [Pi.mul_apply]
  have he0ne0 : e0 ≠ 0 := by
    intro h; have h0 := congrFun h 0; simp +zetaDelta at h0
  have he0ne1 : e0 ≠ 1 := by
    intro h; have h1 := congrFun h 1; simp +zetaDelta at h1
  have he0cent : e0 ∈ Subalgebra.center ℂ P := by
    rw [Subalgebra.mem_center_iff]
    intro b; funext j; fin_cases j <;> simp +zetaDelta [Pi.mul_apply]
  -- Transport to `g0, g1` in `Cl(V)`.
  have hg01 : g0 + g1 = 1 := by rw [hg0, hg1, ← map_add, he01, map_one]
  have hg0g1 : g0 * g1 = 0 := by rw [hg0, hg1, ← map_mul, he0e1, map_zero]
  have hg0sq : g0 * g0 = g0 := by rw [hg0, ← map_mul, he0sq]
  have hg0ne0 : g0 ≠ 0 := by
    intro h; apply he0ne0; rw [← AlgEquiv.apply_symm_apply eiso e0, ← hg0, h, map_zero]
  have hg0ne1 : g0 ≠ 1 := by
    intro h; apply he0ne1; rw [← AlgEquiv.apply_symm_apply eiso e0, ← hg0, h, map_one]
  have hg0cent : g0 ∈ Subalgebra.center ℂ (CliffAlg B) := by
    rw [Subalgebra.mem_center_iff]
    intro y
    have hs := Subalgebra.mem_center_iff.mp he0cent (eiso y)
    have h1 : g0 * y = eiso.symm (e0 * eiso y) := by
      rw [hg0, map_mul, AlgEquiv.symm_apply_apply]
    have h2 : y * g0 = eiso.symm (eiso y * e0) := by
      rw [hg0, map_mul, AlgEquiv.symm_apply_apply]
    rw [h1, h2, hs]
  -- `g0` is central so lies in `span{1, e univ}`; write `g0 = a•1 + b•(e univ)`.
  obtain ⟨a, b, hab⟩ := Submodule.mem_span_pair.mp (center_le_span_eUniv B v hv hnd hg0cent)
  rw [e_empty] at hab
  obtain ⟨μ, hμ0, hμ⟩ := exists_eUniv_sq B v hv hnd
  -- `{1, e univ}` is linearly independent.
  have hne : (∅ : Finset (Fin (Module.finrank ℂ V))) ≠ Finset.univ := by
    intro h
    have hc : (Finset.univ : Finset (Fin (Module.finrank ℂ V))).card = 0 := by rw [← h]; simp
    rw [Finset.card_univ, Fintype.card_fin] at hc
    rw [hdim] at hc; omega
  have hidxinj : Function.Injective
      (![(∅ : Finset (Fin (Module.finrank ℂ V))), Finset.univ]) := by
    intro x y hxy
    fin_cases x <;> fin_cases y <;> simp_all
  have hli : LinearIndependent ℂ ![(1 : CliffAlg B), e B v Finset.univ] := by
    have hcomp : ![(1 : CliffAlg B), e B v Finset.univ]
        = ⇑(cliffBasis B v hv) ∘ ![(∅ : Finset (Fin (Module.finrank ℂ V))), Finset.univ] := by
      funext i; fin_cases i <;> simp [cliffBasis_apply, e_empty]
    rw [hcomp]
    exact (cliffBasis B v hv).linearIndependent.comp _ hidxinj
  -- Idempotent equation `g0² = g0` gives two scalar equations.
  have expand : (a • (1 : CliffAlg B) + b • e B v Finset.univ)
        * (a • (1 : CliffAlg B) + b • e B v Finset.univ)
      = (a * a + b * b * μ) • (1 : CliffAlg B) + (2 * a * b) • e B v Finset.univ := by
    rw [mul_add, add_mul, add_mul, smul_mul_smul_comm, smul_mul_smul_comm,
        smul_mul_smul_comm, smul_mul_smul_comm]
    simp only [mul_one, one_mul]
    rw [hμ]
    module
  have hidem : (a * a + b * b * μ - a) • (1 : CliffAlg B)
      + (2 * a * b - b) • e B v Finset.univ = 0 := by
    have h : (a • (1 : CliffAlg B) + b • e B v Finset.univ)
          * (a • (1 : CliffAlg B) + b • e B v Finset.univ)
        = a • (1 : CliffAlg B) + b • e B v Finset.univ := by rw [hab]; exact hg0sq
    rw [expand] at h
    rw [sub_smul, sub_smul, sub_add_sub_comm, sub_eq_zero]
    exact h
  have hzero : ∀ i, (![a * a + b * b * μ - a, 2 * a * b - b] : Fin 2 → ℂ) i = 0 := by
    apply (Fintype.linearIndependent_iff.mp hli)
    rw [Fin.sum_univ_two]
    simpa using hidem
  have heq2 : 2 * a * b - b = 0 := by simpa using hzero 1
  -- `b ≠ 0`, else `g0` is a scalar idempotent, forcing `g0 ∈ {0, 1}`.
  have hb0 : b ≠ 0 := by
    intro hb
    rw [hb, zero_smul, add_zero] at hab
    have hinj : Function.Injective (algebraMap ℂ (CliffAlg B)) :=
      (algebraMap ℂ (CliffAlg B)).injective
    have key : (a * a) • (1 : CliffAlg B) = a • (1 : CliffAlg B) := by
      have h := hg0sq
      rw [← hab, smul_mul_smul_comm, mul_one] at h
      exact h
    have haa : a * a = a := by
      have e2 := key
      rw [← Algebra.algebraMap_eq_smul_one, ← Algebra.algebraMap_eq_smul_one] at e2
      exact hinj e2
    have hfac : a * (a - 1) = 0 := by rw [mul_sub, mul_one, haa, sub_self]
    rcases mul_eq_zero.mp hfac with h | h
    · exact hg0ne0 (by rw [← hab, h, zero_smul])
    · exact hg0ne1 (by rw [← hab, sub_eq_zero.mp h, one_smul])
  -- Hence `2a = 1`.
  have h2a : 2 * a = 1 := by
    have hbf : b * (2 * a - 1) = 0 := by linear_combination heq2
    rcases mul_eq_zero.mp hbf with h | h
    · exact absurd h hb0
    · exact sub_eq_zero.mp h
  -- The grade involution negates `e univ` (odd dimension), whence `involute g0 = g1`.
  have hinv_u : CliffordAlgebra.involute (e B v Finset.univ) = - e B v Finset.univ := by
    rw [involute_e]
    have hcard : (Finset.univ : Finset (Fin (Module.finrank ℂ V))).card = Module.finrank ℂ V := by
      rw [Finset.card_univ, Fintype.card_fin]
    rw [hcard, hNodd.neg_one_pow, neg_one_smul]
  have hφg0 : CliffordAlgebra.involute g0 = g1 := by
    rw [← hab, map_add, map_smul, map_smul, map_one, hinv_u]
    have hlin : (a • (1 : CliffAlg B) + b • (- e B v Finset.univ))
          + (a • (1 : CliffAlg B) + b • e B v Finset.univ)
        = (2 * a) • (1 : CliffAlg B) := by module
    have hone : (2 * a) • (1 : CliffAlg B) = 1 := by rw [h2a, one_smul]
    have htgt : (a • (1 : CliffAlg B) + b • (- e B v Finset.univ)) + g0 = 1 := by
      rw [← hab, hlin, hone]
    have hcancel : (a • (1 : CliffAlg B) + b • (- e B v Finset.univ)) + g0 = g1 + g0 := by
      rw [htgt, add_comm g1 g0, hg01]
    exact add_right_cancel hcancel
  -- Transport the grade involution to an automorphism `ψ : P ≃ₐ P` with `ψ e0 = e1`.
  let φE : CliffAlg B ≃ₐ[ℂ] CliffAlg B := CliffordAlgebra.involuteEquiv
  have hφE : ∀ x, φE x = CliffordAlgebra.involute x := fun _ => rfl
  let ψ : P ≃ₐ[ℂ] P := (eiso.symm.trans φE).trans eiso
  have hψe0 : ψ e0 = e1 := by
    change eiso (φE (eiso.symm e0)) = e1
    rw [← hg0, hφE, hφg0, hg1, AlgEquiv.apply_symm_apply]
  -- The two "coordinate" left ideals `Iᵢ = eᵢ · P` have `finrank = dᵢ²`, and `ψ` swaps them.
  set I0 : Submodule ℂ P := LinearMap.range (LinearMap.mulLeft ℂ e0) with hI0
  set I1 : Submodule ℂ P := LinearMap.range (LinearMap.mulLeft ℂ e1) with hI1
  have he0mul : ∀ p : P, e0 * p = Pi.single 0 (p 0) := by
    intro p; rw [he0]; funext j
    rcases eq_or_ne j 0 with rfl | hj
    · simp +zetaDelta [Pi.mul_apply, Pi.single_eq_same]
    · simp +zetaDelta [Pi.mul_apply, Pi.single_eq_of_ne hj]
  have he1mul : ∀ p : P, e1 * p = Pi.single 1 (p 1) := by
    intro p; rw [he1]; funext j
    rcases eq_or_ne j 1 with rfl | hj
    · simp +zetaDelta [Pi.mul_apply, Pi.single_eq_same]
    · simp +zetaDelta [Pi.mul_apply, Pi.single_eq_of_ne hj]
  have hI0eq : I0 = LinearMap.range
      (LinearMap.single ℂ (fun i : Fin 2 => Matrix (Fin (d i)) (Fin (d i)) ℂ) 0) := by
    rw [hI0]; apply le_antisymm
    · rintro _ ⟨p, rfl⟩
      rw [LinearMap.mulLeft_apply, he0mul]
      exact ⟨p 0, by rw [LinearMap.single_apply]⟩
    · rintro _ ⟨x, rfl⟩
      refine ⟨Pi.single 0 x, ?_⟩
      rw [LinearMap.mulLeft_apply, he0mul, LinearMap.single_apply]
      simp
  have hI1eq : I1 = LinearMap.range
      (LinearMap.single ℂ (fun i : Fin 2 => Matrix (Fin (d i)) (Fin (d i)) ℂ) 1) := by
    rw [hI1]; apply le_antisymm
    · rintro _ ⟨p, rfl⟩
      rw [LinearMap.mulLeft_apply, he1mul]
      exact ⟨p 1, by rw [LinearMap.single_apply]⟩
    · rintro _ ⟨x, rfl⟩
      refine ⟨Pi.single 1 x, ?_⟩
      rw [LinearMap.mulLeft_apply, he1mul, LinearMap.single_apply]
      simp
  have hfrI0 : Module.finrank ℂ I0 = d 0 * d 0 := by
    rw [hI0eq, LinearMap.finrank_range_of_inj
        (LinearMap.ker_eq_bot.mp (LinearMap.ker_single
          (R := ℂ) (φ := fun i : Fin 2 => Matrix (Fin (d i)) (Fin (d i)) ℂ) 0)),
      Module.finrank_matrix]
    simp
  have hfrI1 : Module.finrank ℂ I1 = d 1 * d 1 := by
    rw [hI1eq, LinearMap.finrank_range_of_inj
        (LinearMap.ker_eq_bot.mp (LinearMap.ker_single
          (R := ℂ) (φ := fun i : Fin 2 => Matrix (Fin (d i)) (Fin (d i)) ℂ) 1)),
      Module.finrank_matrix]
    simp
  have hψsymm_e1 : ψ.symm e1 = e0 := ψ.symm_apply_eq.mpr hψe0.symm
  have hmap : Submodule.map (ψ.toLinearEquiv : P →ₗ[ℂ] P) I0 = I1 := by
    rw [hI0, hI1]
    ext y
    simp only [Submodule.mem_map, LinearMap.mem_range, LinearEquiv.coe_coe,
      AlgEquiv.coe_toLinearEquiv, LinearMap.mulLeft_apply]
    constructor
    · rintro ⟨x, ⟨q, rfl⟩, rfl⟩
      exact ⟨ψ q, by rw [map_mul, hψe0]⟩
    · rintro ⟨r, rfl⟩
      exact ⟨ψ.symm (e1 * r), ⟨ψ.symm r, by rw [← hψsymm_e1, ← map_mul]⟩,
        ψ.apply_symm_apply _⟩
  have hfr_eq : d 1 * d 1 = d 0 * d 0 := by
    have hfm := LinearEquiv.finrank_map_eq ψ.toLinearEquiv I0
    rw [hmap] at hfm
    rw [← hfrI1, ← hfrI0, hfm]
  -- So `d0 = d1`; the total dimension count then forces `d0 = d1 = 2ⁿ`.
  have hd01 : d 0 = d 1 := (mul_self_inj (Nat.zero_le _) (Nat.zero_le _)).mp hfr_eq.symm
  have hfrP : Module.finrank ℂ P = d 0 * d 0 + d 1 * d 1 := by
    change Module.finrank ℂ (∀ i : Fin 2, Matrix (Fin (d i)) (Fin (d i)) ℂ) = _
    rw [Module.finrank_pi_fintype, Fin.sum_univ_two]
    simp [Module.finrank_matrix]
  have hfrPeq : Module.finrank ℂ P = 2 ^ (2 * n + 1) := by
    rw [← eiso.toLinearEquiv.finrank_eq, finrank_cliffAlg B v, hdim]
  have hk : d 0 = 2 ^ n := by
    have hsum : d 0 * d 0 + d 0 * d 0 = 2 ^ n * 2 ^ n + 2 ^ n * 2 ^ n := by
      have he : d 0 * d 0 + d 1 * d 1 = 2 ^ (2 * n + 1) := hfrP.symm.trans hfrPeq
      rw [← hd01] at he
      rw [he, show 2 * n + 1 = n + n + 1 by ring, pow_succ, pow_add]; ring
    have hd0 : d 0 * d 0 = 2 ^ n * 2 ^ n := by omega
    exact (mul_self_inj (Nat.zero_le _) (Nat.zero_le _)).mp hd0
  have hd1k : d 1 = 2 ^ n := by rw [← hd01]; exact hk
  -- Assemble `P ≃ₐ M_{2ⁿ}(ℂ) × M_{2ⁿ}(ℂ) ≃ₐ End(S) × End(S)`.
  let pf2 : P ≃ₐ[ℂ] Matrix (Fin (d 0)) (Fin (d 0)) ℂ × Matrix (Fin (d 1)) (Fin (d 1)) ℂ :=
    AlgEquiv.ofRingEquiv (f := RingEquiv.piFinTwo
      (fun i : Fin 2 => Matrix (Fin (d i)) (Fin (d i)) ℂ)) (fun _ => rfl)
  let r0 : Matrix (Fin (d 0)) (Fin (d 0)) ℂ ≃ₐ[ℂ] Matrix (Fin (2 ^ n)) (Fin (2 ^ n)) ℂ :=
    Matrix.reindexAlgEquiv ℂ ℂ (finCongr hk)
  let r1 : Matrix (Fin (d 1)) (Fin (d 1)) ℂ ≃ₐ[ℂ] Matrix (Fin (2 ^ n)) (Fin (2 ^ n)) ℂ :=
    Matrix.reindexAlgEquiv ℂ ℂ (finCongr hd1k)
  let mEnd : Matrix (Fin (2 ^ n)) (Fin (2 ^ n)) ℂ ≃ₐ[ℂ] Module.End ℂ (Fin (2 ^ n) → ℂ) :=
    LinearMap.toMatrixAlgEquiv'.symm
  refine ⟨Fin (2 ^ n) → ℂ, inferInstance, inferInstance, ?_, ⟨?_⟩⟩
  · rw [Module.finrank_fintype_fun_eq_card, Fintype.card_fin]
  · exact eiso.trans (pf2.trans ((AlgEquiv.prodCongr r0 r1).trans (AlgEquiv.prodCongr mEnd mEnd)))

omit [FiniteDimensional ℂ V] in
/-- **Problem 3.9.5(ii), forward direction.** If `B` is degenerate then `Cl(V)` is *not* a
semisimple ring.

Proof sketch (elementary, no spinor construction needed). Degeneracy gives a nonzero vector `v`
in the radical of `B` (`∀ w, B v w = 0`). Set `a := ι v ∈ Cl(V)`. Then:
* `a * a = ι v * ι v = Q v = B v v = 0`;
* `a` anticommutes with every `ι w`, since `polar Q v w = B v w + B w v = 0`;
* consequently `a * r = involute r * a` for all `r` (grade involution, by Clifford induction),
  hence `a * r * a = involute r * (a * a) = 0`.

For every `y`, `(a*y)^2 = a*y*a*y = (a*y*a)*y = 0`, so `1 + a*y` is a unit with inverse `1 - a*y`.
By `Ideal.mem_jacobson_bot` this puts `a` in the Jacobson radical. But `a = ι v ≠ 0` (the map `ι`
is injective in characteristic `≠ 2`, via `CliffordAlgebra.equivExterior`), while a semisimple ring
has trivial Jacobson radical (`IsSemisimpleRing.jacobson_eq_bot`), a contradiction. -/
theorem not_isSemisimpleRing_of_degenerate
    (hsymm : ∀ x y, B x y = B y x) (hdeg : ¬ B.Nondegenerate) :
    ¬ IsSemisimpleRing (CliffAlg B) := by
  classical
  intro hss
  -- A nonzero radical vector `v`.
  obtain ⟨v, hv0, hvne⟩ : ∃ v : V, (∀ w, B v w = 0) ∧ v ≠ 0 := by
    rw [LinearMap.BilinForm.Nondegenerate, LinearMap.Nondegenerate, not_and_or] at hdeg
    rcases hdeg with h | h
    · rw [LinearMap.SeparatingLeft] at h
      push Not at h
      obtain ⟨v, hv, hne⟩ := h
      exact ⟨v, hv, hne⟩
    · rw [LinearMap.SeparatingRight] at h
      push Not at h
      obtain ⟨v, hv, hne⟩ := h
      exact ⟨v, fun w => (hsymm v w).trans (hv w), hne⟩
  set Q := quadForm B with hQ
  set a : CliffAlg B := CliffordAlgebra.ι Q v with ha
  -- `a * a = 0`.
  have haa : a * a = 0 := by
    have hQv : Q v = 0 := by
      simp only [hQ, quadForm, LinearMap.BilinMap.toQuadraticMap_apply]
      exact hv0 v
    rw [ha, CliffordAlgebra.ι_sq_scalar, hQv, map_zero]
  -- `a` anticommutes with every generator.
  have hanti : ∀ w, a * CliffordAlgebra.ι Q w + CliffordAlgebra.ι Q w * a = 0 := by
    intro w
    have hpolar : QuadraticMap.polar Q v w = 0 := by
      rw [hQ, LinearMap.BilinMap.polar_toQuadraticMap, hv0 w, hsymm w v, hv0 w, add_zero]
    rw [ha, CliffordAlgebra.ι_mul_ι_add_swap, hpolar, map_zero]
  -- Grade-involution intertwining: `a * r = involute r * a`.
  have hkey : ∀ r : CliffAlg B, a * r = CliffordAlgebra.involute r * a := by
    intro r
    induction r using CliffordAlgebra.induction with
    | algebraMap s => rw [AlgHom.commutes, Algebra.commutes]
    | ι w =>
        rw [CliffordAlgebra.involute_ι, neg_mul]
        exact eq_neg_of_add_eq_zero_left (hanti w)
    | mul x y hx hy => rw [← mul_assoc, hx, mul_assoc, hy, ← mul_assoc, map_mul]
    | add x y hx hy => rw [mul_add, hx, hy, map_add, add_mul]
  -- Hence `a * r * a = 0` for all `r`.
  have hara : ∀ r : CliffAlg B, a * r * a = 0 := by
    intro r
    rw [hkey r, mul_assoc, haa, mul_zero]
  -- `a` lies in the Jacobson radical: it belongs to every maximal left ideal `M`. Indeed if
  -- `a ∉ M`, then `M ⊔ span{a} = ⊤` by maximality, so `1 = m + r*a` with `m ∈ M`; then
  -- `m = 1 - r*a` is a unit (inverse `1 + r*a`, since `(r*a)² = r*(a*r*a) = 0`), forcing `M = ⊤`.
  have hmem : a ∈ Ring.jacobson (CliffAlg B) := by
    rw [Ring.jacobson_eq_sInf_isMaximal]
    refine Ideal.mem_sInf.mpr (fun {M} hM => ?_)
    rw [Set.mem_setOf_eq] at hM
    by_contra haM
    have hlt : M < M ⊔ Ideal.span {a} := by
      refine lt_of_le_of_ne le_sup_left (fun heq => haM ?_)
      have hain : a ∈ M ⊔ Ideal.span {a} :=
        Submodule.mem_sup_right (Ideal.mem_span_singleton_self a)
      rwa [← heq] at hain
    have hsup : M ⊔ Ideal.span {a} = ⊤ := (Ideal.isMaximal_def.1 hM).2 _ hlt
    have h1 : (1 : CliffAlg B) ∈ M ⊔ Ideal.span {a} := hsup ▸ Submodule.mem_top
    rw [Submodule.mem_sup] at h1
    obtain ⟨m, hmM, n, hn, hmn⟩ := h1
    obtain ⟨r, hr⟩ := Ideal.mem_span_singleton'.mp hn
    have hm_eq : m = 1 - r * a := by
      rw [← hr] at hmn; exact eq_sub_of_add_eq hmn
    have h0 : r * a * r * a = 0 := by
      have e : r * a * r * a = r * (a * r * a) := by noncomm_ring
      rw [e, hara r, mul_zero]
    have hunit : IsUnit m := by
      rw [hm_eq]
      have hval : (1 - r * a) * (1 + r * a) = 1 := by
        have e : (1 - r * a) * (1 + r * a) = 1 - r * a * r * a := by noncomm_ring
        rw [e, h0, sub_zero]
      have hinv : (1 + r * a) * (1 - r * a) = 1 := by
        have e : (1 + r * a) * (1 - r * a) = 1 - r * a * r * a := by noncomm_ring
        rw [e, h0, sub_zero]
      exact ⟨⟨1 - r * a, 1 + r * a, hval, hinv⟩, rfl⟩
    exact hM.ne_top (Ideal.eq_top_of_isUnit_mem M hmM hunit)
  -- But `a = ι v ≠ 0`, contradicting triviality of the radical of a semisimple ring.
  have ha_ne : a ≠ 0 := by
    rw [ha]
    intro h0
    apply hvne
    haveI : Invertible (2 : ℂ) := invertibleOfNonzero (by norm_num)
    have himg : (CliffordAlgebra.equivExterior Q) (CliffordAlgebra.ι Q v)
        = ExteriorAlgebra.ι ℂ v :=
      CliffordAlgebra.changeForm_ι CliffordAlgebra.changeForm.associated_neg_proof v
    have : ExteriorAlgebra.ι ℂ v = 0 := by rw [← himg, h0, map_zero]
    exact (ExteriorAlgebra.ι_eq_zero_iff (R := ℂ) v).1 this
  have hjac : Ring.jacobson (CliffAlg B) = ⊥ := IsSemisimpleRing.jacobson_eq_bot (CliffAlg B)
  rw [hjac, Ideal.mem_bot] at hmem
  exact ha_ne hmem

/-- **Problem 3.9.5(ii).** `Cl(V)` is semisimple if and only if `B` is nondegenerate.

The forward direction is `not_isSemisimpleRing_of_degenerate` (contrapositive); the reverse is
`isSemisimpleRing_of_nondegenerate` (part (i), the spinor construction). -/
theorem isSemisimpleRing_iff_nondegenerate (hsymm : ∀ x y, B x y = B y x) :
    IsSemisimpleRing (CliffAlg B) ↔ B.Nondegenerate := by
  refine ⟨fun hss => ?_, fun hnd => isSemisimpleRing_of_nondegenerate B hsymm hnd⟩
  by_contra hdeg
  exact not_isSemisimpleRing_of_degenerate B hsymm hdeg hss

/-- The radical submodule of `B`: the vectors `v` with `B v = 0` (equivalently `B v w = 0`
for all `w`). This is the kernel of `B : V →ₗ[ℂ] V →ₗ[ℂ] ℂ`. -/
noncomputable def radSubmodule : Submodule ℂ V := LinearMap.ker B

omit [FiniteDimensional ℂ V] in
theorem mem_radSubmodule {v : V} : v ∈ radSubmodule B ↔ B v = 0 := Iff.rfl

/-- The bilinear form induced by `B` on the quotient `V ⧸ rad B`. Constructed by descending both
arguments of `B` across the quotient map (well-defined because `B` vanishes on the radical, using
symmetry for the second argument). -/
noncomputable def radQuotForm (hsymm : ∀ x y, B x y = B y x) :
    LinearMap.BilinForm ℂ (V ⧸ radSubmodule B) :=
  -- descend the first argument: `B` factors through `V ⧸ ker B`
  let Bfst : (V ⧸ radSubmodule B) →ₗ[ℂ] V →ₗ[ℂ] ℂ := (radSubmodule B).liftQ B le_rfl
  -- flip so the un-quotiented `V` argument becomes outer, then descend it too
  let g : V →ₗ[ℂ] (V ⧸ radSubmodule B) →ₗ[ℂ] ℂ := Bfst.flip
  ((radSubmodule B).liftQ g (by
    intro u hu
    rw [LinearMap.mem_ker]
    refine LinearMap.ext fun w => ?_
    obtain ⟨v, rfl⟩ := (radSubmodule B).mkQ_surjective w
    change Bfst ((radSubmodule B).mkQ v) u = 0
    -- `Bfst (mk v) u = B v u = B u v = 0` since `u ∈ rad B`
    have h0 : B u = 0 := (mem_radSubmodule B).1 hu
    simp only [Submodule.mkQ_apply, Submodule.liftQ_apply, Bfst]
    rw [hsymm v u, h0, LinearMap.zero_apply])).flip

omit [FiniteDimensional ℂ V] in
@[simp]
theorem radQuotForm_mk_mk (hsymm : ∀ x y, B x y = B y x) (v w : V) :
    radQuotForm B hsymm ((radSubmodule B).mkQ v) ((radSubmodule B).mkQ w) = B v w := by
  simp only [radQuotForm, LinearMap.flip_apply, Submodule.mkQ_apply, Submodule.liftQ_apply]

omit [FiniteDimensional ℂ V] in
theorem radQuotForm_isSymm (hsymm : ∀ x y, B x y = B y x) :
    ∀ x y, radQuotForm B hsymm x y = radQuotForm B hsymm y x := by
  intro x y
  obtain ⟨v, rfl⟩ := (radSubmodule B).mkQ_surjective x
  obtain ⟨w, rfl⟩ := (radSubmodule B).mkQ_surjective y
  rw [radQuotForm_mk_mk, radQuotForm_mk_mk, hsymm]

omit [FiniteDimensional ℂ V] in
theorem radQuotForm_nondegenerate (hsymm : ∀ x y, B x y = B y x) :
    (radQuotForm B hsymm).Nondegenerate := by
  have hL : (radQuotForm B hsymm).SeparatingLeft := by
    intro x hx
    obtain ⟨v, rfl⟩ := (radSubmodule B).mkQ_surjective x
    rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero, mem_radSubmodule]
    ext w
    have := hx ((radSubmodule B).mkQ w)
    rwa [radQuotForm_mk_mk] at this
  exact ⟨hL, fun y hy => hL y fun x => by rw [radQuotForm_isSymm]; exact hy x⟩

omit [FiniteDimensional ℂ V] in
/-- For a radical vector `u` (so `ι u` anticommutes with every generator `ι y`), left
multiplication by `ι u` intertwines with the grade involution: `ι u * z = involute z * ι u`. -/
theorem ι_rad_mul (hsymm : ∀ x y, B x y = B y x) {u : V} (hu : u ∈ radSubmodule B)
    (z : CliffAlg B) :
    CliffordAlgebra.ι (quadForm B) u * z
      = CliffordAlgebra.involute z * CliffordAlgebra.ι (quadForm B) u := by
  induction z using CliffordAlgebra.induction with
  | algebraMap r =>
    rw [AlgHom.commutes, Algebra.commutes]
  | ι y =>
    rw [CliffordAlgebra.involute_ι, neg_mul]
    have hp : QuadraticMap.polar (quadForm B) u y = 0 := by
      have h0 : B u = 0 := (mem_radSubmodule B).1 hu
      have hu0 : (B u) y = 0 := by rw [h0]; rfl
      have hyu : (B y) u = 0 := by rw [hsymm y u]; exact hu0
      change QuadraticMap.polar (LinearMap.BilinMap.toQuadraticMap B) u y = 0
      rw [LinearMap.BilinMap.polar_toQuadraticMap, hu0, hyu, add_zero]
    have hswap := CliffordAlgebra.ι_mul_ι_add_swap (Q := quadForm B) u y
    rw [hp, map_zero] at hswap
    exact eq_neg_of_add_eq_zero_left hswap
  | mul a b ha hb =>
    rw [← mul_assoc, ha, mul_assoc, hb, ← mul_assoc, ← map_mul]
  | add a b ha hb =>
    rw [mul_add, ha, hb, map_add, add_mul]

/-- The canonical isometry `Cl(V) → Cl(V ⧸ rad B)` underlying the quotient map on `V`. -/
noncomputable def radQuotIsometry (hsymm : ∀ x y, B x y = B y x) :
    (quadForm B) →qᵢ (quadForm (radQuotForm B hsymm)) where
  toLinearMap := (radSubmodule B).mkQ
  map_app' v := by
    change LinearMap.BilinMap.toQuadraticMap (radQuotForm B hsymm) ((radSubmodule B).mkQ v)
      = LinearMap.BilinMap.toQuadraticMap B v
    rw [LinearMap.BilinMap.toQuadraticMap_apply, LinearMap.BilinMap.toQuadraticMap_apply,
      radQuotForm_mk_mk]

/-- The two-sided ideal of `Cl(V)` generated by `ι v` for `v` in the radical of `B`. This is the
kernel of the map to `Cl(V ⧸ rad B)` and, when `B` is symmetric, equals the Jacobson radical. -/
noncomputable def radIdeal : Ideal (CliffAlg B) :=
  Ideal.span (CliffordAlgebra.ι (quadForm B) '' (radSubmodule B : Set V))

omit [FiniteDimensional ℂ V] in
theorem ι_mem_radIdeal {u : V} (hu : u ∈ radSubmodule B) :
    CliffordAlgebra.ι (quadForm B) u ∈ radIdeal B :=
  Ideal.subset_span ⟨u, hu, rfl⟩

omit [FiniteDimensional ℂ V] in
/-- `radIdeal B` is a two-sided ideal: using `ι_rad_mul`, `ι u * z` is a left multiple of `ι u`. -/
theorem radIdeal_isTwoSided (hsymm : ∀ x y, B x y = B y x) : (radIdeal B).IsTwoSided := by
  -- `T`: the left ideal of elements that stay in `radIdeal` after right multiplication.
  let T : Submodule (CliffAlg B) (CliffAlg B) :=
    { carrier := {x | ∀ c, x * c ∈ radIdeal B}
      add_mem' := fun {x y} hx hy c => by rw [add_mul]; exact (radIdeal B).add_mem (hx c) (hy c)
      zero_mem' := fun c => by rw [zero_mul]; exact (radIdeal B).zero_mem
      smul_mem' := fun r x hx c => by
        rw [smul_eq_mul, mul_assoc]; exact (radIdeal B).mul_mem_left r (hx c) }
  have hsub : radIdeal B ≤ T := by
    rw [radIdeal, Ideal.span_le]
    rintro _ ⟨u, hu, rfl⟩ c
    rw [ι_rad_mul B hsymm hu c]
    exact (radIdeal B).mul_mem_left _ (ι_mem_radIdeal B hu)
  exact ⟨fun {a} b ha => hsub ha b⟩

omit [FiniteDimensional ℂ V] in
/-- The kernel of the algebra map `Cl(V) → Cl(V ⧸ rad B)` is exactly the ideal generated by
`ι(rad B)`. The hard inclusion `ker ⊆ radIdeal` is a retraction: the algebra map
`Cl(V ⧸ rad B) → Cl(V)/radIdeal` sending `ι v̄ ↦ [ι v]` (well-defined since `ι` of a radical
vector lands in `radIdeal`) is a left inverse to `Cl(V) → Cl(V ⧸ rad B)`. -/
theorem ker_map_radQuotIsometry (hsymm : ∀ x y, B x y = B y x) :
    RingHom.ker (CliffordAlgebra.map (radQuotIsometry B hsymm)).toRingHom = radIdeal B := by
  haveI hTS : (radIdeal B).IsTwoSided := radIdeal_isTwoSided B hsymm
  set φ0 := CliffordAlgebra.map (radQuotIsometry B hsymm) with hφ0
  set mkq := Ideal.Quotient.mkₐ ℂ (radIdeal B) with hmkq
  refine le_antisymm ?_ ?_
  · -- `ker φ0 ⊆ radIdeal`, via the retraction `h`.
    have hker_le : radSubmodule B ≤
        LinearMap.ker (mkq.toLinearMap.comp (CliffordAlgebra.ι (quadForm B))) := by
      intro u hu
      rw [LinearMap.mem_ker, LinearMap.comp_apply, AlgHom.toLinearMap_apply, hmkq,
        Ideal.Quotient.mkₐ_eq_mk, Ideal.Quotient.eq_zero_iff_mem]
      exact ι_mem_radIdeal B hu
    set k := (radSubmodule B).liftQ (mkq.toLinearMap.comp (CliffordAlgebra.ι (quadForm B)))
      hker_le with hk
    have hkv : ∀ v : V, k ((radSubmodule B).mkQ v) = mkq (CliffordAlgebra.ι (quadForm B) v) := by
      intro v
      rw [hk, Submodule.mkQ_apply, Submodule.liftQ_apply, LinearMap.comp_apply,
        AlgHom.toLinearMap_apply]
    have hcond : ∀ w, k w * k w =
        algebraMap ℂ (CliffAlg B ⧸ radIdeal B) (quadForm (radQuotForm B hsymm) w) := by
      intro w
      obtain ⟨v, rfl⟩ := (radSubmodule B).mkQ_surjective w
      have hq : quadForm (radQuotForm B hsymm) ((radSubmodule B).mkQ v) = quadForm B v := by
        change LinearMap.BilinMap.toQuadraticMap (radQuotForm B hsymm) ((radSubmodule B).mkQ v)
          = LinearMap.BilinMap.toQuadraticMap B v
        rw [LinearMap.BilinMap.toQuadraticMap_apply, LinearMap.BilinMap.toQuadraticMap_apply,
          radQuotForm_mk_mk]
      rw [hkv, hq, ← map_mul, CliffordAlgebra.ι_sq_scalar]
      exact mkq.commutes _
    set h := CliffordAlgebra.lift (quadForm (radQuotForm B hsymm)) ⟨k, hcond⟩ with hh
    have hcomp : h.comp φ0 = mkq := by
      apply CliffordAlgebra.hom_ext
      ext v
      simp only [AlgHom.toLinearMap_apply, LinearMap.comp_apply, AlgHom.comp_apply]
      rw [hφ0, CliffordAlgebra.map_apply_ι, hh, CliffordAlgebra.lift_ι_apply]
      exact hkv v
    intro x hx
    rw [RingHom.mem_ker] at hx
    have hx0 : mkq x = 0 := by
      have hcx := congrArg (fun f : CliffAlg B →ₐ[ℂ] _ => f x) hcomp
      simp only [AlgHom.comp_apply] at hcx
      rw [← hcx]
      change h (φ0 x) = 0
      rw [show φ0 x = 0 from hx, map_zero]
    rwa [hmkq, Ideal.Quotient.mkₐ_eq_mk, Ideal.Quotient.eq_zero_iff_mem] at hx0
  · -- `radIdeal ⊆ ker φ0`: each generator `ι u` maps to `ι 0 = 0`.
    have hsub : (CliffordAlgebra.ι (quadForm B) '' (radSubmodule B : Set V)) ⊆
        (RingHom.ker φ0.toRingHom : Set (CliffAlg B)) := by
      rintro _ ⟨u, hu, rfl⟩
      rw [SetLike.mem_coe, RingHom.mem_ker]
      change φ0 (CliffordAlgebra.ι (quadForm B) u) = 0
      rw [hφ0, CliffordAlgebra.map_apply_ι]
      have hu0 : (radQuotIsometry B hsymm) u = 0 := by
        change (radSubmodule B).mkQ u = 0
        rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]; exact hu
      rw [hu0, map_zero]
    exact Ideal.span_le.mpr hsub

omit [FiniteDimensional ℂ V] in
/-- Each generator `ι u` of `radIdeal` (with `u` in the radical) lies in the Jacobson radical:
`a := ι u` squares to zero and satisfies `a r a = 0`, so for a maximal left ideal `M` with `a ∉ M`
one writes `1 = m + r a` with `m = 1 - r a` a unit (inverse `1 + r a`), contradicting `M ≠ ⊤`. -/
theorem ι_mem_jacobson (hsymm : ∀ x y, B x y = B y x) {u : V} (hu : u ∈ radSubmodule B) :
    CliffordAlgebra.ι (quadForm B) u ∈ Ring.jacobson (CliffAlg B) := by
  set a : CliffAlg B := CliffordAlgebra.ι (quadForm B) u with ha
  have haa : a * a = 0 := by
    have hQu : quadForm B u = 0 := by
      have h0 : B u = 0 := (mem_radSubmodule B).1 hu
      change LinearMap.BilinMap.toQuadraticMap B u = 0
      rw [LinearMap.BilinMap.toQuadraticMap_apply, h0, LinearMap.zero_apply]
    rw [ha, CliffordAlgebra.ι_sq_scalar, hQu, map_zero]
  have hara : ∀ r : CliffAlg B, a * r * a = 0 := by
    intro r
    have hkey : a * r = CliffordAlgebra.involute r * a := ι_rad_mul B hsymm hu r
    rw [hkey, mul_assoc, haa, mul_zero]
  rw [Ring.jacobson_eq_sInf_isMaximal]
  refine Ideal.mem_sInf.mpr (fun {M} hM => ?_)
  rw [Set.mem_setOf_eq] at hM
  by_contra haM
  have hlt : M < M ⊔ Ideal.span {a} := by
    refine lt_of_le_of_ne le_sup_left (fun heq => haM ?_)
    have hain : a ∈ M ⊔ Ideal.span {a} :=
      Submodule.mem_sup_right (Ideal.mem_span_singleton_self a)
    rwa [← heq] at hain
  have hsup : M ⊔ Ideal.span {a} = ⊤ := (Ideal.isMaximal_def.1 hM).2 _ hlt
  have h1 : (1 : CliffAlg B) ∈ M ⊔ Ideal.span {a} := hsup ▸ Submodule.mem_top
  rw [Submodule.mem_sup] at h1
  obtain ⟨m, hmM, n, hn, hmn⟩ := h1
  obtain ⟨r, hr⟩ := Ideal.mem_span_singleton'.mp hn
  have hm_eq : m = 1 - r * a := by rw [← hr] at hmn; exact eq_sub_of_add_eq hmn
  have h0 : r * a * r * a = 0 := by
    have e : r * a * r * a = r * (a * r * a) := by noncomm_ring
    rw [e, hara r, mul_zero]
  have hunit : IsUnit m := by
    rw [hm_eq]
    have hval : (1 - r * a) * (1 + r * a) = 1 := by
      have e : (1 - r * a) * (1 + r * a) = 1 - r * a * r * a := by noncomm_ring
      rw [e, h0, sub_zero]
    have hinv : (1 + r * a) * (1 - r * a) = 1 := by
      have e : (1 + r * a) * (1 - r * a) = 1 - r * a * r * a := by noncomm_ring
      rw [e, h0, sub_zero]
    exact ⟨⟨1 - r * a, 1 + r * a, hval, hinv⟩, rfl⟩
  exact hM.ne_top (Ideal.eq_top_of_isUnit_mem M hmM hunit)

/-- The ideal `radIdeal B` generated by `ι(rad B)` equals the Jacobson radical of `Cl(V)`.
`radIdeal ≤ jacobson` since its generators lie in the radical (`ι_mem_jacobson`); the reverse holds
because `Cl(V)/radIdeal ≅ Cl(V ⧸ rad B)` is semisimple (`isSemisimpleRing_of_nondegenerate`), so
the radical is killed by the surjection to it. -/
theorem radIdeal_eq_jacobson (hsymm : ∀ x y, B x y = B y x) :
    radIdeal B = Ring.jacobson (CliffAlg B) := by
  refine le_antisymm ?_ ?_
  · change Ideal.span (CliffordAlgebra.ι (quadForm B) '' (radSubmodule B : Set V)) ≤ _
    rw [Ideal.span_le]
    rintro _ ⟨u, hu, rfl⟩
    exact ι_mem_jacobson B hsymm hu
  · haveI hss : IsSemisimpleRing (CliffAlg (radQuotForm B hsymm)) :=
      isSemisimpleRing_of_nondegenerate (radQuotForm B hsymm) (radQuotForm_isSymm B hsymm)
        (radQuotForm_nondegenerate B hsymm)
    set φ0 := CliffordAlgebra.map (radQuotIsometry B hsymm) with hφ0
    haveI hsurj : RingHomSurjective φ0.toRingHom :=
      ⟨CliffordAlgebra.map_surjective (radQuotIsometry B hsymm)
        (Submodule.mkQ_surjective (radSubmodule B))⟩
    let fsl : CliffAlg B →ₛₗ[φ0.toRingHom] (CliffAlg (radQuotForm B hsymm)) :=
      { toFun := φ0
        map_add' := map_add φ0
        map_smul' := fun r x => by rw [smul_eq_mul, smul_eq_mul]; exact map_mul φ0 r x }
    have hle := IsSemisimpleModule.jacobson_le_ker (f := fsl)
    rw [← ker_map_radQuotIsometry B hsymm]
    intro x hx
    rw [RingHom.mem_ker]
    have hxk : x ∈ LinearMap.ker fsl := hle hx
    rwa [LinearMap.mem_ker] at hxk

/-- **Problem 3.9.5(ii), the degenerate quotient.** If `B` is degenerate, the semisimple
quotient `Cl(V) / Rad(Cl(V))` is the Clifford algebra of a nondegenerate form `B'` on the
quotient of `V` by the radical of `B`. Phrased as: there is a nondegenerate symmetric form
`B'` on some space `W` together with a surjective algebra map `Cl(V) → Cl(W, B')` whose
kernel is the Jacobson radical. -/
theorem radicalQuotient_isClifford_of_degenerate
    (hsymm : ∀ x y, B x y = B y x) (hdeg : ¬ B.Nondegenerate) :
    ∃ (W : Type) (_ : AddCommGroup W) (_ : Module ℂ W) (B' : LinearMap.BilinForm ℂ W),
      (∀ x y, B' x y = B' y x) ∧ B'.Nondegenerate ∧
      ∃ φ : CliffAlg B →ₐ[ℂ] CliffordAlgebra (quadForm B'),
        Function.Surjective φ ∧ RingHom.ker φ.toRingHom = Ring.jacobson (CliffAlg B) := by
  classical
  set U := radSubmodule B with hU
  set n := Module.finrank ℂ (V ⧸ U) with hn
  -- A `Type`-universe model `Fin n → ℂ` of `V ⧸ rad B`, and the transported form.
  let e : (V ⧸ U) ≃ₗ[ℂ] (Fin n → ℂ) := (Module.finBasis ℂ (V ⧸ U)).equivFun
  let B' : LinearMap.BilinForm ℂ (Fin n → ℂ) :=
    (radQuotForm B hsymm).compl₁₂ e.symm.toLinearMap e.symm.toLinearMap
  have hB'_apply : ∀ x y, B' x y = radQuotForm B hsymm (e.symm x) (e.symm y) :=
    fun x y => LinearMap.compl₁₂_apply _ _ _ _ _
  have hB'_symm : ∀ x y, B' x y = B' y x := fun x y => by
    rw [hB'_apply, hB'_apply, radQuotForm_isSymm]
  have hL : B'.SeparatingLeft := by
    intro x hx
    have hxr : ∀ w, radQuotForm B hsymm (e.symm x) w = 0 := by
      intro w
      have := hx (e w)
      rwa [hB'_apply, LinearEquiv.symm_apply_apply] at this
    have hx0 : e.symm x = 0 := (radQuotForm_nondegenerate B hsymm).1 _ hxr
    have := congrArg e hx0
    rwa [LinearEquiv.apply_symm_apply, map_zero] at this
  have hB'_nondeg : B'.Nondegenerate :=
    ⟨hL, fun y hy => hL y fun w => (hB'_symm y w).trans (hy w)⟩
  -- Isometry equivalence `Cl(V ⧸ rad B) ≅ Cl(W, B')`.
  let eqv : (quadForm (radQuotForm B hsymm)).IsometryEquiv (quadForm B') :=
    { toLinearEquiv := e
      map_app' := fun w => by
        change LinearMap.BilinMap.toQuadraticMap B' (e w)
          = LinearMap.BilinMap.toQuadraticMap (radQuotForm B hsymm) w
        rw [LinearMap.BilinMap.toQuadraticMap_apply, LinearMap.BilinMap.toQuadraticMap_apply,
          hB'_apply, LinearEquiv.symm_apply_apply] }
  let e_alg := CliffordAlgebra.equivOfIsometry eqv
  set φ0 := CliffordAlgebra.map (radQuotIsometry B hsymm) with hφ0
  refine ⟨Fin n → ℂ, inferInstance, inferInstance, B', hB'_symm, hB'_nondeg,
    e_alg.toAlgHom.comp φ0, ?_, ?_⟩
  · -- surjective: composite of surjections
    have h0 : Function.Surjective φ0 :=
      CliffordAlgebra.map_surjective _ (Submodule.mkQ_surjective U)
    exact e_alg.surjective.comp h0
  · -- kernel: post-composing with the iso `e_alg` does not change the kernel
    have hkereq : RingHom.ker (e_alg.toAlgHom.comp φ0).toRingHom = RingHom.ker φ0.toRingHom := by
      ext x
      rw [RingHom.mem_ker, RingHom.mem_ker]
      constructor
      · intro h
        have hx : e_alg (φ0 x) = 0 := h
        exact (map_eq_zero_iff e_alg e_alg.injective).1 hx
      · intro h
        change e_alg (φ0 x) = 0
        rw [show φ0 x = 0 from h, map_zero]
    rw [hkereq, ker_map_radQuotIsometry B hsymm, radIdeal_eq_jacobson B hsymm]

end Etingof.Problem3_9_5
