import EtingofRepresentationTheory.Chapter3.Problem3_8_4_Functoriality

/-!
# Problem 3.8.4: descent of a base-change isomorphism to a finitely generated subalgebra

`Problem3_8_4.lean` reduces part (i) of Problem 3.8.4 over an *arbitrary* field extension
`L / K` to the case of a finite extension. The book's hint first passes through a **finitely
generated** intermediate `K`-algebra: an `L ⊗[K] A`-linear isomorphism
`L ⊗[K] V ≃ L ⊗[K] W` is already defined over a finitely generated `K`-subalgebra `R ⊆ L`,
because — `V`, `W` being finite dimensional over `K` — the isomorphism and its inverse are
described by finitely many structure constants (matrix entries) in `L`. Adjoining those
finitely many elements to `K` produces a finitely generated `R`, and the polynomial identities
witnessing "mutually inverse" and "intertwines the `A`-action" already hold in `R` (they hold
in `L` and `R ↪ L`).

The main result of this file is `exists_fg_subalgebra_baseChange_iso`: from an
`L ⊗[K] A`-linear isomorphism it produces a finitely generated `K`-subalgebra `R ⊆ L`
together with an `R ⊗[K] A`-linear isomorphism `R ⊗[K] V ≃ R ⊗[K] W`. Pushing that forward
along the inclusion `R ↪ L` (`Functoriality.pushEquiv`) recovers a base-change isomorphism
over `L`; the follow-up assembly issue then pushes it further to a residue field of `R`, which
is *finite* over `K` by Zariski's lemma.

All base-changed module structures are taken from `Problem3_8_4.Functoriality.bcMod`, uniformly
in the commutative `K`-algebra parameter (here `L` and `↥R`), so that no field-versus-general
instance diamond arises.
-/

open scoped TensorProduct

namespace Etingof.Problem3_8_4.Functoriality

variable {K A V W : Type*}
  [Field K] [Ring A] [Algebra K A]
  [AddCommGroup V] [Module K V] [Module A V] [IsScalarTower K A V]
  [AddCommGroup W] [Module K W] [Module A W] [IsScalarTower K A W]

variable {L : Type*} [Field L] [Algebra K L]

/-- **Descent of a base-change isomorphism (Problem 3.8.4, reduction to finitely generated).**
Given finite dimensional `A`-modules `V`, `W` over `K` and an `L ⊗[K] A`-linear isomorphism
`L ⊗[K] V ≃ L ⊗[K] W` over a field extension `L / K`, there is a finitely generated
`K`-subalgebra `R ⊆ L` carrying an `R ⊗[K] A`-linear isomorphism `R ⊗[K] V ≃ R ⊗[K] W`.

The subalgebra is generated by the (finitely many) matrix entries of the isomorphism and its
inverse in `K`-bases of `V` and `W`; being polynomial relations in those entries, "mutually
inverse" and "`A`-linear" transport from `L` down to `R` along the injection `R ↪ L`. -/
theorem exists_fg_subalgebra_baseChange_iso
    [FiniteDimensional K V] [FiniteDimensional K W]
    (e : (L ⊗[K] V) ≃ₗ[L ⊗[K] A] (L ⊗[K] W)) :
    ∃ R : Subalgebra K L, Algebra.FiniteType K R ∧
      Nonempty ((R ⊗[K] V) ≃ₗ[R ⊗[K] A] (R ⊗[K] W)) := by
  sorry

end Etingof.Problem3_8_4.Functoriality
