import Mathlib.Data.Complex.Basic
import Mathlib.LinearAlgebra.CliffordAlgebra.Basic
import Mathlib.LinearAlgebra.CliffordAlgebra.Conjugation
import Mathlib.LinearAlgebra.CliffordAlgebra.Contraction
import Mathlib.LinearAlgebra.QuadraticForm.Basic
import Mathlib.LinearAlgebra.BilinearForm.Properties
import Mathlib.LinearAlgebra.ExteriorAlgebra.Basic
import Mathlib.LinearAlgebra.ExteriorAlgebra.Basis
import Mathlib.LinearAlgebra.Trace
import Mathlib.Algebra.Algebra.Bilinear
import Mathlib.RingTheory.SimpleModule.Basic
import Mathlib.RingTheory.Jacobson.Radical
import Mathlib.RingTheory.Jacobson.Ideal
import Mathlib.RingTheory.Jacobson.Semiprimary
import Mathlib.RingTheory.Artinian.Algebra
import Mathlib.RingTheory.Artinian.Ring
import Mathlib.LinearAlgebra.FiniteDimensional.Defs
import Mathlib.Tactic.NoncommRing
import Mathlib.LinearAlgebra.Dimension.OrzechProperty
import Mathlib.LinearAlgebra.Dimension.Finrank

/-!
# Problem 3.9.5: The Clifford algebra

Let `V` be a finite dimensional complex vector space with a symmetric bilinear form
`(·,·) = B`. The **Clifford algebra** `Cl(V)` is the quotient of the tensor algebra `TV`
by the ideal generated by `v ⊗ v − (v,v)·1`. Equivalently, for a basis `xᵢ` with
`(xᵢ, xⱼ) = aᵢⱼ`, it is generated by the `xᵢ` with relations
`xᵢ xⱼ + xⱼ xᵢ = 2aᵢⱼ`, `xᵢ² = aᵢᵢ`. If `(·,·) = 0`, then `Cl(V) = ⋀ V`.

We model `Cl(V)` as Mathlib's `CliffordAlgebra Q` for the quadratic form
`Q(v) = B(v, v)` (`LinearMap.BilinMap.toQuadraticMap B`). Its defining relation
`ι(v)² = Q(v)` polarises to `ι(v)ι(w) + ι(w)ι(v) = B(v,w) + B(w,v) = 2B(v,w)` when `B`
is symmetric, matching the book's relations with `aᵢⱼ = B(xᵢ, xⱼ)`.

* **(i)** If `B` is nondegenerate then `Cl(V)` is semisimple. If `dim V = 2n` it is a
  matrix algebra, with a single irreducible representation `S` (the spinor module) of
  dimension `2ⁿ`; if `dim V = 2n+1` it is a direct sum of two matrix algebras, with two
  non-isomorphic irreducible representations `S₊, S₋` of dimension `2ⁿ`.
* **(ii)** `Cl(V)` is semisimple iff `B` is nondegenerate. When `B` is degenerate, the
  semisimple quotient `Cl(V) / Rad(Cl(V))` is the (nondegenerate) Clifford algebra of the
  induced form on `V` modulo the radical of `B`.

A "matrix algebra" is phrased as `Module.End ℂ S` for a finite dimensional `S` — the
endomorphism algebra of its `2ⁿ`-dimensional spinor representation, which is exactly the
statement that `S` is the unique irreducible module.

Statement pass: the quadratic form and Clifford algebra are genuinely constructed; the
proofs are left as `sorry`.
-/

namespace Etingof.Problem3_9_5

variable {V : Type*} [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V]
  (B : LinearMap.BilinForm ℂ V)

/-- The quadratic form `Q(v) = (v, v) = B v v` attached to the symmetric bilinear form `B`.
Genuinely constructed via `LinearMap.BilinMap.toQuadraticMap`. -/
noncomputable abbrev quadForm : QuadraticForm ℂ V :=
  LinearMap.BilinMap.toQuadraticMap B

/-- The Clifford algebra `Cl(V)` of the form, as `CliffordAlgebra Q`. -/
abbrev CliffAlg : Type _ := CliffordAlgebra (quadForm B)

/-- `Cl(V)` is finite-dimensional over `ℂ`. Transport the finite basis of `⋀ V` (indexed by
`Finset` of a basis of `V`, `Module.Basis.ExteriorAlgebra`) across the characteristic-≠-2 linear
equivalence `CliffordAlgebra.equivExterior`. This underlies every part of the problem: it makes
`Cl(V)` an Artinian ring, so `IsSemisimpleRing`/Jacobson-radical machinery applies. -/
instance : Module.Finite ℂ (CliffAlg B) := by
  haveI : Invertible (2 : ℂ) := invertibleOfNonzero two_ne_zero
  haveI : Module.Finite ℂ (ExteriorAlgebra ℂ V) :=
    Module.Finite.of_basis (Module.Basis.ExteriorAlgebra (Module.finBasis ℂ V))
  exact Module.Finite.equiv (CliffordAlgebra.equivExterior (quadForm B)).symm

omit [FiniteDimensional ℂ V] in
/-- **Parenthetical.** If the form is zero, `Cl(V)` is the exterior algebra `⋀ V`. -/
theorem cliffordAlgebra_zero_eq_exterior :
    Nonempty (CliffordAlgebra (quadForm (0 : LinearMap.BilinForm ℂ V)) ≃ₐ[ℂ]
      ExteriorAlgebra ℂ V) := by
  -- `ExteriorAlgebra ℂ V` is *defined* as `CliffordAlgebra (0 : QuadraticForm ℂ V)`, so it
  -- suffices to see that the quadratic form of the zero bilinear form is the zero form.
  have hq : quadForm (0 : LinearMap.BilinForm ℂ V) = (0 : QuadraticForm ℂ V) := by
    ext v
    simp [quadForm]
  rw [hq]
  exact ⟨AlgEquiv.refl⟩

/-- **Dickson's semisimplicity criterion (characteristic zero).** A finite-dimensional `ℂ`-algebra
`A` is semisimple as soon as its trace form `(x, y) ↦ tr(L_{xy})` (where `L_z` is left
multiplication by `z`) is nondegenerate.

`A` is Artinian, so its Jacobson radical `J` is a nilpotent ideal. For `x ∈ J` and any `y`, the
element `y * x` again lies in `J`, hence is nilpotent, so `L_{y*x}` is a nilpotent operator and its
trace vanishes. Since `tr(L_{x*y}) = tr(L_x L_y) = tr(L_y L_x) = tr(L_{y*x}) = 0` for every `y`,
nondegeneracy forces `x = 0`; thus `J = 0` and `A` is semisimple. -/
theorem isSemisimpleRing_of_traceForm_nondegenerate
    {A : Type*} [Ring A] [Algebra ℂ A] [Module.Finite ℂ A]
    (hnd : ∀ x : A, (∀ y : A, LinearMap.trace ℂ A (LinearMap.mulLeft ℂ (x * y)) = 0) → x = 0) :
    IsSemisimpleRing A := by
  haveI : IsArtinianRing A := IsArtinianRing.of_finite ℂ A
  rw [IsArtinianRing.isSemisimpleRing_iff_jacobson, eq_bot_iff]
  intro x hx
  rw [Ideal.mem_bot]
  apply hnd
  intro y
  -- Symmetry of the trace form: `tr(L_{x*y}) = tr(L_{y*x})`.
  have hsymm : LinearMap.trace ℂ A (LinearMap.mulLeft ℂ (x * y))
      = LinearMap.trace ℂ A (LinearMap.mulLeft ℂ (y * x)) := by
    rw [LinearMap.mulLeft_mul, LinearMap.mulLeft_mul,
      ← Module.End.mul_eq_comp, ← Module.End.mul_eq_comp, LinearMap.trace_mul_comm]
  rw [hsymm]
  -- `y * x` lies in the (nilpotent) Jacobson radical, so it is a nilpotent element.
  have hyx : y * x ∈ Ring.jacobson A := (Ring.jacobson A).mul_mem_left y hx
  obtain ⟨n, hn⟩ := IsArtinianRing.isNilpotent_jacobson_bot (R := A)
  rw [Ideal.jacobson_bot] at hn
  have hnil : IsNilpotent (y * x) := by
    refine ⟨n, ?_⟩
    have hmem : (y * x) ^ n ∈ (Ring.jacobson A) ^ n := Ideal.pow_mem_pow hyx n
    rw [hn] at hmem
    simpa using hmem
  -- Left multiplication by a nilpotent element is a nilpotent operator, hence has zero trace.
  have hmul : IsNilpotent (LinearMap.mulLeft ℂ (y * x)) :=
    hnil.map (Algebra.lmul ℂ A).toRingHom
  exact (LinearMap.isNilpotent_trace_of_isNilpotent hmul).eq_zero

/-!
### Orthogonal monomial basis of `Cl(V)`

For an orthogonal basis `v` of `V` (with respect to `B`), the `2^N` ordered products
`e S = ∏_{i ∈ S} ι(vᵢ)` (the product taken in increasing order of `i`) form a basis of `Cl(V)`.
Because the basis is orthogonal, the generators satisfy the clean relations
`ι(vᵢ) ι(vⱼ) = - ι(vⱼ) ι(vᵢ)` for `i ≠ j` and `ι(vᵢ)² = B(vᵢ,vᵢ)`, with **no** lower-order
correction terms. This makes left multiplication by `e S` a signed permutation of the monomial
basis, from which `tr(L_{e S})` and the nondegeneracy of the trace form drop out.
-/

section Monomial

variable {N : ℕ} (v : Module.Basis (Fin N) ℂ V)

open CliffordAlgebra in
/-- The Clifford generator `ι(vᵢ)` attached to the `i`-th orthogonal basis vector. -/
noncomputable def gen (i : Fin N) : CliffAlg B := CliffordAlgebra.ι (quadForm B) (v i)

open scoped Classical in
/-- Ordered monomial `e S = ∏_{i ∈ S} ι(vᵢ)`, the product taken in increasing order of `i`. -/
noncomputable def e (S : Finset (Fin N)) : CliffAlg B :=
  ((S.sort (· ≤ ·)).map (gen B v)).prod

@[simp] theorem e_empty : e B v ∅ = 1 := by
  simp [e]

@[simp] theorem e_singleton (i : Fin N) : e B v {i} = gen B v i := by
  simp [e, Finset.sort_singleton]

/-- If `i` is strictly below every element of `S`, then `e (insert i S) = ι(vᵢ) · e S`
(no reordering needed since `i` is the new minimum). -/
theorem e_insert_of_lt {i : Fin N} {S : Finset (Fin N)} (h : ∀ j ∈ S, i < j) :
    e B v (insert i S) = gen B v i * e B v S := by
  have hi : i ∉ S := fun hmem => (lt_irrefl i (h i hmem))
  rw [e, Finset.sort_insert (· ≤ ·) (fun j hj => (h j hj).le) hi, List.map_cons, List.prod_cons, e]

/-- Peeling off the minimum: `e S = ι(v (min S)) · e (S.erase (min S))`. -/
theorem e_minPeel {S : Finset (Fin N)} (hS : S.Nonempty) :
    e B v S = gen B v (S.min' hS) * e B v (S.erase (S.min' hS)) := by
  have hmem : S.min' hS ∈ S := S.min'_mem hS
  have hlt : ∀ j ∈ S.erase (S.min' hS), S.min' hS < j := by
    intro j hj
    rw [Finset.mem_erase] at hj
    exact lt_of_le_of_ne (S.min'_le j hj.2) (Ne.symm hj.1)
  conv_lhs => rw [← Finset.insert_erase hmem]
  exact e_insert_of_lt B v hlt

/-- `ι(vᵢ)² = B(vᵢ,vᵢ)` as a scalar. -/
theorem gen_sq (i : Fin N) :
    gen B v i * gen B v i = algebraMap ℂ (CliffAlg B) (B (v i) (v i)) := by
  unfold gen
  rw [CliffordAlgebra.ι_sq_scalar]
  rfl

/-- For an orthogonal basis, distinct generators anticommute. -/
theorem gen_anticomm (hv : B.IsOrthoᵢ v) {i j : Fin N} (hij : i ≠ j) :
    gen B v i * gen B v j = - (gen B v j * gen B v i) := by
  have h := CliffordAlgebra.ι_mul_ι_add_swap (Q := quadForm B) (v i) (v j)
  have hpolar : QuadraticMap.polar (quadForm B) (v i) (v j) = 0 := by
    rw [LinearMap.BilinMap.polar_toQuadraticMap,
      LinearMap.isOrthoᵢ_def.mp hv i j hij, LinearMap.isOrthoᵢ_def.mp hv j i hij.symm, add_zero]
  rw [hpolar, map_zero] at h
  unfold gen
  exact eq_neg_of_add_eq_zero_left h

/-- On a nondegenerate orthogonal basis, every diagonal entry `B(vᵢ,vᵢ)` is nonzero. -/
theorem diag_ne_zero (hv : B.IsOrthoᵢ v) (hnd : B.Nondegenerate) (i : Fin N) :
    B (v i) (v i) ≠ 0 := by
  intro hz
  refine v.ne_zero i (hnd.1 (v i) ?_)
  intro y
  have hzero : B (v i) = 0 := by
    apply v.ext
    intro j
    rcases eq_or_ne i j with rfl | hij
    · simpa using hz
    · simpa using LinearMap.isOrthoᵢ_def.mp hv i j hij
  rw [hzero, LinearMap.zero_apply]

/-- Each generator is a unit (its inverse is `B(vᵢ,vᵢ)⁻¹ · ι(vᵢ)`). -/
theorem isUnit_gen (hv : B.IsOrthoᵢ v) (hnd : B.Nondegenerate) (i : Fin N) :
    IsUnit (gen B v i) := by
  have ha := diag_ne_zero B v hv hnd i
  refine ⟨⟨gen B v i, (B (v i) (v i))⁻¹ • gen B v i, ?_, ?_⟩, rfl⟩
  · rw [mul_smul_comm, gen_sq, Algebra.smul_def, ← map_mul, inv_mul_cancel₀ ha, map_one]
  · rw [smul_mul_assoc, gen_sq, Algebra.smul_def, ← map_mul, inv_mul_cancel₀ ha, map_one]

open scoped Classical in
/-- The monomial `e S` is a unit (a product of units). -/
theorem isUnit_e (hv : B.IsOrthoᵢ v) (hnd : B.Nondegenerate) (S : Finset (Fin N)) :
    IsUnit (e B v S) := by
  rw [e]
  apply List.prod_isUnit
  intro x hx
  rw [List.mem_map] at hx
  obtain ⟨i, _, rfl⟩ := hx
  exact isUnit_gen B v hv hnd i

open scoped symmDiff

/-- **Generator × monomial reduction.** `ι(vⱼ) · e U` is a scalar multiple of the monomial on
`U ∆ {j}`. Proved by strong induction on `U`: peel the minimum `k` of `U`, and recurse on the
same index `j` with the smaller set `U.erase k` (valid since `j > k`), handling `j < min U` and
`j = min U` directly. Because the basis is orthogonal, no lower-order terms appear. -/
theorem gen_mul_mem (hv : B.IsOrthoᵢ v) (j : Fin N) (U : Finset (Fin N)) :
    gen B v j * e B v U ∈ Submodule.span ℂ {e B v (U ∆ {j})} := by
  induction U using Finset.strongInductionOn with
  | _ U ih =>
    rcases U.eq_empty_or_nonempty with rfl | hU
    · have h0 : (∅ : Finset (Fin N)) ∆ {j} = {j} := by ext a; simp [Finset.mem_symmDiff]
      rw [e_empty, mul_one, h0, e_singleton]
      exact Submodule.mem_span_singleton_self _
    · rcases lt_trichotomy j (U.min' hU) with hjk | hjk | hjk
      · -- `j < min U`: `ι(vⱼ)` prepends directly and `U ∆ {j} = insert j U`.
        have hjnotU : j ∉ U := fun hmem => absurd (U.min'_le j hmem) (not_le.mpr hjk)
        have hlt : ∀ i ∈ U, j < i := fun i hi => lt_of_lt_of_le hjk (U.min'_le i hi)
        have hset : U ∆ {j} = insert j U := by
          ext a
          simp only [Finset.mem_symmDiff, Finset.mem_singleton, Finset.mem_insert]
          constructor
          · rintro (⟨ha, _⟩ | ⟨rfl, _⟩)
            · exact Or.inr ha
            · exact Or.inl rfl
          · rintro (rfl | ha)
            · exact Or.inr ⟨rfl, hjnotU⟩
            · exact Or.inl ⟨ha, fun h => hjnotU (h ▸ ha)⟩
        rw [hset, ← e_insert_of_lt B v hlt]
        exact Submodule.mem_span_singleton_self _
      · -- `j = min U`: `ι(vⱼ)² = B(vⱼ,vⱼ)` collapses and `U ∆ {j} = U.erase j`.
        have hjU : j ∈ U := hjk ▸ U.min'_mem hU
        have hset : U ∆ {j} = U.erase j := by
          ext a
          simp only [Finset.mem_symmDiff, Finset.mem_singleton, Finset.mem_erase]
          constructor
          · rintro (⟨ha, hne⟩ | ⟨rfl, hn⟩)
            · exact ⟨hne, ha⟩
            · exact absurd hjU hn
          · rintro ⟨hne, ha⟩; exact Or.inl ⟨ha, hne⟩
        rw [hset, e_minPeel B v hU, ← hjk, ← mul_assoc, gen_sq, ← Algebra.smul_def]
        exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self _)
      · -- `j > min U =: k`: anticommute past `ι(v k)` and recurse on `U.erase k`.
        set k := U.min' hU with hkdef
        have hkU : k ∈ U := U.min'_mem hU
        have hjne : j ≠ k := ne_of_gt hjk
        obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp
          (ih (U.erase k) (Finset.erase_ssubset hkU))
        have hltW : ∀ i ∈ (U.erase k) ∆ {j}, k < i := by
          intro i hi
          simp only [Finset.mem_symmDiff, Finset.mem_erase, Finset.mem_singleton] at hi
          rcases hi with ⟨⟨hik, hiU⟩, _⟩ | ⟨rfl, _⟩
          · have hle : k ≤ i := U.min'_le i hiU
            exact lt_of_le_of_ne hle (Ne.symm hik)
          · exact hjk
        have hset : insert k ((U.erase k) ∆ {j}) = U ∆ {j} := by
          ext a
          simp only [Finset.mem_insert, Finset.mem_symmDiff, Finset.mem_erase,
            Finset.mem_singleton]
          by_cases hak : a = k <;> by_cases haj : a = j <;> by_cases haU : a ∈ U <;>
            simp_all
        rw [e_minPeel B v hU, ← hkdef, ← mul_assoc, gen_anticomm B v hv hjne, neg_mul,
          mul_assoc, ← hc, mul_smul_comm, ← e_insert_of_lt B v hltW, hset]
        exact Submodule.neg_mem _ (Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self _))

/-- **Monomial × monomial reduction.** `e S · e T` is a scalar multiple of the monomial on
`S ∆ T`. Proved by strong induction on `S` (peel the minimum) using `gen_mul_mem`. -/
theorem e_mul_mem (hv : B.IsOrthoᵢ v) (S T : Finset (Fin N)) :
    e B v S * e B v T ∈ Submodule.span ℂ {e B v (S ∆ T)} := by
  induction S using Finset.strongInductionOn with
  | _ S ih =>
    rcases S.eq_empty_or_nonempty with rfl | hS
    · have h0 : (∅ : Finset (Fin N)) ∆ T = T := by ext a; simp [Finset.mem_symmDiff]
      rw [e_empty, one_mul, h0]
      exact Submodule.mem_span_singleton_self _
    · set k := S.min' hS with hkdef
      have hkS : k ∈ S := S.min'_mem hS
      obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp
        (ih (S.erase k) (Finset.erase_ssubset hkS))
      have hset : ((S.erase k) ∆ T) ∆ {k} = S ∆ T := by
        ext a
        simp only [Finset.mem_symmDiff, Finset.mem_erase, Finset.mem_singleton]
        by_cases hak : a = k <;> by_cases haS : a ∈ S <;> by_cases haT : a ∈ T <;>
          simp_all [hkS]
      have hg := gen_mul_mem B v hv k ((S.erase k) ∆ T)
      rw [hset] at hg
      rw [e_minPeel B v hS, ← hkdef, mul_assoc, ← hc, mul_smul_comm]
      exact Submodule.smul_mem _ _ hg

end Monomial

section CliffBasis

variable {N : ℕ} (v : Module.Basis (Fin N) ℂ V)

open scoped symmDiff

/-- The monomials `e S` span `Cl(V)`. Every element reduces to a linear combination of ordered
monomials: the span is a subalgebra (closed under multiplication by `e_mul_mem`) containing every
generator `ι(vᵢ) = e {i}`, hence all of `Cl(V)` by `CliffordAlgebra.induction`. -/
theorem span_e_eq_top (hv : B.IsOrthoᵢ v) :
    Submodule.span ℂ (Set.range (e B v)) = ⊤ := by
  set W := Submodule.span ℂ (Set.range (e B v)) with hWdef
  have hmem : ∀ S, e B v S ∈ W := fun S => Submodule.subset_span ⟨S, rfl⟩
  have h1 : (1 : CliffAlg B) ∈ W := e_empty B v ▸ hmem ∅
  have hbmul : ∀ S T, e B v S * e B v T ∈ W := fun S T =>
    Submodule.span_mono (by rintro _ rfl; exact ⟨S ∆ T, rfl⟩) (e_mul_mem B v hv S T)
  have hWmul : ∀ x ∈ W, ∀ y ∈ W, x * y ∈ W := by
    have hle : W * W ≤ W := by
      rw [hWdef, Submodule.span_mul_span, Submodule.span_le]
      rintro _ ⟨_, ⟨S, rfl⟩, _, ⟨T, rfl⟩, rfl⟩
      exact hbmul S T
    exact fun x hx y hy => hle (Submodule.mul_mem_mul hx hy)
  rw [eq_top_iff]
  rintro x -
  induction x using CliffordAlgebra.induction with
  | algebraMap r => rw [Algebra.algebraMap_eq_smul_one]; exact W.smul_mem r h1
  | ι w =>
      have hexp : CliffordAlgebra.ι (quadForm B) w = ∑ i, v.repr w i • gen B v i := by
        conv_lhs => rw [← v.sum_repr w]
        rw [map_sum]; simp only [map_smul, gen]
      rw [hexp]
      exact W.sum_mem (fun i _ => W.smul_mem _ (e_singleton B v i ▸ hmem {i}))
  | mul a b ha hb => exact hWmul a ha b hb
  | add a b ha hb => exact W.add_mem ha hb

include v in
/-- `Cl(V)` has dimension `2^N` over `ℂ`: transport the exterior-algebra basis (indexed by
`Finset (Fin N)`) across `CliffordAlgebra.equivExterior`. -/
theorem finrank_cliffAlg : Module.finrank ℂ (CliffAlg B) = 2 ^ N := by
  haveI : Invertible (2 : ℂ) := invertibleOfNonzero two_ne_zero
  rw [(CliffordAlgebra.equivExterior (quadForm B)).finrank_eq,
    Module.finrank_eq_card_basis (Module.Basis.ExteriorAlgebra v),
    Fintype.card_finset, Fintype.card_fin]

/-- The `2^N` monomials `e S` form a basis of `Cl(V)` (spanning family of the right cardinality). -/
noncomputable def cliffBasis (hv : B.IsOrthoᵢ v) :
    Module.Basis (Finset (Fin N)) ℂ (CliffAlg B) :=
  basisOfTopLeSpanOfCardEqFinrank (e B v) (span_e_eq_top B v hv).ge
    (by rw [Fintype.card_finset, Fintype.card_fin, finrank_cliffAlg B v])

@[simp] theorem cliffBasis_apply (hv : B.IsOrthoᵢ v) (S : Finset (Fin N)) :
    cliffBasis B v hv S = e B v S := by
  simp only [cliffBasis, coe_basisOfTopLeSpanOfCardEqFinrank]

end CliffBasis

section TraceForm

variable {N : ℕ} (v : Module.Basis (Fin N) ℂ V)

open scoped symmDiff

/-- Left multiplication is `ℂ`-linear in the multiplier: `L_{c·z} = c·L_z`. -/
theorem mulLeft_smul (c : ℂ) (z : CliffAlg B) :
    LinearMap.mulLeft ℂ (c • z) = c • LinearMap.mulLeft ℂ z := by
  ext w; simp [smul_mul_assoc]

/-- **Trace of `L_{e R}`.** Left multiplication by the monomial `e R` permutes the monomial basis
`e T ↦ ± scalar · e_{R ∆ T}`, so it has a nonzero diagonal entry only when `R ∆ T = T`, i.e.
`R = ∅`. Hence `tr(L_{e R}) = 2^N` if `R = ∅` and `0` otherwise. -/
theorem tr_mulLeft_e (hv : B.IsOrthoᵢ v) (R : Finset (Fin N)) :
    LinearMap.trace ℂ (CliffAlg B) (LinearMap.mulLeft ℂ (e B v R))
      = if R = ∅ then (2 ^ N : ℂ) else 0 := by
  classical
  have htr : Matrix.trace (LinearMap.toMatrix (cliffBasis B v hv) (cliffBasis B v hv)
      (LinearMap.mulLeft ℂ (e B v R)))
      = ∑ T, (cliffBasis B v hv).repr (e B v R * e B v T) T := by
    simp only [Matrix.trace, Matrix.diag, LinearMap.toMatrix_apply, LinearMap.mulLeft_apply,
      cliffBasis_apply]
  rw [LinearMap.trace_eq_matrix_trace ℂ (cliffBasis B v hv), htr]
  by_cases hR : R = ∅
  · subst hR
    rw [if_pos rfl]
    have hone : ∀ T : Finset (Fin N),
        (cliffBasis B v hv).repr (e B v ∅ * e B v T) T = 1 := by
      intro T
      rw [e_empty, one_mul, ← cliffBasis_apply B v hv T, Module.Basis.repr_self_apply, if_pos rfl]
    rw [Finset.sum_congr rfl (fun T _ => hone T), Finset.sum_const, Finset.card_univ,
      Fintype.card_finset, Fintype.card_fin, nsmul_eq_mul, mul_one, Nat.cast_pow, Nat.cast_ofNat]
  · rw [if_neg hR]
    refine Finset.sum_eq_zero (fun T _ => ?_)
    obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp (e_mul_mem B v hv R T)
    rw [← hc, ← cliffBasis_apply B v hv (R ∆ T), map_smul, Finsupp.smul_apply,
      Module.Basis.repr_self_apply, if_neg, smul_zero]
    intro h
    exact hR (by rw [← Finset.bot_eq_empty]; exact symmDiff_eq_right.mp h)

/-- **Off-diagonal trace form vanishes.** For `S ≠ T`, `tr(L_{e S · e T}) = 0`, because
`e S · e T` is a scalar multiple of `e_{S ∆ T}` with `S ∆ T ≠ ∅`. -/
theorem tr_mulLeft_e_mul_of_ne (hv : B.IsOrthoᵢ v) {S T : Finset (Fin N)} (hST : S ≠ T) :
    LinearMap.trace ℂ (CliffAlg B) (LinearMap.mulLeft ℂ (e B v S * e B v T)) = 0 := by
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp (e_mul_mem B v hv S T)
  rw [← hc, mulLeft_smul, map_smul, tr_mulLeft_e B v hv, if_neg, smul_zero]
  intro h
  exact hST (symmDiff_eq_bot.mp (Finset.bot_eq_empty ▸ h))

/-- The diagonal trace form value `tr(L_{e T · e T})` is nonzero: `e T` is a unit, so `e T · e T`
is a unit, hence `tr(L_{e T · e T}) = c · 2^N` with `c ≠ 0`. -/
theorem tr_mulLeft_e_mul_self_ne_zero (hv : B.IsOrthoᵢ v) (hnd : B.Nondegenerate)
    (T : Finset (Fin N)) :
    LinearMap.trace ℂ (CliffAlg B) (LinearMap.mulLeft ℂ (e B v T * e B v T)) ≠ 0 := by
  haveI : Nontrivial (CliffAlg B) :=
    Module.nontrivial_of_finrank_pos (by rw [finrank_cliffAlg B v]; exact pow_pos (by norm_num) N)
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp (e_mul_mem B v hv T T)
  have hunit : IsUnit (e B v T * e B v T) :=
    (isUnit_e B v hv hnd T).mul (isUnit_e B v hv hnd T)
  have hcne : c ≠ 0 := by
    rintro rfl
    rw [zero_smul] at hc
    exact hunit.ne_zero hc.symm
  have hTT : T ∆ T = (∅ : Finset (Fin N)) := by rw [symmDiff_self, Finset.bot_eq_empty]
  rw [← hc, mulLeft_smul, map_smul, tr_mulLeft_e B v hv, if_pos hTT, smul_eq_mul]
  exact mul_ne_zero hcne (pow_ne_zero N two_ne_zero)

end TraceForm

/-- **Problem 3.9.5(i), semisimplicity.** If `B` is nondegenerate then `Cl(V)` is a
semisimple ring.

By Dickson's criterion (`isSemisimpleRing_of_traceForm_nondegenerate`) it suffices that the trace
form of `Cl(V)` is nondegenerate. That is the content of the spinor construction from the book: a
direct computation on the `2^{dim V}` monomial basis `∏_{i∈S} ι(bᵢ)` shows `tr(L_{e_S e_T})` is a
nonzero multiple of `∏` of the pairings `B` exactly when `S = T`, which is nondegenerate precisely
when `B` is. -/
theorem isSemisimpleRing_of_nondegenerate
    (hsymm : ∀ x y, B x y = B y x) (hnd : B.Nondegenerate) :
    IsSemisimpleRing (CliffAlg B) := by
  apply isSemisimpleRing_of_traceForm_nondegenerate
  -- Remaining: the Clifford trace form is nondegenerate when `B` is. Tracked separately (the
  -- monomial-basis / spinor computation).
  sorry

/-- **Problem 3.9.5(i), even case.** If `B` is nondegenerate and `dim V = 2n`, then
`Cl(V)` is a matrix algebra: it is isomorphic to `End(S)` for a `2ⁿ`-dimensional space
`S`, the unique (spinor) irreducible representation. -/
theorem even_isMatrixAlgebra
    (hsymm : ∀ x y, B x y = B y x) (hnd : B.Nondegenerate)
    (n : ℕ) (hdim : Module.finrank ℂ V = 2 * n) :
    ∃ (S : Type) (_ : AddCommGroup S) (_ : Module ℂ S),
      Module.finrank ℂ S = 2 ^ n ∧ Nonempty (CliffAlg B ≃ₐ[ℂ] Module.End ℂ S) := by
  sorry

/-- **Problem 3.9.5(i), odd case.** If `B` is nondegenerate and `dim V = 2n+1`, then
`Cl(V)` is a direct sum of two matrix algebras: `End(S) × End(S)` with `dim S = 2ⁿ`. The
two factors are the two non-isomorphic irreducible representations `S₊, S₋`. -/
theorem odd_isSumMatrixAlgebra
    (hsymm : ∀ x y, B x y = B y x) (hnd : B.Nondegenerate)
    (n : ℕ) (hdim : Module.finrank ℂ V = 2 * n + 1) :
    ∃ (S : Type) (_ : AddCommGroup S) (_ : Module ℂ S),
      Module.finrank ℂ S = 2 ^ n ∧
      Nonempty (CliffAlg B ≃ₐ[ℂ] (Module.End ℂ S × Module.End ℂ S)) := by
  sorry

omit [FiniteDimensional ℂ V] in
/-- **Problem 3.9.5(ii), forward direction.** If `B` is degenerate then `Cl(V)` is *not* a
semisimple ring.

Proof sketch (elementary, no spinor construction needed). Degeneracy gives a nonzero vector `v`
in the radical of `B` (`∀ w, B v w = 0`). Set `a := ι v ∈ Cl(V)`. Then:
* `a * a = ι v * ι v = Q v = B v v = 0`;
* `a` anticommutes with every `ι w`, since `polar Q v w = B v w + B w v = 0`;
* consequently `a * r = involute r * a` for all `r` (grade involution, by Clifford induction),
  hence `a * r * a = involute r * (a * a) = 0`.

For every `y`, `(a*y)^2 = a*y*a*y = (a*y*a)*y = 0`, so `1 + a*y` is a unit with inverse `1 - a*y`.
By `Ideal.mem_jacobson_bot` this puts `a` in the Jacobson radical. But `a = ι v ≠ 0` (the map `ι`
is injective in characteristic `≠ 2`, via `CliffordAlgebra.equivExterior`), while a semisimple ring
has trivial Jacobson radical (`IsSemisimpleRing.jacobson_eq_bot`) — contradiction. -/
theorem not_isSemisimpleRing_of_degenerate
    (hsymm : ∀ x y, B x y = B y x) (hdeg : ¬ B.Nondegenerate) :
    ¬ IsSemisimpleRing (CliffAlg B) := by
  classical
  intro hss
  -- A nonzero radical vector `v`.
  obtain ⟨v, hv0, hvne⟩ : ∃ v : V, (∀ w, B v w = 0) ∧ v ≠ 0 := by
    rw [LinearMap.BilinForm.Nondegenerate, LinearMap.Nondegenerate, not_and_or] at hdeg
    rcases hdeg with h | h
    · rw [LinearMap.SeparatingLeft] at h
      push_neg at h
      obtain ⟨v, hv, hne⟩ := h
      exact ⟨v, hv, hne⟩
    · rw [LinearMap.SeparatingRight] at h
      push_neg at h
      obtain ⟨v, hv, hne⟩ := h
      exact ⟨v, fun w => (hsymm v w).trans (hv w), hne⟩
  set Q := quadForm B with hQ
  set a : CliffAlg B := CliffordAlgebra.ι Q v with ha
  -- `a * a = 0`.
  have haa : a * a = 0 := by
    have hQv : Q v = 0 := by
      simp only [hQ, quadForm, LinearMap.BilinMap.toQuadraticMap_apply]
      exact hv0 v
    rw [ha, CliffordAlgebra.ι_sq_scalar, hQv, map_zero]
  -- `a` anticommutes with every generator.
  have hanti : ∀ w, a * CliffordAlgebra.ι Q w + CliffordAlgebra.ι Q w * a = 0 := by
    intro w
    have hpolar : QuadraticMap.polar Q v w = 0 := by
      rw [hQ, LinearMap.BilinMap.polar_toQuadraticMap, hv0 w, hsymm w v, hv0 w, add_zero]
    rw [ha, CliffordAlgebra.ι_mul_ι_add_swap, hpolar, map_zero]
  -- Grade-involution intertwining: `a * r = involute r * a`.
  have hkey : ∀ r : CliffAlg B, a * r = CliffordAlgebra.involute r * a := by
    intro r
    induction r using CliffordAlgebra.induction with
    | algebraMap s => rw [AlgHom.commutes, Algebra.commutes]
    | ι w =>
        rw [CliffordAlgebra.involute_ι, neg_mul]
        exact eq_neg_of_add_eq_zero_left (hanti w)
    | mul x y hx hy => rw [← mul_assoc, hx, mul_assoc, hy, ← mul_assoc, map_mul]
    | add x y hx hy => rw [mul_add, hx, hy, map_add, add_mul]
  -- Hence `a * r * a = 0` for all `r`.
  have hara : ∀ r : CliffAlg B, a * r * a = 0 := by
    intro r
    rw [hkey r, mul_assoc, haa, mul_zero]
  -- `a` lies in the Jacobson radical: it belongs to every maximal left ideal `M`. Indeed if
  -- `a ∉ M`, then `M ⊔ span{a} = ⊤` by maximality, so `1 = m + r*a` with `m ∈ M`; then
  -- `m = 1 - r*a` is a unit (inverse `1 + r*a`, since `(r*a)² = r*(a*r*a) = 0`), forcing `M = ⊤`.
  have hmem : a ∈ Ring.jacobson (CliffAlg B) := by
    rw [Ring.jacobson_eq_sInf_isMaximal]
    refine Ideal.mem_sInf.mpr (fun {M} hM => ?_)
    rw [Set.mem_setOf_eq] at hM
    by_contra haM
    have hlt : M < M ⊔ Ideal.span {a} := by
      refine lt_of_le_of_ne le_sup_left (fun heq => haM ?_)
      have hain : a ∈ M ⊔ Ideal.span {a} :=
        Submodule.mem_sup_right (Ideal.mem_span_singleton_self a)
      rwa [← heq] at hain
    have hsup : M ⊔ Ideal.span {a} = ⊤ := (Ideal.isMaximal_def.1 hM).2 _ hlt
    have h1 : (1 : CliffAlg B) ∈ M ⊔ Ideal.span {a} := hsup ▸ Submodule.mem_top
    rw [Submodule.mem_sup] at h1
    obtain ⟨m, hmM, n, hn, hmn⟩ := h1
    obtain ⟨r, hr⟩ := Ideal.mem_span_singleton'.mp hn
    have hm_eq : m = 1 - r * a := by
      rw [← hr] at hmn; exact eq_sub_of_add_eq hmn
    have h0 : r * a * r * a = 0 := by
      have e : r * a * r * a = r * (a * r * a) := by noncomm_ring
      rw [e, hara r, mul_zero]
    have hunit : IsUnit m := by
      rw [hm_eq]
      have hval : (1 - r * a) * (1 + r * a) = 1 := by
        have e : (1 - r * a) * (1 + r * a) = 1 - r * a * r * a := by noncomm_ring
        rw [e, h0, sub_zero]
      have hinv : (1 + r * a) * (1 - r * a) = 1 := by
        have e : (1 + r * a) * (1 - r * a) = 1 - r * a * r * a := by noncomm_ring
        rw [e, h0, sub_zero]
      exact ⟨⟨1 - r * a, 1 + r * a, hval, hinv⟩, rfl⟩
    exact hM.ne_top (Ideal.eq_top_of_isUnit_mem M hmM hunit)
  -- But `a = ι v ≠ 0`, contradicting triviality of the radical of a semisimple ring.
  have ha_ne : a ≠ 0 := by
    rw [ha]
    intro h0
    apply hvne
    haveI : Invertible (2 : ℂ) := invertibleOfNonzero (by norm_num)
    have himg : (CliffordAlgebra.equivExterior Q) (CliffordAlgebra.ι Q v)
        = ExteriorAlgebra.ι ℂ v :=
      CliffordAlgebra.changeForm_ι CliffordAlgebra.changeForm.associated_neg_proof v
    have : ExteriorAlgebra.ι ℂ v = 0 := by rw [← himg, h0, map_zero]
    exact (ExteriorAlgebra.ι_eq_zero_iff (R := ℂ) v).1 this
  have hjac : Ring.jacobson (CliffAlg B) = ⊥ := IsSemisimpleRing.jacobson_eq_bot (CliffAlg B)
  rw [hjac, Ideal.mem_bot] at hmem
  exact ha_ne hmem

/-- **Problem 3.9.5(ii).** `Cl(V)` is semisimple if and only if `B` is nondegenerate.

The forward direction is `not_isSemisimpleRing_of_degenerate` (contrapositive); the reverse is
`isSemisimpleRing_of_nondegenerate` (part (i), the spinor construction). -/
theorem isSemisimpleRing_iff_nondegenerate (hsymm : ∀ x y, B x y = B y x) :
    IsSemisimpleRing (CliffAlg B) ↔ B.Nondegenerate := by
  refine ⟨fun hss => ?_, fun hnd => isSemisimpleRing_of_nondegenerate B hsymm hnd⟩
  by_contra hdeg
  exact not_isSemisimpleRing_of_degenerate B hsymm hdeg hss

/-- **Problem 3.9.5(ii), the degenerate quotient.** If `B` is degenerate, the semisimple
quotient `Cl(V) / Rad(Cl(V))` is the Clifford algebra of a nondegenerate form `B'` on the
quotient of `V` by the radical of `B`. Phrased as: there is a nondegenerate symmetric form
`B'` on some space `W` together with a surjective algebra map `Cl(V) → Cl(W, B')` whose
kernel is the Jacobson radical. -/
theorem radicalQuotient_isClifford_of_degenerate
    (hsymm : ∀ x y, B x y = B y x) (hdeg : ¬ B.Nondegenerate) :
    ∃ (W : Type) (_ : AddCommGroup W) (_ : Module ℂ W) (B' : LinearMap.BilinForm ℂ W),
      (∀ x y, B' x y = B' y x) ∧ B'.Nondegenerate ∧
      ∃ φ : CliffAlg B →ₐ[ℂ] CliffordAlgebra (quadForm B'),
        Function.Surjective φ ∧ RingHom.ker φ.toRingHom = Ring.jacobson (CliffAlg B) := by
  sorry

end Etingof.Problem3_9_5
