import EtingofRepresentationTheory.Chapter3.Problem3_9_1
import EtingofRepresentationTheory.Chapter2.Definition2_3_8
import Mathlib.Data.Complex.Basic
import Mathlib.RingTheory.MvPolynomial.Basic
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.Algebra.FreeAlgebra
import Mathlib.Algebra.RingQuot
import Mathlib.LinearAlgebra.FiniteDimensional.Defs
import Mathlib.LinearAlgebra.Pi
import Mathlib.Algebra.Algebra.Bilinear
import Mathlib.Algebra.Module.Submodule.Lattice

/-!
# Problem 3.9.2: `Ext¹` for polynomial algebras and algebras with zero multiplication

**(a)** Let `A = ℂ[x₁, …, xₙ]` and let `Vₐ, V_b` be the 1-dimensional representations in which
`xᵢ` acts by `aᵢ`, `bᵢ` respectively. Compute `Ext¹(Vₐ, V_b)` and classify the 2-dimensional
representations of `A`.

**(b)** Let `B = ℂ⟨x₁, …, xₙ⟩ / (xᵢxⱼ = 0)`. Show that for `n > 1`, `B` has infinitely many
nonisomorphic indecomposable representations.

We model the 1-dimensional representation `Vₐ` as the quotient `A ⧸ 𝔪ₐ` by the maximal
ideal `𝔪ₐ = (x₁ − a₁, …, xₙ − aₙ)`. This is a genuine `A`-module and `ℂ`-module with the
scalar tower `ℂ → A → A⧸𝔪ₐ`, on which `xᵢ` acts by the scalar `aᵢ`, so it fits the
`Ext¹` framework of Problem 3.9.1 (`Etingof.Problem3_9_1.Ext1`). The convention there is that
`Ext1 k A V W` classifies extensions `0 → V → U → W → 0`, i.e. `Ext¹(W, V)`; so the book's
`Ext¹(Vₐ, V_b)` — extensions `0 → V_b → U → Vₐ → 0` — is `Ext1 ℂ A V_b Vₐ`.

The answer to (a): `Ext¹(Vₐ, V_b) ≅ ℂⁿ` if `a = b` and `= 0` if `a ≠ b`. Every 2-dimensional
representation is an extension of two 1-dimensional ones, so is classified by the pair
`(a, b)` together with a class in `Ext¹(Vₐ, V_b)`.

For (b) the algebra `B` is the free algebra `ℂ⟨x₁,…,xₙ⟩` modulo the two-sided relations
`xᵢxⱼ = 0`, constructed as a `RingQuot`.

Statement pass: the modules and algebras are genuinely constructed; proofs are `sorry`.
-/

namespace Etingof.Problem3_9_2

open Etingof.Problem3_9_1 (Ext1)

/-! ## Part (a): the polynomial algebra `ℂ[x₁, …, xₙ]` -/

/-- The polynomial algebra `A = ℂ[x₁, …, xₙ]`. -/
abbrev polyAlg (n : ℕ) : Type := MvPolynomial (Fin n) ℂ

/-- The maximal ideal `𝔪ₐ = (x₁ − a₁, …, xₙ − aₙ)` of `ℂ[x₁, …, xₙ]` at the point `a`. -/
noncomputable def maxIdeal {n : ℕ} (a : Fin n → ℂ) : Ideal (polyAlg n) :=
  Ideal.span (Set.range fun i => MvPolynomial.X i - MvPolynomial.C (a i))

/-- The 1-dimensional representation `Vₐ`, in which `xᵢ` acts by the scalar `aᵢ`, modelled as
the quotient `A ⧸ 𝔪ₐ`. A genuine `A`-module and `ℂ`-module with scalar tower. -/
abbrev Vrep {n : ℕ} (a : Fin n → ℂ) : Type := polyAlg n ⧸ maxIdeal a

/-- **Problem 3.9.2(a), equal weights.** `Ext¹(Vₐ, Vₐ) ≅ ℂⁿ`: self-extensions of the
1-dimensional rep are classified by the `n` "nilpotent directions" `xᵢ`. -/
theorem ext1_self {n : ℕ} (a : Fin n → ℂ) :
    Nonempty (Ext1 ℂ (polyAlg n) (Vrep a) (Vrep a) ≃ₗ[ℂ] (Fin n → ℂ)) := by
  sorry

/-- **Problem 3.9.2(a), distinct weights.** `Ext¹(Vₐ, V_b) = 0` when `a ≠ b`: any extension
splits because some `xⱼ` has distinct eigenvalues `aⱼ ≠ bⱼ`. -/
theorem ext1_subsingleton_of_ne {n : ℕ} (a b : Fin n → ℂ) (hab : a ≠ b) :
    Subsingleton (Ext1 ℂ (polyAlg n) (Vrep b) (Vrep a)) := by
  sorry

/-- **Problem 3.9.2(a), classification of 2-dimensional representations.** Every
2-dimensional representation `U` of `ℂ[x₁, …, xₙ]` is an extension of two 1-dimensional
representations: there is a pair of weights `a, b` and a subrepresentation `S ≅ V_b` with
quotient `U ⧸ S ≅ Vₐ`. Combined with the `Ext¹` computation above, this classifies the
2-dimensional representations. -/
theorem two_dim_is_extension {n : ℕ} (U : Type)
    [AddCommGroup U] [Module ℂ U] [Module (polyAlg n) U] [IsScalarTower ℂ (polyAlg n) U]
    [FiniteDimensional ℂ U] (hdim : Module.finrank ℂ U = 2) :
    ∃ (a b : Fin n → ℂ) (S : Submodule (polyAlg n) U),
      Nonempty (S ≃ₗ[polyAlg n] Vrep b) ∧ Nonempty ((U ⧸ S) ≃ₗ[polyAlg n] Vrep a) := by
  sorry

/-! ## Part (b): the algebra with zero multiplication `B = ℂ⟨x₁,…,xₙ⟩/(xᵢxⱼ)` -/

/-- The defining relations of `B`: every product `xᵢ xⱼ` of generators is zero. -/
inductive BRel (n : ℕ) : FreeAlgebra ℂ (Fin n) → FreeAlgebra ℂ (Fin n) → Prop
  | mul (i j : Fin n) :
      BRel n (FreeAlgebra.ι ℂ i * FreeAlgebra.ι ℂ j) 0

/-- The algebra `B = ℂ⟨x₁, …, xₙ⟩ / (xᵢxⱼ = 0)`, the free algebra on `n` generators modulo
the two-sided ideal generated by all products of generators. Genuinely constructed via
`RingQuot`. -/
abbrev zeroMulAlg (n : ℕ) : Type := RingQuot (BRel n)

/-! ### The family of indecomposable `B`-modules

For `n > 1` we exhibit a family `Mₖ = ℂ²` (`k ∈ ℕ`) of pairwise nonisomorphic indecomposable
`B`-modules. On `Mₖ` the generator `x₀` acts by the square-zero nilpotent `N : (a,b) ↦ (0,a)`,
`x₁` acts by `k • N`, and the remaining `xᵢ` act by `0`. Every product of generators acts by
`N² = 0`, so this is a genuine `B = zeroMulAlg n`-module. The socle line `ℂ·v` (with
`v = (0,1) = N u`, `u = (1,0)`) sits inside every nonzero submodule, forcing indecomposability;
the scalar `k` (the ratio of the `x₁`- and `x₀`-actions on the socle) is preserved by any module
isomorphism, forcing pairwise non-isomorphism.

The carriers `Cyc n k` are per-index type copies of `ℂ²`, so each index `k` carries its own
`B`-action as a canonical instance (distinct types keep the two module structures unambiguous
when comparing `Mₖ` and `Mₗ`). -/

/-- The distinguished socle vector `v = (0,1) ∈ ℂ²` (raw). -/
def socleVecR : Fin 2 → ℂ := ![0, 1]

/-- The cyclic vector `u = (1,0) ∈ ℂ²` (raw), with `N u = v`. -/
def cycVecR : Fin 2 → ℂ := ![1, 0]

/-- The square-zero nilpotent `N : (a,b) ↦ (0,a)` on `ℂ²`. -/
noncomputable def nilOpR : Module.End ℂ (Fin 2 → ℂ) where
  toFun m := m 0 • socleVecR
  map_add' a b := by simp [add_smul]
  map_smul' c m := by simp [mul_smul]

@[simp] lemma nilOpR_apply (m : Fin 2 → ℂ) : nilOpR m = m 0 • socleVecR := rfl

lemma nilOpR_sq : nilOpR * nilOpR = (0 : Module.End ℂ (Fin 2 → ℂ)) := by
  ext m i
  fin_cases i <;> simp [Module.End.mul_apply, nilOpR_apply, socleVecR]

/-- The carrier of the `k`-th module: a type copy of `ℂ²` so each index carries its own action. -/
def Cyc (n k : ℕ) : Type := Fin 2 → ℂ

instance (n k : ℕ) : AddCommGroup (Cyc n k) := inferInstanceAs (AddCommGroup (Fin 2 → ℂ))
noncomputable instance (n k : ℕ) : Module ℂ (Cyc n k) := inferInstanceAs (Module ℂ (Fin 2 → ℂ))
instance (n k : ℕ) : Nontrivial (Cyc n k) := inferInstanceAs (Nontrivial (Fin 2 → ℂ))

/-- The socle vector `v` inside `Cyc n k`. -/
def socleVec (n k : ℕ) : Cyc n k := (socleVecR : Fin 2 → ℂ)

/-- The cyclic vector `u` inside `Cyc n k`. -/
def cycVec (n k : ℕ) : Cyc n k := (cycVecR : Fin 2 → ℂ)

/-- The square-zero nilpotent `N` on `Cyc n k`. -/
noncomputable def nilOp (n k : ℕ) : Module.End ℂ (Cyc n k) := nilOpR

@[simp] lemma nilOp_apply (n k : ℕ) (m : Cyc n k) : nilOp n k m = m 0 • socleVec n k := rfl

lemma nilOp_sq (n k : ℕ) : nilOp n k * nilOp n k = (0 : Module.End ℂ (Cyc n k)) := nilOpR_sq

lemma socleVec_ne_zero (n k : ℕ) : socleVec n k ≠ (0 : Cyc n k) := by
  have h : (socleVecR : Fin 2 → ℂ) ≠ 0 := by
    intro h; simpa [socleVecR] using congrFun h 1
  exact h

/-- The weight of generator `xᵢ` in the `k`-th module: `1` for `i = 0`, `k` for `i = 1`, and `0`
otherwise. -/
def wt (k : ℕ) {n : ℕ} (i : Fin n) : ℂ :=
  if (i : ℕ) = 0 then 1 else if (i : ℕ) = 1 then (k : ℂ) else 0

@[simp] lemma wt_zero (k : ℕ) {n : ℕ} [NeZero n] : wt k (0 : Fin n) = 1 := by simp [wt]

lemma wt_one (k : ℕ) {n : ℕ} [NeZero n] (hn : 1 < n) : wt k (1 : Fin n) = (k : ℂ) := by
  have h1 : ((1 : Fin n) : ℕ) = 1 := by rw [Fin.val_one']; exact Nat.mod_eq_of_lt hn
  unfold wt
  rw [h1]
  norm_num

/-- The image of generator `xᵢ` in `End (Cyc n k)` for the `k`-th module: `wt k i • N`. -/
noncomputable def genImg (n k : ℕ) (i : Fin n) : Module.End ℂ (Cyc n k) := wt k i • nilOp n k

lemma genImg_mul (n k : ℕ) (i j : Fin n) : genImg n k i * genImg n k j = 0 := by
  simp only [genImg, smul_mul_assoc, mul_smul_comm, nilOp_sq, smul_zero]

/-- The `k`-th representation of the free algebra `ℂ⟨x₁,…,xₙ⟩` on `Cyc n k`. -/
noncomputable def freeRep (n k : ℕ) :
    FreeAlgebra ℂ (Fin n) →ₐ[ℂ] Module.End ℂ (Cyc n k) :=
  FreeAlgebra.lift ℂ (genImg n k)

lemma freeRep_rel (n k : ℕ) : ∀ ⦃a b⦄, BRel n a b → freeRep n k a = freeRep n k b := by
  intro a b hab
  cases hab with
  | mul i j =>
    simp only [freeRep, map_mul, map_zero, FreeAlgebra.lift_ι_apply]
    exact genImg_mul n k i j

/-- The `k`-th representation of `B = zeroMulAlg n` on `Cyc n k`. -/
noncomputable def rep (n k : ℕ) : zeroMulAlg n →ₐ[ℂ] Module.End ℂ (Cyc n k) :=
  RingQuot.liftAlgHom ℂ ⟨freeRep n k, freeRep_rel n k⟩

/-- The generator `xᵢ ∈ B`. -/
noncomputable def gen (n : ℕ) (i : Fin n) : zeroMulAlg n :=
  RingQuot.mkAlgHom ℂ (BRel n) (FreeAlgebra.ι ℂ i)

lemma rep_gen (n k : ℕ) (i : Fin n) : rep n k (gen n i) = wt k i • nilOp n k := by
  simp only [rep, gen, RingQuot.liftAlgHom_mkAlgHom_apply, freeRep, FreeAlgebra.lift_ι_apply,
    genImg]

/-- The `B`-module structure on `Cyc n k` given by the `k`-th representation. -/
noncomputable instance instModuleCyc (n k : ℕ) : Module (zeroMulAlg n) (Cyc n k) :=
  Module.compHom (Cyc n k) (rep n k).toRingHom

/-- Under the `k`-th module structure, `algebraMap ℂ B c` acts by the base scalar `c`. -/
lemma rep_algebraMap_smul (n k : ℕ) (c : ℂ) (y : Cyc n k) :
    rep n k (algebraMap ℂ (zeroMulAlg n) c) y = c • y := by
  rw [AlgHom.commutes, Module.algebraMap_end_apply]

/-- **Problem 3.9.2(b).** For `n > 1`, the algebra `B` has infinitely many nonisomorphic
indecomposable representations: there is a family `M : ℕ → Type` of pairwise nonisomorphic
indecomposable `B`-modules. -/
theorem infinitely_many_indecomposables {n : ℕ} (hn : 1 < n) :
    ∃ (M : ℕ → Type) (_ : ∀ k, AddCommGroup (M k)) (_ : ∀ k, Module (zeroMulAlg n) (M k)),
      (∀ k, Etingof.IsIndecomposable (zeroMulAlg n) (M k)) ∧
      (∀ k l, Nonempty ((M k) ≃ₗ[zeroMulAlg n] (M l)) → k = l) := by
  haveI : NeZero n := ⟨by omega⟩
  refine ⟨fun k => Cyc n k, fun _ => inferInstance, fun _ => inferInstance, ?_, ?_⟩
  · -- Each `Mₖ` is indecomposable.
    intro k
    -- A `B`-submodule is closed under the base scalar action of `ℂ`.
    have csmul_mem : ∀ (c : ℂ) (x : Cyc n k) (W : Submodule (zeroMulAlg n) (Cyc n k)),
        x ∈ W → c • x ∈ W := by
      intro c x W hx
      have hc : c • x = (algebraMap ℂ (zeroMulAlg n) c) • x := (rep_algebraMap_smul n k c x).symm
      rw [hc]; exact W.smul_mem _ hx
    -- Every nonzero `B`-submodule contains the socle vector `v`.
    have mem_of_ne_bot : ∀ W : Submodule (zeroMulAlg n) (Cyc n k), W ≠ ⊥ → socleVec n k ∈ W := by
      intro W hW
      obtain ⟨w, hwW, hw0⟩ := (Submodule.ne_bot_iff W).mp hW
      by_cases h0 : w 0 = 0
      · -- `w` lies on the socle line already.
        set a : ℂ := w 1 with ha
        have hwv : w = a • socleVec n k := by
          funext j; fin_cases j
          · show w 0 = a • socleVec n k 0
            simp [socleVec, socleVecR, h0]
          · show w 1 = a • socleVec n k 1
            simp [socleVec, socleVecR, ha]
        have hw1 : a ≠ 0 := fun h1 => hw0 (by rw [hwv, h1, zero_smul])
        have hv : socleVec n k = a⁻¹ • w := by
          rw [hwv, smul_smul, inv_mul_cancel₀ hw1, one_smul]
        rw [hv]; exact csmul_mem _ _ _ hwW
      · -- Apply `x₀` (acting as `N`) to reach the socle line.
        have hxw : (gen n (0 : Fin n)) • w ∈ W := W.smul_mem _ hwW
        have hact : (gen n (0 : Fin n)) • w = w 0 • socleVec n k := by
          show rep n k (gen n 0) w = w 0 • socleVec n k
          rw [rep_gen, wt_zero]; simp
        rw [hact] at hxw
        have hv : socleVec n k = (w 0)⁻¹ • (w 0 • socleVec n k) := by
          rw [smul_smul, inv_mul_cancel₀ h0, one_smul]
        rw [hv]; exact csmul_mem _ _ _ hxw
    refine ⟨inferInstance, ?_⟩
    intro W₁ W₂ hcompl
    by_contra hcon
    push_neg at hcon
    obtain ⟨hW1, hW2⟩ := hcon
    have hv : socleVec n k ∈ W₁ ⊓ W₂ := ⟨mem_of_ne_bot _ hW1, mem_of_ne_bot _ hW2⟩
    rw [disjoint_iff.mp hcompl.disjoint] at hv
    exact socleVec_ne_zero n k ((Submodule.mem_bot _).mp hv)
  · -- The modules are pairwise nonisomorphic: the socle scalar `k` is an isomorphism invariant.
    rintro k l ⟨φ⟩
    -- The equivalence intertwines the representation actions.
    have hmap : ∀ (r : zeroMulAlg n) (x : Cyc n k), φ (rep n k r x) = rep n l r (φ x) :=
      fun r x => map_smul φ r x
    -- `φ` is `ℂ`-linear, since `ℂ` acts through `algebraMap ℂ B`.
    have philin : ∀ (c : ℂ) (x : Cyc n k), φ (c • x) = c • φ x := by
      intro c x
      have h := hmap (algebraMap ℂ (zeroMulAlg n) c) x
      rw [rep_algebraMap_smul, rep_algebraMap_smul] at h
      exact h
    -- `φ` commutes with the `x₀`-action `N`.
    have hN : ∀ x, φ (nilOp n k x) = nilOp n l (φ x) := by
      intro x
      have h := hmap (gen n (0 : Fin n)) x
      rw [rep_gen, rep_gen, wt_zero, wt_zero, LinearMap.smul_apply, LinearMap.smul_apply,
        one_smul, one_smul] at h
      exact h
    -- The `x₁`-action scales by `k` on the source and by `l` on the target.
    have hK : φ ((k : ℂ) • nilOp n k (cycVec n k)) = (l : ℂ) • nilOp n l (φ (cycVec n k)) := by
      have h := hmap (gen n (1 : Fin n)) (cycVec n k)
      rw [rep_gen, rep_gen, wt_one _ hn, wt_one _ hn, LinearMap.smul_apply,
        LinearMap.smul_apply] at h
      exact h
    have hNu : nilOp n k (cycVec n k) = socleVec n k := by
      simp [nilOp_apply, cycVec, cycVecR]
    rw [hNu, philin] at hK
    rw [← hN (cycVec n k), hNu] at hK
    -- Now `hK : (k:ℂ) • φ v = (l:ℂ) • φ v`, with `φ v ≠ 0`.
    have hφv : φ (socleVec n k) ≠ 0 :=
      fun h => socleVec_ne_zero n k (φ.injective (by rw [map_zero]; exact h))
    have hkl : ((k : ℂ) - (l : ℂ)) • φ (socleVec n k) = 0 := by rw [sub_smul, hK, sub_self]
    rcases smul_eq_zero.mp hkl with hc | hc
    · rw [sub_eq_zero] at hc; exact_mod_cast hc
    · exact absurd hc hφv

end Etingof.Problem3_9_2
