import Mathlib.Data.Complex.Basic
import Mathlib.LinearAlgebra.CliffordAlgebra.Basic
import Mathlib.LinearAlgebra.QuadraticForm.Basic
import Mathlib.LinearAlgebra.BilinearForm.Properties
import Mathlib.LinearAlgebra.ExteriorAlgebra.Basic
import Mathlib.RingTheory.SimpleModule.Basic
import Mathlib.RingTheory.Jacobson.Radical
import Mathlib.LinearAlgebra.FiniteDimensional.Defs

/-!
# Problem 3.9.5: The Clifford algebra

Let `V` be a finite dimensional complex vector space with a symmetric bilinear form
`(·,·) = B`. The **Clifford algebra** `Cl(V)` is the quotient of the tensor algebra `TV`
by the ideal generated by `v ⊗ v − (v,v)·1`. Equivalently, for a basis `xᵢ` with
`(xᵢ, xⱼ) = aᵢⱼ`, it is generated by the `xᵢ` with relations
`xᵢ xⱼ + xⱼ xᵢ = 2aᵢⱼ`, `xᵢ² = aᵢᵢ`. If `(·,·) = 0`, then `Cl(V) = ⋀ V`.

We model `Cl(V)` as Mathlib's `CliffordAlgebra Q` for the quadratic form
`Q(v) = B(v, v)` (`LinearMap.BilinMap.toQuadraticMap B`). Its defining relation
`ι(v)² = Q(v)` polarises to `ι(v)ι(w) + ι(w)ι(v) = B(v,w) + B(w,v) = 2B(v,w)` when `B`
is symmetric, matching the book's relations with `aᵢⱼ = B(xᵢ, xⱼ)`.

* **(i)** If `B` is nondegenerate then `Cl(V)` is semisimple. If `dim V = 2n` it is a
  matrix algebra, with a single irreducible representation `S` (the spinor module) of
  dimension `2ⁿ`; if `dim V = 2n+1` it is a direct sum of two matrix algebras, with two
  non-isomorphic irreducible representations `S₊, S₋` of dimension `2ⁿ`.
* **(ii)** `Cl(V)` is semisimple iff `B` is nondegenerate. When `B` is degenerate, the
  semisimple quotient `Cl(V) / Rad(Cl(V))` is the (nondegenerate) Clifford algebra of the
  induced form on `V` modulo the radical of `B`.

A "matrix algebra" is phrased as `Module.End ℂ S` for a finite dimensional `S` — the
endomorphism algebra of its `2ⁿ`-dimensional spinor representation, which is exactly the
statement that `S` is the unique irreducible module.

Statement pass: the quadratic form and Clifford algebra are genuinely constructed; the
proofs are left as `sorry`.
-/

namespace Etingof.Problem3_9_5

variable {V : Type*} [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V]
  (B : LinearMap.BilinForm ℂ V)

/-- The quadratic form `Q(v) = (v, v) = B v v` attached to the symmetric bilinear form `B`.
Genuinely constructed via `LinearMap.BilinMap.toQuadraticMap`. -/
noncomputable abbrev quadForm : QuadraticForm ℂ V :=
  LinearMap.BilinMap.toQuadraticMap B

/-- The Clifford algebra `Cl(V)` of the form, as `CliffordAlgebra Q`. -/
abbrev CliffAlg : Type _ := CliffordAlgebra (quadForm B)

omit [FiniteDimensional ℂ V] in
/-- **Parenthetical.** If the form is zero, `Cl(V)` is the exterior algebra `⋀ V`. -/
theorem cliffordAlgebra_zero_eq_exterior :
    Nonempty (CliffordAlgebra (quadForm (0 : LinearMap.BilinForm ℂ V)) ≃ₐ[ℂ]
      ExteriorAlgebra ℂ V) := by
  -- `ExteriorAlgebra ℂ V` is *defined* as `CliffordAlgebra (0 : QuadraticForm ℂ V)`, so it
  -- suffices to see that the quadratic form of the zero bilinear form is the zero form.
  have hq : quadForm (0 : LinearMap.BilinForm ℂ V) = (0 : QuadraticForm ℂ V) := by
    ext v
    simp [quadForm]
  rw [hq]
  exact ⟨AlgEquiv.refl⟩

/-- **Problem 3.9.5(i), semisimplicity.** If `B` is nondegenerate then `Cl(V)` is a
semisimple ring. -/
theorem isSemisimpleRing_of_nondegenerate
    (hsymm : ∀ x y, B x y = B y x) (hnd : B.Nondegenerate) :
    IsSemisimpleRing (CliffAlg B) := by
  sorry

/-- **Problem 3.9.5(i), even case.** If `B` is nondegenerate and `dim V = 2n`, then
`Cl(V)` is a matrix algebra: it is isomorphic to `End(S)` for a `2ⁿ`-dimensional space
`S`, the unique (spinor) irreducible representation. -/
theorem even_isMatrixAlgebra
    (hsymm : ∀ x y, B x y = B y x) (hnd : B.Nondegenerate)
    (n : ℕ) (hdim : Module.finrank ℂ V = 2 * n) :
    ∃ (S : Type) (_ : AddCommGroup S) (_ : Module ℂ S),
      Module.finrank ℂ S = 2 ^ n ∧ Nonempty (CliffAlg B ≃ₐ[ℂ] Module.End ℂ S) := by
  sorry

/-- **Problem 3.9.5(i), odd case.** If `B` is nondegenerate and `dim V = 2n+1`, then
`Cl(V)` is a direct sum of two matrix algebras: `End(S) × End(S)` with `dim S = 2ⁿ`. The
two factors are the two non-isomorphic irreducible representations `S₊, S₋`. -/
theorem odd_isSumMatrixAlgebra
    (hsymm : ∀ x y, B x y = B y x) (hnd : B.Nondegenerate)
    (n : ℕ) (hdim : Module.finrank ℂ V = 2 * n + 1) :
    ∃ (S : Type) (_ : AddCommGroup S) (_ : Module ℂ S),
      Module.finrank ℂ S = 2 ^ n ∧
      Nonempty (CliffAlg B ≃ₐ[ℂ] (Module.End ℂ S × Module.End ℂ S)) := by
  sorry

/-- **Problem 3.9.5(ii).** `Cl(V)` is semisimple if and only if `B` is nondegenerate. -/
theorem isSemisimpleRing_iff_nondegenerate (hsymm : ∀ x y, B x y = B y x) :
    IsSemisimpleRing (CliffAlg B) ↔ B.Nondegenerate := by
  sorry

/-- **Problem 3.9.5(ii), the degenerate quotient.** If `B` is degenerate, the semisimple
quotient `Cl(V) / Rad(Cl(V))` is the Clifford algebra of a nondegenerate form `B'` on the
quotient of `V` by the radical of `B`. Phrased as: there is a nondegenerate symmetric form
`B'` on some space `W` together with a surjective algebra map `Cl(V) → Cl(W, B')` whose
kernel is the Jacobson radical. -/
theorem radicalQuotient_isClifford_of_degenerate
    (hsymm : ∀ x y, B x y = B y x) (hdeg : ¬ B.Nondegenerate) :
    ∃ (W : Type) (_ : AddCommGroup W) (_ : Module ℂ W) (B' : LinearMap.BilinForm ℂ W),
      (∀ x y, B' x y = B' y x) ∧ B'.Nondegenerate ∧
      ∃ φ : CliffAlg B →ₐ[ℂ] CliffordAlgebra (quadForm B'),
        Function.Surjective φ ∧ RingHom.ker φ.toRingHom = Ring.jacobson (CliffAlg B) := by
  sorry

end Etingof.Problem3_9_5
