import EtingofRepresentationTheory.Chapter3.Problem3_9_2
import Mathlib.Algebra.DualNumber

/-!
# Two-dimensional representations of `ℂ[x₁, …, xₙ]` up to isomorphism

Problem 3.9.2(a) asks for the classification of the 2-dimensional representations of
`A = ℂ[x₁, …, xₙ]`. `Etingof.Problem3_9_2.two_dim_is_extension` supplies the reduction step:
every 2-dimensional representation is an extension of two 1-dimensional ones. This file turns
that reduction into a classification: it exhibits explicit normal forms, proves every
2-dimensional representation is isomorphic to one of them, and decides when two normal forms
are isomorphic.

Two families of normal forms occur.

* For a pair of weights `a ≠ b` the extension splits, because `Ext¹(Vₐ, V_b) = 0`
  (`ext1_subsingleton_of_ne`), and the module is the direct sum `V_b × Vₐ`.
* For a single weight `a` the extensions of `Vₐ` by itself are classified by
  `Ext¹(Vₐ, Vₐ) ≅ ℂⁿ` (`ext1_self`). The module attached to `c : Fin n → ℂ` is `Jrep a c`,
  the algebra of dual numbers `ℂ[ε]` with `xᵢ` acting as `aᵢ + cᵢ ε`. The class `c = 0` gives the
  split module `Vₐ × Vₐ`, and `Jrep a c ≅ Jrep a c'` exactly when `c` and `c'` are proportional,
  so the nonsplit self-extensions are parametrized by the projective space of `ℂⁿ`.

The two families are disjoint: a module in the first family has two distinct weights, one in the
second family has a single weight.
-/

namespace Etingof.Problem3_9_2

open Etingof.Problem3_9_1
open MvPolynomial
open DualNumber

/-! ## The generators as `ℂ`-linear endomorphisms -/

section GenEnd

variable {n : ℕ} {M : Type*} [AddCommGroup M] [Module ℂ M] [Module (polyAlg n) M]
  [IsScalarTower ℂ (polyAlg n) M]

/-- The `polyAlg n`-action commutes with the `ℂ`-action, since `ℂ` is central in `polyAlg n`. -/
lemma smulCommClass_polyAlg : SMulCommClass (polyAlg n) ℂ M :=
  ⟨fun q r m => by
    rw [← algebraMap_smul (polyAlg n) r m, ← mul_smul, ← algebraMap_smul (polyAlg n) r (q • m),
      ← mul_smul, Algebra.commutes]⟩

/-- The action of the generator `xᵢ` as a `ℂ`-linear endomorphism. -/
noncomputable def genEnd (i : Fin n) : Module.End ℂ M :=
  letI := smulCommClass_polyAlg (n := n) (M := M)
  { toFun := fun m => (X i : polyAlg n) • m
    map_add' := fun x y => smul_add _ _ _
    map_smul' := fun r m => by
      simp only [RingHom.id_apply]
      exact smul_comm (X i : polyAlg n) r m }

@[simp] lemma genEnd_apply (i : Fin n) (m : M) : genEnd i m = (X i : polyAlg n) • m := rfl

end GenEnd

/-! ## `ℂ`-linear equivalences commuting with the generators are `A`-linear -/

/-- A `ℂ`-linear equivalence between two `A`-modules that commutes with the action of every
generator `xᵢ` is `A`-linear. Since `A` is generated by the `xᵢ` over `ℂ`, the multiplicative
structure is determined by the generators. -/
theorem nonempty_linearEquiv_of_comm_X {n : ℕ} {M N : Type*}
    [AddCommGroup M] [Module ℂ M] [Module (polyAlg n) M] [IsScalarTower ℂ (polyAlg n) M]
    [AddCommGroup N] [Module ℂ N] [Module (polyAlg n) N] [IsScalarTower ℂ (polyAlg n) N]
    (e : M ≃ₗ[ℂ] N)
    (h : ∀ (i : Fin n) (m : M), e ((X i : polyAlg n) • m) = (X i : polyAlg n) • e m) :
    Nonempty (M ≃ₗ[polyAlg n] N) := by
  have key : ∀ (p : polyAlg n) (m : M), e (p • m) = p • e m := by
    intro p
    induction p using MvPolynomial.induction_on with
    | C r =>
      intro m
      rw [← MvPolynomial.algebraMap_eq, algebraMap_smul, algebraMap_smul, map_smul]
    | add p q hp hq => intro m; rw [add_smul, map_add, hp, hq, add_smul]
    | mul_X p i hp => intro m; rw [mul_smul, hp, h, ← mul_smul]
  exact ⟨{ e with map_smul' := key }⟩

/-- To check that a `ℂ`-linear equivalence commutes with the generators it suffices to check it
on a `ℂ`-basis. -/
theorem nonempty_linearEquiv_of_comm_X_basis {n : ℕ} {M N : Type*}
    [AddCommGroup M] [Module ℂ M] [Module (polyAlg n) M] [IsScalarTower ℂ (polyAlg n) M]
    [AddCommGroup N] [Module ℂ N] [Module (polyAlg n) N] [IsScalarTower ℂ (polyAlg n) N]
    {ι : Type*} (B : Module.Basis ι ℂ M) (e : M ≃ₗ[ℂ] N)
    (h : ∀ (i : Fin n) (j : ι), e ((X i : polyAlg n) • B j) = (X i : polyAlg n) • e (B j)) :
    Nonempty (M ≃ₗ[polyAlg n] N) := by
  refine nonempty_linearEquiv_of_comm_X e fun i m => ?_
  have hmaps : (e.toLinearMap ∘ₗ genEnd (M := M) i) = (genEnd (M := N) i ∘ₗ e.toLinearMap) :=
    B.ext fun j => by simpa using h i j
  simpa using LinearMap.congr_fun hmaps m

/-! ## The dual-number normal form `Jrep a c` -/

/-- Carrier of the normal form attached to a weight `a` and an extension class `c`: the algebra
`ℂ[ε]` of dual numbers. The parameters appear in the type so that distinct parameters carry
distinct `polyAlg n`-module structures. -/
def Jrep {n : ℕ} (_a _c : Fin n → ℂ) : Type := DualNumber ℂ

namespace Jrep

variable {n : ℕ} (a c : Fin n → ℂ)

instance : CommRing (Jrep a c) := inferInstanceAs (CommRing (DualNumber ℂ))
instance : Algebra ℂ (Jrep a c) := inferInstanceAs (Algebra ℂ (DualNumber ℂ))
instance : Module.Finite ℂ (Jrep a c) := inferInstanceAs (Module.Finite ℂ (ℂ × ℂ))
instance : Nontrivial (Jrep a c) := inferInstanceAs (Nontrivial (ℂ × ℂ))
instance : FiniteDimensional ℂ (Jrep a c) := inferInstanceAs (FiniteDimensional ℂ (ℂ × ℂ))

/-- The nilpotent dual number `ε`, spanning the unique one-dimensional submodule. -/
def eps : Jrep a c := (ε : DualNumber ℂ)

@[simp] theorem eps_mul_eps : eps a c * eps a c = 0 := DualNumber.eps_mul_eps

/-- First dual-number coordinate. -/
def fst (x : Jrep a c) : ℂ := TrivSqZeroExt.fst (x : DualNumber ℂ)

/-- Second dual-number coordinate. -/
def snd (x : Jrep a c) : ℂ := TrivSqZeroExt.snd (x : DualNumber ℂ)

@[simp] theorem fst_zero : fst a c 0 = 0 := rfl
@[simp] theorem snd_zero : snd a c 0 = 0 := rfl
@[simp] theorem fst_one : fst a c 1 = 1 := rfl
@[simp] theorem snd_one : snd a c 1 = 0 := rfl
@[simp] theorem fst_eps : fst a c (eps a c) = 0 := rfl
@[simp] theorem snd_eps : snd a c (eps a c) = 1 := rfl

@[simp] theorem fst_add (x y : Jrep a c) : fst a c (x + y) = fst a c x + fst a c y := rfl
@[simp] theorem snd_add (x y : Jrep a c) : snd a c (x + y) = snd a c x + snd a c y := rfl
@[simp] theorem fst_smul (r : ℂ) (x : Jrep a c) : fst a c (r • x) = r * fst a c x := rfl
@[simp] theorem snd_smul (r : ℂ) (x : Jrep a c) : snd a c (r • x) = r * snd a c x := rfl

theorem ext {x y : Jrep a c} (h1 : fst a c x = fst a c y) (h2 : snd a c x = snd a c y) : x = y :=
  TrivSqZeroExt.ext h1 h2

/-- Every dual number is a `ℂ`-combination of `1` and `ε`. -/
theorem eq_smul_one_add_smul_eps (x : Jrep a c) :
    x = fst a c x • (1 : Jrep a c) + snd a c x • eps a c := by
  refine ext a c ?_ ?_ <;> simp

end Jrep

/-- Multiplying a dual number by `ε` retains only its scalar part. -/
private theorem dualNumber_eps_mul (x : DualNumber ℂ) :
    (ε : DualNumber ℂ) * x = TrivSqZeroExt.fst x • (ε : DualNumber ℂ) := by
  refine TrivSqZeroExt.ext ?_ ?_ <;>
    simp [TrivSqZeroExt.fst_mul, TrivSqZeroExt.snd_mul]

theorem Jrep.eps_mul {n : ℕ} (a c : Fin n → ℂ) (x : Jrep a c) :
    eps a c * x = fst a c x • eps a c :=
  dualNumber_eps_mul x

/-- The algebra map sending `xᵢ` to the dual number `aᵢ + cᵢ ε`. -/
noncomputable def jHom {n : ℕ} (a c : Fin n → ℂ) : polyAlg n →ₐ[ℂ] Jrep a c :=
  MvPolynomial.aeval fun i => algebraMap ℂ (Jrep a c) (a i) + c i • Jrep.eps a c

@[simp] theorem jHom_X {n : ℕ} (a c : Fin n → ℂ) (i : Fin n) :
    jHom a c (X i) = algebraMap ℂ (Jrep a c) (a i) + c i • Jrep.eps a c := by
  simp [jHom]

noncomputable instance jrepModule {n : ℕ} (a c : Fin n → ℂ) : Module (polyAlg n) (Jrep a c) :=
  Module.compHom (Jrep a c) (jHom a c).toRingHom

theorem jrep_smul_def {n : ℕ} (a c : Fin n → ℂ) (p : polyAlg n) (x : Jrep a c) :
    p • x = jHom a c p * x := rfl

instance {n : ℕ} (a c : Fin n → ℂ) : IsScalarTower ℂ (polyAlg n) (Jrep a c) :=
  ⟨fun r p x => by rw [jrep_smul_def, jrep_smul_def, map_smul, smul_mul_assoc]⟩

theorem jrep_finrank {n : ℕ} (a c : Fin n → ℂ) : Module.finrank ℂ (Jrep a c) = 2 := by
  change Module.finrank ℂ (ℂ × ℂ) = 2
  rw [Module.finrank_prod, Module.finrank_self]

/-- The generator `xᵢ` acts on `Jrep a c` as `aᵢ + cᵢ ε`. -/
theorem jrep_X_smul {n : ℕ} (a c : Fin n → ℂ) (i : Fin n) (x : Jrep a c) :
    (X i : polyAlg n) • x = a i • x + c i • (Jrep.eps a c * x) := by
  rw [jrep_smul_def, jHom_X, add_mul, Algebra.algebraMap_eq_smul_one, smul_mul_assoc, one_mul,
    smul_mul_assoc]

@[simp] theorem jrep_X_smul_one {n : ℕ} (a c : Fin n → ℂ) (i : Fin n) :
    (X i : polyAlg n) • (1 : Jrep a c) = a i • (1 : Jrep a c) + c i • Jrep.eps a c := by
  rw [jrep_X_smul, mul_one]

@[simp] theorem jrep_X_smul_eps {n : ℕ} (a c : Fin n → ℂ) (i : Fin n) :
    (X i : polyAlg n) • Jrep.eps a c = a i • Jrep.eps a c := by
  rw [jrep_X_smul, Jrep.eps_mul_eps, smul_zero, add_zero]

/-- `ε` is a weight vector of weight `a`. -/
theorem jrep_eps_ne_zero {n : ℕ} (a c : Fin n → ℂ) : Jrep.eps a c ≠ 0 := by
  intro h
  have := congrArg (Jrep.snd a c) h
  simp at this

/-- The `ℂ`-basis `1, ε` of `Jrep a c`. -/
noncomputable def jrepBasis {n : ℕ} (a c : Fin n → ℂ) :
    Module.Basis (Fin 2) ℂ (Jrep a c) := by
  refine basisOfLinearIndependentOfCardEqFinrank
    (b := ![(1 : Jrep a c), Jrep.eps a c]) ?_ ?_
  · rw [LinearIndependent.pair_iff]
    intro s t hst
    have h1 := congrArg (Jrep.fst a c) hst
    have h2 := congrArg (Jrep.snd a c) hst
    simp only [Jrep.fst_add, Jrep.snd_add, Jrep.fst_smul, Jrep.snd_smul, Jrep.fst_one,
      Jrep.snd_one, Jrep.fst_eps, Jrep.snd_eps, mul_one, mul_zero, add_zero, zero_add,
      Jrep.fst_zero, Jrep.snd_zero] at h1 h2
    exact ⟨h1, h2⟩
  · rw [Fintype.card_fin, jrep_finrank]

@[simp] theorem jrepBasis_apply {n : ℕ} (a c : Fin n → ℂ) (j : Fin 2) :
    jrepBasis a c j = ![(1 : Jrep a c), Jrep.eps a c] j := by
  rw [jrepBasis, coe_basisOfLinearIndependentOfCardEqFinrank]

theorem jrepBasis_zero_eq {n : ℕ} (a c : Fin n → ℂ) : jrepBasis a c 0 = (1 : Jrep a c) := by
  rw [jrepBasis_apply]; rfl

theorem jrepBasis_one_eq {n : ℕ} (a c : Fin n → ℂ) : jrepBasis a c 1 = Jrep.eps a c := by
  rw [jrepBasis_apply]; rfl

/-! ## Weight lines -/

section WeightLine

variable {n : ℕ} {U : Type*} [AddCommGroup U] [Module ℂ U] [Module (polyAlg n) U]
  [IsScalarTower ℂ (polyAlg n) U]

/-- The `A`-submodule generated by a weight vector is already its `ℂ`-line, because a polynomial
`p` acts on a weight vector by the scalar `p(b)`. -/
lemma weightLine_restrictScalars (b : Fin n → ℂ) (w : U)
    (hb : ∀ i, (X i : polyAlg n) • w = b i • w) :
    (Submodule.span (polyAlg n) {w}).restrictScalars ℂ = Submodule.span ℂ {w} := by
  apply le_antisymm
  · rw [SetLike.le_def]
    intro x hx
    rw [Submodule.restrictScalars_mem, Submodule.mem_span_singleton] at hx
    obtain ⟨p, rfl⟩ := hx
    rw [eigen_smul_eq b w hb p]
    exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self w)
  · rw [Submodule.span_le]
    simp only [Set.singleton_subset_iff, SetLike.mem_coe, Submodule.restrictScalars_mem]
    exact Submodule.mem_span_singleton_self w

/-- A nonzero weight vector of weight `b` generates a copy of `V_b`. -/
noncomputable def weightLine_iso (b : Fin n → ℂ) (w : U) (hw : w ≠ 0)
    (hb : ∀ i, (X i : polyAlg n) • w = b i • w) :
    ↥(Submodule.span (polyAlg n) {w}) ≃ₗ[polyAlg n] Vrep b := by
  have hrs := weightLine_restrictScalars b w hb
  have h1 : Module.finrank ℂ ↥((Submodule.span (polyAlg n) {w}).restrictScalars ℂ) = 1 := by
    rw [hrs]; exact finrank_span_singleton hw
  have h1' : Module.finrank ℂ ↥(Submodule.span (polyAlg n) {w}) = 1 := h1
  haveI : FiniteDimensional ℂ ↥(Submodule.span (polyAlg n) {w}) :=
    FiniteDimensional.of_finrank_pos (by rw [h1']; norm_num)
  refine oneDim_iso_Vrep b (⟨w, Submodule.mem_span_singleton_self w⟩) ?_ h1' ?_
  · rw [Ne, Submodule.mk_eq_zero]; exact hw
  · intro i
    apply Subtype.ext
    change (X i : polyAlg n) • w = b i • w
    exact hb i

/-- A `ℂ`-multiple of an element of an `A`-submodule stays in it. -/
lemma smul_mem_of_tower {S : Submodule (polyAlg n) U} (r : ℂ) {x : U} (hx : x ∈ S) : r • x ∈ S := by
  rw [← algebraMap_smul (polyAlg n) r x]
  exact Submodule.smul_mem _ _ hx

end WeightLine

/-! ## Exhaustiveness of the normal forms -/

/-- **Every 2-dimensional representation is a normal form.** A 2-dimensional representation of
`ℂ[x₁, …, xₙ]` is isomorphic either to a direct sum `V_b × Vₐ` of two 1-dimensional
representations with distinct weights, or to a dual-number module `Jrep a c`. -/
theorem two_dim_normal_form {n : ℕ} (U : Type)
    [AddCommGroup U] [Module ℂ U] [Module (polyAlg n) U] [IsScalarTower ℂ (polyAlg n) U]
    [FiniteDimensional ℂ U] (hdim : Module.finrank ℂ U = 2) :
    (∃ b a : Fin n → ℂ, b ≠ a ∧ Nonempty (U ≃ₗ[polyAlg n] Vrep b × Vrep a)) ∨
      (∃ a c : Fin n → ℂ, Nonempty (U ≃ₗ[polyAlg n] Jrep a c)) := by
  haveI : SMulCommClass (polyAlg n) ℂ U := smulCommClass_polyAlg
  obtain ⟨b, v, hv, hb⟩ := exists_common_eigenvector (n := n) U hdim
  -- A vector outside the `ℂ`-line of `v`.
  obtain ⟨u, hu⟩ : ∃ u : U, u ∉ Submodule.span ℂ {v} := by
    by_contra hcon
    have htop : Submodule.span ℂ ({v} : Set U) = ⊤ :=
      eq_top_iff.mpr fun x _ => not_not.mp fun hx => hcon ⟨x, hx⟩
    have hcg : Module.finrank ℂ ↥(Submodule.span ℂ ({v} : Set U))
        = Module.finrank ℂ ↥(⊤ : Submodule ℂ U) :=
      congrArg (fun S : Submodule ℂ U => Module.finrank ℂ ↥S) htop
    rw [finrank_span_singleton hv, finrank_top, hdim] at hcg
    omega
  -- `u, v` is a `ℂ`-basis of `U`.
  have hindep : LinearIndependent ℂ ![u, v] := by
    rw [LinearIndependent.pair_iff]
    intro s t hst
    by_cases hs : s = 0
    · subst hs
      rw [zero_smul, zero_add] at hst
      exact ⟨rfl, (smul_eq_zero.mp hst).resolve_right hv⟩
    · exfalso
      apply hu
      have h1 : s • u = -(t • v) := eq_neg_of_add_eq_zero_left hst
      have h2 : u = (-(s⁻¹ * t)) • v := by
        rw [neg_smul, ← smul_smul, ← smul_neg, ← h1, inv_smul_smul₀ hs]
      rw [h2]
      exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self v)
  obtain ⟨B, hBcoe⟩ : ∃ B : Module.Basis (Fin 2) ℂ U, ⇑B = ![u, v] :=
    ⟨basisOfLinearIndependentOfCardEqFinrank hindep (by rw [Fintype.card_fin, hdim]),
      coe_basisOfLinearIndependentOfCardEqFinrank _ _⟩
  have hBu : B 0 = u := by rw [hBcoe]; rfl
  have hBv : B 1 = v := by rw [hBcoe]; rfl
  have hcoord : ∀ x : U, x = B.repr x 0 • u + B.repr x 1 • v := by
    intro x
    have h := B.sum_repr x
    rw [Fin.sum_univ_two, hBu, hBv] at h
    exact h.symm
  have hpair : ∀ s₁ t₁ s₂ t₂ : ℂ, s₁ • u + t₁ • v = s₂ • u + t₂ • v → s₁ = s₂ ∧ t₁ = t₂ := by
    intro s₁ t₁ s₂ t₂ h
    have h0 : (s₁ - s₂) • u + (t₁ - t₂) • v = 0 := by
      have h' : (s₁ • u + t₁ • v) - (s₂ • u + t₂ • v) = 0 := sub_eq_zero_of_eq h
      rw [← h']; module
    obtain ⟨hs, ht⟩ := LinearIndependent.pair_iff.mp hindep _ _ h0
    exact ⟨sub_eq_zero.mp hs, sub_eq_zero.mp ht⟩
  -- The matrix of the action in the basis `u, v`: `xᵢ • u = αᵢ u + γᵢ v`.
  obtain ⟨α, γ, hXu⟩ : ∃ α γ : Fin n → ℂ, ∀ i, (X i : polyAlg n) • u = α i • u + γ i • v :=
    ⟨fun i => B.repr ((X i : polyAlg n) • u) 0, fun i => B.repr ((X i : polyAlg n) • u) 1,
      fun i => hcoord _⟩
  have hXsmul : ∀ (i : Fin n) (r : ℂ) (x : U),
      (X i : polyAlg n) • (r • x) = r • ((X i : polyAlg n) • x) := fun i r x => smul_comm _ _ _
  have hexp : ∀ i j : Fin n, (X i : polyAlg n) • ((X j : polyAlg n) • u)
      = (α j * α i) • u + (α j * γ i + γ j * b i) • v := by
    intro i j
    rw [hXu j, smul_add, hXsmul, hXsmul, hXu i, hb i]
    module
  -- Commutativity of the generators forces `γᵢ (b_j − α_j) = γ_j (b_i − α_i)`.
  have hrel : ∀ i j : Fin n, α j * γ i + γ j * b i = α i * γ j + γ i * b j := by
    intro i j
    have h1 : (X i : polyAlg n) • ((X j : polyAlg n) • u)
        = (X j : polyAlg n) • ((X i : polyAlg n) • u) := by
      rw [← mul_smul, ← mul_smul, mul_comm]
    rw [hexp i j, hexp j i] at h1
    exact (hpair _ _ _ _ h1).2
  by_cases hαb : α = b
  · -- Equal weights: a dual-number module.
    right
    refine ⟨α, γ, ?_⟩
    have hvα : ∀ i, (X i : polyAlg n) • v = α i • v := by rw [hαb]; exact hb
    set e := B.equiv (jrepBasis α γ) (Equiv.refl (Fin 2)) with he
    have he0 : e (B 0) = (1 : Jrep α γ) := by
      rw [he, Module.Basis.equiv_apply, Equiv.refl_apply, jrepBasis_apply]; rfl
    have he1 : e (B 1) = Jrep.eps α γ := by
      rw [he, Module.Basis.equiv_apply, Equiv.refl_apply, jrepBasis_apply]; rfl
    refine nonempty_linearEquiv_of_comm_X_basis B e ?_
    intro i j
    have h0 : e ((X i : polyAlg n) • B 0) = (X i : polyAlg n) • e (B 0) := by
      rw [hBu, hXu i, map_add, map_smul, map_smul, ← hBu, ← hBv, he0, he1, jrep_X_smul_one,
        add_comm]
    have h1 : e ((X i : polyAlg n) • B 1) = (X i : polyAlg n) • e (B 1) := by
      rw [hBv, hvα i, map_smul, ← hBv, he1, jrep_X_smul_eps]
    fin_cases j
    · exact h0
    · exact h1
  · -- Distinct weights: the extension splits.
    left
    obtain ⟨k, hk⟩ := Function.ne_iff.mp hαb
    have hbk : b k - α k ≠ 0 := sub_ne_zero_of_ne (Ne.symm hk)
    obtain ⟨t, ht⟩ : ∃ t : ℂ, t = γ k / (b k - α k) := ⟨_, rfl⟩
    obtain ⟨u', hu'def⟩ : ∃ u' : U, u' = u - t • v := ⟨_, rfl⟩
    -- Shifting `u` by the right multiple of `v` produces a weight vector of weight `α`.
    have hXu' : ∀ i, (X i : polyAlg n) • u' = α i • u' := by
      intro i
      have hti : t * (b i - α i) = γ i := by
        rw [ht, div_mul_eq_mul_div, div_eq_iff hbk]
        linear_combination hrel i k
      rw [hu'def, smul_sub, hXsmul, hXu i, hb i]
      match_scalars
      · ring
      · linear_combination -hti
    have hu'ne : u' ≠ 0 := by
      intro h
      rw [hu'def] at h
      apply hu
      rw [sub_eq_zero.mp h]
      exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self v)
    have hindep' : LinearIndependent ℂ ![v, u'] := by
      rw [LinearIndependent.pair_iff]
      intro s r hsr
      rw [hu'def] at hsr
      have h0 : r • u + (s - r * t) • v = 0 := by rw [← hsr]; module
      obtain ⟨hr, hs⟩ := LinearIndependent.pair_iff.mp hindep _ _ h0
      rw [hr, zero_mul, sub_zero] at hs
      exact ⟨hs, hr⟩
    have hspan' : ∀ x : U, ∃ s r : ℂ, x = s • v + r • u' := by
      intro x
      obtain ⟨p, q, hpq⟩ : ∃ p q : ℂ, x = p • u + q • v := ⟨_, _, hcoord x⟩
      exact ⟨q + p * t, p, by rw [hpq, hu'def]; module⟩
    have hdisj : Disjoint (Submodule.span (polyAlg n) ({v} : Set U))
        (Submodule.span (polyAlg n) ({u'} : Set U)) := by
      rw [Submodule.disjoint_def]
      intro x hx1 hx2
      have hx1' : x ∈ Submodule.span ℂ ({v} : Set U) := by
        rw [← weightLine_restrictScalars b v hb, Submodule.restrictScalars_mem]; exact hx1
      have hx2' : x ∈ Submodule.span ℂ ({u'} : Set U) := by
        rw [← weightLine_restrictScalars α u' hXu', Submodule.restrictScalars_mem]; exact hx2
      obtain ⟨s, hs⟩ := Submodule.mem_span_singleton.mp hx1'
      obtain ⟨r, hr⟩ := Submodule.mem_span_singleton.mp hx2'
      have h0 : s • v + (-r) • u' = 0 := by rw [hs, ← hr]; module
      obtain ⟨hs0, _⟩ := LinearIndependent.pair_iff.mp hindep' _ _ h0
      rw [← hs, hs0, zero_smul]
    have hcodisj : Codisjoint (Submodule.span (polyAlg n) ({v} : Set U))
        (Submodule.span (polyAlg n) ({u'} : Set U)) := by
      rw [codisjoint_iff, eq_top_iff]
      intro x _
      obtain ⟨s, r, hsr⟩ := hspan' x
      rw [hsr]
      exact Submodule.add_mem_sup
        (smul_mem_of_tower s (Submodule.mem_span_singleton_self v))
        (smul_mem_of_tower r (Submodule.mem_span_singleton_self u'))
    refine ⟨b, α, fun h => hk (by rw [h]), ?_⟩
    exact ⟨(Submodule.prodEquivOfIsCompl _ _ ⟨hdisj, hcodisj⟩).symm.trans
      ((weightLine_iso b v hv hb).prodCongr (weightLine_iso α u' hu'ne hXu'))⟩

/-! ## The isomorphism criterion -/

section JrepIso

variable {n : ℕ}

/-- An `A`-linear map is in particular `ℂ`-linear, because `ℂ` acts through `A`. -/
lemma map_smul_complex {M N : Type*}
    [AddCommGroup M] [Module ℂ M] [Module (polyAlg n) M] [IsScalarTower ℂ (polyAlg n) M]
    [AddCommGroup N] [Module ℂ N] [Module (polyAlg n) N] [IsScalarTower ℂ (polyAlg n) N]
    (φ : M ≃ₗ[polyAlg n] N) (r : ℂ) (x : M) : φ (r • x) = r • φ x := by
  rw [← algebraMap_smul (polyAlg n) r x, map_smul, algebraMap_smul]

/-- On `Jrep a c` the operator `xᵢ − r` is `(aᵢ − r)` plus `cᵢ` times multiplication by `ε`. -/
theorem jrep_sub_smul (a c : Fin n → ℂ) (i : Fin n) (r : ℂ) (x : Jrep a c) :
    (X i : polyAlg n) • x - r • x = (a i - r) • x + c i • (Jrep.eps a c * x) := by
  rw [jrep_X_smul]; module

/-- A multiple of `ε` vanishes only when the scalar does. -/
theorem jrep_smul_eps_eq_zero_iff (a c : Fin n → ℂ) (r : ℂ) :
    r • Jrep.eps a c = 0 ↔ r = 0 := by
  refine ⟨fun h => ?_, fun h => by rw [h, zero_smul]⟩
  have h2 := congrArg (Jrep.snd a c) h
  simpa using h2

/-- The operator `xᵢ − aᵢ` on `Jrep a c` squares to zero: it is `cᵢ ε`, and `ε² = 0`. -/
theorem jrep_nilpotent (a c : Fin n → ℂ) (i : Fin n) (x : Jrep a c) :
    (X i : polyAlg n) • ((X i : polyAlg n) • x - a i • x)
      - a i • ((X i : polyAlg n) • x - a i • x) = 0 := by
  have h : ∀ z : Jrep a c, (X i : polyAlg n) • z - a i • z = c i • (Jrep.eps a c * z) := by
    intro z; rw [jrep_sub_smul]; simp
  rw [h, h, mul_smul_comm, ← mul_assoc, Jrep.eps_mul_eps, zero_mul, smul_zero, smul_zero]

/-- **The weight is an invariant.** If `Jrep a c ≅ Jrep a' c'` then `a = a'`: the operator
`xᵢ − a'ᵢ` is nilpotent on the target, hence on the source, and on the source it differs from a
nilpotent operator by the nonzero scalar `aᵢ − a'ᵢ` unless the two weights agree. -/
theorem jrep_weight_eq (a c a' c' : Fin n → ℂ) (φ : Jrep a c ≃ₗ[polyAlg n] Jrep a' c') :
    a = a' := by
  funext i
  have hstep : ∀ x : Jrep a c, φ ((X i : polyAlg n) • x - a' i • x)
      = (X i : polyAlg n) • φ x - a' i • φ x := by
    intro x; rw [map_sub, map_smul, map_smul_complex]
  have hsrc : (X i : polyAlg n) • ((X i : polyAlg n) • (1 : Jrep a c) - a' i • (1 : Jrep a c))
      - a' i • ((X i : polyAlg n) • (1 : Jrep a c) - a' i • (1 : Jrep a c)) = 0 := by
    apply φ.injective
    rw [map_zero, hstep, hstep]
    exact jrep_nilpotent a' c' i (φ 1)
  rw [jrep_sub_smul, jrep_sub_smul, mul_one] at hsrc
  have hfst := congrArg (Jrep.fst a c) hsrc
  simp only [Jrep.eps_mul, Jrep.fst_add, Jrep.fst_smul, Jrep.fst_one, Jrep.fst_eps,
    Jrep.fst_zero, mul_zero, add_zero, mul_one] at hfst
  have hd : a i - a' i = 0 := by
    rcases mul_eq_zero.mp hfst with h' | h' <;> exact h'
  exact sub_eq_zero.mp hd

/-- If every generator acts by a scalar on `Jrep a c`, the extension class vanishes. -/
theorem jrep_class_eq_zero_of_scalar (a c : Fin n → ℂ)
    (h : ∀ (i : Fin n) (x : Jrep a c), (X i : polyAlg n) • x = a i • x) : c = 0 := by
  funext i
  have h1 := h i 1
  rw [jrep_X_smul_one] at h1
  have h2 : c i • Jrep.eps a c = 0 :=
    calc c i • Jrep.eps a c
        = (a i • (1 : Jrep a c) + c i • Jrep.eps a c) - a i • (1 : Jrep a c) := by abel
      _ = a i • (1 : Jrep a c) - a i • (1 : Jrep a c) := by rw [h1]
      _ = 0 := by abel
  simpa using (jrep_smul_eps_eq_zero_iff a c (c i)).mp h2

/-- A vanishing extension class on the target forces one on the source. -/
theorem jrep_class_eq_zero_of_target (a c c' : Fin n → ℂ) (hc' : c' = 0)
    (φ : Jrep a c ≃ₗ[polyAlg n] Jrep a c') : c = 0 := by
  subst hc'
  refine jrep_class_eq_zero_of_scalar a c fun i x => ?_
  apply φ.injective
  rw [map_smul, map_smul_complex, jrep_X_smul]
  simp

/-- **The extension class is determined up to a scalar.** -/
theorem jrep_exists_scalar (a c c' : Fin n → ℂ) (hc' : c' ≠ 0)
    (φ : Jrep a c ≃ₗ[polyAlg n] Jrep a c') : ∃ lam : ℂ, lam ≠ 0 ∧ c' = lam • c := by
  -- The nilpotent parts of the two actions intertwine.
  have hN : ∀ (i : Fin n) (x : Jrep a c),
      φ (c i • (Jrep.eps a c * x)) = c' i • (Jrep.eps a c' * φ x) := by
    intro i x
    have h1 : ∀ z : Jrep a c, c i • (Jrep.eps a c * z)
        = (X i : polyAlg n) • z - a i • z := by
      intro z; rw [jrep_sub_smul]; simp
    have h2 : ∀ z : Jrep a c', c' i • (Jrep.eps a c' * z)
        = (X i : polyAlg n) • z - a i • z := by
      intro z; rw [jrep_sub_smul]; simp
    rw [h1, h2, map_sub, map_smul, map_smul_complex]
  obtain ⟨s, hs⟩ : ∃ s, Jrep.fst a c' (φ 1) = s := ⟨_, rfl⟩
  obtain ⟨s', hs'⟩ : ∃ s', Jrep.fst a c' (φ (Jrep.eps a c)) = s' := ⟨_, rfl⟩
  obtain ⟨t', ht'⟩ : ∃ t', Jrep.snd a c' (φ (Jrep.eps a c)) = t' := ⟨_, rfl⟩
  -- Testing the intertwining on `ε` kills the `1`-coordinate of `φ ε`.
  have hs'zero : s' = 0 := by
    obtain ⟨i, hi⟩ := Function.ne_iff.mp hc'
    have hi' : c' i ≠ 0 := by simpa using hi
    have h := hN i (Jrep.eps a c)
    rw [Jrep.eps_mul_eps, smul_zero, map_zero, Jrep.eps_mul, hs', smul_smul] at h
    have h2 := (jrep_smul_eps_eq_zero_iff a c' (c' i * s')).mp h.symm
    exact (mul_eq_zero.mp h2).resolve_left hi'
  have hepsimg : φ (Jrep.eps a c) = t' • Jrep.eps a c' := by
    have h := Jrep.eq_smul_one_add_smul_eps a c' (φ (Jrep.eps a c))
    rw [hs', ht', hs'zero, zero_smul, zero_add] at h
    exact h
  have ht'ne : t' ≠ 0 := by
    intro h
    rw [h, zero_smul] at hepsimg
    exact jrep_eps_ne_zero a c (φ.injective (by rw [hepsimg, map_zero]))
  -- Surjectivity forces the `1`-coordinate of `φ 1` to be nonzero.
  have hsne : s ≠ 0 := by
    intro h
    obtain ⟨t, htdef⟩ : ∃ t, Jrep.snd a c' (φ 1) = t := ⟨_, rfl⟩
    have honeimg : φ 1 = t • Jrep.eps a c' := by
      have h0 := Jrep.eq_smul_one_add_smul_eps a c' (φ 1)
      rw [hs, htdef, h, zero_smul, zero_add] at h0
      exact h0
    obtain ⟨x, hx⟩ := φ.surjective (1 : Jrep a c')
    obtain ⟨p, q, hpq⟩ : ∃ p q : ℂ, x = p • (1 : Jrep a c) + q • Jrep.eps a c :=
      ⟨_, _, Jrep.eq_smul_one_add_smul_eps a c x⟩
    rw [hpq, map_add, map_smul_complex, map_smul_complex, honeimg, hepsimg, smul_smul,
      smul_smul, ← add_smul] at hx
    have hf := congrArg (Jrep.fst a c') hx
    simp at hf
  -- Testing the intertwining on `1` pins the scalar.
  have hkey : ∀ i, c i * t' = c' i * s := by
    intro i
    have h := hN i 1
    rw [mul_one, map_smul_complex, hepsimg, smul_smul, Jrep.eps_mul, hs, smul_smul] at h
    have h2 : (c i * t' - c' i * s) • Jrep.eps a c' = 0 := by rw [sub_smul, h, sub_self]
    exact sub_eq_zero.mp ((jrep_smul_eps_eq_zero_iff a c' _).mp h2)
  refine ⟨t' / s, div_ne_zero ht'ne hsne, funext fun i => ?_⟩
  simp only [Pi.smul_apply, smul_eq_mul]
  field_simp
  linear_combination -hkey i

/-- Scaling the `ε`-coordinate realizes proportional classes as isomorphic modules. -/
theorem jrep_iso_of_scalar (a c c' : Fin n → ℂ) (lam : ℂ) (hlam : lam ≠ 0) (hc' : c' = lam • c) :
    Nonempty (Jrep a c ≃ₗ[polyAlg n] Jrep a c') := by
  subst hc'
  set B' := (jrepBasis a (lam • c)).unitsSMul ![1, Units.mk0 lam hlam] with hB'
  set e := (jrepBasis a c).equiv B' (Equiv.refl (Fin 2)) with he
  have hB'0 : B' 0 = (1 : Jrep a (lam • c)) := by
    rw [hB', Module.Basis.unitsSMul_apply, jrepBasis_zero_eq]
    simp
  have hB'1 : B' 1 = lam • Jrep.eps a (lam • c) := by
    rw [hB', Module.Basis.unitsSMul_apply, jrepBasis_one_eq]
    simp [Units.smul_def]
  have he0b : e (jrepBasis a c 0) = (1 : Jrep a (lam • c)) := by
    rw [he, Module.Basis.equiv_apply, Equiv.refl_apply, hB'0]
  have he1b : e (jrepBasis a c 1) = lam • Jrep.eps a (lam • c) := by
    rw [he, Module.Basis.equiv_apply, Equiv.refl_apply, hB'1]
  have he0 : e (1 : Jrep a c) = (1 : Jrep a (lam • c)) := by
    rw [jrepBasis_zero_eq a c] at he0b; exact he0b
  have he1 : e (Jrep.eps a c) = lam • Jrep.eps a (lam • c) := by
    rw [jrepBasis_one_eq a c] at he1b; exact he1b
  haveI : SMulCommClass (polyAlg n) ℂ (Jrep a (lam • c)) := smulCommClass_polyAlg
  refine nonempty_linearEquiv_of_comm_X_basis (jrepBasis a c) e fun i j => ?_
  have h0 : e ((X i : polyAlg n) • jrepBasis a c 0)
      = (X i : polyAlg n) • e (jrepBasis a c 0) := by
    rw [he0b, jrep_X_smul_one a (lam • c) i, jrepBasis_zero_eq a c, jrep_X_smul_one a c i,
      map_add, map_smul, map_smul, he0, he1]
    simp only [Pi.smul_apply, smul_eq_mul, smul_smul]
    module
  have h1 : e ((X i : polyAlg n) • jrepBasis a c 1)
      = (X i : polyAlg n) • e (jrepBasis a c 1) := by
    rw [he1b, smul_comm (X i : polyAlg n) lam (Jrep.eps a (lam • c)),
      jrep_X_smul_eps a (lam • c) i, jrepBasis_one_eq a c, jrep_X_smul_eps a c i, map_smul, he1]
    module
  fin_cases j
  · exact h0
  · exact h1

end JrepIso

/-- Two dual-number normal forms are isomorphic exactly when they share the weight and their
extension classes are proportional. So the nonzero classes contribute the projective space of
`ℂⁿ`, and the zero class the split module `Vₐ × Vₐ`. -/
theorem jrep_iso_iff {n : ℕ} (a c a' c' : Fin n → ℂ) :
    Nonempty (Jrep a c ≃ₗ[polyAlg n] Jrep a' c') ↔
      a = a' ∧ ∃ lam : ℂ, lam ≠ 0 ∧ c' = lam • c := by
  constructor
  · rintro ⟨φ⟩
    have haa : a = a' := jrep_weight_eq a c a' c' φ
    subst haa
    refine ⟨rfl, ?_⟩
    by_cases hc' : c' = 0
    · have hc : c = 0 := jrep_class_eq_zero_of_target a c c' hc' φ
      exact ⟨1, one_ne_zero, by rw [hc, hc', smul_zero]⟩
    · exact jrep_exists_scalar a c c' hc' φ
  · rintro ⟨rfl, lam, hlam, hc'⟩
    exact jrep_iso_of_scalar a c c' lam hlam hc'

/-! ## Weights as an isomorphism invariant -/

section Weights

variable {n : ℕ}

/-- The set of weights of a module: those `a` admitting a nonzero simultaneous eigenvector for
all the generators, with `xᵢ` acting by `aᵢ`. -/
def Weights (M : Type*) [AddCommGroup M] [Module ℂ M] [Module (polyAlg n) M] :
    Set (Fin n → ℂ) :=
  {a | ∃ m : M, m ≠ 0 ∧ ∀ i, (X i : polyAlg n) • m = a i • m}

variable {M N : Type*}
  [AddCommGroup M] [Module ℂ M] [Module (polyAlg n) M] [IsScalarTower ℂ (polyAlg n) M]
  [AddCommGroup N] [Module ℂ N] [Module (polyAlg n) N] [IsScalarTower ℂ (polyAlg n) N]

theorem weights_subset_of_linearEquiv (φ : M ≃ₗ[polyAlg n] N) :
    Weights (n := n) M ⊆ Weights (n := n) N := by
  rintro a ⟨m, hm, ha⟩
  refine ⟨φ m, fun h => hm (φ.injective (by rw [h, map_zero])), fun i => ?_⟩
  rw [← map_smul, ha i, map_smul_complex]

/-- Isomorphic modules have the same weights. -/
theorem weights_eq_of_linearEquiv (φ : M ≃ₗ[polyAlg n] N) :
    Weights (n := n) M = Weights (n := n) N :=
  Set.Subset.antisymm (weights_subset_of_linearEquiv φ)
    (weights_subset_of_linearEquiv φ.symm)

end Weights

/-- A dual-number module has the single weight `a`. -/
theorem weights_jrep {n : ℕ} (a c : Fin n → ℂ) : Weights (Jrep a c) = {a} := by
  apply Set.Subset.antisymm
  · rintro w ⟨x, hx, hw⟩
    funext i
    have h := hw i
    rw [jrep_X_smul, Jrep.eps_mul, smul_smul] at h
    have h1 := congrArg (Jrep.fst a c) h
    have h2 := congrArg (Jrep.snd a c) h
    simp only [Jrep.fst_add, Jrep.snd_add, Jrep.fst_smul, Jrep.snd_smul, Jrep.fst_eps,
      Jrep.snd_eps, mul_zero, mul_one, add_zero] at h1 h2
    by_cases hfx : Jrep.fst a c x = 0
    · have hsx : Jrep.snd a c x ≠ 0 := by
        intro hs
        exact hx (Jrep.ext a c (by simp [hfx]) (by simp [hs]))
      rw [hfx, mul_zero, add_zero] at h2
      exact (mul_right_cancel₀ hsx h2).symm
    · exact (mul_right_cancel₀ hfx h1).symm
  · rintro w hw
    rw [Set.mem_singleton_iff] at hw
    rw [hw]
    exact ⟨Jrep.eps a c, jrep_eps_ne_zero a c, fun i => jrep_X_smul_eps a c i⟩

/-- A direct sum of two one-dimensional representations has exactly the two weights. -/
theorem weights_vrep_prod {n : ℕ} (b a : Fin n → ℂ) :
    Weights (Vrep b × Vrep a) = {b, a} := by
  have hXb : ∀ (i : Fin n) (x : Vrep b), (X i : polyAlg n) • x = b i • x := by
    intro i x; rw [Vrep_smul_eq]; simp
  have hXa : ∀ (i : Fin n) (y : Vrep a), (X i : polyAlg n) • y = a i • y := by
    intro i y; rw [Vrep_smul_eq]; simp
  apply Set.Subset.antisymm
  · rintro w ⟨⟨x, y⟩, hxy, hw⟩
    by_cases hx : x = 0
    · have hy : y ≠ 0 := fun h => hxy (Prod.ext hx h)
      refine Or.inr (funext fun i => ?_)
      have h2 : (X i : polyAlg n) • y = w i • y := congrArg Prod.snd (hw i)
      rw [hXa i y] at h2
      have h3 : (a i - w i) • y = 0 := by rw [sub_smul, h2, sub_self]
      exact (sub_eq_zero.mp ((smul_eq_zero.mp h3).resolve_right hy)).symm
    · refine Or.inl (funext fun i => ?_)
      have h1 : (X i : polyAlg n) • x = w i • x := congrArg Prod.fst (hw i)
      rw [hXb i x] at h1
      have h3 : (b i - w i) • x = 0 := by rw [sub_smul, h1, sub_self]
      exact (sub_eq_zero.mp ((smul_eq_zero.mp h3).resolve_right hx)).symm
  · rintro w hw
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hw
    rcases hw with hw | hw
    · subst w
      refine ⟨(Submodule.Quotient.mk 1, 0), fun h => ?_, fun i => ?_⟩
      · exact quot_mk_one_ne_zero b (Prod.mk_eq_zero.mp h).1
      · exact Prod.ext (hXb i _) (by simp)
    · subst w
      refine ⟨(0, Submodule.Quotient.mk 1), fun h => ?_, fun i => ?_⟩
      · exact quot_mk_one_ne_zero a (Prod.mk_eq_zero.mp h).2
      · exact Prod.ext (by simp) (hXa i _)

/-- The split normal forms are isomorphic exactly when their weights agree as unordered pairs. -/
theorem split_iso_iff {n : ℕ} (b a b' a' : Fin n → ℂ) :
    Nonempty ((Vrep b × Vrep a) ≃ₗ[polyAlg n] Vrep b' × Vrep a') ↔
      (b = b' ∧ a = a') ∨ (b = a' ∧ a = b') := by
  constructor
  · rintro ⟨φ⟩
    have h := weights_eq_of_linearEquiv φ
    rw [weights_vrep_prod, weights_vrep_prod] at h
    exact Set.pair_eq_pair_iff.mp h
  · rintro (⟨rfl, rfl⟩ | ⟨rfl, rfl⟩)
    · exact ⟨LinearEquiv.refl _ _⟩
    · exact ⟨LinearEquiv.prodComm (polyAlg n) (Vrep b) (Vrep a)⟩

/-- A split module with distinct weights is never a dual-number module: it has two weights,
whereas `Jrep a' c'` has only the weight `a'`. -/
theorem split_not_iso_jrep {n : ℕ} (b a a' c' : Fin n → ℂ) (hba : b ≠ a) :
    ¬ Nonempty ((Vrep b × Vrep a) ≃ₗ[polyAlg n] Jrep a' c') := by
  rintro ⟨φ⟩
  have h := weights_eq_of_linearEquiv φ
  rw [weights_vrep_prod, weights_jrep] at h
  have hmem : ∀ w : Fin n → ℂ, w ∈ ({b, a} : Set (Fin n → ℂ)) → w = a' := by
    intro w hwmem
    rw [h, Set.mem_singleton_iff] at hwmem
    exact hwmem
  exact hba ((hmem b (by simp)).trans (hmem a (by simp)).symm)

end Etingof.Problem3_9_2
