import Mathlib

/-!
# The Jacobson radical of a tensor product of algebras

The proof of Theorem 3.10.2(ii) in Etingof reduces to finite-dimensional algebras and then
asserts, for `A`, `B` finite dimensional over the (algebraically closed) ground field `k`,

  `Rad(A ⊗ B) = Rad(A) ⊗ B + A ⊗ Rad(B)`,

together with the resulting identification

  `(A ⊗ B)/Rad(A ⊗ B) = (A/Rad(A)) ⊗ (B/Rad(B))`.

This file formalizes both.

## Book statement (Etingof, proof of Theorem 3.10.2)

> Indeed, denote the latter by `J`. Then `J` is a nilpotent ideal in `A ⊗ B`, as `Rad(A)` and
> `Rad(B)` are nilpotent. On the other hand, `(A ⊗ B)/J = (A/Rad(A)) ⊗ (B/Rad(B))`, which is a
> product of two semisimple algebras, hence semisimple. This implies `J ⊃ Rad(A ⊗ B)`.
> Altogether, by Proposition 3.5.3, we see that `J = Rad(A ⊗ B)`.

## Scope

The book's ambient algebras in Theorem 3.10.2 need not be finite dimensional; the proof first
replaces them by their finite-dimensional image algebras (see `Theorem3_10_2.lean`, which takes
a different density/Artinian route to the same theorem). The radical formula proved here is for
finite-dimensional algebras, and the `⊇` inclusion additionally needs semisimplicity of
`(A/Rad A) ⊗ (B/Rad B)`, which is where algebraic closure of `k` enters: over a general field
the tensor product of two semisimple algebras need not be semisimple (e.g.
`ℂ ⊗_ℝ ℂ` is semisimple but `𝔽_p(t^{1/p}) ⊗_{𝔽_p(t)} 𝔽_p(t^{1/p})` is not).

The two inclusions are therefore proved under different hypotheses and packaged separately:

* `Etingof.radTensorSum_le_jacobson` — the easy inclusion, needs only nilpotence of the two
  radicals (so: finite dimensionality, no hypothesis on `k`).
* `Etingof.jacobson_le_radTensorSum` — the hard inclusion, needs `(A/Rad A) ⊗ (B/Rad B)`
  semisimple.
* `Etingof.jacobson_tensorProduct_eq` — the book's identity, over an algebraically closed `k`.

## Main declarations

* `Etingof.radTensorLeft`, `Etingof.radTensorRight` — the ideals `Rad(A) ⊗ B` and `A ⊗ Rad(B)`
  of `A ⊗[k] B`, defined as the ideals generated by the images of the two radicals.
* `Etingof.radTensorSum` — their sum `J`.
* `Etingof.tensorRadQuot` — the surjection `A ⊗ B ↠ (A/Rad A) ⊗ (B/Rad B)`.
* `Etingof.radTensorSum_eq_ker` — `J` is exactly the kernel of that surjection.
* `Etingof.quotientRadTensorSumEquiv` — `(A ⊗ B)/J ≃ₐ[k] (A/Rad A) ⊗ (B/Rad B)`.
* `Etingof.jacobson_tensorProduct_eq` — `Rad(A ⊗ B) = J` for finite-dimensional `A`, `B` over an
  algebraically closed `k`.
* `Etingof.quotientJacobsonTensorEquiv` — the displayed quotient identification
  `(A ⊗ B)/Rad(A ⊗ B) ≃ₐ[k] (A/Rad A) ⊗ (B/Rad B)`.
-/

namespace Etingof

open scoped TensorProduct

section Defs

variable (k A B : Type*) [Field k] [Ring A] [Ring B] [Algebra k A] [Algebra k B]

/-- The canonical surjection `A ⊗ B ↠ (A/Rad A) ⊗ (B/Rad B)`, the tensor product of the two
quotient maps. Its kernel is `Rad(A) ⊗ B + A ⊗ Rad(B)` (`Etingof.radTensorSum_eq_ker`). -/
noncomputable def tensorRadQuot :
    A ⊗[k] B →ₐ[k] (A ⧸ Ring.jacobson A) ⊗[k] (B ⧸ Ring.jacobson B) :=
  Algebra.TensorProduct.map (Ideal.Quotient.mkₐ k (Ring.jacobson A))
    (Ideal.Quotient.mkₐ k (Ring.jacobson B))

/-- The ideal `Rad(A) ⊗ B` of `A ⊗[k] B`: the ideal generated by `{a ⊗ 1 | a ∈ Rad A}`. -/
noncomputable def radTensorLeft : Ideal (A ⊗[k] B) :=
  Ideal.map (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := B))
    (Ring.jacobson A)

/-- The ideal `A ⊗ Rad(B)` of `A ⊗[k] B`: the ideal generated by `{1 ⊗ b | b ∈ Rad B}`. -/
noncomputable def radTensorRight : Ideal (A ⊗[k] B) :=
  Ideal.map (Algebra.TensorProduct.includeRight (R := k) (A := A) (B := B)) (Ring.jacobson B)

/-- The ideal `J = Rad(A) ⊗ B + A ⊗ Rad(B)` of `A ⊗[k] B` appearing in the proof of
Theorem 3.10.2. -/
noncomputable def radTensorSum : Ideal (A ⊗[k] B) :=
  radTensorLeft k A B ⊔ radTensorRight k A B

end Defs

section Basic

variable {k A B : Type*} [Field k] [Ring A] [Ring B] [Algebra k A] [Algebra k B]

@[simp]
theorem tensorRadQuot_tmul (a : A) (b : B) :
    tensorRadQuot k A B (a ⊗ₜ[k] b) =
      (Ideal.Quotient.mk (Ring.jacobson A) a) ⊗ₜ[k] (Ideal.Quotient.mk (Ring.jacobson B) b) :=
  rfl

theorem tensorRadQuot_surjective : Function.Surjective (tensorRadQuot k A B) :=
  Algebra.TensorProduct.map_surjective _ _ Ideal.Quotient.mk_surjective
    Ideal.Quotient.mk_surjective

/-- `J` is exactly the kernel of `A ⊗ B ↠ (A/Rad A) ⊗ (B/Rad B)`. This is the precise form of
the book's `(A ⊗ B)/J = (A/Rad(A)) ⊗ (B/Rad(B))`. -/
theorem radTensorSum_eq_ker :
    radTensorSum k A B = RingHom.ker (tensorRadQuot k A B) := by
  have hA : RingHom.ker (Ideal.Quotient.mkₐ k (Ring.jacobson A)) = Ring.jacobson A :=
    Ideal.mk_ker
  have hB : RingHom.ker (Ideal.Quotient.mkₐ k (Ring.jacobson B)) = Ring.jacobson B :=
    Ideal.mk_ker
  rw [tensorRadQuot, Algebra.TensorProduct.map_ker _ _ Ideal.Quotient.mk_surjective
    Ideal.Quotient.mk_surjective, hA, hB]
  rfl

instance : (radTensorSum k A B).IsTwoSided := by
  rw [radTensorSum_eq_ker]; infer_instance

/-- The book's displayed identification `(A ⊗ B)/J ≅ (A/Rad A) ⊗ (B/Rad B)`. -/
noncomputable def quotientRadTensorSumEquiv :
    ((A ⊗[k] B) ⧸ radTensorSum k A B) ≃ₐ[k]
      (A ⧸ Ring.jacobson A) ⊗[k] (B ⧸ Ring.jacobson B) :=
  (Ideal.quotientEquivAlgOfEq k radTensorSum_eq_ker).trans
    (Ideal.quotientKerAlgEquivOfSurjective tensorRadQuot_surjective)

end Basic

section Nilpotent

/-- **A nilpotent ideal is contained in the Jacobson radical.** Mathlib has this only for
commutative rings (`Ideal.radical_le_jacobson`, `nilradical_le_jacobson`); the argument here is
the usual one and works over any ring: for `x ∈ I` and any `y`, the product `y * x` lies in the
left ideal `I`, hence is nilpotent, so `1 + y * x` is a unit, which is exactly the unit
criterion `Ideal.mem_jacobson_iff` for membership in `Ring.jacobson`. -/
theorem le_jacobson_of_isNilpotent {R : Type*} [Ring R] {I : Ideal R} (h : IsNilpotent I) :
    I ≤ Ring.jacobson R := by
  obtain ⟨n, hn⟩ := h
  intro x hx
  rw [← Ideal.jacobson_bot, Ideal.mem_jacobson_iff]
  intro y
  have hyx : y * x ∈ I := I.mul_mem_left y hx
  have hpow : (y * x) ^ n ∈ I ^ n := Ideal.pow_mem_pow hyx n
  rw [hn] at hpow
  have hnil : IsNilpotent (-(y * x)) :=
    IsNilpotent.neg (⟨n, by simpa using hpow⟩ : IsNilpotent (y * x))
  obtain ⟨u, hu⟩ := IsNilpotent.isUnit_one_sub hnil
  refine ⟨(↑u⁻¹ : R), ?_⟩
  have h1 : (↑u⁻¹ : R) * (1 + y * x) = 1 := by
    rw [show (1 : R) + y * x = (u : R) by rw [hu, sub_neg_eq_add]]
    exact u.inv_mul
  have h2 : (↑u⁻¹ : R) * y * x + (↑u⁻¹ : R) = (↑u⁻¹ : R) * (1 + y * x) := by noncomm_ring
  rw [h2, h1, sub_self]
  exact Ideal.zero_mem _

variable {k A B : Type*} [Field k] [Ring A] [Ring B] [Algebra k A] [Algebra k B]
variable [FiniteDimensional k A] [FiniteDimensional k B]

/-- "`J` is a nilpotent ideal in `A ⊗ B`, as `Rad(A)` and `Rad(B)` are nilpotent." -/
theorem isNilpotent_radTensorSum : IsNilpotent (radTensorSum k A B) := by
  sorry

/-- The easy inclusion `Rad(A) ⊗ B + A ⊗ Rad(B) ⊆ Rad(A ⊗ B)`: a nilpotent two-sided ideal is
contained in the Jacobson radical. No hypothesis on `k` beyond finite dimensionality. -/
theorem radTensorSum_le_jacobson :
    radTensorSum k A B ≤ Ring.jacobson (A ⊗[k] B) :=
  le_jacobson_of_isNilpotent isNilpotent_radTensorSum

end Nilpotent

section Semisimple

variable {k A B : Type*} [Field k] [Ring A] [Ring B] [Algebra k A] [Algebra k B]

/-- The hard inclusion `Rad(A ⊗ B) ⊆ J`: "`(A ⊗ B)/J = (A/Rad A) ⊗ (B/Rad B)`, which is
semisimple. This implies `J ⊃ Rad(A ⊗ B)`." Stated with the semisimplicity as an explicit
hypothesis, since over a general field it can fail. Note that no finiteness is needed here:
all the finiteness is in the other inclusion. -/
theorem jacobson_le_radTensorSum
    (h : IsSemisimpleRing ((A ⧸ Ring.jacobson A) ⊗[k] (B ⧸ Ring.jacobson B))) :
    Ring.jacobson (A ⊗[k] B) ≤ radTensorSum k A B := by
  have hq : IsSemisimpleRing ((A ⊗[k] B) ⧸ radTensorSum k A B) :=
    (quotientRadTensorSumEquiv (k := k) (A := A) (B := B)).symm.toRingEquiv.isSemisimpleRing
  exact Ring.jacobson_le_of_eq_bot (IsSemisimpleRing.jacobson_eq_bot _)

end Semisimple

section AlgClosed

variable {k : Type*} [Field k] [IsAlgClosed k]

/-- Over an algebraically closed field, a finite-dimensional semisimple algebra is a finite
product of matrix algebras over `k` itself: Wedderburn–Artin plus the fact that a
finite-dimensional division algebra over an algebraically closed field is the field. -/
theorem exists_algEquiv_pi_matrix (A : Type*) [Ring A] [Algebra k A] [FiniteDimensional k A]
    [IsSemisimpleRing A] :
    ∃ (n : ℕ) (d : Fin n → ℕ), (∀ i, NeZero (d i)) ∧
      Nonempty (A ≃ₐ[k] ∀ i, Matrix (Fin (d i)) (Fin (d i)) k) := by
  sorry

/-- **Over an algebraically closed field, the tensor product of two finite-dimensional
semisimple algebras is semisimple.** This is the "product of two semisimple algebras, hence
semisimple" step of the book's proof; it is exactly where algebraic closure is used. -/
theorem isSemisimpleRing_tensorProduct
    (A B : Type*) [Ring A] [Algebra k A] [FiniteDimensional k A] [IsSemisimpleRing A]
    [Ring B] [Algebra k B] [FiniteDimensional k B] [IsSemisimpleRing B] :
    IsSemisimpleRing (A ⊗[k] B) := by
  sorry

end AlgClosed

section Main

variable {k A B : Type*} [Field k] [IsAlgClosed k]
variable [Ring A] [Ring B] [Algebra k A] [Algebra k B]
variable [FiniteDimensional k A] [FiniteDimensional k B]

/-- **The radical of a tensor product** (Etingof, proof of Theorem 3.10.2):
`Rad(A ⊗ B) = Rad(A) ⊗ B + A ⊗ Rad(B)` for finite-dimensional algebras over an algebraically
closed field. -/
theorem jacobson_tensorProduct_eq :
    Ring.jacobson (A ⊗[k] B) = radTensorSum k A B := by
  -- `IsArtinianRing` does not fire from `FiniteDimensional k A` by instance search.
  haveI : IsArtinianRing A := IsArtinianRing.of_finite k A
  haveI : IsArtinianRing B := IsArtinianRing.of_finite k B
  haveI : FiniteDimensional k (A ⧸ Ring.jacobson A) :=
    Module.Finite.of_surjective (Ideal.Quotient.mkₐ k (Ring.jacobson A)).toLinearMap
      Ideal.Quotient.mk_surjective
  haveI : FiniteDimensional k (B ⧸ Ring.jacobson B) :=
    Module.Finite.of_surjective (Ideal.Quotient.mkₐ k (Ring.jacobson B)).toLinearMap
      Ideal.Quotient.mk_surjective
  exact le_antisymm (jacobson_le_radTensorSum (isSemisimpleRing_tensorProduct _ _))
    radTensorSum_le_jacobson

/-- **The displayed quotient identification** (Etingof, proof of Theorem 3.10.2):
`(A ⊗ B)/Rad(A ⊗ B) ≅ (A/Rad A) ⊗ (B/Rad B)`. -/
noncomputable def quotientJacobsonTensorEquiv :
    ((A ⊗[k] B) ⧸ Ring.jacobson (A ⊗[k] B)) ≃ₐ[k]
      (A ⧸ Ring.jacobson A) ⊗[k] (B ⧸ Ring.jacobson B) :=
  (Ideal.quotientEquivAlgOfEq k jacobson_tensorProduct_eq).trans quotientRadTensorSumEquiv

end Main

end Etingof
