import EtingofRepresentationTheory.Chapter6.Definition6_4_5
import EtingofRepresentationTheory.Chapter6.Lemma6_7_2
import EtingofRepresentationTheory.Chapter6.Remark6_4_4

/-!
# Remark 6.4.11: the Weyl group

> As a linear operator of `ℝⁿ`, `s_α` fixes any vector orthogonal to `α` and `s_α(α) = -α`.
> Therefore `s_α` is the reflection at the hyperplane orthogonal to `α` and in particular
> fixes `B`. The `sᵢ := s_{αᵢ}` generate a subgroup `W ⊆ O(ℝⁿ)`, which is called **the Weyl
> group** of `Γ`. Since for every `w ∈ W`, `w(αᵢ)` is a root, and since there are only
> finitely many roots, `W` has to be finite.

This file turns that paragraph into definitions and theorems.

## Contents

* `Etingof.rootReflection_apply_of_orthogonal` and `Etingof.rootReflection_apply_self` are the
  two displayed reflection identities: `s_α` fixes `α^⊥` and negates `α`.
* `Etingof.rootReflectionEquiv` packages `s_α` as a `ℤ`-linear automorphism of the root
  lattice (it is an involution, hence invertible), and
  `Etingof.rootReflection_dotProduct` says it preserves `B`.
* `Etingof.cartanOrthogonalGroup` is the orthogonal group of `(ℤⁿ, B)`, and
  `Etingof.weylGroup` is the subgroup generated by the simple reflections
  `Etingof.simpleReflectionEquiv`. `Etingof.weylGroup_le_cartanOrthogonalGroup` is the
  book's `W ⊆ O(ℝⁿ)`.
* `Etingof.IsRoot.weyl` : the root set is stable under `W`; in particular
  `Etingof.weyl_simpleRoot_isRoot` is the book's "`w(αᵢ)` is a root".
* `Etingof.Remark_6_4_11_weylGroup_finite` : `W` is finite. The argument is the book's: a
  Weyl group element is determined by its values on the simple roots (they are a basis of
  `ℤⁿ`), those values are roots, and there are only finitely many roots
  (`Etingof.Remark_6_4_4_roots_finite`).

## Lattice versus `ℝⁿ`

The book states the remark for operators on `ℝⁿ`. The rest of this chapter — roots
(Definition 6.4.3), simple roots (Definition 6.4.5), reflections (Definition 6.4.10),
Coxeter elements (Definition 6.7.1) — works on the root lattice `ℤⁿ`, so we do too:
`Etingof.cartanOrthogonalGroup` is the group of `ℤ`-linear automorphisms of `ℤⁿ`
preserving `B`, i.e. the orthogonal group of the lattice `(ℤⁿ, B)`. Because the simple
roots form a `ℤ`-basis of `ℤⁿ` and an `ℝ`-basis of `ℝⁿ`, restriction to the lattice is
injective on the subgroup of `O(ℝⁿ)` generated by the `sᵢ`, so no information is lost;
this is also what makes the finiteness argument work verbatim.
-/

namespace Etingof

open Matrix

variable {n : ℕ} {adj : Matrix (Fin n) (Fin n) ℤ}

/-! ## The Cartan bilinear form -/

/-- The bilinear form `B(x, y) = xᵀ A y` attached to the Cartan matrix `A = 2·Id - adj`.
(Etingof Definition 6.4.1) -/
def cartanForm (n : ℕ) (adj : Matrix (Fin n) (Fin n) ℤ) (x y : Fin n → ℤ) : ℤ :=
  dotProduct x ((cartanMatrix n adj).mulVec y)

lemma cartanForm_apply (x y : Fin n → ℤ) :
    cartanForm n adj x y = dotProduct x ((cartanMatrix n adj).mulVec y) := rfl

/-- A root is exactly a nonzero vector of `B`-square `2`. -/
lemma isRoot_iff_cartanForm {x : Fin n → ℤ} :
    IsRoot n adj x ↔ x ≠ 0 ∧ cartanForm n adj x x = 2 := Iff.rfl

/-! ## Reflection geometry (the two displayed identities) -/

section Reflection

variable {A : Matrix (Fin n) (Fin n) ℤ}

/-- Symmetry of `xᵀ A y` for a symmetric matrix `A`. -/
lemma dotProduct_mulVec_comm (hA : A.IsSymm) (x y : Fin n → ℤ) :
    dotProduct x (A.mulVec y) = dotProduct y (A.mulVec x) := by
  simp only [dotProduct, Matrix.mulVec, Finset.mul_sum]
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun j _ => ?_
  rw [show A j i = A i j from congr_fun (congr_fun hA i) j]
  ring

/-- **Remark 6.4.11**, first identity: `s_α` fixes every vector orthogonal to `α`. -/
theorem rootReflection_apply_of_orthogonal (α v : Fin n → ℤ)
    (h : dotProduct v (A.mulVec α) = 0) :
    rootReflection n A α v = v := by
  simp [rootReflection, h]

/-- **Remark 6.4.11**, second identity: `s_α(α) = -α` for any `α` with `B(α, α) = 2`
(in particular for any root). -/
theorem rootReflection_apply_self (α : Fin n → ℤ)
    (hα : dotProduct α (A.mulVec α) = 2) :
    rootReflection n A α α = -α := by
  ext j
  simp only [rootReflection, hα, Pi.sub_apply, Pi.smul_apply, Pi.neg_apply, smul_eq_mul]
  ring

/-- The coefficient `B(·, α)` changes sign under `s_α`. -/
private lemma dotProduct_rootReflection (α v : Fin n → ℤ)
    (hα : dotProduct α (A.mulVec α) = 2) :
    dotProduct (rootReflection n A α v) (A.mulVec α) = -dotProduct v (A.mulVec α) := by
  simp only [rootReflection, sub_dotProduct, smul_dotProduct, smul_eq_mul, hα]
  ring

/-- `s_α` is an involution. -/
theorem rootReflection_involutive (α : Fin n → ℤ)
    (hα : dotProduct α (A.mulVec α) = 2) (v : Fin n → ℤ) :
    rootReflection n A α (rootReflection n A α v) = v := by
  conv_lhs => rw [rootReflection, dotProduct_rootReflection α v hα, rootReflection]
  ext j
  simp only [Pi.sub_apply, Pi.smul_apply, smul_eq_mul, neg_mul]
  ring

lemma rootReflection_add (α u v : Fin n → ℤ) :
    rootReflection n A α (u + v) = rootReflection n A α u + rootReflection n A α v := by
  simp only [rootReflection, add_dotProduct, add_smul]
  abel

lemma rootReflection_smul (α : Fin n → ℤ) (c : ℤ) (v : Fin n → ℤ) :
    rootReflection n A α (c • v) = c • rootReflection n A α v := by
  simp only [rootReflection, smul_dotProduct, smul_eq_mul, mul_smul, smul_sub]

/-- The reflection `s_α` as a `ℤ`-linear automorphism of the root lattice `ℤⁿ`.

This is the "linear operator of `ℝⁿ`" of Remark 6.4.11, on the lattice; it is invertible
because it is an involution (`Etingof.rootReflection_involutive`). -/
def rootReflectionEquiv (n : ℕ) (A : Matrix (Fin n) (Fin n) ℤ) (α : Fin n → ℤ)
    (hα : dotProduct α (A.mulVec α) = 2) : (Fin n → ℤ) ≃ₗ[ℤ] (Fin n → ℤ) where
  toFun := rootReflection n A α
  map_add' := rootReflection_add α
  map_smul' := rootReflection_smul α
  invFun := rootReflection n A α
  left_inv := rootReflection_involutive α hα
  right_inv := rootReflection_involutive α hα

@[simp]
lemma rootReflectionEquiv_apply (α : Fin n → ℤ)
    (hα : dotProduct α (A.mulVec α) = 2) (v : Fin n → ℤ) :
    rootReflectionEquiv n A α hα v = rootReflection n A α v := rfl

@[simp]
lemma rootReflectionEquiv_symm (α : Fin n → ℤ)
    (hα : dotProduct α (A.mulVec α) = 2) :
    (rootReflectionEquiv n A α hα).symm = rootReflectionEquiv n A α hα := rfl

/-- **Remark 6.4.11**: `s_α` "fixes `B`", i.e. it is an isometry of the bilinear form. -/
theorem rootReflection_dotProduct (hA : A.IsSymm) (α : Fin n → ℤ)
    (hα : dotProduct α (A.mulVec α) = 2) (v w : Fin n → ℤ) :
    dotProduct (rootReflection n A α v) (A.mulVec (rootReflection n A α w)) =
      dotProduct v (A.mulVec w) := by
  have hαw : dotProduct α (A.mulVec w) = dotProduct w (A.mulVec α) :=
    dotProduct_mulVec_comm hA α w
  have hαα : dotProduct α (A.mulVec α) = 2 := hα
  simp only [rootReflection, Matrix.mulVec_sub, Matrix.mulVec_smul, sub_dotProduct,
    dotProduct_sub, smul_dotProduct, dotProduct_smul, smul_eq_mul, hαw, hαα]
  ring

end Reflection

/-! ## The orthogonal group of the root lattice -/

/-- The orthogonal group of the lattice `(ℤⁿ, B)`: the `ℤ`-linear automorphisms of `ℤⁿ`
preserving the Cartan bilinear form. This is the lattice-level counterpart of the book's
`O(ℝⁿ)` in Remark 6.4.11. -/
def cartanOrthogonalGroup (n : ℕ) (adj : Matrix (Fin n) (Fin n) ℤ) :
    Subgroup ((Fin n → ℤ) ≃ₗ[ℤ] (Fin n → ℤ)) where
  carrier := {f | ∀ v w, cartanForm n adj (f v) (f w) = cartanForm n adj v w}
  mul_mem' {f g} hf hg := fun v w => by
    change cartanForm n adj (f (g v)) (f (g w)) = cartanForm n adj v w
    rw [hf (g v) (g w), hg v w]
  one_mem' := fun _ _ => rfl
  inv_mem' {f} hf := fun v w => by
    have := hf (f.symm v) (f.symm w)
    rwa [f.apply_symm_apply, f.apply_symm_apply, eq_comm] at this

lemma mem_cartanOrthogonalGroup_iff {f : (Fin n → ℤ) ≃ₗ[ℤ] (Fin n → ℤ)} :
    f ∈ cartanOrthogonalGroup n adj ↔
      ∀ v w, cartanForm n adj (f v) (f w) = cartanForm n adj v w := Iff.rfl

/-! ## The Weyl group -/

/-- The `i`-th simple reflection `sᵢ = s_{αᵢ}` as a linear automorphism of the root
lattice. (Etingof Definition 6.4.10, Remark 6.4.11) -/
def simpleReflectionEquiv (hDynkin : IsDynkinDiagram n adj) (i : Fin n) :
    (Fin n → ℤ) ≃ₗ[ℤ] (Fin n → ℤ) :=
  rootReflectionEquiv n (cartanMatrix n adj) (simpleRoot n i) (simpleRoot_B_eq_two hDynkin i)

@[simp]
lemma simpleReflectionEquiv_apply (hDynkin : IsDynkinDiagram n adj) (i : Fin n)
    (v : Fin n → ℤ) :
    simpleReflectionEquiv hDynkin i v = simpleReflection n (cartanMatrix n adj) i v := rfl

/-- Each simple reflection has order dividing `2`; it is the identity only in degenerate
situations, and squares to the identity always. -/
@[simp]
lemma simpleReflectionEquiv_mul_self (hDynkin : IsDynkinDiagram n adj) (i : Fin n) :
    simpleReflectionEquiv hDynkin i * simpleReflectionEquiv hDynkin i = 1 := by
  refine LinearEquiv.ext fun v => ?_
  exact rootReflection_involutive _ (simpleRoot_B_eq_two hDynkin i) v

/-- `sᵢ(αᵢ) = -αᵢ`. -/
lemma simpleReflectionEquiv_apply_simpleRoot (hDynkin : IsDynkinDiagram n adj) (i : Fin n) :
    simpleReflectionEquiv hDynkin i (simpleRoot n i) = -simpleRoot n i :=
  rootReflection_apply_self _ (simpleRoot_B_eq_two hDynkin i)

/-- `sᵢ` fixes every vector orthogonal to `αᵢ`. -/
lemma simpleReflectionEquiv_apply_of_orthogonal (hDynkin : IsDynkinDiagram n adj) (i : Fin n)
    (v : Fin n → ℤ) (h : cartanForm n adj v (simpleRoot n i) = 0) :
    simpleReflectionEquiv hDynkin i v = v :=
  rootReflection_apply_of_orthogonal _ _ h

/-- **The Weyl group** `W` of `Γ`: the subgroup of the orthogonal group of the root lattice
generated by the simple reflections `sᵢ`. (Etingof Remark 6.4.11) -/
def weylGroup (hDynkin : IsDynkinDiagram n adj) :
    Subgroup ((Fin n → ℤ) ≃ₗ[ℤ] (Fin n → ℤ)) :=
  Subgroup.closure (Set.range (simpleReflectionEquiv hDynkin))

lemma simpleReflectionEquiv_mem_weylGroup (hDynkin : IsDynkinDiagram n adj) (i : Fin n) :
    simpleReflectionEquiv hDynkin i ∈ weylGroup hDynkin :=
  Subgroup.subset_closure ⟨i, rfl⟩

lemma simpleReflectionEquiv_mem_cartanOrthogonalGroup (hDynkin : IsDynkinDiagram n adj)
    (i : Fin n) :
    simpleReflectionEquiv hDynkin i ∈ cartanOrthogonalGroup n adj := fun v w =>
  rootReflection_dotProduct (cartanMatrix_isSymm hDynkin.1) _
    (simpleRoot_B_eq_two hDynkin i) v w

/-- **Remark 6.4.11**: `W ⊆ O`, i.e. every Weyl group element preserves `B`. -/
theorem weylGroup_le_cartanOrthogonalGroup (hDynkin : IsDynkinDiagram n adj) :
    weylGroup hDynkin ≤ cartanOrthogonalGroup n adj := by
  rw [weylGroup, Subgroup.closure_le]
  rintro _ ⟨i, rfl⟩
  exact simpleReflectionEquiv_mem_cartanOrthogonalGroup hDynkin i

theorem weylGroup_cartanForm (hDynkin : IsDynkinDiagram n adj)
    {w : (Fin n → ℤ) ≃ₗ[ℤ] (Fin n → ℤ)} (hw : w ∈ weylGroup hDynkin) (v u : Fin n → ℤ) :
    cartanForm n adj (w v) (w u) = cartanForm n adj v u :=
  weylGroup_le_cartanOrthogonalGroup hDynkin hw v u

/-! ## The Weyl group permutes the roots -/

/-- Every simple root is a root: `B(αᵢ, αᵢ) = Aᵢᵢ = 2`. -/
theorem isRoot_simpleRoot (hDynkin : IsDynkinDiagram n adj) (i : Fin n) :
    IsRoot n adj (simpleRoot n i) := by
  refine ⟨?_, simpleRoot_B_eq_two hDynkin i⟩
  intro h
  have := congr_fun h i
  simp [simpleRoot] at this

/-- **Remark 6.4.11**: the root set is stable under the Weyl group. -/
theorem IsRoot.weyl (hDynkin : IsDynkinDiagram n adj)
    {w : (Fin n → ℤ) ≃ₗ[ℤ] (Fin n → ℤ)} (hw : w ∈ weylGroup hDynkin)
    {x : Fin n → ℤ} (hx : IsRoot n adj x) : IsRoot n adj (w x) := by
  refine ⟨?_, ?_⟩
  · intro h
    exact hx.1 ((LinearEquiv.map_eq_zero_iff w).mp h)
  · exact (weylGroup_cartanForm hDynkin hw x x).trans hx.2

theorem weylGroup_mapsTo_roots (hDynkin : IsDynkinDiagram n adj)
    {w : (Fin n → ℤ) ≃ₗ[ℤ] (Fin n → ℤ)} (hw : w ∈ weylGroup hDynkin) :
    Set.MapsTo w {x : Fin n → ℤ | IsRoot n adj x} {x : Fin n → ℤ | IsRoot n adj x} :=
  fun _ hx => IsRoot.weyl hDynkin hw hx

/-- **Remark 6.4.11**: "for every `w ∈ W`, `w(αᵢ)` is a root". -/
theorem weyl_simpleRoot_isRoot (hDynkin : IsDynkinDiagram n adj)
    {w : (Fin n → ℤ) ≃ₗ[ℤ] (Fin n → ℤ)} (hw : w ∈ weylGroup hDynkin) (i : Fin n) :
    IsRoot n adj (w (simpleRoot n i)) :=
  IsRoot.weyl hDynkin hw (isRoot_simpleRoot hDynkin i)

/-! ## The permutation action on the root set, and finiteness -/

/-- The inverse of a Weyl group element also maps roots to roots. -/
theorem IsRoot.weyl_symm (hDynkin : IsDynkinDiagram n adj) (w : weylGroup hDynkin)
    {x : Fin n → ℤ} (hx : IsRoot n adj x) :
    IsRoot n adj ((w : (Fin n → ℤ) ≃ₗ[ℤ] (Fin n → ℤ)).symm x) :=
  IsRoot.weyl hDynkin (w⁻¹).2 hx

/-- A Weyl group element, viewed as a permutation of the (finite) root set. -/
def weylRootEquiv (hDynkin : IsDynkinDiagram n adj) (w : weylGroup hDynkin) :
    Equiv.Perm {x : Fin n → ℤ | IsRoot n adj x} where
  toFun x := ⟨(w : (Fin n → ℤ) ≃ₗ[ℤ] (Fin n → ℤ)) x, IsRoot.weyl hDynkin w.2 x.2⟩
  invFun x := ⟨(w : (Fin n → ℤ) ≃ₗ[ℤ] (Fin n → ℤ)).symm x, IsRoot.weyl_symm hDynkin w x.2⟩
  left_inv _ := Subtype.ext (LinearEquiv.symm_apply_apply _ _)
  right_inv _ := Subtype.ext (LinearEquiv.apply_symm_apply _ _)

@[simp]
lemma weylRootEquiv_apply_coe (hDynkin : IsDynkinDiagram n adj) (w : weylGroup hDynkin)
    (x : {x : Fin n → ℤ | IsRoot n adj x}) :
    (weylRootEquiv hDynkin w x : Fin n → ℤ) = (w : (Fin n → ℤ) ≃ₗ[ℤ] (Fin n → ℤ)) x := rfl

/-- **Remark 6.4.11**: the Weyl group acts on the root set by permutations. -/
def weylRootPerm (hDynkin : IsDynkinDiagram n adj) :
    weylGroup hDynkin →* Equiv.Perm {x : Fin n → ℤ | IsRoot n adj x} where
  toFun := weylRootEquiv hDynkin
  map_one' := by ext x; rfl
  map_mul' _ _ := by ext x; rfl

/-- A `ℤ`-linear automorphism of `ℤⁿ` is determined by its values on the simple roots,
which form a basis of the lattice (Definition 6.4.5). -/
theorem linearEquiv_eq_of_simpleRoot (f g : (Fin n → ℤ) ≃ₗ[ℤ] (Fin n → ℤ))
    (h : ∀ i, f (simpleRoot n i) = g (simpleRoot n i)) : f = g := by
  apply LinearEquiv.toLinearMap_injective
  refine (Pi.basisFun ℤ (Fin n)).ext fun i => ?_
  simpa [simpleRoot, Pi.basisFun_apply] using h i

/-- The action of the Weyl group on the root set is **faithful**: a Weyl group element is
determined by its values on the simple roots, and those are roots. -/
theorem weylRootPerm_injective (hDynkin : IsDynkinDiagram n adj) :
    Function.Injective (weylRootPerm hDynkin) := by
  intro w₁ w₂ h
  refine Subtype.ext (linearEquiv_eq_of_simpleRoot _ _ fun i => ?_)
  have := congrArg (fun σ => (σ ⟨simpleRoot n i, isRoot_simpleRoot hDynkin i⟩ : _)) h
  exact congrArg Subtype.val this

/-- **Remark 6.4.11**: the Weyl group is finite.

The book's argument, verbatim: `W` acts faithfully on the root set (a Weyl group element is
determined by the vectors `w(αᵢ)`, since the simple roots are a basis of `ℤⁿ`, and each
`w(αᵢ)` is a root), and there are only finitely many roots (Remark 6.4.4). So `W` embeds in
the finite group of permutations of the root set. -/
theorem Remark_6_4_11_weylGroup_finite (hDynkin : IsDynkinDiagram n adj) :
    Finite (weylGroup hDynkin) := by
  have hfin : Set.Finite {x : Fin n → ℤ | IsRoot n adj x} :=
    Remark_6_4_4_roots_finite hDynkin
  have : Finite {x : Fin n → ℤ | IsRoot n adj x} := hfin.to_subtype
  exact Finite.of_injective _ (weylRootPerm_injective hDynkin)

/-- The Weyl group is finite as a `Fintype` (noncomputably). -/
noncomputable instance fintypeWeylGroup (hDynkin : IsDynkinDiagram n adj) :
    Fintype (weylGroup hDynkin) :=
  @Fintype.ofFinite _ (Remark_6_4_11_weylGroup_finite hDynkin)

/-! ## Connection with the iterated-reflection machinery

Definition 6.7.1 and Lemma 6.7.2 act on the root lattice by iterating simple reflections
along a list of vertices (`Etingof.iteratedSimpleReflection`, and the Coxeter element as the
special case of an ordering of all vertices). Every such operator is a Weyl group element. -/

theorem exists_mem_weylGroup_eq_iteratedSimpleReflection (hDynkin : IsDynkinDiagram n adj)
    (l : List (Fin n)) :
    ∃ w ∈ weylGroup hDynkin,
      ∀ v, w v = iteratedSimpleReflection n (cartanMatrix n adj) l v := by
  induction l with
  | nil => exact ⟨1, one_mem _, fun _ => rfl⟩
  | cons i rest ih =>
    obtain ⟨w, hw, hwv⟩ := ih
    refine ⟨w * simpleReflectionEquiv hDynkin i,
      mul_mem hw (simpleReflectionEquiv_mem_weylGroup hDynkin i), fun v => ?_⟩
    change w (simpleReflectionEquiv hDynkin i v) = _
    rw [hwv]
    rfl

/-- Every ordered composition of simple reflections is a Weyl group element. -/
theorem exists_mem_weylGroup_eq_foldr (hDynkin : IsDynkinDiagram n adj) (l : List (Fin n)) :
    ∃ w ∈ weylGroup hDynkin, ∀ v,
      w v = (l.map (fun i => simpleReflection n (cartanMatrix n adj) i)).foldr (· ∘ ·) id v := by
  induction l with
  | nil => exact ⟨1, one_mem _, fun _ => rfl⟩
  | cons i rest ih =>
    obtain ⟨w, hw, hwv⟩ := ih
    refine ⟨simpleReflectionEquiv hDynkin i * w,
      mul_mem (simpleReflectionEquiv_mem_weylGroup hDynkin i) hw, fun v => ?_⟩
    change simpleReflectionEquiv hDynkin i (w v) = _
    rw [hwv v]
    rfl

/-- The Coxeter element of Definition 6.7.1 lies in the Weyl group. -/
theorem exists_mem_weylGroup_eq_coxeterElement (hDynkin : IsDynkinDiagram n adj) :
    ∃ w ∈ weylGroup hDynkin, ∀ v, w v = coxeterElement n adj v := by
  obtain ⟨w, hw, hwv⟩ := exists_mem_weylGroup_eq_foldr hDynkin (List.finRange n)
  refine ⟨w, hw, fun v => ?_⟩
  rw [hwv v, coxeterElement, List.ofFn_eq_map]

end Etingof
