import Mathlib

/-!
# Lemma 5.18.3: Symmetric Power Generation

Two key generation results:

(i) S^n U (the n-th symmetric power) is spanned by elements of the form
    u ⊗ u ⊗ ... ⊗ u (n times) for u ∈ U. This follows from the fact that
    S^n U is an irreducible GL(U)-module (equivalently, by polarization).

(ii) S^n A (for an algebra A) is generated as an algebra by elements Δ_n(a)
     for a ∈ A, where Δ_n(a) = a⊗1⊗...⊗1 + 1⊗a⊗...⊗1 + ... + 1⊗...⊗1⊗a.
     This follows from the fundamental theorem of symmetric functions.

## Mathlib correspondence

- `SymmetricPower` for S^n U (quotient of `PiTensorProduct` by permutations)
- `SymmetricPower.tprod` for the canonical multilinear map to the symmetric power
- `Submodule.span` for module generation
- The algebra structure on S^n A is not yet in Mathlib (listed as TODO).
  Part (ii) is stated in terms of the subalgebra generated by diagonal operators
  in End(V^⊗n), which captures the same content in the representation-theoretic
  context where this lemma is applied.
-/

open scoped TensorProduct

namespace Etingof.Lemma5_18_3

section Span

variable (k : Type) [Field k]
  (U : Type*) [AddCommGroup U] [Module k U] [Module.Finite k U]
  (n : ℕ)

/-- The set of n-fold diagonal symmetric tensors u^⊗n for u ∈ U.
These are elements of S^n U of the form u ⊗ u ⊗ ... ⊗ u (n times). -/
def diagonalTensors : Set (Sym[k]^n U) :=
  Set.range (fun u : U => SymmetricPower.tprod k (fun (_ : Fin n) => u))

/-- Alternating sum of (-1)^|S| over subsets of a nonempty finset is zero.
This is the fundamental Möbius identity on the boolean lattice. -/
private lemma sum_powerset_neg_one_pow_card_eq_zero
    {α : Type*} {x : Finset α} (hx : x.Nonempty) :
    (∑ m ∈ x.powerset, (-1 : k) ^ m.card) = 0 := by
  have hZ := Finset.sum_powerset_neg_one_pow_card_of_nonempty hx
  -- Cast the ℤ identity to k
  have : (∑ m ∈ x.powerset, (-1 : k) ^ m.card) =
      ((∑ m ∈ x.powerset, (-1 : ℤ) ^ m.card : ℤ) : k) := by
    rw [Int.cast_sum]
    congr 1; ext m
    simp [Int.cast_pow]
  rw [this, hZ, Int.cast_zero]

/-- The alternating sum over supersets of T in Finset.univ equals 1 if T = univ, 0 otherwise.
Key lemma for the polarization identity. -/
private lemma alternating_superset_sum
    (T : Finset (Fin n)) :
    (∑ S ∈ (Finset.univ : Finset (Fin n)).powerset.filter (fun S => T ⊆ S),
      (-1 : k) ^ (n - S.card)) =
    if T = Finset.univ then 1 else 0 := by
  classical
  -- Biject {S | T ⊆ S ⊆ univ} ↔ {T' | T' ⊆ univ \ T} via S ↦ S \ T
  -- Under this bijection: n - |S| = n - |T| - |T'| = |univ \ T| - |T'|
  -- And the sum becomes ∑_{T' ⊆ univ\T} (-1)^{|univ\T| - |T'|}
  -- For T = univ: univ \ T = ∅, so the only T' is ∅, giving (-1)^0 = 1
  -- For T ≠ univ: univ \ T is nonempty, and the sum = (-1)^{|univ\T|} * ∑ (-1)^{|T'|} = 0
  split_ifs with hT
  · -- Case T = univ: only superset is univ itself
    subst hT
    have : Finset.univ.powerset.filter (fun S => Finset.univ ⊆ S) =
        {(Finset.univ : Finset (Fin n))} := by
      ext S; simp [Finset.univ_subset_iff]
    rw [this, Finset.sum_singleton, Finset.card_univ, Fintype.card_fin, Nat.sub_self, pow_zero]
  · -- Case T ≠ univ: use Möbius identity
    have hC : (Finset.univ \ T).Nonempty := by
      rw [Finset.sdiff_nonempty]
      exact fun h => hT (Finset.univ_subset_iff.mp h)
    -- Biject {S | T ⊆ S ⊆ univ} ↔ powerset(univ \ T) via S ↦ S \ T, inverse T' ↦ T' ∪ T
    rw [show ∑ S ∈ Finset.univ.powerset.filter (fun S => T ⊆ S),
          (-1 : k) ^ (n - S.card) =
        ∑ T' ∈ (Finset.univ \ T).powerset,
          (-1 : k) ^ ((Finset.univ \ T).card - T'.card) from by
      apply Finset.sum_nbij' (· \ T) (· ∪ T)
      · -- hi: S \ T ∈ powerset(univ \ T)
        intro S hS
        simp only [Finset.mem_filter, Finset.mem_powerset] at hS ⊢
        exact Finset.sdiff_subset_sdiff hS.1 (Finset.Subset.refl T)
      · -- hj: T' ∪ T ∈ filtered set
        intro T' hT'
        simp only [Finset.mem_powerset] at hT'
        simp only [Finset.mem_filter, Finset.mem_powerset]
        exact ⟨Finset.union_subset (hT'.trans Finset.sdiff_subset) (Finset.subset_univ T),
               Finset.subset_union_right⟩
      · -- left_inv: (S \ T) ∪ T = S
        intro S hS
        simp only [Finset.mem_filter, Finset.mem_powerset] at hS
        exact Finset.sdiff_union_of_subset hS.2
      · -- right_inv: (T' ∪ T) \ T = T'
        intro T' hT'
        simp only [Finset.mem_powerset] at hT'
        rw [Finset.union_sdiff_right, Finset.sdiff_eq_self_of_disjoint]
        exact Finset.disjoint_of_subset_left hT' disjoint_sdiff_self_left
      · -- h: summands match — need n - |S| = |C| - |S \ T| where C = univ \ T
        intro S hS
        simp only [Finset.mem_filter, Finset.mem_powerset] at hS
        congr 1
        -- Use card_sdiff_add_card to avoid ℕ subtraction issues
        have h1 : (S \ T).card + T.card = S.card :=
          Finset.card_sdiff_add_card_eq_card hS.2
        have h2 : ((Finset.univ : Finset (Fin n)) \ T).card + T.card =
            (Finset.univ : Finset (Fin n)).card :=
          Finset.card_sdiff_add_card_eq_card (Finset.subset_univ T)
        have h3 : S.card ≤ (Finset.univ : Finset (Fin n)).card :=
          Finset.card_le_card hS.1
        have h4 : (S \ T).card ≤ ((Finset.univ : Finset (Fin n)) \ T).card :=
          Finset.card_le_card (Finset.sdiff_subset_sdiff hS.1 (Finset.Subset.refl T))
        simp only [Finset.card_univ, Fintype.card_fin] at h2 h3
        omega]
    -- Now need: ∑ T' ∈ C.powerset, (-1)^(C.card - T'.card) = 0
    -- Factor: (-1)^(a-b) = (-1)^a * (-1)^b since (-1)^2 = 1
    set C := Finset.univ \ T with hCdef
    have factor : ∀ T' ∈ C.powerset, (-1 : k) ^ (C.card - T'.card) =
        (-1 : k) ^ C.card * (-1 : k) ^ T'.card := by
      intro T' hT'
      simp only [Finset.mem_powerset] at hT'
      have hle := Finset.card_le_card hT'
      have hmul : (-1 : k) ^ (C.card - T'.card) * (-1 : k) ^ T'.card =
          (-1 : k) ^ C.card := by
        rw [← pow_add, Nat.sub_add_cancel hle]
      have hsq : (-1 : k) ^ T'.card * (-1 : k) ^ T'.card = 1 := by
        rw [← pow_add, ← two_mul, pow_mul, neg_one_sq, one_pow]
      calc (-1 : k) ^ (C.card - T'.card)
          = (-1 : k) ^ (C.card - T'.card) * 1 := (mul_one _).symm
        _ = (-1 : k) ^ (C.card - T'.card) *
            ((-1 : k) ^ T'.card * (-1 : k) ^ T'.card) := by rw [hsq]
        _ = (-1 : k) ^ (C.card - T'.card) * (-1 : k) ^ T'.card *
            (-1 : k) ^ T'.card := by rw [mul_assoc]
        _ = (-1 : k) ^ C.card * (-1 : k) ^ T'.card := by rw [hmul]
    rw [Finset.sum_congr rfl factor, ← Finset.mul_sum]
    rw [sum_powerset_neg_one_pow_card_eq_zero (k := k) hC, mul_zero]

/-- The polarization identity for symmetric tensors.

n! • tprod(f) = ∑_{S ⊆ Fin n} (-1)^{n-|S|} • (∑_{i∈S} f i)^⊗n

This expresses a general pure symmetric tensor as a ℤ-linear combination
of diagonal tensors (times n!). -/
private lemma polarization_eq [CharZero k] (f : Fin n → U) :
    (n.factorial : k) • SymmetricPower.tprod k f =
      ∑ S ∈ (Finset.univ : Finset (Fin n)).powerset,
        ((-1 : k) ^ (n - S.card)) • SymmetricPower.tprod k (fun _ => ∑ i ∈ S, f i) := by
  classical
  -- Step 1: Expand each tprod(const(∑ f i)) using multilinearity, distribute smul
  conv_rhs =>
    arg 2; ext S
    rw [show (-1 : k) ^ (n - S.card) • SymmetricPower.tprod k (fun _ => ∑ i ∈ S, f i) =
        ∑ r ∈ Fintype.piFinset (fun _ : Fin n => S),
          (-1 : k) ^ (n - S.card) • (SymmetricPower.tprod k) (fun i => f (r i)) by
      rw [MultilinearMap.map_sum_finset (SymmetricPower.tprod k) (fun _ => f) (fun _ => S)]
      rw [Finset.smul_sum]]
  -- Step 2: Swap the order of summation using sum_comm'
  rw [Finset.sum_comm'
    (s' := fun r => Finset.univ.powerset.filter (fun S => ∀ i, r i ∈ S))
    (t' := Fintype.piFinset (fun _ : Fin n => Finset.univ))
    (h := by
      intro S r
      simp only [Finset.mem_powerset, Fintype.mem_piFinset, Finset.mem_filter, Finset.mem_univ]
      tauto)]
  -- Step 3: Factor out tprod(f ∘ r) from the inner sum
  simp_rw [← Finset.sum_smul]
  -- Step 4: Evaluate inner coefficient using alternating_superset_sum
  have coeff_eq : ∀ r : Fin n → Fin n,
      (∑ S ∈ Finset.univ.powerset.filter (fun S => ∀ j, r j ∈ S),
        (-1 : k) ^ (n - S.card)) =
      if Finset.image r Finset.univ = Finset.univ then 1 else 0 := by
    intro r
    convert alternating_superset_sum k n (Finset.image r Finset.univ) using 2
    ext S; simp [Finset.subset_iff]
  simp_rw [coeff_eq]
  -- Step 5: Non-surjective terms vanish
  simp only [ite_smul, one_smul, zero_smul]
  rw [Finset.sum_ite, Finset.sum_const_zero, add_zero]
  -- Step 6: In the symmetric power, tprod(f ∘ σ) = tprod(f) for any permutation σ
  -- The sum is over surjective (= bijective for Fin n) functions
  -- Each gives tprod(f), and there are n! of them
  -- First, simplify tprod using symmetry: in the symmetric power, permuting args is identity
  have tprod_perm : ∀ (σ : Equiv.Perm (Fin n)),
      (⨂ₛ[k] (i : Fin n), f (σ i)) = SymmetricPower.tprod k f := by
    intro σ; exact SymmetricPower.tprod_equiv σ f
  -- Step 6a: Each term in the filtered sum equals tprod k f
  have all_eq : ∀ x ∈ (Fintype.piFinset fun _ : Fin n => Finset.univ).filter
        (fun x => Finset.image x Finset.univ = Finset.univ),
      (⨂ₛ[k] (i : Fin n), f (x i)) = SymmetricPower.tprod k f := by
    intro x hx
    simp only [Finset.mem_filter, Fintype.mem_piFinset] at hx
    have hxsurj : Function.Surjective x := by
      intro b
      have hb : b ∈ Finset.image x Finset.univ := by rw [hx.2]; exact Finset.mem_univ b
      exact let ⟨a, _, ha⟩ := Finset.mem_image.mp hb; ⟨a, ha⟩
    exact tprod_perm (Equiv.ofBijective x
      ((Finite.surjective_iff_bijective (α := Fin n)).mp hxsurj))
  rw [Finset.sum_congr rfl all_eq, Finset.sum_const, ← Nat.cast_smul_eq_nsmul k]
  congr 1
  -- Step 6b: Card of {r : Fin n → Fin n | image r univ = univ} = n!
  norm_cast
  -- Establish bijection with Perm (Fin n) via embedding
  let e : Equiv.Perm (Fin n) ↪ (Fin n → Fin n) :=
    ⟨fun σ => σ, fun σ₁ σ₂ h => Equiv.ext (congr_fun h)⟩
  have hmap : (Fintype.piFinset fun _ : Fin n => (Finset.univ : Finset (Fin n))).filter
        (fun x => Finset.image x Finset.univ = Finset.univ) =
      (Finset.univ : Finset (Equiv.Perm (Fin n))).map e := by
    ext r
    simp only [Finset.mem_filter, Fintype.mem_piFinset, Finset.mem_univ,
      Finset.mem_map]
    constructor
    · intro ⟨_, hr⟩
      have hsurj : Function.Surjective r := by
        intro b
        have : b ∈ Finset.image r Finset.univ := by rw [hr]; exact Finset.mem_univ b
        exact let ⟨a, _, ha⟩ := Finset.mem_image.mp this; ⟨a, ha⟩
      exact ⟨Equiv.ofBijective r
        ((Finite.surjective_iff_bijective (α := Fin n)).mp hsurj), trivial, rfl⟩
    · rintro ⟨σ, _, rfl⟩
      exact ⟨fun _ => trivial, Finset.image_univ_of_surjective σ.surjective⟩
  rw [hmap, Finset.card_map, Finset.card_univ, Fintype.card_perm, Fintype.card_fin]

/-- S^n U is spanned by n-fold tensor powers u^⊗n for u ∈ U, assuming characteristic zero.

Unlike the general spanning result `SymmetricPower.span_tprod_eq_top` (which says
all pure tensors `u₁ ⊗ u₂ ⊗ ... ⊗ uₙ` span), this states that the smaller set
of *diagonal* pure tensors `u ⊗ u ⊗ ... ⊗ u` already spans. This follows from
polarization: a symmetric multilinear form that vanishes on the diagonal determines
zero, so the diagonal tensors must span.

(Etingof Lemma 5.18.3, part i) -/
theorem span_diagonalTensors [CharZero k] :
    Submodule.span k (diagonalTensors k U n) = ⊤ := by
  rw [eq_top_iff, ← SymmetricPower.span_tprod_eq_top]
  apply Submodule.span_le.mpr
  rintro _ ⟨f, rfl⟩
  -- Need: tprod k f ∈ Submodule.span k (diagonalTensors k U n)
  have hfact : (n.factorial : k) ≠ 0 :=
    Nat.cast_ne_zero.mpr n.factorial_ne_zero
  rw [show SymmetricPower.tprod k f =
      (n.factorial : k)⁻¹ • ((n.factorial : k) • SymmetricPower.tprod k f) from
    (inv_smul_smul₀ hfact _).symm]
  rw [polarization_eq]
  apply Submodule.smul_mem
  apply Submodule.sum_mem
  intro S _
  apply Submodule.smul_mem
  exact Submodule.subset_span ⟨∑ i ∈ S, f i, rfl⟩

end Span

section Generated

variable (k : Type*) [Field k] [CharZero k]
  (V : Type*) [AddCommGroup V] [Module k V] [Module.Finite k V]
  (n : ℕ)

/-- The subalgebra of End(V^⊗n) generated by diagonal elements Δ_n(b) for
b ∈ End(V), where Δ_n(b) = Σᵢ (1 ⊗ ... ⊗ b ⊗ ... ⊗ 1). -/
noncomputable def diagonalSubalgebra :
    Subalgebra k (Module.End k (⨂[k] (_ : Fin n), V)) :=
  Algebra.adjoin k (Set.range fun (b : Module.End k V) =>
    ∑ i : Fin n,
      PiTensorProduct.map (fun j => if j = i then b else LinearMap.id))

/-- The subalgebra of End(V^⊗n) generated by full diagonal operators
f ⊗ f ⊗ ... ⊗ f for f ∈ End(V). -/
noncomputable def fullDiagonalSubalgebra :
    Subalgebra k (Module.End k (⨂[k] (_ : Fin n), V)) :=
  Algebra.adjoin k (Set.range fun (f : Module.End k V) =>
    PiTensorProduct.map (fun _ => f))

/-- T_i(b) and T_j(c) commute when i ≠ j. The composition T_i(b) ∘ T_j(c) applies b at
position i and c at position j simultaneously, regardless of order. -/
private lemma singleAction_commute {b c : Module.End k V} {i j : Fin n} (hij : i ≠ j) :
    Commute
      (PiTensorProduct.map (fun l => if l = i then b else LinearMap.id))
      (PiTensorProduct.map (fun l => if l = j then c else LinearMap.id)) := by
  show _ * _ = _ * _
  rw [← PiTensorProduct.map_mul, ← PiTensorProduct.map_mul]
  congr 1; ext l
  split_ifs with hi hj hj hi
  · exact absurd (hi ▸ hj) hij
  all_goals rfl

/-- T_i(b ∘ c) = T_i(b) ∘ T_i(c): composition at the same position is composition of maps. -/
private lemma singleAction_comp (b c : Module.End k V) (i : Fin n) :
    PiTensorProduct.map (fun j => if j = i then b * c else LinearMap.id) =
    PiTensorProduct.map (fun j => if j = i then b else LinearMap.id) *
    PiTensorProduct.map (fun j => if j = i then c else LinearMap.id) := by
  rw [← PiTensorProduct.map_mul]
  congr 1; ext l
  split_ifs <;> rfl

/-- The full diagonal operator f^⊗n is in the diagonal subalgebra for n ≤ 1.
For n = 0 the sum is empty (zero), and for n = 1 the generator Δ₁(f) = T₀(f) = f^⊗1. -/
private lemma diag_gen_mem_fullDiag_le_one (b : Module.End k V) (hn : n ≤ 1) :
    (∑ i : Fin n, PiTensorProduct.map (fun j => if j = i then b else LinearMap.id)) ∈
    (fullDiagonalSubalgebra k V n : Set _) := by
  interval_cases n
  · simp [fullDiagonalSubalgebra]
  · simp only [Fin.sum_univ_one, Fin.isValue]
    have : (fun (j : Fin 1) => if j = (0 : Fin 1) then b else LinearMap.id) = (fun _ => b) := by
      ext j; fin_cases j; simp
    rw [this]
    exact Algebra.subset_adjoin ⟨b, rfl⟩

/-- The full diagonal operator f^⊗n is in the diagonal subalgebra for n ≤ 1.
For n = 0 it's the identity, and for n = 1 it equals Δ₁(f). -/
private lemma fullDiag_gen_mem_diag_le_one (f : Module.End k V) (hn : n ≤ 1) :
    PiTensorProduct.map (fun (_ : Fin n) => f) ∈
    (diagonalSubalgebra k V n : Set _) := by
  interval_cases n
  · have hmf : PiTensorProduct.map (fun (_ : Fin 0) => f) = 1 := by
      have := PiTensorProduct.map_one (R := k) (s := fun (_ : Fin 0) => V)
      convert this
    rw [hmf]; exact Subalgebra.one_mem _
  · have h1 : (fun (_ : Fin 1) => f) =
        (fun (j : Fin 1) => if j = (0 : Fin 1) then f else LinearMap.id) := by
      ext j; fin_cases j; simp
    rw [h1]
    have h2 : PiTensorProduct.map
        (fun j : Fin 1 => if j = 0 then f else LinearMap.id) =
        ∑ i : Fin 1, PiTensorProduct.map
          (fun j => if j = i then f else LinearMap.id) := by
      simp only [Fin.sum_univ_one, Fin.isValue]
    rw [h2]
    exact Algebra.subset_adjoin ⟨f, rfl⟩

/-- T_i(id + b) = id + T_i(b): adding `id` at position i is the same as adding `id` globally.
This follows from the multilinearity of `PiTensorProduct.tprod` in each component. -/
private lemma singleAction_add_id (b : Module.End k V) (i : Fin n) :
    PiTensorProduct.map (fun j : Fin n => if j = i then LinearMap.id + b else LinearMap.id) =
    LinearMap.id +
      PiTensorProduct.map (fun j : Fin n => if j = i then b else LinearMap.id) := by
  have hfam : (fun j : Fin n => if j = i then LinearMap.id + b else LinearMap.id) =
    Function.update (fun _ => (LinearMap.id : V →ₗ[k] V)) i (LinearMap.id + b) := by
    ext j x; split_ifs with h <;> simp [Function.update, h]
  have hb : (fun j : Fin n => if j = i then b else (LinearMap.id : V →ₗ[k] V)) =
    Function.update (fun _ => (LinearMap.id : V →ₗ[k] V)) i b := by
    ext j x; split_ifs with h <;> simp [Function.update, h]
  rw [hfam, PiTensorProduct.map_update_add, hb]
  congr 1
  have h1 : Function.update (fun _ : Fin n => (LinearMap.id : V →ₗ[k] V))
      i LinearMap.id = fun _ => LinearMap.id := by
    ext j; simp [Function.update]
  rw [h1]
  exact PiTensorProduct.map_one (R := k) (s := fun _ => V)

/-- f^⊗n = ∏ᵢ T_i(f): the full diagonal operator is the (noncommutative) product of the
single-position operators. This follows from the MonoidHom property of `PiTensorProduct.map`
and `Pi.mulSingle` decomposition. -/
private lemma fullDiag_eq_noncommProd (f : Module.End k V) :
    PiTensorProduct.map (fun (_ : Fin n) => f) =
    Finset.univ.noncommProd
      (fun i : Fin n => PiTensorProduct.map
        (fun j : Fin n => if j = i then f else LinearMap.id))
      (fun _i _ _j _ hij => singleAction_commute k V n hij) := by
  let x : ∀ _ : Fin n, Module.End k V := fun _ => f
  have h1 := (Finset.noncommProd_mulSingle x).symm
  have h2 := Finset.map_noncommProd Finset.univ (fun i => Pi.mulSingle i (x i))
    (fun i _ j _ _ => Pi.mulSingle_apply_commute x i j)
    (PiTensorProduct.mapMonoidHom (R := k) (s := fun _ => V))
  -- h2 : mapMonoidHom (noncommProd mulSingle) = noncommProd (mapMonoidHom ∘ mulSingle)
  -- h1 : x = noncommProd mulSingle
  -- Goal: map x = noncommProd (map ∘ δᵢ)
  calc PiTensorProduct.map x
      = PiTensorProduct.mapMonoidHom (Finset.univ.noncommProd
          (fun i => Pi.mulSingle i (x i))
          (fun i _ j _ _ => Pi.mulSingle_apply_commute x i j)) := by
        exact congrArg PiTensorProduct.map h1
    _ = Finset.univ.noncommProd
          (fun i => PiTensorProduct.map (Pi.mulSingle i (x i))) _ := h2
    _ = _ := by
        apply Finset.noncommProd_congr rfl
        intro i _
        congr 1; ext j
        simp [Pi.mulSingle, Function.update, x]
        split_ifs <;> rfl

/-- S^n A is generated by diagonal elements Δ_n(a) for a ∈ A.

The n-th symmetric power of an algebra A, viewed inside End(V^⊗n) via the
diagonal representation, is generated by the Lie algebra-type diagonal elements
Δ_n(b) = Σᵢ (1 ⊗ ... ⊗ b ⊗ ... ⊗ 1). In other words, the subalgebra generated
by these "additive" diagonal elements equals the subalgebra generated by the
"multiplicative" diagonal elements f ⊗ f ⊗ ... ⊗ f.

This follows from the fundamental theorem of symmetric functions: the power
sum symmetric polynomials generate the ring of symmetric polynomials.
Requires CharZero because Newton's identities need k ≥ n! to be invertible.

(Etingof Lemma 5.18.3, part ii) -/
theorem diagonalSubalgebra_eq_fullDiagonal :
    diagonalSubalgebra k V n = fullDiagonalSubalgebra k V n := by
  apply le_antisymm
  · -- ⊆: Each Δ_n(b) ∈ fullDiagonalSubalgebra
    -- Strategy: By fullDiag_eq_noncommProd + singleAction_add_id:
    --   (id + t·b)^⊗n = ∏ᵢ T_i(id + t·b) = ∏ᵢ (id + t · T_i(b))
    -- Expanding ∏(1 + t·aᵢ) for pairwise-commuting aᵢ gives Σ_m t^m · e_m(b).
    -- The e_1 coefficient is Δ_n(b). Evaluating at t = 0,...,n and inverting the
    -- Vandermonde matrix (invertible in CharZero) extracts Δ_n(b) as a k-linear
    -- combination of (id + j·b)^⊗n ∈ fullDiag.
    -- Remaining work: prove ∏(1 + t·aᵢ) = Σ t^m · e_m for commuting aᵢ (not in Mathlib),
    -- then use Matrix.det_vandermonde for the extraction.
    apply Algebra.adjoin_le
    rintro _ ⟨b, rfl⟩
    sorry
  · -- ⊇: Each f^⊗n ∈ diagonalSubalgebra
    -- Strategy: By fullDiag_eq_noncommProd, f^⊗n = ∏ᵢ T_i(f).
    -- Define e_m = Σ_{|S|=m} ∏_{i∈S} T_i(f) (elementary symmetric polynomial in T_i(f)).
    -- Then e_0 = 1, e_n = f^⊗n, and p_k = Σᵢ T_i(f)^k = Δ_n(f^k) ∈ diag.
    --
    -- Newton-Girard identity (NOT in Mathlib): m · e_m = Σ_{j=1}^m (-1)^{j+1} e_{m-j} · p_j
    -- By induction on m with CharZero division: e_m ∈ diag for all m ≤ n.
    -- In particular e_n = f^⊗n ∈ diag.
    --
    -- Remaining work: prove Newton-Girard identity for pairwise-commuting elements
    -- in a (non-commutative) ring, then the induction.
    apply Algebra.adjoin_le
    rintro _ ⟨f, rfl⟩
    sorry

end Generated

end Etingof.Lemma5_18_3
