import Mathlib
import EtingofRepresentationTheory.Chapter5.Definition5_12_1
import EtingofRepresentationTheory.Chapter5.Theorem5_12_2_Irreducible
import EtingofRepresentationTheory.Chapter5.Definition5_14_2

/-!
# Problem 5.24.1(b): the sign twist sends `V_λ` to `V_{λ*}`

**Problem 5.24.1.** (b) Let `φ : ℂ[S_n] → ℂ[S_n]` be the automorphism sending `s` to
`(-1)^s s` for any permutation `s`. Show that `φ` maps any representation `V` of `S_n` to
`V ⊗ ℂ_-`. Show also that `φ(ℂ[S_n] a) = ℂ[S_n] φ(a)`, for `a ∈ ℂ[S_n]`. Use (a) to deduce
that `V_λ ⊗ ℂ_- = V_{λ*}`, where `λ*` is the conjugate partition to `λ`, obtained by
reflecting the Young diagram of `λ`.

## Formalization

Here `ℂ_-` is the one-dimensional **sign representation**: `g` acts by the scalar
`(-1)^g = sign(g)`. The automorphism `φ` twists the group-algebra basis element `g` by this
scalar, `φ(g) = sign(g) · g`; because `sign` is a group homomorphism this is an algebra
automorphism (`signTwist`).

* **`φ` maps `V` to `V ⊗ ℂ_-`** (`signTwist_smul_of`): restricting scalars along `φ` sends
  the `g`-action `v ↦ g • v` to `v ↦ sign(g) • (g • v)`, which is exactly the action on
  `V ⊗ ℂ_-`.
* **`φ(ℂ[S_n] a) = ℂ[S_n] φ(a)`** (`signTwist_map_leftIdeal`): `φ` carries the left ideal
  generated by `a` onto the left ideal generated by `φ(a)`.
* **`V_λ ⊗ ℂ_- = V_{λ*}`** (`spechtModule_signTwist_iso_conjugate`): the Specht module
  `V_λ` with its `S_n`-action twisted by `sign` (i.e. `V_λ ⊗ ℂ_-`) is isomorphic to the
  Specht module `V_{λ*}` for the conjugate partition.

The conjugate partition `λ*` is `conjugatePartition`, built by transposing the Young
diagram of `λ`.

Statement pass: proofs are left as `sorry`.
-/

namespace Etingof

open scoped Classical

/-! ### Young diagram cell-count helpers

The `parts_sum` obligation for `conjugatePartition` reduces to the standard fact that a Young
diagram, its transpose, and its list of row lengths all record the same number of cells. Mathlib
does not package these directly, so we establish them here. -/

/-- Summing a function over `List.range n` agrees with the corresponding `Finset.range` sum. -/
private theorem sum_list_range_map (n : ℕ) (f : ℕ → ℕ) :
    ((List.range n).map f).sum = ∑ i ∈ Finset.range n, f i := by
  induction n with
  | zero => simp
  | succ k ih =>
    rw [List.range_succ, List.map_append, List.sum_append, ih, Finset.sum_range_succ]; simp

/-- The sum of the row lengths of a Young diagram is its number of cells: the rows partition the
cells, and each row `i` has `rowLen i` cells. -/
private theorem rowLens_sum_eq_card (μ : YoungDiagram) : μ.rowLens.sum = μ.card := by
  rw [YoungDiagram.rowLens, sum_list_range_map]
  show _ = μ.cells.card
  rw [Finset.card_eq_sum_card_fiberwise (f := Prod.fst) (t := Finset.range (μ.colLen 0)) ?_]
  · apply Finset.sum_congr rfl
    intro i _
    exact YoungDiagram.rowLen_eq_card μ
  · intro c hc
    obtain ⟨i, j⟩ := c
    rw [Finset.mem_coe, Finset.mem_range]
    rw [Finset.mem_coe, YoungDiagram.mem_cells, YoungDiagram.mem_iff_lt_colLen] at hc
    exact lt_of_lt_of_le hc (μ.colLen_anti 0 j (Nat.zero_le _))

/-- Transposing a Young diagram preserves the number of cells (it permutes the cells). -/
private theorem card_transpose (μ : YoungDiagram) : μ.transpose.card = μ.card := by
  show μ.transpose.cells.card = μ.cells.card
  rw [YoungDiagram.transpose]
  simp [Equiv.finsetCongr_apply]

/-- The Young diagram of a partition of `n` has exactly `n` cells. -/
private theorem card_toYoungDiagram {n : ℕ} (la : Nat.Partition n) :
    la.toYoungDiagram.card = n := by
  rw [← rowLens_sum_eq_card, Nat.Partition.toYoungDiagram,
    YoungDiagram.rowLens_ofRowLens_eq_self (fun x hx => la.parts_pos (by
      rw [Multiset.mem_sort] at hx; exact hx))]
  rw [← Multiset.sum_coe, Multiset.sort_eq]
  exact la.parts_sum

/-! ### The conjugate partition `λ*` -/

/-- The conjugate (transpose) partition `λ*`: reflect the Young diagram of `λ` across its
main diagonal. Its parts are the row lengths of the transposed diagram. The `parts_sum`
obligation is the standard fact that transposing a Young diagram preserves the number of
cells (`card_transpose`), which equals `n` (`card_toYoungDiagram`). -/
noncomputable def conjugatePartition {n : ℕ} (la : Nat.Partition n) : Nat.Partition n where
  parts := (la.toYoungDiagram.transpose.rowLens : Multiset ℕ)
  parts_pos := by
    intro i hi
    rw [Multiset.mem_coe] at hi
    exact la.toYoungDiagram.transpose.pos_of_mem_rowLens i hi
  parts_sum := by
    -- `∑ (transpose λ).rowLens = (transpose λ).card = λ.card = n`; transposition is a
    -- bijection on cells so it preserves the total.
    rw [Multiset.sum_coe, rowLens_sum_eq_card, card_transpose, card_toYoungDiagram]

/-! ### The sign-twist automorphism `φ` -/

/-- The sign-twist monoid homomorphism `g ↦ sign(g) • g` from `S_n` into the group algebra
`ℂ[S_n]`. Since `sign` is multiplicative, this is a monoid homomorphism into the
multiplicative monoid of `ℂ[S_n]`. -/
noncomputable def signTwistHom (n : ℕ) :
    Equiv.Perm (Fin n) →* SymGroupAlgebra n where
  toFun g := ((Equiv.Perm.sign g : ℤ) : ℂ) • MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g
  map_one' := by
    simp only [Equiv.Perm.sign_one, Units.val_one, Int.cast_one, one_smul, map_one]
  map_mul' g h := by
    simp only [map_mul, Units.val_mul, Int.cast_mul, smul_mul_smul_comm]

/-- The **sign-twist automorphism** `φ : ℂ[S_n] → ℂ[S_n]`, `φ(g) = sign(g) • g`
(Etingof Problem 5.24.1(b)). Extended from `signTwistHom` by the universal property of the
group algebra, this is an algebra homomorphism (it is in fact an involutive automorphism,
see `signTwist_bijective`). -/
noncomputable def signTwist (n : ℕ) : SymGroupAlgebra n →ₐ[ℂ] SymGroupAlgebra n :=
  MonoidAlgebra.lift ℂ (SymGroupAlgebra n) (Equiv.Perm (Fin n)) (signTwistHom n)

/-- `φ` sends the basis element `g` to `sign(g) • g`. -/
theorem signTwist_of (n : ℕ) (g : Equiv.Perm (Fin n)) :
    signTwist n (MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g)
      = ((Equiv.Perm.sign g : ℤ) : ℂ) • MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g := by
  rw [signTwist, MonoidAlgebra.lift_of]
  rfl

/-- `φ` is an involution: applying the sign twist twice is the identity (because
`sign(g)^2 = 1`). In particular `φ` is bijective, i.e. an algebra automorphism. -/
theorem signTwist_bijective (n : ℕ) : Function.Bijective (signTwist n) := by
  have hcomp : (signTwist n).comp (signTwist n) = AlgHom.id ℂ (SymGroupAlgebra n) := by
    apply MonoidAlgebra.algHom_ext
    intro g
    have hsq : ((Equiv.Perm.sign g : ℤ) : ℂ) * ((Equiv.Perm.sign g : ℤ) : ℂ) = 1 := by
      rw [← Int.cast_mul, ← Units.val_mul, Int.units_mul_self, Units.val_one, Int.cast_one]
    show signTwist n (signTwist n (MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g))
        = MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g
    rw [signTwist_of, map_smul, signTwist_of, smul_smul, hsq, one_smul]
  have hinv : Function.Involutive (signTwist n) := fun a => by
    have := DFunLike.congr_fun hcomp a
    simpa using this
  exact hinv.bijective

/-- **`φ` maps `V` to `V ⊗ ℂ_-`.** For any `ℂ[S_n]`-module `V`, restricting the module
structure along `φ` turns the `g`-action `v ↦ g • v` into `v ↦ sign(g) • (g • v)` — the
action on the twist `V ⊗ ℂ_-` by the one-dimensional sign representation. -/
theorem signTwist_smul_of (n : ℕ) {V : Type*} [AddCommGroup V]
    [Module ℂ V] [Module (SymGroupAlgebra n) V] [IsScalarTower ℂ (SymGroupAlgebra n) V]
    (g : Equiv.Perm (Fin n)) (v : V) :
    (signTwist n (MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g)) • v
      = ((Equiv.Perm.sign g : ℤ) : ℂ) • ((MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g) • v) := by
  rw [signTwist_of, smul_assoc]

/-- **`φ(ℂ[S_n] a) = ℂ[S_n] φ(a)`.** The sign twist carries the left ideal generated by `a`
onto the left ideal generated by `φ(a)`. -/
theorem signTwist_map_leftIdeal (n : ℕ) (a : SymGroupAlgebra n) :
    Ideal.map (signTwist n) (Ideal.span {a})
      = Ideal.span {signTwist n a} := by
  rw [Ideal.map_span, Set.image_singleton]

/-! ### The sign twist on the row/column symmetrizers

These record how `φ` transforms the two symmetrizers, and are the reusable algebraic core of
the conjugate-partition isomorphism: `φ` turns the (unsigned) row symmetrizer `a_λ` into the
*signed* sum over the row subgroup, and the (signed) column antisymmetrizer `b_λ` into the
*unsigned* sum over the column subgroup. Under conjugation of the partition the row subgroup of
`λ` plays the role of the column subgroup of `λ*` (and vice versa), so these are exactly the
building blocks of `a_{λ*} b_{λ*}`. -/

/-- `φ(a_λ) = ∑_{g ∈ P_λ} sign(g) • g`: the sign twist turns the row symmetrizer into the
*signed* sum over the row subgroup (a "row antisymmetrizer"). -/
theorem signTwist_rowSymmetrizer (n : ℕ) (la : Nat.Partition n) :
    haveI : DecidablePred (· ∈ RowSubgroup n la) := Classical.decPred _
    signTwist n (RowSymmetrizer n la)
      = ∑ g : (RowSubgroup n la),
          ((Equiv.Perm.sign g.val : ℤ) : ℂ) • MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g.val := by
  classical
  rw [RowSymmetrizer, map_sum]
  exact Finset.sum_congr rfl (fun g _ => signTwist_of n g.val)

/-- `φ(b_λ) = ∑_{g ∈ Q_λ} g`: the sign twist turns the column antisymmetrizer into the
*unsigned* sum over the column subgroup (a "column symmetrizer"), because `sign(g)² = 1`. -/
theorem signTwist_columnAntisymmetrizer (n : ℕ) (la : Nat.Partition n) :
    haveI : DecidablePred (· ∈ ColumnSubgroup n la) := Classical.decPred _
    signTwist n (ColumnAntisymmetrizer n la)
      = ∑ g : (ColumnSubgroup n la), MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g.val := by
  classical
  rw [ColumnAntisymmetrizer, map_sum]
  refine Finset.sum_congr rfl (fun g _ => ?_)
  rw [map_smul, signTwist_of, smul_smul]
  have hsq : ((Equiv.Perm.sign g.val : ℤ) : ℂ) * ((Equiv.Perm.sign g.val : ℤ) : ℂ) = 1 := by
    rw [← Int.cast_mul, ← Units.val_mul, Int.units_mul_self, Units.val_one, Int.cast_one]
  rw [hsq, one_smul]

/-! ### Combinatorial bridge: the conjugate partition transposes cells

To identify `φ(V_λ)` with `V_{λ*}` we need the geometric fact that the canonical filling of
`λ*` is the transpose of the canonical filling of `λ`. We work through Mathlib's `YoungDiagram`
API: a cell `(r, c)` lies in `λ`'s diagram iff `c < λ.sortedParts.getD r 0`, and the conjugate
partition's diagram is exactly the transpose. -/

/-- The row-length membership condition unpacked to `getD`: `∃ h : r < w.length, c < w[r]`
is equivalent to `c < w.getD r 0`. -/
private theorem lt_getD_iff (w : List ℕ) (r c : ℕ) :
    (∃ h : r < w.length, c < w[r]) ↔ c < w.getD r 0 := by
  rw [List.getD_eq_getElem?_getD]
  rcases lt_or_ge r w.length with hr | hr
  · rw [List.getElem?_eq_getElem hr, Option.getD_some]
    exact ⟨fun ⟨_, h⟩ => h, fun h => ⟨hr, h⟩⟩
  · rw [List.getElem?_eq_none hr, Option.getD_none]
    exact ⟨fun ⟨h, _⟩ => absurd h (not_lt.mpr hr), fun h => absurd h (Nat.not_lt_zero c)⟩

/-- A cell `(r, c)` belongs to the Young diagram of `la` iff `c` is below the `r`-th row
length `la.sortedParts.getD r 0`. -/
private theorem mem_toYoungDiagram_iff {n : ℕ} (la : Nat.Partition n) (r c : ℕ) :
    (r, c) ∈ la.toYoungDiagram ↔ c < la.sortedParts.getD r 0 := by
  rw [Nat.Partition.toYoungDiagram, YoungDiagram.mem_ofRowLens]
  exact lt_getD_iff _ r c

/-- Two `ofRowLens` diagrams built from equal lists are equal (the sortedness proof is
irrelevant). -/
private theorem ofRowLens_congr {w1 w2 : List ℕ} (h : w1 = w2)
    (h1 : w1.SortedGE) (h2 : w2.SortedGE) :
    YoungDiagram.ofRowLens w1 h1 = YoungDiagram.ofRowLens w2 h2 := by
  subst h; rfl

/-- The Young diagram of the conjugate partition `λ*` is the transpose of the Young diagram of
`λ`. -/
private theorem conjugate_toYoungDiagram {n : ℕ} (la : Nat.Partition n) :
    (conjugatePartition la).toYoungDiagram = la.toYoungDiagram.transpose := by
  have hlist : (conjugatePartition la).parts.sort (· ≥ ·)
      = la.toYoungDiagram.transpose.rowLens := by
    change (↑(la.toYoungDiagram.transpose.rowLens) : Multiset ℕ).sort (· ≥ ·) = _
    rw [Multiset.coe_sort]
    exact List.mergeSort_eq_self (r := (· ≥ ·))
      (List.sortedGE_iff_pairwise.mp (YoungDiagram.rowLens_sorted _))
  conv_rhs => rw [← YoungDiagram.ofRowLens_to_rowLens_eq_self (μ := la.toYoungDiagram.transpose)]
  rw [Nat.Partition.toYoungDiagram]
  exact ofRowLens_congr hlist _ _

/-- **Transpose of cells.** A cell `(r, c)` fits under the conjugate partition's row lengths iff
the transposed cell `(c, r)` fits under `λ`'s row lengths. -/
private theorem transpose_cell_iff {n : ℕ} (la : Nat.Partition n) (r c : ℕ) :
    c < (conjugatePartition la).sortedParts.getD r 0 ↔ r < la.sortedParts.getD c 0 := by
  rw [← mem_toYoungDiagram_iff, conjugate_toYoungDiagram, YoungDiagram.mem_transpose,
    Prod.swap_prod_mk, mem_toYoungDiagram_iff]

/-! ### `V_λ ⊗ ℂ_- = V_{λ*}` -/

/-- **Problem 5.24.1(b), main statement.** `V_λ ⊗ ℂ_- ≅ V_{λ*}`: the Specht module `V_λ`,
with its `S_n`-action twisted by the sign character (which is `V_λ ⊗ ℂ_-`), is isomorphic to
the Specht module `V_{λ*}` of the conjugate partition. Concretely there is a `ℂ`-linear
equivalence `e` intertwining the twisted action on `V_λ` with the ordinary action on
`V_{λ*}`: `e (g • x) = sign(g) • g • e x`. -/
theorem spechtModule_signTwist_iso_conjugate (n : ℕ) (la : Nat.Partition n) :
    ∃ e : ↥(SpechtModule n la) ≃ₗ[ℂ] ↥(SpechtModule n (conjugatePartition la)),
      ∀ (g : Equiv.Perm (Fin n)) (x : ↥(SpechtModule n la)),
        e ((MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g) • x)
          = ((Equiv.Perm.sign g : ℤ) : ℂ)
              • ((MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g) • e x) := by
  sorry

end Etingof
