import Mathlib
import EtingofRepresentationTheory.Chapter5.Definition5_12_1
import EtingofRepresentationTheory.Chapter5.Theorem5_12_2_Irreducible
import EtingofRepresentationTheory.Chapter5.Definition5_14_2

/-!
# Problem 5.24.1(b): the sign twist sends `V_λ` to `V_{λ*}`

**Problem 5.24.1.** (b) Let `φ : ℂ[S_n] → ℂ[S_n]` be the automorphism sending `s` to
`(-1)^s s` for any permutation `s`. Show that `φ` maps any representation `V` of `S_n` to
`V ⊗ ℂ_-`. Show also that `φ(ℂ[S_n] a) = ℂ[S_n] φ(a)`, for `a ∈ ℂ[S_n]`. Use (a) to deduce
that `V_λ ⊗ ℂ_- = V_{λ*}`, where `λ*` is the conjugate partition to `λ`, obtained by
reflecting the Young diagram of `λ`.

## Formalization

Here `ℂ_-` is the one-dimensional **sign representation**: `g` acts by the scalar
`(-1)^g = sign(g)`. The automorphism `φ` twists the group-algebra basis element `g` by this
scalar, `φ(g) = sign(g) · g`; because `sign` is a group homomorphism this is an algebra
automorphism (`signTwist`).

* **`φ` maps `V` to `V ⊗ ℂ_-`** (`signTwist_smul_of`): restricting scalars along `φ` sends
  the `g`-action `v ↦ g • v` to `v ↦ sign(g) • (g • v)`, which is exactly the action on
  `V ⊗ ℂ_-`.
* **`φ(ℂ[S_n] a) = ℂ[S_n] φ(a)`** (`signTwist_map_leftIdeal`): `φ` carries the left ideal
  generated by `a` onto the left ideal generated by `φ(a)`.
* **`V_λ ⊗ ℂ_- = V_{λ*}`** (`spechtModule_signTwist_iso_conjugate`): the Specht module
  `V_λ` with its `S_n`-action twisted by `sign` (i.e. `V_λ ⊗ ℂ_-`) is isomorphic to the
  Specht module `V_{λ*}` for the conjugate partition.

The conjugate partition `λ*` is `conjugatePartition`, built by transposing the Young
diagram of `λ`.

Statement pass: proofs are left as `sorry`.
-/

namespace Etingof

open scoped Classical

/-! ### The conjugate partition `λ*` -/

/-- The conjugate (transpose) partition `λ*`: reflect the Young diagram of `λ` across its
main diagonal. Its parts are the row lengths of the transposed diagram. The `parts_sum`
obligation is the standard fact that transposing a Young diagram preserves the number of
cells; it is left as `sorry` (a proof obligation within the definition — the underlying
data, the transposed row lengths, is genuine). -/
noncomputable def conjugatePartition {n : ℕ} (la : Nat.Partition n) : Nat.Partition n where
  parts := (la.toYoungDiagram.transpose.rowLens : Multiset ℕ)
  parts_pos := by
    intro i hi
    rw [Multiset.mem_coe] at hi
    exact la.toYoungDiagram.transpose.pos_of_mem_rowLens i hi
  parts_sum := by
    -- `∑ (transpose λ).rowLens = (transpose λ).card = λ.card = n`; transposition is a
    -- bijection on cells so it preserves the total. Standard; deferred for the statement pass.
    sorry

/-! ### The sign-twist automorphism `φ` -/

/-- The sign-twist monoid homomorphism `g ↦ sign(g) • g` from `S_n` into the group algebra
`ℂ[S_n]`. Since `sign` is multiplicative, this is a monoid homomorphism into the
multiplicative monoid of `ℂ[S_n]`. -/
noncomputable def signTwistHom (n : ℕ) :
    Equiv.Perm (Fin n) →* SymGroupAlgebra n where
  toFun g := ((Equiv.Perm.sign g : ℤ) : ℂ) • MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g
  map_one' := by
    simp only [Equiv.Perm.sign_one, Units.val_one, Int.cast_one, one_smul, map_one]
  map_mul' g h := by
    simp only [map_mul, Units.val_mul, Int.cast_mul, smul_mul_smul_comm]

/-- The **sign-twist automorphism** `φ : ℂ[S_n] → ℂ[S_n]`, `φ(g) = sign(g) • g`
(Etingof Problem 5.24.1(b)). Extended from `signTwistHom` by the universal property of the
group algebra, this is an algebra homomorphism (it is in fact an involutive automorphism,
see `signTwist_bijective`). -/
noncomputable def signTwist (n : ℕ) : SymGroupAlgebra n →ₐ[ℂ] SymGroupAlgebra n :=
  MonoidAlgebra.lift ℂ (SymGroupAlgebra n) (Equiv.Perm (Fin n)) (signTwistHom n)

/-- `φ` sends the basis element `g` to `sign(g) • g`. -/
theorem signTwist_of (n : ℕ) (g : Equiv.Perm (Fin n)) :
    signTwist n (MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g)
      = ((Equiv.Perm.sign g : ℤ) : ℂ) • MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g := by
  rw [signTwist, MonoidAlgebra.lift_of]
  rfl

/-- `φ` is an involution: applying the sign twist twice is the identity (because
`sign(g)^2 = 1`). In particular `φ` is bijective, i.e. an algebra automorphism. -/
theorem signTwist_bijective (n : ℕ) : Function.Bijective (signTwist n) := by
  sorry

/-- **`φ` maps `V` to `V ⊗ ℂ_-`.** For any `ℂ[S_n]`-module `V`, restricting the module
structure along `φ` turns the `g`-action `v ↦ g • v` into `v ↦ sign(g) • (g • v)` — the
action on the twist `V ⊗ ℂ_-` by the one-dimensional sign representation. -/
theorem signTwist_smul_of (n : ℕ) {V : Type*} [AddCommGroup V]
    [Module ℂ V] [Module (SymGroupAlgebra n) V] [IsScalarTower ℂ (SymGroupAlgebra n) V]
    (g : Equiv.Perm (Fin n)) (v : V) :
    (signTwist n (MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g)) • v
      = ((Equiv.Perm.sign g : ℤ) : ℂ) • ((MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g) • v) := by
  sorry

/-- **`φ(ℂ[S_n] a) = ℂ[S_n] φ(a)`.** The sign twist carries the left ideal generated by `a`
onto the left ideal generated by `φ(a)`. -/
theorem signTwist_map_leftIdeal (n : ℕ) (a : SymGroupAlgebra n) :
    Ideal.map (signTwist n) (Ideal.span {a})
      = Ideal.span {signTwist n a} := by
  sorry

/-! ### `V_λ ⊗ ℂ_- = V_{λ*}` -/

/-- **Problem 5.24.1(b), main statement.** `V_λ ⊗ ℂ_- ≅ V_{λ*}`: the Specht module `V_λ`,
with its `S_n`-action twisted by the sign character (which is `V_λ ⊗ ℂ_-`), is isomorphic to
the Specht module `V_{λ*}` of the conjugate partition. Concretely there is a `ℂ`-linear
equivalence `e` intertwining the twisted action on `V_λ` with the ordinary action on
`V_{λ*}`: `e (g • x) = sign(g) • g • e x`. -/
theorem spechtModule_signTwist_iso_conjugate (n : ℕ) (la : Nat.Partition n) :
    ∃ e : ↥(SpechtModule n la) ≃ₗ[ℂ] ↥(SpechtModule n (conjugatePartition la)),
      ∀ (g : Equiv.Perm (Fin n)) (x : ↥(SpechtModule n la)),
        e ((MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g) • x)
          = ((Equiv.Perm.sign g : ℤ) : ℂ)
              • ((MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g) • e x) := by
  sorry

end Etingof
