import Mathlib
import EtingofRepresentationTheory.Chapter5.Proposition5_2_5
import EtingofRepresentationTheory.Chapter5.Theorem5_3_1

/-!
# Remark 5.2.8: A modification of the vanishing-of-characters argument

> **Remark 5.2.8.** Here is a modification of this argument, which does not use
> (a). Let `N = |G|`. For any `0 < j < N` coprime to `N`, show that the map
> `g ↦ gʲ` is a bijection `G → G`. Deduce that `∏_{g ≠ 1} |χ_V(gʲ)|² = β`. Then
> show that `β ∈ K := ℚ(ζ)`, `ζ = e^{2πi/N}`, and that it does not change under
> the automorphism of `K` given by `ζ ↦ ζʲ`. Deduce that `β` is an integer, and
> derive a contradiction.

This remark is an *alternative proof* of the vanishing statement of
**Problem 5.2.7(b)**: if `V` is an irreducible complex representation of a finite
group `G` with `dim V > 1`, then `χ_V(g) = 0` for some `g ∈ G`. The main argument
of Problem 5.2.7(b) shows `0 < β < 1` for `β := ∏_{g ≠ 1} |χ_V(g)|²` (assuming
the characters never vanish) and rules this out by passing to the Galois
conjugates of the representation supplied by part (a). Remark 5.2.8 replaces that
step by a purely arithmetic argument.

## What is formalized here

The remark decomposes into five steps. Three of them are elementary and
self-contained; they are formalized in this file as real, `sorry`-free theorems:

* **Step 1** (`pow_coprime_bijective`): for `gcd(|G|, j) = 1` the map `g ↦ gʲ` is a
  bijection `G → G`. This is `Nat.Coprime.pow_left_bijective` / `powCoprime` from
  Mathlib, restated in the form the remark uses.

* **Step 2** (`prod_ne_one_pow`): the bijection of Step 1 fixes `1`, hence
  restricts to a bijection of `G ∖ {1}`; reindexing the product along it gives
  `∏_{g ≠ 1} f(gʲ) = ∏_{g ≠ 1} f(g)` for any `f` into a commutative monoid. Taking
  `f g = |χ_V(g)|²` this is exactly "`∏_{g ≠ 1} |χ_V(gʲ)|² = β`".

* **Step 5 + contradiction** (`not_isIntegral_rat_mem_Ioo`): an algebraic integer
  that is rational and lies strictly between `0` and `1` does not exist. Combined
  with Step 2's identity (which forces `β` to be Galois-invariant, hence rational)
  and the fact that `β` is a product of algebraic integers, this "deduce that `β`
  is an integer, and derive a contradiction" step closes the argument. The
  algebraic-integer-∩-ℚ-is-ℤ input is `Etingof.Proposition5_2_5`.

The **root-of-unity content of Step 3** is also formalized here, `sorry`-free:

* **Step 3 (root-of-unity content)** (`character_eq_sum_rootsOfUnity`): every
  character value `χ_V(g)` is a sum of `N`-th roots of unity, `N = |G|` — the
  eigenvalues of `ρ(g)` are the roots of its characteristic polynomial, each an
  `N`-th root of unity (as `ρ(g)` has order dividing `N`), and `χ_V(g)` is their
  sum. This places `χ_V(g)`, hence `β`, in the ring generated by the `N`-th roots
  of unity, i.e. in `ℚ(ζ_N)`.

## Steps 3-4: `β` is rational

**Step 4 (representation-theoretic core)** — the identity `σ_j(χ_V(g)) = χ_V(gʲ)`
for a ring endomorphism `σ_j` of `ℂ` raising every `N`-th root of unity to its
`j`-th power — is formalized here, `sorry`-free, as `character_ringHom_pow`. Its
proof is a clean eigenvalue computation: `ρ(g)` is semisimple (its minimal
polynomial divides the squarefree `X^N - 1`), so `V` splits into eigenspaces and
`trace(ρ(g)ᵏ) = ∑_μ (dim Eμ)·μᵏ` (`trace_pow_eq_sum_eigenvalues`); applying `σ_j`
moves the exponent from `1` to `j`. Combined with Step 2 this gives `σ_j(β) = β`
(`ringHom_prod_char_inv`) for `β = ∏_{g≠1} χ_V(g)·χ_V(g⁻¹)`, the honest polynomial
form of `∏_{g≠1} |χ_V(g)|²`.

The **field-theoretic half of Step 4, together with Step 3** (`β ∈ ℚ`), is also
formalized here, `sorry`-free, as `character_prod_rat`. It realizes the cyclotomic
field `K = ℚ(ζ_N)` as the intermediate field `ℚ⟮ζ⟯ ⊆ ℂ` for a primitive `N`-th root
of unity `ζ`, lifts `β` to `β_K ∈ K` (Step 3: every character value is a `ℤ`-
combination of `N`-th roots of unity, all lying in `K`), shows `β_K` is fixed by the
whole Galois group `Gal(K/ℚ)` (each automorphism acts on roots of unity as
`ζ ↦ ζʲ`, so `φ(χ_V(g)) = χ_V(gʲ)` and reindexing along `g ↦ gʲ` restores the
product), and concludes `β_K ∈ ℚ` because the fixed field of the full Galois group
is the base field (`IsGalois.mem_range_algebraMap_iff_fixed`).

The only remaining input to the final contradiction (`not_isIntegral_rat_mem_Ioo`)
is the `0 < β < 1` bound, which is the main argument of Problem 5.2.7(b) and is
tracked under the parent issue, not here.
-/

namespace Etingof.Remark5_2_8

open Finset

variable {G : Type*} [Group G]

/-- **Step 1 of Remark 5.2.8.** For `j` coprime to `|G|`, the `j`-th power map
`g ↦ gʲ` is a bijection `G → G`. -/
theorem pow_coprime_bijective {j : ℕ} (h : (Nat.card G).Coprime j) :
    Function.Bijective (fun g : G => g ^ j) :=
  Nat.Coprime.pow_left_bijective h

/-- The `j`-th power map fixes the identity and is injective, so `gʲ = 1 ↔ g = 1`
when `j` is coprime to `|G|`. -/
theorem pow_eq_one_iff {j : ℕ} (h : (Nat.card G).Coprime j) {g : G} :
    g ^ j = 1 ↔ g = 1 := by
  refine ⟨fun hg => (pow_coprime_bijective h).injective ?_, fun hg => by rw [hg, one_pow]⟩
  simpa using hg

/-- **Step 2 of Remark 5.2.8.** Since `g ↦ gʲ` (for `gcd(|G|, j) = 1`) is a
bijection of `G` fixing `1`, reindexing the product over `G ∖ {1}` along it leaves
the product unchanged:
`∏_{g ≠ 1} f(gʲ) = ∏_{g ≠ 1} f(g)`.
Taking `f g = |χ_V(g)|²` this is the identity `∏_{g ≠ 1} |χ_V(gʲ)|² = β`. -/
theorem prod_ne_one_pow {M : Type*} [CommMonoid M] [Fintype G] [DecidableEq G] {j : ℕ}
    (h : (Nat.card G).Coprime j) (f : G → M) :
    ∏ g ∈ univ.filter (· ≠ 1), f (g ^ j) = ∏ g ∈ univ.filter (· ≠ 1), f g := by
  refine Finset.prod_bij (fun g _ => g ^ j) ?_ ?_ ?_ ?_
  · -- the map sends `G ∖ {1}` into `G ∖ {1}`
    intro a ha
    simp only [mem_filter, mem_univ, true_and] at ha ⊢
    rwa [Ne, pow_eq_one_iff h]
  · -- injective on `G ∖ {1}`
    intro a₁ _ a₂ _ hab
    exact (pow_coprime_bijective h).injective hab
  · -- surjective onto `G ∖ {1}`
    intro b hb
    simp only [mem_filter, mem_univ, true_and] at hb
    obtain ⟨a, ha⟩ := (pow_coprime_bijective h).surjective b
    refine ⟨a, ?_, ha⟩
    simp only [mem_filter, mem_univ, true_and]
    rintro rfl
    exact hb (by simpa using ha.symm)
  · intro a _; rfl

/-- **Step 5 of Remark 5.2.8, with the contradiction.** There is no rational
algebraic integer strictly between `0` and `1`. Concretely, if `q : ℚ` maps to an
algebraic integer in `ℂ` and `0 < q < 1`, we reach a contradiction: by
`Etingof.Proposition5_2_5` such a `q` is an integer, and there is no integer in
`(0, 1)`.

In the remark, `β` is Galois-invariant (Step 4, using Step 2's identity), hence
rational, and it is a product of algebraic integers, hence an algebraic integer;
the main argument of Problem 5.2.7(b) gives `0 < β < 1`. This lemma is exactly the
final "deduce that `β` is an integer, and derive a contradiction". -/
theorem not_isIntegral_rat_mem_Ioo {q : ℚ}
    (hint : IsIntegral ℤ (algebraMap ℚ ℂ q)) (h0 : 0 < q) (h1 : q < 1) : False := by
  obtain ⟨n, rfl⟩ := (Etingof.Proposition5_2_5 q).mp hint
  have hn0 : (0 : ℤ) < n := by exact_mod_cast h0
  have hn1 : n < 1 := by exact_mod_cast h1
  omega

/-!
## The algebraic-integer half of Steps 3-5

The final contradiction needs two facts about `β := ∏_{g ≠ 1} |χ_V(g)|²`:

* `β` is **rational** — this is the content of Steps 3-4 (Galois invariance in
  `ℚ(ζ_N)`), established `sorry`-free below as `character_prod_rat`;
* `β` is an **algebraic integer** — established here, `sorry`-free, from the fact
  that character values are algebraic integers (`FDRep.character_isIntegral`).

Given both, `not_isIntegral_rat_mem_Ioo` closes the argument once `0 < β < 1`.
The integrality half below needs none of the blocked infrastructure.
-/

open scoped ComplexConjugate

/-- The complex conjugate of an algebraic integer in `ℂ` is again an algebraic
integer: conjugation `z ↦ conj z` is a `ℤ`-algebra automorphism of `ℂ`, so it
preserves integrality over `ℤ`. -/
theorem isIntegral_conj {z : ℂ} (hz : IsIntegral ℤ z) : IsIntegral ℤ (conj z) :=
  hz.map (Complex.conjAe.restrictScalars ℤ).toAlgHom

set_option linter.unusedFintypeInType false in
/-- The squared modulus `|χ_V(g)|²` of a character value is an algebraic integer:
`|χ_V(g)|² = χ_V(g) · conj(χ_V(g))` is a product of algebraic integers
(`FDRep.character_isIntegral`), and the algebraic integers form a ring. -/
theorem isIntegral_normSq_character {G : Type} [Group G] [Fintype G]
    (V : FDRep ℂ G) (g : G) :
    IsIntegral ℤ ((Complex.normSq (V.character g) : ℂ)) := by
  rw [← Complex.mul_conj]
  exact (FDRep.character_isIntegral V g).mul (isIntegral_conj (FDRep.character_isIntegral V g))

set_option linter.unusedFintypeInType false in
/-- **The algebraic-integer half of Remark 5.2.8.** For any finite set `s` of group
elements, `∏_{g ∈ s} |χ_V(g)|²` is an algebraic integer. Taking
`s = G ∖ {1}` this is exactly "`β` is a product of algebraic integers, hence an
algebraic integer" — the input to `not_isIntegral_rat_mem_Ioo` that does not depend
on the cyclotomic Galois argument (Steps 3-4). -/
theorem isIntegral_prod_normSq_character {G : Type} [Group G] [Fintype G]
    (V : FDRep ℂ G) (s : Finset G) :
    IsIntegral ℤ (∏ g ∈ s, (Complex.normSq (V.character g) : ℂ)) := by
  have h : (∏ g ∈ s, (Complex.normSq (V.character g) : ℂ)) ∈ integralClosure ℤ ℂ :=
    prod_mem (fun g _ => isIntegral_normSq_character V g)
  exact h

/-!
## Step 3 (root-of-unity content): character values are sums of `N`-th roots of unity

Step 3 of the remark is "`β ∈ K := ℚ(ζ_N)`". The concrete representation-theoretic
fact underlying it is that each character value `χ_V(g)` is a *sum of `N`-th roots of
unity*, `N = |G|`: `χ_V(g)` is the trace of `ρ(g)`, hence the sum of the eigenvalues
of `ρ(g)`, and every eigenvalue `μ` satisfies `μ^{orderOf g} = 1`, so `μ^N = 1` since
`orderOf g ∣ N` (Lagrange). This places `χ_V(g)` — and therefore `β`, a product of the
`|χ_V(g)|² = χ_V(g)·χ_V(g⁻¹)` — in the ring generated by the `N`-th roots of unity,
i.e. in `ℚ(ζ_N)`.

The remaining half of Steps 3-4 — that `β` is *fixed* by the Galois action `ζ ↦ ζʲ`
(via `σ_j(χ_V(g)) = χ_V(gʲ)`), forcing `β ∈ ℚ` — is formalized below as
`character_prod_rat`, using the cyclotomic field `ℚ(ζ_N) = ℚ⟮ζ⟯ ⊆ ℂ` together with
its Galois group and the fixed-field theorem.
-/

set_option linter.unusedFintypeInType false in
/-- **Step 3 of Remark 5.2.8 (root-of-unity content).** For a finite-dimensional
complex representation `V` of a finite group `G`, every character value `χ_V(g)` is a
sum of `N`-th roots of unity with `N = |G|`. Concretely, the multiset of eigenvalues
of `ρ(g)` (the roots of its characteristic polynomial) consists of `N`-th roots of
unity and sums to `χ_V(g)`.

This is the concrete meaning of "`χ_V(g) ∈ ℚ(ζ_N)`" that underlies Step 3: the
eigenvalues of `ρ(g)` are roots of unity because `ρ(g)` has order dividing `N`, and
the character is their sum. -/
theorem character_eq_sum_rootsOfUnity {G : Type} [Group G] [Fintype G]
    (V : FDRep ℂ G) (g : G) :
    ∃ s : Multiset ℂ, (∀ μ ∈ s, μ ^ Nat.card G = 1) ∧ V.character g = s.sum := by
  set f := V.ρ g with hf_def
  -- `f^{orderOf g} = 1`, since `ρ` is a homomorphism and `g^{orderOf g} = 1`.
  have hf_pow : f ^ orderOf g = 1 := by
    rw [hf_def, ← map_pow, pow_orderOf_eq_one, map_one]
  have hne : LinearMap.charpoly f ≠ 0 := (LinearMap.charpoly_monic f).ne_zero
  refine ⟨(LinearMap.charpoly f).roots, ?_, ?_⟩
  · -- Every root `μ` of the charpoly is an eigenvalue, hence `μ^{orderOf g} = 1`,
    -- hence `μ^N = 1` because `orderOf g ∣ N = |G|`.
    intro μ hμ
    rw [Polynomial.mem_roots hne] at hμ
    have heig : Module.End.HasEigenvalue f μ :=
      (Module.End.hasEigenvalue_iff_isRoot_charpoly f μ).mpr hμ
    obtain ⟨v, hv⟩ := heig.exists_hasEigenvector
    have hpow_v : ∀ k : ℕ, (f ^ k) v = (μ ^ k) • v := by
      intro k; induction k with
      | zero => simp
      | succ k ih => rw [pow_succ, Module.End.mul_apply, hv.apply_eq_smul,
          map_smul, ih, smul_smul, ← pow_succ']
    have h1 : v = (μ ^ orderOf g) • v := by rw [← hpow_v, hf_pow]; simp
    have h2 : (μ ^ orderOf g - 1) • v = 0 := by rw [sub_smul, one_smul, ← h1, sub_self]
    have hμord : μ ^ orderOf g = 1 := by
      rcases smul_eq_zero.mp h2 with h3 | h3
      · exact sub_eq_zero.mp h3
      · exact absurd h3 hv.2
    obtain ⟨k, hk⟩ := orderOf_dvd_card (x := g)
    rw [Nat.card_eq_fintype_card, hk, pow_mul, hμord, one_pow]
  · -- `χ_V(g) = trace(ρ(g)) = sum of the charpoly roots` (which split over `ℂ`).
    change LinearMap.trace ℂ V f = _
    set b := Module.finBasis ℂ V
    rw [LinearMap.trace_eq_matrix_trace ℂ b]
    have h1 : (LinearMap.toMatrix b b f).trace =
        (LinearMap.toMatrix b b f).charpoly.roots.sum :=
      Matrix.trace_eq_sum_roots_charpoly _
    simpa only [LinearMap.charpoly_toMatrix] using h1

/-!
## Step 4: the Galois automorphism `ζ ↦ ζʲ` sends `χ_V(g)` to `χ_V(gʲ)`

The remaining representation-theoretic content of Step 4 is the identity
`σ_j(χ_V(g)) = χ_V(gʲ)`, where `σ_j : ζ ↦ ζʲ` is (the restriction to `ℚ(ζ_N)` of)
a ring endomorphism of `ℂ` that raises every `N`-th root of unity to its `j`-th
power. The proof is a clean eigenvalue computation and needs *no* cyclotomic-field
infrastructure: it only uses that `σ_j` powers roots of unity.

The key linear-algebra input is that a finite-order operator `f` (`f^N = 1`) over
`ℂ` is semisimple — its minimal polynomial divides the squarefree `X^N - 1` — hence
diagonalizable, so `V` decomposes as the internal direct sum of the eigenspaces of
`f`. On the `μ`-eigenspace `f^k` acts as `μ^k`, so
`trace(f^k) = ∑_μ (dim Eμ) · μ^k` (`trace_pow_eq_sum_eigenvalues`). Applying `σ_j`
to `χ_V(g) = trace(ρ(g)) = ∑_μ (dim Eμ) · μ` moves the exponent from `1` to `j`
(each `μ` is an `N`-th root of unity, and `σ_j` fixes the integer dimensions),
landing on `∑_μ (dim Eμ) · μʲ = trace(ρ(g)ʲ) = trace(ρ(gʲ)) = χ_V(gʲ)`.

Combined with Step 2 (`prod_ne_one_pow`) this yields `σ_j(β) = β` for
`β = ∏_{g≠1} χ_V(g)·χ_V(g⁻¹)` (`ringHom_prod_char_inv`), the honest polynomial form
of `∏_{g≠1} |χ_V(g)|²`. Landing `β ∈ ℚ` from "fixed by every `σ_j`" — the pure
cyclotomic-Galois field theory (`IsCyclotomicExtension`, `Gal(ℚ(ζ_N)/ℚ)`, fixed
field `= ℚ`) — is carried out below in `character_prod_rat`.
-/

/-- For `x` in the `μ`-eigenspace of `f`, one has `fᵏ x = μᵏ • x`. -/
theorem pow_apply_of_mem_eigenspace {V : Type*} [AddCommGroup V] [Module ℂ V]
    (f : Module.End ℂ V) (μ : ℂ) {x : V} (hx : x ∈ Module.End.eigenspace f μ) (m : ℕ) :
    (f ^ m) x = μ ^ m • x := by
  induction m with
  | zero => simp
  | succ m ih =>
      rw [pow_succ', Module.End.mul_apply, ih, map_smul,
        (Module.End.mem_eigenspace_iff.mp hx), smul_smul, ← pow_succ]

/-- An eigenvalue of a finite-order operator is a root of unity: if `f^N = 1` and
`μ` is an eigenvalue of `f`, then `μ^N = 1`. -/
theorem eigenvalue_pow_eq_one {V : Type*} [AddCommGroup V] [Module ℂ V]
    (f : Module.End ℂ V) {N : ℕ} (hf : f ^ N = 1) {μ : ℂ}
    (hμ : Module.End.eigenspace f μ ≠ ⊥) : μ ^ N = 1 := by
  obtain ⟨v, hv, hv0⟩ := (Submodule.ne_bot_iff _).mp hμ
  have hpow := pow_apply_of_mem_eigenspace f μ hv N
  rw [hf, Module.End.one_apply] at hpow
  have hz : (μ ^ N - 1) • v = 0 := by rw [sub_smul, one_smul, ← hpow, sub_self]
  rcases smul_eq_zero.mp hz with h | h
  · exact sub_eq_zero.mp h
  · exact absurd h hv0

open Polynomial in
/-- **Trace-power-sum for a finite-order operator over `ℂ`.** If `f^N = 1`
(`N > 0`) then, `f` being semisimple, `V` splits as the direct sum of the
eigenspaces of `f`, and the trace of `fᵏ` is `∑_μ (dim Eμ)·μᵏ` summed over the
eigenvalues `μ`. This is the linear-algebra core of Step 4: taking `k = 1` gives
`χ_V(g)` and `k = j` gives `χ_V(gʲ)`, with the *same* eigenspace dimensions. -/
theorem trace_pow_eq_sum_eigenvalues {V : Type*} [AddCommGroup V] [Module ℂ V]
    [FiniteDimensional ℂ V] (f : Module.End ℂ V) {N : ℕ} (hN : 0 < N)
    (hf : f ^ N = 1) (k : ℕ)
    (hfin : {μ : ℂ | Module.End.eigenspace f μ ≠ ⊥}.Finite) :
    LinearMap.trace ℂ V (f ^ k) =
      ∑ μ ∈ hfin.toFinset, (Module.finrank ℂ (Module.End.eigenspace f μ) : ℂ) * μ ^ k := by
  -- `f` is semisimple: `X^N - 1` is squarefree and annihilates `f`.
  have hsep : (X ^ N - 1 : ℂ[X]).Separable :=
    Polynomial.X_pow_sub_one_separable_iff.mpr (by exact_mod_cast hN.ne')
  have haeval : (aeval f) (X ^ N - 1 : ℂ[X]) = 0 := by simp [map_sub, hf]
  have hss : f.IsSemisimple :=
    Module.End.isSemisimple_of_squarefree_aeval_eq_zero hsep.squarefree haeval
  -- Eigenspace decomposition of `V`.
  have hInternal : DirectSum.IsInternal (Module.End.eigenspace f) :=
    (DirectSum.isInternal_submodule_iff_iSupIndep_and_iSup_eq_top _).mpr
      ⟨f.eigenspaces_iSupIndep, hss.iSup_eigenspace_eq_top⟩
  -- `f^k` maps each eigenspace to itself.
  have hmaps : ∀ μ : ℂ, Set.MapsTo (f ^ k)
      (Module.End.eigenspace f μ) (Module.End.eigenspace f μ) := by
    intro μ x hx
    rw [pow_apply_of_mem_eigenspace f μ hx k]
    exact (Module.End.eigenspace f μ).smul_mem _ hx
  classical
  rw [LinearMap.trace_eq_sum_trace_restrict' hInternal hfin hmaps]
  apply Finset.sum_congr rfl
  intro μ _
  -- The restriction of `f^k` to the `μ`-eigenspace is `μ^k • id`.
  have hrestrict : (f ^ k).restrict (hmaps μ) = (μ ^ k) • LinearMap.id := by
    ext x
    simp only [LinearMap.coe_restrict_apply, LinearMap.smul_apply, LinearMap.id_apply,
      Submodule.coe_smul]
    exact pow_apply_of_mem_eigenspace f μ x.2 k
  rw [hrestrict, LinearMap.map_smul, LinearMap.trace_id, smul_eq_mul, mul_comm]

set_option linter.unusedFintypeInType false in
/-- **Step 4 of Remark 5.2.8 (representation-theoretic core).** Let `σ` be a ring
endomorphism of `ℂ` raising every `|G|`-th root of unity to its `j`-th power (the
arithmetic of the cyclotomic automorphism `ζ ↦ ζʲ`). Then `σ` sends the character
value `χ_V(g)` to `χ_V(gʲ)`. -/
theorem character_ringHom_pow {G : Type} [Group G] [Fintype G]
    (V : FDRep ℂ G) (g : G) {j : ℕ} (σ : ℂ →+* ℂ)
    (hσ : ∀ μ : ℂ, μ ^ Nat.card G = 1 → σ μ = μ ^ j) :
    σ (V.character g) = V.character (g ^ j) := by
  classical
  set f := V.ρ g with hf_def
  have hN : 0 < Nat.card G := Nat.card_pos
  have hf : f ^ Nat.card G = 1 := by
    rw [hf_def, ← map_pow, Nat.card_eq_fintype_card, pow_card_eq_one, map_one]
  have hfin : {μ : ℂ | Module.End.eigenspace f μ ≠ ⊥}.Finite :=
    Module.End.finite_hasEigenvalue f
  have e1 := trace_pow_eq_sum_eigenvalues f hN hf 1 hfin
  have ej := trace_pow_eq_sum_eigenvalues f hN hf j hfin
  simp only [pow_one] at e1
  have hchar_g : V.character g = LinearMap.trace ℂ V f := rfl
  have hchar_gj : V.character (g ^ j) = LinearMap.trace ℂ V (f ^ j) := by
    rw [hf_def, ← map_pow]; rfl
  rw [hchar_g, hchar_gj, e1, ej, map_sum]
  apply Finset.sum_congr rfl
  intro μ hμ
  have hμmem : Module.End.eigenspace f μ ≠ ⊥ := (Set.Finite.mem_toFinset hfin).mp hμ
  rw [map_mul, map_natCast, hσ μ (eigenvalue_pow_eq_one f hf hμmem)]

/-- **`σ_j` fixes `β` (Step 4, combined with Step 2).** For `j` coprime to `|G|` and
a ring endomorphism `σ` of `ℂ` raising every `|G|`-th root of unity to its `j`-th
power, the product `β = ∏_{g ≠ 1} χ_V(g)·χ_V(g⁻¹)` (the honest polynomial form of
`∏_{g ≠ 1} |χ_V(g)|²`) is fixed: `σ(β) = β`. Indeed `σ` maps each factor
`χ_V(g)·χ_V(g⁻¹)` to `χ_V(gʲ)·χ_V((gʲ)⁻¹)` by `character_ringHom_pow`, and
reindexing along `g ↦ gʲ` (`prod_ne_one_pow`) restores the original product. -/
theorem ringHom_prod_char_inv {G : Type} [Group G] [Fintype G] [DecidableEq G]
    (V : FDRep ℂ G) {j : ℕ} (hj : (Nat.card G).Coprime j) (σ : ℂ →+* ℂ)
    (hσ : ∀ μ : ℂ, μ ^ Nat.card G = 1 → σ μ = μ ^ j) :
    σ (∏ g ∈ univ.filter (· ≠ 1), V.character g * V.character g⁻¹)
      = ∏ g ∈ univ.filter (· ≠ 1), V.character g * V.character g⁻¹ := by
  rw [map_prod]
  have step : ∀ g : G, σ (V.character g * V.character g⁻¹)
      = V.character (g ^ j) * V.character (g ^ j)⁻¹ := by
    intro g
    rw [map_mul, character_ringHom_pow V g σ hσ, character_ringHom_pow V g⁻¹ σ hσ, inv_pow]
  simp_rw [step]
  exact prod_ne_one_pow hj (fun g => V.character g * V.character g⁻¹)

/-!
## Step 4 (field-theoretic half) and Step 3: `β ∈ ℚ` via the cyclotomic fixed field

The final field-theoretic content of the remark is that `β := ∏_{g ≠ 1} χ_V(g)·χ_V(g⁻¹)`
is *rational*. We realize the cyclotomic field `K = ℚ(ζ_N)` as the intermediate field
`ℚ⟮ζ⟯ ⊆ ℂ` generated by a primitive `N`-th root of unity `ζ = e^{2πi/N}`. Then:

* Every character value `χ_V(g)` is a `ℤ`-combination of `N`-th roots of unity
  (`character_eq_sum_rootsOfUnity` / `trace_pow_eq_sum_eigenvalues`), and every `N`-th
  root of unity in `ℂ` lies in `K`; so `β` lifts to an element `β_K ∈ K` (Step 3,
  `β ∈ K`).
* Each `φ ∈ Gal(K/ℚ)` raises `ζ` — hence every `N`-th root of unity in `K` — to a fixed
  power `ζ ↦ ζʲ`, `j` coprime to `N` (`IsPrimitiveRoot.autToPow_spec`). Transporting the
  eigenvalue decomposition into `K` gives `φ(χ_V(g)) = χ_V(gʲ)` inside `K`, so by
  reindexing along `g ↦ gʲ` (`prod_ne_one_pow`) we get `φ(β_K) = β_K` (Step 4).
* `K/ℚ` is Galois and finite (`IsCyclotomicExtension.isGalois` /
  `.finiteDimensional`), so an element of `K` fixed by every `φ ∈ Gal(K/ℚ)` lies in the
  base field `ℚ` (`IntermediateField.mem_range_algebraMap_iff_fixed`). Hence `β ∈ ℚ`.

This closes the rationality half of Remark 5.2.8; combined with
`isIntegral_prod_normSq_character` (β is an algebraic integer) and the `0 < β < 1` bound of
Problem 5.2.7(b), `not_isIntegral_rat_mem_Ioo` derives the contradiction.
-/

set_option linter.unusedFintypeInType false in
/-- **Step 3 + Step 4 (field-theoretic half) of Remark 5.2.8.** The product
`β = ∏_{g ≠ 1} χ_V(g)·χ_V(g⁻¹)` (the honest polynomial form of `∏_{g ≠ 1} |χ_V(g)|²`) is
rational: it lies in the image of `algebraMap ℚ ℂ`.

The proof realizes `K = ℚ(ζ_N) ⊆ ℂ` as `ℚ⟮ζ⟯` for a primitive `N`-th root of unity `ζ`,
lifts `β` to `β_K ∈ K` (each character value being a `ℤ`-combination of `N`-th roots of
unity, all of which lie in `K`), shows `β_K` is fixed by the whole Galois group
`Gal(K/ℚ)` (each `φ` acts on roots of unity as `ζ ↦ ζʲ`, so `φ(χ_V(g)) = χ_V(gʲ)` and
reindexing restores the product), and concludes `β_K ∈ ℚ` from the fixed field of the full
Galois group being the base field. -/
theorem character_prod_rat {G : Type} [Group G] [Fintype G] [DecidableEq G]
    (V : FDRep ℂ G) :
    ∃ q : ℚ, algebraMap ℚ ℂ q =
      ∏ g ∈ univ.filter (· ≠ 1), V.character g * V.character g⁻¹ := by
  classical
  set N := Nat.card G with hN_def
  have hNpos : 0 < N := Nat.card_pos
  haveI : NeZero N := ⟨hNpos.ne'⟩
  -- A primitive `N`-th root of unity in `ℂ`, and the cyclotomic field `K = ℚ⟮ζ⟯ ⊆ ℂ`.
  obtain ⟨ζ, hζ⟩ : ∃ ζ : ℂ, IsPrimitiveRoot ζ N :=
    ⟨Complex.exp (2 * Real.pi * Complex.I / N), Complex.isPrimitiveRoot_exp N hNpos.ne'⟩
  set K := IntermediateField.adjoin ℚ ({ζ} : Set ℂ) with hK_def
  have hζK_mem : ζ ∈ K := IntermediateField.subset_adjoin ℚ {ζ} (Set.mem_singleton ζ)
  -- `ζ` is algebraic over `ℚ` (a root of the nonzero `X^N - 1`), so `K` is a cyclotomic
  -- extension of `ℚ`.
  have halg : IsAlgebraic ℚ ζ := by
    have hmonic : (Polynomial.X ^ N - Polynomial.C (1 : ℚ)).Monic :=
      Polynomial.monic_X_pow_sub_C 1 hNpos.ne'
    refine ⟨Polynomial.X ^ N - 1, ?_, ?_⟩
    · have hCe : (Polynomial.X ^ N - Polynomial.C (1 : ℚ)) = Polynomial.X ^ N - 1 := by simp
      rw [← hCe]; exact hmonic.ne_zero
    · simp [hζ.pow_eq_one]
  haveI hcyc : IsCyclotomicExtension {N} ℚ K := by
    change IsCyclotomicExtension {N} ℚ (IntermediateField.adjoin ℚ {ζ}).toSubalgebra
    rw [IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic halg]
    exact hζ.adjoin_isCyclotomicExtension ℚ
  haveI : IsGalois ℚ K := IsCyclotomicExtension.isGalois (S := ({N} : Set ℕ)) (K := ℚ) (L := K)
  haveI : FiniteDimensional ℚ K :=
    IsCyclotomicExtension.finiteDimensional (S := ({N} : Set ℕ)) (K := ℚ) K
  -- `ζ`, viewed in `K`, is a primitive `N`-th root of unity.
  set ζK : K := ⟨ζ, hζK_mem⟩ with hζK_def
  have hmapζK : algebraMap K ℂ ζK = ζ := rfl
  have hζK : IsPrimitiveRoot ζK N :=
    IsPrimitiveRoot.of_map_of_injective (f := algebraMap K ℂ)
      (by rw [hmapζK]; exact hζ) (algebraMap K ℂ).injective
  -- Every `N`-th root of unity in `ℂ` lies in `K`.
  have hrootK : ∀ μ : ℂ, μ ^ N = 1 → μ ∈ K := by
    intro μ hμ
    obtain ⟨i, -, rfl⟩ := hζ.eq_pow_of_pow_eq_one hμ
    exact pow_mem hζK_mem i
  -- For each `g`, a lift `x g ∈ K` of `χ_V(g)`, together with the transport property that
  -- any `φ` powering roots of unity sends `x g` to a lift of `χ_V(gʲ)`.
  have hmem : ∀ g : G, ∃ x : K,
      algebraMap K ℂ x = V.character g ∧
      ∀ (j : ℕ) (φ : K ≃ₐ[ℚ] K), (∀ w : K, w ^ N = 1 → φ w = w ^ j) →
        algebraMap K ℂ (φ x) = V.character (g ^ j) := by
    intro g
    set f := V.ρ g with hf_def
    have hf : f ^ N = 1 := by
      rw [hf_def, ← map_pow, hN_def, Nat.card_eq_fintype_card, pow_card_eq_one, map_one]
    have hfin : {μ : ℂ | Module.End.eigenspace f μ ≠ ⊥}.Finite :=
      Module.End.finite_hasEigenvalue f
    set S := hfin.toFinset with hS_def
    set d : ℂ → ℕ := fun μ => Module.finrank ℂ (Module.End.eigenspace f μ) with hd_def
    have hSpow : ∀ μ ∈ S, μ ^ N = 1 := by
      intro μ hμ
      exact eigenvalue_pow_eq_one f hf ((Set.Finite.mem_toFinset hfin).mp hμ)
    have hmemμ : ∀ μ ∈ S, μ ∈ K := fun μ hμ => hrootK μ (hSpow μ hμ)
    have e1 : V.character g = ∑ μ ∈ S, (d μ : ℂ) * μ := by
      have hchar_g : V.character g = LinearMap.trace ℂ V f := rfl
      rw [hchar_g]
      simpa using trace_pow_eq_sum_eigenvalues f hNpos hf 1 hfin
    have ej : ∀ j : ℕ, V.character (g ^ j) = ∑ μ ∈ S, (d μ : ℂ) * μ ^ j := by
      intro j
      have htr : V.character (g ^ j) = LinearMap.trace ℂ V (f ^ j) := by
        rw [hf_def, ← map_pow]; rfl
      rw [htr, trace_pow_eq_sum_eigenvalues f hNpos hf j hfin]
    refine ⟨∑ μ ∈ S.attach, (d μ.1 : K) * ⟨μ.1, hmemμ μ.1 μ.2⟩, ?_, ?_⟩
    · -- `algebraMap K ℂ (x g) = χ_V(g)`
      rw [map_sum]
      have hterm : ∀ μ : S, algebraMap K ℂ ((d μ.1 : K) * ⟨μ.1, hmemμ μ.1 μ.2⟩)
          = (d μ.1 : ℂ) * μ.1 := by
        intro μ; rw [map_mul, map_natCast]; rfl
      rw [Finset.sum_congr rfl (fun μ _ => hterm μ), Finset.sum_attach S (fun μ => (d μ : ℂ) * μ),
        ← e1]
    · -- transport property
      intro j φ hφ
      rw [map_sum, map_sum, ej j]
      have hterm : ∀ μ : S, algebraMap K ℂ (φ ((d μ.1 : K) * ⟨μ.1, hmemμ μ.1 μ.2⟩))
          = (d μ.1 : ℂ) * μ.1 ^ j := by
        intro μ
        have hwN : (⟨μ.1, hmemμ μ.1 μ.2⟩ : K) ^ N = 1 := by
          apply (algebraMap K ℂ).injective
          rw [map_pow, map_one]; exact hSpow μ.1 μ.2
        rw [map_mul, map_natCast, hφ _ hwN, map_mul, map_natCast, map_pow]; rfl
      rw [Finset.sum_congr rfl (fun μ _ => hterm μ),
        Finset.sum_attach S (fun μ => (d μ : ℂ) * μ ^ j)]
  choose x hx1 hx2 using hmem
  -- The lift of `β` and its defining property.
  set βK : K := ∏ g ∈ univ.filter (· ≠ 1), x g * x g⁻¹ with hβK_def
  have hβ : algebraMap K ℂ βK
      = ∏ g ∈ univ.filter (· ≠ 1), V.character g * V.character g⁻¹ := by
    rw [hβK_def, map_prod]
    exact Finset.prod_congr rfl (fun g _ => by rw [map_mul, hx1, hx1])
  -- `βK` is fixed by every Galois automorphism.
  have hfix : ∀ φ : K ≃ₐ[ℚ] K, φ βK = βK := by
    intro φ
    set j := (hζK.autToPow ℚ φ : ZMod N).val with hj_def
    have hjcop : N.Coprime j := (ZMod.val_coe_unit_coprime (hζK.autToPow ℚ φ)).symm
    have hφpow : ∀ w : K, w ^ N = 1 → φ w = w ^ j := by
      intro w hw
      obtain ⟨m, -, rfl⟩ := hζK.eq_pow_of_pow_eq_one hw
      have hζj : φ ζK = ζK ^ j := (hζK.autToPow_spec ℚ φ).symm
      rw [map_pow, hζj, ← pow_mul, ← pow_mul, Nat.mul_comm]
    have hstep : ∀ g : G, φ (x g * x g⁻¹) = (fun g => x g * x g⁻¹) (g ^ j) := by
      intro g
      have h1 : φ (x g) = x (g ^ j) :=
        (algebraMap K ℂ).injective (by rw [hx2 g j φ hφpow, hx1])
      have h2 : φ (x g⁻¹) = x ((g ^ j)⁻¹) :=
        (algebraMap K ℂ).injective (by rw [hx2 g⁻¹ j φ hφpow, hx1, inv_pow])
      simp only [map_mul, h1, h2]
    rw [hβK_def, map_prod, Finset.prod_congr rfl (fun g _ => hstep g),
      prod_ne_one_pow hjcop (fun g => x g * x g⁻¹)]
  -- Fixed by the whole Galois group ⟹ in the base field `ℚ`.
  obtain ⟨q, hq⟩ := (IsGalois.mem_range_algebraMap_iff_fixed βK).mpr hfix
  exact ⟨q, by rw [← hβ, ← hq, IsScalarTower.algebraMap_apply ℚ K ℂ q]⟩

/-!
## The remark, assembled: `β` integer ⟹ contradiction

The pieces above compose into the closing move of the remark, "Deduce that `β` is
an integer, and derive a contradiction." Write `β = ∏_{g ≠ 1} χ_V(g)·χ_V(g⁻¹)` (the
honest polynomial form of `∏_{g ≠ 1} |χ_V(g)|²`). We have shown:

* `β` is **rational** — `character_prod_rat` produces the witnessing `q : ℚ` with
  `algebraMap ℚ ℂ q = β` (Steps 3-4);
* `β` is an **algebraic integer** — each factor `χ_V(g)`, `χ_V(g⁻¹)` is
  (`FDRep.character_isIntegral`), and algebraic integers are closed under products.

So `q` is a rational algebraic integer. The remaining input the remark inherits
from the main argument of Problem 5.2.7(b) is the bound `0 < β < 1`, i.e. `0 < q < 1`;
given it, `not_isIntegral_rat_mem_Ioo` closes the contradiction. The capstone below
takes that bound as a hypothesis (it is Problem 5.2.7(b)'s deliverable, not this
remark's) and derives `False`, exhibiting the full logical spine of the remark as a
single `sorry`-free theorem.
-/

set_option linter.unusedFintypeInType false in
/-- **Remark 5.2.8, assembled.** Let `β = ∏_{g ≠ 1} χ_V(g)·χ_V(g⁻¹)` and let `q : ℚ`
be the rational value of `β` supplied by `character_prod_rat` (Steps 3-4). If the
Problem 5.2.7(b) bound `0 < β < 1` holds — i.e. `0 < q < 1` — then `False`.

This is the remark's closing "deduce that `β` is an integer, and derive a
contradiction": `q` is a rational algebraic integer (each character value is integral
over `ℤ` and products of algebraic integers are algebraic integers), so
`not_isIntegral_rat_mem_Ioo` applies. The only hypothesis not established elsewhere in
this file is `0 < q < 1`, which is exactly the main argument of Problem 5.2.7(b). -/
theorem beta_rat_not_mem_Ioo {G : Type} [Group G] [Fintype G] [DecidableEq G]
    (V : FDRep ℂ G) {q : ℚ}
    (hq : algebraMap ℚ ℂ q =
      ∏ g ∈ univ.filter (· ≠ 1), V.character g * V.character g⁻¹)
    (h0 : 0 < q) (h1 : q < 1) : False := by
  refine not_isIntegral_rat_mem_Ioo ?_ h0 h1
  have hmem : (∏ g ∈ univ.filter (· ≠ 1), V.character g * V.character g⁻¹)
      ∈ integralClosure ℤ ℂ :=
    prod_mem fun g _ =>
      mul_mem (FDRep.character_isIntegral V g) (FDRep.character_isIntegral V g⁻¹)
  rw [hq]; exact hmem

end Etingof.Remark5_2_8
