import Mathlib
import EtingofRepresentationTheory.Chapter5.Proposition5_2_5
import EtingofRepresentationTheory.Chapter5.Theorem5_3_1

/-!
# Remark 5.2.8: A modification of the vanishing-of-characters argument

> **Remark 5.2.8.** Here is a modification of this argument, which does not use
> (a). Let `N = |G|`. For any `0 < j < N` coprime to `N`, show that the map
> `g ↦ gʲ` is a bijection `G → G`. Deduce that `∏_{g ≠ 1} |χ_V(gʲ)|² = β`. Then
> show that `β ∈ K := ℚ(ζ)`, `ζ = e^{2πi/N}`, and that it does not change under
> the automorphism of `K` given by `ζ ↦ ζʲ`. Deduce that `β` is an integer, and
> derive a contradiction.

This remark is an *alternative proof* of the vanishing statement of
**Problem 5.2.7(b)**: if `V` is an irreducible complex representation of a finite
group `G` with `dim V > 1`, then `χ_V(g) = 0` for some `g ∈ G`. The main argument
of Problem 5.2.7(b) shows `0 < β < 1` for `β := ∏_{g ≠ 1} |χ_V(g)|²` (assuming
the characters never vanish) and rules this out by passing to the Galois
conjugates of the representation supplied by part (a). Remark 5.2.8 replaces that
step by a purely arithmetic argument.

## What is formalized here

The remark decomposes into five steps. Three of them are elementary and
self-contained; they are formalized in this file as real, `sorry`-free theorems:

* **Step 1** (`pow_coprime_bijective`): for `gcd(|G|, j) = 1` the map `g ↦ gʲ` is a
  bijection `G → G`. This is `Nat.Coprime.pow_left_bijective` / `powCoprime` from
  Mathlib, restated in the form the remark uses.

* **Step 2** (`prod_ne_one_pow`): the bijection of Step 1 fixes `1`, hence
  restricts to a bijection of `G ∖ {1}`; reindexing the product along it gives
  `∏_{g ≠ 1} f(gʲ) = ∏_{g ≠ 1} f(g)` for any `f` into a commutative monoid. Taking
  `f g = |χ_V(g)|²` this is exactly "`∏_{g ≠ 1} |χ_V(gʲ)|² = β`".

* **Step 5 + contradiction** (`not_isIntegral_rat_mem_Ioo`): an algebraic integer
  that is rational and lies strictly between `0` and `1` does not exist. Combined
  with Step 2's identity (which forces `β` to be Galois-invariant, hence rational)
  and the fact that `β` is a product of algebraic integers, this "deduce that `β`
  is an integer, and derive a contradiction" step closes the argument. The
  algebraic-integer-∩-ℚ-is-ℤ input is `Etingof.Proposition5_2_5`.

The **root-of-unity content of Step 3** is also formalized here, `sorry`-free:

* **Step 3 (root-of-unity content)** (`character_eq_sum_rootsOfUnity`): every
  character value `χ_V(g)` is a sum of `N`-th roots of unity, `N = |G|` — the
  eigenvalues of `ρ(g)` are the roots of its characteristic polynomial, each an
  `N`-th root of unity (as `ρ(g)` has order dividing `N`), and `χ_V(g)` is their
  sum. This places `χ_V(g)`, hence `β`, in the ring generated by the `N`-th roots
  of unity, i.e. in `ℚ(ζ_N)`.

## What remains (foundation sub-issue)

**Step 4** — that `β` is fixed by the automorphism `ζ ↦ ζʲ` of `K = ℚ(ζ_N)` (via
the identity `σ_j(χ_V(g)) = χ_V(gʲ)`, so `σ_j(β) = ∏_{g≠1} |χ_V(gʲ)|² = β` by
Step 2), forcing `β ∈ ℚ` — requires the cyclotomic field `ℚ(ζ_N)` as a Lean object,
the Galois action of `Gal(ℚ(ζ_N)/ℚ) ≅ (ℤ/Nℤ)ˣ`, and the representation-theoretic
identity `σ_j(χ_V(g)) = χ_V(gʲ)` (`σ_j` sends each root-of-unity eigenvalue `λ` of
`ρ(g)` to `λʲ`, and the eigenvalues of `ρ(gʲ) = ρ(g)ʲ` are the `λʲ`). That is a
large, standalone foundation and is tracked as a separate sub-issue; this file lands
the elementary steps, the closing contradiction, the algebraic-integer half, and the
root-of-unity content of Step 3 incrementally.
-/

namespace Etingof.Remark5_2_8

open Finset

variable {G : Type*} [Group G]

/-- **Step 1 of Remark 5.2.8.** For `j` coprime to `|G|`, the `j`-th power map
`g ↦ gʲ` is a bijection `G → G`. -/
theorem pow_coprime_bijective {j : ℕ} (h : (Nat.card G).Coprime j) :
    Function.Bijective (fun g : G => g ^ j) :=
  Nat.Coprime.pow_left_bijective h

/-- The `j`-th power map fixes the identity and is injective, so `gʲ = 1 ↔ g = 1`
when `j` is coprime to `|G|`. -/
theorem pow_eq_one_iff {j : ℕ} (h : (Nat.card G).Coprime j) {g : G} :
    g ^ j = 1 ↔ g = 1 := by
  refine ⟨fun hg => (pow_coprime_bijective h).injective ?_, fun hg => by rw [hg, one_pow]⟩
  simpa using hg

/-- **Step 2 of Remark 5.2.8.** Since `g ↦ gʲ` (for `gcd(|G|, j) = 1`) is a
bijection of `G` fixing `1`, reindexing the product over `G ∖ {1}` along it leaves
the product unchanged:
`∏_{g ≠ 1} f(gʲ) = ∏_{g ≠ 1} f(g)`.
Taking `f g = |χ_V(g)|²` this is the identity `∏_{g ≠ 1} |χ_V(gʲ)|² = β`. -/
theorem prod_ne_one_pow {M : Type*} [CommMonoid M] [Fintype G] [DecidableEq G] {j : ℕ}
    (h : (Nat.card G).Coprime j) (f : G → M) :
    ∏ g ∈ univ.filter (· ≠ 1), f (g ^ j) = ∏ g ∈ univ.filter (· ≠ 1), f g := by
  refine Finset.prod_bij (fun g _ => g ^ j) ?_ ?_ ?_ ?_
  · -- the map sends `G ∖ {1}` into `G ∖ {1}`
    intro a ha
    simp only [mem_filter, mem_univ, true_and] at ha ⊢
    rwa [Ne, pow_eq_one_iff h]
  · -- injective on `G ∖ {1}`
    intro a₁ _ a₂ _ hab
    exact (pow_coprime_bijective h).injective hab
  · -- surjective onto `G ∖ {1}`
    intro b hb
    simp only [mem_filter, mem_univ, true_and] at hb
    obtain ⟨a, ha⟩ := (pow_coprime_bijective h).surjective b
    refine ⟨a, ?_, ha⟩
    simp only [mem_filter, mem_univ, true_and]
    rintro rfl
    exact hb (by simpa using ha.symm)
  · intro a _; rfl

/-- **Step 5 of Remark 5.2.8, with the contradiction.** There is no rational
algebraic integer strictly between `0` and `1`. Concretely, if `q : ℚ` maps to an
algebraic integer in `ℂ` and `0 < q < 1`, we reach a contradiction: by
`Etingof.Proposition5_2_5` such a `q` is an integer, and there is no integer in
`(0, 1)`.

In the remark, `β` is Galois-invariant (Step 4, using Step 2's identity), hence
rational, and it is a product of algebraic integers, hence an algebraic integer;
the main argument of Problem 5.2.7(b) gives `0 < β < 1`. This lemma is exactly the
final "deduce that `β` is an integer, and derive a contradiction". -/
theorem not_isIntegral_rat_mem_Ioo {q : ℚ}
    (hint : IsIntegral ℤ (algebraMap ℚ ℂ q)) (h0 : 0 < q) (h1 : q < 1) : False := by
  obtain ⟨n, rfl⟩ := (Etingof.Proposition5_2_5 q).mp hint
  have hn0 : (0 : ℤ) < n := by exact_mod_cast h0
  have hn1 : n < 1 := by exact_mod_cast h1
  omega

/-!
## The algebraic-integer half of Steps 3-5

The final contradiction needs two facts about `β := ∏_{g ≠ 1} |χ_V(g)|²`:

* `β` is **rational** — this is the content of Steps 3-4 (Galois invariance in
  `ℚ(ζ_N)`), which requires cyclotomic / Galois infrastructure and is tracked in
  the foundation sub-issue;
* `β` is an **algebraic integer** — established here, `sorry`-free, from the fact
  that character values are algebraic integers (`FDRep.character_isIntegral`).

Given both, `not_isIntegral_rat_mem_Ioo` closes the argument once `0 < β < 1`.
The integrality half below needs none of the blocked infrastructure.
-/

open scoped ComplexConjugate

/-- The complex conjugate of an algebraic integer in `ℂ` is again an algebraic
integer: conjugation `z ↦ conj z` is a `ℤ`-algebra automorphism of `ℂ`, so it
preserves integrality over `ℤ`. -/
theorem isIntegral_conj {z : ℂ} (hz : IsIntegral ℤ z) : IsIntegral ℤ (conj z) :=
  hz.map (Complex.conjAe.restrictScalars ℤ).toAlgHom

set_option linter.unusedFintypeInType false in
/-- The squared modulus `|χ_V(g)|²` of a character value is an algebraic integer:
`|χ_V(g)|² = χ_V(g) · conj(χ_V(g))` is a product of algebraic integers
(`FDRep.character_isIntegral`), and the algebraic integers form a ring. -/
theorem isIntegral_normSq_character {G : Type} [Group G] [Fintype G]
    (V : FDRep ℂ G) (g : G) :
    IsIntegral ℤ ((Complex.normSq (V.character g) : ℂ)) := by
  rw [← Complex.mul_conj]
  exact (FDRep.character_isIntegral V g).mul (isIntegral_conj (FDRep.character_isIntegral V g))

set_option linter.unusedFintypeInType false in
/-- **The algebraic-integer half of Remark 5.2.8.** For any finite set `s` of group
elements, `∏_{g ∈ s} |χ_V(g)|²` is an algebraic integer. Taking
`s = G ∖ {1}` this is exactly "`β` is a product of algebraic integers, hence an
algebraic integer" — the input to `not_isIntegral_rat_mem_Ioo` that does not depend
on the cyclotomic Galois argument (Steps 3-4). -/
theorem isIntegral_prod_normSq_character {G : Type} [Group G] [Fintype G]
    (V : FDRep ℂ G) (s : Finset G) :
    IsIntegral ℤ (∏ g ∈ s, (Complex.normSq (V.character g) : ℂ)) := by
  have h : (∏ g ∈ s, (Complex.normSq (V.character g) : ℂ)) ∈ integralClosure ℤ ℂ :=
    prod_mem (fun g _ => isIntegral_normSq_character V g)
  exact h

/-!
## Step 3 (root-of-unity content): character values are sums of `N`-th roots of unity

Step 3 of the remark is "`β ∈ K := ℚ(ζ_N)`". The concrete representation-theoretic
fact underlying it is that each character value `χ_V(g)` is a *sum of `N`-th roots of
unity*, `N = |G|`: `χ_V(g)` is the trace of `ρ(g)`, hence the sum of the eigenvalues
of `ρ(g)`, and every eigenvalue `μ` satisfies `μ^{orderOf g} = 1`, so `μ^N = 1` since
`orderOf g ∣ N` (Lagrange). This places `χ_V(g)` — and therefore `β`, a product of the
`|χ_V(g)|² = χ_V(g)·χ_V(g⁻¹)` — in the ring generated by the `N`-th roots of unity,
i.e. in `ℚ(ζ_N)`.

The remaining half of Steps 3-4 — that `β` is *fixed* by the Galois action `ζ ↦ ζʲ`
(via `σ_j(χ_V(g)) = χ_V(gʲ)`), forcing `β ∈ ℚ` — needs the cyclotomic field `ℚ(ζ_N)`
as a Lean object together with its Galois group `(ZMod N)ˣ`, and is tracked in the
foundation sub-issue.
-/

set_option linter.unusedFintypeInType false in
/-- **Step 3 of Remark 5.2.8 (root-of-unity content).** For a finite-dimensional
complex representation `V` of a finite group `G`, every character value `χ_V(g)` is a
sum of `N`-th roots of unity with `N = |G|`. Concretely, the multiset of eigenvalues
of `ρ(g)` (the roots of its characteristic polynomial) consists of `N`-th roots of
unity and sums to `χ_V(g)`.

This is the concrete meaning of "`χ_V(g) ∈ ℚ(ζ_N)`" that underlies Step 3: the
eigenvalues of `ρ(g)` are roots of unity because `ρ(g)` has order dividing `N`, and
the character is their sum. -/
theorem character_eq_sum_rootsOfUnity {G : Type} [Group G] [Fintype G]
    (V : FDRep ℂ G) (g : G) :
    ∃ s : Multiset ℂ, (∀ μ ∈ s, μ ^ Nat.card G = 1) ∧ V.character g = s.sum := by
  set f := V.ρ g with hf_def
  -- `f^{orderOf g} = 1`, since `ρ` is a homomorphism and `g^{orderOf g} = 1`.
  have hf_pow : f ^ orderOf g = 1 := by
    rw [hf_def, ← map_pow, pow_orderOf_eq_one, map_one]
  have hne : LinearMap.charpoly f ≠ 0 := (LinearMap.charpoly_monic f).ne_zero
  refine ⟨(LinearMap.charpoly f).roots, ?_, ?_⟩
  · -- Every root `μ` of the charpoly is an eigenvalue, hence `μ^{orderOf g} = 1`,
    -- hence `μ^N = 1` because `orderOf g ∣ N = |G|`.
    intro μ hμ
    rw [Polynomial.mem_roots hne] at hμ
    have heig : Module.End.HasEigenvalue f μ :=
      (Module.End.hasEigenvalue_iff_isRoot_charpoly f μ).mpr hμ
    obtain ⟨v, hv⟩ := heig.exists_hasEigenvector
    have hpow_v : ∀ k : ℕ, (f ^ k) v = (μ ^ k) • v := by
      intro k; induction k with
      | zero => simp
      | succ k ih => rw [pow_succ, Module.End.mul_apply, hv.apply_eq_smul,
          map_smul, ih, smul_smul, ← pow_succ']
    have h1 : v = (μ ^ orderOf g) • v := by rw [← hpow_v, hf_pow]; simp
    have h2 : (μ ^ orderOf g - 1) • v = 0 := by rw [sub_smul, one_smul, ← h1, sub_self]
    have hμord : μ ^ orderOf g = 1 := by
      rcases smul_eq_zero.mp h2 with h3 | h3
      · exact sub_eq_zero.mp h3
      · exact absurd h3 hv.2
    obtain ⟨k, hk⟩ := orderOf_dvd_card (x := g)
    rw [Nat.card_eq_fintype_card, hk, pow_mul, hμord, one_pow]
  · -- `χ_V(g) = trace(ρ(g)) = sum of the charpoly roots` (which split over `ℂ`).
    change LinearMap.trace ℂ V f = _
    set b := Module.finBasis ℂ V
    rw [LinearMap.trace_eq_matrix_trace ℂ b]
    have h1 : (LinearMap.toMatrix b b f).trace =
        (LinearMap.toMatrix b b f).charpoly.roots.sum :=
      Matrix.trace_eq_sum_roots_charpoly _
    simpa only [LinearMap.charpoly_toMatrix] using h1

end Etingof.Remark5_2_8
