import Mathlib
import EtingofRepresentationTheory.Chapter5.Theorem5_18_1

/-!
# Theorem 5.18.1: exhaustiveness of the simple families (Double Centralizer)

`Theorem5_18_1.lean` produces the bimodule decomposition
`E ≃ ⨁ᵢ Vᵢ ⊗ Lᵢ` with the `Vᵢ` pairwise non-isomorphic simple `A`-modules
and the `Lᵢ = Vᵢ →ₗ[A] E` simple `B`-modules (`B = centralizer(A)`). What that
file does *not* establish is **exhaustiveness**: that the list `{Vᵢ}` (resp.
`{Lᵢ}`) already contains *every* simple `A`-module (resp. `B`-module) up to
isomorphism. Without exhaustiveness the theorem only exhibits a finite family of
summands; the book's claim that the `Vᵢ` "are all the irreducible
representations of `A`" is stronger.

This file supplies the missing crux, a single embedding lemma

* `exists_simpleSubmodule_iso_of_faithful`: **every simple module of a
  semisimple subalgebra `C ⊆ End_k(E)` is isomorphic to a simple `C`-submodule
  of `E`.**

Because `E` is faithful over `C` (an element of `C ⊆ End_k(E)` that kills `E`
is the zero endomorphism), a simple `C`-module `S` embeds into `C` (as a direct
summand, `C` being semisimple), and `C` embeds `C`-linearly into `E → E` by
`c ↦ (e ↦ c e)`; some coordinate projection of the composite `S → E` is a
nonzero, hence injective, `C`-linear map, and its range is a simple submodule
of `E` isomorphic to `S`.

The lemma applies to *both* sides of the double centralizer theorem:

* with `C = A` it gives **A-family exhaustiveness**
  (`Theorem5_18_1_A_family_exhaustive`): every simple `A`-module is realised as
  a simple submodule of `E`, i.e. is one of the `Vᵢ`;
* with `C = centralizer(A)` (semisimple by
  `Theorem5_18_1_commutant_semisimple`) it gives **B-family exhaustiveness**
  (`Theorem5_18_1_B_family_exhaustive`): every simple `B`-module is realised as
  a simple `B`-submodule of `E`.

Combined with the already-established distinctness of the `Vᵢ`
(`Theorem5_18_1_bimodule_decomposition_explicit`) and the biduality
correspondence `Vᵢ ↔ Lᵢ = Hom_A(Vᵢ, E)`
(`MultiplicitySpaceBiduality.multiplicitySpace_biduality_Aiso`,
`isSimpleModule_homA_centralizer`), these results pin down both families as
complete lists of simple modules.
-/

open scoped TensorProduct

universe u v w

namespace Etingof

variable (k : Type u) [Field k]
  (E : Type v) [AddCommGroup E] [Module k E] [Module.Finite k E]

omit [Module.Finite k E] in
/-- **Every simple module of a semisimple subalgebra of `End_k(E)` is realised
inside `E`.**

For a subalgebra `C ⊆ End_k(E)` that is semisimple as a ring, any simple
`C`-module `S` is isomorphic to a simple `C`-submodule of `E`.

The finite-dimensionality of `E` is not needed for the statement, but `E` being
faithful over `C` is automatic here: `C` is literally a subalgebra of
`End_k(E)`, so the natural map `C → (E → E)`, `c ↦ (e ↦ c e)`, is injective.

Proof outline:
* `S` is a quotient of `C` (cyclic, generated by any nonzero `s₀`), hence — `C`
  being semisimple — isomorphic to a `C`-submodule of `C`, giving an injection
  `ι : S ↪ C`;
* `ψ : C ↪ (E → E)`, `c ↦ (e ↦ c e)`, is injective since `C ⊆ End_k(E)`;
* the composite `S → (E → E)` is injective, so some coordinate `f : S → E` is
  nonzero, hence injective (`S` simple), and `range f` is the desired simple
  submodule. -/
theorem exists_simpleSubmodule_iso_of_faithful
    (C : Subalgebra k (Module.End k E)) [IsSemisimpleRing C]
    (S : Type w) [AddCommGroup S] [Module C S] [IsSimpleModule C S] :
    ∃ W : Submodule C E, IsSimpleModule C W ∧ Nonempty (S ≃ₗ[C] W) := by
  classical
  haveI : Nontrivial S := IsSimpleModule.nontrivial C S
  obtain ⟨s₀, hs₀⟩ := exists_ne (0 : S)
  -- Surjection `g : C ↠ S`, `a ↦ a • s₀` (cyclic since `S` is simple).
  set g : (↥C) →ₗ[↥C] S := LinearMap.toSpanSingleton (↥C) S s₀ with hg
  have hg_surj : Function.Surjective g := by
    intro x
    have hspan : Submodule.span (↥C) {s₀} = ⊤ := by
      rcases eq_bot_or_eq_top (Submodule.span (↥C) {s₀}) with h | h
      · exact absurd (by simpa [h] using Submodule.mem_span_singleton_self (R := ↥C) s₀) hs₀
      · exact h
    have hx : x ∈ Submodule.span (↥C) {s₀} := by rw [hspan]; trivial
    rw [Submodule.mem_span_singleton] at hx
    obtain ⟨a, ha⟩ := hx
    exact ⟨a, by simp only [hg, LinearMap.toSpanSingleton_apply]; exact ha⟩
  -- `S ≃ C ⧸ ker g`; `ker g` splits off a summand `P ≃ C ⧸ ker g`, giving `S ↪ C`.
  let equivS : ((↥C) ⧸ LinearMap.ker g) ≃ₗ[↥C] S := g.quotKerEquivOfSurjective hg_surj
  obtain ⟨P, ⟨eP⟩⟩ :=
    IsSemisimpleModule.exists_submodule_linearEquiv_quotient (LinearMap.ker g)
  let ιSC : S →ₗ[↥C] (↥C) := P.subtype ∘ₗ (equivS.symm.trans eP.symm).toLinearMap
  have hι_inj : Function.Injective ιSC :=
    Subtype.val_injective.comp (equivS.symm.trans eP.symm).injective
  -- `ψ : C ↪ (E → E)`, `c ↦ (e ↦ c e)`.
  let ψ : (↥C) →ₗ[↥C] (E → E) :=
    { toFun := fun c e => c.val e
      map_add' := fun c c' => by ext e; simp
      map_smul' := fun a c => by ext e; rfl }
  have hψ_inj : Function.Injective ψ := by
    rw [injective_iff_map_eq_zero]
    intro c hc
    have hval : (c : Module.End k E) = 0 := by
      ext e; exact congr_fun hc e
    exact Subtype.ext (by simpa using hval)
  -- The composite `S ↪ (E → E)` is injective, hence nonzero on `s₀`.
  let emb : S →ₗ[↥C] (E → E) := ψ ∘ₗ ιSC
  have hemb_inj : Function.Injective emb := hψ_inj.comp hι_inj
  have hemb_s₀ : emb s₀ ≠ 0 := fun h => hs₀ (hemb_inj (by rw [h, map_zero]))
  -- Some coordinate `f = proj e ∘ emb : S → E` is nonzero.
  have hcoord : ∃ e : E, (emb s₀) e ≠ 0 := by
    by_contra hh
    apply hemb_s₀
    funext e
    by_contra hne
    exact hh ⟨e, hne⟩
  obtain ⟨e, he⟩ := hcoord
  let f : S →ₗ[↥C] E := (LinearMap.proj e) ∘ₗ emb
  have hf_ne : f ≠ 0 := fun h => he (by
    have : f s₀ = 0 := by rw [h]; rfl
    exact this)
  -- `f` is injective (`S` simple), so its range is a simple submodule of `E`.
  have hker : LinearMap.ker f = ⊥ := by
    rcases eq_bot_or_eq_top (LinearMap.ker f) with h | h
    · exact h
    · exact absurd (LinearMap.ker_eq_top.mp h) hf_ne
  have hf_inj : Function.Injective f := LinearMap.ker_eq_bot.mp hker
  refine ⟨LinearMap.range f, ?_, ⟨LinearEquiv.ofInjective f hf_inj⟩⟩
  exact IsSimpleModule.congr (LinearEquiv.ofInjective f hf_inj).symm

omit [Module.Finite k E] in
/-- **A-family exhaustiveness (Double Centralizer Theorem 5.18.1(iii)).**

Every simple `A`-module is isomorphic to a simple `A`-submodule of `E`, i.e. is
one of the `Vᵢ` appearing in the bimodule decomposition
`Theorem5_18_1_bimodule_decomposition_explicit`. Together with the pairwise
non-isomorphism of the `Vᵢ` proved there, this shows `{Vᵢ}` is the complete list
of simple `A`-modules. -/
theorem Theorem5_18_1_A_family_exhaustive
    (A : Subalgebra k (Module.End k E)) [IsSemisimpleRing A] [FaithfulSMul A E]
    (S : Type w) [AddCommGroup S] [Module A S] [IsSimpleModule A S] :
    ∃ W : Submodule A E, IsSimpleModule A W ∧ Nonempty (S ≃ₗ[A] W) :=
  exists_simpleSubmodule_iso_of_faithful k E A S

/-- **B-family exhaustiveness (Double Centralizer Theorem 5.18.1(iii)).**

With `B = centralizer(A)` (semisimple by `Theorem5_18_1_commutant_semisimple`),
every simple `B`-module is isomorphic to a simple `B`-submodule of `E`. Together
with the multiplicity-space distinctness
(`MultiplicitySpaceBiduality.multiplicitySpace_Cdistinct`) and the biduality
correspondence, this shows the `B`-simples `{Lᵢ = Hom_A(Vᵢ, E)}` form the
complete list of simple `B`-modules. -/
theorem Theorem5_18_1_B_family_exhaustive
    (A : Subalgebra k (Module.End k E)) [IsSemisimpleRing A] [FaithfulSMul A E]
    (T : Type w)
    [AddCommGroup T]
    [Module (↥(Subalgebra.centralizer k (A : Set (Module.End k E)))) T]
    [IsSimpleModule (↥(Subalgebra.centralizer k (A : Set (Module.End k E)))) T] :
    ∃ W : Submodule (↥(Subalgebra.centralizer k (A : Set (Module.End k E)))) E,
      IsSimpleModule (↥(Subalgebra.centralizer k (A : Set (Module.End k E)))) W ∧
      Nonempty (T ≃ₗ[↥(Subalgebra.centralizer k (A : Set (Module.End k E)))] W) := by
  haveI : IsSemisimpleRing (↥(Subalgebra.centralizer k (A : Set (Module.End k E)))) :=
    Theorem5_18_1_commutant_semisimple k E A
  exact exists_simpleSubmodule_iso_of_faithful k E
    (Subalgebra.centralizer k (A : Set (Module.End k E))) T

end Etingof
