-- Section 5.1: Types of Representations
import EtingofRepresentationTheory.Chapter5.Definition5_1_1
import EtingofRepresentationTheory.Chapter5.Example5_1_3
import EtingofRepresentationTheory.Chapter5.Definition5_1_4
import EtingofRepresentationTheory.Chapter5.Theorem5_1_5
import EtingofRepresentationTheory.Chapter5.FrobeniusSchurRealType
import EtingofRepresentationTheory.Chapter5.FrobeniusSchurTraceIdentity
import EtingofRepresentationTheory.Chapter5.Corollary5_1_6

-- Section 5.2: Algebraic Numbers and Integers
import EtingofRepresentationTheory.Chapter5.Definition5_2_1
import EtingofRepresentationTheory.Chapter5.Definition5_2_2
import EtingofRepresentationTheory.Chapter5.Proposition5_2_3
import EtingofRepresentationTheory.Chapter5.Proposition5_2_4
import EtingofRepresentationTheory.Chapter5.Proposition5_2_5
import EtingofRepresentationTheory.Chapter5.Lemma5_2_6

-- Section 5.3: Divisibility and Integrality
import EtingofRepresentationTheory.Chapter5.Theorem5_3_1
import EtingofRepresentationTheory.Chapter5.Proposition5_3_2

-- Section 5.4: Solvability and Simplicity
import EtingofRepresentationTheory.Chapter5.Definition5_4_1
import EtingofRepresentationTheory.Chapter5.Theorem5_4_3
import EtingofRepresentationTheory.Chapter5.Theorem5_4_4
import EtingofRepresentationTheory.Chapter5.Lemma5_4_5
import EtingofRepresentationTheory.Chapter5.Theorem5_4_6
import EtingofRepresentationTheory.Chapter5.Lemma5_4_7

-- Section 5.6: Product Groups
import EtingofRepresentationTheory.Chapter5.Theorem5_6_1

-- Section 5.7: Virtual Representations
import EtingofRepresentationTheory.Chapter5.Definition5_7_1
import EtingofRepresentationTheory.Chapter5.Lemma5_7_2

-- Section 5.8: Induced Representations
import EtingofRepresentationTheory.Chapter5.Definition5_8_1
import EtingofRepresentationTheory.Chapter5.Remark5_8_2

-- Section 5.9: Frobenius Formula
import EtingofRepresentationTheory.Chapter5.TraceCoinvariants
import EtingofRepresentationTheory.Chapter5.Theorem5_9_1

-- Section 5.10: Frobenius Reciprocity
import EtingofRepresentationTheory.Chapter5.Theorem5_10_1

-- Section 5.11: Worked examples of induced representations (S₃)
import EtingofRepresentationTheory.Chapter5.Discussion5_11_examples

-- Section 5.12: Specht Modules and Young Tableaux
import EtingofRepresentationTheory.Chapter5.Definition5_12_1
import EtingofRepresentationTheory.Chapter5.Theorem5_12_2
import EtingofRepresentationTheory.Chapter5.Theorem5_12_2_Irreducible
import EtingofRepresentationTheory.Chapter5.Theorem5_12_2_Distinct
import EtingofRepresentationTheory.Chapter5.Theorem5_12_2_DistinctGeneral
import EtingofRepresentationTheory.Chapter5.Theorem5_12_2_Classification
import EtingofRepresentationTheory.Chapter5.Example5_12_3
import EtingofRepresentationTheory.Chapter5.Corollary5_12_4

-- Section 5.13: Young Projectors
import EtingofRepresentationTheory.Chapter5.Lemma5_13_1
import EtingofRepresentationTheory.Chapter5.Lemma5_13_2
import EtingofRepresentationTheory.Chapter5.Lemma5_13_3
import EtingofRepresentationTheory.Chapter5.Lemma5_13_4

-- Section 5.14: Kostka Numbers
import EtingofRepresentationTheory.Chapter5.Introduction5_14
import EtingofRepresentationTheory.Chapter5.Proposition5_14_1
import EtingofRepresentationTheory.Chapter5.Definition5_14_2
import EtingofRepresentationTheory.Chapter5.Theorem5_14_3

-- Section 5.15: Frobenius Character Formula
import EtingofRepresentationTheory.Chapter5.Theorem5_15_1
import EtingofRepresentationTheory.Chapter5.Lemma5_15_3
import EtingofRepresentationTheory.Chapter5.Corollary5_15_4
import EtingofRepresentationTheory.Chapter5.PowerSumCauchyIdentity

-- Section 5.17: Hook Length Formula
import EtingofRepresentationTheory.Chapter5.SYTFintype
import EtingofRepresentationTheory.Chapter5.PolytabloidBasis
import EtingofRepresentationTheory.Chapter5.TabloidModule
-- The Garnir-straightening route to dim V_λ = #SYT was removed: it is not in
-- Etingof's book (§5.17 derives the hook length formula via the Frobenius
-- character formula + Vandermonde, not the standard polytabloid basis), had no
-- consumers, and its residual was an off-book research nut. Theorem 5.17.1 goes
-- through the book's Frobenius route (`Theorem5_17_1` → `CharValueHookFormula`).
import EtingofRepresentationTheory.Chapter5.Theorem5_17_1

-- Section 5.18: Schur-Weyl Duality
import EtingofRepresentationTheory.Chapter5.Theorem5_18_1
import EtingofRepresentationTheory.Chapter5.Theorem5_18_2
import EtingofRepresentationTheory.Chapter5.Lemma5_18_3
import EtingofRepresentationTheory.Chapter5.Theorem5_18_4
import EtingofRepresentationTheory.Chapter5.PrimitiveIdempotentSimplicity
import EtingofRepresentationTheory.Chapter5.PolynomialTensorBridge
import EtingofRepresentationTheory.Chapter5.EvalEqOnGL
import EtingofRepresentationTheory.Chapter5.DistinctEigenvalueDensity
import EtingofRepresentationTheory.Chapter5.PolynomialRepEmbedding
import EtingofRepresentationTheory.Chapter5.DetLocalization
import EtingofRepresentationTheory.Chapter5.DetIrreducible
import EtingofRepresentationTheory.Chapter5.PolynomialGLRightAction
import EtingofRepresentationTheory.Chapter5.PolynomialGLBiAction
import EtingofRepresentationTheory.Chapter5.LocalizationGLRightAction
import EtingofRepresentationTheory.Chapter5.KernelLemmaKPrime
import EtingofRepresentationTheory.Chapter5.ConstituentCharacterExtraction
import EtingofRepresentationTheory.Chapter5.CharEqIso
import EtingofRepresentationTheory.Chapter5.CauchyDetQuotient
import EtingofRepresentationTheory.Chapter5.CauchyCharacterRight
import EtingofRepresentationTheory.Chapter5.CauchySchurBasis
import EtingofRepresentationTheory.Chapter5.SchurPolyShift
import EtingofRepresentationTheory.Chapter5.RepresentationAsModuleHom
import EtingofRepresentationTheory.Chapter5.CauchyCharDiff
import EtingofRepresentationTheory.Chapter5.CauchyWeightSpaceDimension
import EtingofRepresentationTheory.Chapter5.CauchyCharacterRightAssembly
import EtingofRepresentationTheory.Chapter5.CauchyDetQuotientDegree
import EtingofRepresentationTheory.Chapter5.CauchyDetQuotientGrading
import EtingofRepresentationTheory.Chapter5.SimpleSubrepExtraction
import EtingofRepresentationTheory.Chapter5.CleanFormalCharacterAdditivity
import EtingofRepresentationTheory.Chapter5.CleanSubSpanning
import EtingofRepresentationTheory.Chapter5.CleanQuotientHelpers
import EtingofRepresentationTheory.Chapter5.CleanConstituentExtraction
import EtingofRepresentationTheory.Chapter5.KernelLemmaKPrimeAssembly
import EtingofRepresentationTheory.Chapter5.DetPowerFiltration
import EtingofRepresentationTheory.Chapter5.KernelLemmaK
import EtingofRepresentationTheory.Chapter5.DetInvElim

-- Section 5.19: Schur-Weyl Duality and Schur Functors
import EtingofRepresentationTheory.Chapter5.Proposition5_19_1
import EtingofRepresentationTheory.Chapter5.Corollary5_19_2
import EtingofRepresentationTheory.Chapter5.Example5_19_3

-- Section 5.21: Schur Polynomials
import EtingofRepresentationTheory.Chapter5.Proposition5_21_1
import EtingofRepresentationTheory.Chapter5.Proposition5_21_2

-- Section 5.22: Weyl Character Formula
import EtingofRepresentationTheory.Chapter5.PermDiagonalTrace
import EtingofRepresentationTheory.Chapter5.Theorem5_22_1
import EtingofRepresentationTheory.Chapter5.SchurWeylGLTransfer
import EtingofRepresentationTheory.Chapter5.SchurWeylSpecialBlockGeneral
import EtingofRepresentationTheory.Chapter5.SemisimpleIsotypic
import EtingofRepresentationTheory.Chapter5.SchurModuleSimple
import EtingofRepresentationTheory.Chapter5.Proposition5_22_2
import EtingofRepresentationTheory.Chapter5.SchurWeylPolynomialIdentity

-- Section 5.23: Algebraic Representations of GL(V)
import EtingofRepresentationTheory.Chapter5.Definition5_23_1
import EtingofRepresentationTheory.Chapter5.GLRepAlgebraic
import EtingofRepresentationTheory.Chapter5.DetTwistAlgebraic
import EtingofRepresentationTheory.Chapter5.PolynomialWeightSaturation
import EtingofRepresentationTheory.Chapter5.DetClearing
import EtingofRepresentationTheory.Chapter5.Theorem5_23_2Core
import EtingofRepresentationTheory.Chapter5.Theorem5_23_2
import EtingofRepresentationTheory.Chapter5.AlgIrrepGLRep
import EtingofRepresentationTheory.Chapter5.ContragredientPairing
import EtingofRepresentationTheory.Chapter5.ContragredientIdentity
import EtingofRepresentationTheory.Chapter5.AlgIrrepDualPairing
import EtingofRepresentationTheory.Chapter5.SpechtCharacterGeneral
import EtingofRepresentationTheory.Chapter5.SpechtBaseChangeComplex
import EtingofRepresentationTheory.Chapter5.SpechtBridgeGeneral
import EtingofRepresentationTheory.Chapter5.SchurModuleSpecialBlock
import EtingofRepresentationTheory.Chapter5.PolynomialGLDecomposition
import EtingofRepresentationTheory.Chapter5.PolynomialGLSemisimple
import EtingofRepresentationTheory.Chapter5.CharacterIndependence
import EtingofRepresentationTheory.Chapter5.SchurWeylSimplesClassification
import EtingofRepresentationTheory.Chapter5.SchurWeylLDistinct
import EtingofRepresentationTheory.Chapter5.SchurWeylBimoduleFull
import EtingofRepresentationTheory.Chapter5.SchurWeylPartition
import EtingofRepresentationTheory.Chapter5.SchurWeylFormalCharacterIso
import EtingofRepresentationTheory.Chapter5.DiagonalizableConj

-- Section 5.25: Representations of GL₂(𝔽_q)
import EtingofRepresentationTheory.Chapter5.Proposition5_25_1
import EtingofRepresentationTheory.Chapter5.Theorem5_25_2
import EtingofRepresentationTheory.Chapter5.GL2CharacterValues
import EtingofRepresentationTheory.Chapter5.Lemma5_25_3
import EtingofRepresentationTheory.Chapter5.Discussion5_25_4

-- Section 5.26: Artin's Theorem
import EtingofRepresentationTheory.Chapter5.Theorem5_26_1
import EtingofRepresentationTheory.Chapter5.Corollary5_26_3

import EtingofRepresentationTheory.Chapter5.QuotDetDegreeAlgebraic

-- Section 5.27: Representations of Semidirect Products
import EtingofRepresentationTheory.Chapter5.Theorem5_27_1

/-! # Chapter 5: Representations of the Symmetric Group -/
