-- Section 4.1: Maschke's Theorem
import EtingofRepresentationTheory.Chapter4.Theorem4_1_1
import EtingofRepresentationTheory.Chapter4.Proposition4_1_2
import EtingofRepresentationTheory.Chapter4.Example4_1_3

-- Section 4.2: Characters
import EtingofRepresentationTheory.Chapter4.Theorem4_2_1
import EtingofRepresentationTheory.Chapter4.Corollary4_2_2
import EtingofRepresentationTheory.Chapter4.Corollary4_2_4

-- Section 4.4: Duals and Tensor Products
import EtingofRepresentationTheory.Chapter4.Discussion_4_4

-- Section 4.3: Examples
import EtingofRepresentationTheory.Chapter4.Example4_3_S3
import EtingofRepresentationTheory.Chapter4.Example4_3_Q8
import EtingofRepresentationTheory.Chapter4.Example4_3_FiniteAbelianGroups
import EtingofRepresentationTheory.Chapter4.Example4_3_S4

-- Section 4.5: Orthogonality of Characters
import EtingofRepresentationTheory.Chapter4.Theorem4_5_1
import EtingofRepresentationTheory.Chapter4.Discussion_after_Theorem4_5_1
import EtingofRepresentationTheory.Chapter4.Theorem4_5_4
import EtingofRepresentationTheory.Chapter4.Remark4_5_3
import EtingofRepresentationTheory.Chapter4.Remark4_5_5

-- Section 4.6: Unitary Representations
import EtingofRepresentationTheory.Chapter4.Definition4_6_1
import EtingofRepresentationTheory.Chapter4.Theorem4_6_2
import EtingofRepresentationTheory.Chapter4.Discussion_after_Theorem4_6_2
import EtingofRepresentationTheory.Chapter4.Theorem4_6_3
import EtingofRepresentationTheory.Chapter4.Remark4_6_4

-- Section 4.7: Orthogonality of Matrix Elements
import EtingofRepresentationTheory.Chapter4.Proposition4_7_1

-- Section 4.8-4.9: Character Tables and Tensor Products
import EtingofRepresentationTheory.Chapter4.Example4_8_1
import EtingofRepresentationTheory.Chapter4.Example4_9_1
import EtingofRepresentationTheory.Chapter4.Example4_8_1.A5Complete

-- Section 4.10: Frobenius Determinant
import EtingofRepresentationTheory.Chapter4.Definition4_10_1
import EtingofRepresentationTheory.Chapter4.Theorem4_10_2
import EtingofRepresentationTheory.Chapter4.Lemma4_10_3

-- Section 4.1, 4.12: Exercises (statement pass)
import EtingofRepresentationTheory.Chapter4.Exercise4_2_3
import EtingofRepresentationTheory.Chapter4.Exercise4_2_3_Assembly
import EtingofRepresentationTheory.Chapter4.Exercise4_2_3_BaseChangePiMatrix
import EtingofRepresentationTheory.Chapter4.Exercise4_2_3_Cocenter
import EtingofRepresentationTheory.Chapter4.Exercise4_2_3_CountingBound
import EtingofRepresentationTheory.Chapter4.Exercise4_2_3_FieldGeneral
import EtingofRepresentationTheory.Chapter4.Exercise4_2_3_SemisimpleBaseChange
import EtingofRepresentationTheory.Chapter4.Exercise4_2_3_StrictBound
import EtingofRepresentationTheory.Chapter4.SimpleModuleClassesBaseChange
import EtingofRepresentationTheory.Chapter4.Problem4_5_2
import EtingofRepresentationTheory.Chapter4.Problem4_1_4
import EtingofRepresentationTheory.Chapter4.Exercise4_3_1
import EtingofRepresentationTheory.Chapter4.Problem4_12_1
import EtingofRepresentationTheory.Chapter4.Problem4_12_2
import EtingofRepresentationTheory.Chapter4.Problem4_12_4
import EtingofRepresentationTheory.Chapter4.Problem4_12_5
import EtingofRepresentationTheory.Chapter4.Problem4_12_6
import EtingofRepresentationTheory.Chapter4.Problem4_12_7
import EtingofRepresentationTheory.Chapter4.Problem4_12_8
import EtingofRepresentationTheory.Chapter4.Problem4_12_9
import EtingofRepresentationTheory.Chapter4.Problem4_12_10
import EtingofRepresentationTheory.Chapter4.Problem4_12_10_Symmetric
import EtingofRepresentationTheory.Chapter4.Problem4_12_10_OrbitEval
import EtingofRepresentationTheory.Chapter4.Problem4_12_11

/-! # Chapter 4: Representations of Finite Groups: Further Results -/
