-- Section 2.1: Overview and Classification Theorems
import EtingofRepresentationTheory.Chapter2.Sl2Defs
import EtingofRepresentationTheory.Chapter2.Sl2Irrep
import EtingofRepresentationTheory.Chapter2.Problem2_15_1_complete_reducibility
import EtingofRepresentationTheory.Chapter2.Problem2_15_1_l
import EtingofRepresentationTheory.Chapter2.Problem2_15_1_m
import EtingofRepresentationTheory.Chapter2.Problem2_15_1_m_Module
import EtingofRepresentationTheory.Chapter2.Problem2_15_1_n
import EtingofRepresentationTheory.Chapter2.Theorem2_1_1
import EtingofRepresentationTheory.Chapter2.Theorem2_1_2

-- Section 2.2: Algebras
import EtingofRepresentationTheory.Chapter2.Definition2_2_1
import EtingofRepresentationTheory.Chapter2.Definition2_2_2
import EtingofRepresentationTheory.Chapter2.Definition2_2_5
import EtingofRepresentationTheory.Chapter2.Definition2_2_6
import EtingofRepresentationTheory.Chapter2.Proposition2_2_3
import EtingofRepresentationTheory.Chapter2.Example2_2_4
import EtingofRepresentationTheory.Chapter2.Discussion_commutativity_examples

-- Section 2.3: Representations
import EtingofRepresentationTheory.Chapter2.Definition2_3_1
import EtingofRepresentationTheory.Chapter2.Remark2_3_2
import EtingofRepresentationTheory.Chapter2.Discussion_2_5_well_defined
import EtingofRepresentationTheory.Chapter2.Definition2_3_4
import EtingofRepresentationTheory.Chapter2.Definition2_3_5
import EtingofRepresentationTheory.Chapter2.Definition2_3_6
import EtingofRepresentationTheory.Chapter2.Definition2_3_7
import EtingofRepresentationTheory.Chapter2.Definition2_3_8
import EtingofRepresentationTheory.Chapter2.Discussion_2_1_irreducible_indecomposable
import EtingofRepresentationTheory.Chapter2.Example2_3_3
import EtingofRepresentationTheory.Chapter2.Proposition2_3_9
import EtingofRepresentationTheory.Chapter2.Corollary2_3_10
import EtingofRepresentationTheory.Chapter2.Remark2_3_11
import EtingofRepresentationTheory.Chapter2.Remark2_3_13
import EtingofRepresentationTheory.Chapter2.Problem2_3_15
import EtingofRepresentationTheory.Chapter2.Problem2_3_17
import EtingofRepresentationTheory.Chapter2.Corollary2_3_12
import EtingofRepresentationTheory.Chapter2.Example2_3_14
import EtingofRepresentationTheory.Chapter2.Example2_3_14_continued

-- Section 2.7: Characters and the Weyl Algebra
import EtingofRepresentationTheory.Chapter2.Definition2_7_3
import EtingofRepresentationTheory.Chapter2.Proposition2_7_1
import EtingofRepresentationTheory.Chapter2.Proposition2_7_1_ii
import EtingofRepresentationTheory.Chapter2.FaithfulWeylModule
import EtingofRepresentationTheory.Chapter2.Remark2_7_2

-- Section 2.8: Quivers
import EtingofRepresentationTheory.Chapter2.Definition2_8_1
import EtingofRepresentationTheory.Chapter2.Definition2_8_3
import EtingofRepresentationTheory.Chapter2.Definition2_8_4
import EtingofRepresentationTheory.Chapter2.Definition2_8_8
import EtingofRepresentationTheory.Chapter2.Definition2_8_9
import EtingofRepresentationTheory.Chapter2.Definition2_8_10
import EtingofRepresentationTheory.Chapter2.Discussion_quiver_rep_bijection
import EtingofRepresentationTheory.Chapter2.Example2_8_2

-- Section 2.9: Lie Algebras
import EtingofRepresentationTheory.Chapter2.Definition2_9_1
import EtingofRepresentationTheory.Chapter2.Definition2_9_6
import EtingofRepresentationTheory.Chapter2.Definition2_9_7
import EtingofRepresentationTheory.Chapter2.Definition2_9_9
import EtingofRepresentationTheory.Chapter2.Example2_9_2
import EtingofRepresentationTheory.Chapter2.Example2_9_2_continued
import EtingofRepresentationTheory.Chapter2.Remark2_9_3
import EtingofRepresentationTheory.Chapter2.Remark2_9_4
import EtingofRepresentationTheory.Chapter2.Example2_9_8
import EtingofRepresentationTheory.Chapter2.Example2_9_12
import EtingofRepresentationTheory.Chapter2.Example2_9_13

-- Section 2.11-2.12: Tensor Products, Symmetric/Exterior Algebras
import EtingofRepresentationTheory.Chapter2.Definition2_11_1
import EtingofRepresentationTheory.Chapter2.Remark2_11_4
import EtingofRepresentationTheory.Chapter2.Problem2_11_6
import EtingofRepresentationTheory.Chapter2.Definition2_12_1

-- Section 2.14: Tensor/Dual Representations of Lie Algebras
import EtingofRepresentationTheory.Chapter2.Definition2_14_1
import EtingofRepresentationTheory.Chapter2.Definition2_14_2

/-! # Chapter 2: General Results of Representation Theory -/
