#!/usr/bin/env python3
"""Validate mathlib-coverage-external.json against the ledger and Mathlib.

Checks:
  - Every external dependency has a corresponding coverage entry
  - Match quality is a valid enum value (exact, partial, missing)
  - Mathlib names are non-empty strings and appear in a generated Lean checker
  - The audit records the exact Mathlib revision currently pinned by Lake
  - Required fields present in each entry

Prints summary statistics and exits non-zero on validation failure.
"""

import argparse
import json
import sys
import textwrap
from pathlib import Path


VALID_MATCH_QUALITIES = {"exact", "partial", "missing"}
REQUIRED_FIELDS = {"description", "category", "mathlib_names", "match_quality", "notes"}
CHECKER_RELATIVE_PATH = Path("EtingofRepresentationTheory/MathlibCoverageDeclarations.lean")
AUDIT_RELATIVE_PATH = Path("research/mathlib-coverage-external-audit.json")
DECLARATION_NAME_FIELDS = ("mathlib_names", "related_mathlib_names")


def load_json(path: Path) -> list:
    with open(path) as f:
        return json.load(f)


def render_checker(coverage: list[dict]) -> str:
    """Render the Lean module which resolves every non-empty declaration pointer."""
    lines = [
        "import Mathlib",
        "",
        "/-!",
        "# Mathlib declarations cited by the external-dependency coverage ledger",
        "",
        "This file is generated by `scripts/validate_mathlib_coverage.py --write-checker`.",
        "Each `#check` makes a direct or related Mathlib declaration pointer compiler-verified.",
        "-/",
        "",
    ]
    seen = set()
    for entry in coverage:
        cited_names = [
            name for field in DECLARATION_NAME_FIELDS for name in entry.get(field, [])]
        fresh_names = [name for name in cited_names if name not in seen]
        if not fresh_names:
            continue
        for line in textwrap.wrap(entry.get("description", "<missing description>"), width=96):
            lines.append(f"-- {line}")
        for name in fresh_names:
            lines.append(f"#check @{name}")
            seen.add(name)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def validate(repo_root: Path | None = None):
    if repo_root is None:
        repo_root = Path(__file__).resolve().parent.parent
    external_path = repo_root / "dependencies" / "external.json"
    coverage_path = repo_root / "research" / "mathlib-coverage-external.json"
    audit_path = repo_root / AUDIT_RELATIVE_PATH
    manifest_path = repo_root / "lake-manifest.json"
    checker_path = repo_root / CHECKER_RELATIVE_PATH

    if not external_path.exists():
        print(f"ERROR: {external_path} not found")
        return False
    if not coverage_path.exists():
        print(f"ERROR: {coverage_path} not found")
        return False

    external = load_json(external_path)
    coverage = load_json(coverage_path)

    errors = []
    warnings = []

    # Build lookup by description
    coverage_by_desc = {}
    for i, entry in enumerate(coverage):
        # Check required fields
        missing_fields = REQUIRED_FIELDS - set(entry.keys())
        if missing_fields:
            errors.append(f"Coverage entry {i}: missing fields {missing_fields}")
            continue

        desc = entry["description"]
        if desc in coverage_by_desc:
            errors.append(f"Duplicate coverage entry for: {desc}")
        coverage_by_desc[desc] = entry

        # Validate match_quality
        mq = entry["match_quality"]
        if mq not in VALID_MATCH_QUALITIES:
            errors.append(f"Entry '{desc}': invalid match_quality '{mq}' "
                          f"(must be one of {VALID_MATCH_QUALITIES})")

        # Validate mathlib_names
        names = entry["mathlib_names"]
        if not isinstance(names, list):
            errors.append(f"Entry '{desc}': mathlib_names must be a list")
        else:
            if mq != "missing" and len(names) == 0:
                warnings.append(f"Entry '{desc}': match_quality is '{mq}' but "
                                f"mathlib_names is empty")
            for name in names:
                if not isinstance(name, str) or len(name.strip()) == 0:
                    errors.append(f"Entry '{desc}': mathlib_names contains "
                                  f"empty or non-string value: {name!r}")
        related_names = entry.get("related_mathlib_names", [])
        if not isinstance(related_names, list):
            errors.append(f"Entry '{desc}': related_mathlib_names must be a list")
        else:
            for name in related_names:
                if not isinstance(name, str) or len(name.strip()) == 0:
                    errors.append(f"Entry '{desc}': related_mathlib_names contains "
                                  f"empty or non-string value: {name!r}")

        # Validate notes
        if not isinstance(entry["notes"], str) or len(entry["notes"].strip()) == 0:
            warnings.append(f"Entry '{desc}': notes is empty")

    # Check completeness: every external dep must have a coverage entry
    for ext_dep in external:
        ext_desc = ext_dep["description"]
        if ext_desc not in coverage_by_desc:
            errors.append(f"Missing coverage for external dep: {ext_desc}")

    # Keep the declaration checker mechanically synchronized with the ledger.
    expected_checker = render_checker(coverage)
    if not checker_path.exists():
        errors.append(f"Missing generated declaration checker: {checker_path}")
    elif checker_path.read_text() != expected_checker:
        errors.append(
            f"Generated declaration checker is stale: run "
            f"scripts/validate_mathlib_coverage.py --write-checker")

    # A negative coverage assertion cannot be compiler-checked, so record the
    # exact Mathlib revision against which the human audit was performed.
    if not audit_path.exists():
        errors.append(f"Missing audit metadata: {audit_path}")
    elif not manifest_path.exists():
        errors.append(f"Missing Lake manifest: {manifest_path}")
    else:
        audit = load_json(audit_path)
        manifest = load_json(manifest_path)
        mathlib_packages = [p for p in manifest.get("packages", []) if p.get("name") == "mathlib"]
        if len(mathlib_packages) != 1:
            errors.append("Lake manifest must contain exactly one mathlib package")
        else:
            mathlib = mathlib_packages[0]
            if audit.get("mathlib_revision") != mathlib.get("rev"):
                errors.append(
                    "Mathlib coverage audit revision is stale: "
                    f"{audit.get('mathlib_revision')!r} != {mathlib.get('rev')!r}")
            if audit.get("mathlib_input_revision") != mathlib.get("inputRev"):
                errors.append(
                    "Mathlib coverage audit input revision is stale: "
                    f"{audit.get('mathlib_input_revision')!r} != {mathlib.get('inputRev')!r}")
        if audit.get("entries_reviewed") != len(coverage):
            errors.append(
                f"Audit entries_reviewed is {audit.get('entries_reviewed')!r}, expected {len(coverage)}")
        nonexact_count = sum(1 for e in coverage if e.get("match_quality") != "exact")
        if audit.get("nonexact_entries_after_audit") != nonexact_count:
            errors.append(
                "Audit nonexact_entries_after_audit is "
                f"{audit.get('nonexact_entries_after_audit')!r}, expected {nonexact_count}")
        if audit.get("previously_partial_and_missing_entries_reviewed") != 24:
            errors.append(
                "Audit must record the 24 previously partial/missing entries reviewed for issue #8534")

    # Summary statistics
    exact_count = sum(1 for e in coverage if e.get("match_quality") == "exact")
    partial_count = sum(1 for e in coverage if e.get("match_quality") == "partial")
    missing_count = sum(1 for e in coverage if e.get("match_quality") == "missing")
    total = len(coverage)

    print(f"=== Mathlib Coverage Validation ===")
    print(f"External dependencies: {len(external)}")
    print(f"Coverage entries:      {total}")
    print()
    print(f"  exact:   {exact_count:3d} ({100*exact_count/total:.0f}%)")
    print(f"  partial: {partial_count:3d} ({100*partial_count/total:.0f}%)")
    print(f"  missing: {missing_count:3d} ({100*missing_count/total:.0f}%)")
    print()

    if warnings:
        print(f"Warnings ({len(warnings)}):")
        for w in warnings:
            print(f"  WARN: {w}")
        print()

    if errors:
        print(f"Errors ({len(errors)}):")
        for e in errors:
            print(f"  ERROR: {e}")
        print()
        print("VALIDATION FAILED")
        return False

    print("VALIDATION PASSED")
    return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write-checker", action="store_true",
        help=f"regenerate {CHECKER_RELATIVE_PATH}")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    if args.write_checker:
        coverage = load_json(root / "research" / "mathlib-coverage-external.json")
        checker_path = root / CHECKER_RELATIVE_PATH
        checker_path.write_text(render_checker(coverage))
        print(f"Wrote {checker_path}")
    success = validate(root)
    sys.exit(0 if success else 1)
