import VersoManual

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter5.DiscussionProofOfTheorem546

#doc (Manual) "Completion of proof of Theorem 5.4.6" =>

# Completion of proof of Theorem 5.4.6
%%%
tag := "Chapter5/Discussion_proof_of_Theorem5.4.6"
number := false
%%%

Now pick $`V \in N` such that $`\chi_V(g) \neq 0`; it exists by Lemma 5.4.7. Theorem 5.4.4 implies that $`g` (and hence any element of $`C`) acts by a scalar in $`V`. Now let $`H` be the subgroup of $`G` generated by elements $`ab^{-1}`, $`a, b \in C`. It is normal and acts trivially in $`V`, so $`H \neq G`, as $`V` is nontrivial. Also $`H \neq 1`, since $`|C| > 1`. $`\square`
