import EtingofRepresentationTheory.Chapter5.Problem5_24_2_Bridge
import EtingofRepresentationTheory.Chapter5.SchurWeylGLTransfer

/-!
# Problem 5.24.2: supporting lemmas for the FFT range identification

Two self-contained supporting lemmas for the deep step of Problem 5.24.2
(`weightedHomogeneous_invariant_mem_range_endTensorEval`, in `Problem5_24_2_Bridge.lean`):

* `mem_symGroupImage_iff_commute_diag`: the identification of `symGroupImage` (the `ℂ`-span of the
  permutation operators) with the `GL(V)`-invariant tensors: an endomorphism `M` of `V^{⊗n}` lies in
  `symGroupImage` iff it commutes with every diagonal operator `g^{⊗n}` for `g` a unit of `End V`.
  This converts the centralizer form of Schur–Weyl (`Theorem5_18_4_centralizers`) to an
  invariants statement, using the Zariski-density fact
  `adjoin_unitsTensorPow_eq_diagonalActionImage` (units `g^{⊗n}` already generate the
  diagonal-action subalgebra).
-/

noncomputable section

namespace Etingof

open scoped TensorProduct

variable (N n : ℕ)

/-- The diagonal operator `g^{⊗n}` on `V^{⊗n}` (`V = BridgeV N`) for `g` a unit of `End V`. -/
private abbrev diagOp (g : (Module.End ℂ (BridgeV N))ˣ) :
    Module.End ℂ (TensorPower ℂ (BridgeV N) n) :=
  PiTensorProduct.map (R := ℂ) (fun _ : Fin n => (g : Module.End ℂ (BridgeV N)))

/-- **`symGroupImage` = GL-invariant tensors.** An endomorphism `M` of `V^{⊗n}` lies in the
`ℂ`-span of the permutation operators `symGroupImage ℂ V n` iff it commutes with every diagonal
operator `g^{⊗n}` for `g` a unit of `End V`.

The `⊇` content is Schur–Weyl duality: by `Theorem5_18_4_centralizers`, `symGroupImage` is the
centralizer of the diagonal-action subalgebra `diagonalActionImage`, and by
`adjoin_unitsTensorPow_eq_diagonalActionImage` the latter is generated by the units' tensor powers
`g^{⊗n}`. Commuting with the generators propagates to the whole adjoin. -/
theorem mem_symGroupImage_iff_commute_diag
    (M : Module.End ℂ (TensorPower ℂ (BridgeV N) n)) :
    M ∈ symGroupImage ℂ (BridgeV N) n ↔
      ∀ g : (Module.End ℂ (BridgeV N))ˣ, Commute (diagOp N n g) M := by
  rw [(Theorem5_18_4_centralizers ℂ (BridgeV N) n).1, Subalgebra.mem_centralizer_iff]
  constructor
  · -- `M` centralizes `diagonalActionImage`; each `g^{⊗n}` lies in it.
    intro h g
    have hmem : diagOp N n g ∈
        (diagonalActionImage ℂ (BridgeV N) n :
          Set (Module.End ℂ (TensorPower ℂ (BridgeV N) n))) := by
      rw [← adjoin_unitsTensorPow_eq_diagonalActionImage (V := BridgeV N) ℂ n]
      exact Algebra.subset_adjoin ⟨g, rfl⟩
    exact h _ hmem
  · -- `M` commutes with every generator `g^{⊗n}`, hence with all of the adjoin.
    intro h y hy
    rw [← adjoin_unitsTensorPow_eq_diagonalActionImage (V := BridgeV N) ℂ n] at hy
    have hcomm : Commute M y :=
      Algebra.commute_of_mem_adjoin_of_forall_mem_commute hy (by
        rintro _ ⟨g, rfl⟩; exact (h g).symm)
    exact hcomm.symm

end Etingof
