import Mathlib

/-!
# Problem 5.24.2: the invariant ring and its multidegree grading (core definitions)

**Problem 5.24.2.** Let `R_{k,N}` be the algebra of polynomials on the space of `k`-tuples of
complex `N × N` matrices `X₁, …, X_k`, invariant under simultaneous conjugation. An example of an
element of `R_{k,N}` is the function `T_w := Tr(w(X₁, …, X_k))`, where `w` is any finite word on a
`k`-letter alphabet. Show that `R_{k,N}` is generated by the elements `T_w`.

This file collects the core setup shared by the coordinate side of the problem: the coordinate
ring `MatrixTupleRing`, the conjugation action, the invariant subalgebra, the trace-of-word
functions, and the `matrixWeight` multidegree grading together with the fact that conjugation
preserves it. The coordinate ↔ tensor correspondence (`Problem5_24_2_Bridge.lean`) and the final
First Fundamental Theorem (`Problem5_24_2.lean`) build on these definitions.

## Formalization

The coordinate ring of the space of `k`-tuples of `N × N` complex matrices is the polynomial ring
`MvPoly := MvPolynomial (Fin k × Fin N × Fin N) ℂ`, one variable `(i, r, c)` for the `(r, c)` entry
of the `i`-th matrix. The generic `i`-th matrix `Xmat i` has these variables as entries.

* **Simultaneous conjugation.** An invertible matrix `g ∈ GLₙ(ℂ)` acts by the `ℂ`-algebra
  automorphism `conjAlgHom g` substituting each `Xmat i` by `g · Xmat i · g⁻¹` (i.e. variable
  `(i, r, c) ↦ (g Xᵢ g⁻¹)_{r c}`).
* **The invariant ring `R_{k,N}`** is `invariantSubalgebra`: the subalgebra of polynomials fixed by
  `conjAlgHom g` for every `g`, realized as the infimum of the equalizers of `conjAlgHom g` and the
  identity.
* **Trace-of-word functions.** For a word `w : List (Fin k)`, `traceWord w := Tr(w(X₁, …, X_k))` is
  the trace of the matrix product `∏_{i ∈ w} Xmat i`.

The multidegree grading `matrixWeight` (variable `(i, r, c)` has weight `single i 1`) records the
degree `dᵢ` in each `Xᵢ`; conjugation preserves it, so each homogeneous component of an invariant is
again invariant.
-/

noncomputable section

namespace Etingof

open scoped Classical

variable (k N : ℕ)

/-- The coordinate ring of `k`-tuples of `N × N` complex matrices: one variable `(i, r, c)` per
matrix entry. -/
abbrev MatrixTupleRing : Type := MvPolynomial (Fin k × Fin N × Fin N) ℂ

/-- The generic `i`-th matrix `Xᵢ`, whose `(r, c)` entry is the variable `(i, r, c)`. -/
noncomputable def genericMatrix (i : Fin k) :
    Matrix (Fin N) (Fin N) (MatrixTupleRing k N) :=
  fun r c => MvPolynomial.X (i, r, c)

/-- Simultaneous conjugation by `g ∈ GLₙ(ℂ)` as a `ℂ`-algebra automorphism of the coordinate ring:
it substitutes each generic matrix `Xᵢ` by `g · Xᵢ · g⁻¹`. -/
noncomputable def conjAlgHom (g : (Matrix (Fin N) (Fin N) ℂ)ˣ) :
    MatrixTupleRing k N →ₐ[ℂ] MatrixTupleRing k N :=
  MvPolynomial.aeval fun v : Fin k × Fin N × Fin N =>
    (((↑g : Matrix (Fin N) (Fin N) ℂ).map (algebraMap ℂ (MatrixTupleRing k N)))
        * genericMatrix k N v.1
        * ((↑g⁻¹ : Matrix (Fin N) (Fin N) ℂ).map (algebraMap ℂ (MatrixTupleRing k N))))
      v.2.1 v.2.2

/-- The invariant ring `R_{k,N}`: polynomials fixed by simultaneous conjugation by every
`g ∈ GLₙ(ℂ)`, as the infimum of the equalizers of `conjAlgHom g` and the identity. -/
noncomputable def invariantSubalgebra : Subalgebra ℂ (MatrixTupleRing k N) :=
  ⨅ g : (Matrix (Fin N) (Fin N) ℂ)ˣ,
    AlgHom.equalizer (conjAlgHom k N g) (AlgHom.id ℂ (MatrixTupleRing k N))

/-- The trace-of-word function `T_w = Tr(w(X₁, …, X_k))`: the trace of the matrix product of the
generic matrices indexed by the letters of the word `w`. -/
noncomputable def traceWord (w : List (Fin k)) : MatrixTupleRing k N :=
  Matrix.trace ((w.map (genericMatrix k N)).prod)

/-- Telescoping of a conjugated product in a monoid: `∏ᵢ (a · fᵢ · a') = a · (∏ᵢ fᵢ) · a'`
whenever `a` and `a'` are two-sided inverses. Used to show that conjugating each generic matrix in
a word by `g` conjugates the whole word. -/
private lemma prod_map_conj {M : Type*} [Monoid M] (a a' : M) (haa' : a * a' = 1)
    (ha'a : a' * a = 1) {ι : Type*} (f : ι → M) :
    ∀ l : List ι, (l.map (fun i => a * f i * a')).prod = a * (l.map f).prod * a'
  | [] => by simp [haa']
  | i :: t => by
      simp only [List.map_cons, List.prod_cons, prod_map_conj a a' haa' ha'a f t]
      simp only [mul_assoc]
      rw [← mul_assoc a' a, ha'a, one_mul]

/-- **Elementary inclusion.** Each trace-of-word function `T_w` is invariant under simultaneous
conjugation. Applying `conjAlgHom g` conjugates each generic matrix by `G := g` (mapped into the
coordinate ring), hence conjugates the whole word `w(X₁,…,X_k)` by `G`; the trace of a conjugate
`G · P · G⁻¹` equals the trace of `P` by cyclic invariance. -/
theorem traceWord_mem_invariantSubalgebra (w : List (Fin k)) :
    traceWord k N w ∈ invariantSubalgebra k N := by
  rw [invariantSubalgebra, Algebra.mem_iInf]
  intro g
  rw [AlgHom.mem_equalizer, AlgHom.id_apply]
  set G : Matrix (Fin N) (Fin N) (MatrixTupleRing k N) :=
    (↑g : Matrix (Fin N) (Fin N) ℂ).map (algebraMap ℂ (MatrixTupleRing k N)) with hG
  set G' : Matrix (Fin N) (Fin N) (MatrixTupleRing k N) :=
    (↑g⁻¹ : Matrix (Fin N) (Fin N) ℂ).map (algebraMap ℂ (MatrixTupleRing k N)) with hG'
  have hGG' : G * G' = 1 := by
    rw [hG, hG', ← Matrix.map_mul, Units.mul_inv, Matrix.map_one _ (map_zero _) (map_one _)]
  have hG'G : G' * G = 1 := by
    rw [hG, hG', ← Matrix.map_mul, Units.inv_mul, Matrix.map_one _ (map_zero _) (map_one _)]
  -- Conjugation acts on each generic matrix by `Xᵢ ↦ G · Xᵢ · G⁻¹`.
  have hconj : ∀ i, (genericMatrix k N i).map (conjAlgHom k N g)
      = G * genericMatrix k N i * G' := by
    intro i
    refine Matrix.ext fun r c => ?_
    rw [Matrix.map_apply]
    change conjAlgHom k N g (MvPolynomial.X (i, r, c)) = _
    rw [conjAlgHom, MvPolynomial.aeval_X, ← hG, ← hG']
  -- Conjugating the whole word: `(conjAlgHom g).mapMatrix P = G · P · G⁻¹`.
  have key : (conjAlgHom k N g).mapMatrix ((w.map (genericMatrix k N)).prod)
      = G * (w.map (genericMatrix k N)).prod * G' := by
    rw [map_list_prod, List.map_map]
    have hcomp : ((conjAlgHom k N g).mapMatrix ∘ genericMatrix k N)
        = fun i => G * genericMatrix k N i * G' := by
      funext i; simp only [Function.comp_apply, AlgHom.mapMatrix_apply]; exact hconj i
    rw [hcomp]
    exact prod_map_conj G G' hGG' hG'G (genericMatrix k N) w
  rw [traceWord, AddMonoidHom.map_trace (conjAlgHom k N g), ← AlgHom.mapMatrix_apply, key,
    Matrix.trace_mul_comm, ← mul_assoc, hG'G, one_mul]

open MvPolynomial

/-- **Multidegree weight.** The entry variable `(i, r, c)` of the `i`-th generic matrix is given
weight `single i 1`. A polynomial is `matrixWeight`-homogeneous of weight `d : Fin k →₀ ℕ` exactly
when it is multihomogeneous of degree `d i` in the entries of `Xᵢ` for every `i`, the grading the
book's hint uses ("invariant functions of degree `dᵢ` in each `Xᵢ`"). -/
def matrixWeight : Fin k × Fin N × Fin N → (Fin k →₀ ℕ) := fun v => Finsupp.single v.1 1

/-- Conjugation substitutes the entry variable `(i, r, c)` by an entry of `G · Xᵢ · G⁻¹`, a
`ℂ`-linear combination of the entries of `Xᵢ`; hence `conjAlgHom g (X v)` is `matrixWeight`
homogeneous of the same weight `single i 1` as `X v`. -/
theorem conjAlgHom_X_isWeightedHomogeneous (g : (Matrix (Fin N) (Fin N) ℂ)ˣ)
    (v : Fin k × Fin N × Fin N) :
    IsWeightedHomogeneous (matrixWeight k N) (conjAlgHom k N g (X v)) (matrixWeight k N v) := by
  obtain ⟨i, r, c⟩ := v
  -- A single conjugated entry `C α · X (i,a,b) · C β` is weight-`single i 1` homogeneous.
  have hCXC : ∀ (α β : ℂ) (a b : Fin N),
      IsWeightedHomogeneous (matrixWeight k N)
        (C α * X ((i, a, b) : Fin k × Fin N × Fin N) * C β) (Finsupp.single i 1) := by
    intro α β a b
    have hcxc : C α * X ((i, a, b) : Fin k × Fin N × Fin N) * C β
        = C (α * β) * X ((i, a, b) : Fin k × Fin N × Fin N) := by
      rw [mul_right_comm, ← map_mul]
    rw [hcxc]
    have hX : IsWeightedHomogeneous (matrixWeight k N)
        (X ((i, a, b) : Fin k × Fin N × Fin N) : MatrixTupleRing k N) (Finsupp.single i 1) :=
      isWeightedHomogeneous_X (R := ℂ) (matrixWeight k N) (i, a, b)
    exact hX.C_mul _
  -- Expand `conjAlgHom g (X (i,r,c))` as the matrix entry `(G · Xᵢ · G⁻¹) r c`, a double sum.
  simp only [conjAlgHom, MvPolynomial.aeval_X]
  rw [Matrix.mul_apply]
  apply IsWeightedHomogeneous.sum
  intro b _
  rw [Matrix.mul_apply, Finset.sum_mul]
  apply IsWeightedHomogeneous.sum
  intro a _
  simp only [Matrix.map_apply, MvPolynomial.algebraMap_eq, genericMatrix]
  exact hCXC ((↑g : Matrix (Fin N) (Fin N) ℂ) r a) ((↑g⁻¹ : Matrix (Fin N) (Fin N) ℂ) b c) a b

/-- Conjugation sends the monomial `X^u` to a `matrixWeight`-homogeneous polynomial of weight
`weight u`: each variable `X v` maps to a weight-`matrixWeight v` homogeneous element, and taking
products/powers adds the weights. -/
theorem conjAlgHom_monomial_isWeightedHomogeneous (g : (Matrix (Fin N) (Fin N) ℂ)ˣ)
    (u : (Fin k × Fin N × Fin N) →₀ ℕ) (a : ℂ) :
    IsWeightedHomogeneous (matrixWeight k N) (conjAlgHom k N g (monomial u a))
      (Finsupp.weight (matrixWeight k N) u) := by
  have hbase : ∀ v, IsWeightedHomogeneous (matrixWeight k N)
      (conjAlgHom k N g (X v)) (matrixWeight k N v) :=
    conjAlgHom_X_isWeightedHomogeneous k N g
  rw [monomial_eq, map_mul, ← MvPolynomial.algebraMap_eq, AlgHom.commutes,
    MvPolynomial.algebraMap_eq]
  apply IsWeightedHomogeneous.C_mul
  simp only [Finsupp.prod, map_prod, map_pow]
  rw [show Finsupp.weight (matrixWeight k N) u
      = ∑ n ∈ u.support, (u n) • (matrixWeight k N n) by rw [Finsupp.weight_apply]; rfl]
  exact IsWeightedHomogeneous.prod u.support
    (fun n => (conjAlgHom k N g (X n)) ^ (u n)) (fun n => (u n) • matrixWeight k N n)
    (fun n _ => (hbase n).pow (u n))

/-- Conjugation commutes with taking `matrixWeight`-homogeneous components: since `conjAlgHom g`
maps each weight-`d` homogeneous piece into the weight-`d` piece, it commutes with the projection
`weightedHomogeneousComponent d`. -/
theorem conjAlgHom_weightedHomogeneousComponent (g : (Matrix (Fin N) (Fin N) ℂ)ˣ)
    (d : Fin k →₀ ℕ) (p : MatrixTupleRing k N) :
    weightedHomogeneousComponent (matrixWeight k N) d (conjAlgHom k N g p)
      = conjAlgHom k N g (weightedHomogeneousComponent (matrixWeight k N) d p) := by
  induction p using MvPolynomial.induction_on' with
  | monomial u a =>
    have hm : IsWeightedHomogeneous (matrixWeight k N) (monomial u a)
        (Finsupp.weight (matrixWeight k N) u) :=
      isWeightedHomogeneous_monomial _ _ _ rfl
    have hcm : IsWeightedHomogeneous (matrixWeight k N) (conjAlgHom k N g (monomial u a))
        (Finsupp.weight (matrixWeight k N) u) :=
      conjAlgHom_monomial_isWeightedHomogeneous k N g u a
    by_cases hd : d = Finsupp.weight (matrixWeight k N) u
    · subst hd
      rw [hcm.weightedHomogeneousComponent_same, hm.weightedHomogeneousComponent_same]
    · rw [hcm.weightedHomogeneousComponent_ne d hd, hm.weightedHomogeneousComponent_ne d hd,
        map_zero]
  | add p q hp hq =>
    simp only [map_add, hp, hq]

/-- Each `matrixWeight`-homogeneous component of a conjugation-invariant polynomial is itself
conjugation-invariant. -/
theorem weightedHomogeneousComponent_mem_invariantSubalgebra (d : Fin k →₀ ℕ)
    {f : MatrixTupleRing k N} (hf : f ∈ invariantSubalgebra k N) :
    weightedHomogeneousComponent (matrixWeight k N) d f ∈ invariantSubalgebra k N := by
  rw [invariantSubalgebra, Algebra.mem_iInf] at hf ⊢
  intro g
  rw [AlgHom.mem_equalizer, AlgHom.id_apply]
  have hg : conjAlgHom k N g f = f := by
    have := hf g; rwa [AlgHom.mem_equalizer, AlgHom.id_apply] at this
  rw [← conjAlgHom_weightedHomogeneousComponent k N g d f, hg]

end Etingof
