import Mathlib
import EtingofRepresentationTheory.Chapter5.Example5_1_3

/-!
# Every irreducible representation of `Sₙ` is of real type

This file records the `n`-generic statement behind the reality argument of Problem 5.12.5:
every simple `ℂ[Sₙ]`-module is of real type, and consequently has Frobenius-Schur indicator `1`.

The real-type statement is the `n`-generic version of `Etingof.Example5_1_3_S4`
(`Example5_1_3.lean`): every simple `ℂ[Sₙ]`-module is isomorphic to a Specht module
`V_λ = ℂ[Sₙ]·c_λ` (`Theorem5_12_2_classification`), generated by the integer-coefficient
Young symmetrizer `c_λ`; transporting the coordinate dot-product form
(`isRealType_of_coordForm_transport`) along this iso gives a nondegenerate invariant
symmetric form.

Combined with the reverse Frobenius-Schur implication
`Etingof.frobeniusSchurIndicator_eq_one_of_isRealType` (`FrobeniusSchurRealType.lean`), this gives
`FS(V) = 1` for every simple representation, which is the input Problem 5.12.5 needs to reduce
Theorem 5.1.5's `∑ dim Vᵢ · FS(Vᵢ)` to the bare `∑ dim Vᵢ = #{g : g² = 1}`.
-/

open MonoidAlgebra

namespace Etingof

/-- **Every simple `ℂ[Sₙ]`-module is of real type.** The `n`-generic version of
`Etingof.Example5_1_3_S4`: every simple `ℂ[Sₙ]`-module is isomorphic to a Specht module
`V_λ = ℂ[Sₙ]·c_λ`, and transporting the coordinate dot-product form along this iso gives a
nondegenerate invariant symmetric form (the Young symmetrizer `c_λ` has integer, hence real,
coefficients). -/
theorem isRealType_of_isSimpleModule_symmetricGroup (n : ℕ)
    {V : Type*} [AddCommGroup V] [Module ℂ V] [Module.Finite ℂ V]
    (ρ : Representation ℂ (Equiv.Perm (Fin n)) V)
    (hρ : IsSimpleModule (MonoidAlgebra ℂ (Equiv.Perm (Fin n))) ρ.asModule) :
    Etingof.IsRealType ρ := by
  classical
  haveI := hρ
  -- Embed `ρ.asModule` as a left ideal `I ⊆ ℂ[Sₙ]`, then classify `I` as a Specht module.
  obtain ⟨I, ⟨φ_M⟩⟩ :=
    IsSemisimpleRing.exists_linearEquiv_ideal_of_isSimpleModule
      (MonoidAlgebra ℂ (Equiv.Perm (Fin n))) ρ.asModule
  haveI : IsSimpleModule (MonoidAlgebra ℂ (Equiv.Perm (Fin n))) I :=
    IsSimpleModule.congr φ_M.symm
  obtain ⟨la, ⟨φ_I⟩⟩ := Etingof.Theorem5_12_2_classification n I
  -- `Ψ : ρ.asModule ≃ₗ[ℂ[Sₙ]] V_λ`.
  set Ψ := φ_M.trans φ_I with hΨ
  set c := Etingof.YoungSymmetrizer n la with hc
  have hc_mem : c ∈ Etingof.SpechtModule n la := Submodule.subset_span rfl
  -- The intertwiner `ψ : V → ℂ[Sₙ]`, `v ↦ ↑(Ψ (asModuleEquiv⁻¹ v))`.
  set ψ : V →ₗ[ℂ] MonoidAlgebra ℂ (Equiv.Perm (Fin n)) :=
    ((Etingof.SpechtModule n la).subtype.restrictScalars ℂ).comp
      ((Ψ.restrictScalars ℂ).toLinearMap.comp ρ.asModuleEquiv.symm.toLinearMap) with hψdef
  have hψ_apply : ∀ v : V,
      ψ v = (Ψ (ρ.asModuleEquiv.symm v) : MonoidAlgebra ℂ (Equiv.Perm (Fin n))) := by
    intro v; rfl
  -- `ψ` intertwines the `ρ`-action with left multiplication.
  have hψ : ∀ (g : Equiv.Perm (Fin n)) (v : V),
      ψ (ρ g v) = MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g * ψ v := by
    intro g v
    rw [hψ_apply, hψ_apply, ρ.asModuleEquiv_symm_map_rho, map_smul]
    simp only [Submodule.coe_smul, smul_eq_mul]
  -- `c` is real and nonzero, and lies in the image of `ψ`.
  have hcne : c ≠ 0 := by
    intro h0
    rw [hc] at h0
    exact Etingof.young_symmetrizer_sq_ne_zero n la (by rw [h0, mul_zero])
  set v₀ : V := ρ.asModuleEquiv (Ψ.symm ⟨c, hc_mem⟩) with hv₀def
  have hv₀ : ψ v₀ = c := by
    rw [hψ_apply, hv₀def, LinearEquiv.symm_apply_apply, LinearEquiv.apply_symm_apply]
  exact isRealType_of_coordForm_transport ρ hρ ψ hψ c
    (Etingof.youngSymmetrizer_im_eq_zero n la) v₀ hv₀ hcne

/-- **Every simple `ℂ[Sₙ]`-module has Frobenius-Schur indicator `1`.** Immediate from real
type (`isRealType_of_isSimpleModule_symmetricGroup`) and the reverse Frobenius-Schur implication
`frobeniusSchurIndicator_eq_one_of_isRealType`. -/
theorem frobeniusSchurIndicator_symmetricGroup_eq_one (n : ℕ)
    {V : Type*} [AddCommGroup V] [Module ℂ V] [Module.Finite ℂ V]
    (ρ : Representation ℂ (Equiv.Perm (Fin n)) V)
    (hρ : IsSimpleModule (MonoidAlgebra ℂ (Equiv.Perm (Fin n))) ρ.asModule) :
    Etingof.frobeniusSchurIndicator ρ = 1 :=
  Etingof.frobeniusSchurIndicator_eq_one_of_isRealType ρ hρ
    (isRealType_of_isSimpleModule_symmetricGroup n ρ hρ)

end Etingof
