import Mathlib
import EtingofRepresentationTheory.Chapter5.Theorem5_23_2Core
import EtingofRepresentationTheory.Chapter5.Proposition5_22_2
import EtingofRepresentationTheory.Chapter5.AlgIrrepGLRep
import EtingofRepresentationTheory.Chapter5.AlgIrrepGLNonIso
import EtingofRepresentationTheory.Chapter5.RepresentationAsModuleHom

-- These mirror the lakefile's project-wide `[leanOptions]` so the module also type-checks under a
-- bare `lake env lean`, which does not read the lakefile options. `maxSynthPendingDepth 3` clears
-- the deep Schur-module instance chains; `backward.isDefEq.respectTransparency false` restores the
-- full-transparency `isDefEq` the `charTwistRep`/Schur carrier identifications rely on.
set_option maxSynthPendingDepth 3
set_option backward.isDefEq.respectTransparency false

/-!
# Remark 5.23.3: Extension of the GL(V) theory to 𝔰𝔩(V) and SL(V)

Etingof's Remark 5.23.3 observes that, since `𝔰𝔩(V)` (traceless operators) is the quotient of
`𝔤𝔩(V)` by scalars and `SL(V)` is the subgroup of determinant-`1` operators, the classification of
algebraic representations of `GL(V)` (Theorem 5.23.2) carries over to `𝔰𝔩(V)` / `SL(V)`. The one
change is that the determinant character becomes trivial: on `SL(V)` the representation `L_λ` and
its determinant twist `L_{λ + 1ᴺ}` coincide, so the irreducibles are parametrized by dominant
weights `λ₁ ≥ ⋯ ≥ λ_N` only up to a simultaneous shift by a constant. Etingof also states,
without proof ("we will not do this here"), that every finite-dimensional `𝔰𝔩(V)`-representation is
completely reducible and every irreducible is an `L_λ`. For `dim V = 2` this recovers the
representation theory of `𝔰𝔩(2)` from Problem 2.15.1.

## What is formalized here

**Weights.** The parametrization up to a simultaneous constant shift is made precise on
`Etingof.DominantWeight`:

* `Etingof.DominantWeight.constShift lam c`: the simultaneous shift `λ ↦ λ + c·1ᴺ` (adding the
  same integer `c` to every entry). This is the weight-side of tensoring `L_λ` with `det^c`.
* `Etingof.DominantWeight.shiftSetoid`: the equivalence relation "differ by a simultaneous constant
  shift", together with `Etingof.SLWeightParam n := Quotient (shiftSetoid n)`, the type that
  parametrizes the irreducible `SL_N`-representations. This is exactly Etingof's "`λ₁ ≥ ⋯ ≥ λ_N` up
  to a simultaneous shift by a constant".

**The `SL_N`-action and the isomorphism `L_λ ≅ L_{λ + c·1ᴺ}`.**

* `Etingof.slRestrict ρ`: the restriction of a `GL_N(k)`-representation to `SL_N(k)` along
  `Matrix.SpecialLinearGroup.toGL`. Applied to `Etingof.algIrrepGLRepρ` this is the bundled
  `SL_N`-action on `L_λ`.
* `Etingof.slRestrict_charTwistRep_detChar_zpow`: any power of the determinant character becomes
  trivial after restriction, so `det`-twists are invisible on `SL_N`. This is the one input that
  makes the whole `GL_N` theory descend.
* `Etingof.algIrrepGL_slEquiv_constShift`: the `SL_N`-equivariant isomorphism
  `L_{λ + c·1ᴺ}|_{SL_N} ≅ L_λ|_{SL_N}` as a `Representation.Equiv`, obtained by restricting the
  `GL_N`-level determinant-twist isomorphism of Proposition 5.22.2 and observing that the twist
  disappears. `Etingof.algIrrepGL_finrank_constShift` is its dimension shadow.

**The parametrization by `SLWeightParam N`.**

* `Etingof.slIsoSetoid n k`: the relation "the `SL_N`-restrictions of `L_λ` and `L_μ` are
  isomorphic" on dominant weights, an equivalence relation because `Representation.Equiv` has
  `refl`/`symm`/`trans`.
* `Etingof.slIrrepClass`: the induced map `SLWeightParam n → Quotient (slIsoSetoid n k)`. It is
  well defined by `Etingof.shiftEquiv_slIso` (shift-equivalent weights give isomorphic `SL_N`
  representations) and surjective by `Etingof.slIrrepClass_surjective`.
* `Etingof.slIso_shiftEquiv`: the converse of `shiftEquiv_slIso` — isomorphic `SL_N`-restrictions
  force the weights to differ by a constant shift — hence `Etingof.slIrrepClass_injective` and the
  bijection `Etingof.slIrrepEquiv : SLWeightParam n ≃ Quotient (slIsoSetoid n k)`. This is
  Etingof's "parametrized by `λ₁ ≥ ⋯ ≥ λ_N` up to a simultaneous shift by a constant" in full.
  The route back from `SL_N` to `GL_N` is the scalar torus: `Etingof.scalarGL` acts on `L_λ` by
  `s^{|λ|}` (`Etingof.algIrrepGLRepρ_scalarGL`, with `|λ| = Etingof.DominantWeight.total`), the
  scalars inside `SL_N` are the `N`-th roots of unity and pin the shift down to
  `c = (|μ| - |λ|)/N` (`Etingof.natCast_dvd_total_sub_of_slIso`), and `GL_N(k)` is generated by
  its scalars together with `SL_N(k)` (`Etingof.specialLinearFactor`), so once the total weights
  agree the `SL_N`-map is already `GL_N`-equivariant and
  `Etingof.algIrrepGLRepρ_iso_iff_eq` applies.

  The `GL_N` highest-weight classification is now available in `AlgIrrepGLExhaustive.lean`.
  `SLIrrepExhaustive.lean` proves that every intrinsically algebraic simple `SL_N`
  representation has an algebraic `GL_N` extension and is therefore isomorphic to one of the
  constructed restrictions.

**What is intentionally omitted.** Etingof states, and explicitly declines to prove ("we will not
do this here"), that every finite-dimensional `𝔰𝔩(V)`-representation is completely reducible and
every irreducible one is an `L_λ`. Following the project's omission policy, this file carries no
declaration for those assertions; the decision is recorded in `skipped-exercises.md` under
"Remark 5.23.3". The `𝔰𝔩(2)` case that the remark points at is proved independently as
`Etingof.Sl2Irrep.complete_reducibility` (Problem 2.15.1).
-/

open Etingof.KernelLemmaKPrime

namespace Etingof

namespace DominantWeight

variable {n : ℕ}

/-- **Simultaneous constant shift** `λ ↦ λ + c·1ᴺ`: add the same integer `c` to every entry of a
dominant weight. This is the effect on highest weights of tensoring `L_λ` with the `c`-th power of
the determinant character `det^c`. Adding a constant preserves the weakly-decreasing (antitone)
condition, so the result is again a dominant weight. -/
def constShift (lam : DominantWeight n) (c : ℤ) : DominantWeight n :=
  ⟨fun i => lam.val i + c, fun _ _ h => by dsimp only; have := lam.property h; omega⟩

@[simp] lemma constShift_val (lam : DominantWeight n) (c : ℤ) (i : Fin n) :
    (lam.constShift c).val i = lam.val i + c := rfl

@[simp] lemma constShift_zero (lam : DominantWeight n) : lam.constShift 0 = lam := by
  apply Subtype.ext; funext i; simp

lemma constShift_constShift (lam : DominantWeight n) (c d : ℤ) :
    (lam.constShift c).constShift d = lam.constShift (c + d) := by
  apply Subtype.ext; funext i; simp [add_assoc]

/-- **The total weight** `|λ| = λ₁ + ⋯ + λ_N`. This is the character by which the scalar matrices
act: `s·1ᴺ` acts on `L_λ` by `s^{|λ|}` (`Etingof.algIrrepGLRepρ_scalarGL`). It is the only part of
`λ` that a constant shift moves, and it moves by `N·c`. -/
def total (lam : DominantWeight n) : ℤ := ∑ i, lam.val i

@[simp] lemma total_constShift (lam : DominantWeight n) (c : ℤ) :
    (lam.constShift c).total = lam.total + n * c := by
  simp only [total, constShift_val, Finset.sum_add_distrib, Finset.sum_const,
    Finset.card_univ, Fintype.card_fin, nsmul_eq_mul]

/-- Two dominant weights are shift-equivalent when they differ by a simultaneous constant shift,
i.e. `μ = λ + c·1ᴺ` for some `c : ℤ`. On `SL(V)` this is exactly the relation that identifies
`L_λ` with its determinant twists, so shift-equivalence classes index the irreducibles of `SL_N`. -/
def ShiftEquiv (lam mu : DominantWeight n) : Prop := ∃ c : ℤ, mu = lam.constShift c

/-- Shift-equivalence is an equivalence relation on dominant weights. -/
def shiftSetoid (n : ℕ) : Setoid (DominantWeight n) where
  r := ShiftEquiv
  iseqv :=
    { refl := fun lam => ⟨0, (lam.constShift_zero).symm⟩
      symm := fun {lam mu} ⟨c, hc⟩ => ⟨-c, by
        apply Subtype.ext; funext i; subst hc; simp⟩
      trans := fun {lam mu nu} ⟨c, hc⟩ ⟨d, hd⟩ => ⟨c + d, by
        subst hc; subst hd; rw [constShift_constShift]⟩ }

@[simp] lemma shiftSetoid_r (lam mu : DominantWeight n) :
    (shiftSetoid n).r lam mu ↔ ∃ c : ℤ, mu = lam.constShift c := Iff.rfl

end DominantWeight

/-- **The parameter set for the irreducible representations of `SL_N`.** By Remark 5.23.3 the
irreducibles of `SL(V)` are the images of the `GL(V)`-irreducibles `L_λ`, with `L_λ` and
`L_{λ + c·1ᴺ}` identified; equivalently they are parametrized by dominant weights
`λ₁ ≥ ⋯ ≥ λ_N` up to a simultaneous constant shift. -/
abbrev SLWeightParam (n : ℕ) := Quotient (DominantWeight.shiftSetoid n)

/-- **Determinant is trivial on `SL_N`**, the source of the `SL(V)` identification. For an element
`g` of the special linear group, the determinant of the underlying matrix is `1`; hence the
determinant character `det^c` acts trivially and `L_λ ≅ L_{λ + c·1ᴺ}` as `SL_N`-representations. -/
lemma specialLinear_det_eq_one {n : ℕ} {k : Type*} [CommRing k]
    (g : Matrix.SpecialLinearGroup (Fin n) k) :
    (g : Matrix (Fin n) (Fin n) k).det = 1 :=
  g.property

/-- The non-negative weight `λ.toNatWeight` recovers `λ` up to its shift:
`(λ.toNatWeight i : ℤ) = λ_i + shift`. The shift is chosen (as the negative of the minimal
entry) so that `λ_i + shift ≥ 0`, hence the `Int.toNat` in `toNatWeight` is exact. -/
private lemma toNatWeight_cast {n : ℕ} (lam : DominantWeight n) (i : Fin n) :
    (lam.toNatWeight i : ℤ) = lam.val i + (lam.shift : ℤ) := by
  have hnonneg : (0 : ℤ) ≤ lam.val i + (lam.shift : ℤ) := by
    obtain ⟨m, rfl⟩ : ∃ m, n = m + 1 := ⟨n - 1, (Nat.succ_pred_eq_of_pos (Fin.pos i)).symm⟩
    have hlast : lam.val (Fin.last m) ≤ lam.val i := lam.property (Fin.le_last i)
    change (0 : ℤ) ≤ lam.val i + (((-(lam.val (Fin.last m))).toNat : ℕ) : ℤ)
    omega
  change (((lam.val i + (lam.shift : ℤ)).toNat : ℕ) : ℤ) = lam.val i + (lam.shift : ℤ)
  rw [Int.toNat_of_nonneg hnonneg]

/-- `λ.toNatWeight` is antitone: shifting an antitone integer weight by a constant and clamping
at `0` (which never triggers, by `toNatWeight_cast`'s nonnegativity) preserves the order. -/
private lemma toNatWeight_antitone {n : ℕ} (lam : DominantWeight n) :
    Antitone lam.toNatWeight := by
  intro i j hij
  simp only [DominantWeight.toNatWeight]
  exact Int.toNat_le_toNat (by have := lam.property hij; omega)

/-- **Single `+1` step (dimension shadow of Proposition 5.22.2).** For an antitone `ℕ`-weight `μ`,
tensoring the Schur module `L_μ` by the one-dimensional determinant character gives `L_{μ + 1ᴺ}`
without changing the underlying vector space, so the two Schur modules have equal dimension. This
is the dimension consequence of `schurModule_shift_iso_detTwist`. -/
private lemma finrank_schurModuleSubmodule_succ {N : ℕ} {k : Type} [Field k] [IsAlgClosed k]
    [CharZero k] (μ : Fin N → ℕ) (hμ : Antitone μ) :
    Module.finrank k (SchurModuleSubmodule k N (fun i => μ i + 1))
      = Module.finrank k (SchurModuleSubmodule k N μ) := by
  obtain ⟨e⟩ := schurModule_shift_iso_detTwist k N μ hμ
  exact (FDRep.isoToLinearEquiv e).finrank_eq

/-- **Constant `+m` shift preserves the Schur-module dimension.** Iterating the single-step
`+1` identity (`finrank_schurModuleSubmodule_succ`): for an antitone `ℕ`-weight `μ` and any
`m : ℕ`, `dim L_{μ + m·1ᴺ} = dim L_μ`. -/
private lemma finrank_schurModuleSubmodule_add_const {N : ℕ} {k : Type} [Field k] [IsAlgClosed k]
    [CharZero k] (μ : Fin N → ℕ) (hμ : Antitone μ) (m : ℕ) :
    Module.finrank k (SchurModuleSubmodule k N (fun i => μ i + m))
      = Module.finrank k (SchurModuleSubmodule k N μ) := by
  induction m with
  | zero => simp
  | succ m ih =>
    have key : Module.finrank k (SchurModuleSubmodule k N (fun i => μ i + (m + 1)))
        = Module.finrank k (SchurModuleSubmodule k N (fun i => μ i + m)) := by
      have hidx : (fun i => μ i + (m + 1)) = (fun i => (μ i + m) + 1) := by
        funext i; omega
      rw [hidx]
      exact finrank_schurModuleSubmodule_succ (fun j => μ j + m)
        (fun a b h => Nat.add_le_add_right (hμ h) m)
    rw [key, ih]

/-- **Dimension-level statement of `L_λ ≅ L_{λ + c·1ᴺ}` (Remark 5.23.3).** Tensoring `L_λ` with the
`c`-th power of the one-dimensional determinant character does not change the underlying dimension,
so `dim L_λ = dim L_{λ + c·1ᴺ}`. On `SL(V)` (where `det = 1`, `specialLinear_det_eq_one`) this
common dimension reflects an isomorphism of `SL_N`-representations; capturing that
isomorphism `SL_N`-equivariantly would require an `SL_N`-action on `AlgIrrepGL`, which this
development does not build, so only the dimension identity is stated here.

The two `AlgIrrepGL` carriers are `SchurModuleSubmodule k n (·).toNatWeight` at the two dominant
weights; `constShift c` adds the same integer `c` to every entry, so the two `ℕ`-valued weights
`(lam.constShift c).toNatWeight` and `lam.toNatWeight` differ by a single constant `Δ` (whichever
is pointwise larger equals the other plus `|Δ|`). The identity then follows from
`finrank_schurModuleSubmodule_add_const`. As with the rest of the Schur–Weyl / character theory in
this chapter, this lives over an algebraically closed field of characteristic zero.
(Etingof Remark 5.23.3) -/
theorem algIrrepGL_finrank_constShift
    {n : ℕ} {k : Type} [Field k] [IsAlgClosed k] [CharZero k]
    (lam : DominantWeight n) (c : ℤ) :
    Module.finrank k (AlgIrrepGL n (lam.constShift c) k)
      = Module.finrank k (AlgIrrepGL n lam k) := by
  change Module.finrank k (SchurModuleSubmodule k n (lam.constShift c).toNatWeight)
    = Module.finrank k (SchurModuleSubmodule k n lam.toNatWeight)
  have ha_anti : Antitone lam.toNatWeight := toNatWeight_antitone lam
  have hb_anti : Antitone (lam.constShift c).toNatWeight := toNatWeight_antitone (lam.constShift c)
  set Δ : ℤ := c + ((lam.constShift c).shift : ℤ) - (lam.shift : ℤ) with hΔdef
  have hrel : ∀ i, ((lam.constShift c).toNatWeight i : ℤ) = (lam.toNatWeight i : ℤ) + Δ := by
    intro i
    rw [toNatWeight_cast (lam.constShift c) i, toNatWeight_cast lam i,
      DominantWeight.constShift_val, hΔdef]
    ring
  rcases le_total 0 Δ with hΔ | hΔ
  · have hbrw : (lam.constShift c).toNatWeight = (fun i => lam.toNatWeight i + Δ.toNat) := by
      funext i; have := hrel i; omega
    rw [hbrw]
    exact finrank_schurModuleSubmodule_add_const lam.toNatWeight ha_anti Δ.toNat
  · have harw : lam.toNatWeight = (fun i => (lam.constShift c).toNatWeight i + (-Δ).toNat) := by
      funext i; have := hrel i; omega
    rw [harw]
    exact (finrank_schurModuleSubmodule_add_const (lam.constShift c).toNatWeight hb_anti
      (-Δ).toNat).symm

/-! ## Restriction of `GL_N`-representations to `SL_N`

Etingof's remark is about restricting the `GL(V)`-theory along `SL(V) ⊆ GL(V)`. We build that
restriction and record the one fact that drives the whole descent: the determinant character, and
hence every power of it, becomes trivial on `SL_N`. -/

section SLRestriction

variable {n : ℕ} {k : Type*} [CommRing k] {V : Type*} [AddCommMonoid V] [Module k V]

/-- **Restriction of a `GL_N(k)`-representation to `SL_N(k)`**, along Mathlib's embedding
`Matrix.SpecialLinearGroup.toGL` of the determinant-one matrices into the general linear group.
This is the bundled `SL_N`-action that Remark 5.23.3 is about. -/
def slRestrict (ρ : Representation k (Matrix.GeneralLinearGroup (Fin n) k) V) :
    Representation k (Matrix.SpecialLinearGroup (Fin n) k) V :=
  MonoidHom.comp ρ Matrix.SpecialLinearGroup.toGL

@[simp] lemma slRestrict_apply (ρ : Representation k (Matrix.GeneralLinearGroup (Fin n) k) V)
    (g : Matrix.SpecialLinearGroup (Fin n) k) (v : V) :
    slRestrict ρ g v = ρ (Matrix.SpecialLinearGroup.toGL g) v := rfl

/-- **The determinant character is trivial on `SL_N`.** This is the single input that makes the
`GL(V)`-theory descend to `SL(V)`: the determinant twists that separate `L_λ` from `L_{λ + c·1ᴺ}`
become invisible after restriction. -/
@[simp] lemma detChar_toGL (g : Matrix.SpecialLinearGroup (Fin n) k) :
    detChar k n (Matrix.SpecialLinearGroup.toGL g) = 1 :=
  Units.ext (by simp [detChar, Matrix.GeneralLinearGroup.det])

/-- Twisting by any integer power of the determinant character leaves the restriction to `SL_N`
unchanged: `(det^c · ρ)|_{SL_N} = ρ|_{SL_N}`. -/
lemma slRestrict_charTwistRep_detChar_zpow (c : ℤ)
    (ρ : Representation k (Matrix.GeneralLinearGroup (Fin n) k) V) :
    slRestrict (charTwistRep (detChar k n ^ c) ρ) = slRestrict ρ := by
  ext g v
  simp [MonoidHom.zpow_apply]

end SLRestriction

/-- Transport a categorical isomorphism `FDRep.of ρ ≅ FDRep.of σ` to an isomorphism of the
underlying representations. The underlying linear equivalence is `FDRep.isoToLinearEquiv`, and its
intertwining property is `FDRep.Iso.conj_ρ`, which says exactly that conjugating `ρ g` by it gives
`σ g`. -/
noncomputable def fdRepIsoToEquiv {K : Type} [Field K] {G : Type*} [Monoid G]
    {V W : Type} [AddCommGroup V] [Module K V] [Module.Finite K V]
    [AddCommGroup W] [Module K W] [Module.Finite K W]
    (ρ : Representation K G V) (σ : Representation K G W)
    (α : FDRep.of ρ ≅ FDRep.of σ) : Representation.Equiv ρ σ :=
  Representation.Equiv.mk (FDRep.isoToLinearEquiv α) fun g => by
    have h := FDRep.Iso.conj_ρ α g
    rw [FDRep.of_ρ', FDRep.of_ρ'] at h
    rw [h, LinearEquiv.conj_apply]
    refine LinearMap.ext fun v => ?_
    simp

/-- Restrict an isomorphism of `GL_N`-representations to an isomorphism of their `SL_N`
restrictions. -/
def slRestrictEquiv {n : ℕ} {k : Type*} [CommRing k] {V W : Type*}
    [AddCommMonoid V] [Module k V] [AddCommMonoid W] [Module k W]
    {ρ : Representation k (Matrix.GeneralLinearGroup (Fin n) k) V}
    {σ : Representation k (Matrix.GeneralLinearGroup (Fin n) k) W}
    (E : Representation.Equiv ρ σ) :
    Representation.Equiv (slRestrict ρ) (slRestrict σ) :=
  Representation.Equiv.mk E.toLinearEquiv fun g =>
    E.isIntertwining' (Matrix.SpecialLinearGroup.toGL g)

/-! ## The `SL_N`-equivariant isomorphism `L_λ ≅ L_{λ + c·1ᴺ}`

The `GL_N`-level input is Proposition 5.22.2 in the form
`schurModule_shift_iso_detTwist : L_{μ+1ᴺ} ≅ L_μ ⊗ det`. Restriction to `SL_N` makes the `det`
factor trivial, so `L_{μ+1ᴺ}|_{SL_N} ≅ L_μ|_{SL_N}`; iterating gives the constant shift. The
`det^{-shift}` normalization built into `algIrrepGLRepρ` is invisible for the same reason, which
extends the statement from non-negative to integer weights. -/

section SLEquiv

variable {k : Type} [Field k] [IsAlgClosed k] [CharZero k]

omit [IsAlgClosed k] [CharZero k] in
/-- The determinant twist of Proposition 5.22.2 is the character twist by `detChar`. -/
lemma detTwistedSchurModuleRep_eq_charTwistRep (N : ℕ) (lam : Fin N → ℕ) :
    detTwistedSchurModuleRep k N lam = charTwistRep (detChar k N) (schurModuleRep k N lam) := rfl

omit [IsAlgClosed k] [CharZero k] in
/-- The determinant-twisted Schur module and the Schur module have the same `SL_N`-restriction:
the twisting scalar `det g` is `1` on `SL_N`. -/
lemma slRestrict_detTwistedSchurModuleRep (N : ℕ) (lam : Fin N → ℕ) :
    slRestrict (detTwistedSchurModuleRep k N lam) = slRestrict (schurModuleRep k N lam) := by
  rw [detTwistedSchurModuleRep_eq_charTwistRep, ← zpow_one (detChar k N)]
  exact slRestrict_charTwistRep_detChar_zpow 1 _

/-- **One shift step, `SL_N`-equivariantly.** Restricting Proposition 5.22.2's determinant-twist
isomorphism `L_{μ+1ᴺ} ≅ L_μ ⊗ det` to `SL_N`, where the `det` factor is trivial. -/
theorem schurModule_slEquiv_succ (N : ℕ) (lam : Fin N → ℕ) (hlam : Antitone lam) :
    Nonempty (Representation.Equiv (slRestrict (schurModuleRep k N (fun i => lam i + 1)))
      (slRestrict (schurModuleRep k N lam))) := by
  obtain ⟨e⟩ := schurModule_shift_iso_detTwist k N lam hlam
  refine ⟨?_⟩
  have E := slRestrictEquiv (fdRepIsoToEquiv _ _ e)
  rwa [slRestrict_detTwistedSchurModuleRep N lam] at E

omit [IsAlgClosed k] [CharZero k] in
/-- Transporting along an equality of `ℕ`-weights. Stated separately because rewriting the weight
inside `slRestrict (schurModuleRep k N ·)` also rewrites the carrier type. -/
theorem schurModule_slEquiv_congr (N : ℕ) {lam mu : Fin N → ℕ} (h : lam = mu) :
    Nonempty (Representation.Equiv (slRestrict (schurModuleRep k N lam))
      (slRestrict (schurModuleRep k N mu))) := by
  subst h; exact ⟨Representation.Equiv.refl _⟩

/-- **Constant `+m` shift, `SL_N`-equivariantly.** Iterating `schurModule_slEquiv_succ`. -/
theorem schurModule_slEquiv_add_const (N : ℕ) (lam : Fin N → ℕ) (hlam : Antitone lam) (m : ℕ) :
    Nonempty (Representation.Equiv (slRestrict (schurModuleRep k N (fun i => lam i + m)))
      (slRestrict (schurModuleRep k N lam))) := by
  induction m with
  | zero =>
    exact schurModule_slEquiv_congr (k := k) N
      (show (fun i => lam i + 0) = lam by funext i; omega)
  | succ m ih =>
    obtain ⟨E⟩ := ih
    obtain ⟨F⟩ := schurModule_slEquiv_succ (k := k) N (fun i => lam i + m)
      (fun a b h => Nat.add_le_add_right (hlam h) m)
    obtain ⟨G⟩ := schurModule_slEquiv_congr (k := k) N
      (show (fun i => lam i + (m + 1)) = (fun i => (lam i + m) + 1) by funext i; omega)
    exact ⟨(G.trans F).trans E⟩

omit [CharZero k] in
/-- The `SL_N`-restriction of `L_λ` is the `SL_N`-restriction of the underlying Schur module: the
`det^{-λ.shift}` normalization built into `algIrrepGLRepρ` is invisible on `SL_N`. -/
lemma slRestrict_algIrrepGLRepρ {n : ℕ} (lam : DominantWeight n) :
    slRestrict (algIrrepGLRepρ n lam k) = slRestrict (schurModuleRep k n lam.toNatWeight) :=
  slRestrict_charTwistRep_detChar_zpow _ _

/-- **The `SL_N`-equivariant isomorphism `L_{λ + c·1ᴺ} ≅ L_λ` (Remark 5.23.3).** On `SL(V)` the
determinant character is trivial, so the `GL(V)`-representations `L_λ` and its determinant twists
`L_{λ + c·1ᴺ}` become isomorphic. This is the representation-level statement whose dimension
shadow is `algIrrepGL_finrank_constShift`.
(Etingof Remark 5.23.3) -/
theorem algIrrepGL_slEquiv_constShift {n : ℕ} (lam : DominantWeight n) (c : ℤ) :
    Nonempty (Representation.Equiv (slRestrict (algIrrepGLRepρ n (lam.constShift c) k))
      (slRestrict (algIrrepGLRepρ n lam k))) := by
  rw [slRestrict_algIrrepGLRepρ, slRestrict_algIrrepGLRepρ]
  have ha_anti : Antitone lam.toNatWeight := toNatWeight_antitone lam
  have hb_anti : Antitone (lam.constShift c).toNatWeight := toNatWeight_antitone (lam.constShift c)
  set Δ : ℤ := c + ((lam.constShift c).shift : ℤ) - (lam.shift : ℤ) with hΔdef
  have hrel : ∀ i, ((lam.constShift c).toNatWeight i : ℤ) = (lam.toNatWeight i : ℤ) + Δ := by
    intro i
    rw [toNatWeight_cast (lam.constShift c) i, toNatWeight_cast lam i,
      DominantWeight.constShift_val, hΔdef]
    ring
  rcases le_total 0 Δ with hΔ | hΔ
  · obtain ⟨G⟩ := schurModule_slEquiv_congr (k := k) n
      (show (lam.constShift c).toNatWeight = (fun i => lam.toNatWeight i + Δ.toNat) by
        funext i; have := hrel i; omega)
    obtain ⟨E⟩ := schurModule_slEquiv_add_const (k := k) n lam.toNatWeight ha_anti Δ.toNat
    exact ⟨G.trans E⟩
  · obtain ⟨G⟩ := schurModule_slEquiv_congr (k := k) n
      (show lam.toNatWeight = (fun i => (lam.constShift c).toNatWeight i + (-Δ).toNat) by
        funext i; have := hrel i; omega)
    obtain ⟨E⟩ := schurModule_slEquiv_add_const (k := k) n (lam.constShift c).toNatWeight hb_anti
      (-Δ).toNat
    exact ⟨(G.trans E).symm⟩

end SLEquiv

/-! ## The parametrization of the `L_λ|_{SL_N}` by `SLWeightParam N` -/

section SLParam

variable (n : ℕ) (k : Type) [Field k] [IsAlgClosed k] [CharZero k]

/-- **Isomorphism of `SL_N`-restrictions**, as an equivalence relation on dominant weights: `λ` and
`μ` are related when `L_λ` and `L_μ` become isomorphic after restricting to `SL_N`. It is an
equivalence relation because `Representation.Equiv` carries `refl`, `symm` and `trans`. -/
def slIsoSetoid : Setoid (DominantWeight n) where
  r lam mu := Nonempty (Representation.Equiv (slRestrict (algIrrepGLRepρ n lam k))
    (slRestrict (algIrrepGLRepρ n mu k)))
  iseqv :=
    { refl := fun _ => ⟨Representation.Equiv.refl _⟩
      symm := fun ⟨E⟩ => ⟨E.symm⟩
      trans := fun ⟨E⟩ ⟨F⟩ => ⟨E.trans F⟩ }

variable {n k}

/-- **Shift-equivalent weights give isomorphic `SL_N`-representations.** This is what makes the
parametrization of the `L_λ|_{SL_N}` by `SLWeightParam N` well defined: the shift relation refines
the isomorphism relation. -/
theorem shiftEquiv_slIso {lam mu : DominantWeight n}
    (h : DominantWeight.ShiftEquiv lam mu) : (slIsoSetoid n k).r lam mu := by
  obtain ⟨c, rfl⟩ := h
  exact ⟨(algIrrepGL_slEquiv_constShift (k := k) lam c).some.symm⟩

variable (n k)

/-- **The parametrization map.** Etingof's "the irreducible `SL(V)`-representations are
parametrized by `λ₁ ≥ ⋯ ≥ λ_N` up to a simultaneous shift by a constant" says that
`λ ↦ L_λ|_{SL_N}` descends to `SLWeightParam N` and is a bijection onto the irreducibles. The
descent is `shiftEquiv_slIso`; the resulting map lands in the isomorphism classes of the
`SL_N`-restrictions of the `L_λ`. -/
def slIrrepClass : SLWeightParam n → Quotient (slIsoSetoid n k) :=
  Quotient.map' id fun _ _ h => shiftEquiv_slIso h

@[simp] lemma slIrrepClass_mk (lam : DominantWeight n) :
    slIrrepClass n k (Quotient.mk _ lam) = Quotient.mk _ lam := rfl

/-- The parametrization map is surjective: every `SL_N`-restriction `L_λ|_{SL_N}` is named by the
shift class of `λ`. -/
theorem slIrrepClass_surjective : Function.Surjective (slIrrepClass n k) := by
  intro q
  induction q using Quotient.inductionOn with
  | h lam => exact ⟨Quotient.mk _ lam, rfl⟩

end SLParam

/-! ## Injectivity of the parametrization: distinct shift classes stay distinct

`shiftEquiv_slIso` is the easy half of Etingof's claim — shift-equivalent weights give isomorphic
`SL_N`-restrictions. This section proves the converse, so the shift classes are *exactly* the
isomorphism classes and `slIrrepClass` is a bijection.

The `GL_N`-side input is `algIrrepGLRepρ_iso_iff_eq` (distinct dominant weights give
non-isomorphic `L_λ`), and the route from `SL_N` back up to `GL_N` runs through the scalar
matrices `s·1ᴺ`. Two facts about them do all the work:

* a scalar acts on `L_λ` by `s^{|λ|}`, where `|λ| = ∑ᵢ λᵢ` is `DominantWeight.total`
  (`algIrrepGLRepρ_scalarGL`);
* over an algebraically closed field every `d : kˣ` has an `N`-th root, so
  `g = (s·1ᴺ) · ((s·1ᴺ)⁻¹ * g)` with the second factor of determinant one: `GL_N(k)` is generated
  by its scalars together with `SL_N(k)` (`specialLinearFactor`).

The proof is then two steps. The scalars that already lie *inside* `SL_N` are the `N`-th roots of
unity, and an `SL_N`-equivariant isomorphism has to match the scalars they act by, forcing
`s^{|λ|} = s^{|μ|}` for every one of them; a primitive root then upgrades that to `N ∣ |μ| - |λ|`
(`natCast_dvd_total_sub_of_slIso`). That divisibility is exactly what it takes for
`c := (|μ| - |λ|)/N` to be an integer, and replacing `λ` by `λ + c·1ᴺ` — harmless, by
`algIrrepGL_slEquiv_constShift` — equalizes the two total weights. Once the totals agree the
scalar factors cancel, so an `SL_N`-equivariant map is *automatically* `GL_N`-equivariant
(`isIntertwining_of_slEquiv_of_total_eq`), and the `GL_N` classification finishes the job.
-/

section Scalars

variable (k : Type*) [Field k] (n : ℕ)

/-- **The scalar matrix `s·1ᴺ` as an element of `GL_N(k)`.** Over an algebraically closed field the
scalars together with `SL_N(k)` generate `GL_N(k)` (`specialLinearFactor`), which is what lets an
`SL_N`-equivariant map be promoted to a `GL_N`-equivariant one. -/
def scalarGL (s : kˣ) : Matrix.GeneralLinearGroup (Fin n) k where
  val := (s : k) • (1 : Matrix (Fin n) (Fin n) k)
  inv := ((s⁻¹ : kˣ) : k) • (1 : Matrix (Fin n) (Fin n) k)
  val_inv := by simp [smul_smul]
  inv_val := by simp [smul_smul]

variable {k n}

@[simp] lemma scalarGL_val (s : kˣ) :
    ((scalarGL k n s : Matrix.GeneralLinearGroup (Fin n) k) : Matrix (Fin n) (Fin n) k)
      = (s : k) • 1 := rfl

/-- **The determinant of `s·1ᴺ` is `s^N`.** This is the one place `N` enters the descent: it is why
the scalars inside `SL_N` are the `N`-th roots of unity, and why the constant shift `c` is
`(|μ| - |λ|)/N`. -/
@[simp] lemma detChar_scalarGL (s : kˣ) : detChar k n (scalarGL k n s) = s ^ n := by
  apply Units.ext
  change Matrix.det (scalarGL k n s).val = ((s ^ n : kˣ) : k)
  simp

/-- `detChar` is `Matrix.GeneralLinearGroup.det`, but `map_mul`/`map_inv` leave the latter form
behind, so `detChar_scalarGL` needs an unfolded copy to rewrite with. -/
lemma det_scalarGL (s : kˣ) :
    Matrix.GeneralLinearGroup.det (scalarGL k n s) = s ^ n := detChar_scalarGL s

/-- **An `N`-th root of unity gives a scalar element of `SL_N(k)`.** These are exactly the scalars
an `SL_N`-equivariant map can see. -/
def scalarSL (s : kˣ) (hs : (s : k) ^ n = 1) : Matrix.SpecialLinearGroup (Fin n) k :=
  ⟨(s : k) • 1, by simp [hs]⟩

@[simp] lemma toGL_scalarSL (s : kˣ) (hs : (s : k) ^ n = 1) :
    Matrix.SpecialLinearGroup.toGL (scalarSL s hs) = scalarGL k n s := Units.ext rfl

/-- **`GL_N(k) = (scalars) · SL_N(k)` over an algebraically closed field.** Given `g`, take an
`N`-th root `s` of `det g` — one exists because `k` is algebraically closed and `N > 0` — and split
off the scalar `s·1ᴺ`; what is left has determinant `det g / s^N = 1`. -/
lemma specialLinearFactor [IsAlgClosed k] (hn : n ≠ 0)
    (g : Matrix.GeneralLinearGroup (Fin n) k) :
    ∃ (s : kˣ) (h : Matrix.SpecialLinearGroup (Fin n) k),
      g = scalarGL k n s * Matrix.SpecialLinearGroup.toGL h := by
  obtain ⟨x, hx⟩ := IsAlgClosed.exists_pow_nat_eq
    ((g : Matrix (Fin n) (Fin n) k).det) (Nat.pos_of_ne_zero hn)
  have hx0 : x ≠ 0 := by
    intro h0
    rw [h0, zero_pow hn] at hx
    exact (Matrix.GeneralLinearGroup.det g).ne_zero hx.symm
  refine ⟨Units.mk0 x hx0, ⟨((scalarGL k n (Units.mk0 x hx0))⁻¹ * g).val, ?_⟩, ?_⟩
  · -- The leftover factor has determinant `det g / s^N = 1`.
    have hdet : Matrix.GeneralLinearGroup.det ((scalarGL k n (Units.mk0 x hx0))⁻¹ * g) = 1 := by
      rw [map_mul, map_inv, det_scalarGL, inv_mul_eq_one]
      exact Units.ext (by simpa using hx)
    exact congrArg Units.val hdet
  · apply Units.ext
    change (g : Matrix (Fin n) (Fin n) k)
        = (scalarGL k n (Units.mk0 x hx0)).val * ((scalarGL k n (Units.mk0 x hx0))⁻¹ * g).val
    rw [← Units.val_mul, mul_inv_cancel_left]

end Scalars

section ScalarAction

variable {k : Type*} [Field k] {n : ℕ}

/-- **A scalar acts on `V^{⊗ m}` by `s^m`.** The diagonal action `g ↦ g^{⊗ m}` sends `s·1ᴺ` to
`(s · id)^{⊗ m}`, and pulling the scalar out of each of the `m` tensor slots multiplies them. -/
lemma glTensorRep_scalarGL (m : ℕ) (s : kˣ) (x : TensorPower k (Fin n → k) m) :
    glTensorRep k n m (scalarGL k n s) x = ((s : k) ^ m) • x := by
  induction x using PiTensorProduct.induction_on with
  | smul_tprod a v =>
    change glTensorRep k n m (scalarGL k n s) (a • PiTensorProduct.tprod k v) = _
    rw [map_smul]
    change a • PiTensorProduct.map (fun _ : Fin m => Matrix.mulVecLin (scalarGL k n s).val)
      (PiTensorProduct.tprod k v) = _
    rw [PiTensorProduct.map_tprod]
    have hmv : ∀ i : Fin m,
        Matrix.mulVecLin (R := k) (scalarGL k n s).val (v i) = (s : k) • v i := by
      intro i
      change ((s : k) • (1 : Matrix (Fin n) (Fin n) k)).mulVec (v i) = (s : k) • v i
      rw [Matrix.smul_mulVec, Matrix.one_mulVec]
    rw [funext hmv, (PiTensorProduct.tprod k).map_smul_univ (fun _ : Fin m => (s : k)) v]
    simp [smul_smul, mul_comm]
  | add x y hx hy => simp only [map_add, hx, hy, smul_add]

/-- **A scalar acts on the Schur module `L_a` by `s^{|a|}`**, `|a| = ∑ᵢ aᵢ` being the tensor degree
`L_a ⊆ V^{⊗ |a|}` lives in. -/
lemma schurModuleRep_scalarGL (a : Fin n → ℕ) (s : kˣ) (v : SchurModuleSubmodule k n a) :
    schurModuleRep k n a (scalarGL k n s) v = ((s : k) ^ (∑ i, a i)) • v := by
  apply Subtype.ext
  change glTensorRep k n (∑ i, a i) (scalarGL k n s) (v : TensorPower k (Fin n → k) (∑ i, a i))
    = ((s : k) ^ (∑ i, a i)) • (v : TensorPower k (Fin n → k) (∑ i, a i))
  exact glTensorRep_scalarGL _ s _

variable [IsAlgClosed k]

/-- The `ℕ`-weight `λ.toNatWeight` has total `|λ| + N·shift`: it is `λ` shifted up by
`λ.shift` in each of the `N` coordinates. -/
private lemma sum_toNatWeight (lam : DominantWeight n) :
    ((∑ i, lam.toNatWeight i : ℕ) : ℤ) = lam.total + n * (lam.shift : ℤ) := by
  push_cast
  rw [Finset.sum_congr rfl (fun i _ => toNatWeight_cast lam i)]
  simp only [DominantWeight.total, Finset.sum_add_distrib, Finset.sum_const, Finset.card_univ,
    Fintype.card_fin, nsmul_eq_mul]

/-- **A scalar acts on `L_λ` by `s^{|λ|}` (Remark 5.23.3).** The `det^{-λ.shift}` normalization
built into `algIrrepGLRepρ` contributes `s^{-N·λ.shift}` and the underlying Schur module
contributes `s^{|λ| + N·λ.shift}`, so the two shift terms cancel and only the total weight
`|λ| = ∑ᵢ λᵢ` survives. This is the character of `GL_N` by which the centre acts, and it is the
invariant that pins down the constant `c` in Etingof's "up to a simultaneous shift". -/
lemma algIrrepGLRepρ_scalarGL (lam : DominantWeight n) (s : kˣ) (v : AlgIrrepGL n lam k) :
    algIrrepGLRepρ n lam k (scalarGL k n s) v = ((s ^ lam.total : kˣ) : k) • v := by
  -- The two `s`-powers combine to `s ^ |λ|`: the `-N·shift` from the determinant twist cancels
  -- the `+N·shift` that `toNatWeight` put into the Schur module's degree.
  have key : ((detChar k n ^ (-(lam.shift : ℤ))) (scalarGL k n s))
      * (s ^ (∑ i, lam.toNatWeight i) : kˣ) = s ^ lam.total := by
    rw [MonoidHom.zpow_apply, detChar_scalarGL, ← zpow_natCast s (∑ i, lam.toNatWeight i),
      ← zpow_natCast s n, ← zpow_mul, ← zpow_add]
    congr 1
    rw [sum_toNatWeight lam]
    ring
  -- Restate on the Schur-module carrier, where `schurModuleRep_scalarGL` can be rewritten.
  change ((detChar k n ^ (-(lam.shift : ℤ))) (scalarGL k n s) : k) •
      schurModuleRep k n lam.toNatWeight (scalarGL k n s)
        (v : SchurModuleSubmodule k n lam.toNatWeight)
      = ((s ^ lam.total : kˣ) : k) • (v : SchurModuleSubmodule k n lam.toNatWeight)
  rw [schurModuleRep_scalarGL, smul_smul, ← Units.val_pow_eq_pow_val, ← Units.val_mul, key]

end ScalarAction

section SLNonIso

variable {n : ℕ} {k : Type} [Field k] [IsAlgClosed k] [CharZero k]

/-- Every weight of `DominantWeight 0` is the same one: there are no coordinates. -/
instance : Subsingleton (DominantWeight 0) :=
  ⟨fun _ _ => Subtype.ext (funext fun i => i.elim0)⟩

omit [IsAlgClosed k] [CharZero k] in
/-- Pointwise form of the intertwining property of a `Representation.Equiv`, phrased on the
underlying linear equivalence (which is the form `Representation.asModuleEquivOfIntertwiner`
consumes). -/
private lemma equiv_apply_rho {G : Type*} [Monoid G] {V W : Type*}
    [AddCommGroup V] [Module k V] [AddCommGroup W] [Module k W]
    {ρ : Representation k G V} {σ : Representation k G W} (E : Representation.Equiv ρ σ)
    (g : G) (v : V) : E.toLinearEquiv (ρ g v) = σ g (E.toLinearEquiv v) :=
  LinearMap.ext_iff.mp (E.isIntertwining' g) v

/-- **The `N`-th roots of unity separate the total weights.** An `SL_N`-equivariant isomorphism
`L_λ|_{SL_N} ≅ L_μ|_{SL_N}` has to match the scalar by which each `N`-th root of unity `s` acts,
i.e. `s^{|λ|} = s^{|μ|}`. Taking `s` primitive — available because `k` is algebraically closed of
characteristic zero — this says exactly `N ∣ |μ| - |λ|`, which is what makes the constant
`c = (|μ| - |λ|)/N` of Etingof's simultaneous shift an integer. -/
theorem natCast_dvd_total_sub_of_slIso {lam mu : DominantWeight n}
    (h : (slIsoSetoid n k).r lam mu) : (n : ℤ) ∣ mu.total - lam.total := by
  rcases Nat.eq_zero_or_pos n with rfl | hn
  · -- No coordinates: both totals are the empty sum.
    simp [DominantWeight.total]
  obtain ⟨E⟩ := h
  have hn0 : n ≠ 0 := hn.ne'
  haveI : NeZero n := ⟨hn0⟩
  haveI : NeZero ((n : ℕ) : k) := ⟨Nat.cast_ne_zero.mpr hn0⟩
  obtain ⟨ζ, hζ⟩ := HasEnoughRootsOfUnity.exists_primitiveRoot k n
  -- `ζ` is a unit, and as a unit it is still a primitive `N`-th root of unity.
  obtain ⟨u, huζ⟩ : ∃ u : kˣ, (u : k) = ζ := ⟨(hζ.isUnit hn0).unit, IsUnit.unit_spec _⟩
  have hζu : IsPrimitiveRoot u n := IsPrimitiveRoot.coe_units_iff.mp (by rw [huζ]; exact hζ)
  have hun : (u : k) ^ n = 1 := by rw [huζ]; exact hζ.pow_eq_one
  -- A nonzero vector of `L_λ`, on which the two scalars can be compared.
  obtain ⟨w, hwmem, hw0⟩ := (Submodule.ne_bot_iff _).mp
    (schurModuleSubmodule_ne_bot (k := k) n lam.toNatWeight lam.toNatWeight_antitone)
  have hvne : (⟨w, hwmem⟩ : AlgIrrepGL n lam k) ≠ 0 :=
    fun hcon => hw0 (congrArg Subtype.val hcon)
  have hEne : E.toLinearEquiv (⟨w, hwmem⟩ : AlgIrrepGL n lam k) ≠ 0 :=
    fun hcon => hvne (E.toLinearEquiv.map_eq_zero_iff.mp hcon)
  -- The scalar `u·1ᴺ` lies in `SL_N`, so `E` must match the two scalars it acts by.
  have hint := equiv_apply_rho E (scalarSL u hun) (⟨w, hwmem⟩ : AlgIrrepGL n lam k)
  simp only [slRestrict_apply, toGL_scalarSL, algIrrepGLRepρ_scalarGL, map_smul] at hint
  have hscal : ((u ^ lam.total : kˣ) : k) = ((u ^ mu.total : kˣ) : k) := by
    by_contra hne
    apply hEne
    have hz := sub_eq_zero_of_eq hint
    rw [← sub_smul] at hz
    exact (smul_eq_zero.mp hz).resolve_left (sub_ne_zero_of_ne hne)
  -- Hence `u ^ (|μ| - |λ|) = 1`, and `u` is primitive, so `N ∣ |μ| - |λ|`.
  refine (hζu.zpow_eq_one_iff_dvd (mu.total - lam.total)).mp ?_
  rw [zpow_sub, show u ^ mu.total = u ^ lam.total from Units.ext hscal.symm, mul_inv_cancel]

omit [CharZero k] in
/-- **Equal total weights turn an `SL_N`-map into a `GL_N`-map.** Write `g = (s·1ᴺ)·h` with
`h ∈ SL_N` (`specialLinearFactor`). The `SL_N`-equivariance handles `h`, and the scalar `s·1ᴺ`
contributes `s^{|λ|}` on the source and `s^{|μ|}` on the target — the same factor once
`|λ| = |μ|`, so it commutes past the map. -/
theorem isIntertwining_of_slEquiv_of_total_eq {lam mu : DominantWeight n} (hn : n ≠ 0)
    (htot : lam.total = mu.total) (f : AlgIrrepGL n lam k ≃ₗ[k] AlgIrrepGL n mu k)
    (hf : ∀ (h : Matrix.SpecialLinearGroup (Fin n) k) (v : AlgIrrepGL n lam k),
      f (algIrrepGLRepρ n lam k (Matrix.SpecialLinearGroup.toGL h) v)
        = algIrrepGLRepρ n mu k (Matrix.SpecialLinearGroup.toGL h) (f v))
    (g : Matrix.GeneralLinearGroup (Fin n) k) (v : AlgIrrepGL n lam k) :
    f (algIrrepGLRepρ n lam k g v) = algIrrepGLRepρ n mu k g (f v) := by
  obtain ⟨s, h, rfl⟩ := specialLinearFactor hn g
  rw [map_mul, Module.End.mul_apply, map_mul, Module.End.mul_apply,
    algIrrepGLRepρ_scalarGL, map_smul, algIrrepGLRepρ_scalarGL, htot]
  -- The scalar factors are now literally equal, and `hf` handles the `SL_N` factor.
  exact congrArg _ (hf h v)

/-- **Isomorphic `SL_N`-restrictions come from shift-equivalent weights (Remark 5.23.3).** The
converse of `shiftEquiv_slIso`, and the missing half of Etingof's parametrization: if `L_λ` and
`L_μ` become isomorphic after restricting to `SL_N`, then `μ = λ + c·1ᴺ` for some integer `c`.

The constant is forced: `c = (|μ| - |λ|)/N`, an integer by `natCast_dvd_total_sub_of_slIso`. With
that `c`, the weight `λ + c·1ᴺ` has the same total weight as `μ` and still the same
`SL_N`-restriction as `λ` (`algIrrepGL_slEquiv_constShift`), so the isomorphism between them is
already `GL_N`-equivariant (`isIntertwining_of_slEquiv_of_total_eq`) and the `GL_N` classification
`algIrrepGLRepρ_iso_iff_eq` gives `λ + c·1ᴺ = μ` on the nose.
(Etingof Remark 5.23.3) -/
theorem slIso_shiftEquiv {lam mu : DominantWeight n}
    (h : (slIsoSetoid n k).r lam mu) : DominantWeight.ShiftEquiv lam mu := by
  rcases Nat.eq_zero_or_pos n with rfl | hn
  · exact ⟨0, Subsingleton.elim _ _⟩
  obtain ⟨c, hc⟩ := natCast_dvd_total_sub_of_slIso h
  refine ⟨c, ?_⟩
  -- Move `λ` to the shift-equivalent weight with the same total weight as `μ`.
  set lam' : DominantWeight n := lam.constShift c with hlam'
  have htot : lam'.total = mu.total := by
    rw [hlam', DominantWeight.total_constShift]; omega
  -- `L_{λ'}|_{SL_N} ≅ L_λ|_{SL_N} ≅ L_μ|_{SL_N}`.
  have hslam' : (slIsoSetoid n k).r lam' mu :=
    (slIsoSetoid n k).trans ((slIsoSetoid n k).symm (shiftEquiv_slIso ⟨c, rfl⟩)) h
  obtain ⟨E⟩ := hslam'
  -- Equal totals make it `GL_N`-equivariant, so the `GL_N` classification applies.
  have hiso : Nonempty ((algIrrepGLRepρ n lam' k).asModule ≃ₗ[MonoidAlgebra k
      (Matrix.GeneralLinearGroup (Fin n) k)] (algIrrepGLRepρ n mu k).asModule) :=
    ⟨Representation.asModuleEquivOfIntertwiner E.toLinearEquiv
      (isIntertwining_of_slEquiv_of_total_eq hn.ne' htot E.toLinearEquiv
        (fun g x => equiv_apply_rho E g x))⟩
  exact ((algIrrepGLRepρ_iso_iff_eq n k).mp hiso).symm

variable (n k)

/-- **The parametrization map is injective**: weights in different shift classes give
non-isomorphic `SL_N`-restrictions. This is `slIso_shiftEquiv` read on the quotient. -/
theorem slIrrepClass_injective : Function.Injective (slIrrepClass n k) := by
  intro p q hpq
  induction p using Quotient.inductionOn with
  | h lam =>
    induction q using Quotient.inductionOn with
    | h mu =>
      exact Quotient.sound (slIso_shiftEquiv (k := k) (Quotient.exact hpq))

/-- **The parametrization map is bijective.** -/
theorem slIrrepClass_bijective : Function.Bijective (slIrrepClass n k) :=
  ⟨slIrrepClass_injective n k, slIrrepClass_surjective n k⟩

/-- **Etingof's parametrization of the irreducible `SL_N`-representations (Remark 5.23.3).** The
`SL_N`-restrictions of the `L_λ`, taken up to isomorphism, are in bijection with the dominant
weights `λ₁ ≥ ⋯ ≥ λ_N` modulo a simultaneous shift by a constant. Surjectivity is
`slIrrepClass_surjective` (every restriction is named by a weight) and injectivity is
`slIrrepClass_injective` (only the shift can be undone).
(Etingof Remark 5.23.3) -/
noncomputable def slIrrepEquiv : SLWeightParam n ≃ Quotient (slIsoSetoid n k) :=
  Equiv.ofBijective _ (slIrrepClass_bijective n k)

@[simp] lemma slIrrepEquiv_apply (lam : DominantWeight n) :
    slIrrepEquiv n k (Quotient.mk _ lam) = Quotient.mk _ lam := rfl

end SLNonIso

end Etingof
