import Mathlib
import EtingofRepresentationTheory.Chapter5.Theorem5_18_1

/-!
# Theorem 5.18.1: exhaustiveness of the simple families (Double Centralizer)

`Theorem5_18_1.lean` produces the bimodule decomposition
`E ≃ ⨁ᵢ Vᵢ ⊗ Lᵢ` with the `Vᵢ` pairwise non-isomorphic simple `A`-modules
and the `Lᵢ = Vᵢ →ₗ[A] E` simple `B`-modules (`B = centralizer(A)`). What that
file does *not* establish is **exhaustiveness**: that the list `{Vᵢ}` (resp.
`{Lᵢ}`) already contains *every* simple `A`-module (resp. `B`-module) up to
isomorphism. Without exhaustiveness the theorem only exhibits a finite family of
summands; the book's claim that the `Vᵢ` "are all the irreducible
representations of `A`" is stronger.

This file supplies the missing crux, a single embedding lemma

* `exists_simpleSubmodule_iso_of_faithful`: **every simple module of a
  semisimple subalgebra `C ⊆ End_k(E)` is isomorphic to a simple `C`-submodule
  of `E`.**

Because `E` is faithful over `C` (an element of `C ⊆ End_k(E)` that kills `E`
is the zero endomorphism), a simple `C`-module `S` embeds into `C` (as a direct
summand, `C` being semisimple), and `C` embeds `C`-linearly into `E → E` by
`c ↦ (e ↦ c e)`; some coordinate projection of the composite `S → E` is a
nonzero, hence injective, `C`-linear map, and its range is a simple submodule
of `E` isomorphic to `S`.

The lemma applies to *both* sides of the double centralizer theorem:

* with `C = A` it gives **A-family exhaustiveness**
  (`Theorem5_18_1_A_family_exhaustive`): every simple `A`-module is realised as
  a simple submodule of `E`, i.e. is one of the `Vᵢ`;
* with `C = centralizer(A)` (semisimple by
  `Theorem5_18_1_commutant_semisimple`) it gives **B-family exhaustiveness**
  (`Theorem5_18_1_B_family_exhaustive`): every simple `B`-module is realised as
  a simple `B`-submodule of `E`.

Combined with the already-established distinctness of the `Vᵢ`
(`Theorem5_18_1_bimodule_decomposition_explicit`) and the biduality
correspondence `Vᵢ ↔ Lᵢ = Hom_A(Vᵢ, E)`
(`MultiplicitySpaceBiduality.multiplicitySpace_biduality_Aiso`,
`isSimpleModule_homA_centralizer`), these results pin down both families as
complete lists of simple modules.
-/

open scoped TensorProduct

universe u v w

namespace Etingof

variable (k : Type u) [Field k]
  (E : Type v) [AddCommGroup E] [Module k E] [Module.Finite k E]

omit [Module.Finite k E] in
/-- **Every simple module of a semisimple subalgebra of `End_k(E)` is realised
inside `E`.**

For a subalgebra `C ⊆ End_k(E)` that is semisimple as a ring, any simple
`C`-module `S` is isomorphic to a simple `C`-submodule of `E`.

The finite-dimensionality of `E` is not needed for the statement, but `E` being
faithful over `C` is automatic here: `C` is literally a subalgebra of
`End_k(E)`, so the natural map `C → (E → E)`, `c ↦ (e ↦ c e)`, is injective.

Proof outline:
* `S` is a quotient of `C` (cyclic, generated by any nonzero `s₀`), hence — `C`
  being semisimple — isomorphic to a `C`-submodule of `C`, giving an injection
  `ι : S ↪ C`;
* `ψ : C ↪ (E → E)`, `c ↦ (e ↦ c e)`, is injective since `C ⊆ End_k(E)`;
* the composite `S → (E → E)` is injective, so some coordinate `f : S → E` is
  nonzero, hence injective (`S` simple), and `range f` is the desired simple
  submodule. -/
theorem exists_simpleSubmodule_iso_of_faithful
    (C : Subalgebra k (Module.End k E)) [IsSemisimpleRing C]
    (S : Type w) [AddCommGroup S] [Module C S] [IsSimpleModule C S] :
    ∃ W : Submodule C E, IsSimpleModule C W ∧ Nonempty (S ≃ₗ[C] W) := by
  classical
  haveI : Nontrivial S := IsSimpleModule.nontrivial C S
  obtain ⟨s₀, hs₀⟩ := exists_ne (0 : S)
  -- Surjection `g : C ↠ S`, `a ↦ a • s₀` (cyclic since `S` is simple).
  set g : (↥C) →ₗ[↥C] S := LinearMap.toSpanSingleton (↥C) S s₀ with hg
  have hg_surj : Function.Surjective g := by
    intro x
    have hspan : Submodule.span (↥C) {s₀} = ⊤ := by
      rcases eq_bot_or_eq_top (Submodule.span (↥C) {s₀}) with h | h
      · exact absurd (by simpa [h] using Submodule.mem_span_singleton_self (R := ↥C) s₀) hs₀
      · exact h
    have hx : x ∈ Submodule.span (↥C) {s₀} := by rw [hspan]; trivial
    rw [Submodule.mem_span_singleton] at hx
    obtain ⟨a, ha⟩ := hx
    exact ⟨a, by simp only [hg, LinearMap.toSpanSingleton_apply]; exact ha⟩
  -- `S ≃ C ⧸ ker g`; `ker g` splits off a summand `P ≃ C ⧸ ker g`, giving `S ↪ C`.
  let equivS : ((↥C) ⧸ LinearMap.ker g) ≃ₗ[↥C] S := g.quotKerEquivOfSurjective hg_surj
  obtain ⟨P, ⟨eP⟩⟩ :=
    IsSemisimpleModule.exists_submodule_linearEquiv_quotient (LinearMap.ker g)
  let ιSC : S →ₗ[↥C] (↥C) := P.subtype ∘ₗ (equivS.symm.trans eP.symm).toLinearMap
  have hι_inj : Function.Injective ιSC :=
    Subtype.val_injective.comp (equivS.symm.trans eP.symm).injective
  -- `ψ : C ↪ (E → E)`, `c ↦ (e ↦ c e)`.
  let ψ : (↥C) →ₗ[↥C] (E → E) :=
    { toFun := fun c e => c.val e
      map_add' := fun c c' => by ext e; simp
      map_smul' := fun a c => by ext e; rfl }
  have hψ_inj : Function.Injective ψ := by
    rw [injective_iff_map_eq_zero]
    intro c hc
    have hval : (c : Module.End k E) = 0 := by
      ext e; exact congr_fun hc e
    exact Subtype.ext (by simpa using hval)
  -- The composite `S ↪ (E → E)` is injective, hence nonzero on `s₀`.
  let emb : S →ₗ[↥C] (E → E) := ψ ∘ₗ ιSC
  have hemb_inj : Function.Injective emb := hψ_inj.comp hι_inj
  have hemb_s₀ : emb s₀ ≠ 0 := fun h => hs₀ (hemb_inj (by rw [h, map_zero]))
  -- Some coordinate `f = proj e ∘ emb : S → E` is nonzero.
  have hcoord : ∃ e : E, (emb s₀) e ≠ 0 := by
    by_contra hh
    apply hemb_s₀
    funext e
    by_contra hne
    exact hh ⟨e, hne⟩
  obtain ⟨e, he⟩ := hcoord
  let f : S →ₗ[↥C] E := (LinearMap.proj e) ∘ₗ emb
  have hf_ne : f ≠ 0 := fun h => he (by
    have : f s₀ = 0 := by rw [h]; rfl
    exact this)
  -- `f` is injective (`S` simple), so its range is a simple submodule of `E`.
  have hker : LinearMap.ker f = ⊥ := by
    rcases eq_bot_or_eq_top (LinearMap.ker f) with h | h
    · exact h
    · exact absurd (LinearMap.ker_eq_top.mp h) hf_ne
  have hf_inj : Function.Injective f := LinearMap.ker_eq_bot.mp hker
  refine ⟨LinearMap.range f, ?_, ⟨LinearEquiv.ofInjective f hf_inj⟩⟩
  exact IsSimpleModule.congr (LinearEquiv.ofInjective f hf_inj).symm

omit [Module.Finite k E] in
/-- **Complete irredundant classification of the simple modules of a semisimple
subalgebra `C ⊆ End_k(E)`.**

Indexing by the isotypic components of `E`, choose one simple submodule
`V c ≤ c` per component. Then the family `{V c}`:

* consists of simple `C`-modules;
* is **irredundant**: `V c ≃ V c' ⟹ c = c'` (distinct components carry
  non-isomorphic simples, since isomorphic simple submodules generate the same
  isotypic component);
* is **exhaustive**: every simple `C`-module `S` is isomorphic to some `V c`
  (`exists_simpleSubmodule_iso_of_faithful` realises `S` as a simple submodule
  `W ≤ E`, which lies in — hence is isomorphic to the chosen simple of — its
  isotypic component).

This is the abstract engine behind both sides of Theorem 5.18.1: applied to
`C = A` it classifies the simple `A`-modules; applied to `C = centralizer(A)`
(semisimple by `Theorem5_18_1_commutant_semisimple`) it classifies the simple
`B`-modules. When `E` is finite-dimensional the index `isotypicComponents C E`
is finite, so each family is a finite complete list. -/
theorem simpleModule_classification_of_semisimple
    (C : Subalgebra k (Module.End k E)) [IsSemisimpleRing C] :
    ∃ (V : isotypicComponents C E → Submodule C E) (_ : ∀ c, IsSimpleModule C (V c)),
      (∀ c, (V c : Submodule C E) ≤ (c : Submodule C E)) ∧
      (∀ c c', Nonempty (↥(V c) ≃ₗ[C] ↥(V c')) → c = c') ∧
      ∀ (S : Type w) [AddCommGroup S] [Module C S] [IsSimpleModule C S],
        ∃ c, Nonempty (S ≃ₗ[C] ↥(V c)) := by
  classical
  haveI : IsSemisimpleModule C E := IsSemisimpleRing.isSemisimpleModule
  -- Choose a simple submodule `V c ≤ c` in each isotypic component.
  let V : isotypicComponents C E → Submodule C E := fun c =>
    ((IsSemisimpleModule.eq_bot_or_exists_simple_le (c.1 : Submodule C E)).resolve_left
      (bot_lt_isotypicComponents c.2).ne').choose
  have V_le : ∀ c, V c ≤ c.1 := fun c =>
    ((IsSemisimpleModule.eq_bot_or_exists_simple_le (c.1 : Submodule C E)).resolve_left
      (bot_lt_isotypicComponents c.2).ne').choose_spec.1
  have V_simple : ∀ c, IsSimpleModule C (V c) := fun c =>
    ((IsSemisimpleModule.eq_bot_or_exists_simple_le (c.1 : Submodule C E)).resolve_left
      (bot_lt_isotypicComponents c.2).ne').choose_spec.2
  have V_spec : ∀ c, (c.1 : Submodule C E) = isotypicComponent C E (V c) := by
    intro c
    haveI := V_simple c
    exact eq_isotypicComponent_of_le c.2 (V_le c)
  refine ⟨V, V_simple, V_le, ?_, ?_⟩
  · -- Irredundant: isomorphic representatives share an isotypic component.
    rintro c c' ⟨e⟩
    have h_eq : isotypicComponent C E (V c) = isotypicComponent C E (V c') :=
      e.isotypicComponent_eq
    have hc : (c.1 : Submodule C E) = c'.1 := by rw [V_spec c, V_spec c']; exact h_eq
    exact Subtype.ext hc
  · -- Exhaustive: every simple `C`-module is one of the `V c`.
    intro S _ _ _
    obtain ⟨W, hW_simple, ⟨eSW⟩⟩ := exists_simpleSubmodule_iso_of_faithful k E C S
    haveI := hW_simple
    set c : isotypicComponents C E := ⟨isotypicComponent C E W, ⟨W, hW_simple, rfl⟩⟩ with hc
    haveI := V_simple c
    -- `isotypicComponent C E (V c) = c.1 = isotypicComponent C E W`.
    have hcomp : isotypicComponent C E (V c) = isotypicComponent C E W := (V_spec c).symm
    have hWle : W ≤ isotypicComponent C E (V c) := by
      rw [hcomp]; exact Submodule.le_isotypicComponent W
    obtain ⟨eWV⟩ :=
      isIsotypicOfType_submodule_iff.mp
        (IsIsotypicOfType.isotypicComponent C E (V c)) W hWle
    exact ⟨c, ⟨eSW.trans eWV⟩⟩

omit [Module.Finite k E] in
/-- **A-family exhaustiveness (Double Centralizer Theorem 5.18.1(iii)).**

Every simple `A`-module is isomorphic to a simple `A`-submodule of `E`, i.e. is
one of the `Vᵢ` appearing in the bimodule decomposition
`Theorem5_18_1_bimodule_decomposition_explicit`. Together with the pairwise
non-isomorphism of the `Vᵢ` proved there, this shows `{Vᵢ}` is the complete list
of simple `A`-modules. -/
theorem Theorem5_18_1_A_family_exhaustive
    (A : Subalgebra k (Module.End k E)) [IsSemisimpleRing A] [FaithfulSMul A E]
    (S : Type w) [AddCommGroup S] [Module A S] [IsSimpleModule A S] :
    ∃ W : Submodule A E, IsSimpleModule A W ∧ Nonempty (S ≃ₗ[A] W) :=
  exists_simpleSubmodule_iso_of_faithful k E A S

/-- **B-family exhaustiveness (Double Centralizer Theorem 5.18.1(iii)).**

With `B = centralizer(A)` (semisimple by `Theorem5_18_1_commutant_semisimple`),
every simple `B`-module is isomorphic to a simple `B`-submodule of `E`. Together
with the multiplicity-space distinctness
(`MultiplicitySpaceBiduality.multiplicitySpace_Cdistinct`) and the biduality
correspondence, this shows the `B`-simples `{Lᵢ = Hom_A(Vᵢ, E)}` form the
complete list of simple `B`-modules. -/
theorem Theorem5_18_1_B_family_exhaustive
    (A : Subalgebra k (Module.End k E)) [IsSemisimpleRing A] [FaithfulSMul A E]
    (T : Type w)
    [AddCommGroup T]
    [Module (↥(Subalgebra.centralizer k (A : Set (Module.End k E)))) T]
    [IsSimpleModule (↥(Subalgebra.centralizer k (A : Set (Module.End k E)))) T] :
    ∃ W : Submodule (↥(Subalgebra.centralizer k (A : Set (Module.End k E)))) E,
      IsSimpleModule (↥(Subalgebra.centralizer k (A : Set (Module.End k E)))) W ∧
      Nonempty (T ≃ₗ[↥(Subalgebra.centralizer k (A : Set (Module.End k E)))] W) := by
  haveI : IsSemisimpleRing (↥(Subalgebra.centralizer k (A : Set (Module.End k E)))) :=
    Theorem5_18_1_commutant_semisimple k E A
  exact exists_simpleSubmodule_iso_of_faithful k E
    (Subalgebra.centralizer k (A : Set (Module.End k E))) T

omit [Module.Finite k E] in
/-- **The `A`-family `{Vᵢ}` is a complete irredundant list of simple
`A`-modules.** Indexed by the isotypic components of `E`, the chosen simple
submodules `V c ≤ c` are pairwise non-isomorphic and exhaust the simple
`A`-modules up to isomorphism. This is the strong (indexed) form of
`Theorem5_18_1_A_family_exhaustive`. -/
theorem Theorem5_18_1_A_classification
    (A : Subalgebra k (Module.End k E)) [IsSemisimpleRing A] [FaithfulSMul A E] :
    ∃ (V : isotypicComponents A E → Submodule A E) (_ : ∀ c, IsSimpleModule A (V c)),
      (∀ c, (V c : Submodule A E) ≤ (c : Submodule A E)) ∧
      (∀ c c', Nonempty (↥(V c) ≃ₗ[A] ↥(V c')) → c = c') ∧
      ∀ (S : Type w) [AddCommGroup S] [Module A S] [IsSimpleModule A S],
        ∃ c, Nonempty (S ≃ₗ[A] ↥(V c)) :=
  simpleModule_classification_of_semisimple k E A

/-- **The `B`-family is a complete irredundant list of simple `B`-modules**
(`B = centralizer(A)`). Indexed by the isotypic components of `E` over `B`, the
chosen simple `B`-submodules `W c ≤ c` are pairwise non-isomorphic and exhaust
the simple `B`-modules. This is the strong (indexed) form of
`Theorem5_18_1_B_family_exhaustive`. Identifying these `B`-submodules with the
multiplicity spaces `Hom_A(Vᵢ, E)` is handled by the biduality correspondence
(`MultiplicitySpaceBiduality`). -/
theorem Theorem5_18_1_B_classification
    (A : Subalgebra k (Module.End k E)) [IsSemisimpleRing A] [FaithfulSMul A E] :
    ∃ (W : isotypicComponents (Subalgebra.centralizer k (A : Set (Module.End k E))) E →
          Submodule (↥(Subalgebra.centralizer k (A : Set (Module.End k E)))) E)
        (_ : ∀ c, IsSimpleModule
          (↥(Subalgebra.centralizer k (A : Set (Module.End k E)))) (W c)),
      (∀ c, (W c : Submodule (↥(Subalgebra.centralizer k (A : Set (Module.End k E)))) E) ≤
          (c : Submodule (↥(Subalgebra.centralizer k (A : Set (Module.End k E)))) E)) ∧
      (∀ c c', Nonempty
          (↥(W c) ≃ₗ[↥(Subalgebra.centralizer k (A : Set (Module.End k E)))] ↥(W c')) → c = c') ∧
      ∀ (T : Type w) [AddCommGroup T]
        [Module (↥(Subalgebra.centralizer k (A : Set (Module.End k E)))) T]
        [IsSimpleModule (↥(Subalgebra.centralizer k (A : Set (Module.End k E)))) T],
        ∃ c, Nonempty
          (T ≃ₗ[↥(Subalgebra.centralizer k (A : Set (Module.End k E)))] ↥(W c)) := by
  haveI : IsSemisimpleRing (↥(Subalgebra.centralizer k (A : Set (Module.End k E)))) :=
    Theorem5_18_1_commutant_semisimple k E A
  exact simpleModule_classification_of_semisimple k E
    (Subalgebra.centralizer k (A : Set (Module.End k E)))

end Etingof
