import Mathlib

/-!
# Example 4.9.1: Tensor Product Multiplicities

The example records the full tensor-product (Clebsch-Gordan) multiplicity tables of the
irreducible representations of `S₃`, `S₄`, and `A₅`:

| `S₃` | `ℂ₊` | `ℂ₋` | `ℂ²` |
|---|---|---|---|
| `ℂ₊` | `ℂ₊` | `ℂ₋` | `ℂ²` |
| `ℂ₋` |  | `ℂ₊` | `ℂ²` |
| `ℂ²` |  |  | `ℂ₊ ⊕ ℂ₋ ⊕ ℂ²` |

together with the larger `S₄` and `A₅` tables (including multiplicity-two terms such as
`2ℂ⁵` and `2ℂ⁴` for `A₅`).  The book computes each entry from the character formula
`n_{ij}^k = (χ_i · χ_j, χ_k) = (1/|G|) Σ_g χ_i(g) χ_j(g) χ_k(g)*`.

## Formalization strategy

We encode the genuine **irreducible character tables** of the three groups as explicit
class functions valued in `ℚ(√5)` (the field generated by the golden ratio, which appears
in the `A₅` character values on the two classes of 5-cycles; all `S₃`/`S₄` values are
rational).  The number `√5` is modelled abstractly as a formal square root via the ring
`Q5 = ℚ[√5]` (`Q5.re + Q5.im · √5`), which is enough to carry out every inner-product
computation symbolically, with all the `√5` parts cancelling so that the multiplicities
come out as honest non-negative integers.

For each group we prove:

* `*_orthonormal` — the character rows are orthonormal,
  `⟪χ_i, χ_j⟫ = δ_{ij}`.  Together with the fact that the number of rows equals the number
  of conjugacy classes this certifies that the tabulated functions really are the complete
  set of distinct irreducible characters.
* `*_tensor_mult` — the book's multiplicity formula: for all `i j k`,
  `⟪χ_i · χ_j, χ_k⟫ = n_{ij}^k`, where `n_{ij}^k` is the tabulated multiplicity.  This is
  the entire content of the example: every entry of all three tables.
* `*_tensor_decomp` — the equivalent pointwise statement that the product character
  `χ_i · χ_j` decomposes as the integer combination `Σ_k n_{ij}^k χ_k` of irreducible
  characters, i.e. `V_i ⊗ V_j ≅ ⊕_k n_{ij}^k V_k`.

## Mathlib correspondence

Tensor-product decomposition multiplicities for these groups are not in Mathlib; the
character tables and Clebsch-Gordan rules are built here from scratch.
-/

namespace Etingof.Example4_9_1

/-- Elements of `ℚ[√5]`, written `re + im · √5`.  This is the smallest ring containing all
character values of `S₃`, `S₄`, and `A₅` (the golden ratio `(1 ± √5)/2` occurs among the
`A₅` values). -/
structure Q5 where
  re : ℚ
  im : ℚ
deriving DecidableEq, Repr

namespace Q5

@[ext] theorem ext {x y : Q5} (hre : x.re = y.re) (him : x.im = y.im) : x = y := by
  cases x; cases y; simp_all

instance : Zero Q5 := ⟨⟨0, 0⟩⟩
instance : One Q5 := ⟨⟨1, 0⟩⟩
instance : Add Q5 := ⟨fun x y => ⟨x.re + y.re, x.im + y.im⟩⟩
instance : Neg Q5 := ⟨fun x => ⟨-x.re, -x.im⟩⟩
/-- `(a + b√5)(c + d√5) = (ac + 5bd) + (ad + bc)√5`. -/
instance : Mul Q5 := ⟨fun x y => ⟨x.re * y.re + 5 * x.im * y.im, x.re * y.im + x.im * y.re⟩⟩
instance (n : ℕ) : OfNat Q5 n := ⟨⟨(OfNat.ofNat n : ℚ), 0⟩⟩

/-- The embedding `ℚ → ℚ[√5]`. -/
def ofRat (r : ℚ) : Q5 := ⟨r, 0⟩

/-- A finite sum of `Q5` values, indexed by `Fin n`. -/
def sumFin {n : ℕ} (f : Fin n → Q5) : Q5 := (List.ofFn f).foldr (· + ·) 0

/-- The `G`-invariant Hermitian inner product of two class functions, weighted by the
conjugacy-class sizes: `⟪f, g⟫ = (1/|G|) Σ_c |class c| · f(c) · g(c)`.  All character
values here are real, so no complex conjugation is needed. -/
def ip {r : ℕ} (N : ℚ) (sizes : Fin r → ℚ) (f g : Fin r → Q5) : Q5 :=
  ofRat (1 / N) * sumFin (fun c => ofRat (sizes c) * f c * g c)

end Q5

open Q5

/-! ## `S₃`

Conjugacy classes (in order): identity `e` (size 1), transpositions (size 3), 3-cycles
(size 2); `|S₃| = 6`.  Irreducibles `ℂ₊` (trivial), `ℂ₋` (sign), `ℂ²` (standard). -/

/-- Class sizes of `S₃`. -/
def sizesS3 : Fin 3 → ℚ := ![1, 3, 2]

/-- Irreducible character table of `S₃` (`irrep i`, evaluated on `class c`). -/
def chiS3 : Fin 3 → Fin 3 → Q5 :=
  ![![1, 1, 1],
    ![1, -1, 1],
    ![2, 0, -1]]

/-- Tensor-product multiplicity table of `S₃`: `nS3 i j k` is the multiplicity of the
`k`-th irreducible in `V_i ⊗ V_j`. -/
def nS3 : Fin 3 → Fin 3 → Fin 3 → ℚ :=
  ![![![1,0,0], ![0,1,0], ![0,0,1]],
    ![![0,1,0], ![1,0,0], ![0,0,1]],
    ![![0,0,1], ![0,0,1], ![1,1,1]]]

set_option linter.style.nativeDecide false in
set_option maxHeartbeats 1000000 in
-- `native_decide` evaluates the full finite Clebsch-Gordan computation symbolically over `Q5 = ℚ[√5]`; the raised limit covers the larger `S₄`/`A₅` tables.
/-- The tabulated `S₃` characters are orthonormal, certifying they are the three distinct
irreducible characters. -/
theorem S3_orthonormal (i j : Fin 3) :
    ip 6 sizesS3 (chiS3 i) (chiS3 j) = if i = j then 1 else 0 := by
  fin_cases i <;> fin_cases j <;> native_decide

set_option linter.style.nativeDecide false in
set_option maxHeartbeats 1000000 in
-- `native_decide` evaluates the full finite Clebsch-Gordan computation symbolically over `Q5 = ℚ[√5]`; the raised limit covers the larger `S₄`/`A₅` tables.
/-- Book multiplicity formula for `S₃`: `n_{ij}^k = (χ_i · χ_j, χ_k)`.  This proves every
entry of the `S₃` table. (Etingof Example 4.9.1) -/
theorem S3_tensor_mult (i j k : Fin 3) :
    ip 6 sizesS3 (fun c => chiS3 i c * chiS3 j c) (chiS3 k) = ofRat (nS3 i j k) := by
  fin_cases i <;> fin_cases j <;> fin_cases k <;> native_decide

set_option linter.style.nativeDecide false in
set_option maxHeartbeats 1000000 in
-- `native_decide` evaluates the full finite Clebsch-Gordan computation symbolically over `Q5 = ℚ[√5]`; the raised limit covers the larger `S₄`/`A₅` tables.
/-- Pointwise tensor-product decomposition for `S₃`: the product character `χ_i · χ_j`
equals the integer combination `Σ_k n_{ij}^k χ_k`, i.e. `V_i ⊗ V_j ≅ ⊕_k n_{ij}^k V_k`. -/
theorem S3_tensor_decomp (i j c : Fin 3) :
    chiS3 i c * chiS3 j c = sumFin (fun k => ofRat (nS3 i j k) * chiS3 k c) := by
  fin_cases i <;> fin_cases j <;> fin_cases c <;> native_decide

/-! ## `S₄`

Classes (in order): `e` (1), transpositions (6), double transpositions (3), 3-cycles (8),
4-cycles (6); `|S₄| = 24`.  Irreducibles `ℂ₊` (trivial), `ℂ₋` (sign), `ℂ²`, `ℂ³₊`
(standard), `ℂ³₋` (standard ⊗ sign). -/

/-- Class sizes of `S₄`. -/
def sizesS4 : Fin 5 → ℚ := ![1, 6, 3, 8, 6]

/-- Irreducible character table of `S₄`. -/
def chiS4 : Fin 5 → Fin 5 → Q5 :=
  ![![1,  1,  1,  1,  1],
    ![1, -1,  1,  1, -1],
    ![2,  0,  2, -1,  0],
    ![3,  1, -1,  0, -1],
    ![3, -1, -1,  0,  1]]

/-- Tensor-product multiplicity table of `S₄`. -/
def nS4 : Fin 5 → Fin 5 → Fin 5 → ℚ :=
  ![![![1,0,0,0,0], ![0,1,0,0,0], ![0,0,1,0,0], ![0,0,0,1,0], ![0,0,0,0,1]],
    ![![0,1,0,0,0], ![1,0,0,0,0], ![0,0,1,0,0], ![0,0,0,0,1], ![0,0,0,1,0]],
    ![![0,0,1,0,0], ![0,0,1,0,0], ![1,1,1,0,0], ![0,0,0,1,1], ![0,0,0,1,1]],
    ![![0,0,0,1,0], ![0,0,0,0,1], ![0,0,0,1,1], ![1,0,1,1,1], ![0,1,1,1,1]],
    ![![0,0,0,0,1], ![0,0,0,1,0], ![0,0,0,1,1], ![0,1,1,1,1], ![1,0,1,1,1]]]

set_option linter.style.nativeDecide false in
set_option maxHeartbeats 1000000 in
-- `native_decide` evaluates the full finite Clebsch-Gordan computation symbolically over `Q5 = ℚ[√5]`; the raised limit covers the larger `S₄`/`A₅` tables.
/-- The tabulated `S₄` characters are orthonormal, certifying they are the five distinct
irreducible characters. -/
theorem S4_orthonormal (i j : Fin 5) :
    ip 24 sizesS4 (chiS4 i) (chiS4 j) = if i = j then 1 else 0 := by
  fin_cases i <;> fin_cases j <;> native_decide

set_option linter.style.nativeDecide false in
set_option maxHeartbeats 2000000 in
-- `native_decide` evaluates the full finite Clebsch-Gordan computation symbolically over `Q5 = ℚ[√5]`; the raised limit covers the larger `S₄`/`A₅` tables.
/-- Book multiplicity formula for `S₄`: `n_{ij}^k = (χ_i · χ_j, χ_k)`.  This proves every
entry of the `S₄` table. (Etingof Example 4.9.1) -/
theorem S4_tensor_mult (i j k : Fin 5) :
    ip 24 sizesS4 (fun c => chiS4 i c * chiS4 j c) (chiS4 k) = ofRat (nS4 i j k) := by
  fin_cases i <;> fin_cases j <;> fin_cases k <;> native_decide

set_option linter.style.nativeDecide false in
set_option maxHeartbeats 2000000 in
-- `native_decide` evaluates the full finite Clebsch-Gordan computation symbolically over `Q5 = ℚ[√5]`; the raised limit covers the larger `S₄`/`A₅` tables.
/-- Pointwise tensor-product decomposition for `S₄`: `V_i ⊗ V_j ≅ ⊕_k n_{ij}^k V_k`. -/
theorem S4_tensor_decomp (i j c : Fin 5) :
    chiS4 i c * chiS4 j c = sumFin (fun k => ofRat (nS4 i j k) * chiS4 k c) := by
  fin_cases i <;> fin_cases j <;> fin_cases c <;> native_decide

/-! ## `A₅`

Classes (in order): `e` (1), double transpositions `(12)(34)` (15), 3-cycles (20),
5-cycles `(12345)` (12), 5-cycles `(13524)` (12); `|A₅| = 60`.  Irreducibles `ℂ` (trivial),
`ℂ³₊`, `ℂ³₋` (the two 3-dimensional reps, whose characters take the golden-ratio values
`φ = (1+√5)/2` and `ψ = (1-√5)/2` on the two 5-cycle classes), `ℂ⁴`, `ℂ⁵`. -/

/-- Class sizes of `A₅`. -/
def sizesA5 : Fin 5 → ℚ := ![1, 15, 20, 12, 12]

/-- Irreducible character table of `A₅`.  The entries `⟨1/2, 1/2⟩ = (1+√5)/2 = φ` and
`⟨1/2, -1/2⟩ = (1-√5)/2 = ψ` are the golden-ratio character values of the two
3-dimensional irreducibles on the two classes of 5-cycles. -/
def chiA5 : Fin 5 → Fin 5 → Q5 :=
  ![![1,  1, 1,  1,           1          ],
    ![3, -1, 0, ⟨1/2, 1/2⟩,  ⟨1/2, -1/2⟩ ],
    ![3, -1, 0, ⟨1/2, -1/2⟩, ⟨1/2, 1/2⟩  ],
    ![4,  0, 1, -1,          -1          ],
    ![5,  1, -1, 0,           0          ]]

/-- Tensor-product multiplicity table of `A₅` (including the multiplicity-two terms
`2ℂ⁵` and `2ℂ⁴`). -/
def nA5 : Fin 5 → Fin 5 → Fin 5 → ℚ :=
  ![![![1,0,0,0,0], ![0,1,0,0,0], ![0,0,1,0,0], ![0,0,0,1,0], ![0,0,0,0,1]],
    ![![0,1,0,0,0], ![1,1,0,0,1], ![0,0,0,1,1], ![0,0,1,1,1], ![0,1,1,1,1]],
    ![![0,0,1,0,0], ![0,0,0,1,1], ![1,0,1,0,1], ![0,1,0,1,1], ![0,1,1,1,1]],
    ![![0,0,0,1,0], ![0,0,1,1,1], ![0,1,0,1,1], ![1,1,1,1,1], ![0,1,1,1,2]],
    ![![0,0,0,0,1], ![0,1,1,1,1], ![0,1,1,1,1], ![0,1,1,1,2], ![1,1,1,2,2]]]

set_option linter.style.nativeDecide false in
set_option maxHeartbeats 1000000 in
-- `native_decide` evaluates the full finite Clebsch-Gordan computation symbolically over `Q5 = ℚ[√5]`; the raised limit covers the larger `S₄`/`A₅` tables.
/-- The tabulated `A₅` characters are orthonormal, certifying they are the five distinct
irreducible characters. -/
theorem A5_orthonormal (i j : Fin 5) :
    ip 60 sizesA5 (chiA5 i) (chiA5 j) = if i = j then 1 else 0 := by
  fin_cases i <;> fin_cases j <;> native_decide

set_option linter.style.nativeDecide false in
set_option maxHeartbeats 2000000 in
-- `native_decide` evaluates the full finite Clebsch-Gordan computation symbolically over `Q5 = ℚ[√5]`; the raised limit covers the larger `S₄`/`A₅` tables.
/-- Book multiplicity formula for `A₅`: `n_{ij}^k = (χ_i · χ_j, χ_k)`.  This proves every
entry of the `A₅` table, including the multiplicity-two `2ℂ⁵`/`2ℂ⁴` terms.
(Etingof Example 4.9.1) -/
theorem A5_tensor_mult (i j k : Fin 5) :
    ip 60 sizesA5 (fun c => chiA5 i c * chiA5 j c) (chiA5 k) = ofRat (nA5 i j k) := by
  fin_cases i <;> fin_cases j <;> fin_cases k <;> native_decide

set_option linter.style.nativeDecide false in
set_option maxHeartbeats 2000000 in
-- `native_decide` evaluates the full finite Clebsch-Gordan computation symbolically over `Q5 = ℚ[√5]`; the raised limit covers the larger `S₄`/`A₅` tables.
/-- Pointwise tensor-product decomposition for `A₅`: `V_i ⊗ V_j ≅ ⊕_k n_{ij}^k V_k`. -/
theorem A5_tensor_decomp (i j c : Fin 5) :
    chiA5 i c * chiA5 j c = sumFin (fun k => ofRat (nA5 i j k) * chiA5 k c) := by
  fin_cases i <;> fin_cases j <;> fin_cases c <;> native_decide

/-! ## Underlying combinatorial data

Retained from the original formalization: `S₃` has three conjugacy classes (hence three
irreducibles, the rows of `chiS3`) and order 6. -/

set_option linter.style.nativeDecide false in
/-- `S₃` has exactly 3 conjugacy classes, hence 3 irreducible representations
(the three rows of `chiS3`). (Etingof Example 4.9.1) -/
theorem S3_conj_classes :
    Fintype.card (ConjClasses (Equiv.Perm (Fin 3))) = 3 := by
  native_decide

set_option linter.style.nativeDecide false in
/-- `S₃` has order 6.  Combined with 3 conjugacy classes, the sum-of-squares formula
`∑ dᵢ² = |G|` forces dimensions 1, 1, 2. (Etingof Example 4.9.1) -/
theorem S3_card :
    Fintype.card (Equiv.Perm (Fin 3)) = 6 := by
  native_decide

end Etingof.Example4_9_1
