import Mathlib

/-!
# Problem 4.12.8: classification of finite subgroups of `SO(3)` and `SU(2)`

**Problem 4.12.8.** It is known that the classification of finite subgroups of `SO(3)` is as
follows:

1. the cyclic group `ℤ/nℤ`, `n ≥ 1`, generated by a rotation by `2π/n` around an axis;
2. the dihedral group `Dₙ` of order `2n`, `n ≥ 2`;
3. the group of rotations of a regular tetrahedron (`A₄`);
4. the group of rotations of a cube or regular octahedron (`S₄`);
5. the group of rotations of a regular dodecahedron or icosahedron (`A₅`).

(a) Derive this classification. (Hint: let `G` be a finite subgroup of `SO(3)`, acting on the
unit sphere; a *pole* is a point fixed by a nontrivial element. Every nontrivial element fixes
a unique pair of opposite poles, the stabilizer of a pole is cyclic of some order `m`, and
counting nontrivial elements gives `2(1 - 1/n) = ∑ᵢ (1 - 1/mᵢ)`, whose solutions yield the
list above.)

(b) Using this classification, classify finite subgroups of `SU(2)` (use the homomorphism
`SU(2) → SO(3)`).

## Formalization

`SO(3)` is `Matrix.specialOrthogonalGroup (Fin 3) ℝ` and `SU(2)` is
`Matrix.specialUnitaryGroup (Fin 2) ℂ`. Statements (faithful signatures, `sorry` proofs — a
statement pass):

* **(a)** `so3_finite_subgroup_classification`: every finite subgroup `G ≤ SO(3)` is either
  cyclic, dihedral (`≃* DihedralGroup n`), or isomorphic to `A₄ = alternatingGroup (Fin 4)`,
  `S₄ = Equiv.Perm (Fin 4)`, or `A₅ = alternatingGroup (Fin 5)`. (The pole-counting identity
  `2(1 - 1/n) = ∑ᵢ (1 - 1/mᵢ)` is the method; it is recorded in this docstring rather than
  formalized separately.)
* **(b)** `su2_finite_subgroup_double_cover`: via a `2`-to-`1` homomorphism `h : SU(2) → SO(3)`
  with kernel `{±1}`, any finite subgroup `H ≤ SU(2)` has image `h(H)` a finite subgroup of
  `SO(3)` (classified by (a)), and `|H| = |h(H)|` or `|H| = 2·|h(H)|` according to whether `H`
  contains `-1`. The corresponding subgroups of `SU(2)` are the cyclic, binary dihedral, and
  binary tetrahedral/octahedral/icosahedral groups (recorded here in the docstring).
-/

open Matrix

namespace Etingof.Problem4_12_8

/-- **Rotation axis (part (a), step i).** Every element `g` of `SO(3)` fixes a nonzero vector —
the axis of rotation, i.e. `1` is an eigenvalue of `g`.

The proof is the elementary `det(g - 1) = 0` computation, needing no eigenvalue theory: from
orthogonality (`gᵀ g = 1`) and `det g = 1`,
`det(g - 1) = det gᵀ · det(g - 1) = det(gᵀ (g - 1)) = det(1 - gᵀ) = det((1 - g)ᵀ) = det(1 - g)
= (-1)³ det(g - 1) = -det(g - 1)`, hence `det(g - 1) = 0`, so `g - 1` is singular and has a
nonzero kernel vector `v` with `g *ᵥ v = v`. -/
theorem exists_fixed_vector (g : specialOrthogonalGroup (Fin 3) ℝ) (_hg : g ≠ 1) :
    ∃ v : Fin 3 → ℝ, v ≠ 0 ∧ (g : Matrix (Fin 3) (Fin 3) ℝ) *ᵥ v = v := by
  set M : Matrix (Fin 3) (Fin 3) ℝ := (g : Matrix (Fin 3) (Fin 3) ℝ) with hM
  obtain ⟨hortho, hdet⟩ := mem_specialOrthogonalGroup_iff.mp (SetLike.coe_mem g)
  have hMtM : Mᵀ * M = 1 := (mem_orthogonalGroup_iff' (Fin 3) ℝ).mp hortho
  have hdetT : Mᵀ.det = 1 := by rw [det_transpose]; exact hdet
  -- `det (M - 1) = 0`, obtained from `M - 1 = -(1 - M)` and orthogonality.
  have hkey : (M - 1).det = 0 := by
    have e1 : (M - 1).det = (1 - Mᵀ).det := by
      have hprod : Mᵀ * (M - 1) = 1 - Mᵀ := by rw [mul_sub, mul_one, hMtM]
      calc (M - 1).det = Mᵀ.det * (M - 1).det := by rw [hdetT, one_mul]
        _ = (Mᵀ * (M - 1)).det := (det_mul _ _).symm
        _ = (1 - Mᵀ).det := by rw [hprod]
    have e2 : (1 - Mᵀ).det = (1 - M).det := by
      rw [show (1 : Matrix (Fin 3) (Fin 3) ℝ) - Mᵀ = (1 - M)ᵀ by
        rw [transpose_sub, transpose_one], det_transpose]
    have e3 : (1 - M).det = -((M - 1).det) := by
      rw [show (1 : Matrix (Fin 3) (Fin 3) ℝ) - M = -(M - 1) by abel, det_neg,
        Fintype.card_fin]
      ring
    have hself : (M - 1).det = -((M - 1).det) := e1.trans (e2.trans e3)
    linarith
  -- A singular matrix has a nonzero vector in its kernel.
  obtain ⟨v, hv0, hMv⟩ := Matrix.exists_mulVec_eq_zero_iff.mpr hkey
  refine ⟨v, hv0, ?_⟩
  rw [sub_mulVec, one_mulVec, sub_eq_zero] at hMv
  exact hMv

/-- **Part (a).** Every finite subgroup `G` of `SO(3)` is isomorphic to one of: a cyclic group
`ℤ/nℤ`, a dihedral group `Dₙ`, the tetrahedral group `A₄`, the octahedral group `S₄`, or the
icosahedral group `A₅`. -/
theorem so3_finite_subgroup_classification
    (G : Subgroup (specialOrthogonalGroup (Fin 3) ℝ)) [Finite G] :
    IsCyclic G ∨
    (∃ n : ℕ, Nonempty (G ≃* DihedralGroup n)) ∨
    Nonempty (G ≃* alternatingGroup (Fin 4)) ∨
    Nonempty (G ≃* Equiv.Perm (Fin 4)) ∨
    Nonempty (G ≃* alternatingGroup (Fin 5)) := by
  sorry

/-- **Part (b).** Fix a surjective homomorphism `h : SU(2) → SO(3)` with kernel `{±1}` (the
double cover). For any finite subgroup `H ≤ SU(2)`, its image `h(H)` is a finite subgroup of
`SO(3)` — hence classified by part (a) — and `H` is a double cover of `h(H)` exactly when it
contains `-1`: `|H| = 2·|h(H)|` if `-1 ∈ H`, and `|H| = |h(H)|` otherwise. -/
theorem su2_finite_subgroup_double_cover
    (h : specialUnitaryGroup (Fin 2) ℂ →* specialOrthogonalGroup (Fin 3) ℝ)
    (hker : ∀ A : specialUnitaryGroup (Fin 2) ℂ,
      A ∈ h.ker ↔ ((A : Matrix (Fin 2) (Fin 2) ℂ) = 1 ∨
        (A : Matrix (Fin 2) (Fin 2) ℂ) = -1))
    (H : Subgroup (specialUnitaryGroup (Fin 2) ℂ)) [Finite H] :
    ((∃ A ∈ H, (A : Matrix (Fin 2) (Fin 2) ℂ) = -1) →
        Nat.card H = 2 * Nat.card (H.map h)) ∧
    ((∀ A ∈ H, (A : Matrix (Fin 2) (Fin 2) ℂ) ≠ -1) →
        Nat.card H = Nat.card (H.map h)) := by
  -- Restrict `h` to `H`.
  set h' : H →* specialOrthogonalGroup (Fin 3) ℝ := h.comp H.subtype with hh'
  -- The range of `h'` is exactly the image subgroup `H.map h`.
  have hrange : h'.range = H.map h := by
    rw [hh', MonoidHom.range_eq_map, ← Subgroup.map_map, ← MonoidHom.range_eq_map,
      Subgroup.range_subtype]
  -- The composite `H → SU(2) → Matrix` is injective (both coercions are `Subtype.val`).
  have hinj : ∀ a b : H,
      ((a : specialUnitaryGroup (Fin 2) ℂ) : Matrix (Fin 2) (Fin 2) ℂ) =
        ((b : specialUnitaryGroup (Fin 2) ℂ) : Matrix (Fin 2) (Fin 2) ℂ) → a = b := by
    intro a b hab
    apply Subtype.ext
    apply Subtype.ext
    exact hab
  -- Membership in the kernel of `h'` is the `±1` condition on the underlying matrix.
  have hmem : ∀ x : H, x ∈ h'.ker ↔
      ((x : specialUnitaryGroup (Fin 2) ℂ) : Matrix (Fin 2) (Fin 2) ℂ) = 1 ∨
      ((x : specialUnitaryGroup (Fin 2) ℂ) : Matrix (Fin 2) (Fin 2) ℂ) = -1 := by
    intro x
    rw [MonoidHom.mem_ker, hh', MonoidHom.comp_apply, Subgroup.coe_subtype,
      ← MonoidHom.mem_ker, hker]
  -- The matrix of the identity of `H` is `1`.
  have h1mat : (((1 : H) : specialUnitaryGroup (Fin 2) ℂ) :
      Matrix (Fin 2) (Fin 2) ℂ) = 1 := by simp
  -- An element of the kernel with matrix `1` is the identity.
  have key1 : ∀ y : H,
      ((y : specialUnitaryGroup (Fin 2) ℂ) : Matrix (Fin 2) (Fin 2) ℂ) = 1 → y = 1 := by
    intro y hy
    apply hinj
    rw [hy]
    exact h1mat.symm
  -- `1 ≠ -1` as `2 × 2` complex matrices.
  have hne : (1 : Matrix (Fin 2) (Fin 2) ℂ) ≠ -1 := by
    intro he
    have h00 := congrFun (congrFun he 0) 0
    rw [Matrix.one_apply_eq, Matrix.neg_apply, Matrix.one_apply_eq] at h00
    norm_num at h00
  -- Lagrange / first isomorphism theorem: `|H| = |image| · |kernel|`.
  have hcount : Nat.card H = Nat.card (H.map h) * Nat.card h'.ker := by
    have hq : Nat.card (H ⧸ h'.ker) = Nat.card (H.map h) := by
      rw [Nat.card_congr (QuotientGroup.quotientKerEquivRange h').toEquiv, hrange]
    rw [Subgroup.card_eq_card_quotient_mul_card_subgroup h'.ker, hq]
  refine ⟨?_, ?_⟩
  · -- Case `-1 ∈ H`: the kernel has exactly two elements, so `|H| = 2 · |image|`.
    rintro ⟨A₀, hA₀H, hA₀⟩
    let g : H := ⟨A₀, hA₀H⟩
    have hg_mat : ((g : specialUnitaryGroup (Fin 2) ℂ) :
        Matrix (Fin 2) (Fin 2) ℂ) = -1 := hA₀
    have hgker : g ∈ h'.ker := (hmem g).mpr (Or.inr hg_mat)
    -- Every kernel element with matrix `-1` equals `g`.
    have keyg : ∀ y : H,
        ((y : specialUnitaryGroup (Fin 2) ℂ) : Matrix (Fin 2) (Fin 2) ℂ) = -1 → y = g := by
      intro y hy
      apply hinj
      rw [hy]
      exact hg_mat.symm
    have hcard : Nat.card h'.ker = 2 := by
      rw [Nat.card_eq_two_iff]
      refine ⟨⟨1, (h'.ker).one_mem⟩, ⟨g, hgker⟩, ?_, ?_⟩
      · intro he
        have h1g : (1 : H) = g := congrArg Subtype.val he
        have e1 : (((1 : H) : specialUnitaryGroup (Fin 2) ℂ) :
            Matrix (Fin 2) (Fin 2) ℂ) =
            ((g : specialUnitaryGroup (Fin 2) ℂ) : Matrix (Fin 2) (Fin 2) ℂ) := by rw [h1g]
        rw [h1mat, hg_mat] at e1
        exact hne e1
      · rw [Set.eq_univ_iff_forall]
        rintro ⟨y, hyk⟩
        have hy2 := (hmem y).mp hyk
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff]
        rcases hy2 with hy1 | hy1
        · exact Or.inl (Subtype.ext (key1 y hy1))
        · exact Or.inr (Subtype.ext (keyg y hy1))
    rw [hcount, hcard, mul_comm]
  · -- Case `-1 ∉ H`: the kernel is trivial, so `|H| = |image|`.
    intro hno
    have hbot : h'.ker = ⊥ := by
      rw [Subgroup.eq_bot_iff_forall]
      intro x hx
      rcases (hmem x).mp hx with h1 | h1
      · exact key1 x h1
      · exact absurd h1 (hno (x : specialUnitaryGroup (Fin 2) ℂ) x.2)
    rw [hcount, hbot, Subgroup.card_bot, mul_one]

end Etingof.Problem4_12_8
