import VersoManual

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter9.Problem932

#doc (Manual) "Simple modules, projective modules, and Cartan matrix of a specific algebra" =>

# Simple modules, projective modules, and Cartan matrix of a specific algebra
%%%
tag := "Chapter9/Problem9.3.2"
number := false
%%%

*Problem 9.3.2.* Let $`A` be the algebra over complex numbers generated by elements $`g, x` with defining relations $`gx = -xg`, $`x^2 = 0`, $`g^2 = 1`. Find the simple modules, the indecomposable projective modules, and the Cartan matrix of $`A`.
