import EtingofRepresentationTheory.Chapter2.Definition2_9_9
import EtingofRepresentationTheory.Chapter2.Discussion_2_6
import EtingofRepresentationTheory.Chapter2.Problem2_11_3_SymPowBasis

/-!
# Definition 2.12.1: Symmetric Algebra, Exterior Algebra, and Universal Enveloping Algebra

(i) The **symmetric algebra** SV of V is the quotient of TV by the ideal generated by
v ⊗ w - w ⊗ v.

(ii) The **exterior algebra** ∧V of V is the quotient of TV by the ideal generated by
v ⊗ v.

(iii) If V is a Lie algebra, the **universal enveloping algebra** U(V) of V is the quotient
of TV by the ideal generated by v ⊗ w - w ⊗ v - [v, w].

## Mathlib correspondence

The coordinate-free constructions are Mathlib's `SymmetricAlgebra R M`,
`ExteriorAlgebra R M`, and `UniversalEnvelopingAlgebra R L`.  For the enveloping algebra this
file also constructs the book's earlier basis-and-structure-constants presentation and proves it
equivalent to Mathlib's coordinate-free construction.  Thus Definition 2.9.9, Remark 2.9.10, and
part (iii) of this definition are connected by an actual algebra equivalence rather than merely
being assigned the same Lean type.  We also record the basis identifications and the final
decompositions into the symmetric and exterior powers constructed in Problem 2.11.3.
-/

/-- The symmetric algebra of a module, in the sense of Etingof Definition 2.12.1 (i).
This is `SymmetricAlgebra k V` in Mathlib. -/
abbrev Etingof.SymmetricAlgebraDef (k : Type*) (V : Type*) [CommRing k]
    [AddCommGroup V] [Module k V] :=
  SymmetricAlgebra k V

/-- The exterior algebra of a module, in the sense of Etingof Definition 2.12.1 (ii).
This is `ExteriorAlgebra k V` in Mathlib. -/
abbrev Etingof.ExteriorAlgebraDef (k : Type*) (V : Type*) [CommRing k]
    [AddCommGroup V] [Module k V] :=
  ExteriorAlgebra k V

/-- The universal enveloping algebra (coordinate-free), in the sense of
Etingof Definition 2.12.1 (iii). This is `UniversalEnvelopingAlgebra k L` in Mathlib. -/
abbrev Etingof.UniversalEnvelopingAlgebraCoordFree (k : Type*) (L : Type*) [CommRing k]
    [LieRing L] [LieAlgebra k L] :=
  UniversalEnvelopingAlgebra k L
namespace Etingof

open scoped DirectSum TensorProduct

universe u v w

variable (k : Type u) [Field k]
variable (L : Type v) [LieRing L] [LieAlgebra k L]
variable {ι : Type w} (b : Module.Basis ι k L)

attribute [local instance 100] LieRing.ofAssociativeRing

/-! ## The defining quotient relations -/

/-- The canonical generators of the symmetric algebra commute, the relation imposed in part (i). -/
theorem symmetricAlgebra_generators_commute (V : Type v) [AddCommGroup V] [Module k V]
    (x y : V) :
    SymmetricAlgebra.ι k V x * SymmetricAlgebra.ι k V y =
      SymmetricAlgebra.ι k V y * SymmetricAlgebra.ι k V x :=
  mul_comm _ _

/-- The canonical generators of the exterior algebra square to zero, the relation imposed in
part (ii). -/
theorem exteriorAlgebra_generator_sq_zero (V : Type v) [AddCommGroup V] [Module k V] (x : V) :
    ExteriorAlgebra.ι k x * ExteriorAlgebra.ι k x = 0 :=
  ExteriorAlgebra.ι_sq_zero x

/-- The canonical generators of the universal enveloping algebra satisfy the relation from
part (iii). -/
theorem universalEnvelopingAlgebra_generator_relation (x y : L) :
    UniversalEnvelopingAlgebra.ι k x * UniversalEnvelopingAlgebra.ι k y -
        UniversalEnvelopingAlgebra.ι k y * UniversalEnvelopingAlgebra.ι k x =
      UniversalEnvelopingAlgebra.ι k ⁅x, y⁆ := by
  rw [← LieRing.of_associative_ring_bracket, ← LieHom.map_lie]

/-! ## Identifications after choosing a basis -/

/-- A basis identifies the symmetric algebra with the polynomial algebra on the basis indices. -/
noncomputable def symmetricAlgebraEquivPolynomial (V : Type v) [AddCommGroup V] [Module k V]
    {ι : Type w} (b : Module.Basis ι k V) :
    SymmetricAlgebraDef k V ≃ₐ[k] MvPolynomial ι k :=
  SymmetricAlgebra.equivMvPolynomial b

/-- The symmetric-algebra/polynomial identification sends a chosen basis vector to the
corresponding polynomial variable. -/
@[simp] theorem symmetricAlgebraEquivPolynomial_ι (V : Type v) [AddCommGroup V] [Module k V]
    {ι : Type w} (b : Module.Basis ι k V) (i : ι) :
    symmetricAlgebraEquivPolynomial k V b (SymmetricAlgebra.ι k V (b i)) =
      MvPolynomial.X i :=
  SymmetricAlgebra.equivMvPolynomial_ι_apply b i

/-- A basis identifies the exterior algebra with the exterior algebra on the free coordinate
module on its basis indices. -/
noncomputable def exteriorAlgebraEquivBasisModule (V : Type v) [AddCommGroup V] [Module k V]
    {ι : Type w} (b : Module.Basis ι k V) :
    ExteriorAlgebraDef k V ≃ₐ[k] ExteriorAlgebra k (ι →₀ k) :=
  CliffordAlgebra.equivOfIsometry
    ({ toLinearEquiv := b.repr, map_app' := fun _ => rfl } :
      QuadraticMap.IsometryEquiv (0 : QuadraticForm k V) (0 : QuadraticForm k (ι →₀ k)))

/-- The exterior-algebra basis identification acts on generators by taking coordinates in the
chosen basis. -/
@[simp] theorem exteriorAlgebraEquivBasisModule_ι (V : Type v) [AddCommGroup V] [Module k V]
    {ι : Type w} (b : Module.Basis ι k V) (x : V) :
    exteriorAlgebraEquivBasisModule k V b (ExteriorAlgebra.ι k x) =
      ExteriorAlgebra.ι k (b.repr x) := by
  rw [exteriorAlgebraEquivBasisModule, CliffordAlgebra.equivOfIsometry_apply,
    CliffordAlgebra.map_apply_ι]
  rfl

/-! ## Decompositions into symmetric and exterior powers -/

/-- The monomial indices of a symmetric algebra split uniquely by total degree: a finitely
supported exponent vector is equivalently a degree together with a multiset of that cardinality. -/
noncomputable def symmetricMonomialDegreeEquiv (ι : Type w) :
    (ι →₀ ℕ) ≃ Σ n : ℕ, Sym ι n := by
  classical
  exact (Equiv.sigmaFiberEquiv (fun f : ι →₀ ℕ => f.sum fun _ m => m)).symm.trans
    (Equiv.sigmaCongrRight fun n => (Sym.equivNatSum ι n).symm)

/-- The book's decomposition `S(V) = ⨁ n, S^n(V)`.  The right-hand summands are the quotient
models of symmetric powers constructed in Problem 2.11.3.  A chosen basis identifies the monomial
basis of `S(V)`, grouped by total degree, with the corresponding bases of those quotients. -/
noncomputable def symmetricAlgebraEquivDirectSumSymmetricPowers
    (V : Type v) [AddCommGroup V] [Module k V] {ι : Type w} (b : Module.Basis ι k V) :
    SymmetricAlgebraDef k V ≃ₗ[k]
      ⨁ n : ℕ, Problem2_11_3.SymPow k V n :=
  b.symmetricAlgebra.repr ≪≫ₗ
    Finsupp.domLCongr (symmetricMonomialDegreeEquiv ι) ≪≫ₗ
    sigmaFinsuppLequivDFinsupp k ≪≫ₗ
    DFinsupp.mapRange.linearEquiv fun n => (Problem2_11_3.symPowBasis b n).repr.symm

/-- The book's decomposition `∧(V) = ⨁ n, ∧^n(V)`.  Mathlib's canonical grading gives the
direct sum of its exterior-power submodules, and the componentwise equivalences proved for
Problem 2.11.3 identify those with the book's quotient models. -/
noncomputable def exteriorAlgebraEquivDirectSumExteriorPowers
    (V : Type v) [AddCommGroup V] [Module k V] :
    ExteriorAlgebraDef k V ≃ₗ[k]
      ⨁ n : ℕ, Problem2_11_3.ExtPow k V n :=
  DirectSum.decomposeLinearEquiv (fun n : ℕ => ⋀[k]^n V) ≪≫ₗ
    DFinsupp.mapRange.linearEquiv fun n => Problem2_11_3.exteriorPowerEquiv n

/-- The defining relator
`X_i X_j - X_j X_i - ∑_r (b.repr ⁅b i, b j⁆) r • X_r` for the basis presentation of
the universal enveloping algebra.  The coordinate sum is a `Finsupp.sum`, so the index type need
not be finite. -/
noncomputable def ueaBasisRelator (ij : ι × ι) : FreeAlgebra k ι :=
  FreeAlgebra.ι k ij.1 * FreeAlgebra.ι k ij.2 -
    FreeAlgebra.ι k ij.2 * FreeAlgebra.ι k ij.1 -
      (b.repr ⁅b ij.1, b ij.2⁆).sum fun r a => a • FreeAlgebra.ι k r

/-- The basis-and-structure-constants presentation of the universal enveloping algebra from
Definition 2.9.9. -/
abbrev UEABasisPresentation :=
  PresentedAlgebra k ι (ι × ι) (ueaBasisRelator k L b)

/-- The homomorphism from the basis presentation to the coordinate-free enveloping algebra,
sending the generator indexed by `i` to the canonical image of `b i`. -/
noncomputable def ueaBasisToCoordFree :
    UEABasisPresentation k L b →ₐ[k] UniversalEnvelopingAlgebraCoordFree k L :=
  PresentedAlgebra.lift (ueaBasisRelator k L b)
    (fun i => UniversalEnvelopingAlgebra.ι k (b i)) (by
      rintro ⟨i, j⟩
      simp only [ueaBasisRelator, map_sub, map_mul, FreeAlgebra.lift_ι_apply]
      simp only [Finsupp.sum, map_sum, map_smul, FreeAlgebra.lift_ι_apply]
      have hbexp : (b.repr ⁅b i, b j⁆).sum (fun r a => a • b r) = ⁅b i, b j⁆ := by
        change Finsupp.linearCombination k b (b.repr ⁅b i, b j⁆) = ⁅b i, b j⁆
        rw [← Module.Basis.repr_symm_apply, b.repr.symm_apply_apply]
      rw [sub_eq_zero]
      symm
      calc
        ∑ r ∈ (b.repr ⁅b i, b j⁆).support,
            (b.repr ⁅b i, b j⁆) r • UniversalEnvelopingAlgebra.ι k (b r) =
            UniversalEnvelopingAlgebra.ι k
              ((b.repr ⁅b i, b j⁆).sum (fun r a => a • b r)) := by
          simp only [Finsupp.sum, map_sum, map_smul]
        _ = UniversalEnvelopingAlgebra.ι k ⁅b i, b j⁆ :=
          congrArg (UniversalEnvelopingAlgebra.ι k) hbexp
        _ = ⁅UniversalEnvelopingAlgebra.ι k (b i),
              UniversalEnvelopingAlgebra.ι k (b j)⁆ := LieHom.map_lie _ _ _
        _ = UniversalEnvelopingAlgebra.ι k (b i) *
              UniversalEnvelopingAlgebra.ι k (b j) -
              UniversalEnvelopingAlgebra.ι k (b j) *
                UniversalEnvelopingAlgebra.ι k (b i) :=
          LieRing.of_associative_ring_bracket _ _)

/-- The linear map from the Lie algebra into its basis presentation, obtained by expanding in the
chosen basis and sending basis vectors to the corresponding generators. -/
noncomputable def basisGenLinear : L →ₗ[k] UEABasisPresentation k L b :=
  (b.constr k) (PresentedAlgebra.gen (ueaBasisRelator k L b))

/-- The basis-generator linear map sends each basis vector to its named generator. -/
@[simp] theorem basisGenLinear_apply_basis (i : ι) :
    basisGenLinear k L b (b i) = PresentedAlgebra.gen (ueaBasisRelator k L b) i :=
  Module.Basis.constr_basis b k _ i

/-- The canonical Lie map into the basis presentation.  Preservation of brackets is precisely
the family of defining relations. -/
noncomputable def basisGenLie : L →ₗ⁅k⁆ UEABasisPresentation k L b :=
  { basisGenLinear k L b with
    map_lie' := by
      intro x y
      let lhs : L →ₗ[k] L →ₗ[k] UEABasisPresentation k L b :=
        LinearMap.mk₂ k (fun x y => basisGenLinear k L b ⁅x, y⁆)
          (by simp) (by simp) (by simp) (by simp)
      let rhs : L →ₗ[k] L →ₗ[k] UEABasisPresentation k L b :=
        LinearMap.mk₂ k (fun x y => ⁅basisGenLinear k L b x, basisGenLinear k L b y⁆)
          (by simp) (by simp) (by simp)
          (by
            intro c x y
            rw [map_smul]
            exact lie_smul c (basisGenLinear k L b x) (basisGenLinear k L b y))
      have hbilin : lhs = rhs := by
        apply Module.Basis.ext b
        intro i
        apply Module.Basis.ext b
        intro j
        change basisGenLinear k L b ⁅b i, b j⁆ =
          ⁅basisGenLinear k L b (b i), basisGenLinear k L b (b j)⁆
        rw [basisGenLinear_apply_basis, basisGenLinear_apply_basis,
          basisGenLinear, Module.Basis.constr_apply]
        have hrel := PresentedAlgebra.mk_rel (ueaBasisRelator k L b) (i, j)
        simp only [ueaBasisRelator, map_sub, map_mul,
          Finsupp.sum, map_sum, map_smul] at hrel
        rw [LieRing.of_associative_ring_bracket]
        exact (sub_eq_zero.mp hrel).symm
      exact congrArg (fun F => F x y) hbilin }

/-- The homomorphism from the coordinate-free enveloping algebra to the basis presentation,
induced by its universal property. -/
noncomputable def coordFreeToUeaBasis :
    UniversalEnvelopingAlgebraCoordFree k L →ₐ[k] UEABasisPresentation k L b :=
  UniversalEnvelopingAlgebra.lift k (basisGenLie k L b)

/-- Formula for the forward map on a named generator. -/
@[simp] theorem ueaBasisToCoordFree_gen (i : ι) :
    ueaBasisToCoordFree k L b (PresentedAlgebra.gen (ueaBasisRelator k L b) i) =
      UniversalEnvelopingAlgebra.ι k (b i) := by
  simp [ueaBasisToCoordFree]

/-- Formula for the inverse map on the canonical image of a Lie algebra element. -/
theorem coordFreeToUeaBasis_ι (x : L) :
    coordFreeToUeaBasis k L b (UniversalEnvelopingAlgebra.ι k x) =
      basisGenLinear k L b x := by
  rw [coordFreeToUeaBasis, UniversalEnvelopingAlgebra.lift_ι_apply]
  rfl

/-- The algebra equivalence promised by Remark 2.9.10 between Definition 2.9.9's chosen-basis
presentation and Definition 2.12.1's coordinate-free universal enveloping algebra. -/
noncomputable def ueaBasisAlgEquiv :
    UEABasisPresentation k L b ≃ₐ[k] UniversalEnvelopingAlgebraDef k L :=
  AlgEquiv.ofAlgHom (ueaBasisToCoordFree k L b) (coordFreeToUeaBasis k L b)
    (by
      apply UniversalEnvelopingAlgebra.hom_ext
      apply LieHom.ext
      intro x
      rw [LieHom.coe_comp, Function.comp_apply, AlgHom.coe_toLieHom, AlgHom.comp_apply,
        coordFreeToUeaBasis_ι]
      change ueaBasisToCoordFree k L b (basisGenLinear k L b x) = _
      rw [basisGenLinear, Module.Basis.constr_apply]
      simp only [Finsupp.sum, map_sum, map_smul, ueaBasisToCoordFree_gen]
      have hbexp : (b.repr x).sum (fun r a => a • b r) = x := by
        change Finsupp.linearCombination k b (b.repr x) = x
        rw [← Module.Basis.repr_symm_apply, b.repr.symm_apply_apply]
      calc
        ∑ r ∈ (b.repr x).support,
            (b.repr x) r • UniversalEnvelopingAlgebra.ι k (b r) =
            UniversalEnvelopingAlgebra.ι k
              ((b.repr x).sum (fun r a => a • b r)) := by
          simp only [Finsupp.sum, map_sum, map_smul]
        _ = UniversalEnvelopingAlgebra.ι k x :=
          congrArg (UniversalEnvelopingAlgebra.ι k) hbexp)
    (by
      apply PresentedAlgebra.hom_ext (ueaBasisRelator k L b)
      intro i
      rw [AlgHom.comp_apply, ueaBasisToCoordFree_gen, coordFreeToUeaBasis_ι,
        basisGenLinear_apply_basis]
      rfl)

/-- The forward homomorphism is uniquely characterized by its values on basis generators. -/
theorem ueaBasisToCoordFree_unique
    (F : UEABasisPresentation k L b →ₐ[k] UniversalEnvelopingAlgebraDef k L)
    (hF : ∀ i, F (PresentedAlgebra.gen (ueaBasisRelator k L b) i) =
      UniversalEnvelopingAlgebra.ι k (b i)) :
    F = ueaBasisToCoordFree k L b := by
  apply PresentedAlgebra.hom_ext (ueaBasisRelator k L b)
  intro i
  rw [hF, ueaBasisToCoordFree_gen]

/-- The inverse homomorphism is uniquely characterized by its values on the canonical image of
the Lie algebra. -/
theorem coordFreeToUeaBasis_unique
    (F : UniversalEnvelopingAlgebraCoordFree k L →ₐ[k] UEABasisPresentation k L b)
    (hF : ∀ x, F (UniversalEnvelopingAlgebra.ι k x) = basisGenLinear k L b x) :
    F = coordFreeToUeaBasis k L b := by
  apply UniversalEnvelopingAlgebra.hom_ext
  apply LieHom.ext
  intro x
  change F (UniversalEnvelopingAlgebra.ι k x) =
    coordFreeToUeaBasis k L b (UniversalEnvelopingAlgebra.ι k x)
  rw [hF, coordFreeToUeaBasis_ι]

end Etingof
