import EtingofRepresentationTheory.Chapter2.Definition2_3_4
import Mathlib.RingTheory.SimpleRing.Basic
import Mathlib.RingTheory.TwoSidedIdeal.Kernel
import Mathlib.RingTheory.TwoSidedIdeal.Operations

/-!
# Section 2.4: Ideals

This file records the dictionary used in §2.4 between Etingof's terminology and Mathlib:

* a left ideal of `A` is a submodule of the left regular representation;
* a right ideal of `A` is a submodule of the left regular representation of `Aᵐᵒᵖ`;
* a two-sided ideal is `TwoSidedIdeal A`;
* a simple nontrivial ring is expressed by `IsSimpleRing A`;
* generated left, right, and two-sided ideals are the appropriate spans.

For two-sided ideals, `TwoSidedIdeal.mem_span_iff_mem_addSubgroup_closure` is the precise
unital-ring version of the book's description as the additive span of products `a * s * b`.
-/

namespace Etingof.Discussion2_4

open scoped Pointwise

variable (A : Type*) [Ring A]

/-- A left ideal is a submodule of the left regular representation. -/
abbrev LeftIdeal := Submodule A A

/-- A right ideal is a submodule of the regular representation of the opposite ring. -/
abbrev RightIdeal := Submodule Aᵐᵒᵖ Aᵐᵒᵖ

/-- The book's two-sided ideals are Mathlib's `TwoSidedIdeal`. -/
abbrev Ideal := TwoSidedIdeal A

/-- The book's definition of a simple nonzero ring is Mathlib's `IsSimpleRing`. -/
abbrev IsSimple : Prop := IsSimpleRing A

/-- The zero two-sided ideal. -/
abbrev zeroIdeal : Ideal A := ⊥

/-- The whole ring as a two-sided ideal. -/
abbrev unitIdeal : Ideal A := ⊤

/-- A two-sided ideal viewed as a left ideal. -/
abbrev Ideal.toLeft (I : Ideal A) : LeftIdeal A := I.asIdeal

/-- A two-sided ideal viewed as a right ideal. -/
abbrev Ideal.toRight (I : Ideal A) : RightIdeal A := I.asIdealOpposite

/-- The left ideal generated by `S`. -/
abbrev leftGenerated (S : Set A) : LeftIdeal A := Submodule.span A S

/-- The right ideal generated by `S`, transported to the opposite ring. -/
abbrev rightGenerated (S : Set A) : RightIdeal A :=
  Submodule.span Aᵐᵒᵖ (MulOpposite.op '' S)

/-- The two-sided ideal generated by `S`. -/
abbrev generated (S : Set A) : Ideal A := TwoSidedIdeal.span S

/-- Left ideals and subrepresentations of the left regular representation are definitionally the
same objects. -/
theorem leftIdeal_eq_regularSubrepresentation :
    LeftIdeal A = Etingof.Subrepresentation A A := rfl

/-- Right ideals and subrepresentations of the regular representation of `Aᵐᵒᵖ` are
definitionally the same objects. -/
theorem rightIdeal_eq_op_regularSubrepresentation :
    RightIdeal A = Etingof.Subrepresentation Aᵐᵒᵖ Aᵐᵒᵖ := rfl

/-- Membership in a two-sided ideal agrees with membership after viewing it as a left ideal. -/
theorem mem_toLeft_iff {I : Ideal A} {x : A} : x ∈ I.toLeft ↔ x ∈ I :=
  TwoSidedIdeal.mem_asIdeal

/-- Membership in a two-sided ideal agrees with membership after viewing it as a right ideal. -/
@[simp]
theorem mem_toRight_iff {I : Ideal A} {x : Aᵐᵒᵖ} : x ∈ I.toRight ↔ x.unop ∈ I :=
  TwoSidedIdeal.mem_asIdealOpposite

/-- The generated left ideal is the smallest left ideal containing its generators. -/
theorem leftGenerated_le_iff {S : Set A} {I : LeftIdeal A} :
    leftGenerated A S ≤ I ↔ S ⊆ I := Submodule.span_le

/-- The generated right ideal is the smallest right ideal containing the opposite images of its
generators. -/
theorem rightGenerated_le_iff {S : Set A} {I : RightIdeal A} :
    rightGenerated A S ≤ I ↔ MulOpposite.op '' S ⊆ I := Submodule.span_le

/-- The generated two-sided ideal is the smallest two-sided ideal containing its generators. -/
theorem generated_le_iff {S : Set A} {I : Ideal A} :
    generated A S ≤ I ↔ S ⊆ I := TwoSidedIdeal.span_le

/-- In a unital ring, the two-sided ideal generated by `S` is the additive span of the elements
`a * s * b`. -/
theorem mem_generated_iff_mem_addSubgroup_closure {S : Set A} {x : A} :
    x ∈ generated A S ↔
      x ∈ AddSubgroup.closure ((Set.univ : Set A) * S * Set.univ) :=
  TwoSidedIdeal.mem_span_iff_mem_addSubgroup_closure

/-- The kernel of a ring homomorphism is a two-sided ideal, with the expected membership test. -/
theorem mem_ker_iff {B : Type*} [NonAssocSemiring B] (f : A →+* B) (x : A) :
    x ∈ TwoSidedIdeal.ker f ↔ f x = 0 := TwoSidedIdeal.mem_ker f

end Etingof.Discussion2_4
