import Mathlib.Algebra.Lie.Basic
import Mathlib.Algebra.Lie.Classical
import Mathlib.Algebra.Lie.OfAssociative
import Mathlib.Algebra.Lie.Sl2
import Mathlib.Algebra.Lie.UniversalEnveloping
import Mathlib.Algebra.FreeAlgebra

/-!
# Example 2.9.12: Universal Enveloping Algebra of sl(2)

The associative algebra `U(𝔰𝔩(2))` is the algebra generated by `e`, `f`, `h`, with relations

  `he − eh = 2e`,  `hf − fh = −2f`,  `ef − fe = h`.

## Formalization

`𝔰𝔩(2)` is the 3-dimensional Lie algebra with basis `e, f, h` and the brackets
`⁅h, e⁆ = 2e`, `⁅h, f⁆ = -2f`, `⁅e, f⁆ = h`. We construct it concretely as `k × k × k`, with the
triple `(a, b, d)` denoting `a·e + b·f + d·h`, and verify the defining bracket relations.

The content is:

* `sl2` is a Lie algebra with the stated brackets (`bracket_h_e`, `bracket_h_f`,
  `bracket_e_f`);
* inside `U(𝔰𝔩(2))`, the images `E = ι e`, `F = ι f`, `H = ι h` satisfy the book's relations
  `HE − EH = 2E`, `HF − FH = −2F`, `EF − FE = H` (`sl2_universal_relations`). These are specific
  to `𝔰𝔩(2)`: they are not provable for an arbitrary `L`.

## Mathlib correspondence

Mathlib has `UniversalEnvelopingAlgebra`, but `𝔰𝔩(2)` with the explicit `e, f, h` basis and these
relations is not directly available as a concrete presentation, so we build it here. The full
universal property (that `e, f, h` generate `U(𝔰𝔩(2))` and that these relations are a complete
presentation) is beyond current Mathlib infrastructure; we assert and prove the defining relations.
-/

namespace Etingof.Example2_9_12

open UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing

variable {k : Type*} [CommRing k]

/-- The Lie algebra `𝔰𝔩(2)` over `k`: the 3-dimensional space `k·e ⊕ k·f ⊕ k·h`, carried by
`k × k × k`. The triple `(a, b, d)` denotes `a·e + b·f + d·h`. -/
def sl2 (k : Type*) [CommRing k] : Type _ := k × k × k

instance : AddCommGroup (sl2 k) := inferInstanceAs (AddCommGroup (k × k × k))

instance : Module k (sl2 k) := inferInstanceAs (Module k (k × k × k))

@[ext] theorem sl2.ext {a b : sl2 k}
    (h1 : a.1 = b.1) (h2 : a.2.1 = b.2.1) (h3 : a.2.2 = b.2.2) : a = b :=
  Prod.ext h1 (Prod.ext h2 h3)

-- Projection lemmas for the (componentwise) module structure. They are `rfl` but stated so that
-- `simp` can rewrite through the `sl2` type synonym (whose add/zero/smul instances do not
-- syntactically match the generic `Prod` lemmas).
@[simp] theorem add_fst (a b : sl2 k) : (a + b).1 = a.1 + b.1 := rfl
@[simp] theorem add_snd_fst (a b : sl2 k) : (a + b).2.1 = a.2.1 + b.2.1 := rfl
@[simp] theorem add_snd_snd (a b : sl2 k) : (a + b).2.2 = a.2.2 + b.2.2 := rfl
@[simp] theorem zero_fst : (0 : sl2 k).1 = 0 := rfl
@[simp] theorem zero_snd_fst : (0 : sl2 k).2.1 = 0 := rfl
@[simp] theorem zero_snd_snd : (0 : sl2 k).2.2 = 0 := rfl
@[simp] theorem smul_fst (t : k) (a : sl2 k) : (t • a).1 = t • a.1 := rfl
@[simp] theorem smul_snd_fst (t : k) (a : sl2 k) : (t • a).2.1 = t • a.2.1 := rfl
@[simp] theorem smul_snd_snd (t : k) (a : sl2 k) : (t • a).2.2 = t • a.2.2 := rfl
@[simp] theorem neg_fst (a : sl2 k) : (-a).1 = -a.1 := rfl
@[simp] theorem neg_snd_fst (a : sl2 k) : (-a).2.1 = -a.2.1 := rfl
@[simp] theorem neg_snd_snd (a : sl2 k) : (-a).2.2 = -a.2.2 := rfl

/-- The `𝔰𝔩(2)` bracket. With the basis convention `(a, b, d) = a·e + b·f + d·h`, expanding
`⁅u, v⁆` bilinearly from `⁅h, e⁆ = 2e`, `⁅h, f⁆ = -2f`, `⁅e, f⁆ = h` (and antisymmetry) gives the
`e`-coordinate `2(d₁a₂ − a₁d₂)`, the `f`-coordinate `−2(d₁b₂ − b₁d₂)`, and the `h`-coordinate
`a₁b₂ − b₁a₂`. -/
instance : Bracket (sl2 k) (sl2 k) where
  bracket u v :=
    (2 * (u.2.2 * v.1 - u.1 * v.2.2),
     -(2 * (u.2.2 * v.2.1 - u.2.1 * v.2.2)),
     u.1 * v.2.1 - u.2.1 * v.1)

@[simp]
theorem bracket_def (u v : sl2 k) :
    ⁅u, v⁆ =
      (2 * (u.2.2 * v.1 - u.1 * v.2.2),
       -(2 * (u.2.2 * v.2.1 - u.2.1 * v.2.2)),
       u.1 * v.2.1 - u.2.1 * v.1) := rfl

instance : LieRing (sl2 k) where
  add_lie x y z := by
    apply sl2.ext <;>
      simp only [bracket_def, add_fst, add_snd_fst, add_snd_snd] <;> ring
  lie_add x y z := by
    apply sl2.ext <;>
      simp only [bracket_def, add_fst, add_snd_fst, add_snd_snd] <;> ring
  lie_self x := by
    apply sl2.ext <;> simp [bracket_def] <;> ring
  leibniz_lie x y z := by
    apply sl2.ext <;>
      simp only [bracket_def, add_fst, add_snd_fst, add_snd_snd] <;> ring

instance : LieAlgebra k (sl2 k) where
  lie_smul t x y := by
    apply sl2.ext <;>
      simp only [bracket_def, smul_fst, smul_snd_fst, smul_snd_snd, smul_eq_mul] <;> ring

/-- The basis vector `e` of `𝔰𝔩(2)`. -/
def e : sl2 k := ((1 : k), (0 : k), (0 : k))

/-- The basis vector `f` of `𝔰𝔩(2)`. -/
def f : sl2 k := ((0 : k), (1 : k), (0 : k))

/-- The basis vector `h` of `𝔰𝔩(2)`. -/
def h : sl2 k := ((0 : k), (0 : k), (1 : k))

@[simp] theorem bracket_h_e : ⁅(h : sl2 k), (e : sl2 k)⁆ = (2 : k) • (e : sl2 k) := by
  apply sl2.ext <;> simp [bracket_def, e, h]

@[simp] theorem bracket_h_f : ⁅(h : sl2 k), (f : sl2 k)⁆ = (-2 : k) • (f : sl2 k) := by
  apply sl2.ext <;> simp [bracket_def, f, h]

@[simp] theorem bracket_e_f : ⁅(e : sl2 k), (f : sl2 k)⁆ = (h : sl2 k) := by
  apply sl2.ext <;> simp [bracket_def, e, f, h]

/-- **Example 2.9.12.** The defining relations of `U(𝔰𝔩(2))`: writing `E = ι e`, `F = ι f`,
`H = ι h` for the images of the `𝔰𝔩(2)` generators in the universal enveloping algebra, we have

  `HE − EH = 2E`,  `HF − FH = −2F`,  `EF − FE = H`.

These are exactly the book's relations `he − eh = 2e`, `hf − fh = −2f`, `ef − fe = h`. Unlike the
generic `Algebra k (UniversalEnvelopingAlgebra k L)` statement (which holds for any `L`), these
relations are specific to the `𝔰𝔩(2)` presentation. -/
theorem sl2_universal_relations (k : Type*) [CommRing k] :
    (ι k (h : sl2 k)) * (ι k e) - (ι k e) * (ι k h) = (2 : k) • ι k e ∧
    (ι k (h : sl2 k)) * (ι k f) - (ι k f) * (ι k h) = (-2 : k) • ι k f ∧
    (ι k (e : sl2 k)) * (ι k f) - (ι k f) * (ι k e) = ι k h := by
  refine ⟨?_, ?_, ?_⟩
  · rw [← LieRing.of_associative_ring_bracket, ← LieHom.map_lie, bracket_h_e, map_smul]
  · rw [← LieRing.of_associative_ring_bracket, ← LieHom.map_lie, bracket_h_f, map_smul]
  · rw [← LieRing.of_associative_ring_bracket, ← LieHom.map_lie, bracket_e_f]

/-- Every element of `𝔰𝔩(2)` is the expected combination of the basis vectors `e`, `f`, `h`. -/
theorem eq_smul_e_add_smul_f_add_smul_h (x : sl2 k) :
    x = x.1 • (e : sl2 k) + x.2.1 • (f : sl2 k) + x.2.2 • (h : sl2 k) := by
  apply sl2.ext <;> simp [e, f, h]

/-! ### `e`, `f`, `h` generate `U(𝔰𝔩(2))`

The book says `U(𝔰𝔩(2))` *is the algebra generated by* `e`, `f`, `h` with the three relations.
This section proves the "generated by" half; the next section proves that the relations are a
complete presentation.
-/

/-- The image of `ι` generates the universal enveloping algebra of any Lie algebra. -/
theorem adjoin_range_ι (k : Type*) [CommRing k] (L : Type*) [LieRing L] [LieAlgebra k L] :
    Algebra.adjoin k (Set.range (ι k : L → UniversalEnvelopingAlgebra k L)) = ⊤ := by
  have hsurj : (mkAlgHom k L).range = ⊤ :=
    (AlgHom.range_eq_top _).mpr (RingQuot.mkAlgHom_surjective k (Rel k L))
  calc Algebra.adjoin k (Set.range (ι k : L → UniversalEnvelopingAlgebra k L))
      = Algebra.adjoin k (mkAlgHom k L '' Set.range (TensorAlgebra.ι k)) := by
        rw [← Set.range_comp]; rfl
    _ = (Algebra.adjoin k (Set.range (TensorAlgebra.ι k (M := L)))).map (mkAlgHom k L) :=
        (AlgHom.map_adjoin _ _).symm
    _ = (⊤ : Subalgebra k (TensorAlgebra k L)).map (mkAlgHom k L) := by
        rw [TensorAlgebra.adjoin_range_ι]
    _ = ⊤ := by rw [Algebra.map_top, hsurj]

/-- **Example 2.9.12, "generated by" half.** The three images `ι e`, `ι f`, `ι h` generate
`U(𝔰𝔩(2))` as a `k`-algebra. -/
theorem adjoin_ι_e_f_h (k : Type*) [CommRing k] :
    Algebra.adjoin k {ι k (e : sl2 k), ι k (f : sl2 k), ι k (h : sl2 k)} = ⊤ := by
  rw [eq_top_iff, ← adjoin_range_ι k (sl2 k), Algebra.adjoin_le_iff]
  rintro _ ⟨x, rfl⟩
  rw [eq_smul_e_add_smul_f_add_smul_h x, map_add, map_add, map_smul, map_smul, map_smul]
  set S := Algebra.adjoin k {ι k (e : sl2 k), ι k (f : sl2 k), ι k (h : sl2 k)} with hS
  have he : ι k (e : sl2 k) ∈ S := Algebra.subset_adjoin (by simp)
  have hf : ι k (f : sl2 k) ∈ S := Algebra.subset_adjoin (by simp)
  have hh : ι k (h : sl2 k) ∈ S := Algebra.subset_adjoin (by simp)
  exact add_mem (add_mem (Subalgebra.smul_mem _ he _) (Subalgebra.smul_mem _ hf _))
    (Subalgebra.smul_mem _ hh _)

/-! ### The universal property of the three relations

A triple `(X, Y, Z)` in an associative `k`-algebra satisfying the book's three relations is the
same thing as a Lie algebra morphism out of `𝔰𝔩(2)`. This is the computational heart of the
presentation theorem: it is used once for the presented algebra and once for `U(𝔰𝔩(2))` itself.
-/

section Triple

variable {A : Type*} [Ring A] [Algebra k A]

/-- A triple `(X, Y, Z)` in an associative `k`-algebra satisfying the `𝔰𝔩(2)` relations
`ZX − XZ = 2X`, `ZY − YZ = −2Y`, `XY − YX = Z` determines a Lie algebra morphism
`𝔰𝔩(2) →ₗ⁅k⁆ A` sending `e ↦ X`, `f ↦ Y`, `h ↦ Z`. -/
def liftTriple (X Y Z : A) (hX : Z * X - X * Z = (2 : k) • X)
    (hY : Z * Y - Y * Z = (-2 : k) • Y) (hZ : X * Y - Y * X = Z) : sl2 k →ₗ⁅k⁆ A where
  toFun u := u.1 • X + u.2.1 • Y + u.2.2 • Z
  map_add' u v := by
    simp only [add_fst, add_snd_fst, add_snd_snd, add_smul]
    abel
  map_smul' t u := by
    simp only [smul_fst, smul_snd_fst, smul_snd_snd, smul_eq_mul, RingHom.id_apply,
      smul_add, smul_smul]
  map_lie' {u v} := by
    obtain ⟨a₁, b₁, d₁⟩ := u
    obtain ⟨a₂, b₂, d₂⟩ := v
    have expand :
        (a₁ • X + b₁ • Y + d₁ • Z) * (a₂ • X + b₂ • Y + d₂ • Z) -
            (a₂ • X + b₂ • Y + d₂ • Z) * (a₁ • X + b₁ • Y + d₁ • Z) =
          (a₁ * b₂ - b₁ * a₂) • (X * Y - Y * X) + (d₁ * a₂ - a₁ * d₂) • (Z * X - X * Z) +
            (d₁ * b₂ - b₁ * d₂) • (Z * Y - Y * Z) := by
      simp only [add_mul, mul_add, smul_mul_smul_comm, smul_sub]
      module
    simp only [LieRing.of_associative_ring_bracket, bracket_def]
    rw [expand, hX, hY, hZ]
    module

@[simp] theorem liftTriple_apply (X Y Z : A) (hX : Z * X - X * Z = (2 : k) • X)
    (hY : Z * Y - Y * Z = (-2 : k) • Y) (hZ : X * Y - Y * X = Z) (u : sl2 k) :
    liftTriple X Y Z hX hY hZ u = u.1 • X + u.2.1 • Y + u.2.2 • Z := rfl

@[simp] theorem liftTriple_e (X Y Z : A) (hX : Z * X - X * Z = (2 : k) • X)
    (hY : Z * Y - Y * Z = (-2 : k) • Y) (hZ : X * Y - Y * X = Z) :
    liftTriple X Y Z hX hY hZ (e : sl2 k) = X := by simp [e]

@[simp] theorem liftTriple_f (X Y Z : A) (hX : Z * X - X * Z = (2 : k) • X)
    (hY : Z * Y - Y * Z = (-2 : k) • Y) (hZ : X * Y - Y * X = Z) :
    liftTriple X Y Z hX hY hZ (f : sl2 k) = Y := by simp [f]

@[simp] theorem liftTriple_h (X Y Z : A) (hX : Z * X - X * Z = (2 : k) • X)
    (hY : Z * Y - Y * Z = (-2 : k) • Y) (hZ : X * Y - Y * X = Z) :
    liftTriple X Y Z hX hY hZ (h : sl2 k) = Z := by simp [h]

end Triple

end Etingof.Example2_9_12
