import Mathlib.RingTheory.SimpleModule.Rank
import Mathlib.FieldTheory.IsAlgClosed.Basic
import Mathlib.Algebra.Polynomial.Module.AEval
import Mathlib.LinearAlgebra.Eigenspace.Minpoly
import Mathlib.Algebra.Module.PID
import EtingofRepresentationTheory.Chapter2.Definition2_3_8

/-!
# Example 2.3.14: Irreducible and Indecomposable Representations of k and k[x]

1. A = k. Since representations of A are simply vector spaces, V = A is the only irreducible
   and the only indecomposable representation.

2. A = k[x]. The irreducible finite dimensional representations are the 1-dimensional
   representations V_λ = k with ρ(x) = λ for λ ∈ k. The indecomposable finite dimensional
   representations are V_{λ,n} = kⁿ with ρ(x) = J_{λ,n} (Jordan blocks).

This example shows that an indecomposable representation need not be irreducible.

The classification is exhaustive in both directions: `jordanRep_indecomposable` shows each
`V_{λ,n}` is indecomposable, `exists_equiv_jordanRep` shows there are no others, and
`jordanRep_equiv_iff` shows they are pairwise nonisomorphic.
-/

/-- For A = k, the unique irreducible representation is k itself (1-dimensional).
(Etingof Example 2.3.14(1)) -/
example (k : Type*) [Field k] : IsSimpleModule k k := inferInstance

/-- **Example 2.3.14(1), uniqueness of the irreducible representation.** Every irreducible
representation of the field `k` is isomorphic to the regular one-dimensional representation `k`. -/
theorem Etingof.Example_2_3_14_field_irreducible_unique
    (k : Type*) [Field k] (V : Type*) [AddCommGroup V] [Module k V]
    [IsSimpleModule k V] : Nonempty (V ≃ₗ[k] k) := by
  exact (Module.nonempty_linearEquiv_of_finrank_eq_one
    (isSimpleModule_iff_finrank_eq_one.mp (inferInstance : IsSimpleModule k V))).map
      LinearEquiv.symm

/-- **Example 2.3.14(1), uniqueness of the indecomposable representation.** Every indecomposable
representation of the field `k` is isomorphic to the regular one-dimensional representation `k`. -/
theorem Etingof.Example_2_3_14_field_indecomposable_unique
    (k : Type*) [Field k] (V : Type*) [AddCommGroup V] [Module k V]
    (hV : Etingof.IsIndecomposable k V) : Nonempty (V ≃ₗ[k] k) := by
  letI : Nontrivial V := hV.1
  haveI : IsSimpleModule k V := (isSimpleModule_iff k V).2 {
    eq_bot_or_eq_top := by
      intro W
      obtain ⟨P, hP⟩ := ComplementedLattice.exists_isCompl W
      rcases hV.2 W P hP with hW | hPbot
      · exact Or.inl hW
      · right
        have hsup : W ⊔ P = ⊤ := codisjoint_iff.mp hP.codisjoint
        simpa [hPbot] using hsup }
  exact Etingof.Example_2_3_14_field_irreducible_unique k V

/-- Over an algebraically closed field k, every simple k[x]-module is 1-dimensional.
Equivalently, every maximal ideal of k[x] has quotient of k-dimension 1.
This is because k[x] is a PID, so maximal ideals are generated by irreducible
polynomials, which are linear over an algebraically closed field.
(Etingof Example 2.3.14(2)) -/
theorem Etingof.Example_2_3_14_polynomial_reps (k : Type*) [Field k] [IsAlgClosed k]
    (I : Ideal (Polynomial k)) [hmax : I.IsMaximal] :
    Module.finrank k (Polynomial k ⧸ I) = 1 := by
  set p := Submodule.IsPrincipal.generator I
  have hI : I = Ideal.span {p} := by
    rw [← Ideal.submodule_span_eq]; exact (Submodule.IsPrincipal.span_singleton_generator I).symm
  rw [hI, finrank_quotient_span_eq_natDegree]
  have hne : p ≠ 0 := by
    intro h
    have hbot : I = ⊥ := by rw [hI, h, Ideal.span_singleton_eq_bot]
    rw [hbot] at hmax
    have hXtop : Ideal.span {(Polynomial.X : Polynomial k)} = ⊤ :=
      hmax.1.2 _ (bot_lt_iff_ne_bot.mpr (mt Ideal.span_singleton_eq_bot.mp
        Polynomial.X_ne_zero))
    exact (Polynomial.irreducible_X (R := k)).1 (Ideal.span_singleton_eq_top.mp hXtop)
  have hprime : (Ideal.span {p}).IsPrime := by rw [← hI]; exact hmax.isPrime
  rw [Ideal.span_singleton_prime hne] at hprime
  have hirr : Irreducible p := hprime.irreducible
  have hdeg : p.degree = 1 := IsAlgClosed.degree_eq_one_of_irreducible (k := k) hirr
  rwa [Polynomial.degree_eq_natDegree hne, Nat.cast_eq_one] at hdeg

/-!
## Part (2), continued: Jordan-block representations and indecomposability

The substantive content of Etingof Example 2.3.14(2): the finite-dimensional indecomposable
representations of `k[x]` are the Jordan blocks `V_{λ,n} = (kⁿ, ρ(x) = J_{λ,n})`. We build
these as `k[X]`-modules (`Module.AEval'` of the Jordan-block operator), prove they are
indecomposable, and prove that for `n ≥ 2` they are not simple, giving the book's
conclusion that an indecomposable representation need not be irreducible.

The other half of the book's claim — that every finite-dimensional indecomposable
`k[x]`-representation is isomorphic to some `V_{λ,n}`, and that the parameters `(λ, n)` are
determined — is the existence-and-uniqueness of Jordan normal form. It is proved below
(`exists_equiv_jordanRep`, `jordanRep_equiv_iff`) from the structure theorem for finitely
generated modules over the principal ideal domain `k[X]`, via the cyclic model
`V_{λ,n} ≅ k[X]/((X-λ)ⁿ)` (`jordanQuotEquiv`).
-/

open Polynomial

namespace Etingof.Example_2_3_14

/- The numbered namespace is part of the project's stable source-traceability API. The
`defsWithUnderscore` linter otherwise blames every definition nested in it, even though each
definition's own basename follows Mathlib's naming convention. -/

variable {k : Type*} [Field k]

/-- The nilpotent down-shift on `Fin n → k`: it sends the basis vector `eᵢ` to `eᵢ₋₁`
(and `e₀` to `0`). On coordinates, `(shift v) i = v (i+1)` (zero when `i+1 = n`). -/
def shift (n : ℕ) : (Fin n → k) →ₗ[k] (Fin n → k) where
  toFun v i := if h : (i : ℕ) + 1 < n then v ⟨i + 1, h⟩ else 0
  map_add' u v := by funext i; dsimp; split <;> simp
  map_smul' c v := by funext i; dsimp; split <;> simp

/-- The shift reads the next coordinate, or vanishes at the final coordinate. -/
@[simp] lemma shift_apply (n : ℕ) (v : Fin n → k) (i : Fin n) :
    shift n v i = if h : (i : ℕ) + 1 < n then v ⟨i + 1, h⟩ else 0 := rfl

/-- The Jordan block `J_{λ,n}`: in the standard basis, `J eᵢ = λ eᵢ + eᵢ₋₁`. -/
def jordanBlock (lam : k) (n : ℕ) : (Fin n → k) →ₗ[k] (Fin n → k) :=
  lam • LinearMap.id + shift n

/-- The coordinate formula for the Jordan block. -/
@[simp] lemma jordanBlock_apply (lam : k) (n : ℕ) (v : Fin n → k) (i : Fin n) :
    jordanBlock lam n v i = lam * v i + (if h : (i : ℕ) + 1 < n then v ⟨i + 1, h⟩ else 0) := by
  simp [jordanBlock, shift]

/-- Iterating the shift `j` times lowers the index by `j`. -/
lemma shift_pow_apply (n j : ℕ) (v : Fin n → k) (i : Fin n) :
    ((shift n) ^ j) v i = if h : (i : ℕ) + j < n then v ⟨i + j, h⟩ else 0 := by
  induction j generalizing v with
  | zero => simp
  | succ j ih =>
    rw [pow_succ, Module.End.mul_apply, ih (shift n v)]
    by_cases h : (i : ℕ) + (j + 1) < n
    · have h1 : (i : ℕ) + j < n := by omega
      rw [dif_pos h1]
      simp only [shift_apply]
      have h2 : ((⟨(i : ℕ) + j, h1⟩ : Fin n) : ℕ) + 1 < n := by omega
      rw [dif_pos h2, dif_pos h]
      exact congrArg v (Fin.ext (by simp; omega))
    · rw [dif_neg (by omega : ¬ (i : ℕ) + (j + 1) < n)]
      by_cases h1 : (i : ℕ) + j < n
      · rw [dif_pos h1]
        simp only [shift_apply]
        rw [dif_neg (show ¬ ((⟨(i : ℕ) + j, h1⟩ : Fin n) : ℕ) + 1 < n by omega)]
      · rw [dif_neg h1]

/-- The shift on `kⁿ` is nilpotent. -/
lemma shift_nilpotent (n : ℕ) : IsNilpotent (shift n : (Fin n → k) →ₗ[k] (Fin n → k)) := by
  refine ⟨n, ?_⟩
  apply LinearMap.ext; intro v; funext i
  rw [shift_pow_apply]
  rw [dif_neg (by omega : ¬ (i : ℕ) + n < n)]
  simp

/-- The standard basis vector `e₀ = (1, 0, …, 0)`. It spans the (one-dimensional)
eigenspace of the Jordan block for the eigenvalue `λ`. -/
def e0 (n : ℕ) [NeZero n] : Fin n → k := Pi.single 0 1

/-- The vector `e₀` is nonzero in every positive dimension. -/
lemma e0_ne_zero (n : ℕ) [NeZero n] : (e0 n : Fin n → k) ≠ 0 := by
  intro h
  have : (e0 n : Fin n → k) 0 = (0 : Fin n → k) 0 := by rw [h]
  simp [e0, Pi.single_eq_same] at this

/-- `e₀` is an eigenvector of the Jordan block with eigenvalue `λ`: `J e₀ = λ e₀`. -/
lemma jordanBlock_e0 (lam : k) (n : ℕ) [NeZero n] :
    jordanBlock lam n (e0 n) = lam • (e0 n : Fin n → k) := by
  funext i
  rw [jordanBlock_apply]
  have hz : (if h : (i : ℕ) + 1 < n then (e0 n : Fin n → k) ⟨i + 1, h⟩ else 0) = 0 := by
    split
    · apply Pi.single_eq_of_ne
      intro hh; rw [Fin.ext_iff] at hh; simp at hh
    · rfl
  rw [hz, add_zero]
  simp [Pi.smul_apply]

/-- The kernel of the shift is contained in the line spanned by `e₀`. -/
lemma ker_shift_le (n : ℕ) [NeZero n] :
    LinearMap.ker (shift n) ≤ Submodule.span k {(e0 n : Fin n → k)} := by
  intro v hv
  rw [LinearMap.mem_ker] at hv
  rw [Submodule.mem_span_singleton]
  refine ⟨v 0, ?_⟩
  funext j
  simp only [e0, Pi.smul_apply, smul_eq_mul]
  rcases Nat.eq_zero_or_pos (j : ℕ) with hj | hj
  · have : j = 0 := Fin.ext hj
    simp [this]
  · rw [Pi.single_eq_of_ne (by intro h; rw [h] at hj; simp at hj), mul_zero]
    -- v j = 0 because j = i+1 for i = j-1 and shift v = 0
    have hjlt : (j : ℕ) < n := j.isLt
    set i : Fin n := ⟨(j : ℕ) - 1, by omega⟩ with hi
    have hival : (i : ℕ) = (j : ℕ) - 1 := by rw [hi]
    have hlt : (i : ℕ) + 1 < n := by omega
    have hv' := congrFun hv i
    simp only [shift_apply, Pi.zero_apply] at hv'
    rw [dif_pos hlt] at hv'
    have hidx : (⟨(i : ℕ) + 1, hlt⟩ : Fin n) = j := Fin.ext (by change (i : ℕ) + 1 = (j : ℕ); omega)
    rw [hidx] at hv'
    exact hv'.symm

/-- A nilpotent endomorphism of a nontrivial module has a nonzero kernel vector. -/
lemma exists_mem_ker_of_isNilpotent {N : Type*} [AddCommGroup N] [Module k N] [Nontrivial N]
    (g : N →ₗ[k] N) (hg : IsNilpotent g) : ∃ u : N, u ≠ 0 ∧ g u = 0 := by
  by_contra h
  rw [not_exists] at h
  simp only [not_and] at h
  -- h : ∀ u, u ≠ 0 → g u = 0 is impossible, so reformulate: ∀ u, g u = 0 → u = 0
  have hinj : Function.Injective g := by
    rw [← LinearMap.ker_eq_bot, Submodule.eq_bot_iff]
    intro x hx
    by_contra hxne
    exact h x hxne (LinearMap.mem_ker.mp hx)
  obtain ⟨m, hm⟩ := hg
  have hpow : ∀ j, Function.Injective ⇑((g ^ j : Module.End k N)) := by
    intro j
    induction j with
    | zero => intro a b hab; simpa using hab
    | succ j ih =>
      rw [pow_succ]
      intro a b hab
      exact hinj (ih (by simpa only [Module.End.mul_apply] using hab))
  have hzero := hpow m
  rw [hm] at hzero
  obtain ⟨a, b, hab⟩ := exists_pair_ne N
  exact hab (hzero (by simp))

/-- Every nonzero `J_{λ,n}`-invariant subspace contains the eigenvector `e₀`.
This is the engine behind indecomposability: any two nonzero invariant subspaces meet in `e₀`. -/
lemma e0_mem_of_invariant (lam : k) (n : ℕ) [NeZero n] {W : Submodule k (Fin n → k)}
    (hW : W ≠ ⊥) (hinv : ∀ m ∈ W, jordanBlock lam n m ∈ W) :
    (e0 n : Fin n → k) ∈ W := by
  -- `W` is invariant under `shift = J - λ•id`.
  have hshift : Set.MapsTo (shift n) (W : Set (Fin n → k)) (W : Set (Fin n → k)) := by
    intro m hm
    have hsub : shift n m = jordanBlock lam n m - lam • m := by
      have : jordanBlock lam n m = lam • m + shift n m := by simp [jordanBlock]
      rw [this]; abel
    rw [hsub]
    exact W.sub_mem (hinv m hm) (W.smul_mem lam hm)
  have hnil : IsNilpotent ((shift n).restrict hshift) :=
    Module.End.isNilpotent.restrict hshift (shift_nilpotent n)
  have hnontriv : Nontrivial W := Submodule.nontrivial_iff_ne_bot.mpr hW
  obtain ⟨u, hune, hu0⟩ := exists_mem_ker_of_isNilpotent ((shift n).restrict hshift) hnil
  -- `↑u` is a nonzero kernel vector of `shift`, hence a nonzero multiple of `e₀`.
  have hu0' : shift n (u : Fin n → k) = 0 := by
    have := congrArg (Subtype.val) hu0
    rwa [LinearMap.restrict_apply] at this
  have huker : (u : Fin n → k) ∈ Submodule.span k {(e0 n : Fin n → k)} :=
    ker_shift_le n (LinearMap.mem_ker.mpr hu0')
  rw [Submodule.mem_span_singleton] at huker
  obtain ⟨c, hc⟩ := huker
  have hcne : c ≠ 0 := by
    rintro rfl
    apply hune
    apply Subtype.ext
    simpa using hc.symm
  -- `e₀ = c⁻¹ • ↑u ∈ W`.
  have : (e0 n : Fin n → k) = c⁻¹ • (u : Fin n → k) := by
    rw [← hc, smul_smul, inv_mul_cancel₀ hcne, one_smul]
  rw [this]
  exact W.smul_mem c⁻¹ u.2

/-- The Jordan-block representation `V_{λ,n} = (kⁿ, ρ(x) = J_{λ,n})`, realized as a
`k[X]`-module via `Module.AEval'`: the action of `X` is the Jordan block `J_{λ,n}`.
(Etingof Example 2.3.14(2)) -/
abbrev jordanRep (lam : k) (n : ℕ) := Module.AEval' (jordanBlock lam n)

/-- A positive-dimensional Jordan-block representation is nontrivial. -/
instance jordanRep_nontrivial (lam : k) (n : ℕ) [NeZero n] :
    Nontrivial (jordanRep lam n) :=
  (Module.AEval'.of (jordanBlock lam n)).symm.toEquiv.nontrivial

/-- **The Jordan-block representations `V_{λ,n}` are indecomposable.**
Any two nonzero `J`-invariant subspaces both contain the eigenvector `e₀`, so they cannot be
complementary. (Etingof Example 2.3.14(2): "these representations are indecomposable".) -/
theorem jordanRep_indecomposable (lam : k) (n : ℕ) [NeZero n] :
    IsIndecomposable (Polynomial k) (jordanRep lam n) := by
  set φ := jordanBlock lam n with hφ
  set of := Module.AEval'.of φ with hof
  refine ⟨inferInstance, ?_⟩
  intro N P hcompl
  by_contra hcon
  rw [not_or] at hcon
  obtain ⟨hN, hP⟩ := hcon
  -- Pull a `k[X]`-submodule back to a `φ`-invariant `k`-subspace of `kⁿ`.
  have invar : ∀ Q : Submodule (Polynomial k) (jordanRep lam n),
      ∀ m : Fin n → k, of m ∈ Q → φ m ∈
        ((Q.restrictScalars k).comap (of : (Fin n → k) →ₗ[k] jordanRep lam n)) := by
    intro Q m hm
    rw [Submodule.mem_comap, Submodule.restrictScalars_mem]
    have : (Polynomial.X : Polynomial k) • of m ∈ Q := Q.smul_mem _ hm
    rwa [Module.AEval'.X_smul_of] at this
  -- For a nonzero `Q`, the pullback contains `e₀`.
  have e0mem : ∀ Q : Submodule (Polynomial k) (jordanRep lam n), Q ≠ ⊥ →
      of (e0 n) ∈ Q := by
    intro Q hQ
    set W : Submodule k (Fin n → k) :=
      (Q.restrictScalars k).comap (of : (Fin n → k) →ₗ[k] jordanRep lam n) with hW
    have hWmem : ∀ m : Fin n → k, m ∈ W ↔ of m ∈ Q := fun m => Iff.rfl
    have hWbot : W ≠ ⊥ := by
      rw [Submodule.ne_bot_iff] at hQ ⊢
      obtain ⟨x, hxQ, hxne⟩ := hQ
      refine ⟨of.symm x, ?_, ?_⟩
      · rw [hWmem]; simpa using hxQ
      · exact (map_ne_zero_iff of.symm of.symm.injective).mpr hxne
    have hinv : ∀ m ∈ W, φ m ∈ W := by
      intro m hm
      rw [hWmem] at hm ⊢
      exact invar Q m hm
    have := e0_mem_of_invariant lam n hWbot hinv
    rwa [hWmem] at this
  have hNe : of (e0 n) ∈ N := e0mem N hN
  have hPe : of (e0 n) ∈ P := e0mem P hP
  have : of (e0 n) ∈ N ⊓ P := Submodule.mem_inf.mpr ⟨hNe, hPe⟩
  rw [hcompl.inf_eq_bot] at this
  rw [Submodule.mem_bot] at this
  exact (map_ne_zero_iff of of.injective).mpr (e0_ne_zero n) this

/-- **For `n ≥ 2`, the Jordan-block representation `V_{λ,n}` is not irreducible (not simple).**
The eigenline `k · e₀` is a proper nonzero subrepresentation: `e₀` is fixed up to scalar by
`J`, so the cyclic `k[X]`-submodule it generates is one-dimensional, hence not all of `kⁿ`.
(Etingof Example 2.3.14(2): "an indecomposable representation need not be irreducible".) -/
theorem jordanRep_not_isSimpleModule (lam : k) (n : ℕ) (hn : 2 ≤ n) :
    ¬ IsSimpleModule (Polynomial k) (jordanRep lam n) := by
  haveI : NeZero n := ⟨by omega⟩
  set φ := jordanBlock lam n with hφ
  set of := Module.AEval'.of φ with hof
  intro hsimp
  haveI := hsimp
  -- The eigenline: the cyclic `k[X]`-submodule generated by `of e₀`.
  set Q := Submodule.span (Polynomial k) {(of (e0 n) : jordanRep lam n)} with hQ
  have hQbot : Q ≠ ⊥ := by
    rw [hQ, Ne, Submodule.span_singleton_eq_bot]
    exact (map_ne_zero_iff of of.injective).mpr (e0_ne_zero n)
  have hQtop : Q = ⊤ := (eq_bot_or_eq_top Q).resolve_left hQbot
  -- `e₁` lies in `⊤ = Q`, but every element of `Q` is a scalar multiple of `e₀`.
  set e1 : Fin n → k := Pi.single ⟨1, hn⟩ 1 with he1
  have he1mem : of e1 ∈ Q := hQtop ▸ Submodule.mem_top
  rw [hQ, Submodule.mem_span_singleton] at he1mem
  obtain ⟨a, ha⟩ := he1mem
  -- Rewrite `a • of e₀` as `of ((eval lam a) • e₀)` using that `e₀` is an eigenvector.
  have hsmul : a • of (e0 n) = of (a.eval lam • e0 n) := by
    rw [← Module.AEval.of_aeval_smul]
    congr 1
    exact Module.End.aeval_apply_of_mem_apply_eq_smul (jordanBlock_e0 lam n)
  rw [hsmul] at ha
  have hvec : a.eval lam • e0 n = e1 := of.injective ha
  -- Contradiction at coordinate `1`.
  have := congrFun hvec ⟨1, hn⟩
  rw [he1, Pi.single_eq_same] at this
  simp only [e0, Pi.smul_apply, smul_eq_mul] at this
  rw [Pi.single_eq_of_ne (by intro h; rw [Fin.ext_iff] at h; simp at h)] at this
  simp at this

/-- **An indecomposable representation need not be irreducible.**
The Jordan-block representation `V_{0,2} = (k², J_{0,2})` (a single `2 × 2` nilpotent Jordan
block) is an indecomposable `k[X]`-module that is not simple. (Etingof Example 2.3.14(2).) -/
theorem exists_indecomposable_not_simple :
    IsIndecomposable (Polynomial k) (jordanRep (0 : k) 2) ∧
      ¬ IsSimpleModule (Polynomial k) (jordanRep (0 : k) 2) :=
  ⟨jordanRep_indecomposable 0 2, jordanRep_not_isSimpleModule 0 2 le_rfl⟩

/-!
## The cyclic model of a Jordan block

`V_{λ,n}` is the cyclic `k[X]`-module `k[X]/((X-λ)ⁿ)`: the top basis vector `e_{n-1}` is a
cyclic vector, `X - λ` acts on it as the nilpotent down-shift, and `(X-λ)ⁿ` kills it.

This is the form in which the structure theorem for modules over the principal ideal domain
`k[X]` delivers its summands, so it is what connects that theorem to the Jordan blocks.
-/

/-- The top standard basis vector `e_{n-1} = (0, …, 0, 1)`. It is a cyclic vector for the
Jordan block `J_{λ,n}`: applying the shift repeatedly sweeps out the whole standard basis. -/
def eTop (n : ℕ) [NeZero n] : Fin n → k :=
  Pi.single ⟨n - 1, Nat.sub_lt (Nat.pos_of_ne_zero (NeZero.ne n)) one_pos⟩ 1

/-- Applying the shift `j < n` times to `e_{n-1}` gives the basis vector `e_{n-1-j}`. -/
lemma shift_pow_eTop (n : ℕ) [NeZero n] {j : ℕ} (hj : j < n) :
    ((shift n) ^ j) (eTop n : Fin n → k) = Pi.single ⟨n - 1 - j, by omega⟩ 1 := by
  funext i
  rw [shift_pow_apply]
  by_cases h : (i : ℕ) + j < n
  · rw [dif_pos h]
    simp only [eTop, Pi.single_apply, Fin.ext_iff]
    have : ((i : ℕ) + j = n - 1) ↔ ((i : ℕ) = n - 1 - j) := by omega
    simp [this]
  · rw [dif_neg h]
    symm
    simp only [Pi.single_apply, Fin.ext_iff]
    rw [if_neg (by omega)]

/-- `X - λ` acts on `V_{λ,n}` as the nilpotent down-shift: `J_{λ,n} - λ = S`. -/
lemma aeval_jordanBlock_X_sub_C (lam : k) (n : ℕ) :
    Polynomial.aeval (jordanBlock lam n) (X - C lam) = shift n := by
  rw [map_sub, Polynomial.aeval_X, Polynomial.aeval_C]
  ext v i
  simp [jordanBlock, Module.algebraMap_end_apply]

/-- `V_{λ,n}` has `k`-dimension `n`. -/
@[simp] lemma finrank_jordanRep (lam : k) (n : ℕ) :
    Module.finrank k (jordanRep lam n) = n := by
  rw [← (Module.AEval'.of (jordanBlock lam n)).finrank_eq]
  simp

/-- Evaluation at the cyclic vector: the `k[X]`-linear map `k[X] → V_{λ,n}`, `q ↦ q • e_{n-1}`. -/
noncomputable def cyclicMap (lam : k) (n : ℕ) [NeZero n] :
    Polynomial k →ₗ[Polynomial k] jordanRep lam n :=
  LinearMap.toSpanSingleton (Polynomial k) (jordanRep lam n)
    (Module.AEval'.of (jordanBlock lam n) (eTop n))

/-- The cyclic map evaluates a polynomial at the Jordan block and applies it to the top vector. -/
lemma cyclicMap_apply (lam : k) (n : ℕ) [NeZero n] (q : Polynomial k) :
    cyclicMap lam n q
      = Module.AEval'.of (jordanBlock lam n) (Polynomial.aeval (jordanBlock lam n) q (eTop n)) :=
  rfl

/-- The cyclic map sends `(X - λ)ʲ` to the `j`th shift of the top vector. -/
lemma cyclicMap_X_sub_C_pow (lam : k) (n : ℕ) [NeZero n] (j : ℕ) :
    cyclicMap lam n ((X - C lam) ^ j)
      = Module.AEval'.of (jordanBlock lam n) (((shift n) ^ j) (eTop n)) := by
  rw [cyclicMap_apply, map_pow, aeval_jordanBlock_X_sub_C]

/-- The shift on `kⁿ` is nilpotent of index exactly `n`. -/
lemma shift_pow_self (n : ℕ) : ((shift n : (Fin n → k) →ₗ[k] (Fin n → k)) ^ n) = 0 := by
  apply LinearMap.ext; intro v; funext i
  rw [shift_pow_apply, dif_neg (by omega : ¬ (i : ℕ) + n < n)]
  simp

/-- `(X - λ)ⁿ` annihilates the cyclic vector, since the shift is nilpotent of index `n`. -/
lemma cyclicMap_X_sub_C_pow_self (lam : k) (n : ℕ) [NeZero n] :
    cyclicMap lam n ((X - C lam) ^ n) = 0 := by
  rw [cyclicMap_X_sub_C_pow, shift_pow_self]
  simp

/-- The cyclic vector generates: `q ↦ q • e_{n-1}` is onto `V_{λ,n}`. -/
lemma cyclicMap_surjective (lam : k) (n : ℕ) [NeZero n] :
    Function.Surjective (cyclicMap lam n) := by
  set of := Module.AEval'.of (jordanBlock lam n) with hof
  -- every standard basis vector is `(X-λ)^{n-1-i} • e_{n-1}`
  have hbasis : ∀ i : Fin n,
      of (Pi.single i 1) ∈ LinearMap.range (cyclicMap lam n) := by
    intro i
    have hi := i.isLt
    refine ⟨(X - C lam) ^ (n - 1 - (i : ℕ)), ?_⟩
    rw [cyclicMap_X_sub_C_pow, shift_pow_eTop n (by omega)]
    have hidx : (⟨n - 1 - (n - 1 - (i : ℕ)), by omega⟩ : Fin n) = i :=
      Fin.ext (show n - 1 - (n - 1 - (i : ℕ)) = (i : ℕ) by omega)
    rw [hidx]
  -- the standard basis spans, so the (a fortiori `k`-) submodule they generate is everything
  have hspan : Submodule.span k (Set.range fun i : Fin n => (Pi.single i 1 : Fin n → k)) = ⊤ := by
    rw [show (fun i : Fin n => (Pi.single i 1 : Fin n → k)) = ⇑(Pi.basisFun k (Fin n)) from
      funext fun i => (Pi.basisFun_apply k (Fin n) i).symm]
    exact (Pi.basisFun k (Fin n)).span_eq
  have htop : (⊤ : Submodule k (Fin n → k)) ≤
      Submodule.comap (of : (Fin n → k) →ₗ[k] jordanRep lam n)
        ((LinearMap.range (cyclicMap lam n)).restrictScalars k) := by
    rw [← hspan, Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    exact hbasis i
  intro y
  have := htop (Submodule.mem_top (x := of.symm y))
  rw [Submodule.mem_comap] at this
  simpa using this

/-- **The cyclic model of a Jordan block.** `V_{λ,n} ≅ k[X]/((X-λ)ⁿ)` as `k[X]`-modules.

Both sides have `k`-dimension `n`, and `q ↦ q • e_{n-1}` is a surjection killing `(X-λ)ⁿ`,
so the induced map out of the quotient is an isomorphism. -/
noncomputable def jordanQuotEquiv (lam : k) (n : ℕ) [NeZero n] :
    (Polynomial k ⧸ Ideal.span {(X - C lam) ^ n}) ≃ₗ[Polynomial k] jordanRep lam n := by
  haveI : Module.Finite k (Polynomial k ⧸ Ideal.span {(X - C lam) ^ n}) :=
    ((monic_X_sub_C lam).pow n).finite_quotient
  have hle : Ideal.span {(X - C lam) ^ n} ≤ LinearMap.ker (cyclicMap lam n) := by
    rw [Ideal.span_le]
    rintro _ rfl
    exact cyclicMap_X_sub_C_pow_self lam n
  refine LinearEquiv.ofBijective (Submodule.liftQ _ (cyclicMap lam n) hle) ⟨?_, ?_⟩
  · -- injective, by equality of `k`-dimensions
    have hdim : Module.finrank k (Polynomial k ⧸ Ideal.span {(X - C lam) ^ n})
        = Module.finrank k (jordanRep lam n) := by
      rw [finrank_quotient_span_eq_natDegree, finrank_jordanRep]
      simp [Polynomial.natDegree_pow]
    have := (LinearMap.injective_iff_surjective_of_finrank_eq_finrank (K := k) hdim
      (f := (Submodule.liftQ _ (cyclicMap lam n) hle).restrictScalars k)).2
    exact this (fun y => by
      obtain ⟨q, hq⟩ := cyclicMap_surjective lam n y
      exact ⟨Submodule.Quotient.mk q, hq⟩)
  · intro y
    obtain ⟨q, hq⟩ := cyclicMap_surjective lam n y
    exact ⟨Submodule.Quotient.mk q, hq⟩

/-!
## The converse: every finite-dimensional indecomposable `k[X]`-module is a Jordan block

This is the second half of Etingof Example 2.3.14(2), the content the book attributes to the
existence and uniqueness of Jordan normal form. We get it from the structure theorem for
finitely generated modules over the principal ideal domain `k[X]`: such a module is a finite
direct sum of cyclic primary pieces `k[X]/(pᵉ)`, indecomposability leaves exactly one piece,
over an algebraically closed field `p` is linear, and `k[X]/((X-λ)ⁿ)` is the Jordan block
`V_{λ,n}` by `jordanQuotEquiv`.
-/

/-- Indecomposability transfers along a linear equivalence. -/
lemma IsIndecomposable.congr {R : Type*} [Ring R] {M N : Type*} [AddCommGroup M] [Module R M]
    [AddCommGroup N] [Module R N] (e : M ≃ₗ[R] N) (h : IsIndecomposable R M) :
    IsIndecomposable R N := by
  haveI := h.1
  refine ⟨e.symm.toEquiv.nontrivial, fun A B hAB => ?_⟩
  set f := Submodule.orderIsoMapComap e with hf
  rcases h.2 (f.symm A) (f.symm B) (f.symm.isCompl hAB) with hbot | hbot
  · exact Or.inl (by rw [← f.apply_symm_apply A, hbot, f.map_bot])
  · exact Or.inr (by rw [← f.apply_symm_apply B, hbot, f.map_bot])

/-- An indecomposable module presented as a finite product of modules is isomorphic to one of
the factors: the factor inclusions cut the product into complementary pieces, so all but one
factor must vanish. -/
lemma exists_equiv_of_equiv_pi {R : Type*} [Ring R] {M : Type*} [AddCommGroup M] [Module R M]
    {ι : Type*} [Finite ι] (φ : ι → Type*) [∀ i, AddCommGroup (φ i)] [∀ i, Module R (φ i)]
    (e : M ≃ₗ[R] ∀ i, φ i) (h : IsIndecomposable R M) :
    ∃ i, Nonempty (M ≃ₗ[R] φ i) := by
  classical
  haveI := h.1
  have hind : IsIndecomposable R (∀ i, φ i) := IsIndecomposable.congr e h
  haveI := hind.1
  set P : ι → Submodule R (∀ i, φ i) := fun i => LinearMap.range (LinearMap.single R φ i) with hP
  have hsup : ⨆ i, P i = ⊤ := LinearMap.iSup_range_single R φ
  -- some factor is nonzero, else the whole product would be
  obtain ⟨i₀, hi₀⟩ : ∃ i, P i ≠ ⊥ := by
    by_contra hcon
    have hcon' : ∀ i, P i = ⊥ := fun i => not_not.mp fun hne => hcon ⟨i, hne⟩
    exact top_ne_bot (α := Submodule R (∀ i, φ i)) (by rw [← hsup]; simp [hcon'])
  -- the `i₀` factor and the rest are complementary
  have hcompl : IsCompl (P i₀) (⨆ i ∈ ({i₀}ᶜ : Set ι), P i) := by
    constructor
    · have hd := LinearMap.disjoint_single_single R φ {i₀} {i₀}ᶜ disjoint_compl_right
      rwa [iSup_singleton] at hd
    · rw [codisjoint_iff, eq_top_iff, ← hsup]
      refine iSup_le fun i => ?_
      by_cases hi : i = i₀
      · exact hi ▸ le_sup_left
      · exact le_sup_of_le_right (le_biSup P hi)
  rcases hind.2 _ _ hcompl with hbot | hbot
  · exact absurd hbot hi₀
  -- so the `i₀` factor is everything
  have htop : P i₀ = ⊤ := by
    have := hcompl.sup_eq_top
    rwa [hbot, sup_bot_eq] at this
  refine ⟨i₀, ⟨e.trans (LinearEquiv.ofBijective (LinearMap.single R φ i₀) ⟨?_, ?_⟩).symm⟩⟩
  · rw [← LinearMap.ker_eq_bot]; exact LinearMap.ker_single R φ i₀
  · rw [← LinearMap.range_eq_top]; exact htop

section Converse

variable (M : Type*) [AddCommGroup M] [Module k M] [Module (Polynomial k) M]
  [IsScalarTower k (Polynomial k) M]

/-- A `k[X]`-module that is finite dimensional over `k` is a torsion `k[X]`-module: no element
can generate a free `k[X]`-submodule, because `k[X]` is infinite dimensional over `k`. -/
lemma isTorsion_of_finiteDimensional [FiniteDimensional k M] :
    Module.IsTorsion (Polynomial k) M := by
  intro m
  have hnotinj : ¬ Function.Injective
      ((LinearMap.toSpanSingleton (Polynomial k) M m).restrictScalars k) := fun hinj =>
    Polynomial.not_finite (Module.Finite.of_injective _ hinj)
  rw [← LinearMap.ker_eq_bot] at hnotinj
  obtain ⟨q, hq, hqne⟩ := (Submodule.ne_bot_iff _).mp hnotinj
  exact ⟨⟨q, mem_nonZeroDivisors_of_ne_zero hqne⟩, LinearMap.mem_ker.mp hq⟩

/-- **Jordan normal form, in representation-theoretic form.** Every finite-dimensional
`k[X]`-representation over an algebraically closed field is a finite direct sum of Jordan-block
representations. A finite product is Mathlib's model for this finite direct sum. -/
theorem exists_equiv_pi_jordanRep [IsAlgClosed k] [FiniteDimensional k M] :
    ∃ (m : ℕ) (lam : Fin m → k) (n : Fin m → ℕ),
      (∀ i, 0 < n i) ∧
        Nonempty (M ≃ₗ[Polynomial k] ∀ i : Fin m, jordanRep (lam i) (n i)) := by
  classical
  let R := Polynomial k
  haveI : Module.Finite R M := Module.Finite.of_restrictScalars_finite k R M
  obtain ⟨ι, instι, p, hp, expo, ⟨estr⟩⟩ :=
    Module.equiv_directSum_of_isTorsion (isTorsion_of_finiteDimensional (k := k) M)
  letI : Fintype ι := instι
  let I := {i : ι // 0 < expo i}
  let Q : ι → Type _ := fun i => R ⧸ (R ∙ p i ^ expo i)
  -- Discard the zero summands arising from exponent zero.
  let dropZero : (∀ i : ι, Q i) ≃ₗ[R] ∀ i : I, Q i := {
    toFun := fun f i => f i
    invFun := fun f i => if hi : 0 < expo i then f ⟨i, hi⟩ else 0
    left_inv := by
      intro f
      funext i
      by_cases hi : 0 < expo i
      · simp [hi]
      · have hzero : expo i = 0 := Nat.eq_zero_of_not_pos hi
        haveI : Subsingleton (Q i) := by
          dsimp [Q]
          rw [hzero, pow_zero, Ideal.submodule_span_eq, Ideal.span_singleton_one]
          infer_instance
        exact Subsingleton.elim _ _
    right_inv := by
      intro f
      funext i
      change (if hi : 0 < expo (i : ι) then f ⟨i, hi⟩ else 0) = f i
      rw [dif_pos i.property]
    map_add' := by intro f g; rfl
    map_smul' := by intro c f; rfl }
  -- Every irreducible polynomial over an algebraically closed field is associated to `X - λ`.
  have hassoc : ∀ i : I, ∃ lam : k, Associated (X - C lam) (p i) := by
    intro i
    have hdeg : (p i).degree ≠ 0 := fun hd =>
      (hp i).not_isUnit (Polynomial.isUnit_iff_degree_eq_zero.mpr hd)
    obtain ⟨lam, hlam⟩ := IsAlgClosed.exists_root (p i) hdeg
    exact ⟨lam, (Polynomial.irreducible_X_sub_C lam).associated_of_dvd (hp i)
      (Polynomial.dvd_iff_isRoot.mpr hlam)⟩
  choose lam hlam using hassoc
  let blockEquiv : ∀ i : I, Q i ≃ₗ[R] jordanRep (lam i) (expo i) := fun i => by
    letI : NeZero (expo i) := ⟨Nat.ne_of_gt i.property⟩
    refine (Submodule.quotEquivOfEq _ _ ?_).trans (jordanQuotEquiv (lam i) (expo i))
    rw [Ideal.submodule_span_eq]
    exact Ideal.span_singleton_eq_span_singleton.mpr
      ((hlam i).pow_pow (n := expo i)).symm
  let e : Fin (Fintype.card I) ≃ I := (Fintype.equivFin I).symm
  refine ⟨Fintype.card I, lam ∘ e, fun i => expo (e i), fun i => (e i).property, ?_⟩
  exact ⟨estr.trans (DirectSum.linearEquivFunOnFintype R ι Q) |>.trans dropZero |>.trans
    (LinearEquiv.piCongrRight blockEquiv) |>.trans
    (LinearEquiv.piCongrLeft R (fun i : I => jordanRep (lam i) (expo i)) e).symm⟩

/-- **Etingof Example 2.3.14(2), the classification.** Over an algebraically closed field,
every finite-dimensional indecomposable `k[X]`-representation is isomorphic to a Jordan block
`V_{λ,n} = (kⁿ, ρ(x) = J_{λ,n})` with `n ≥ 1`.

Together with `jordanRep_indecomposable` (each `V_{λ,n}` is indecomposable) and
`jordanRep_equiv_iff` (they are pairwise nonisomorphic), this is the book's statement that the
`V_{λ,n}` are exactly the finite-dimensional indecomposable representations of `k[x]`. -/
theorem exists_equiv_jordanRep [IsAlgClosed k] [FiniteDimensional k M]
    (h : IsIndecomposable (Polynomial k) M) :
    ∃ (lam : k) (n : ℕ), 0 < n ∧ Nonempty (M ≃ₗ[Polynomial k] jordanRep lam n) := by
  classical
  haveI := h.1
  haveI : Module.Finite (Polynomial k) M := Module.Finite.of_restrictScalars_finite k _ _
  -- structure theorem over the PID `k[X]`
  obtain ⟨ι, _, p, hp, expo, ⟨estr⟩⟩ :=
    Module.equiv_directSum_of_isTorsion (isTorsion_of_finiteDimensional (k := k) M)
  -- indecomposability keeps exactly one summand
  obtain ⟨i, ⟨eqi⟩⟩ := exists_equiv_of_equiv_pi _
    (estr.trans (DirectSum.linearEquivFunOnFintype _ _ _)) h
  -- over an algebraically closed field the irreducible `p i` is linear
  have hdeg : (p i).degree ≠ 0 := fun hd =>
    (hp i).not_isUnit (Polynomial.isUnit_iff_degree_eq_zero.mpr hd)
  obtain ⟨lam, hlam⟩ := IsAlgClosed.exists_root (p i) hdeg
  have hassoc : Associated (X - C lam) (p i) :=
    (Polynomial.irreducible_X_sub_C lam).associated_of_dvd (hp i)
      (Polynomial.dvd_iff_isRoot.mpr hlam)
  -- the exponent is positive, else the summand would be the zero module
  have hpos : 0 < expo i := by
    rcases Nat.eq_zero_or_pos (expo i) with h0 | h0
    · exfalso
      have : Subsingleton (Polynomial k ⧸ (Polynomial k) ∙ p i ^ expo i) := by
        rw [h0, pow_zero, Ideal.submodule_span_eq, Ideal.span_singleton_one]
        infer_instance
      exact not_subsingleton M (eqi.toEquiv.subsingleton)
    · exact h0
  haveI : NeZero (expo i) := ⟨by omega⟩
  refine ⟨lam, expo i, hpos, ⟨eqi.trans ((Submodule.quotEquivOfEq _ _ ?_).trans
    (jordanQuotEquiv lam (expo i)))⟩⟩
  rw [Ideal.submodule_span_eq]
  exact Ideal.span_singleton_eq_span_singleton.mpr (hassoc.pow_pow (n := expo i)).symm

end Converse

/-!
## The Jordan blocks are pairwise nonisomorphic

The dimension pins down `n`; the eigenvalue is pinned down because `(X-λ)ⁿ` annihilates
`V_{λ,n}`, while on `V_{μ,m}` the operator `X - λ` is `(μ-λ)·id + S` with `S` nilpotent, which
is nilpotent only when `λ = μ`.
-/

/-- On `V_{μ,n}`, the element `X - λ` acts as `(μ - λ)·id` plus the nilpotent shift. -/
lemma aeval_jordanBlock_X_sub_C' (lam mu : k) (n : ℕ) :
    Polynomial.aeval (jordanBlock mu n) (X - C lam)
      = (mu - lam) • (1 : Module.End k (Fin n → k)) + shift n := by
  rw [map_sub, Polynomial.aeval_X, Polynomial.aeval_C]
  ext v i
  simp [jordanBlock, Module.algebraMap_end_apply, sub_smul]
  ring

/-- `(X - λ)ⁿ` annihilates every element of `V_{λ,n}`. -/
lemma X_sub_C_pow_smul_jordanRep (lam : k) (n : ℕ) (v : jordanRep lam n) :
    ((X - C lam) ^ n : Polynomial k) • v = 0 := by
  obtain ⟨w, rfl⟩ := (Module.AEval'.of (jordanBlock lam n)).surjective v
  have hsmul : ((X - C lam) ^ n : Polynomial k) • (Module.AEval'.of (jordanBlock lam n) w)
      = Module.AEval'.of (jordanBlock lam n)
        (Polynomial.aeval (jordanBlock lam n) ((X - C lam) ^ n) w) := rfl
  rw [hsmul, map_pow, aeval_jordanBlock_X_sub_C, shift_pow_self]
  simp

/-- **The Jordan blocks are pairwise nonisomorphic.** `V_{λ,n} ≅ V_{μ,m}` as `k[X]`-modules
forces `λ = μ` and `n = m`. (Etingof Example 2.3.14(2): "clearly, these representations are
pairwise nonisomorphic".) -/
theorem jordanRep_equiv_iff (lam mu : k) (n m : ℕ) [NeZero n] [NeZero m] :
    Nonempty (jordanRep lam n ≃ₗ[Polynomial k] jordanRep mu m) ↔ lam = mu ∧ n = m := by
  refine ⟨fun ⟨e⟩ => ?_, fun ⟨h1, h2⟩ => h1 ▸ h2 ▸ ⟨LinearEquiv.refl _ _⟩⟩
  have hnm : n = m := by
    have h := (e.restrictScalars k).finrank_eq
    rwa [finrank_jordanRep, finrank_jordanRep] at h
  refine ⟨?_, hnm⟩
  by_contra hne
  -- `(X-λ)ⁿ` kills `V_{λ,n}`, hence — transporting along `e` — also `V_{μ,m}`
  have hop : Polynomial.aeval (jordanBlock mu m) ((X - C lam) ^ n) = 0 := by
    apply LinearMap.ext
    intro w
    have h := X_sub_C_pow_smul_jordanRep lam n (e.symm (Module.AEval'.of (jordanBlock mu m) w))
    have h2 := congrArg e h
    rw [map_smul, e.apply_symm_apply, map_zero] at h2
    exact (map_eq_zero_iff _ (Module.AEval'.of (jordanBlock mu m)).injective).mp h2
  -- so `(μ-λ)·id + S` is nilpotent; subtracting the nilpotent `S` makes `(μ-λ)·id` nilpotent
  set A := Polynomial.aeval (jordanBlock mu m) (X - C lam) with hA
  have hAnil : IsNilpotent A := ⟨n, by rw [hA, ← map_pow]; exact hop⟩
  have hAeq : A = (mu - lam) • (1 : Module.End k (Fin m → k)) + shift m :=
    aeval_jordanBlock_X_sub_C' lam mu m
  have hcomm : Commute A (shift m) := by
    rw [hAeq]
    exact Commute.add_left ((Commute.one_left _).smul_left _) (Commute.refl _)
  have hscal : IsNilpotent ((mu - lam) • (1 : Module.End k (Fin m → k))) := by
    have := hcomm.isNilpotent_sub hAnil (shift_nilpotent m)
    rwa [hAeq, add_sub_cancel_right] at this
  -- a nilpotent scalar on a nonzero space is zero
  obtain ⟨j, hj⟩ := hscal
  rw [smul_pow, one_pow] at hj
  have hvec : ((mu - lam) ^ j) • (e0 m : Fin m → k) = 0 := by
    have := congrArg (fun f : Module.End k (Fin m → k) => f (e0 m)) hj
    simpa using this
  have hpow : (mu - lam) ^ j = 0 := (smul_eq_zero.mp hvec).resolve_right (e0_ne_zero m)
  rcases Nat.eq_zero_or_pos j with hj0 | hj0
  · rw [hj0, pow_zero] at hpow; exact one_ne_zero hpow
  · exact hne (by have := pow_eq_zero_iff (n := j) (by omega) |>.mp hpow; linear_combination -this)

attribute [nolint defsWithUnderscore]
  shift jordanBlock e0 jordanRep eTop cyclicMap jordanQuotEquiv

end Etingof.Example_2_3_14
