import Mathlib.Algebra.Lie.Basic
import Mathlib.Algebra.Lie.OfAssociative
import Mathlib.Algebra.Lie.UniversalEnveloping
import Mathlib.RingTheory.TwoSidedIdeal.Operations
import Mathlib.RingTheory.Congruence.Basic

/-!
# Example 2.9.13: Universal Enveloping Algebra of the Heisenberg Lie Algebra

The algebra U(ℋ), where ℋ is the Heisenberg Lie algebra, is the algebra generated by
x, y, c with the relations:

  yx − xy = c,  yc − cy = 0,  xc − cx = 0.

Note that the Weyl algebra is the quotient of U(ℋ) by the relation c = 1.

## Formalization

The Heisenberg Lie algebra `ℋ` is the 3-dimensional Lie algebra with basis `x, y, c`, the only
nonzero bracket being `⁅y, x⁆ = c` (equivalently `⁅x, y⁆ = -c`), with `c` central. We construct it
concretely as `k × k × k` with the bracket landing in the central `c`-coordinate, and verify the
defining bracket relations.

The genuine, non-vacuous content (the previous statement was the same `inferInstance` example as
2.9.12, provable for *any* Lie algebra and asserting nothing about the Heisenberg presentation) is:

* `Heisenberg` is a genuine Lie algebra with the stated brackets (`bracket_y_x`, `bracket_x_c`,
  `bracket_y_c`);
* inside `U(ℋ)`, the images `X = ι x`, `Y = ι y`, `C = ι c` satisfy the book's relations
  `YX − XY = C`, `YC − CY = 0`, `XC − CX = 0` (`heisenberg_universal_relations`). These are
  *specific* to the Heisenberg algebra — they are not provable for an arbitrary `L`;
* the Weyl algebra is `U(ℋ) ⧸ (C − 1)`, in which `C` becomes `1` (`weyl_c_eq_one`).

## Mathlib correspondence

Mathlib has `UniversalEnvelopingAlgebra` but the Heisenberg Lie algebra is not defined, so we build
it here. The full universal property (that `x, y, c` *generate* `U(ℋ)` and that these relations are
a complete presentation) and the identification of `U(ℋ)/(c−1)` with an abstractly-defined Weyl
algebra are beyond current Mathlib infrastructure; we assert and prove the defining relations, which
is the content the previous statement was missing.
-/

namespace Etingof.Example2_9_13

open UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing

variable {k : Type*} [CommRing k]

/-- The Heisenberg Lie algebra over `k`: the 3-dimensional space `k·x ⊕ k·y ⊕ k·c`, carried by
`k × k × k`. The triple `(a, b, d)` denotes `a·x + b·y + d·c`. -/
def Heisenberg (k : Type*) [CommRing k] : Type _ := k × k × k

instance : AddCommGroup (Heisenberg k) := inferInstanceAs (AddCommGroup (k × k × k))

instance : Module k (Heisenberg k) := inferInstanceAs (Module k (k × k × k))

@[ext] theorem Heisenberg.ext {a b : Heisenberg k}
    (h1 : a.1 = b.1) (h2 : a.2.1 = b.2.1) (h3 : a.2.2 = b.2.2) : a = b :=
  Prod.ext h1 (Prod.ext h2 h3)

-- Projection lemmas for the (componentwise) module structure. They are `rfl` but stated so that
-- `simp` can rewrite through the `Heisenberg` type synonym (whose add/zero/smul instances do not
-- syntactically match the generic `Prod` lemmas).
@[simp] theorem add_fst (a b : Heisenberg k) : (a + b).1 = a.1 + b.1 := rfl
@[simp] theorem add_snd_fst (a b : Heisenberg k) : (a + b).2.1 = a.2.1 + b.2.1 := rfl
@[simp] theorem add_snd_snd (a b : Heisenberg k) : (a + b).2.2 = a.2.2 + b.2.2 := rfl
@[simp] theorem zero_fst : (0 : Heisenberg k).1 = 0 := rfl
@[simp] theorem zero_snd_fst : (0 : Heisenberg k).2.1 = 0 := rfl
@[simp] theorem zero_snd_snd : (0 : Heisenberg k).2.2 = 0 := rfl
@[simp] theorem smul_fst (t : k) (a : Heisenberg k) : (t • a).1 = t • a.1 := rfl
@[simp] theorem smul_snd_fst (t : k) (a : Heisenberg k) : (t • a).2.1 = t • a.2.1 := rfl
@[simp] theorem smul_snd_snd (t : k) (a : Heisenberg k) : (t • a).2.2 = t • a.2.2 := rfl

/-- The Heisenberg bracket: `⁅u, v⁆ = (v₁·u₂ − u₁·v₂)·c`, landing in the central `c`-coordinate.
With the basis convention `(a,b,d) = a·x + b·y + d·c`, this gives `⁅y, x⁆ = c` and `c` central. -/
instance : Bracket (Heisenberg k) (Heisenberg k) where
  bracket u v := ((0 : k), (0 : k), v.1 * u.2.1 - u.1 * v.2.1)

@[simp]
theorem bracket_def (u v : Heisenberg k) :
    ⁅u, v⁆ = ((0 : k), (0 : k), v.1 * u.2.1 - u.1 * v.2.1) := rfl

instance : LieRing (Heisenberg k) where
  add_lie x y z := by
    apply Heisenberg.ext <;>
      simp only [bracket_def, add_fst, add_snd_fst, add_snd_snd] <;> ring
  lie_add x y z := by
    apply Heisenberg.ext <;>
      simp only [bracket_def, add_fst, add_snd_fst, add_snd_snd] <;> ring
  lie_self x := by
    apply Heisenberg.ext <;> simp [bracket_def]
  leibniz_lie x y z := by
    apply Heisenberg.ext <;>
      simp only [bracket_def, add_fst, add_snd_fst, add_snd_snd] <;> ring

instance : LieAlgebra k (Heisenberg k) where
  lie_smul t x y := by
    apply Heisenberg.ext <;>
      simp only [bracket_def, smul_fst, smul_snd_fst, smul_snd_snd, smul_eq_mul] <;> ring

/-- The basis vector `x` of the Heisenberg Lie algebra. -/
def x : Heisenberg k := ((1 : k), (0 : k), (0 : k))

/-- The basis vector `y` of the Heisenberg Lie algebra. -/
def y : Heisenberg k := ((0 : k), (1 : k), (0 : k))

/-- The central basis vector `c` of the Heisenberg Lie algebra. -/
def c : Heisenberg k := ((0 : k), (0 : k), (1 : k))

@[simp] theorem bracket_y_x : ⁅(y : Heisenberg k), (x : Heisenberg k)⁆ = (c : Heisenberg k) := by
  simp [bracket_def, x, y, c]

@[simp] theorem bracket_x_c : ⁅(x : Heisenberg k), (c : Heisenberg k)⁆ = 0 := by
  apply Heisenberg.ext <;> simp [bracket_def, x, c]

@[simp] theorem bracket_y_c : ⁅(y : Heisenberg k), (c : Heisenberg k)⁆ = 0 := by
  apply Heisenberg.ext <;> simp [bracket_def, y, c]

/-- **Example 2.9.13.** The defining relations of `U(ℋ)`: writing `X = ι x`, `Y = ι y`, `C = ι c`
for the images of the Heisenberg generators in the universal enveloping algebra, we have

  `YX − XY = C`,  `YC − CY = 0`,  `XC − CX = 0`.

These are exactly the book's relations `yx − xy = c`, `yc − cy = 0`, `xc − cx = 0`. Unlike the
generic `Algebra k (UniversalEnvelopingAlgebra k L)` statement (which holds for any `L`), these
relations are specific to the Heisenberg presentation. -/
theorem heisenberg_universal_relations (k : Type*) [CommRing k] :
    (ι k (y : Heisenberg k)) * (ι k x) - (ι k x) * (ι k y) = ι k c ∧
    (ι k (y : Heisenberg k)) * (ι k c) - (ι k c) * (ι k y) = 0 ∧
    (ι k (x : Heisenberg k)) * (ι k c) - (ι k c) * (ι k x) = 0 := by
  refine ⟨?_, ?_, ?_⟩
  · rw [← LieRing.of_associative_ring_bracket, ← LieHom.map_lie, bracket_y_x]
  · rw [← LieRing.of_associative_ring_bracket, ← LieHom.map_lie, bracket_y_c, map_zero]
  · rw [← LieRing.of_associative_ring_bracket, ← LieHom.map_lie, bracket_x_c, map_zero]

/-- The two-sided congruence on `U(ℋ)` generated by `C − 1`, defining the Weyl-algebra quotient. -/
abbrev weylCon (k : Type*) [CommRing k] :
    RingCon (UniversalEnvelopingAlgebra k (Heisenberg k)) :=
  (TwoSidedIdeal.span {ι k (c : Heisenberg k) - 1}).ringCon

/-- The Weyl algebra as the quotient of `U(ℋ)` by the two-sided relation `c = 1`. -/
abbrev WeylAlgebra (k : Type*) [CommRing k] : Type _ := (weylCon k).Quotient

/-- In the Weyl algebra `U(ℋ) ⧸ (C − 1)`, the central generator `c` becomes `1`: this is the
relation `c = 1` from the book. -/
theorem weyl_c_eq_one (k : Type*) [CommRing k] :
    (weylCon k).mk' (ι k (c : Heisenberg k)) = (weylCon k).mk' 1 := by
  have h : weylCon k (ι k (c : Heisenberg k)) 1 := by
    rw [weylCon, TwoSidedIdeal.rel_iff]
    exact TwoSidedIdeal.subset_span (Set.mem_singleton _)
  exact (RingCon.eq _).mpr h

end Etingof.Example2_9_13
