import Mathlib.Algebra.Lie.Basic
import Mathlib.Algebra.Lie.Classical
import Mathlib.Algebra.Lie.OfAssociative
import Mathlib.Algebra.Lie.Sl2
import Mathlib.Algebra.Lie.UniversalEnveloping
import Mathlib.Algebra.FreeAlgebra

/-!
# Example 2.9.12: Universal Enveloping Algebra of sl(2)

The associative algebra `U(𝔰𝔩(2))` is the algebra generated by `e`, `f`, `h`, with relations

  `he − eh = 2e`,  `hf − fh = −2f`,  `ef − fe = h`.

## Formalization

`𝔰𝔩(2)` is the 3-dimensional Lie algebra with basis `e, f, h` and the brackets
`⁅h, e⁆ = 2e`, `⁅h, f⁆ = -2f`, `⁅e, f⁆ = h`. We construct it concretely as `k × k × k`, with the
triple `(a, b, d)` denoting `a·e + b·f + d·h`, and verify the defining bracket relations.

The content is:

* `sl2` is a Lie algebra with the stated brackets (`bracket_h_e`, `bracket_h_f`,
  `bracket_e_f`);
* inside `U(𝔰𝔩(2))`, the images `E = ι e`, `F = ι f`, `H = ι h` satisfy the book's relations
  `HE − EH = 2E`, `HF − FH = −2F`, `EF − FE = H` (`sl2_universal_relations`). These are specific
  to `𝔰𝔩(2)`: they are not provable for an arbitrary `L`.

## Mathlib correspondence

Mathlib has `UniversalEnvelopingAlgebra`, but `𝔰𝔩(2)` with the explicit `e, f, h` basis and these
relations is not directly available as a concrete presentation, so we build it here. The full
universal property (that `e, f, h` generate `U(𝔰𝔩(2))` and that these relations are a complete
presentation) is beyond current Mathlib infrastructure; we assert and prove the defining relations.
-/

namespace Etingof.Example2_9_12

open UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing

variable {k : Type*} [CommRing k]

/-- The Lie algebra `𝔰𝔩(2)` over `k`: the 3-dimensional space `k·e ⊕ k·f ⊕ k·h`, carried by
`k × k × k`. The triple `(a, b, d)` denotes `a·e + b·f + d·h`. -/
def sl2 (k : Type*) [CommRing k] : Type _ := k × k × k

instance : AddCommGroup (sl2 k) := inferInstanceAs (AddCommGroup (k × k × k))

instance : Module k (sl2 k) := inferInstanceAs (Module k (k × k × k))

@[ext] theorem sl2.ext {a b : sl2 k}
    (h1 : a.1 = b.1) (h2 : a.2.1 = b.2.1) (h3 : a.2.2 = b.2.2) : a = b :=
  Prod.ext h1 (Prod.ext h2 h3)

-- Projection lemmas for the (componentwise) module structure. They are `rfl` but stated so that
-- `simp` can rewrite through the `sl2` type synonym (whose add/zero/smul instances do not
-- syntactically match the generic `Prod` lemmas).
@[simp] theorem add_fst (a b : sl2 k) : (a + b).1 = a.1 + b.1 := rfl
@[simp] theorem add_snd_fst (a b : sl2 k) : (a + b).2.1 = a.2.1 + b.2.1 := rfl
@[simp] theorem add_snd_snd (a b : sl2 k) : (a + b).2.2 = a.2.2 + b.2.2 := rfl
@[simp] theorem zero_fst : (0 : sl2 k).1 = 0 := rfl
@[simp] theorem zero_snd_fst : (0 : sl2 k).2.1 = 0 := rfl
@[simp] theorem zero_snd_snd : (0 : sl2 k).2.2 = 0 := rfl
@[simp] theorem smul_fst (t : k) (a : sl2 k) : (t • a).1 = t • a.1 := rfl
@[simp] theorem smul_snd_fst (t : k) (a : sl2 k) : (t • a).2.1 = t • a.2.1 := rfl
@[simp] theorem smul_snd_snd (t : k) (a : sl2 k) : (t • a).2.2 = t • a.2.2 := rfl
@[simp] theorem neg_fst (a : sl2 k) : (-a).1 = -a.1 := rfl
@[simp] theorem neg_snd_fst (a : sl2 k) : (-a).2.1 = -a.2.1 := rfl
@[simp] theorem neg_snd_snd (a : sl2 k) : (-a).2.2 = -a.2.2 := rfl

/-- The `𝔰𝔩(2)` bracket. With the basis convention `(a, b, d) = a·e + b·f + d·h`, expanding
`⁅u, v⁆` bilinearly from `⁅h, e⁆ = 2e`, `⁅h, f⁆ = -2f`, `⁅e, f⁆ = h` (and antisymmetry) gives the
`e`-coordinate `2(d₁a₂ − a₁d₂)`, the `f`-coordinate `−2(d₁b₂ − b₁d₂)`, and the `h`-coordinate
`a₁b₂ − b₁a₂`. -/
instance : Bracket (sl2 k) (sl2 k) where
  bracket u v :=
    (2 * (u.2.2 * v.1 - u.1 * v.2.2),
     -(2 * (u.2.2 * v.2.1 - u.2.1 * v.2.2)),
     u.1 * v.2.1 - u.2.1 * v.1)

@[simp]
theorem bracket_def (u v : sl2 k) :
    ⁅u, v⁆ =
      (2 * (u.2.2 * v.1 - u.1 * v.2.2),
       -(2 * (u.2.2 * v.2.1 - u.2.1 * v.2.2)),
       u.1 * v.2.1 - u.2.1 * v.1) := rfl

instance : LieRing (sl2 k) where
  add_lie x y z := by
    apply sl2.ext <;>
      simp only [bracket_def, add_fst, add_snd_fst, add_snd_snd] <;> ring
  lie_add x y z := by
    apply sl2.ext <;>
      simp only [bracket_def, add_fst, add_snd_fst, add_snd_snd] <;> ring
  lie_self x := by
    apply sl2.ext <;> simp [bracket_def] <;> ring
  leibniz_lie x y z := by
    apply sl2.ext <;>
      simp only [bracket_def, add_fst, add_snd_fst, add_snd_snd] <;> ring

instance : LieAlgebra k (sl2 k) where
  lie_smul t x y := by
    apply sl2.ext <;>
      simp only [bracket_def, smul_fst, smul_snd_fst, smul_snd_snd, smul_eq_mul] <;> ring

/-- The basis vector `e` of `𝔰𝔩(2)`. -/
def e : sl2 k := ((1 : k), (0 : k), (0 : k))

/-- The basis vector `f` of `𝔰𝔩(2)`. -/
def f : sl2 k := ((0 : k), (1 : k), (0 : k))

/-- The basis vector `h` of `𝔰𝔩(2)`. -/
def h : sl2 k := ((0 : k), (0 : k), (1 : k))

@[simp] theorem bracket_h_e : ⁅(h : sl2 k), (e : sl2 k)⁆ = (2 : k) • (e : sl2 k) := by
  apply sl2.ext <;> simp [bracket_def, e, h]

@[simp] theorem bracket_h_f : ⁅(h : sl2 k), (f : sl2 k)⁆ = (-2 : k) • (f : sl2 k) := by
  apply sl2.ext <;> simp [bracket_def, f, h]

@[simp] theorem bracket_e_f : ⁅(e : sl2 k), (f : sl2 k)⁆ = (h : sl2 k) := by
  apply sl2.ext <;> simp [bracket_def, e, f, h]

/-- **Example 2.9.12.** The defining relations of `U(𝔰𝔩(2))`: writing `E = ι e`, `F = ι f`,
`H = ι h` for the images of the `𝔰𝔩(2)` generators in the universal enveloping algebra, we have

  `HE − EH = 2E`,  `HF − FH = −2F`,  `EF − FE = H`.

These are exactly the book's relations `he − eh = 2e`, `hf − fh = −2f`, `ef − fe = h`. Unlike the
generic `Algebra k (UniversalEnvelopingAlgebra k L)` statement (which holds for any `L`), these
relations are specific to the `𝔰𝔩(2)` presentation. -/
theorem sl2_universal_relations (k : Type*) [CommRing k] :
    (ι k (h : sl2 k)) * (ι k e) - (ι k e) * (ι k h) = (2 : k) • ι k e ∧
    (ι k (h : sl2 k)) * (ι k f) - (ι k f) * (ι k h) = (-2 : k) • ι k f ∧
    (ι k (e : sl2 k)) * (ι k f) - (ι k f) * (ι k e) = ι k h := by
  refine ⟨?_, ?_, ?_⟩
  · rw [← LieRing.of_associative_ring_bracket, ← LieHom.map_lie, bracket_h_e, map_smul]
  · rw [← LieRing.of_associative_ring_bracket, ← LieHom.map_lie, bracket_h_f, map_smul]
  · rw [← LieRing.of_associative_ring_bracket, ← LieHom.map_lie, bracket_e_f]

/-- Every element of `𝔰𝔩(2)` is the expected combination of the basis vectors `e`, `f`, `h`. -/
theorem eq_smul_e_add_smul_f_add_smul_h (x : sl2 k) :
    x = x.1 • (e : sl2 k) + x.2.1 • (f : sl2 k) + x.2.2 • (h : sl2 k) := by
  apply sl2.ext <;> simp [e, f, h]

/-! ### `e`, `f`, `h` generate `U(𝔰𝔩(2))`

The book says `U(𝔰𝔩(2))` *is the algebra generated by* `e`, `f`, `h` with the three relations.
This section proves the "generated by" half; the next section proves that the relations are a
complete presentation.
-/

/-- The image of `ι` generates the universal enveloping algebra of any Lie algebra. -/
theorem adjoin_range_ι (k : Type*) [CommRing k] (L : Type*) [LieRing L] [LieAlgebra k L] :
    Algebra.adjoin k (Set.range (ι k : L → UniversalEnvelopingAlgebra k L)) = ⊤ := by
  have hsurj : (mkAlgHom k L).range = ⊤ :=
    (AlgHom.range_eq_top _).mpr (RingQuot.mkAlgHom_surjective k (Rel k L))
  calc Algebra.adjoin k (Set.range (ι k : L → UniversalEnvelopingAlgebra k L))
      = Algebra.adjoin k (mkAlgHom k L '' Set.range (TensorAlgebra.ι k)) := by
        rw [← Set.range_comp]; rfl
    _ = (Algebra.adjoin k (Set.range (TensorAlgebra.ι k (M := L)))).map (mkAlgHom k L) :=
        (AlgHom.map_adjoin _ _).symm
    _ = (⊤ : Subalgebra k (TensorAlgebra k L)).map (mkAlgHom k L) := by
        rw [TensorAlgebra.adjoin_range_ι]
    _ = ⊤ := by rw [Algebra.map_top, hsurj]

/-- **Example 2.9.12, "generated by" half.** The three images `ι e`, `ι f`, `ι h` generate
`U(𝔰𝔩(2))` as a `k`-algebra. -/
theorem adjoin_ι_e_f_h (k : Type*) [CommRing k] :
    Algebra.adjoin k {ι k (e : sl2 k), ι k (f : sl2 k), ι k (h : sl2 k)} = ⊤ := by
  rw [eq_top_iff, ← adjoin_range_ι k (sl2 k), Algebra.adjoin_le_iff]
  rintro _ ⟨x, rfl⟩
  rw [eq_smul_e_add_smul_f_add_smul_h x, map_add, map_add, map_smul, map_smul, map_smul]
  set S := Algebra.adjoin k {ι k (e : sl2 k), ι k (f : sl2 k), ι k (h : sl2 k)} with hS
  have he : ι k (e : sl2 k) ∈ S := Algebra.subset_adjoin (by simp)
  have hf : ι k (f : sl2 k) ∈ S := Algebra.subset_adjoin (by simp)
  have hh : ι k (h : sl2 k) ∈ S := Algebra.subset_adjoin (by simp)
  exact add_mem (add_mem (Subalgebra.smul_mem _ he _) (Subalgebra.smul_mem _ hf _))
    (Subalgebra.smul_mem _ hh _)

/-! ### The universal property of the three relations

A triple `(X, Y, Z)` in an associative `k`-algebra satisfying the book's three relations is the
same thing as a Lie algebra morphism out of `𝔰𝔩(2)`. This is the computational heart of the
presentation theorem: it is used once for the presented algebra and once for `U(𝔰𝔩(2))` itself.
-/

section Triple

variable {A : Type*} [Ring A] [Algebra k A]

/-- A triple `(X, Y, Z)` in an associative `k`-algebra satisfying the `𝔰𝔩(2)` relations
`ZX − XZ = 2X`, `ZY − YZ = −2Y`, `XY − YX = Z` determines a Lie algebra morphism
`𝔰𝔩(2) →ₗ⁅k⁆ A` sending `e ↦ X`, `f ↦ Y`, `h ↦ Z`. -/
def liftTriple (X Y Z : A) (hX : Z * X - X * Z = (2 : k) • X)
    (hY : Z * Y - Y * Z = (-2 : k) • Y) (hZ : X * Y - Y * X = Z) : sl2 k →ₗ⁅k⁆ A where
  toFun u := u.1 • X + u.2.1 • Y + u.2.2 • Z
  map_add' u v := by
    simp only [add_fst, add_snd_fst, add_snd_snd, add_smul]
    abel
  map_smul' t u := by
    simp only [smul_fst, smul_snd_fst, smul_snd_snd, smul_eq_mul, RingHom.id_apply,
      smul_add, smul_smul]
  map_lie' {u v} := by
    obtain ⟨a₁, b₁, d₁⟩ := u
    obtain ⟨a₂, b₂, d₂⟩ := v
    have expand :
        (a₁ • X + b₁ • Y + d₁ • Z) * (a₂ • X + b₂ • Y + d₂ • Z) -
            (a₂ • X + b₂ • Y + d₂ • Z) * (a₁ • X + b₁ • Y + d₁ • Z) =
          (a₁ * b₂ - b₁ * a₂) • (X * Y - Y * X) + (d₁ * a₂ - a₁ * d₂) • (Z * X - X * Z) +
            (d₁ * b₂ - b₁ * d₂) • (Z * Y - Y * Z) := by
      simp only [add_mul, mul_add, smul_mul_smul_comm, smul_sub]
      module
    simp only [LieRing.of_associative_ring_bracket, bracket_def]
    rw [expand, hX, hY, hZ]
    module

@[simp] theorem liftTriple_apply (X Y Z : A) (hX : Z * X - X * Z = (2 : k) • X)
    (hY : Z * Y - Y * Z = (-2 : k) • Y) (hZ : X * Y - Y * X = Z) (u : sl2 k) :
    liftTriple X Y Z hX hY hZ u = u.1 • X + u.2.1 • Y + u.2.2 • Z := rfl

@[simp] theorem liftTriple_e (X Y Z : A) (hX : Z * X - X * Z = (2 : k) • X)
    (hY : Z * Y - Y * Z = (-2 : k) • Y) (hZ : X * Y - Y * X = Z) :
    liftTriple X Y Z hX hY hZ (e : sl2 k) = X := by simp [e]

@[simp] theorem liftTriple_f (X Y Z : A) (hX : Z * X - X * Z = (2 : k) • X)
    (hY : Z * Y - Y * Z = (-2 : k) • Y) (hZ : X * Y - Y * X = Z) :
    liftTriple X Y Z hX hY hZ (f : sl2 k) = Y := by simp [f]

@[simp] theorem liftTriple_h (X Y Z : A) (hX : Z * X - X * Z = (2 : k) • X)
    (hY : Z * Y - Y * Z = (-2 : k) • Y) (hZ : X * Y - Y * X = Z) :
    liftTriple X Y Z hX hY hZ (h : sl2 k) = Z := by simp [h]

end Triple

/-! ### The presentation of `U(𝔰𝔩(2))` by generators and relations

The book's claim is that `U(𝔰𝔩(2))` **is** the algebra generated by `e`, `f`, `h` subject only to
`he − eh = 2e`, `hf − fh = −2f`, `ef − fe = h`. We build that algebra directly — the free
`k`-algebra on three generators modulo the two-sided congruence generated by the three relations —
and prove it is isomorphic to `U(𝔰𝔩(2))` as a `k`-algebra, by an isomorphism matching the
generators up.
-/

section Presentation

/-- The three defining relations of the book's presentation, as a relation on the free
`k`-algebra on `Fin 3`. The generators `0`, `1`, `2` stand for `e`, `f`, `h`. -/
inductive PresRel (k : Type*) [CommRing k] :
    FreeAlgebra k (Fin 3) → FreeAlgebra k (Fin 3) → Prop
  | he : PresRel k
      (FreeAlgebra.ι k 2 * FreeAlgebra.ι k 0 - FreeAlgebra.ι k 0 * FreeAlgebra.ι k 2)
      ((2 : k) • FreeAlgebra.ι k 0)
  | hf : PresRel k
      (FreeAlgebra.ι k 2 * FreeAlgebra.ι k 1 - FreeAlgebra.ι k 1 * FreeAlgebra.ι k 2)
      ((-2 : k) • FreeAlgebra.ι k 1)
  | ef : PresRel k
      (FreeAlgebra.ι k 0 * FreeAlgebra.ι k 1 - FreeAlgebra.ι k 1 * FreeAlgebra.ι k 0)
      (FreeAlgebra.ι k 2)

/-- The algebra generated by `e`, `f`, `h` with the book's three relations: the free `k`-algebra
on three generators, quotiented by the relations of `PresRel`. -/
def Presentation (k : Type*) [CommRing k] : Type _ := RingQuot (PresRel k)

instance : Ring (Presentation k) := inferInstanceAs (Ring (RingQuot (PresRel k)))

instance : Algebra k (Presentation k) := inferInstanceAs (Algebra k (RingQuot (PresRel k)))

/-- The quotient map onto the presented algebra. -/
def presMk (k : Type*) [CommRing k] : FreeAlgebra k (Fin 3) →ₐ[k] Presentation k :=
  RingQuot.mkAlgHom k (PresRel k)

/-- The `i`-th generator of the presented algebra: `0`, `1`, `2` are `e`, `f`, `h`. -/
def presGen (k : Type*) [CommRing k] (i : Fin 3) : Presentation k :=
  presMk k (FreeAlgebra.ι k i)

theorem presRel_he (k : Type*) [CommRing k] :
    presGen k 2 * presGen k 0 - presGen k 0 * presGen k 2 = (2 : k) • presGen k 0 := by
  have hrel := RingQuot.mkAlgHom_rel (S := k) (PresRel.he (k := k))
  simp only [map_sub, map_mul, map_smul] at hrel
  exact hrel

theorem presRel_hf (k : Type*) [CommRing k] :
    presGen k 2 * presGen k 1 - presGen k 1 * presGen k 2 = (-2 : k) • presGen k 1 := by
  have hrel := RingQuot.mkAlgHom_rel (S := k) (PresRel.hf (k := k))
  simp only [map_sub, map_mul, map_smul] at hrel
  exact hrel

theorem presRel_ef (k : Type*) [CommRing k] :
    presGen k 0 * presGen k 1 - presGen k 1 * presGen k 0 = presGen k 2 := by
  have hrel := RingQuot.mkAlgHom_rel (S := k) (PresRel.ef (k := k))
  simp only [map_sub, map_mul] at hrel
  exact hrel

/-- The Lie algebra morphism `𝔰𝔩(2) → Presentation k` sending `e`, `f`, `h` to the three
generators. -/
def toPresLie (k : Type*) [CommRing k] : sl2 k →ₗ⁅k⁆ Presentation k :=
  liftTriple (presGen k 0) (presGen k 1) (presGen k 2) (presRel_he k) (presRel_hf k) (presRel_ef k)

/-- `U(𝔰𝔩(2)) → Presentation k`, obtained from the universal property of `U`. -/
def uToPres (k : Type*) [CommRing k] :
    UniversalEnvelopingAlgebra k (sl2 k) →ₐ[k] Presentation k :=
  UniversalEnvelopingAlgebra.lift k (toPresLie k)

/-- The map out of the *free* algebra on three generators sending them to `ι e`, `ι f`, `ι h`. -/
def presToUFree (k : Type*) [CommRing k] :
    FreeAlgebra k (Fin 3) →ₐ[k] UniversalEnvelopingAlgebra k (sl2 k) :=
  FreeAlgebra.lift k ![ι k (e : sl2 k), ι k (f : sl2 k), ι k (h : sl2 k)]

@[simp] theorem presToUFree_ι (k : Type*) [CommRing k] (i : Fin 3) :
    presToUFree k (FreeAlgebra.ι k i) = ι k (![(e : sl2 k), f, h] i) := by
  simp only [presToUFree, FreeAlgebra.lift_ι_apply]
  fin_cases i <;> simp

/-- `ι e`, `ι f`, `ι h` satisfy the book's three relations, so `presToUFree` descends to the
quotient. -/
theorem presToUFree_rel (k : Type*) [CommRing k] :
    ∀ ⦃a b : FreeAlgebra k (Fin 3)⦄, PresRel k a b → presToUFree k a = presToUFree k b := by
  rintro a b hab
  obtain _ | _ | _ := hab
  · simpa using (sl2_universal_relations k).1
  · simpa using (sl2_universal_relations k).2.1
  · simpa using (sl2_universal_relations k).2.2

/-- `Presentation k → U(𝔰𝔩(2))`, obtained from the universal property of the presentation: the
images `ι e`, `ι f`, `ι h` satisfy the three relations by `sl2_universal_relations`. -/
def presToU (k : Type*) [CommRing k] :
    Presentation k →ₐ[k] UniversalEnvelopingAlgebra k (sl2 k) :=
  RingQuot.liftAlgHom k ⟨presToUFree k, presToUFree_rel k⟩

@[simp] theorem uToPres_ι (k : Type*) [CommRing k] (x : sl2 k) :
    uToPres k (ι k x) = x.1 • presGen k 0 + x.2.1 • presGen k 1 + x.2.2 • presGen k 2 :=
  UniversalEnvelopingAlgebra.lift_ι_apply k (toPresLie k) x

@[simp] theorem presToU_presGen (k : Type*) [CommRing k] (i : Fin 3) :
    presToU k (presGen k i) = ι k (![(e : sl2 k), f, h] i) := by
  change RingQuot.liftAlgHom k ⟨presToUFree k, presToUFree_rel k⟩
      (RingQuot.mkAlgHom k (PresRel k) (FreeAlgebra.ι k i)) = _
  rw [RingQuot.liftAlgHom_mkAlgHom_apply, presToUFree_ι]

theorem presToU_comp_uToPres (k : Type*) [CommRing k] :
    (presToU k).comp (uToPres k) = AlgHom.id k (UniversalEnvelopingAlgebra k (sl2 k)) := by
  ext x
  simp only [AlgHom.coe_comp, LieHom.coe_comp, Function.comp_apply, AlgHom.coe_toLieHom,
    AlgHom.coe_id, id_eq, uToPres_ι, map_add, map_smul, presToU_presGen]
  simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_two,
    Matrix.tail_cons]
  rw [← map_smul, ← map_smul, ← map_smul, ← map_add, ← map_add]
  exact congrArg _ (eq_smul_e_add_smul_f_add_smul_h x).symm

theorem uToPres_comp_presToU (k : Type*) [CommRing k] :
    (uToPres k).comp (presToU k) = AlgHom.id k (Presentation k) := by
  apply RingQuot.ringQuot_ext'
  ext i
  fin_cases i
  · change uToPres k (presToU k (presGen k 0)) = presGen k 0
    simp [uToPres, toPresLie, e, f, h]
  · change uToPres k (presToU k (presGen k 1)) = presGen k 1
    simp [uToPres, toPresLie, e, f, h]
  · change uToPres k (presToU k (presGen k 2)) = presGen k 2
    simp [uToPres, toPresLie, e, f, h]

/-- **Example 2.9.12.** `U(𝔰𝔩(2))` *is* the associative `k`-algebra generated by `e`, `f`, `h`
subject to the relations `he − eh = 2e`, `hf − fh = −2f`, `ef − fe = h`: the presented algebra is
isomorphic to `U(𝔰𝔩(2))` as a `k`-algebra. -/
def presentationEquiv (k : Type*) [CommRing k] :
    Presentation k ≃ₐ[k] UniversalEnvelopingAlgebra k (sl2 k) :=
  AlgEquiv.ofAlgHom (presToU k) (uToPres k) (presToU_comp_uToPres k) (uToPres_comp_presToU k)

/-- The isomorphism of `presentationEquiv` carries the presented generators to `ι e`, `ι f`,
`ι h`, so it really is a matching-up of the book's generators. -/
@[simp] theorem presentationEquiv_gen_zero (k : Type*) [CommRing k] :
    presentationEquiv k (presGen k 0) = ι k (e : sl2 k) := by simp [presentationEquiv]

@[simp] theorem presentationEquiv_gen_one (k : Type*) [CommRing k] :
    presentationEquiv k (presGen k 1) = ι k (f : sl2 k) := by simp [presentationEquiv]

@[simp] theorem presentationEquiv_gen_two (k : Type*) [CommRing k] :
    presentationEquiv k (presGen k 2) = ι k (h : sl2 k) := by simp [presentationEquiv]

end Presentation

end Etingof.Example2_9_12
