import Mathlib.Algebra.Algebra.Subalgebra.Centralizer
import Mathlib.Algebra.Order.Ring.Star
import Mathlib.Algebra.RingQuot
import Mathlib.AlgebraicTopology.SimplexCategory.Basic
import Mathlib.Analysis.CStarAlgebra.Classes
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.LinearAlgebra.Eigenspace.Semisimple
import Mathlib.Order.CompletePartialOrder
import Mathlib.RingTheory.Flat.FaithfullyFlat.Basic
import Mathlib.RingTheory.Flat.TorsionFree
import Mathlib.RingTheory.SimpleRing.Principal


/-!
# Problem 2.16.5: Irreducible representations of the quantum group `U_q(sl₂)`

Let `k` be an algebraically closed field of characteristic zero (here `ℂ`) and let `q ∈ k^×`
with `q ≠ ±1`. The quantum enveloping algebra `U_q(sl₂)` is the algebra generated by
`e, f, K, K⁻¹` with relations

  `K e K⁻¹ = q² e`,  `K f K⁻¹ = q⁻² f`,  `[e, f] = (K - K⁻¹) / (q - q⁻¹)`.

The exercise asks to classify the irreducible representations, treating separately the cases
of `q` a root of unity and `q` not a root of unity.

## Construction

We build `U_q(sl₂)` as `RingQuot (Rel q)`, the quotient of the free `ℂ`-algebra on four
generators `e, f, K, L` (`L` playing the role of `K⁻¹`) by the defining relations, cleared of
denominators so they are well-typed for every `q` (the coefficient `q - q⁻¹` is nonzero since
`q ≠ ±1`):

  `K L = 1`,  `L K = 1`,  `K e = q²·(e K)`,  `K f = q⁻²·(f K)`,
  `(q - q⁻¹)·(e f - f e) = K - L`.

The following structural constraints in the two cases are established below:

* **`q` not a root of unity**: every nontrivial finite dimensional representation has a highest
  weight vector (`exists_highest_weight_vector`), and on a simple such module the highest weight
  eigenvalue of `K` is pinned down as `ε · q^(dim V - 1)` with `ε² = 1`
  (`highest_weight_eigenvalue_of_not_isOfFinOrder`).
* **`q` a root of unity**: `K` acts semisimply with the expected eigenvalue structure
  (`Kop_isSemisimple_and_eigenvalues`), `K^(orderOf q)` acts as a scalar
  (`Kpow_orderOf_isScalar`), and every finite dimensional simple module has bounded dimension,
  `finrank ℂ V ≤ orderOf q` (`finrank_irreducible_le_of_isOfFinOrder`, combining
  `finrank_le_of_epow_orderOf_eq_zero`, `finrank_le_of_fpow_orderOf_eq_zero`, and
  `finrank_le_of_cyclic`).

These are inputs to a classification, not an enumeration up to isomorphism. The exhaustive
enumeration of irreducibles up to isomorphism is intentionally omitted by the project-wide scope
decision in `skipped-exercises.md`. The omission is documentation-only: this file does not
introduce an unproved classification declaration.
-/

namespace Etingof.Problem2_16_5

/-- Generators of the free algebra: `0 ↦ e`, `1 ↦ f`, `2 ↦ K`, `3 ↦ L (= K⁻¹)`. -/
abbrev Gen := Fin 4

/-- The `e` generator in the free algebra. -/
noncomputable abbrev fe : FreeAlgebra ℂ Gen := FreeAlgebra.ι ℂ (0 : Fin 4)
/-- The `f` generator in the free algebra. -/
noncomputable abbrev ff : FreeAlgebra ℂ Gen := FreeAlgebra.ι ℂ (1 : Fin 4)
/-- The `K` generator in the free algebra. -/
noncomputable abbrev fK : FreeAlgebra ℂ Gen := FreeAlgebra.ι ℂ (2 : Fin 4)
/-- The `L = K⁻¹` generator in the free algebra. -/
noncomputable abbrev fL : FreeAlgebra ℂ Gen := FreeAlgebra.ι ℂ (3 : Fin 4)

/-- The defining relations of `U_q(sl₂)` (with denominators cleared). -/
inductive Rel (q : ℂˣ) : FreeAlgebra ℂ Gen → FreeAlgebra ℂ Gen → Prop
  | KL : Rel q (fK * fL) 1
  | LK : Rel q (fL * fK) 1
  | Ke : Rel q (fK * fe) (((q : ℂ) ^ 2) • (fe * fK))
  | Kf : Rel q (fK * ff) (((q : ℂ) ^ 2)⁻¹ • (ff * fK))
  | ef : Rel q (((q : ℂ) - (q : ℂ)⁻¹) • (fe * ff - ff * fe)) (fK - fL)

/-- The quantum group `U_q(sl₂)`. -/
noncomputable abbrev Uqsl2 (q : ℂˣ) : Type := RingQuot (Rel q)

/-- The canonical algebra map from the free algebra onto `U_q(sl₂)`. -/
noncomputable def mk (q : ℂˣ) : FreeAlgebra ℂ Gen →ₐ[ℂ] Uqsl2 q := RingQuot.mkAlgHom ℂ (Rel q)

/-- The generator `e` of `U_q(sl₂)`. -/
noncomputable def e (q : ℂˣ) : Uqsl2 q := mk q fe
/-- The generator `f` of `U_q(sl₂)`. -/
noncomputable def f (q : ℂˣ) : Uqsl2 q := mk q ff
/-- The generator `K` of `U_q(sl₂)`. -/
noncomputable def K (q : ℂˣ) : Uqsl2 q := mk q fK
/-- The generator `L = K⁻¹` of `U_q(sl₂)`. -/
noncomputable def L (q : ℂˣ) : Uqsl2 q := mk q fL

/-! ## The defining relations hold in `U_q(sl₂)` -/

/-- The generators K and L are mutual inverses in the quantum quotient. -/
@[simp] lemma KL_rel (q : ℂˣ) : K q * L q = 1 := by
  have h := RingQuot.mkAlgHom_rel ℂ (Rel.KL (q := q)); simp only [map_mul, map_one] at h; exact h

/-- The generators L and K are mutual inverses in the quantum quotient. -/
@[simp] lemma LK_rel (q : ℂˣ) : L q * K q = 1 := by
  have h := RingQuot.mkAlgHom_rel ℂ (Rel.LK (q := q)); simp only [map_mul, map_one] at h; exact h

/-- `K e = q²·(e K)`, i.e. `K e K⁻¹ = q² e`. -/
@[simp] lemma Ke_rel (q : ℂˣ) : K q * e q = ((q : ℂ) ^ 2) • (e q * K q) := by
  have h := RingQuot.mkAlgHom_rel ℂ (Rel.Ke (q := q)); simp only [map_mul, map_smul] at h; exact h

/-- `K f = q⁻²·(f K)`, i.e. `K f K⁻¹ = q⁻² f`. -/
@[simp] lemma Kf_rel (q : ℂˣ) : K q * f q = ((q : ℂ) ^ 2)⁻¹ • (f q * K q) := by
  have h := RingQuot.mkAlgHom_rel ℂ (Rel.Kf (q := q)); simp only [map_mul, map_smul] at h; exact h

/-- `(q - q⁻¹)·(e f - f e) = K - L`, the cleared-denominator form of
`[e, f] = (K - K⁻¹)/(q - q⁻¹)`. -/
@[simp] lemma ef_rel (q : ℂˣ) :
    ((q : ℂ) - (q : ℂ)⁻¹) • (e q * f q - f q * e q) = K q - L q := by
  have h := RingQuot.mkAlgHom_rel ℂ (Rel.ef (q := q))
  simp only [map_smul, map_sub, map_mul] at h; exact h

/-! ## A nontrivial one-dimensional quotient

Sending `e` and `f` to `0` and both `K` and `L` to `1` respects every defining relation. The
resulting surjection `U_q(sl₂) →ₐ[ℂ] ℂ` proves in Lean that the presented algebra is nontrivial;
in particular, the representation-theoretic statements below are not about a collapsed quotient.
-/

/-- Values of the four generators in the one-dimensional quotient. -/
private noncomputable def augmentationGen : Gen → ℂ := ![0, 0, 1, 1]

/-- The free-algebra map underlying the one-dimensional quotient. -/
private noncomputable def augmentationFree : FreeAlgebra ℂ Gen →ₐ[ℂ] ℂ :=
  FreeAlgebra.lift ℂ augmentationGen

private theorem augmentationFree_rel (q : ℂˣ) :
    ∀ ⦃a b⦄, Rel q a b → augmentationFree a = augmentationFree b := by
  rintro _ _ h
  cases h <;> simp [augmentationFree, augmentationGen]

/-- The one-dimensional quotient `U_q(sl₂) →ₐ[ℂ] ℂ`, with `e,f ↦ 0` and `K,L ↦ 1`. -/
noncomputable def augmentation (q : ℂˣ) : Uqsl2 q →ₐ[ℂ] ℂ :=
  RingQuot.liftAlgHom ℂ ⟨augmentationFree, augmentationFree_rel q⟩

/-- The one-dimensional quotient is onto. -/
theorem augmentation_surjective (q : ℂˣ) : Function.Surjective (augmentation q) := by
  intro z
  refine ⟨algebraMap ℂ (Uqsl2 q) z, ?_⟩
  exact (augmentation q).commutes z

/-- The presentation of `U_q(sl₂)` does not collapse to the zero ring. -/
noncomputable instance instNontrivialUqsl2 (q : ℂˣ) : Nontrivial (Uqsl2 q) :=
  (augmentation_surjective q).nontrivial

/-! ## Classification of irreducible representations (spec) -/

/-- Injectivity of the eigenvalue chain `n ↦ q^{2n}·μ₀` when `q` is not a root of unity and
`μ₀ ≠ 0`: since `q²` then has infinite order, distinct `n` give distinct eigenvalues. -/
lemma chain_inj (q : ℂˣ) (hq : ¬ IsOfFinOrder q) (μ₀ : ℂ) (hμ₀ : μ₀ ≠ 0) :
    Function.Injective (fun n : ℕ => (q : ℂ) ^ (2 * n) * μ₀) := by
  intro a b hab
  simp only at hab
  have h : (q : ℂ) ^ (2 * a) = (q : ℂ) ^ (2 * b) := mul_right_cancel₀ hμ₀ hab
  have hu : q ^ (2 * a) = q ^ (2 * b) := by
    apply Units.ext; push_cast; simpa using h
  have hinj : Function.Injective (fun n : ℕ => q ^ n) :=
    injective_pow_iff_not_isOfFinOrder.mpr hq
  have : 2 * a = 2 * b := hinj hu
  omega

section HighestWeight

variable (q : ℂˣ)
variable (V : Type*) [AddCommGroup V] [Module ℂ V] [Module (Uqsl2 q) V]
  [IsScalarTower ℂ (Uqsl2 q) V] [FiniteDimensional ℂ V]

/-- The `K`-action packaged as a `ℂ`-linear endomorphism of `V`. -/
noncomputable def Kop : Module.End ℂ V where
  toFun v := K q • v
  map_add' := by intro x y; simp [smul_add]
  map_smul' := by intro c v; exact smul_comm (K q) c v

omit [FiniteDimensional ℂ V] in
/-- Evaluation formula for `Kop`. -/
@[simp] lemma Kop_apply (v : V) : Kop q V v = K q • v := rfl

omit [FiniteDimensional ℂ V] in
/-- If `w` is a `K`-eigenvector with eigenvalue `μ`, then `e • w` is `0` or a `K`-eigenvector
with eigenvalue `q²·μ` (from the relation `K e = q²·(e K)`). -/
lemma e_eigenvalue_shift (μ : ℂ) (w : V) (hw : Kop q V w = μ • w) :
    Kop q V (e q • w) = ((q : ℂ) ^ 2 * μ) • (e q • w) := by
  simp only [Kop_apply] at hw ⊢
  have h1 : K q • (e q • w) = (K q * e q) • w := by rw [mul_smul]
  rw [h1, Ke_rel, smul_assoc, mul_smul, hw, smul_comm (e q) μ w, smul_smul]

omit [FiniteDimensional ℂ V] in
/-- If `w` is a `K`-eigenvector with eigenvalue `μ`, then `f • w` is `0` or a `K`-eigenvector
with eigenvalue `q⁻²·μ` (from the relation `K f = q⁻²·(f K)`). Dual to `e_eigenvalue_shift`; it
is the `f`-direction of the weight ladder used in the root-of-unity dimension bound. -/
lemma f_eigenvalue_shift (μ : ℂ) (w : V) (hw : Kop q V w = μ • w) :
    Kop q V (f q • w) = (((q : ℂ) ^ 2)⁻¹ * μ) • (f q • w) := by
  simp only [Kop_apply] at hw ⊢
  have h1 : K q • (f q • w) = (K q * f q) • w := by rw [mul_smul]
  rw [h1, Kf_rel, smul_assoc, mul_smul, hw, smul_comm (f q) μ w, smul_smul]

omit [FiniteDimensional ℂ V] in
/-- `K` acts invertibly (`K·L = 1`), so `0` is not an eigenvalue of `Kop`. -/
lemma eigenvalue_ne_zero (μ : ℂ) (hμ : (Kop q V).HasEigenvalue μ) : μ ≠ 0 := by
  rintro rfl
  obtain ⟨v, hv, hv0⟩ := hμ.exists_hasEigenvector
  have hKv : K q • v = 0 := by
    have := Module.End.mem_eigenspace_iff.mp hv; simpa using this
  have : v = 0 := by
    have h := congrArg (fun x => L q • x) hKv
    simp only [smul_zero] at h
    rw [← mul_smul, LK_rel, one_smul] at h
    exact h
  exact hv0 this

/-- There is a "highest" `K`-eigenvalue `μ` for which `q²·μ` is not an eigenvalue. If not,
the injective chain `q^{2n}·μ₀` would give infinitely many independent eigenvectors in the
finite-dimensional `V`. -/
lemma exists_highest_eig (hq : ¬ IsOfFinOrder q) [Nontrivial V] :
    ∃ μ : ℂ, (Kop q V).HasEigenvalue μ ∧ ¬ (Kop q V).HasEigenvalue ((q : ℂ) ^ 2 * μ) := by
  obtain ⟨μ₀, hμ₀⟩ := Module.End.exists_eigenvalue (Kop q V)
  by_contra hcon
  have h_all : ∀ μ : ℂ, (Kop q V).HasEigenvalue μ → (Kop q V).HasEigenvalue ((q : ℂ) ^ 2 * μ) := by
    intro μ hμ; by_contra hne; exact hcon ⟨μ, hμ, hne⟩
  have h_chain : ∀ n : ℕ, (Kop q V).HasEigenvalue ((q : ℂ) ^ (2 * n) * μ₀) := by
    intro n; induction n with
    | zero => simpa using hμ₀
    | succ n ih =>
        have hh := h_all _ ih
        have heq : (q : ℂ) ^ (2 * (n + 1)) * μ₀ = (q : ℂ) ^ 2 * ((q : ℂ) ^ (2 * n) * μ₀) := by ring
        rw [heq]; exact hh
  have h_inj := chain_inj q hq μ₀ (eigenvalue_ne_zero q V μ₀ hμ₀)
  have h_li := Module.End.eigenvectors_linearIndependent' (Kop q V)
    (fun n : ℕ => (q : ℂ) ^ (2 * n) * μ₀) h_inj
    (fun n => (h_chain n).exists_hasEigenvector.choose)
    (fun n => (h_chain n).exists_hasEigenvector.choose_spec)
  exact Module.Finite.not_linearIndependent_of_infinite _ h_li

/-- **Highest weight vector.** Every nonzero finite dimensional representation of `U_q(sl₂)`
with `q` not a root of unity contains a nonzero vector `v` that is annihilated by `e` and is an
eigenvector of `K` (`K • v = λ v`). This is the structural core of the classification of
irreducible representations.

The non-root-of-unity hypothesis `¬ IsOfFinOrder q` is essential: at roots of unity the cyclic
(De Concini–Kac) modules have `e` acting invertibly, so no nonzero vector is killed by `e`. With
`¬ IsOfFinOrder q`, `q²` has infinite order, so the eigenvalue chain `λ, q²λ, q⁴λ, …` is injective
and the `e`-walk-up argument terminates. -/
theorem exists_highest_weight_vector (hq : ¬ IsOfFinOrder q) [Nontrivial V] :
    ∃ (v : V) (lam : ℂ), v ≠ 0 ∧ e q • v = 0 ∧ K q • v = lam • v := by
  obtain ⟨μ, hμ, hμ2⟩ := exists_highest_eig q V hq
  obtain ⟨v, hv⟩ := hμ.exists_hasEigenvector
  refine ⟨v, μ, hv.2, ?_, ?_⟩
  · -- `e • v` would be a `q²μ`-eigenvector if nonzero, contradicting maximality of `μ`.
    by_contra he
    apply hμ2
    have hmem : Kop q V (e q • v) = ((q : ℂ) ^ 2 * μ) • (e q • v) :=
      e_eigenvalue_shift q V μ v (Module.End.mem_eigenspace_iff.mp hv.1)
    exact Module.End.hasEigenvalue_of_hasEigenvector
      ⟨Module.End.mem_eigenspace_iff.mpr hmem, he⟩
  · have := Module.End.mem_eigenspace_iff.mp hv.1
    simpa using this

end HighestWeight

/-! ## Scalar facts for `q` not a root of unity -/

/-- If `q` is not a root of unity, no positive power of `q` is `1`. -/
lemma qpow_ne_one (q : ℂˣ) (hq : ¬ IsOfFinOrder q) {n : ℕ} (hn : 0 < n) : (q : ℂ) ^ n ≠ 1 := by
  intro h
  refine hq (isOfFinOrder_iff_pow_eq_one.mpr ⟨n, hn, ?_⟩)
  apply Units.ext
  push_cast
  simpa using h

/-- `q² ≠ 1` when `q` is not a root of unity. -/
lemma q_sq_ne_one (q : ℂˣ) (hq : ¬ IsOfFinOrder q) : (q : ℂ) ^ 2 ≠ 1 :=
  qpow_ne_one q hq (by norm_num)

/-- `q - q⁻¹ ≠ 0` when `q` is not a root of unity (equivalently `q ≠ ±1`). -/
lemma q_sub_inv_ne (q : ℂˣ) (hq : ¬ IsOfFinOrder q) : (q : ℂ) - (q : ℂ)⁻¹ ≠ 0 := by
  intro h
  have h2 : (q : ℂ) = (q : ℂ)⁻¹ := sub_eq_zero.mp h
  have : (q : ℂ) ^ 2 = 1 := by
    rw [sq]; nth_rewrite 2 [h2]; exact mul_inv_cancel₀ q.ne_zero
  exact q_sq_ne_one q hq this

/-! ## The `f`-ladder of a highest weight vector -/

section Ladder

variable (q : ℂˣ)
variable (V : Type*) [AddCommGroup V] [Module ℂ V] [Module (Uqsl2 q) V]
  [IsScalarTower ℂ (Uqsl2 q) V]

/-- The `f`-ladder of `v`: `ladder q V v i = fⁱ • v`. -/
noncomputable def ladder (v : V) (i : ℕ) : V := (f q) ^ i • v

/-- The `K`-eigenvalue of the `i`-th ladder vector, given `K • v = lam • v`: `lam · q^{-2i}`. -/
noncomputable def mu (lam : ℂ) (i : ℕ) : ℂ := lam * (((q : ℂ) ^ 2)⁻¹) ^ i

omit [Module ℂ V] [IsScalarTower ℂ (Uqsl2 q) V] in
/-- The zero case of `ladder`. -/
@[simp] lemma ladder_zero (v : V) : ladder q V v 0 = v := by simp [ladder]

omit [Module ℂ V] [IsScalarTower ℂ (Uqsl2 q) V] in
/-- The successor-step formula for `ladder`. -/
lemma ladder_succ (v : V) (i : ℕ) : ladder q V v (i + 1) = f q • ladder q V v i := by
  simp only [ladder, pow_succ', mul_smul]

/-- The zero case of `mu`. -/
@[simp] lemma mu_zero (lam : ℂ) : mu q lam 0 = lam := by simp [mu]

/-- The raising coefficient is nonzero away from the top of the ladder. -/
lemma mu_ne_zero (lam : ℂ) (hlam : lam ≠ 0) (i : ℕ) : mu q lam i ≠ 0 := by
  apply mul_ne_zero hlam
  exact pow_ne_zero _ (inv_ne_zero (pow_ne_zero _ q.ne_zero))

/-- `K` acts on the `i`-th ladder vector by `mu q lam i`. -/
lemma K_ladder (v : V) (lam : ℂ) (hKv : K q • v = lam • v) (i : ℕ) :
    K q • ladder q V v i = mu q lam i • ladder q V v i := by
  induction i with
  | zero => simpa [mu] using hKv
  | succ n ih =>
    rw [ladder_succ, ← mul_smul, Kf_rel, smul_assoc, mul_smul, ih,
      smul_comm (f q) (mu q lam n), smul_smul]
    congr 1
    simp only [mu, pow_succ]
    ring

/-- `L = K⁻¹` acts on the `i`-th ladder vector by `(mu q lam i)⁻¹`. -/
lemma L_ladder (v : V) (lam : ℂ) (hlam : lam ≠ 0) (hKv : K q • v = lam • v) (i : ℕ) :
    L q • ladder q V v i = (mu q lam i)⁻¹ • ladder q V v i := by
  have hK := K_ladder q V v lam hKv i
  have hmu := mu_ne_zero q lam hlam i
  have h1 : L q • (K q • ladder q V v i) = ladder q V v i := by
    rw [← mul_smul, LK_rel, one_smul]
  rw [hK, smul_comm (L q) (mu q lam i)] at h1
  -- h1 : mu • (L • ladder) = ladder
  have := congrArg (fun x => (mu q lam i)⁻¹ • x) h1
  simp only [smul_smul, inv_mul_cancel₀ hmu, one_smul] at this
  exact this

/-- The commutator action on a `K`-eigenvector `x` (with `K • x = a • x`, `L • x = a⁻¹ • x`):
`e • (f • x) = f • (e • x) + (q - q⁻¹)⁻¹·(a - a⁻¹) • x`, from `[e,f] = (K-L)/(q-q⁻¹)`. -/
lemma ef_action (hne : (q : ℂ) - (q : ℂ)⁻¹ ≠ 0) (x : V) (a : ℂ)
    (hK : K q • x = a • x) (hL : L q • x = a⁻¹ • x) :
    e q • (f q • x) = f q • (e q • x) + (((q : ℂ) - (q : ℂ)⁻¹)⁻¹ * (a - a⁻¹)) • x := by
  have expand : (K q - L q) • x = (a - a⁻¹) • x := by rw [sub_smul, sub_smul, hK, hL]
  have expand2 : (e q * f q - f q * e q) • x = e q • (f q • x) - f q • (e q • x) := by
    rw [sub_smul, mul_smul, mul_smul]
  have hrel := ef_rel q
  have h3 : ((q : ℂ) - (q : ℂ)⁻¹) • (e q • (f q • x) - f q • (e q • x)) = (a - a⁻¹) • x := by
    rw [← expand2, ← smul_assoc, hrel, expand]
  have hDiff : e q • (f q • x) - f q • (e q • x)
      = ((q : ℂ) - (q : ℂ)⁻¹)⁻¹ • ((a - a⁻¹) • x) := by
    rw [← h3, inv_smul_smul₀ hne]
  rw [mul_smul, ← hDiff]
  abel

/-- The scalar coefficient `e • fⁱ⁺¹v = dcoef q lam i · fⁱv`, a telescoping sum of the quantum
brackets `(q - q⁻¹)⁻¹·(mu j - (mu j)⁻¹)`. -/
noncomputable def dcoef (lam : ℂ) (i : ℕ) : ℂ :=
  ∑ j ∈ Finset.range (i + 1), ((q : ℂ) - (q : ℂ)⁻¹)⁻¹ * (mu q lam j - (mu q lam j)⁻¹)

/-- The `e`-action on the ladder: `e • fⁱ⁺¹v = dcoef q lam i · fⁱv`. -/
lemma e_ladder (hne : (q : ℂ) - (q : ℂ)⁻¹ ≠ 0) (v : V) (lam : ℂ) (hlam : lam ≠ 0)
    (he : e q • v = 0) (hKv : K q • v = lam • v) (i : ℕ) :
    e q • ladder q V v (i + 1) = dcoef q lam i • ladder q V v i := by
  induction i with
  | zero =>
    rw [ladder_succ,
      ef_action q V hne (ladder q V v 0) (mu q lam 0)
        (K_ladder q V v lam hKv 0) (L_ladder q V v lam hlam hKv 0)]
    have hev : e q • ladder q V v 0 = 0 := by simpa using he
    rw [hev, smul_zero, zero_add, dcoef, Finset.sum_range_one]
  | succ n ih =>
    rw [ladder_succ,
      ef_action q V hne (ladder q V v (n + 1)) (mu q lam (n + 1))
        (K_ladder q V v lam hKv (n + 1)) (L_ladder q V v lam hlam hKv (n + 1)),
      ih, smul_comm (f q) (dcoef q lam n), ← ladder_succ, ← add_smul]
    congr 1
    have hstep : dcoef q lam (n + 1) = dcoef q lam n
        + ((q : ℂ) - (q : ℂ)⁻¹)⁻¹ * (mu q lam (n + 1) - (mu q lam (n + 1))⁻¹) := by
      simp only [dcoef, Finset.sum_range_succ]
    rw [hstep]

/-- The eigenvalue chain `i ↦ mu q lam i` is injective when `q` is not a root of unity. -/
lemma mu_inj (hq : ¬ IsOfFinOrder q) (lam : ℂ) (hlam : lam ≠ 0) :
    Function.Injective (mu q lam) := by
  intro a b hab
  simp only [mu] at hab
  have h : (((q : ℂ) ^ 2)⁻¹) ^ a = (((q : ℂ) ^ 2)⁻¹) ^ b := mul_left_cancel₀ hlam hab
  have hu_inf : ¬ IsOfFinOrder ((q ^ 2)⁻¹ : ℂˣ) := by
    rw [isOfFinOrder_inv_iff]
    intro hfin
    apply hq
    rw [isOfFinOrder_iff_pow_eq_one] at hfin ⊢
    obtain ⟨m, hm, hpow⟩ := hfin
    exact ⟨2 * m, by omega, by rw [pow_mul]; exact hpow⟩
  have hinj : Function.Injective (fun n : ℕ => ((q ^ 2)⁻¹ : ℂˣ) ^ n) :=
    injective_pow_iff_not_isOfFinOrder.mpr hu_inf
  have hu : ((q ^ 2)⁻¹ : ℂˣ) ^ a = ((q ^ 2)⁻¹ : ℂˣ) ^ b := by
    have hcast : (((q ^ 2)⁻¹ : ℂˣ) ^ a : ℂ) = (((q ^ 2)⁻¹ : ℂˣ) ^ b : ℂ) := by
      push_cast; exact h
    exact_mod_cast hcast
  exact hinj hu

end Ladder

/-- The vanishing of the telescoping coefficient `dcoef q lam N` forces the highest-weight
constraint `lam² = q^{2N}` (the non-root-of-unity quantum highest weight condition). The sum
`∑_{j=0}^N (mu j - mu j⁻¹)` factors as `SA · (lam - lam⁻¹·q^{2N})` with `SA ≠ 0`. -/
lemma dcoef_eq_zero_imp (q : ℂˣ) (hq : ¬ IsOfFinOrder q) (lam : ℂ) (hlam : lam ≠ 0) (N : ℕ)
    (h : dcoef q lam N = 0) : lam ^ 2 = (q : ℂ) ^ (2 * N) := by
  have hqne : (q : ℂ) ≠ 0 := q.ne_zero
  have htne : (q : ℂ) ^ 2 ≠ 0 := pow_ne_zero _ hqne
  have hc : ((q : ℂ) - (q : ℂ)⁻¹)⁻¹ ≠ 0 := inv_ne_zero (q_sub_inv_ne q hq)
  rw [dcoef, ← Finset.mul_sum] at h
  have hS : ∑ j ∈ Finset.range (N + 1), (mu q lam j - (mu q lam j)⁻¹) = 0 :=
    (mul_eq_zero.mp h).resolve_left hc
  have hSexpand : ∑ j ∈ Finset.range (N + 1), (mu q lam j - (mu q lam j)⁻¹)
      = lam * (∑ j ∈ Finset.range (N + 1), (((q : ℂ) ^ 2)⁻¹) ^ j)
        - lam⁻¹ * (∑ j ∈ Finset.range (N + 1), ((q : ℂ) ^ 2) ^ j) := by
    rw [Finset.mul_sum, Finset.mul_sum, ← Finset.sum_sub_distrib]
    apply Finset.sum_congr rfl
    intro j _
    rw [mu, mul_inv, inv_pow, inv_inv]
  rw [hSexpand] at hS
  set SA : ℂ := ∑ j ∈ Finset.range (N + 1), (((q : ℂ) ^ 2)⁻¹) ^ j with hSA
  set SB : ℂ := ∑ j ∈ Finset.range (N + 1), ((q : ℂ) ^ 2) ^ j with hSB
  have hSB_ne : SB ≠ 0 := by
    intro h0
    have hgeom : SB * ((q : ℂ) ^ 2 - 1) = ((q : ℂ) ^ 2) ^ (N + 1) - 1 := by
      rw [hSB]; exact geom_sum_mul _ _
    rw [h0, zero_mul] at hgeom
    have hX : ((q : ℂ) ^ 2) ^ (N + 1) = 1 := sub_eq_zero.mp hgeom.symm
    exact qpow_ne_one q hq (n := 2 * (N + 1)) (by omega) (by rw [pow_mul]; exact hX)
  have hkey : SA * ((q : ℂ) ^ 2) ^ N = SB := by
    rw [hSA, hSB, Finset.sum_mul,
      ← Finset.sum_range_reflect (fun j => ((q : ℂ) ^ 2) ^ j) (N + 1)]
    apply Finset.sum_congr rfl
    intro j hj
    rw [Finset.mem_range] at hj
    have hjN : j ≤ N := by omega
    rw [inv_pow, show (N + 1) - 1 - j = N - j by omega, pow_sub₀ _ htne hjN]
    exact mul_comm _ _
  have hSA_ne : SA ≠ 0 := by
    intro h0; rw [h0, zero_mul] at hkey; exact hSB_ne hkey.symm
  rw [← hkey] at hS
  have hfact : SA * (lam - lam⁻¹ * ((q : ℂ) ^ 2) ^ N) = 0 := by linear_combination hS
  have hlin : lam - lam⁻¹ * ((q : ℂ) ^ 2) ^ N = 0 :=
    (mul_eq_zero.mp hfact).resolve_left hSA_ne
  have h2 := sub_eq_zero.mp hlin
  have hlam2 : lam ^ 2 = ((q : ℂ) ^ 2) ^ N := by
    rw [sq]
    nth_rewrite 2 [h2]
    rw [← mul_assoc, mul_inv_cancel₀ hlam, one_mul]
  rw [pow_mul]; exact hlam2

/-- A `ℂ`-submodule `W` closed under the four generators `e, f, K, L` is a `U_q(sl₂)`-submodule:
every algebra element maps `W` into `W`. Proved by `FreeAlgebra.induction` on a preimage under the
surjection `mk q`, reducing to the generator closures. -/
lemma smul_mem_of_generators (q : ℂˣ) (V : Type*) [AddCommGroup V] [Module ℂ V]
    [Module (Uqsl2 q) V] [IsScalarTower ℂ (Uqsl2 q) V] (W : Submodule ℂ V)
    (hclE : ∀ x ∈ W, e q • x ∈ W) (hclF : ∀ x ∈ W, f q • x ∈ W)
    (hclK : ∀ x ∈ W, K q • x ∈ W) (hclL : ∀ x ∈ W, L q • x ∈ W)
    (a : Uqsl2 q) (x : V) (hx : x ∈ W) : a • x ∈ W := by
  suffices H : ∀ p : FreeAlgebra ℂ Gen, ∀ y ∈ W, mk q p • y ∈ W by
    obtain ⟨p, rfl⟩ := RingQuot.mkAlgHom_surjective ℂ (Rel q) a
    exact H p x hx
  intro p
  induction p using FreeAlgebra.induction with
  | grade0 r =>
    intro y hy
    rw [show mk q (algebraMap ℂ (FreeAlgebra ℂ Gen) r) = algebraMap ℂ (Uqsl2 q) r from
      AlgHom.commutes (mk q) r, algebraMap_smul]
    exact W.smul_mem r hy
  | grade1 g =>
    intro y hy
    fin_cases g
    · exact hclE y hy
    · exact hclF y hy
    · exact hclK y hy
    · exact hclL y hy
  | mul a b ha hb =>
    intro y hy
    rw [map_mul, mul_smul]
    exact ha _ (hb y hy)
  | add a b ha hb =>
    intro y hy
    rw [map_add, add_smul]
    exact W.add_mem (ha y hy) (hb y hy)

/-- **Non-root-of-unity necessary constraint.** On a highest weight vector `v` of an
`(n+1)`-dimensional irreducible, `K` acts by `ε qⁿ` for some `ε` with `ε² = 1`.

This theorem records only the eigenvalue constraint. It does not assert that dimension and sign
determine the representation up to isomorphism; that enumeration is part of the intentionally
omitted classification. -/
theorem highest_weight_eigenvalue_of_not_isOfFinOrder (q : ℂˣ) (hq : ¬ IsOfFinOrder q)
    (V : Type*) [AddCommGroup V] [Module ℂ V] [Module (Uqsl2 q) V]
    [IsScalarTower ℂ (Uqsl2 q) V] [FiniteDimensional ℂ V] [IsSimpleModule (Uqsl2 q) V] :
    ∃ (v : V) (ε : ℂ), v ≠ 0 ∧ e q • v = 0 ∧ ε ^ 2 = 1 ∧
      K q • v = (ε * (q : ℂ) ^ (Module.finrank ℂ V - 1)) • v := by
  haveI : Nontrivial V := IsSimpleModule.nontrivial (Uqsl2 q) V
  have hqinv : (q : ℂ) - (q : ℂ)⁻¹ ≠ 0 := q_sub_inv_ne q hq
  obtain ⟨v, lam, hv0, he, hKv⟩ := exists_highest_weight_vector q V hq
  -- The highest weight is nonzero (`K` acts invertibly).
  have hlam : lam ≠ 0 := by
    intro h0
    rw [h0, zero_smul] at hKv
    apply hv0
    have h := congrArg (fun x => L q • x) hKv
    simp only [smul_zero] at h
    rw [← mul_smul, LK_rel, one_smul] at h
    exact h
  -- Termination: some ladder vector vanishes (else infinitely many independent eigenvectors).
  have hex : ∃ i, ladder q V v i = 0 := by
    by_contra hcon
    push Not at hcon
    have hLI : LinearIndependent ℂ (ladder q V v) :=
      Module.End.eigenvectors_linearIndependent' (Kop q V) (mu q lam)
        (mu_inj q hq lam hlam) (ladder q V v)
        (fun i => ⟨Module.End.mem_eigenspace_iff.mpr
          (by rw [Kop_apply]; exact K_ladder q V v lam hKv i), hcon i⟩)
    exact Module.Finite.not_linearIndependent_of_infinite _ hLI
  haveI : DecidablePred (fun i => ladder q V v i = 0) := Classical.decPred _
  set M0 := Nat.find hex with hM0def
  have hM0_spec : ladder q V v M0 = 0 := Nat.find_spec hex
  have hM0_ne : M0 ≠ 0 := by
    intro h0; rw [h0, ladder_zero] at hM0_spec; exact hv0 hM0_spec
  obtain ⟨N, hNsucc⟩ : ∃ N, M0 = N + 1 := ⟨M0 - 1, by omega⟩
  have hzero_succ : ladder q V v (N + 1) = 0 := by rw [← hNsucc]; exact hM0_spec
  have hne_le : ∀ i, i ≤ N → ladder q V v i ≠ 0 := fun i hi => Nat.find_min hex (by omega)
  have hzero_ge : ∀ k, ladder q V v (N + 1 + k) = 0 := by
    intro k
    induction k with
    | zero => simpa using hzero_succ
    | succ j ih => rw [show N + 1 + (j + 1) = (N + 1 + j) + 1 by omega, ladder_succ, ih, smul_zero]
  -- The finite spanning family `b i = fⁱ v`, `i < N+1`, and its `ℂ`-span `W`.
  set b : Fin (N + 1) → V := fun i => ladder q V v ↑i with hb
  set W : Submodule ℂ V := Submodule.span ℂ (Set.range b) with hW
  have hiW : ∀ i, ladder q V v i ∈ W := by
    intro i
    by_cases hiN : i ≤ N
    · exact Submodule.subset_span (Set.mem_range.mpr ⟨⟨i, by omega⟩, rfl⟩)
    · have hle' : N + 1 ≤ i := by omega
      obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le hle'
      rw [hzero_ge k]; exact W.zero_mem
  -- Generator closures on `W`.
  have heW : ∀ i, e q • ladder q V v i ∈ W := by
    intro i
    cases i with
    | zero => rw [ladder_zero, he]; exact W.zero_mem
    | succ j => rw [e_ladder q V hqinv v lam hlam he hKv j]; exact W.smul_mem _ (hiW j)
  have hfW : ∀ i, f q • ladder q V v i ∈ W := fun i => by
    rw [← ladder_succ]; exact hiW (i + 1)
  have hKW : ∀ i, K q • ladder q V v i ∈ W := fun i => by
    rw [K_ladder q V v lam hKv i]; exact W.smul_mem _ (hiW i)
  have hLW : ∀ i, L q • ladder q V v i ∈ W := fun i => by
    rw [L_ladder q V v lam hlam hKv i]; exact W.smul_mem _ (hiW i)
  have clOf : ∀ (a : Uqsl2 q), (∀ i, a • ladder q V v i ∈ W) → ∀ x ∈ W, a • x ∈ W := by
    intro a ha x hx
    induction hx using Submodule.span_induction with
    | mem z hz => obtain ⟨i, rfl⟩ := hz; exact ha ↑i
    | zero => rw [smul_zero]; exact W.zero_mem
    | add p r _ _ hp hr => rw [smul_add]; exact W.add_mem hp hr
    | smul c p _ hp => rw [smul_comm]; exact W.smul_mem c hp
  -- `W` is a `U_q`-submodule; by simplicity it is everything.
  let W' : Submodule (Uqsl2 q) V :=
    { carrier := (W : Set V)
      add_mem' := fun ha hb => W.add_mem ha hb
      zero_mem' := W.zero_mem
      smul_mem' := fun a x hx => smul_mem_of_generators q V W (clOf (e q) heW)
        (clOf (f q) hfW) (clOf (K q) hKW) (clOf (L q) hLW) a x hx }
  have hv_mem : v ∈ W' := by
    change v ∈ W
    have := hiW 0; rwa [ladder_zero] at this
  have hne : W' ≠ ⊥ := by
    intro hbot
    apply hv0
    have : v ∈ (⊥ : Submodule (Uqsl2 q) V) := hbot ▸ hv_mem
    exact (Submodule.mem_bot (Uqsl2 q)).mp this
  have hW'top : W' = ⊤ := (eq_bot_or_eq_top W').resolve_left hne
  have hWtop : W = ⊤ := by
    rw [eq_top_iff]
    intro x _
    have hxW' : x ∈ W' := by rw [hW'top]; exact Submodule.mem_top
    exact hxW'
  -- Dimension count: `finrank ℂ V = N + 1`.
  have hbne : ∀ i : Fin (N + 1), b i ≠ 0 := fun i => hne_le ↑i (Nat.lt_succ_iff.mp i.isLt)
  have hLIb : LinearIndependent ℂ b :=
    Module.End.eigenvectors_linearIndependent' (Kop q V) (fun i : Fin (N + 1) => mu q lam ↑i)
      ((mu_inj q hq lam hlam).comp Fin.val_injective) b
      (fun i => ⟨Module.End.mem_eigenspace_iff.mpr
        (by rw [Kop_apply]; exact K_ladder q V v lam hKv ↑i), hbne i⟩)
  have hge : N + 1 ≤ Module.finrank ℂ V := by
    have := hLIb.fintype_card_le_finrank
    rwa [Fintype.card_fin] at this
  have hle : Module.finrank ℂ V ≤ N + 1 := by
    have hspan : Module.finrank ℂ (Submodule.span ℂ (Set.range b)) ≤ N + 1 := by
      have := finrank_range_le_card (R := ℂ) b
      rwa [Set.finrank, Fintype.card_fin] at this
    rw [← hW, hWtop, finrank_top] at hspan
    exact hspan
  have hfinrank : Module.finrank ℂ V = N + 1 := le_antisymm hle hge
  have hfinrank_sub : Module.finrank ℂ V - 1 = N := by omega
  -- Eigenvalue constraint: `dcoef N = 0`, hence `lam² = q^{2N}`.
  have hdcoef : dcoef q lam N = 0 := by
    have h1 : e q • ladder q V v (N + 1) = dcoef q lam N • ladder q V v N :=
      e_ladder q V hqinv v lam hlam he hKv N
    rw [hzero_succ, smul_zero] at h1
    exact (smul_eq_zero.mp h1.symm).resolve_right (hne_le N le_rfl)
  have hlam2 : lam ^ 2 = (q : ℂ) ^ (2 * N) := dcoef_eq_zero_imp q hq lam hlam N hdcoef
  -- Hence `ε = lam / qᴺ`.
  refine ⟨v, lam * ((q : ℂ) ^ N)⁻¹, hv0, he, ?_, ?_⟩
  · have hqN : (q : ℂ) ^ N ≠ 0 := pow_ne_zero _ q.ne_zero
    rw [mul_pow, hlam2, inv_pow, ← pow_mul, show N * 2 = 2 * N by ring,
      mul_inv_cancel₀ (pow_ne_zero _ q.ne_zero)]
  · rw [hKv]
    congr 1
    rw [hfinrank_sub, mul_assoc, inv_mul_cancel₀ (pow_ne_zero N q.ne_zero), mul_one]

/-! ## Root-of-unity infrastructure: centrality of `K ^ orderOf q`

At a root of unity, the element `K ^ orderOf q` is central in `U_q(sl₂)`. This is the algebraic
seed of the dimension bound: on a finite dimensional irreducible representation a central element
acts as a scalar (Schur's lemma over `ℂ`), which forces `K` to be diagonalizable with at most
`orderOf q` distinct eigenvalues. The commutation lemmas below (`Kpow_mul_e`, `Kpow_mul_f`) hold
for every `q`; the centrality corollaries specialise them at `n = orderOf q`, where the twist
`(q²)^{orderOf q}` collapses to `1`. -/

/-- `K^n` commutes past `e` with a `q^{2n}` twist: `K^n · e = (q²)^n · (e · K^n)`. Iterated form
of the defining relation `Ke_rel`. -/
lemma Kpow_mul_e (q : ℂˣ) (n : ℕ) :
    K q ^ n * e q = (((q : ℂ) ^ 2) ^ n) • (e q * K q ^ n) := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [pow_succ (K q), mul_assoc, Ke_rel, mul_smul_comm, ← mul_assoc, ih,
        smul_mul_assoc, smul_smul, mul_assoc (e q), ← pow_succ (K q),
        mul_comm ((q : ℂ) ^ 2), ← pow_succ]

/-- `K^n` commutes past `f` with a `q^{-2n}` twist: `K^n · f = (q²)⁻ⁿ · (f · K^n)`. Iterated form
of the defining relation `Kf_rel`. -/
lemma Kpow_mul_f (q : ℂˣ) (n : ℕ) :
    K q ^ n * f q = ((((q : ℂ) ^ 2)⁻¹) ^ n) • (f q * K q ^ n) := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [pow_succ (K q), mul_assoc, Kf_rel, mul_smul_comm, ← mul_assoc, ih,
        smul_mul_assoc, smul_smul, mul_assoc (f q), ← pow_succ (K q),
        mul_comm (((q : ℂ) ^ 2)⁻¹), ← pow_succ]

/-- At a root of unity the twist collapses: `(q²)^{orderOf q} = 1`. -/
lemma sq_pow_orderOf_eq_one (q : ℂˣ) : ((q : ℂ) ^ 2) ^ orderOf q = 1 := by
  have hq1 : (q : ℂ) ^ orderOf q = 1 := by
    rw [← Units.val_pow_eq_pow_val, pow_orderOf_eq_one, Units.val_one]
  rw [← pow_mul, mul_comm, pow_mul, hq1, one_pow]

/-- **Centrality of `K ^ orderOf q` against `e`.** At a root of unity `K ^ orderOf q` commutes
with `e`. -/
lemma Kpow_orderOf_mul_e (q : ℂˣ) :
    K q ^ orderOf q * e q = e q * K q ^ orderOf q := by
  rw [Kpow_mul_e, sq_pow_orderOf_eq_one, one_smul]

/-- **Centrality of `K ^ orderOf q` against `f`.** At a root of unity `K ^ orderOf q` commutes
with `f`. -/
lemma Kpow_orderOf_mul_f (q : ℂˣ) :
    K q ^ orderOf q * f q = f q * K q ^ orderOf q := by
  rw [Kpow_mul_f, inv_pow, sq_pow_orderOf_eq_one, inv_one, one_smul]

/-- **Centrality of `K ^ orderOf q`.** At a root of unity the element `K ^ orderOf q` is central
in `U_q(sl₂)`: it commutes with every element. It commutes with all four generators
(`Kpow_orderOf_mul_e`, `Kpow_orderOf_mul_f`, and trivially with `K` and `L`), and these generate;
we reduce a general element to the generator cases via the surjection `mk q` and
`FreeAlgebra.induction`. -/
lemma Kpow_orderOf_central (q : ℂˣ) (a : Uqsl2 q) :
    K q ^ orderOf q * a = a * K q ^ orderOf q := by
  suffices H : ∀ p : FreeAlgebra ℂ Gen,
      K q ^ orderOf q * mk q p = mk q p * K q ^ orderOf q by
    obtain ⟨p, rfl⟩ := RingQuot.mkAlgHom_surjective ℂ (Rel q) a
    exact H p
  intro p
  induction p using FreeAlgebra.induction with
  | grade0 r =>
      rw [show mk q (algebraMap ℂ (FreeAlgebra ℂ Gen) r) = algebraMap ℂ (Uqsl2 q) r from
        AlgHom.commutes (mk q) r, Algebra.commutes]
  | grade1 g =>
      fin_cases g
      · change K q ^ orderOf q * e q = e q * K q ^ orderOf q
        exact Kpow_orderOf_mul_e q
      · change K q ^ orderOf q * f q = f q * K q ^ orderOf q
        exact Kpow_orderOf_mul_f q
      · change K q ^ orderOf q * K q = K q * K q ^ orderOf q
        rw [← pow_succ, ← pow_succ']
      · change K q ^ orderOf q * L q = L q * K q ^ orderOf q
        have hc : Commute (K q) (L q) := by
          change K q * L q = L q * K q; rw [KL_rel, LK_rel]
        exact (hc.pow_left (orderOf q)).eq
  | mul x y hx hy =>
      rw [map_mul, ← mul_assoc, hx, mul_assoc, hy, ← mul_assoc]
  | add x y hx hy =>
      rw [map_add, mul_add, add_mul, hx, hy]

/-- The `n`-th power of the `K`-endomorphism `Kop` applies as `K^n • ·`. -/
lemma Kop_pow_apply (q : ℂˣ) (V : Type*) [AddCommGroup V] [Module ℂ V] [Module (Uqsl2 q) V]
    [IsScalarTower ℂ (Uqsl2 q) V] [FiniteDimensional ℂ V] (n : ℕ) (v : V) :
    (Kop q V ^ n) v = K q ^ n • v := by
  induction n generalizing v with
  | zero => simp
  | succ n ih => rw [pow_succ, Module.End.mul_apply, Kop_apply, ih, ← mul_smul, ← pow_succ]

/-- **`K ^ orderOf q` acts as a nonzero scalar.** On a finite dimensional irreducible
`U_q(sl₂)`-module over `ℂ`, the central element `K ^ orderOf q` acts as a single scalar `α ≠ 0`.
This is Schur's lemma: `K ^ orderOf q` is central (`Kpow_orderOf_central`), so it acts
`U_q`-linearly and each of its `ℂ`-eigenspaces is a `U_q`-submodule. Over the algebraically closed
`ℂ` with `V` finite dimensional the operator has an eigenvalue `α`, and its `α`-eigenspace, being a
nonzero `U_q`-submodule of the simple module `V`, is all of `V`. `α ≠ 0` because `K ^ orderOf q` is
a unit (`K · L = 1`). -/
theorem Kpow_orderOf_isScalar (q : ℂˣ) (_hq : IsOfFinOrder q)
    (V : Type*) [AddCommGroup V] [Module ℂ V] [Module (Uqsl2 q) V]
    [IsScalarTower ℂ (Uqsl2 q) V] [FiniteDimensional ℂ V] [IsSimpleModule (Uqsl2 q) V] :
    ∃ α : ℂ, α ≠ 0 ∧ ∀ v : V, K q ^ orderOf q • v = α • v := by
  haveI : Nontrivial V := IsSimpleModule.nontrivial (Uqsl2 q) V
  -- `α`: an eigenvalue of the endomorphism `Kop ^ orderOf q`.
  obtain ⟨α, hα⟩ := Module.End.exists_eigenvalue (Kop q V ^ orderOf q)
  -- The `α`-eigenspace is a `U_q`-submodule (centrality of `K ^ orderOf q`).
  let W' : Submodule (Uqsl2 q) V :=
    { carrier := (Module.End.eigenspace (Kop q V ^ orderOf q) α : Set V)
      add_mem' := fun ha hb => Submodule.add_mem _ ha hb
      zero_mem' := Submodule.zero_mem _
      smul_mem' := by
        intro a x hx
        rw [SetLike.mem_coe, Module.End.mem_eigenspace_iff, Kop_pow_apply] at hx
        rw [SetLike.mem_coe, Module.End.mem_eigenspace_iff, Kop_pow_apply,
          ← mul_smul, Kpow_orderOf_central, mul_smul, hx, smul_comm] }
  -- Nonzero (it contains an eigenvector), so by simplicity it is everything.
  have hne : W' ≠ ⊥ := by
    obtain ⟨v, hv, hv0⟩ := hα.exists_hasEigenvector
    intro hbot
    apply hv0
    have hmem : v ∈ W' := hv
    rw [hbot, Submodule.mem_bot] at hmem
    exact hmem
  have htop : W' = ⊤ := (eq_bot_or_eq_top W').resolve_left hne
  refine ⟨α, ?_, ?_⟩
  · -- `α ≠ 0` since `K ^ orderOf q` is a unit (inverse `L ^ orderOf q`).
    obtain ⟨v, hv, hv0⟩ := hα.exists_hasEigenvector
    intro hα0
    apply hv0
    have hKv : K q ^ orderOf q • v = 0 := by
      have hmem := Module.End.mem_eigenspace_iff.mp hv
      rw [Kop_pow_apply, hα0, zero_smul] at hmem
      exact hmem
    have hLK : L q ^ orderOf q * K q ^ orderOf q = 1 := by
      have hc : Commute (L q) (K q) := by
        change L q * K q = K q * L q; rw [LK_rel, KL_rel]
      rw [← hc.mul_pow, LK_rel, one_pow]
    have h := congrArg (fun x => L q ^ orderOf q • x) hKv
    simp only [smul_zero] at h
    rw [← mul_smul, hLK, one_smul] at h
    exact h
  · intro v
    have hv_mem : v ∈ W' := by rw [htop]; exact Submodule.mem_top
    have hmem : v ∈ Module.End.eigenspace (Kop q V ^ orderOf q) α := hv_mem
    rw [Module.End.mem_eigenspace_iff, Kop_pow_apply] at hmem
    exact hmem

/-- **`K` is diagonalizable at a root of unity.** On a finite dimensional irreducible
`U_q(sl₂)`-module over `ℂ`, the `K`-endomorphism `Kop` is a semisimple operator: it satisfies the
separable annihilating polynomial `X ^ orderOf q - C α` (where `α` is the scalar from
`Kpow_orderOf_isScalar`, nonzero, so the polynomial is squarefree in characteristic zero), hence its
eigenspaces span `V`, and every `K`-eigenvalue is an `orderOf q`-th root of `α` (so there are at
most `orderOf q` distinct `K`-eigenvalues). -/
theorem Kop_isSemisimple_and_eigenvalues (q : ℂˣ) (hq : IsOfFinOrder q)
    (V : Type*) [AddCommGroup V] [Module ℂ V] [Module (Uqsl2 q) V]
    [IsScalarTower ℂ (Uqsl2 q) V] [FiniteDimensional ℂ V] [IsSimpleModule (Uqsl2 q) V] :
    (Kop q V).IsSemisimple ∧
      (⨆ μ : ℂ, Module.End.eigenspace (Kop q V) μ) = ⊤ ∧
      ∃ α : ℂ, α ≠ 0 ∧ ∀ μ : ℂ, (Kop q V).HasEigenvalue μ → μ ^ orderOf q = α := by
  obtain ⟨α, hα0, hα⟩ := Kpow_orderOf_isScalar q hq V
  have hℓ : 0 < orderOf q := hq.orderOf_pos
  -- `Kop` satisfies `Kop ^ orderOf q = α • 1`.
  have hpow : Kop q V ^ orderOf q = α • (1 : Module.End ℂ V) := by
    ext v; rw [Kop_pow_apply, hα v, LinearMap.smul_apply, Module.End.one_apply]
  -- so it is a root of the separable (hence squarefree) polynomial `X ^ orderOf q - C α`.
  have hss : (Kop q V).IsSemisimple := by
    have hsqf : Squarefree (Polynomial.X ^ orderOf q - Polynomial.C α : Polynomial ℂ) :=
      (Polynomial.separable_X_pow_sub_C α (Nat.cast_ne_zero.mpr hℓ.ne') hα0).squarefree
    have haeval : Polynomial.aeval (Kop q V) (Polynomial.X ^ orderOf q - Polynomial.C α) = 0 := by
      rw [map_sub, map_pow, Polynomial.aeval_X, Polynomial.aeval_C, hpow,
        Algebra.algebraMap_eq_smul_one, sub_self]
    exact Module.End.isSemisimple_of_squarefree_aeval_eq_zero hsqf haeval
  refine ⟨hss, hss.iSup_eigenspace_eq_top, α, hα0, ?_⟩
  intro μ hμ
  obtain ⟨v, hv, hv0⟩ := hμ.exists_hasEigenvector
  have hve : Kop q V v = μ • v := Module.End.mem_eigenspace_iff.mp hv
  -- On the eigenvector `v`, `Kop ^ n` acts by `μ ^ n`; specialise at `orderOf q`, compare to `α`.
  have hpm : ∀ n : ℕ, (Kop q V ^ n) v = μ ^ n • v := by
    intro n
    induction n with
    | zero => simp
    | succ n ih => rw [pow_succ, Module.End.mul_apply, hve, map_smul, ih, smul_smul, ← pow_succ']
  have h1 : μ ^ orderOf q • v = α • v := by
    rw [← hpm, hpow, LinearMap.smul_apply, Module.End.one_apply]
  have h2 : (μ ^ orderOf q - α) • v = 0 := by rw [sub_smul, h1, sub_self]
  exact (smul_eq_zero.mp h2).resolve_right hv0 |> sub_eq_zero.mp

/-! ## Root-of-unity infrastructure: centrality of `e ^ orderOf q` and `f ^ orderOf q`

At a root of unity with `q ≠ ±1` (equivalently `q² ≠ 1`) the elements `e ^ orderOf q` and
`f ^ orderOf q` are central in `U_q(sl₂)`. Together with the already-established centrality of
`K ^ orderOf q`, these are the three central "closed-string" scalars of the De Concini–Kac small
quantum group; on a finite dimensional simple module each acts as a scalar (Schur). The nontrivial
commutation is `[e ^ orderOf q, f] = 0`: the iterated commutator `[eⁿ, f]` has a coefficient that is
a geometric sum in `q²`, and at `n = orderOf q` that sum vanishes precisely because
`(q²)^{orderOf q} = 1` while `q² ≠ 1`.

The hypothesis `q² ≠ 1` is essential and cannot be dropped: at `q = ±1` the defining relation
`(q - q⁻¹)·(ef - fe) = K - L` degenerates (its left side vanishes), `e` and `f` become free, and
`e ^ orderOf q` is no longer central. -/

/-- `q - q⁻¹ ≠ 0` whenever `q² ≠ 1` (i.e. `q ≠ ±1`). The root-of-unity analogue of
`q_sub_inv_ne`, which assumed `¬ IsOfFinOrder q`. -/
lemma q_sub_inv_ne_of_sq_ne (q : ℂˣ) (hq2 : (q : ℂ) ^ 2 ≠ 1) : (q : ℂ) - (q : ℂ)⁻¹ ≠ 0 := by
  intro h
  have h2 : (q : ℂ) = (q : ℂ)⁻¹ := sub_eq_zero.mp h
  have : (q : ℂ) ^ 2 = 1 := by rw [sq]; nth_rewrite 2 [h2]; exact mul_inv_cancel₀ q.ne_zero
  exact hq2 this

/-- `L e = q⁻²·(e L)`, the `L`-companion of `Ke_rel`. Derived by conjugating `Ke_rel` by `L`. -/
@[simp] lemma Le_rel (q : ℂˣ) : L q * e q = ((q : ℂ) ^ 2)⁻¹ • (e q * L q) := by
  have hq2 : ((q : ℂ) ^ 2) ≠ 0 := pow_ne_zero _ q.ne_zero
  have key : e q * L q = ((q : ℂ) ^ 2) • (L q * e q) := by
    have h : L q * (K q * e q) * L q = L q * (((q : ℂ) ^ 2) • (e q * K q)) * L q := by
      rw [Ke_rel]
    rw [mul_smul_comm, smul_mul_assoc] at h
    rw [show L q * (K q * e q) * L q = e q * L q by
          rw [← mul_assoc (L q) (K q) (e q), LK_rel, one_mul]] at h
    rw [show L q * (e q * K q) * L q = L q * e q by
          rw [mul_assoc (L q) (e q * K q) (L q), mul_assoc (e q) (K q) (L q), KL_rel, mul_one]] at h
    exact h
  rw [key, smul_smul, inv_mul_cancel₀ hq2, one_smul]

/-- `L f = q²·(f L)`, the `L`-companion of `Kf_rel`. Derived by conjugating `Kf_rel` by `L`. -/
@[simp] lemma Lf_rel (q : ℂˣ) : L q * f q = ((q : ℂ) ^ 2) • (f q * L q) := by
  have key : f q * L q = ((q : ℂ) ^ 2)⁻¹ • (L q * f q) := by
    have h : L q * (K q * f q) * L q = L q * (((q : ℂ) ^ 2)⁻¹ • (f q * K q)) * L q := by
      rw [Kf_rel]
    rw [mul_smul_comm, smul_mul_assoc] at h
    rw [show L q * (K q * f q) * L q = f q * L q by
          rw [← mul_assoc (L q) (K q) (f q), LK_rel, one_mul]] at h
    rw [show L q * (f q * K q) * L q = L q * f q by
          rw [mul_assoc (L q) (f q * K q) (L q), mul_assoc (f q) (K q) (L q), KL_rel, mul_one]] at h
    exact h
  have hq2 : ((q : ℂ) ^ 2) ≠ 0 := pow_ne_zero _ q.ne_zero
  rw [key, smul_smul, mul_inv_cancel₀ hq2, one_smul]

/-- The commutator `[e, f] = (K - L)/(q - q⁻¹)` in un-cleared form, valid once `q ≠ ±1`. -/
lemma ef_diff (q : ℂˣ) (hq' : (q : ℂ) - (q : ℂ)⁻¹ ≠ 0) :
    e q * f q = f q * e q + (((q : ℂ) - (q : ℂ)⁻¹)⁻¹) • (K q - L q) := by
  have h := ef_rel q
  have hd : e q * f q - f q * e q = (((q : ℂ) - (q : ℂ)⁻¹)⁻¹) • (K q - L q) := by
    rw [← h, inv_smul_smul₀ hq']
  rw [← hd]; abel

/-- `K` commutes past `eⁿ` with a `q^{2n}` twist: `K · eⁿ = (q²)ⁿ · (eⁿ · K)`. -/
lemma K_mul_epow (q : ℂˣ) (n : ℕ) :
    K q * e q ^ n = (((q : ℂ) ^ 2) ^ n) • (e q ^ n * K q) := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [pow_succ (e q) n, ← mul_assoc, ih, smul_mul_assoc, mul_assoc (e q ^ n) (K q) (e q),
        Ke_rel, mul_smul_comm, smul_smul, ← mul_assoc (e q ^ n) (e q) (K q),
        ← pow_succ ((q : ℂ) ^ 2) n]

/-- `L` commutes past `eⁿ` with a `q^{-2n}` twist: `L · eⁿ = (q⁻²)ⁿ · (eⁿ · L)`. -/
lemma L_mul_epow (q : ℂˣ) (n : ℕ) :
    L q * e q ^ n = ((((q : ℂ) ^ 2)⁻¹) ^ n) • (e q ^ n * L q) := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [pow_succ (e q) n, ← mul_assoc, ih, smul_mul_assoc, mul_assoc (e q ^ n) (L q) (e q),
        Le_rel, mul_smul_comm, smul_smul, ← mul_assoc (e q ^ n) (e q) (L q),
        ← pow_succ (((q : ℂ) ^ 2)⁻¹) n]

/-- `K` commutes past `fⁿ` with a `q^{-2n}` twist: `K · fⁿ = (q⁻²)ⁿ · (fⁿ · K)`. -/
lemma K_mul_fpow (q : ℂˣ) (n : ℕ) :
    K q * f q ^ n = ((((q : ℂ) ^ 2)⁻¹) ^ n) • (f q ^ n * K q) := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [pow_succ (f q) n, ← mul_assoc, ih, smul_mul_assoc, mul_assoc (f q ^ n) (K q) (f q),
        Kf_rel, mul_smul_comm, smul_smul, ← mul_assoc (f q ^ n) (f q) (K q),
        ← pow_succ (((q : ℂ) ^ 2)⁻¹) n]

/-- `L` commutes past `fⁿ` with a `q^{2n}` twist: `L · fⁿ = (q²)ⁿ · (fⁿ · L)`. -/
lemma L_mul_fpow (q : ℂˣ) (n : ℕ) :
    L q * f q ^ n = (((q : ℂ) ^ 2) ^ n) • (f q ^ n * L q) := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [pow_succ (f q) n, ← mul_assoc, ih, smul_mul_assoc, mul_assoc (f q ^ n) (L q) (f q),
        Lf_rel, mul_smul_comm, smul_smul, ← mul_assoc (f q ^ n) (f q) (L q),
        ← pow_succ ((q : ℂ) ^ 2) n]

/-- Iterated commutator formula: `[eⁿ⁺¹, f]` reduces to `eⁿ` times an explicit `K`/`L`
combination whose scalar coefficients are geometric sums in `q²`. Requires `q ≠ ±1` (so that the
commutator `[e, f] = (K - L)/(q - q⁻¹)` is well-defined). -/
lemma e_pow_mul_f (q : ℂˣ) (hq' : (q : ℂ) - (q : ℂ)⁻¹ ≠ 0) (n : ℕ) :
    e q ^ (n + 1) * f q
      = f q * e q ^ (n + 1)
        + (((q : ℂ) - (q : ℂ)⁻¹)⁻¹ * ∑ k ∈ Finset.range (n + 1), ((q : ℂ) ^ 2) ^ k)
            • (e q ^ n * K q)
        - (((q : ℂ) - (q : ℂ)⁻¹)⁻¹ * ∑ k ∈ Finset.range (n + 1), (((q : ℂ) ^ 2)⁻¹) ^ k)
            • (e q ^ n * L q) := by
  induction n with
  | zero =>
    simp only [zero_add, pow_one, pow_zero, one_mul, mul_one, Finset.range_one,
      Finset.sum_singleton]
    rw [ef_diff q hq', smul_sub]
    abel
  | succ n ih =>
    have hAK : e q * (e q ^ n * K q) = e q ^ (n + 1) * K q := by
      rw [← mul_assoc, ← pow_succ' (e q) n]
    have hAL : e q * (e q ^ n * L q) = e q ^ (n + 1) * L q := by
      rw [← mul_assoc, ← pow_succ' (e q) n]
    have key : e q * (f q * e q ^ (n + 1))
        = f q * e q ^ (n + 1 + 1)
          + ((q : ℂ) - (q : ℂ)⁻¹)⁻¹ • (K q * e q ^ (n + 1))
          - ((q : ℂ) - (q : ℂ)⁻¹)⁻¹ • (L q * e q ^ (n + 1)) := by
      rw [← mul_assoc, ef_diff q hq', add_mul, smul_mul_assoc, sub_mul, smul_sub,
        mul_assoc (f q) (e q) (e q ^ (n + 1)), ← pow_succ' (e q) (n + 1)]
      abel
    rw [Finset.sum_range_succ (fun k => ((q : ℂ) ^ 2) ^ k) (n + 1),
        Finset.sum_range_succ (fun k => (((q : ℂ) ^ 2)⁻¹) ^ k) (n + 1)]
    conv_lhs =>
      rw [pow_succ' (e q) (n + 1), mul_assoc (e q) (e q ^ (n + 1)) (f q), ih,
        mul_sub, mul_add, mul_smul_comm, mul_smul_comm, key, hAK, hAL,
        K_mul_epow q (n + 1), L_mul_epow q (n + 1)]
    module

/-- `[e ^ orderOf q, f] = 0` at a root of unity with `q ≠ ±1`. The geometric-sum coefficients in
`e_pow_mul_f` vanish at `n = orderOf q` because `(q²)^{orderOf q} = 1` and `q² ≠ 1`. -/
lemma epow_orderOf_mul_f (q : ℂˣ) (hq2 : (q : ℂ) ^ 2 ≠ 1) :
    e q ^ orderOf q * f q = f q * e q ^ orderOf q := by
  have hq' : (q : ℂ) - (q : ℂ)⁻¹ ≠ 0 := q_sub_inv_ne_of_sq_ne q hq2
  rcases Nat.eq_zero_or_pos (orderOf q) with h0 | hpos
  · rw [h0, pow_zero, one_mul, mul_one]
  · obtain ⟨m, hm⟩ : ∃ m, orderOf q = m + 1 := Nat.exists_eq_succ_of_ne_zero hpos.ne'
    rw [hm]
    have h1 : ((q : ℂ) ^ 2) ^ (m + 1) = 1 := by rw [← hm]; exact sq_pow_orderOf_eq_one q
    have hSA : (∑ k ∈ Finset.range (m + 1), ((q : ℂ) ^ 2) ^ k) = 0 := by
      have hgeom : (∑ k ∈ Finset.range (m + 1), ((q : ℂ) ^ 2) ^ k) * ((q : ℂ) ^ 2 - 1)
          = ((q : ℂ) ^ 2) ^ (m + 1) - 1 := geom_sum_mul _ _
      rw [h1, sub_self] at hgeom
      exact (mul_eq_zero.mp hgeom).resolve_right (sub_ne_zero.mpr hq2)
    have hSB : (∑ k ∈ Finset.range (m + 1), (((q : ℂ) ^ 2)⁻¹) ^ k) = 0 := by
      have h1' : (((q : ℂ) ^ 2)⁻¹) ^ (m + 1) = 1 := by rw [inv_pow, h1, inv_one]
      have hgeom : (∑ k ∈ Finset.range (m + 1), (((q : ℂ) ^ 2)⁻¹) ^ k) * (((q : ℂ) ^ 2)⁻¹ - 1)
          = (((q : ℂ) ^ 2)⁻¹) ^ (m + 1) - 1 := geom_sum_mul _ _
      rw [h1', sub_self] at hgeom
      exact (mul_eq_zero.mp hgeom).resolve_right
        (sub_ne_zero.mpr (fun h => hq2 (inv_eq_one.mp h)))
    rw [e_pow_mul_f q hq' m, hSA, hSB]
    simp

/-- `e ^ orderOf q` commutes with `K` (twist `(q²)^{orderOf q} = 1`). -/
lemma epow_orderOf_mul_K (q : ℂˣ) : e q ^ orderOf q * K q = K q * e q ^ orderOf q := by
  rw [K_mul_epow q (orderOf q), sq_pow_orderOf_eq_one, one_smul]

/-- `e ^ orderOf q` commutes with `L` (twist `(q⁻²)^{orderOf q} = 1`). -/
lemma epow_orderOf_mul_L (q : ℂˣ) : e q ^ orderOf q * L q = L q * e q ^ orderOf q := by
  rw [L_mul_epow q (orderOf q), inv_pow, sq_pow_orderOf_eq_one, inv_one, one_smul]

/-- `e ^ orderOf q` commutes with `e` (powers of `e`). -/
lemma epow_orderOf_mul_e (q : ℂˣ) : e q ^ orderOf q * e q = e q * e q ^ orderOf q := by
  rw [← pow_succ, ← pow_succ']

/-- **Centrality of `e ^ orderOf q`.** At a root of unity with `q ≠ ±1`, `e ^ orderOf q` is central
in `U_q(sl₂)`. It commutes with all four generators; these generate, so a general element reduces to
the generator cases via the surjection `mk q` and `FreeAlgebra.induction`. -/
lemma epow_orderOf_central (q : ℂˣ) (hq2 : (q : ℂ) ^ 2 ≠ 1) (a : Uqsl2 q) :
    e q ^ orderOf q * a = a * e q ^ orderOf q := by
  suffices H : ∀ p : FreeAlgebra ℂ Gen,
      e q ^ orderOf q * mk q p = mk q p * e q ^ orderOf q by
    obtain ⟨p, rfl⟩ := RingQuot.mkAlgHom_surjective ℂ (Rel q) a
    exact H p
  intro p
  induction p using FreeAlgebra.induction with
  | grade0 r =>
      rw [show mk q (algebraMap ℂ (FreeAlgebra ℂ Gen) r) = algebraMap ℂ (Uqsl2 q) r from
        AlgHom.commutes (mk q) r, Algebra.commutes]
  | grade1 g =>
      fin_cases g
      · change e q ^ orderOf q * e q = e q * e q ^ orderOf q
        exact epow_orderOf_mul_e q
      · change e q ^ orderOf q * f q = f q * e q ^ orderOf q
        exact epow_orderOf_mul_f q hq2
      · change e q ^ orderOf q * K q = K q * e q ^ orderOf q
        exact epow_orderOf_mul_K q
      · change e q ^ orderOf q * L q = L q * e q ^ orderOf q
        exact epow_orderOf_mul_L q
  | mul x y hx hy =>
      rw [map_mul, ← mul_assoc, hx, mul_assoc, hy, ← mul_assoc]
  | add x y hx hy =>
      rw [map_add, mul_add, add_mul, hx, hy]

/-- The commutator `[f, e] = -(K - L)/(q - q⁻¹)`, the mirror of `ef_diff`. -/
lemma fe_diff (q : ℂˣ) (hq' : (q : ℂ) - (q : ℂ)⁻¹ ≠ 0) :
    f q * e q = e q * f q - (((q : ℂ) - (q : ℂ)⁻¹)⁻¹) • (K q - L q) := by
  have h := ef_diff q hq'
  rw [h]; abel

/-- Iterated commutator formula for the `f`-power: `[fⁿ⁺¹, e]` reduces to `fⁿ` times an explicit
`K`/`L` combination. Mirror of `e_pow_mul_f`. -/
lemma f_pow_mul_e (q : ℂˣ) (hq' : (q : ℂ) - (q : ℂ)⁻¹ ≠ 0) (n : ℕ) :
    f q ^ (n + 1) * e q
      = e q * f q ^ (n + 1)
        - (((q : ℂ) - (q : ℂ)⁻¹)⁻¹ * ∑ k ∈ Finset.range (n + 1), (((q : ℂ) ^ 2)⁻¹) ^ k)
            • (f q ^ n * K q)
        + (((q : ℂ) - (q : ℂ)⁻¹)⁻¹ * ∑ k ∈ Finset.range (n + 1), ((q : ℂ) ^ 2) ^ k)
            • (f q ^ n * L q) := by
  induction n with
  | zero =>
    simp only [zero_add, pow_one, pow_zero, one_mul, mul_one, Finset.range_one,
      Finset.sum_singleton]
    rw [fe_diff q hq', smul_sub]
    abel
  | succ n ih =>
    have hAK : f q * (f q ^ n * K q) = f q ^ (n + 1) * K q := by
      rw [← mul_assoc, ← pow_succ' (f q) n]
    have hAL : f q * (f q ^ n * L q) = f q ^ (n + 1) * L q := by
      rw [← mul_assoc, ← pow_succ' (f q) n]
    have key : f q * (e q * f q ^ (n + 1))
        = e q * f q ^ (n + 1 + 1)
          - ((q : ℂ) - (q : ℂ)⁻¹)⁻¹ • (K q * f q ^ (n + 1))
          + ((q : ℂ) - (q : ℂ)⁻¹)⁻¹ • (L q * f q ^ (n + 1)) := by
      rw [← mul_assoc, fe_diff q hq', sub_mul, smul_mul_assoc, sub_mul, smul_sub,
        mul_assoc (e q) (f q) (f q ^ (n + 1)), ← pow_succ' (f q) (n + 1)]
      abel
    rw [Finset.sum_range_succ (fun k => (((q : ℂ) ^ 2)⁻¹) ^ k) (n + 1),
        Finset.sum_range_succ (fun k => ((q : ℂ) ^ 2) ^ k) (n + 1)]
    conv_lhs =>
      rw [pow_succ' (f q) (n + 1), mul_assoc (f q) (f q ^ (n + 1)) (e q), ih,
        mul_add, mul_sub, mul_smul_comm, mul_smul_comm, key, hAK, hAL,
        K_mul_fpow q (n + 1), L_mul_fpow q (n + 1)]
    module

/-- `[f ^ orderOf q, e] = 0` at a root of unity with `q ≠ ±1`. Mirror of `epow_orderOf_mul_f`. -/
lemma fpow_orderOf_mul_e (q : ℂˣ) (hq2 : (q : ℂ) ^ 2 ≠ 1) :
    f q ^ orderOf q * e q = e q * f q ^ orderOf q := by
  have hq' : (q : ℂ) - (q : ℂ)⁻¹ ≠ 0 := q_sub_inv_ne_of_sq_ne q hq2
  rcases Nat.eq_zero_or_pos (orderOf q) with h0 | hpos
  · rw [h0, pow_zero, one_mul, mul_one]
  · obtain ⟨m, hm⟩ : ∃ m, orderOf q = m + 1 := Nat.exists_eq_succ_of_ne_zero hpos.ne'
    rw [hm]
    have h1 : ((q : ℂ) ^ 2) ^ (m + 1) = 1 := by rw [← hm]; exact sq_pow_orderOf_eq_one q
    have hSA : (∑ k ∈ Finset.range (m + 1), ((q : ℂ) ^ 2) ^ k) = 0 := by
      have hgeom : (∑ k ∈ Finset.range (m + 1), ((q : ℂ) ^ 2) ^ k) * ((q : ℂ) ^ 2 - 1)
          = ((q : ℂ) ^ 2) ^ (m + 1) - 1 := geom_sum_mul _ _
      rw [h1, sub_self] at hgeom
      exact (mul_eq_zero.mp hgeom).resolve_right (sub_ne_zero.mpr hq2)
    have hSB : (∑ k ∈ Finset.range (m + 1), (((q : ℂ) ^ 2)⁻¹) ^ k) = 0 := by
      have h1' : (((q : ℂ) ^ 2)⁻¹) ^ (m + 1) = 1 := by rw [inv_pow, h1, inv_one]
      have hgeom : (∑ k ∈ Finset.range (m + 1), (((q : ℂ) ^ 2)⁻¹) ^ k) * (((q : ℂ) ^ 2)⁻¹ - 1)
          = (((q : ℂ) ^ 2)⁻¹) ^ (m + 1) - 1 := geom_sum_mul _ _
      rw [h1', sub_self] at hgeom
      exact (mul_eq_zero.mp hgeom).resolve_right
        (sub_ne_zero.mpr (fun h => hq2 (inv_eq_one.mp h)))
    rw [f_pow_mul_e q hq' m, hSA, hSB]
    simp

/-- `f ^ orderOf q` commutes with `K` (twist `(q⁻²)^{orderOf q} = 1`). -/
lemma fpow_orderOf_mul_K (q : ℂˣ) : f q ^ orderOf q * K q = K q * f q ^ orderOf q := by
  rw [K_mul_fpow q (orderOf q), inv_pow, sq_pow_orderOf_eq_one, inv_one, one_smul]

/-- `f ^ orderOf q` commutes with `L` (twist `(q²)^{orderOf q} = 1`). -/
lemma fpow_orderOf_mul_L (q : ℂˣ) : f q ^ orderOf q * L q = L q * f q ^ orderOf q := by
  rw [L_mul_fpow q (orderOf q), sq_pow_orderOf_eq_one, one_smul]

/-- `f ^ orderOf q` commutes with `f` (powers of `f`). -/
lemma fpow_orderOf_mul_f (q : ℂˣ) : f q ^ orderOf q * f q = f q * f q ^ orderOf q := by
  rw [← pow_succ, ← pow_succ']

/-- **Centrality of `f ^ orderOf q`.** At a root of unity with `q ≠ ±1`, `f ^ orderOf q` is central
in `U_q(sl₂)`. Mirror of `epow_orderOf_central`. -/
lemma fpow_orderOf_central (q : ℂˣ) (hq2 : (q : ℂ) ^ 2 ≠ 1) (a : Uqsl2 q) :
    f q ^ orderOf q * a = a * f q ^ orderOf q := by
  suffices H : ∀ p : FreeAlgebra ℂ Gen,
      f q ^ orderOf q * mk q p = mk q p * f q ^ orderOf q by
    obtain ⟨p, rfl⟩ := RingQuot.mkAlgHom_surjective ℂ (Rel q) a
    exact H p
  intro p
  induction p using FreeAlgebra.induction with
  | grade0 r =>
      rw [show mk q (algebraMap ℂ (FreeAlgebra ℂ Gen) r) = algebraMap ℂ (Uqsl2 q) r from
        AlgHom.commutes (mk q) r, Algebra.commutes]
  | grade1 g =>
      fin_cases g
      · change f q ^ orderOf q * e q = e q * f q ^ orderOf q
        exact fpow_orderOf_mul_e q hq2
      · change f q ^ orderOf q * f q = f q * f q ^ orderOf q
        exact fpow_orderOf_mul_f q
      · change f q ^ orderOf q * K q = K q * f q ^ orderOf q
        exact fpow_orderOf_mul_K q
      · change f q ^ orderOf q * L q = L q * f q ^ orderOf q
        exact fpow_orderOf_mul_L q
  | mul x y hx hy =>
      rw [map_mul, ← mul_assoc, hx, mul_assoc, hy, ← mul_assoc]
  | add x y hx hy =>
      rw [map_add, mul_add, add_mul, hx, hy]

section CentralScalar

variable (q : ℂˣ)
variable (V : Type*) [AddCommGroup V] [Module ℂ V] [Module (Uqsl2 q) V]
  [IsScalarTower ℂ (Uqsl2 q) V]

/-- The action of an algebra element `x` packaged as a `ℂ`-linear endomorphism of `V`. -/
noncomputable def smulEnd (x : Uqsl2 q) : Module.End ℂ V where
  toFun v := x • v
  map_add' := by intro a b; rw [smul_add]
  map_smul' := by intro c v; exact smul_comm x c v

/-- Evaluation formula for `smulEnd`. -/
@[simp] lemma smulEnd_apply (x : Uqsl2 q) (v : V) : smulEnd q V x v = x • v := rfl

/-- **Schur's lemma for central elements.** A central element `x` of `U_q(sl₂)` acts as a scalar on
every finite dimensional simple module over the algebraically closed field `ℂ`: its action is a
`U_q`-linear endomorphism, so each `ℂ`-eigenspace is a `U_q`-submodule, and the eigenspace of an
eigenvalue `α` (which exists by finite-dimensionality over `ℂ`) is a nonzero submodule of the simple
`V`, hence all of `V`. Unlike the `K ^ orderOf q` case the scalar need not be nonzero. -/
theorem central_isScalar (x : Uqsl2 q) (hx : ∀ a : Uqsl2 q, x * a = a * x)
    [FiniteDimensional ℂ V] [IsSimpleModule (Uqsl2 q) V] :
    ∃ α : ℂ, ∀ v : V, x • v = α • v := by
  haveI : Nontrivial V := IsSimpleModule.nontrivial (Uqsl2 q) V
  obtain ⟨α, hα⟩ := Module.End.exists_eigenvalue (smulEnd q V x)
  let W' : Submodule (Uqsl2 q) V :=
    { carrier := (Module.End.eigenspace (smulEnd q V x) α : Set V)
      add_mem' := fun ha hb => Submodule.add_mem _ ha hb
      zero_mem' := Submodule.zero_mem _
      smul_mem' := by
        intro a v hv
        rw [SetLike.mem_coe, Module.End.mem_eigenspace_iff, smulEnd_apply] at hv
        rw [SetLike.mem_coe, Module.End.mem_eigenspace_iff, smulEnd_apply,
          ← mul_smul, hx, mul_smul, hv, smul_comm] }
  have hne : W' ≠ ⊥ := by
    obtain ⟨v, hv, hv0⟩ := hα.exists_hasEigenvector
    intro hbot
    apply hv0
    have hmem : v ∈ W' := hv
    rw [hbot, Submodule.mem_bot] at hmem
    exact hmem
  have htop : W' = ⊤ := (eq_bot_or_eq_top W').resolve_left hne
  refine ⟨α, fun v => ?_⟩
  have hv_mem : v ∈ W' := by rw [htop]; exact Submodule.mem_top
  have hmem : v ∈ Module.End.eigenspace (smulEnd q V x) α := hv_mem
  rw [Module.End.mem_eigenspace_iff, smulEnd_apply] at hmem
  exact hmem

/-- **`e ^ orderOf q` acts as a scalar** on a finite dimensional simple module, given `q ≠ ±1`.
Unlike `K ^ orderOf q` this scalar may be zero (`e` can act nilpotently). -/
theorem epow_orderOf_isScalar (hq2 : (q : ℂ) ^ 2 ≠ 1)
    [FiniteDimensional ℂ V] [IsSimpleModule (Uqsl2 q) V] :
    ∃ α : ℂ, ∀ v : V, e q ^ orderOf q • v = α • v :=
  central_isScalar q V (e q ^ orderOf q) (epow_orderOf_central q hq2)

/-- **`f ^ orderOf q` acts as a scalar** on a finite dimensional simple module, given `q ≠ ±1`.
Mirror of `epow_orderOf_isScalar`; this scalar may likewise be zero. -/
theorem fpow_orderOf_isScalar (hq2 : (q : ℂ) ^ 2 ≠ 1)
    [FiniteDimensional ℂ V] [IsSimpleModule (Uqsl2 q) V] :
    ∃ α : ℂ, ∀ v : V, f q ^ orderOf q • v = α • v :=
  central_isScalar q V (f q ^ orderOf q) (fpow_orderOf_central q hq2)

end CentralScalar

/-! ## The `e`-ladder of a lowest weight vector

Mirror of the `f`-ladder (`ladder`) in the `e`-direction, used for the lowest weight case of the
dimension bound. Starting from a lowest weight vector `w` (`f • w = 0`), the vectors `eⁱ • w` form a
ladder on which `e` raises the `K`-eigenvalue by `q²`, `K`/`L` act diagonally, and `f` steps back
down. The infrastructure is symmetric to the `Ladder` section; the sign of the telescoping
coefficient (`fcoef`) is flipped because the commutator is applied as `fe = ef - (K-L)/(q-q⁻¹)`. -/

section LowerLadder

variable (q : ℂˣ)
variable (V : Type*) [AddCommGroup V] [Module ℂ V] [Module (Uqsl2 q) V]
  [IsScalarTower ℂ (Uqsl2 q) V]

/-- The `e`-ladder of `w`: `eladder q V w i = eⁱ • w`. -/
noncomputable def eladder (w : V) (i : ℕ) : V := (e q) ^ i • w

/-- The `K`-eigenvalue of the `i`-th `e`-ladder vector, given `K • w = lam • w`: `lam · q^{2i}`. -/
noncomputable def nu (lam : ℂ) (i : ℕ) : ℂ := lam * ((q : ℂ) ^ 2) ^ i

omit [Module ℂ V] [IsScalarTower ℂ (Uqsl2 q) V] in
/-- The zero case of `eladder`. -/
@[simp] lemma eladder_zero (w : V) : eladder q V w 0 = w := by simp [eladder]

omit [Module ℂ V] [IsScalarTower ℂ (Uqsl2 q) V] in
/-- The successor-step formula for `eladder`. -/
lemma eladder_succ (w : V) (i : ℕ) : eladder q V w (i + 1) = e q • eladder q V w i := by
  simp only [eladder, pow_succ', mul_smul]

/-- The zero case of `nu`. -/
@[simp] lemma nu_zero (lam : ℂ) : nu q lam 0 = lam := by simp [nu]

/-- The lowering coefficient is nonzero away from the bottom of the ladder. -/
lemma nu_ne_zero (lam : ℂ) (hlam : lam ≠ 0) (i : ℕ) : nu q lam i ≠ 0 := by
  apply mul_ne_zero hlam
  exact pow_ne_zero _ (pow_ne_zero _ q.ne_zero)

/-- `K` acts on the `i`-th `e`-ladder vector by `nu q lam i`. -/
lemma K_eladder (w : V) (lam : ℂ) (hKw : K q • w = lam • w) (i : ℕ) :
    K q • eladder q V w i = nu q lam i • eladder q V w i := by
  induction i with
  | zero => simpa [nu] using hKw
  | succ n ih =>
    rw [eladder_succ, ← mul_smul, Ke_rel, smul_assoc, mul_smul, ih,
      smul_comm (e q) (nu q lam n), smul_smul]
    congr 1
    simp only [nu, pow_succ]
    ring

/-- `L = K⁻¹` acts on the `i`-th `e`-ladder vector by `(nu q lam i)⁻¹`. -/
lemma L_eladder (w : V) (lam : ℂ) (hlam : lam ≠ 0) (hKw : K q • w = lam • w) (i : ℕ) :
    L q • eladder q V w i = (nu q lam i)⁻¹ • eladder q V w i := by
  have hK := K_eladder q V w lam hKw i
  have hnu := nu_ne_zero q lam hlam i
  have h1 : L q • (K q • eladder q V w i) = eladder q V w i := by
    rw [← mul_smul, LK_rel, one_smul]
  rw [hK, smul_comm (L q) (nu q lam i)] at h1
  have := congrArg (fun x => (nu q lam i)⁻¹ • x) h1
  simp only [smul_smul, inv_mul_cancel₀ hnu, one_smul] at this
  exact this

/-- The commutator action `f • (e • x) = e • (f • x) - (q - q⁻¹)⁻¹·(a - a⁻¹) • x` on a
`K`-eigenvector `x`. Rearrangement of `ef_action` via `fe = ef - (K - L)/(q - q⁻¹)`. -/
lemma fe_action (hne : (q : ℂ) - (q : ℂ)⁻¹ ≠ 0) (x : V) (a : ℂ)
    (hK : K q • x = a • x) (hL : L q • x = a⁻¹ • x) :
    f q • (e q • x) = e q • (f q • x) - (((q : ℂ) - (q : ℂ)⁻¹)⁻¹ * (a - a⁻¹)) • x := by
  have h := ef_action q V hne x a hK hL
  rw [h]
  abel

/-- The scalar coefficient `f • eⁱ⁺¹w = fcoef q lam i · eⁱw`, the negated telescoping sum of the
quantum brackets on the `e`-ladder (mirror of `dcoef`). -/
noncomputable def fcoef (lam : ℂ) (i : ℕ) : ℂ :=
  -∑ j ∈ Finset.range (i + 1), ((q : ℂ) - (q : ℂ)⁻¹)⁻¹ * (nu q lam j - (nu q lam j)⁻¹)

/-- The `f`-action on the `e`-ladder of a lowest weight vector:
`f • eⁱ⁺¹w = fcoef q lam i · eⁱw`. -/
lemma f_eladder (hne : (q : ℂ) - (q : ℂ)⁻¹ ≠ 0) (w : V) (lam : ℂ) (hlam : lam ≠ 0)
    (hf : f q • w = 0) (hKw : K q • w = lam • w) (i : ℕ) :
    f q • eladder q V w (i + 1) = fcoef q lam i • eladder q V w i := by
  induction i with
  | zero =>
    rw [eladder_succ,
      fe_action q V hne (eladder q V w 0) (nu q lam 0)
        (K_eladder q V w lam hKw 0) (L_eladder q V w lam hlam hKw 0)]
    have hfw : f q • eladder q V w 0 = 0 := by simpa using hf
    rw [hfw, smul_zero, zero_sub, fcoef, Finset.sum_range_one, neg_smul]
  | succ n ih =>
    rw [eladder_succ,
      fe_action q V hne (eladder q V w (n + 1)) (nu q lam (n + 1))
        (K_eladder q V w lam hKw (n + 1)) (L_eladder q V w lam hlam hKw (n + 1)),
      ih, smul_comm (e q) (fcoef q lam n), ← eladder_succ, ← sub_smul]
    congr 1
    have hstep : fcoef q lam (n + 1) = fcoef q lam n
        - ((q : ℂ) - (q : ℂ)⁻¹)⁻¹ * (nu q lam (n + 1) - (nu q lam (n + 1))⁻¹) := by
      simp only [fcoef, Finset.sum_range_succ]
      ring
    rw [hstep]

end LowerLadder

/-! ## The dimension bound at a root of unity

We now prove the De Concini–Kac dimension bound `dim V ≤ orderOf q` for a finite dimensional
simple `U_q(sl₂)`-module at a root of unity `q ≠ ±1`. The scalars `a`, `b` of the central elements
`e ^ orderOf q`, `f ^ orderOf q` (`epow_orderOf_isScalar`, `fpow_orderOf_isScalar`) split the
argument into cases. The first case, `a = 0` (so `e` acts nilpotently), is the highest weight
case: it is handled here by the closed `f`-ladder of a highest weight vector, whose length is at
most `orderOf q` because `f ^ orderOf q` acts as the scalar `b`, closing the ladder up after
`orderOf q` steps. -/

/-- **Highest weight case of the dimension bound.** If `e ^ orderOf q` acts as `0` on a finite
dimensional simple `U_q(sl₂)`-module `V` (so `e` is nilpotent), then `dim V ≤ orderOf q`.

Walking up with `e` from any `K`-eigenvector produces a highest weight vector `v` (`e • v = 0`,
`K • v = λ v` with `λ ≠ 0`). Its `f`-ladder `v, f v, …, f^{ℓ-1} v` (with `ℓ = orderOf q`) spans a
subspace `W` that is `f`-invariant (`f^ℓ v = b v` folds the top back onto `v`), `K`- and
`L`-invariant (`K_ladder`/`L_ladder`), and `e`-invariant (`e_ladder`, using `e • v = 0`). So `W` is
a nonzero `U_q`-submodule, hence all of `V` by simplicity, and `dim V = dim W ≤ ℓ`. -/
theorem finrank_le_of_epow_orderOf_eq_zero (q : ℂˣ) (hq : IsOfFinOrder q) (hq2 : (q : ℂ) ^ 2 ≠ 1)
    (V : Type*) [AddCommGroup V] [Module ℂ V] [Module (Uqsl2 q) V]
    [IsScalarTower ℂ (Uqsl2 q) V] [FiniteDimensional ℂ V] [IsSimpleModule (Uqsl2 q) V]
    (he0 : ∀ w : V, e q ^ orderOf q • w = 0) :
    Module.finrank ℂ V ≤ orderOf q := by
  haveI : Nontrivial V := IsSimpleModule.nontrivial (Uqsl2 q) V
  have hℓpos : 0 < orderOf q := hq.orderOf_pos
  have hqinv : (q : ℂ) - (q : ℂ)⁻¹ ≠ 0 := q_sub_inv_ne_of_sq_ne q hq2
  classical
  -- Highest weight vector: walk up with `e` from a `K`-eigenvector until annihilated.
  have key : ∃ (v : V) (lam : ℂ),
      v ≠ 0 ∧ e q • v = 0 ∧ K q • v = lam • v ∧ lam ≠ 0 := by
    obtain ⟨μ₀, hμ₀⟩ := Module.End.exists_eigenvalue (Kop q V)
    obtain ⟨w₀, hw₀mem, hw₀0⟩ := hμ₀.exists_hasEigenvector
    have hμ₀0 : μ₀ ≠ 0 := eigenvalue_ne_zero q V μ₀ hμ₀
    have hKw₀ : Kop q V w₀ = μ₀ • w₀ := Module.End.mem_eigenspace_iff.mp hw₀mem
    -- `e^j w₀` is a `K`-eigenvector with eigenvalue `(q²)^j μ₀`.
    have hchain : ∀ j : ℕ,
        Kop q V (e q ^ j • w₀) = (((q : ℂ) ^ 2) ^ j * μ₀) • (e q ^ j • w₀) := by
      intro j
      induction j with
      | zero => simpa using hKw₀
      | succ n ih =>
        have hsplit : e q ^ (n + 1) • w₀ = e q • (e q ^ n • w₀) := by rw [pow_succ', mul_smul]
        rw [hsplit, e_eigenvalue_shift q V _ _ ih]
        congr 1
        ring
    have hex : ∃ k, e q ^ k • w₀ = 0 := ⟨orderOf q, he0 w₀⟩
    have hk0 : Nat.find hex ≠ 0 := by
      intro h
      have hs := Nat.find_spec hex
      rw [h, pow_zero, one_smul] at hs
      exact hw₀0 hs
    obtain ⟨m, hm⟩ : ∃ m, Nat.find hex = m + 1 := ⟨Nat.find hex - 1, by omega⟩
    refine ⟨e q ^ m • w₀, ((q : ℂ) ^ 2) ^ m * μ₀, Nat.find_min hex (by omega), ?_, ?_, ?_⟩
    · have hs := Nat.find_spec hex
      rw [hm] at hs
      rw [← mul_smul, ← pow_succ']
      exact hs
    · have h := hchain m
      rw [Kop_apply] at h
      exact h
    · exact mul_ne_zero (pow_ne_zero _ (pow_ne_zero _ q.ne_zero)) hμ₀0
  obtain ⟨v, lam, hv0, he, hKv, hlam⟩ := key
  -- The scalar of `f ^ orderOf q` (may be zero) closes the ladder up after `orderOf q` steps.
  obtain ⟨fb, hfb⟩ := fpow_orderOf_isScalar q V hq2
  have hladder_ℓ : ladder q V v (orderOf q) = fb • v := hfb v
  -- Finite spanning family `b i = fⁱ v`, `i < orderOf q`, and its `ℂ`-span `W`.
  set b : Fin (orderOf q) → V := fun i => ladder q V v ↑i with hb
  set W : Submodule ℂ V := Submodule.span ℂ (Set.range b) with hW
  have hb_mem : ∀ (n : ℕ), n < orderOf q → ladder q V v n ∈ W :=
    fun n hn => Submodule.subset_span (Set.mem_range.mpr ⟨⟨n, hn⟩, rfl⟩)
  have hvW : v ∈ W := by
    have h0 := hb_mem 0 hℓpos
    rwa [ladder_zero] at h0
  -- Generator closures on the spanning family.
  have heW : ∀ i : Fin (orderOf q), e q • b i ∈ W := by
    intro i
    change e q • ladder q V v ↑i ∈ W
    rcases Nat.eq_zero_or_pos (↑i : ℕ) with hi0 | hipos
    · rw [hi0, ladder_zero, he]; exact W.zero_mem
    · obtain ⟨j, hj⟩ : ∃ j, (↑i : ℕ) = j + 1 := ⟨↑i - 1, by omega⟩
      have hi := i.isLt
      rw [hj, e_ladder q V hqinv v lam hlam he hKv j]
      exact W.smul_mem _ (hb_mem j (by omega))
  have hfW : ∀ i : Fin (orderOf q), f q • b i ∈ W := by
    intro i
    change f q • ladder q V v ↑i ∈ W
    rw [← ladder_succ q V v ↑i]
    rcases eq_or_lt_of_le (show (↑i : ℕ) + 1 ≤ orderOf q from i.isLt) with heq | hlt
    · rw [heq, hladder_ℓ]; exact W.smul_mem _ hvW
    · exact hb_mem (↑i + 1) hlt
  have hKW : ∀ i : Fin (orderOf q), K q • b i ∈ W := by
    intro i
    change K q • ladder q V v ↑i ∈ W
    rw [K_ladder q V v lam hKv ↑i]
    exact W.smul_mem _ (hb_mem ↑i i.isLt)
  have hLW : ∀ i : Fin (orderOf q), L q • b i ∈ W := by
    intro i
    change L q • ladder q V v ↑i ∈ W
    rw [L_ladder q V v lam hlam hKv ↑i]
    exact W.smul_mem _ (hb_mem ↑i i.isLt)
  have clOf : ∀ (a : Uqsl2 q), (∀ i : Fin (orderOf q), a • b i ∈ W) → ∀ x ∈ W, a • x ∈ W := by
    intro a ha x hx
    induction hx using Submodule.span_induction with
    | mem z hz => obtain ⟨i, rfl⟩ := hz; exact ha i
    | zero => rw [smul_zero]; exact W.zero_mem
    | add p r _ _ hp hr => rw [smul_add]; exact W.add_mem hp hr
    | smul c p _ hp => rw [smul_comm]; exact W.smul_mem c hp
  -- `W` is a `U_q`-submodule; by simplicity it is everything.
  let W' : Submodule (Uqsl2 q) V :=
    { carrier := (W : Set V)
      add_mem' := fun ha hb => W.add_mem ha hb
      zero_mem' := W.zero_mem
      smul_mem' := fun a x hx => smul_mem_of_generators q V W (clOf (e q) heW)
        (clOf (f q) hfW) (clOf (K q) hKW) (clOf (L q) hLW) a x hx }
  have hvW' : v ∈ W' := hvW
  have hne' : W' ≠ ⊥ := by
    intro hbot
    apply hv0
    have hmem : v ∈ (⊥ : Submodule (Uqsl2 q) V) := hbot ▸ hvW'
    exact (Submodule.mem_bot (Uqsl2 q)).mp hmem
  have hW'top : W' = ⊤ := (eq_bot_or_eq_top W').resolve_left hne'
  have hWtop : W = ⊤ := by
    rw [eq_top_iff]
    intro x _
    have hxW' : x ∈ W' := by rw [hW'top]; exact Submodule.mem_top
    exact hxW'
  -- Dimension count: `W` is spanned by `orderOf q` vectors.
  have hspan : Module.finrank ℂ (Submodule.span ℂ (Set.range b)) ≤ orderOf q := by
    have hcard := finrank_range_le_card (R := ℂ) b
    rwa [Set.finrank, Fintype.card_fin] at hcard
  rw [← hW, hWtop, finrank_top] at hspan
  exact hspan

/-- **Lowest weight case of the dimension bound.** If `f ^ orderOf q` acts as `0` on a finite
dimensional simple `U_q(sl₂)`-module `V` (so `f` is nilpotent), then `dim V ≤ orderOf q`. This is
the mirror of `finrank_le_of_epow_orderOf_eq_zero`: a lowest weight vector `w` (`f • w = 0`,
`K • w = λ w`) has a closed `e`-ladder `w, e w, …, e^{ℓ-1} w` spanning `V`.

To fill this, mirror the highest-weight construction in the `e`-direction: prove `fe_action`
(from the same relation `ef_rel`, giving `f • (e • x) = e • (f • x) - (…)•x`) and the resulting
`f`-action on the `e`-ladder, then run the same submodule/dimension argument with `e` raising the
`K`-eigenvalue by `q²`. -/
theorem finrank_le_of_fpow_orderOf_eq_zero (q : ℂˣ) (hq : IsOfFinOrder q) (hq2 : (q : ℂ) ^ 2 ≠ 1)
    (V : Type*) [AddCommGroup V] [Module ℂ V] [Module (Uqsl2 q) V]
    [IsScalarTower ℂ (Uqsl2 q) V] [FiniteDimensional ℂ V] [IsSimpleModule (Uqsl2 q) V]
    (hf0 : ∀ w : V, f q ^ orderOf q • w = 0) :
    Module.finrank ℂ V ≤ orderOf q := by
  haveI : Nontrivial V := IsSimpleModule.nontrivial (Uqsl2 q) V
  have hℓpos : 0 < orderOf q := hq.orderOf_pos
  have hqinv : (q : ℂ) - (q : ℂ)⁻¹ ≠ 0 := q_sub_inv_ne_of_sq_ne q hq2
  classical
  -- Lowest weight vector: walk down with `f` from a `K`-eigenvector until annihilated.
  have key : ∃ (w : V) (lam : ℂ),
      w ≠ 0 ∧ f q • w = 0 ∧ K q • w = lam • w ∧ lam ≠ 0 := by
    obtain ⟨μ₀, hμ₀⟩ := Module.End.exists_eigenvalue (Kop q V)
    obtain ⟨w₀, hw₀mem, hw₀0⟩ := hμ₀.exists_hasEigenvector
    have hμ₀0 : μ₀ ≠ 0 := eigenvalue_ne_zero q V μ₀ hμ₀
    have hKw₀ : Kop q V w₀ = μ₀ • w₀ := Module.End.mem_eigenspace_iff.mp hw₀mem
    -- `f^j w₀` is a `K`-eigenvector with eigenvalue `(q²)⁻ʲ μ₀`.
    have hchain : ∀ j : ℕ,
        Kop q V (f q ^ j • w₀) = ((((q : ℂ) ^ 2)⁻¹) ^ j * μ₀) • (f q ^ j • w₀) := by
      intro j
      induction j with
      | zero => simpa using hKw₀
      | succ n ih =>
        have hsplit : f q ^ (n + 1) • w₀ = f q • (f q ^ n • w₀) := by rw [pow_succ', mul_smul]
        rw [hsplit, f_eigenvalue_shift q V _ _ ih]
        congr 1
        rw [pow_succ]
        ring
    have hex : ∃ k, f q ^ k • w₀ = 0 := ⟨orderOf q, hf0 w₀⟩
    have hk0 : Nat.find hex ≠ 0 := by
      intro h
      have hs := Nat.find_spec hex
      rw [h, pow_zero, one_smul] at hs
      exact hw₀0 hs
    obtain ⟨m, hm⟩ : ∃ m, Nat.find hex = m + 1 := ⟨Nat.find hex - 1, by omega⟩
    refine ⟨f q ^ m • w₀, (((q : ℂ) ^ 2)⁻¹) ^ m * μ₀, Nat.find_min hex (by omega), ?_, ?_, ?_⟩
    · have hs := Nat.find_spec hex
      rw [hm] at hs
      rw [← mul_smul, ← pow_succ']
      exact hs
    · have h := hchain m
      rw [Kop_apply] at h
      exact h
    · exact mul_ne_zero (pow_ne_zero _ (inv_ne_zero (pow_ne_zero _ q.ne_zero))) hμ₀0
  obtain ⟨w, lam, hw0, hf, hKw, hlam⟩ := key
  -- The scalar of `e ^ orderOf q` closes the `e`-ladder up after `orderOf q` steps.
  obtain ⟨ea, hea⟩ := epow_orderOf_isScalar q V hq2
  have heladder_ℓ : eladder q V w (orderOf q) = ea • w := hea w
  -- Finite spanning family `b i = eⁱ w`, `i < orderOf q`, and its `ℂ`-span `W`.
  set b : Fin (orderOf q) → V := fun i => eladder q V w ↑i with hb
  set W : Submodule ℂ V := Submodule.span ℂ (Set.range b) with hW
  have hb_mem : ∀ (n : ℕ), n < orderOf q → eladder q V w n ∈ W :=
    fun n hn => Submodule.subset_span (Set.mem_range.mpr ⟨⟨n, hn⟩, rfl⟩)
  have hwW : w ∈ W := by
    have h0 := hb_mem 0 hℓpos
    rwa [eladder_zero] at h0
  -- Generator closures on the spanning family.
  have hfW : ∀ i : Fin (orderOf q), f q • b i ∈ W := by
    intro i
    change f q • eladder q V w ↑i ∈ W
    rcases Nat.eq_zero_or_pos (↑i : ℕ) with hi0 | hipos
    · rw [hi0, eladder_zero, hf]; exact W.zero_mem
    · obtain ⟨j, hj⟩ : ∃ j, (↑i : ℕ) = j + 1 := ⟨↑i - 1, by omega⟩
      have hi := i.isLt
      rw [hj, f_eladder q V hqinv w lam hlam hf hKw j]
      exact W.smul_mem _ (hb_mem j (by omega))
  have heW : ∀ i : Fin (orderOf q), e q • b i ∈ W := by
    intro i
    change e q • eladder q V w ↑i ∈ W
    rw [← eladder_succ q V w ↑i]
    rcases eq_or_lt_of_le (show (↑i : ℕ) + 1 ≤ orderOf q from i.isLt) with heq | hlt
    · rw [heq, heladder_ℓ]; exact W.smul_mem _ hwW
    · exact hb_mem (↑i + 1) hlt
  have hKW : ∀ i : Fin (orderOf q), K q • b i ∈ W := by
    intro i
    change K q • eladder q V w ↑i ∈ W
    rw [K_eladder q V w lam hKw ↑i]
    exact W.smul_mem _ (hb_mem ↑i i.isLt)
  have hLW : ∀ i : Fin (orderOf q), L q • b i ∈ W := by
    intro i
    change L q • eladder q V w ↑i ∈ W
    rw [L_eladder q V w lam hlam hKw ↑i]
    exact W.smul_mem _ (hb_mem ↑i i.isLt)
  have clOf : ∀ (a : Uqsl2 q), (∀ i : Fin (orderOf q), a • b i ∈ W) → ∀ x ∈ W, a • x ∈ W := by
    intro a ha x hx
    induction hx using Submodule.span_induction with
    | mem z hz => obtain ⟨i, rfl⟩ := hz; exact ha i
    | zero => rw [smul_zero]; exact W.zero_mem
    | add p r _ _ hp hr => rw [smul_add]; exact W.add_mem hp hr
    | smul c p _ hp => rw [smul_comm]; exact W.smul_mem c hp
  -- `W` is a `U_q`-submodule; by simplicity it is everything.
  let W' : Submodule (Uqsl2 q) V :=
    { carrier := (W : Set V)
      add_mem' := fun ha hb => W.add_mem ha hb
      zero_mem' := W.zero_mem
      smul_mem' := fun a x hx => smul_mem_of_generators q V W (clOf (e q) heW)
        (clOf (f q) hfW) (clOf (K q) hKW) (clOf (L q) hLW) a x hx }
  have hwW' : w ∈ W' := hwW
  have hne' : W' ≠ ⊥ := by
    intro hbot
    apply hw0
    have hmem : w ∈ (⊥ : Submodule (Uqsl2 q) V) := hbot ▸ hwW'
    exact (Submodule.mem_bot (Uqsl2 q)).mp hmem
  have hW'top : W' = ⊤ := (eq_bot_or_eq_top W').resolve_left hne'
  have hWtop : W = ⊤ := by
    rw [eq_top_iff]
    intro x _
    have hxW' : x ∈ W' := by rw [hW'top]; exact Submodule.mem_top
    exact hxW'
  -- Dimension count: `W` is spanned by `orderOf q` vectors.
  have hspan : Module.finrank ℂ (Submodule.span ℂ (Set.range b)) ≤ orderOf q := by
    have hcard := finrank_range_le_card (R := ℂ) b
    rwa [Set.finrank, Fintype.card_fin] at hcard
  rw [← hW, hWtop, finrank_top] at hspan
  exact hspan

/-- **Cyclic (De Concini–Kac) case of the dimension bound.** If both `e ^ orderOf q` and
`f ^ orderOf q` act as nonzero scalars `a`, `b` (so `e` and `f` are both bijective), then
`dim V ≤ orderOf q`. This is the hard case: `V = ⨁_{j} E_j` over a single `q²`-orbit of
`K`-eigenvalues with `e : E_j ≅ E_{j+1}`, `f : E_j ≅ E_{j-1}`, so all `E_j` share a common
dimension `d` and `dim V = s · d` with `s = ord(q²)`; bounding `d ≤ orderOf q / s` (via `e^s`, `f^s`
on a single eigenspace) is the substantial step. -/
theorem finrank_le_of_cyclic (q : ℂˣ) (hq : IsOfFinOrder q) (hq2 : (q : ℂ) ^ 2 ≠ 1)
    (V : Type*) [AddCommGroup V] [Module ℂ V] [Module (Uqsl2 q) V]
    [IsScalarTower ℂ (Uqsl2 q) V] [FiniteDimensional ℂ V] [IsSimpleModule (Uqsl2 q) V]
    (a : ℂ) (_ha : ∀ v : V, e q ^ orderOf q • v = a • v) (_ha0 : a ≠ 0)
    (b : ℂ) (hb : ∀ v : V, f q ^ orderOf q • v = b • v) (hb0 : b ≠ 0) :
    Module.finrank ℂ V ≤ orderOf q := by
  haveI : Nontrivial V := IsSimpleModule.nontrivial (Uqsl2 q) V
  have hℓpos : 0 < orderOf q := hq.orderOf_pos
  have hqinv : (q : ℂ) - (q : ℂ)⁻¹ ≠ 0 := q_sub_inv_ne_of_sq_ne q hq2
  classical
  -- Pick a `K`-eigenvalue `μ₀ ≠ 0`.
  obtain ⟨μ₀, hμ₀⟩ := Module.End.exists_eigenvalue (Kop q V)
  have hμ₀0 : μ₀ ≠ 0 := eigenvalue_ne_zero q V μ₀ hμ₀
  -- `f ∘ e` maps the `μ₀`-eigenspace into itself: `e` raises the eigenvalue by `q²`,
  -- and `f` lowers it again.
  have hmaps : ∀ w ∈ Module.End.eigenspace (Kop q V) μ₀,
      smulEnd q V (f q * e q) w ∈ Module.End.eigenspace (Kop q V) μ₀ := by
    intro w hw
    rw [Module.End.mem_eigenspace_iff] at hw
    have hqz : (q : ℂ) ^ 2 ≠ 0 := pow_ne_zero 2 q.ne_zero
    have hew : Kop q V (e q • w) = ((q : ℂ) ^ 2 * μ₀) • (e q • w) :=
      e_eigenvalue_shift q V μ₀ w hw
    have hfew : Kop q V (f q • (e q • w))
        = (((q : ℂ) ^ 2)⁻¹ * ((q : ℂ) ^ 2 * μ₀)) • (f q • (e q • w)) :=
      f_eigenvalue_shift q V ((q : ℂ) ^ 2 * μ₀) (e q • w) hew
    rw [smulEnd_apply, Module.End.mem_eigenspace_iff, mul_smul, hfew,
      inv_mul_cancel_left₀ hqz]
  -- The `μ₀`-eigenspace is nonzero, so `f ∘ e` restricted to it has an eigenvector over `ℂ`.
  haveI : Nontrivial (Module.End.eigenspace (Kop q V) μ₀) := by
    obtain ⟨w₀, hw₀mem, hw₀0⟩ := hμ₀.exists_hasEigenvector
    exact ⟨⟨⟨w₀, hw₀mem⟩, 0, fun h => hw₀0 (congrArg Subtype.val h)⟩⟩
  obtain ⟨ρ, v, hv0, hKv, hfe⟩ : ∃ (ρ : ℂ) (v : V),
      v ≠ 0 ∧ K q • v = μ₀ • v ∧ f q • (e q • v) = ρ • v := by
    obtain ⟨ρ, hρ⟩ :=
      Module.End.exists_eigenvalue ((smulEnd q V (f q * e q)).restrict hmaps)
    obtain ⟨v', hv'mem, hv'0⟩ := hρ.exists_hasEigenvector
    refine ⟨ρ, (v' : V), ?_, ?_, ?_⟩
    · simp only [ne_eq, Submodule.coe_eq_zero]; exact hv'0
    · have h := Module.End.mem_eigenspace_iff.mp v'.2
      rwa [Kop_apply] at h
    · have hTv := Module.End.mem_eigenspace_iff.mp hv'mem
      have hcoe := congrArg (Subtype.val) hTv
      simpa only [LinearMap.coe_restrict_apply, smulEnd_apply, Submodule.coe_smul,
        mul_smul] using hcoe
  -- `e • v` lands in the `f`-ladder: from `f • (e • v) = ρ • v` and `f^ℓ • (e•v) = b • (e•v)`.
  obtain ⟨m, hm⟩ : ∃ m, orderOf q = m + 1 := ⟨orderOf q - 1, by omega⟩
  have hev : e q • v = (b⁻¹ * ρ) • ladder q V v m := by
    have h1 : f q ^ m • (f q • (e q • v)) = f q ^ m • (ρ • v) := by rw [hfe]
    rw [← mul_smul, ← pow_succ, ← hm, hb (e q • v), smul_comm (f q ^ m) ρ v] at h1
    have h2 := congrArg (fun x : V => (b⁻¹ : ℂ) • x) h1
    simp only [smul_smul, inv_mul_cancel₀ hb0, one_smul] at h2
    exact h2
  -- Finite spanning family `bv i = fⁱ v`, `i < orderOf q`, and its `ℂ`-span `W`.
  set bv : Fin (orderOf q) → V := fun i => ladder q V v ↑i with hbv
  set W : Submodule ℂ V := Submodule.span ℂ (Set.range bv) with hW
  have hb_mem : ∀ (n : ℕ), n < orderOf q → ladder q V v n ∈ W :=
    fun n hn => Submodule.subset_span (Set.mem_range.mpr ⟨⟨n, hn⟩, rfl⟩)
  have hvW : v ∈ W := by
    have h0 := hb_mem 0 hℓpos
    rwa [ladder_zero] at h0
  have hladder_ℓ : ladder q V v (orderOf q) = b • v := hb v
  -- `f`-closure on the spanning family (the ladder closes up after `orderOf q` steps).
  have hfW : ∀ i : Fin (orderOf q), f q • bv i ∈ W := by
    intro i
    change f q • ladder q V v ↑i ∈ W
    rw [← ladder_succ q V v ↑i]
    rcases eq_or_lt_of_le (show (↑i : ℕ) + 1 ≤ orderOf q from i.isLt) with heq | hlt
    · rw [heq, hladder_ℓ]; exact W.smul_mem _ hvW
    · exact hb_mem (↑i + 1) hlt
  have clOf : ∀ (a : Uqsl2 q), (∀ i : Fin (orderOf q), a • bv i ∈ W) → ∀ x ∈ W, a • x ∈ W := by
    intro a ha x hx
    induction hx using Submodule.span_induction with
    | mem z hz => obtain ⟨i, rfl⟩ := hz; exact ha i
    | zero => rw [smul_zero]; exact W.zero_mem
    | add p r _ _ hp hr => rw [smul_add]; exact W.add_mem hp hr
    | smul c p _ hp => rw [smul_comm]; exact W.smul_mem c hp
  have hfWall : ∀ x ∈ W, f q • x ∈ W := clOf (f q) hfW
  -- Every `fⁿ v` lies in `W` (`W` is `f`-closed and contains `v`).
  have hladder_all : ∀ n, ladder q V v n ∈ W := by
    intro n
    induction n with
    | zero => rw [ladder_zero]; exact hvW
    | succ k ih => rw [ladder_succ]; exact hfWall _ ih
  have hevW : e q • v ∈ W := by rw [hev]; exact W.smul_mem _ (hladder_all m)
  -- `e`-closure on the whole ladder, by induction from `e • v ∈ W` using the `ef` recursion.
  have heW_all : ∀ n, e q • ladder q V v n ∈ W := by
    intro n
    induction n with
    | zero => rw [ladder_zero]; exact hevW
    | succ k ih =>
      have hrec : e q • ladder q V v (k + 1)
          = f q • (e q • ladder q V v k)
            + (((q : ℂ) - (q : ℂ)⁻¹)⁻¹ * (mu q μ₀ k - (mu q μ₀ k)⁻¹)) • ladder q V v k := by
        rw [ladder_succ]
        exact ef_action q V hqinv (ladder q V v k) (mu q μ₀ k)
          (K_ladder q V v μ₀ hKv k) (L_ladder q V v μ₀ hμ₀0 hKv k)
      rw [hrec]
      exact W.add_mem (hfWall _ ih) (W.smul_mem _ (hladder_all k))
  have heW : ∀ i : Fin (orderOf q), e q • bv i ∈ W := fun i => heW_all ↑i
  have hKW : ∀ i : Fin (orderOf q), K q • bv i ∈ W := by
    intro i
    change K q • ladder q V v ↑i ∈ W
    rw [K_ladder q V v μ₀ hKv ↑i]
    exact W.smul_mem _ (hb_mem ↑i i.isLt)
  have hLW : ∀ i : Fin (orderOf q), L q • bv i ∈ W := by
    intro i
    change L q • ladder q V v ↑i ∈ W
    rw [L_ladder q V v μ₀ hμ₀0 hKv ↑i]
    exact W.smul_mem _ (hb_mem ↑i i.isLt)
  -- `W` is a `U_q`-submodule; by simplicity it is everything.
  let W' : Submodule (Uqsl2 q) V :=
    { carrier := (W : Set V)
      add_mem' := fun ha hb => W.add_mem ha hb
      zero_mem' := W.zero_mem
      smul_mem' := fun a x hx => smul_mem_of_generators q V W (clOf (e q) heW)
        (clOf (f q) hfW) (clOf (K q) hKW) (clOf (L q) hLW) a x hx }
  have hvW' : v ∈ W' := hvW
  have hne' : W' ≠ ⊥ := by
    intro hbot
    apply hv0
    have hmem : v ∈ (⊥ : Submodule (Uqsl2 q) V) := hbot ▸ hvW'
    exact (Submodule.mem_bot (Uqsl2 q)).mp hmem
  have hW'top : W' = ⊤ := (eq_bot_or_eq_top W').resolve_left hne'
  have hWtop : W = ⊤ := by
    rw [eq_top_iff]
    intro x _
    have hxW' : x ∈ W' := by rw [hW'top]; exact Submodule.mem_top
    exact hxW'
  -- Dimension count: `W` is spanned by `orderOf q` vectors.
  have hspan : Module.finrank ℂ (Submodule.span ℂ (Set.range bv)) ≤ orderOf q := by
    have hcard := finrank_range_le_card (R := ℂ) bv
    rwa [Set.finrank, Fintype.card_fin] at hcard
  rw [← hW, hWtop, finrank_top] at hspan
  exact hspan

/-- **Root-of-unity case.** When `q` is a root of unity with `q ≠ ±1` (equivalently `q² ≠ 1`), the
dimensions of the finite dimensional irreducible representations are bounded (by `orderOf q`): they
no longer occur in every dimension, in contrast to the non-root-of-unity case.

The hypothesis `q² ≠ 1` is necessary: at `q = ±1` the relation `(q - q⁻¹)(ef - fe) = K - L`
degenerates and arbitrarily large simple modules exist. The proof splits on the central scalars
`a = e^{orderOf q}`, `b = f^{orderOf q}`: `a = 0` is the highest weight case
(`finrank_le_of_epow_orderOf_eq_zero`), `b = 0` the lowest weight case
(`finrank_le_of_fpow_orderOf_eq_zero`), and `a, b ≠ 0` the cyclic case (`finrank_le_of_cyclic`). -/
theorem finrank_irreducible_le_of_isOfFinOrder (q : ℂˣ) (hq : IsOfFinOrder q)
    (hq2 : (q : ℂ) ^ 2 ≠ 1)
    (V : Type*) [AddCommGroup V] [Module ℂ V] [Module (Uqsl2 q) V]
    [IsScalarTower ℂ (Uqsl2 q) V] [FiniteDimensional ℂ V] [IsSimpleModule (Uqsl2 q) V] :
    Module.finrank ℂ V ≤ orderOf q := by
  obtain ⟨a, ha⟩ := epow_orderOf_isScalar q V hq2
  by_cases ha0 : a = 0
  · exact finrank_le_of_epow_orderOf_eq_zero q hq hq2 V
      (fun w => by rw [ha w, ha0, zero_smul])
  · obtain ⟨b, hb⟩ := fpow_orderOf_isScalar q V hq2
    by_cases hb0 : b = 0
    · exact finrank_le_of_fpow_orderOf_eq_zero q hq hq2 V
        (fun w => by rw [hb w, hb0, zero_smul])
    · exact finrank_le_of_cyclic q hq hq2 V a ha ha0 b hb hb0

end Etingof.Problem2_16_5

-- The source-numbered exercise namespace and established API contain intentional underscores.
attribute [nolint defsWithUnderscore]
  Etingof.Problem2_16_5.Gen
  Etingof.Problem2_16_5.fe
  Etingof.Problem2_16_5.ff
  Etingof.Problem2_16_5.fK
  Etingof.Problem2_16_5.fL
  Etingof.Problem2_16_5.Uqsl2
  Etingof.Problem2_16_5.mk
  Etingof.Problem2_16_5.e
  Etingof.Problem2_16_5.f
  Etingof.Problem2_16_5.K
  Etingof.Problem2_16_5.L
  Etingof.Problem2_16_5.augmentation
  Etingof.Problem2_16_5.Kop
  Etingof.Problem2_16_5.ladder
  Etingof.Problem2_16_5.mu
  Etingof.Problem2_16_5.dcoef
  Etingof.Problem2_16_5.smulEnd
  Etingof.Problem2_16_5.eladder
  Etingof.Problem2_16_5.nu
  Etingof.Problem2_16_5.fcoef
