import Mathlib.Algebra.Algebra.Subalgebra.Lattice
import Mathlib.LinearAlgebra.Finsupp.LinearCombination
import EtingofRepresentationTheory.Chapter2.Definition2_8_4

/-!
# Problem 2.8.6: Presentation of the path algebra by generators and relations

For a finite quiver `Q` with vertex set `I` and arrow set `E`, the book-facing path algebra `P_Q`
(`Etingof.BookPathAlgebra k Q`) is generated by the trivial paths `pᵢ` (`i ∈ I`) and the arrows
`aₕ` (`h ∈ E`), subject to the defining relations

1. `∑_{i ∈ I} pᵢ = 1`,
2. `pᵢ² = pᵢ` and `pᵢ pⱼ = 0` for `i ≠ j`,
3. `aₕ p_{h'} = aₕ` and `aₕ pⱼ = 0` for `j ≠ h'` (where `h'` is the source of `h`),
4. `p_{h''} aₕ = aₕ` and `pᵢ aₕ = 0` for `i ≠ h''` (where `h''` is the target of `h`).

`PathAlgebra` is retained as the established source-to-target implementation used by later
chapters. Its opposite `BookPathAlgebra` is the exact public model of Definition 2.8.4. This file
keeps the implementation-convention API for compatibility and, in the `Book` namespace, states
and proves the printed relations literally: `aₕ p_{h'} = aₕ` and `p_{h''} aₕ = aₕ`.

We render the generators, the generation property, the four relations, and the universal
property (that these are defining relations) as the statements.
-/

namespace Etingof.Problem2_8_6

open Etingof

variable (k : Type*) (Q : Type*) [Field k] [Quiver Q] [DecidableEq Q]

/-- The trivial-path idempotent `pᵢ` at a vertex `i`: the length-`0` path at `i`. -/
noncomputable def vertexIdem (i : Q) : PathAlgebra k Q :=
  PathAlgebra.ofPath (k := k) ⟨i, i, Quiver.Path.nil⟩

/-- The arrow generator `aₕ` for an arrow `h : i ⟶ j`: the length-`1` path from `i` to `j`. -/
noncomputable def arrowGen {i j : Q} (e : i ⟶ j) : PathAlgebra k Q :=
  PathAlgebra.ofPath (k := k) ⟨i, j, e.toPath⟩

/-- A path obtained by appending an arrow `e` to the end of a path `q` factors, in the path
algebra, as the product of the basis path `q` with the arrow generator `aₑ`. -/
theorem ofPath_cons {a b c : Q} (q : Quiver.Path a b) (e : b ⟶ c) :
    PathAlgebra.ofPath (k := k) (⟨a, c, q.cons e⟩ : QuiverPathIndex Q)
      = PathAlgebra.ofPath (k := k) (⟨a, b, q⟩ : QuiverPathIndex Q) * arrowGen k Q e := by
  unfold arrowGen PathAlgebra.ofPath
  rw [PathAlgebra.single_mul_single, one_mul, one_smul, PathAlgebra.compSingle_eq,
    Quiver.Path.comp_toPath_eq_cons]

/-! ## Generation -/

/-- The path algebra is generated as a `k`-algebra by the vertex idempotents `pᵢ` and the
arrow generators `aₕ`. -/
theorem adjoin_generators_eq_top [Fintype Q] :
    Algebra.adjoin k
      ({ x : PathAlgebra k Q | ∃ i, x = vertexIdem k Q i } ∪
        { x : PathAlgebra k Q | ∃ (i j : Q) (e : i ⟶ j), x = arrowGen k Q e }) = ⊤ := by
  have hgen : ∀ (a b : Q) (p : Quiver.Path a b),
      PathAlgebra.ofPath (k := k) (⟨a, b, p⟩ : QuiverPathIndex Q) ∈
        Algebra.adjoin k
          ({ x : PathAlgebra k Q | ∃ i, x = vertexIdem k Q i } ∪
            { x : PathAlgebra k Q | ∃ (i j : Q) (e : i ⟶ j), x = arrowGen k Q e }) := by
    intro a b p
    induction p with
    | nil => exact Algebra.subset_adjoin (Or.inl ⟨a, rfl⟩)
    | cons q e ih =>
      rw [ofPath_cons]
      exact mul_mem ih (Algebra.subset_adjoin (Or.inr ⟨_, _, e, rfl⟩))
  rw [Algebra.eq_top_iff]
  intro f
  induction f using PathAlgebra.induction_linear with
  | zero => exact zero_mem _
  | add f g hf hg => exact add_mem hf hg
  | single x c =>
    obtain ⟨a, b, p⟩ := x
    have hsc : (Finsupp.single (⟨a, b, p⟩ : QuiverPathIndex Q) c : PathAlgebra k Q)
        = c • PathAlgebra.ofPath (k := k) (⟨a, b, p⟩ : QuiverPathIndex Q) := by
      exact (PathAlgebra.smul_single_one c _).symm
    rw [hsc]
    exact Subalgebra.smul_mem _ (hgen a b p) c

/-! ## The defining relations -/

/-- Relation (1): the vertex idempotents sum to `1`. -/
theorem sum_vertexIdem [Fintype Q] :
    ∑ i, vertexIdem k Q i = 1 := by
  simp only [vertexIdem]
  exact PathAlgebra.sum_trivialPaths_eq_one k Q

/-- Relation (2): each `pᵢ` is idempotent. -/
theorem vertexIdem_sq [Fintype Q] (i : Q) :
    vertexIdem k Q i * vertexIdem k Q i = vertexIdem k Q i := by
  unfold vertexIdem PathAlgebra.ofPath
  rw [PathAlgebra.single_mul_single, PathAlgebra.compSingle_nil_left, if_pos rfl, mul_one,
    one_smul]

/-- Relation (2): distinct vertex idempotents are orthogonal. -/
theorem vertexIdem_mul_of_ne [Fintype Q] (i j : Q) (h : i ≠ j) :
    vertexIdem k Q i * vertexIdem k Q j = 0 := by
  unfold vertexIdem PathAlgebra.ofPath
  rw [PathAlgebra.single_mul_single, PathAlgebra.compSingle_nil_left, if_neg h]
  exact PathAlgebra.smul_pathAlgebra_zero _

/-- Relation (3): the source idempotent absorbs an arrow (on the left, in the
source-to-target convention): `p_{source} · aₕ = aₕ`. -/
theorem source_mul_arrowGen [Fintype Q] {i j : Q} (e : i ⟶ j) :
    vertexIdem k Q i * arrowGen k Q e = arrowGen k Q e := by
  unfold vertexIdem arrowGen PathAlgebra.ofPath
  rw [PathAlgebra.single_mul_single, PathAlgebra.compSingle_nil_left, if_pos rfl, mul_one,
    one_smul]

/-- Relation (3): a non-source idempotent annihilates an arrow on the left. -/
theorem vertexIdem_mul_arrowGen_of_ne [Fintype Q] {i j : Q} (l : Q) (e : i ⟶ j) (h : l ≠ i) :
    vertexIdem k Q l * arrowGen k Q e = 0 := by
  unfold vertexIdem arrowGen PathAlgebra.ofPath
  rw [PathAlgebra.single_mul_single, PathAlgebra.compSingle_nil_left, if_neg h]
  exact PathAlgebra.smul_pathAlgebra_zero _

/-- Relation (4): the target idempotent absorbs an arrow (on the right, in the
source-to-target convention): `aₕ · p_{target} = aₕ`. -/
theorem arrowGen_mul_target [Fintype Q] {i j : Q} (e : i ⟶ j) :
    arrowGen k Q e * vertexIdem k Q j = arrowGen k Q e := by
  unfold arrowGen vertexIdem PathAlgebra.ofPath
  rw [PathAlgebra.single_mul_single, PathAlgebra.compSingle_nil_right, if_pos rfl, mul_one,
    one_smul]

/-- Relation (4): a non-target idempotent annihilates an arrow on the right. -/
theorem arrowGen_mul_vertexIdem_of_ne [Fintype Q] {i j : Q} (l : Q) (e : i ⟶ j) (h : l ≠ j) :
    arrowGen k Q e * vertexIdem k Q l = 0 := by
  unfold arrowGen vertexIdem PathAlgebra.ofPath
  rw [PathAlgebra.single_mul_single, PathAlgebra.compSingle_nil_right, if_neg h.symm]
  exact PathAlgebra.smul_pathAlgebra_zero _

/-! ## The exact book-facing presentation -/

namespace Book

/-- The trivial-path generator `pᵢ` in the path algebra with the book's multiplication order. -/
noncomputable def vertexIdem (i : Q) : BookPathAlgebra k Q :=
  BookPathAlgebra.trivialPath (k := k) (Q := Q) i

/-- The one-arrow generator `aₕ` in the path algebra with the book's multiplication order. -/
noncomputable def arrowGen {i j : Q} (e : i ⟶ j) : BookPathAlgebra k Q :=
  BookPathAlgebra.ofPath (k := k) ⟨i, j, e.toPath⟩

/-- Appending an arrow to a path is multiplication on the left in the book's order:
`aₑ * a_q = a_{q.cons e}` because the right factor is traversed first. -/
theorem ofPath_cons {a b c : Q} (q : Quiver.Path a b) (e : b ⟶ c) :
    BookPathAlgebra.ofPath (k := k) (⟨a, c, q.cons e⟩ : QuiverPathIndex Q) =
      arrowGen k Q e * BookPathAlgebra.ofPath (k := k) (⟨a, b, q⟩ : QuiverPathIndex Q) := by
  rw [arrowGen, BookPathAlgebra.ofPath_mul_ofPath, Quiver.Path.comp_toPath_eq_cons]

/-- The book-facing path algebra is generated as a `k`-algebra by the vertex idempotents `pᵢ`
and the arrow generators `aₕ`. -/
theorem adjoin_generators_eq_top [Fintype Q] :
    Algebra.adjoin k
      ({x : BookPathAlgebra k Q | ∃ i, x = vertexIdem k Q i} ∪
        {x : BookPathAlgebra k Q | ∃ (i j : Q) (e : i ⟶ j), x = arrowGen k Q e}) = ⊤ := by
  let S : Set (BookPathAlgebra k Q) :=
    {x | ∃ i, x = vertexIdem k Q i} ∪
      {x | ∃ (i j : Q) (e : i ⟶ j), x = arrowGen k Q e}
  have hgen : ∀ (a b : Q) (p : Quiver.Path a b),
      BookPathAlgebra.ofPath (k := k) (⟨a, b, p⟩ : QuiverPathIndex Q) ∈ Algebra.adjoin k S := by
    intro a b p
    induction p with
    | nil =>
        exact Algebra.subset_adjoin (Or.inl ⟨a, rfl⟩)
    | cons q e ih =>
        rw [ofPath_cons]
        exact mul_mem (Algebra.subset_adjoin (Or.inr ⟨_, _, e, rfl⟩)) ih
  change Algebra.adjoin k S = ⊤
  rw [Algebra.eq_top_iff]
  intro x
  rw [← MulOpposite.op_unop x]
  induction x.unop using PathAlgebra.induction_linear with
  | zero => simp
  | add f g hf hg =>
      rw [MulOpposite.op_add]
      exact add_mem hf hg
  | single y c =>
      obtain ⟨a, b, p⟩ := y
      have hsc : MulOpposite.op
          (Finsupp.single (⟨a, b, p⟩ : QuiverPathIndex Q) c : PathAlgebra k Q) =
          c • BookPathAlgebra.ofPath (k := k) (⟨a, b, p⟩ : QuiverPathIndex Q) := by
        apply MulOpposite.unop_injective
        exact (PathAlgebra.smul_single_one c
          (⟨a, b, p⟩ : QuiverPathIndex Q)).symm
      have hmem : c • BookPathAlgebra.ofPath (k := k)
          (⟨a, b, p⟩ : QuiverPathIndex Q) ∈ Algebra.adjoin k S :=
        Subalgebra.smul_mem _ (hgen a b p) c
      exact hsc.symm ▸ hmem

/-- Relation (1): `∑ᵢ pᵢ = 1`. -/
theorem sum_vertexIdem [Fintype Q] :
    ∑ i, vertexIdem k Q i = 1 := by
  exact BookPathAlgebra.sum_trivialPaths_eq_one

/-- Relation (2): `pᵢ² = pᵢ`. -/
theorem vertexIdem_sq [Fintype Q] (i : Q) :
    vertexIdem k Q i * vertexIdem k Q i = vertexIdem k Q i := by
  rw [vertexIdem, BookPathAlgebra.trivialPath, BookPathAlgebra.ofPath_mul_ofPath,
    Quiver.Path.nil_comp]

/-- Relation (2): `pᵢ pⱼ = 0` when `i ≠ j`. -/
theorem vertexIdem_mul_of_ne [Fintype Q] (i j : Q) (h : i ≠ j) :
    vertexIdem k Q i * vertexIdem k Q j = 0 := by
  exact BookPathAlgebra.ofPath_mul_ofPath_eq_zero Quiver.Path.nil Quiver.Path.nil h.symm

/-- Relation (3), exactly as printed: `aₕ p_{h'} = aₕ`. -/
theorem arrowGen_mul_source [Fintype Q] {i j : Q} (e : i ⟶ j) :
    arrowGen k Q e * vertexIdem k Q i = arrowGen k Q e := by
  rw [arrowGen, vertexIdem, BookPathAlgebra.trivialPath,
    BookPathAlgebra.ofPath_mul_ofPath, Quiver.Path.nil_comp]

/-- Relation (3), exactly as printed: `aₕ p_l = 0` when `l ≠ h'`. -/
theorem arrowGen_mul_vertexIdem_of_ne [Fintype Q] {i j : Q} (l : Q) (e : i ⟶ j)
    (h : l ≠ i) :
    arrowGen k Q e * vertexIdem k Q l = 0 := by
  exact BookPathAlgebra.ofPath_mul_ofPath_eq_zero Quiver.Path.nil e.toPath h

/-- Relation (4), exactly as printed: `p_{h''} aₕ = aₕ`. -/
theorem target_mul_arrowGen [Fintype Q] {i j : Q} (e : i ⟶ j) :
    vertexIdem k Q j * arrowGen k Q e = arrowGen k Q e := by
  rw [vertexIdem, BookPathAlgebra.trivialPath, arrowGen,
    BookPathAlgebra.ofPath_mul_ofPath, Quiver.Path.comp_nil]

/-- Relation (4), exactly as printed: `p_l aₕ = 0` when `l ≠ h''`. -/
theorem vertexIdem_mul_arrowGen_of_ne [Fintype Q] {i j : Q} (l : Q) (e : i ⟶ j)
    (h : l ≠ j) :
    vertexIdem k Q l * arrowGen k Q e = 0 := by
  exact BookPathAlgebra.ofPath_mul_ofPath_eq_zero e.toPath Quiver.Path.nil h.symm

end Book

/-! ## Evaluation of paths into a target algebra -/

section Universal

variable {k Q}
variable {B : Type*} [Ring B] [Algebra k B] (P : Q → B) (A : ∀ i j : Q, (i ⟶ j) → B)

/-- Evaluate an oriented path `p : a ⟶* b` into `B` using vertex data `P` and arrow data `A`:
the trivial path at `a` maps to `P a`, and appending an arrow `e` multiplies on the right by the
corresponding `A`. This is the value the universal algebra map assigns to a basis path. -/
def evalPath {a : Q} : {b : Q} → Quiver.Path a b → B
  | _, Quiver.Path.nil => P a
  | _, Quiver.Path.cons q e => evalPath q * A _ _ e

omit [DecidableEq Q] in
@[simp] theorem evalPath_nil (a : Q) :
    evalPath P A (Quiver.Path.nil : Quiver.Path a a) = P a := rfl

omit [DecidableEq Q] in
@[simp] theorem evalPath_cons {a b c : Q} (q : Quiver.Path a b) (e : b ⟶ c) :
    evalPath P A (q.cons e) = evalPath P A q * A b c e := rfl

/-- The `k`-linear map `P_Q → B` sending each basis path to its `evalPath` value. -/
noncomputable def evalMap : PathAlgebra k Q →ₗ[k] B :=
  Finsupp.linearCombination k (fun x : QuiverPathIndex Q => evalPath P A x.2.2)

theorem evalMap_single (x : QuiverPathIndex Q) (c : k) :
    evalMap P A (Finsupp.single x c) = c • evalPath P A x.2.2 :=
  Finsupp.linearCombination_single (R := k) c x

end Universal

/-! ## Universal property: relations (1)–(4) are defining -/

/-- **Defining relations.** For any `k`-algebra `B` with elements `P i` (`i ∈ I`) and
`A i j e` (arrows `e : i ⟶ j`) satisfying the relations (1)–(4), there is a unique `k`-algebra
homomorphism `P_Q → B` sending each `pᵢ ↦ P i` and each `aₕ ↦ A i j e`. This expresses that
(1)–(4) are a complete set of defining relations for the path algebra. -/
theorem defining_relations_universal [Fintype Q]
    (B : Type*) [Ring B] [Algebra k B]
    (P : Q → B) (A : ∀ i j : Q, (i ⟶ j) → B)
    (hsum : ∑ i, P i = 1)
    (hidem : ∀ i, P i * P i = P i)
    (horth : ∀ i j, i ≠ j → P i * P j = 0)
    (hsa : ∀ i j (e : i ⟶ j), P i * A i j e = A i j e)
    (_hsa0 : ∀ (l : Q) i j (e : i ⟶ j), l ≠ i → P l * A i j e = 0)
    (hat : ∀ i j (e : i ⟶ j), A i j e * P j = A i j e)
    (_hat0 : ∀ (l : Q) i j (e : i ⟶ j), l ≠ j → A i j e * P l = 0) :
    ∃! φ : PathAlgebra k Q →ₐ[k] B,
      (∀ i, φ (vertexIdem k Q i) = P i) ∧
        (∀ i j (e : i ⟶ j), φ (arrowGen k Q e) = A i j e) := by
  -- The source vertex idempotent absorbs an evaluated path on the left.
  have hsrc : ∀ {a b : Q} (p : Quiver.Path a b), P a * evalPath P A p = evalPath P A p := by
    intro a b p
    induction p with
    | nil => rw [evalPath_nil]; exact hidem a
    | cons q e ih => rw [evalPath_cons, ← mul_assoc, ih]
  -- The target vertex idempotent absorbs an evaluated path on the right.
  have htgt : ∀ {a b : Q} (p : Quiver.Path a b), evalPath P A p * P b = evalPath P A p := by
    intro a b p
    induction p with
    | nil => rw [evalPath_nil]; exact hidem a
    | cons q e ih => rw [evalPath_cons, mul_assoc, hat]
  -- Evaluation turns path concatenation into multiplication.
  have hcomp : ∀ {a b c : Q} (p : Quiver.Path a b) (q : Quiver.Path b c),
      evalPath P A (p.comp q) = evalPath P A p * evalPath P A q := by
    intro a b c p q
    induction q with
    | nil => rw [Quiver.Path.comp_nil, evalPath_nil, htgt]
    | cons r e ih => rw [Quiver.Path.comp_cons, evalPath_cons, evalPath_cons, ih, mul_assoc]
  -- `evalMap` sends the unit to the unit.
  have h1 : evalMap P A (1 : PathAlgebra k Q) = 1 := by
    rw [PathAlgebra.one_eq_ofPath_sum, map_sum]
    refine Eq.trans (Finset.sum_congr rfl fun i _ => ?_) hsum
    simp [PathAlgebra.ofPath, evalMap_single]
  -- `evalMap` is multiplicative.
  have hmul : ∀ x y : PathAlgebra k Q,
      evalMap P A (x * y) = evalMap P A x * evalMap P A y := by
    intro x y
    induction x using PathAlgebra.induction_linear with
    | zero => rw [zero_mul, map_zero, zero_mul]
    | add x1 x2 hx1 hx2 => rw [add_mul, map_add, map_add, add_mul, hx1, hx2]
    | single sx a =>
      induction y using PathAlgebra.induction_linear with
      | zero => rw [mul_zero, map_zero, mul_zero]
      | add y1 y2 hy1 hy2 => rw [mul_add, map_add, map_add, mul_add, hy1, hy2]
      | single sy b =>
        obtain ⟨xa, xb, xp⟩ := sx
        obtain ⟨ya, yb, yq⟩ := sy
        rw [PathAlgebra.single_mul_single]
        by_cases hxy : xb = ya
        · subst hxy
          rw [PathAlgebra.compSingle_eq]
          simp only [map_smul, evalMap_single, one_smul]
          rw [hcomp, smul_mul_assoc, mul_smul_comm, smul_smul]
        · rw [PathAlgebra.compSingle_eq_zero _ _ hxy, smul_zero, map_zero]
          simp only [evalMap_single]
          rw [smul_mul_assoc, mul_smul_comm]
          have horthxy : evalPath P A xp * evalPath P A yq = 0 := by
            conv_lhs => rw [← htgt xp, ← hsrc yq]
            rw [mul_assoc, ← mul_assoc (P xb), horth xb ya hxy, zero_mul, mul_zero]
          rw [horthxy, smul_zero, smul_zero]
  -- Package the linear map as an algebra homomorphism.
  let φ : PathAlgebra k Q →ₐ[k] B := AlgHom.ofLinearMap (evalMap P A) h1 hmul
  have hφapp : ∀ z, φ z = evalMap P A z := fun _ => rfl
  have hφvertex : ∀ i, φ (vertexIdem k Q i) = P i := by
    intro i
    rw [hφapp, vertexIdem, PathAlgebra.ofPath, evalMap_single]
    simp
  have hφarrow : ∀ i j (e : i ⟶ j), φ (arrowGen k Q e) = A i j e := by
    intro i j e
    rw [hφapp, arrowGen, PathAlgebra.ofPath, evalMap_single, one_smul]
    exact hsa i j e
  refine ⟨φ, ⟨hφvertex, hφarrow⟩, ?_⟩
  -- Uniqueness: any `ψ` agreeing on the generators agrees on every basis path, hence everywhere.
  intro ψ hψ
  apply AlgHom.ext
  intro z
  induction z using PathAlgebra.induction_linear with
  | zero => rw [map_zero, map_zero]
  | add u v hu hv => rw [map_add, map_add, hu, hv]
  | single x c =>
    obtain ⟨a, b, p⟩ := x
    have hsc : (Finsupp.single (⟨a, b, p⟩ : QuiverPathIndex Q) c : PathAlgebra k Q)
        = c • PathAlgebra.ofPath (k := k) (⟨a, b, p⟩ : QuiverPathIndex Q) := by
      exact (PathAlgebra.smul_single_one c _).symm
    rw [hsc, map_smul, map_smul]
    congr 1
    clear hsc
    induction p with
    | nil => exact (hψ.1 a).trans (hφvertex a).symm
    | cons q e ih =>
      rw [ofPath_cons, map_mul, map_mul, ih, hψ.2 _ _ e, hφarrow _ _ e]

namespace Book

/-- **Defining relations in the book's exact order.** Elements satisfying the four printed
relations determine a unique algebra homomorphism from `BookPathAlgebra`. This strengthens the
generation theorem above from "these elements generate" to the asserted generators-and-relations
universal property. -/
theorem defining_relations_universal [Fintype Q]
    (B : Type*) [Ring B] [Algebra k B]
    (P : Q → B) (A : ∀ i j : Q, (i ⟶ j) → B)
    (hsum : ∑ i, P i = 1)
    (hidem : ∀ i, P i * P i = P i)
    (horth : ∀ i j, i ≠ j → P i * P j = 0)
    (has : ∀ i j (e : i ⟶ j), A i j e * P i = A i j e)
    (has0 : ∀ (l : Q) i j (e : i ⟶ j), l ≠ i → A i j e * P l = 0)
    (hta : ∀ i j (e : i ⟶ j), P j * A i j e = A i j e)
    (hta0 : ∀ (l : Q) i j (e : i ⟶ j), l ≠ j → P l * A i j e = 0) :
    ∃! φ : BookPathAlgebra k Q →ₐ[k] B,
      (∀ i, φ (vertexIdem k Q i) = P i) ∧
        (∀ i j (e : i ⟶ j), φ (arrowGen k Q e) = A i j e) := by
  let Pop : Q → Bᵐᵒᵖ := fun i => MulOpposite.op (P i)
  let Aop : ∀ i j : Q, (i ⟶ j) → Bᵐᵒᵖ :=
    fun i j e => MulOpposite.op (A i j e)
  have hsumOp : ∑ i, Pop i = 1 := by
    apply MulOpposite.unop_injective
    rw [show MulOpposite.unop (∑ i, Pop i) = ∑ i, MulOpposite.unop (Pop i) from
      map_sum MulOpposite.opAddEquiv.symm _ Finset.univ]
    simpa [Pop] using hsum
  have hidemOp : ∀ i, Pop i * Pop i = Pop i := by
    intro i
    apply MulOpposite.unop_injective
    simpa [Pop] using hidem i
  have horthOp : ∀ i j, i ≠ j → Pop i * Pop j = 0 := by
    intro i j hij
    apply MulOpposite.unop_injective
    simpa [Pop] using horth j i hij.symm
  have hsaOp : ∀ i j (e : i ⟶ j), Pop i * Aop i j e = Aop i j e := by
    intro i j e
    apply MulOpposite.unop_injective
    simpa [Pop, Aop] using has i j e
  have hsa0Op : ∀ (l : Q) i j (e : i ⟶ j), l ≠ i → Pop l * Aop i j e = 0 := by
    intro l i j e hli
    apply MulOpposite.unop_injective
    simpa [Pop, Aop] using has0 l i j e hli
  have hatOp : ∀ i j (e : i ⟶ j), Aop i j e * Pop j = Aop i j e := by
    intro i j e
    apply MulOpposite.unop_injective
    simpa [Pop, Aop] using hta i j e
  have hat0Op : ∀ (l : Q) i j (e : i ⟶ j), l ≠ j → Aop i j e * Pop l = 0 := by
    intro l i j e hlj
    apply MulOpposite.unop_injective
    simpa [Pop, Aop] using hta0 l i j e hlj
  obtain ⟨ψ, hψ, huniq⟩ := Etingof.Problem2_8_6.defining_relations_universal
    k Q Bᵐᵒᵖ Pop Aop hsumOp hidemOp horthOp hsaOp hsa0Op hatOp hat0Op
  let φ : BookPathAlgebra k Q →ₐ[k] B := AlgHom.opComm ψ
  have hφvertex : ∀ i, φ (vertexIdem k Q i) = P i := by
    intro i
    change MulOpposite.unop (ψ (Etingof.Problem2_8_6.vertexIdem k Q i)) = P i
    rw [hψ.1 i]
    rfl
  have hφarrow : ∀ i j (e : i ⟶ j), φ (arrowGen k Q e) = A i j e := by
    intro i j e
    change MulOpposite.unop (ψ (Etingof.Problem2_8_6.arrowGen k Q e)) = A i j e
    rw [hψ.2 i j e]
    rfl
  refine ⟨φ, ⟨hφvertex, hφarrow⟩, ?_⟩
  intro χ hχ
  let χop : PathAlgebra k Q →ₐ[k] Bᵐᵒᵖ := AlgHom.opComm.symm χ
  have hχopVertex : ∀ i,
      χop (Etingof.Problem2_8_6.vertexIdem k Q i) = Pop i := by
    intro i
    change MulOpposite.op (χ (vertexIdem k Q i)) = MulOpposite.op (P i)
    rw [hχ.1 i]
  have hχopArrow : ∀ i j (e : i ⟶ j),
      χop (Etingof.Problem2_8_6.arrowGen k Q e) = Aop i j e := by
    intro i j e
    change MulOpposite.op (χ (arrowGen k Q e)) = MulOpposite.op (A i j e)
    rw [hχ.2 i j e]
  have hop : χop = ψ := huniq χop ⟨hχopVertex, hχopArrow⟩
  apply AlgHom.opComm.symm.injective
  simpa [χop, φ] using hop

end Book

end Etingof.Problem2_8_6

-- The leaf names follow Mathlib conventions; the underscore comes solely from the stable
-- book-number namespace `Problem2_8_6`, which is part of this project's public API.
attribute [nolint defsWithUnderscore]
  Etingof.Problem2_8_6.vertexIdem Etingof.Problem2_8_6.arrowGen
  Etingof.Problem2_8_6.Book.vertexIdem Etingof.Problem2_8_6.Book.arrowGen
  Etingof.Problem2_8_6.evalPath Etingof.Problem2_8_6.evalMap
