import EtingofRepresentationTheory.Chapter2.Problem2_7_5_Iso
import EtingofRepresentationTheory.Chapter2.Problem2_7_5_FamilySimple

/-!
# Problem 2.7.5(c): the family `V(α,β)` exhausts the finite dimensional irreducibles

Let `q` be a root of unity of order `n = orderOf q`. The three preceding files supply

* `Problem2_7_5_Family.lean` — the `n`-dimensional module `V(α,β)` for `(α, β) ∈ ℂˣ × ℂˣ`,
  with `x` the twisted cyclic shift and `y` diagonal (`y·eⱼ = β·qʲ·eⱼ`);
* `Problem2_7_5_FamilySimple.lean` — every `V(α,β)` is simple;
* `Problem2_7_5_Iso.lean` — `V(α,β) ≅ V(α',β')` iff `α = α'` and `βⁿ = β'ⁿ`.

This file closes the classification by proving the remaining, converse half: **every** finite
dimensional irreducible `qWeylAlgebra ℂ q`-module is isomorphic to some `V(α,β)`.

## The argument

Following the book's hint that Problem 2.7.5(c) "is similar to part (c) of the previous
problem", `Problem2_7_5.exists_orbit_basis` already extracts from an arbitrary finite
dimensional simple module `V` a `ℂ`-basis `b : Fin n → V` on which

* `y` acts diagonally with eigenvalues `β·qⁱ` (`β ≠ 0` the eigenvalue of a chosen
  `y`-eigenvector — one exists because `ℂ` is algebraically closed), and
* `x` acts as the twisted cyclic shift with wrap-around scalar `α ≠ 0` (the scalar by which the
  central element `xⁿ` acts, by Schur's lemma).

Those are exactly the structure constants of `V(α,β)`, so the `ℂ`-linear map `eᵢ ↦ bᵢ` is an
isomorphism of `qWeylAlgebra ℂ q`-modules. Only the two generators `x` and `y` have to be
checked by hand: `x⁻¹` and `y⁻¹` follow formally (`smul_inv_of_smul`), and the algebra is
generated by those four elements, so an `Algebra.adjoin` induction promotes the generator
identities to all of `qWeylAlgebra ℂ q`.

## Main results

* `Etingof.Problem2_7_5.exists_famModule_linearEquiv` — exhaustiveness, phrased on the concrete
  carrier `Fin N → ℂ` for any `N` with `orderOf q = N`.
* `Etingof.Problem2_7_5.exists_fam_linearEquiv` — the same, phrased with the parameter-indexed
  carrier `Fam q α β` of `Problem2_7_5_Iso.lean`.
* `Etingof.Problem2_7_5.finrank_eq_orderOf_of_fam_linearEquiv` — the dimension formula
  `dim V = n`, re-derived from exhaustiveness (so `finrank_irreducible_eq_orderOf` is subsumed,
  not merely paralleled).
* `Etingof.Problem2_7_5.exists_unique_fam_linearEquiv` — **the classification of Problem
  2.7.5(c)**: every finite dimensional irreducible representation is `V(α,β)` for parameters
  `(α, β)` that are unique up to the relation `βⁿ = β'ⁿ`.
-/

namespace Etingof.Problem2_7_5

open Etingof Module

section Exhaustive

variable (q : ℂˣ)

/-- If a map intertwines the action of an invertible algebra element `u`, it also intertwines
the action of its inverse `u'`. Used to get `x⁻¹` and `y⁻¹` for free once `x` and `y` are
checked; note that `E` is not assumed additive, only the two module structures are used. -/
private theorem smul_inv_of_smul {A W V : Type*} [Ring A] [AddCommGroup W] [Module A W]
    [AddCommGroup V] [Module A V] (E : W → V) (u u' : A) (huu' : u * u' = 1) (hu'u : u' * u = 1)
    (hE : ∀ f : W, E (u • f) = u • E f) (f : W) : E (u' • f) = u' • E f := by
  have h1 : u • E (u' • f) = E f := by rw [← hE (u' • f), ← mul_smul, huu', one_smul]
  have h2 : u • (u' • E f) = E f := by rw [← mul_smul, huu', one_smul]
  have h3 : u' • (u • E (u' • f)) = u' • (u • (u' • E f)) := by rw [h1, h2]
  rwa [← mul_smul, hu'u, one_smul, ← mul_smul, hu'u, one_smul] at h3

/-- **Rigidity: two generators suffice.** A `ℂ`-linear isomorphism between `q`-Weyl modules that
intertwines the actions of `x` and `y` is automatically an isomorphism of
`qWeylAlgebra ℂ q`-modules.

The inverses `x⁻¹`, `y⁻¹` are intertwined for free (`smul_inv_of_smul`), and the four elements
`x, x⁻¹, y, y⁻¹` generate `qWeylAlgebra ℂ q` over `ℂ` — that is how the algebra is defined
(`Algebra.adjoin_adjoin_coe_preimage` reads the defining generating set back inside the
subalgebra) — so an `Algebra.adjoin` induction promotes the generator identities to the whole
algebra.

Both module structures are kept abstract on purpose: applying this to a module built by the
universal property `QWeyl.module` would otherwise force the elaborator to unfold that
construction on every unification. -/
theorem nonempty_linearEquiv_of_intertwines_generators
    {W V : Type*} [AddCommGroup W] [Module ℂ W] [Module (qWeylAlgebra ℂ q) W]
    [IsScalarTower ℂ (qWeylAlgebra ℂ q) W]
    [AddCommGroup V] [Module ℂ V] [Module (qWeylAlgebra ℂ q) V]
    [IsScalarTower ℂ (qWeylAlgebra ℂ q) V] (E : W ≃ₗ[ℂ] V)
    (hx : ∀ f : W, E (QWeyl.qWeylMono q (1, 0) • f) = QWeyl.qWeylMono q (1, 0) • E f)
    (hy : ∀ f : W, E (QWeyl.qWeylMono q (0, 1) • f) = QWeyl.qWeylMono q (0, 1) • E f) :
    Nonempty (W ≃ₗ[qWeylAlgebra ℂ q] V) := by
  -- The inverses come for free.
  have hxinv : ∀ f : W,
      E (QWeyl.qWeylMono q (-1, 0) • f) = QWeyl.qWeylMono q (-1, 0) • E f := by
    have h1 : QWeyl.qWeylMono q (1, 0) * QWeyl.qWeylMono q (-1, 0) = 1 := by
      rw [QWeyl.qWeylMono_mul]; norm_num [QWeyl.qWeylMono_zero]
    have h2 : QWeyl.qWeylMono q (-1, 0) * QWeyl.qWeylMono q (1, 0) = 1 := by
      rw [QWeyl.qWeylMono_mul]; norm_num [QWeyl.qWeylMono_zero]
    exact fun f =>
      smul_inv_of_smul (A := qWeylAlgebra ℂ q) (W := W) (V := V) E _ _ h1 h2 hx f
  have hyinv : ∀ f : W,
      E (QWeyl.qWeylMono q (0, -1) • f) = QWeyl.qWeylMono q (0, -1) • E f := by
    have h1 : QWeyl.qWeylMono q (0, 1) * QWeyl.qWeylMono q (0, -1) = 1 := by
      rw [QWeyl.qWeylMono_mul]; norm_num [QWeyl.qWeylMono_zero]
    have h2 : QWeyl.qWeylMono q (0, -1) * QWeyl.qWeylMono q (0, 1) = 1 := by
      rw [QWeyl.qWeylMono_mul]; norm_num [QWeyl.qWeylMono_zero]
    exact fun f =>
      smul_inv_of_smul (A := qWeylAlgebra ℂ q) (W := W) (V := V) E _ _ h1 h2 hy f
  -- The four generators of the concrete subalgebra `qWeylAlgebra ℂ q`, read inside the
  -- subalgebra itself, generate it over `ℂ`.
  have hpre : (((↑) : qWeylAlgebra ℂ q → Module.End ℂ (QWeylModule ℂ)) ⁻¹'
        {qMono ℂ q (1, 0), qMono ℂ q (-1, 0), qMono ℂ q (0, 1), qMono ℂ q (0, -1)})
      = ({QWeyl.qWeylMono q (1, 0), QWeyl.qWeylMono q (-1, 0), QWeyl.qWeylMono q (0, 1),
          QWeyl.qWeylMono q (0, -1)} : Set (qWeylAlgebra ℂ q)) := by
    ext a
    simp [Set.mem_preimage, Subtype.ext_iff]
  have htop : Algebra.adjoin ℂ
      ({QWeyl.qWeylMono q (1, 0), QWeyl.qWeylMono q (-1, 0), QWeyl.qWeylMono q (0, 1),
        QWeyl.qWeylMono q (0, -1)} : Set (qWeylAlgebra ℂ q)) = ⊤ := by
    rw [← hpre]
    exact Algebra.adjoin_adjoin_coe_preimage
  have hall : ∀ (a : qWeylAlgebra ℂ q) (f : W), E (a • f) = a • E f := by
    intro a
    have ha : a ∈ Algebra.adjoin ℂ
        ({QWeyl.qWeylMono q (1, 0), QWeyl.qWeylMono q (-1, 0), QWeyl.qWeylMono q (0, 1),
          QWeyl.qWeylMono q (0, -1)} : Set (qWeylAlgebra ℂ q)) := by
      rw [htop]; exact Algebra.mem_top
    induction ha using Algebra.adjoin_induction with
    | mem g hg =>
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
        rcases hg with rfl | rfl | rfl | rfl
        · exact hx
        · exact hxinv
        · exact hy
        · exact hyinv
    | algebraMap r =>
        intro f
        rw [algebraMap_smul, algebraMap_smul, map_smul]
    | add u v _ _ ihu ihv =>
        intro f
        rw [add_smul, map_add, ihu f, ihv f, add_smul]
    | mul u v _ _ ihu ihv =>
        intro f
        rw [mul_smul, ihu, ihv, ← mul_smul]
  exact ⟨{ E with map_smul' := fun a f => hall a f }⟩

/-- **Exhaustiveness of the family `V(α,β)`.** Every finite dimensional irreducible
representation `V` of the `q`-Weyl algebra is isomorphic to a member of the classifying family:
there are parameters `(α, β) ∈ ℂˣ × ℂˣ` and an isomorphism of `qWeylAlgebra ℂ q`-modules
`V(α,β) ≃ V`.

The parameters are read off the orbit basis of `exists_orbit_basis`: `β` is the eigenvalue of a
`y`-eigenvector, and `α` is the scalar by which the central element `xⁿ` acts. -/
theorem exists_famModule_linearEquiv
    (V : Type*) [AddCommGroup V] [Module ℂ V] [Module (qWeylAlgebra ℂ q) V]
    [IsScalarTower ℂ (qWeylAlgebra ℂ q) V] [FiniteDimensional ℂ V]
    [IsSimpleModule (qWeylAlgebra ℂ q) V] (N : ℕ) [NeZero N] (hqorder : orderOf q = N) :
    ∃ α β : ℂˣ, letI := famModule q α β N hqorder
      Nonempty ((Fin N → ℂ) ≃ₗ[qWeylAlgebra ℂ q] V) := by
  classical
  obtain ⟨α, β, b, hY, hX⟩ := exists_orbit_basis q V N hqorder
  refine ⟨α, β, ?_⟩
  letI := famModule q α β N hqorder
  haveI : IsScalarTower ℂ (qWeylAlgebra ℂ q) (Fin N → ℂ) :=
    famModule_isScalarTower q α β N hqorder
  -- The `ℂ`-linear identification carrying the standard basis to the orbit basis. Only the
  -- characterizing property `hEsingle` is used below, so `E` is kept opaque.
  obtain ⟨E, hEsingle⟩ :
      ∃ E : (Fin N → ℂ) ≃ₗ[ℂ] V, ∀ i : Fin N, E (Pi.single i (1 : ℂ)) = b i := by
    refine ⟨b.equivFun.symm, fun i => ?_⟩
    simp [Module.Basis.equivFun_symm_apply, Pi.single_apply]
  have hdecomp : ∀ f : Fin N → ℂ, f = ∑ i : Fin N, f i • Pi.single i (1 : ℂ) := by
    intro f
    funext j
    simp [Finset.sum_apply, Pi.single_apply]
  -- It suffices to check an intertwining identity on the standard basis.
  have hlin : ∀ (T : (Fin N → ℂ) →ₗ[ℂ] (Fin N → ℂ)) (a : qWeylAlgebra ℂ q),
      (∀ i : Fin N, E (T (Pi.single i (1 : ℂ))) = a • E (Pi.single i (1 : ℂ))) →
      ∀ f : Fin N → ℂ, E (T f) = a • E f := by
    intro T a h f
    have hL : E (T f) = ∑ i : Fin N, f i • E (T (Pi.single i (1 : ℂ))) := by
      conv_lhs => rw [hdecomp f]
      simp only [map_sum, map_smul]
    have hR : a • E f = ∑ i : Fin N, f i • (a • E (Pi.single i (1 : ℂ))) := by
      conv_lhs => rw [hdecomp f]
      rw [map_sum, Finset.smul_sum]
      exact Finset.sum_congr rfl fun i _ => by rw [map_smul, smul_comm]
    rw [hL, hR]
    exact Finset.sum_congr rfl fun i _ => by rw [h i]
  -- The two generators.
  have hx : ∀ f : Fin N → ℂ,
      E (QWeyl.qWeylMono q (1, 0) • f) = QWeyl.qWeylMono q (1, 0) • E f := by
    have key := hlin (Xlin α N) (QWeyl.qWeylMono q (1, 0)) fun i => by
      rw [Xlin_single, map_smul, hEsingle (i + 1), hEsingle i, hX i]
      rfl
    intro f
    rw [famModule_x_smul q α β N hqorder f]
    exact key f
  have hy : ∀ f : Fin N → ℂ,
      E (QWeyl.qWeylMono q (0, 1) • f) = QWeyl.qWeylMono q (0, 1) • E f := by
    have key := hlin (Ylin q β N) (QWeyl.qWeylMono q (0, 1)) fun i => by
      rw [Ylin_single, map_smul, hEsingle i, hY i]
      rfl
    intro f
    rw [famModule_y_smul q α β N hqorder f]
    exact key f
  -- Two generators suffice.
  exact nonempty_linearEquiv_of_intertwines_generators q E hx hy

variable [NeZero (orderOf q)]

/-- **Exhaustiveness, on the parameter-indexed carrier.** Every finite dimensional irreducible
representation of the `q`-Weyl algebra is isomorphic to `Fam q α β = V(α,β)` for some
`(α, β) ∈ ℂˣ × ℂˣ`.

The hypothesis `NeZero (orderOf q)` is not a restriction: it follows from the existence of `V`
(`isOfFinOrder_of_nontrivial_finrep`). It has to be stated because the `qWeylAlgebra ℂ q`-module
instance on `Fam q α β` needs it, and instance arguments must already be available when the
statement is elaborated. -/
theorem exists_fam_linearEquiv
    (V : Type*) [AddCommGroup V] [Module ℂ V] [Module (qWeylAlgebra ℂ q) V]
    [IsScalarTower ℂ (qWeylAlgebra ℂ q) V] [FiniteDimensional ℂ V]
    [IsSimpleModule (qWeylAlgebra ℂ q) V] :
    ∃ α β : ℂˣ, Nonempty (Fam q α β ≃ₗ[qWeylAlgebra ℂ q] V) := by
  obtain ⟨α, β, he⟩ := exists_famModule_linearEquiv q V (orderOf q) rfl
  exact ⟨α, β, he⟩

/-- **The dimension formula, re-derived from exhaustiveness.** Since every finite dimensional
irreducible representation is some `V(α,β)`, and `V(α,β)` has dimension `n = orderOf q`
(`fam_finrank`), the dimension of every such representation is `n`. This recovers
`finrank_irreducible_eq_orderOf` from the classification. -/
theorem finrank_eq_orderOf_of_fam_linearEquiv
    (V : Type*) [AddCommGroup V] [Module ℂ V] [Module (qWeylAlgebra ℂ q) V]
    [IsScalarTower ℂ (qWeylAlgebra ℂ q) V] [FiniteDimensional ℂ V]
    [IsSimpleModule (qWeylAlgebra ℂ q) V] :
    Module.finrank ℂ V = orderOf q := by
  obtain ⟨α, β, ⟨e⟩⟩ := exists_fam_linearEquiv q V
  rw [← LinearEquiv.finrank_eq (e.restrictScalars ℂ), fam_finrank]

/-- **Problem 2.7.5(c): the classification of the finite dimensional irreducible
representations of the `q`-Weyl algebra.** For `q` a root of unity of order `n`, every finite
dimensional irreducible representation `V` is isomorphic to a member `V(α,β)` of the explicit
family, and the parameters are determined by `V` exactly up to the relation of
`fam_nonempty_linearEquiv_iff`: `V(α',β') ≅ V` iff `α' = α` and `β'ⁿ = βⁿ`.

This is existence *and* uniqueness: the classifying data is the central character `(α, βⁿ)`. -/
theorem exists_unique_fam_linearEquiv
    (V : Type*) [AddCommGroup V] [Module ℂ V] [Module (qWeylAlgebra ℂ q) V]
    [IsScalarTower ℂ (qWeylAlgebra ℂ q) V] [FiniteDimensional ℂ V]
    [IsSimpleModule (qWeylAlgebra ℂ q) V] :
    ∃ α β : ℂˣ, Nonempty (Fam q α β ≃ₗ[qWeylAlgebra ℂ q] V) ∧
      ∀ α' β' : ℂˣ, Nonempty (Fam q α' β' ≃ₗ[qWeylAlgebra ℂ q] V)
        ↔ α = α' ∧ (β : ℂ) ^ orderOf q = (β' : ℂ) ^ orderOf q := by
  obtain ⟨α, β, ⟨e⟩⟩ := exists_fam_linearEquiv q V
  refine ⟨α, β, ⟨e⟩, fun α' β' => ?_⟩
  constructor
  · rintro ⟨e'⟩
    exact (fam_nonempty_linearEquiv_iff q α β α' β').mp ⟨e.trans e'.symm⟩
  · intro h
    obtain ⟨f⟩ := (fam_nonempty_linearEquiv_iff q α β α' β').mpr h
    exact ⟨f.symm.trans e⟩

end Exhaustive

end Etingof.Problem2_7_5
