import EtingofRepresentationTheory.Chapter2.Proposition2_7_1
import Mathlib.RingTheory.SimpleRing.Basic
import Mathlib.RingTheory.SimpleModule.Basic
import Mathlib.Algebra.Algebra.Subalgebra.Basic
import Mathlib.Algebra.CharP.Basic
import Mathlib.LinearAlgebra.FiniteDimensional.Defs
import Mathlib.FieldTheory.IsAlgClosed.Basic
import Mathlib.LinearAlgebra.Eigenspace.Triangularizable
import Mathlib.Data.Nat.Prime.Factorial
import Mathlib.LinearAlgebra.Dimension.Finrank
import Mathlib.LinearAlgebra.Dimension.Finite

/-!
# Problem 2.7.4: Representations and ideals of the Weyl algebra

Let `A` be the Weyl algebra (`Etingof.WeylAlgebra k`, generated by `x, y` with `yx = xy + 1`).

* **(a)** In characteristic `0`: the only finite dimensional representation of `A` is the zero
  representation, and the only two-sided ideals of `A` are `0` and `A` (i.e. `A` is simple).
  (The obstruction to a nonzero finite dimensional module is `Tr(ρ(x)ρ(y) - ρ(y)ρ(x)) = 0`
  versus `Tr(ρ(1)) = dim V`, which forces `dim V = 0` in characteristic `0`.)

* **(b)** In characteristic `p`: `x^p` and `y^p` are central, and the center of `A` is the
  polynomial subalgebra `k[x^p, y^p]`.

* **(c)** In characteristic `p`: every irreducible finite dimensional representation of `A` has
  dimension exactly `p`.

We render the book's *answers* as the statements (spec); proofs are deferred.
-/

namespace Etingof.Problem2_7_4

open Etingof

/-! ## Commutator lemmas (used for part (b): `xᵖ`, `yᵖ` central)

From the defining relation `yx = xy + 1` (`WeylAlgebra.yx_eq`) one derives, by induction,
the commutator identities `y·xⁿ⁺¹ = xⁿ⁺¹·y + (n+1)·xⁿ` and `x·yⁿ⁺¹ = yⁿ⁺¹·x − (n+1)·yⁿ`.
In characteristic `p` the coefficient `p` vanishes, so `xᵖ` commutes with `y` and `yᵖ`
commutes with `x`; combined with the trivial fact that `xᵖ` (resp. `yᵖ`) commutes with `x`
(resp. `y`), and that `x, y` generate the algebra, this puts `xᵖ` and `yᵖ` in the center. -/

/-- Commutator identity `y · xⁿ⁺¹ = xⁿ⁺¹ · y + (n+1) • xⁿ` in the Weyl algebra. -/
private lemma y_mul_x_pow_succ (k : Type*) [Field k] (n : ℕ) :
    WeylAlgebra.y k * WeylAlgebra.x k ^ (n + 1)
      = WeylAlgebra.x k ^ (n + 1) * WeylAlgebra.y k + (n + 1) • WeylAlgebra.x k ^ n := by
  induction n with
  | zero => simp only [zero_add, pow_one, pow_zero, one_smul]; exact WeylAlgebra.yx_eq k
  | succ n ih =>
    calc WeylAlgebra.y k * WeylAlgebra.x k ^ (n + 1 + 1)
        = WeylAlgebra.y k * WeylAlgebra.x k ^ (n + 1) * WeylAlgebra.x k := by
          rw [pow_succ, mul_assoc]
      _ = (WeylAlgebra.x k ^ (n + 1) * WeylAlgebra.y k + (n + 1) • WeylAlgebra.x k ^ n)
            * WeylAlgebra.x k := by rw [ih]
      _ = WeylAlgebra.x k ^ (n + 1) * (WeylAlgebra.y k * WeylAlgebra.x k)
            + (n + 1) • WeylAlgebra.x k ^ (n + 1) := by
          rw [add_mul, mul_assoc, smul_mul_assoc, ← pow_succ]
      _ = WeylAlgebra.x k ^ (n + 1) * (WeylAlgebra.x k * WeylAlgebra.y k + 1)
            + (n + 1) • WeylAlgebra.x k ^ (n + 1) := by rw [WeylAlgebra.yx_eq]
      _ = WeylAlgebra.x k ^ (n + 1 + 1) * WeylAlgebra.y k
            + (n + 1 + 1) • WeylAlgebra.x k ^ (n + 1) := by
          rw [mul_add, mul_one, ← mul_assoc, ← pow_succ, add_assoc,
            add_comm (WeylAlgebra.x k ^ (n + 1)) ((n + 1) • WeylAlgebra.x k ^ (n + 1)),
            ← succ_nsmul]

/-- Commutator identity `x · yⁿ⁺¹ = yⁿ⁺¹ · x − (n+1) • yⁿ` in the Weyl algebra. -/
private lemma x_mul_y_pow_succ (k : Type*) [Field k] (n : ℕ) :
    WeylAlgebra.x k * WeylAlgebra.y k ^ (n + 1)
      = WeylAlgebra.y k ^ (n + 1) * WeylAlgebra.x k - (n + 1) • WeylAlgebra.y k ^ n := by
  have hxy : WeylAlgebra.x k * WeylAlgebra.y k = WeylAlgebra.y k * WeylAlgebra.x k - 1 := by
    rw [eq_sub_iff_add_eq]; exact (WeylAlgebra.yx_eq k).symm
  induction n with
  | zero => simp only [zero_add, pow_one, pow_zero, one_smul]; exact hxy
  | succ n ih =>
    calc WeylAlgebra.x k * WeylAlgebra.y k ^ (n + 1 + 1)
        = WeylAlgebra.x k * WeylAlgebra.y k ^ (n + 1) * WeylAlgebra.y k := by
          rw [pow_succ, mul_assoc]
      _ = (WeylAlgebra.y k ^ (n + 1) * WeylAlgebra.x k - (n + 1) • WeylAlgebra.y k ^ n)
            * WeylAlgebra.y k := by rw [ih]
      _ = WeylAlgebra.y k ^ (n + 1) * (WeylAlgebra.x k * WeylAlgebra.y k)
            - (n + 1) • WeylAlgebra.y k ^ (n + 1) := by
          rw [sub_mul, mul_assoc, smul_mul_assoc, ← pow_succ]
      _ = WeylAlgebra.y k ^ (n + 1) * (WeylAlgebra.y k * WeylAlgebra.x k - 1)
            - (n + 1) • WeylAlgebra.y k ^ (n + 1) := by rw [hxy]
      _ = WeylAlgebra.y k ^ (n + 1 + 1) * WeylAlgebra.x k
            - (n + 1 + 1) • WeylAlgebra.y k ^ (n + 1) := by
          rw [mul_sub, mul_one, ← mul_assoc, ← pow_succ, sub_sub,
            add_comm (WeylAlgebra.y k ^ (n + 1)) ((n + 1) • WeylAlgebra.y k ^ (n + 1)),
            ← succ_nsmul]

/-- An element of the Weyl algebra that commutes with both generators `x` and `y` is central.
Since `x, y` generate the algebra (via the surjection from the free algebra), commuting with
the generators is enough to commute with everything. -/
private theorem mem_center_of_comm_gen (k : Type*) [Field k] {z : WeylAlgebra k}
    (hx : z * WeylAlgebra.x k = WeylAlgebra.x k * z)
    (hy : z * WeylAlgebra.y k = WeylAlgebra.y k * z) :
    z ∈ Subalgebra.center k (WeylAlgebra k) := by
  rw [Subalgebra.mem_center_iff]
  intro b
  obtain ⟨a, rfl⟩ := RingQuot.mkAlgHom_surjective k (WeylAlgebraRel k) b
  have ha : a ∈ Algebra.adjoin k (Set.range (FreeAlgebra.ι k)) := by
    rw [FreeAlgebra.adjoin_range_ι]; exact Algebra.mem_top
  induction ha using Algebra.adjoin_induction with
  | mem g hg =>
    obtain ⟨i, rfl⟩ := hg
    fin_cases i
    · exact hx.symm
    · exact hy.symm
  | algebraMap r => rw [AlgHom.commutes]; exact Algebra.commutes r z
  | add p q _ _ ihp ihq => rw [map_add, add_mul, mul_add, ihp, ihq]
  | mul p q _ _ ihp ihq => rw [map_mul, mul_assoc, ihq, ← mul_assoc, ihp, mul_assoc]

/-! ## (a) Characteristic zero -/

/-- **(a)** In characteristic `0`, the Weyl algebra has no nonzero finite dimensional
representation: any finite dimensional `A`-module (as a `k`-vector space) is zero. -/
theorem finrank_eq_zero_of_charZero (k : Type*) [Field k] [CharZero k]
    (V : Type*) [AddCommGroup V] [Module k V] [Module (WeylAlgebra k) V]
    [IsScalarTower k (WeylAlgebra k) V] [FiniteDimensional k V] :
    Module.finrank k V = 0 :=
  sorry

/-- **(a)** In characteristic `0`, the Weyl algebra is a simple ring: its only two-sided ideals
are `0` and the whole algebra. -/
theorem isSimpleRing_charZero (k : Type*) [Field k] [CharZero k] :
    IsSimpleRing (WeylAlgebra k) :=
  sorry

/-! ## (b) Characteristic `p`: the center -/

/-- **(b)** In characteristic `p`, `x^p` is a central element of the Weyl algebra. -/
theorem x_pow_char_mem_center (k : Type*) [Field k] (p : ℕ) [CharP k p] :
    WeylAlgebra.x k ^ p ∈ Subalgebra.center k (WeylAlgebra k) := by
  apply mem_center_of_comm_gen
  · exact (Commute.refl (WeylAlgebra.x k)).pow_left p
  · -- `xᵖ` commutes with `y`: the commutator `(p) • xᵖ⁻¹` vanishes in characteristic `p`.
    cases p with
    | zero => simp
    | succ n =>
      have h := y_mul_x_pow_succ k n
      have hz : (n + 1 : ℕ) • WeylAlgebra.x k ^ n = 0 := by
        rw [← Nat.cast_smul_eq_nsmul (R := k), CharP.cast_eq_zero, zero_smul]
      rw [hz, add_zero] at h
      exact h.symm

/-- **(b)** In characteristic `p`, `y^p` is a central element of the Weyl algebra. -/
theorem y_pow_char_mem_center (k : Type*) [Field k] (p : ℕ) [CharP k p] :
    WeylAlgebra.y k ^ p ∈ Subalgebra.center k (WeylAlgebra k) := by
  apply mem_center_of_comm_gen
  · -- `yᵖ` commutes with `x`: the commutator `(p) • yᵖ⁻¹` vanishes in characteristic `p`.
    cases p with
    | zero => simp
    | succ n =>
      have h := x_mul_y_pow_succ k n
      have hz : (n + 1 : ℕ) • WeylAlgebra.y k ^ n = 0 := by
        rw [← Nat.cast_smul_eq_nsmul (R := k), CharP.cast_eq_zero, zero_smul]
      rw [hz, sub_zero] at h
      exact h.symm
  · exact (Commute.refl (WeylAlgebra.y k)).pow_left p

/-- **(b)** In characteristic `p`, the center of the Weyl algebra is the polynomial subalgebra
`k[x^p, y^p]` generated by `x^p` and `y^p`. -/
theorem center_charP (k : Type*) [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p] :
    Subalgebra.center k (WeylAlgebra k)
      = Algebra.adjoin k {WeylAlgebra.x k ^ p, WeylAlgebra.y k ^ p} :=
  sorry

/-! ## (c) Characteristic `p`: irreducible representations -/

/-- A `k`-submodule of a simple `WeylAlgebra k`-module `V` that is stable under the action of
every algebra element and contains a nonzero vector is all of `V`. This packages the
"nonzero invariant submodule is the whole simple module" step. -/
private lemma mem_of_invariant (k : Type*) [Field k] (V : Type*) [AddCommGroup V] [Module k V]
    [Module (WeylAlgebra k) V] [IsScalarTower k (WeylAlgebra k) V]
    [IsSimpleModule (WeylAlgebra k) V] (Wk : Submodule k V)
    (hstab : ∀ (a : WeylAlgebra k) (z : V), z ∈ Wk → a • z ∈ Wk)
    (hne : ∃ z ∈ Wk, z ≠ 0) : ∀ z : V, z ∈ Wk := by
  let WA : Submodule (WeylAlgebra k) V :=
    { carrier := Wk
      add_mem' := fun ha hb => Wk.add_mem ha hb
      zero_mem' := Wk.zero_mem
      smul_mem' := fun a z hz => hstab a z hz }
  have hbot : WA ≠ ⊥ := by
    obtain ⟨z, hz, hz0⟩ := hne
    intro h
    apply hz0
    have hzWA : z ∈ WA := hz
    rw [h, Submodule.mem_bot] at hzWA
    exact hzWA
  have hWA : WA = ⊤ := (eq_bot_or_eq_top WA).resolve_left hbot
  intro z
  have : z ∈ WA := hWA ▸ Submodule.mem_top
  exact this

/-- A central element of the Weyl algebra acts as a `k`-scalar on a simple finite dimensional
module over an algebraically closed field (Schur's lemma via eigenvalue existence). -/
private lemma central_smul_scalar (k : Type*) [Field k] [IsAlgClosed k] (V : Type*)
    [AddCommGroup V] [Module k V] [Module (WeylAlgebra k) V] [IsScalarTower k (WeylAlgebra k) V]
    [FiniteDimensional k V] [IsSimpleModule (WeylAlgebra k) V]
    (z : WeylAlgebra k) (hz : z ∈ Subalgebra.center k (WeylAlgebra k)) :
    ∃ μ : k, ∀ w : V, z • w = μ • w := by
  haveI : Nontrivial V := IsSimpleModule.nontrivial (WeylAlgebra k) V
  obtain ⟨μ, hμ⟩ := (Algebra.lsmul k k V z).exists_eigenvalue
  refine ⟨μ, ?_⟩
  have hstab : ∀ (a : WeylAlgebra k) (w : V),
      w ∈ Module.End.eigenspace (Algebra.lsmul k k V z) μ →
      a • w ∈ Module.End.eigenspace (Algebra.lsmul k k V z) μ := by
    intro a w hw
    rw [Module.End.mem_eigenspace_iff, Algebra.lsmul_apply] at hw ⊢
    calc z • (a • w) = (a * z) • w := by
              rw [← mul_smul, ← Subalgebra.mem_center_iff.mp hz a]
      _ = a • (z • w) := by rw [mul_smul]
      _ = a • (μ • w) := by rw [hw]
      _ = μ • (a • w) := by rw [smul_comm]
  obtain ⟨w0, hw0⟩ := hμ.exists_hasEigenvector
  have hmem := mem_of_invariant k V (Module.End.eigenspace (Algebra.lsmul k k V z) μ)
    hstab ⟨w0, hw0.1, hw0.2⟩
  intro w
  have hw := hmem w
  rw [Module.End.mem_eigenspace_iff, Algebra.lsmul_apply] at hw
  exact hw

/-- **(c)** In characteristic `p`, over an algebraically closed field, every irreducible finite
dimensional representation of the Weyl algebra has dimension exactly `p`.

The hypothesis `[IsAlgClosed k]` is required: without it the statement is false (over a
non-closed field the Weyl algebra is Azumaya of rank `p²` over its center `k[xᵖ,yᵖ]`, and a
simple module attached to a closed point of residue degree `d` has `k`-dimension `p·d`). The
book (Etingof, Problem 2.7.4(c)) works under the standing convention that `k` is algebraically
closed — the eigenvector of `y` used in the hint exists only then. -/
theorem finrank_irreducible_charP (k : Type*) [Field k] [IsAlgClosed k] (p : ℕ)
    [Fact (Nat.Prime p)] [CharP k p]
    (V : Type*) [AddCommGroup V] [Module k V] [Module (WeylAlgebra k) V]
    [IsScalarTower k (WeylAlgebra k) V] [FiniteDimensional k V]
    [IsSimpleModule (WeylAlgebra k) V] :
    Module.finrank k V = p := by
  haveI : Nontrivial V := IsSimpleModule.nontrivial (WeylAlgebra k) V
  have p_pos : 0 < p := (Fact.out : p.Prime).pos
  have hfac : ∀ m : ℕ, m < p → ((m.factorial : ℕ) : k) ≠ 0 := by
    intro m hm
    rw [ne_eq, CharP.cast_eq_zero_iff k p, Nat.Prime.dvd_factorial Fact.out]
    exact Nat.not_le.mpr hm
  -- Eigenvector `v` of the action of `y`, with eigenvalue `lam`.
  obtain ⟨lam, hlam⟩ := (Algebra.lsmul k k V (WeylAlgebra.y k)).exists_eigenvalue
  obtain ⟨v, hv⟩ := hlam.exists_hasEigenvector
  have hyv : WeylAlgebra.y k • v = lam • v := by
    have h := Module.End.mem_eigenspace_iff.mp hv.1
    rwa [Algebra.lsmul_apply] at h
  have hv0 : v ≠ 0 := hv.2
  set w : ℕ → V := fun i => WeylAlgebra.x k ^ i • v with hwdef
  have hwv : ∀ i, w i = WeylAlgebra.x k ^ i • v := fun _ => rfl
  have hw0 : w 0 = v := by rw [hwv, pow_zero, one_smul]
  -- `xᵖ` acts as a scalar `μ`.
  obtain ⟨μ, hμ⟩ := central_smul_scalar k V (WeylAlgebra.x k ^ p) (x_pow_char_mem_center k p)
  -- The lowering operator `N = ρ(y) - lam`.
  set N : Module.End k V := Algebra.lsmul k k V (WeylAlgebra.y k) - lam • 1 with hN
  have hNstep : ∀ i : ℕ, N (w (i + 1)) = ((i + 1 : ℕ) : k) • w i := by
    intro i
    rw [hwv (i + 1), hN, LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply,
      Algebra.lsmul_apply, ← mul_smul, y_mul_x_pow_succ k i, add_smul, mul_smul, hyv,
      smul_comm (WeylAlgebra.x k ^ (i + 1)) lam v,
      ← Nat.cast_smul_eq_nsmul k (i + 1) (WeylAlgebra.x k ^ i), smul_assoc, hwv i]
    abel
  have hN0 : N (w 0) = 0 := by
    rw [hwv, hN, LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply,
      Algebra.lsmul_apply, pow_zero, one_smul, hyv, sub_self]
  have hkill1 : ∀ i : ℕ, (N ^ (i + 1)) (w i) = 0 := by
    intro i
    induction i with
    | zero => rw [pow_one]; exact hN0
    | succ n ih => rw [pow_succ, Module.End.mul_apply, hNstep, map_smul, ih, smul_zero]
  have hval : ∀ i : ℕ, (N ^ i) (w i) = ((i.factorial : ℕ) : k) • v := by
    intro i
    induction i with
    | zero => rw [pow_zero, Module.End.one_apply, hw0, Nat.factorial_zero, Nat.cast_one, one_smul]
    | succ n ih =>
      rw [pow_succ, Module.End.mul_apply, hNstep, map_smul, ih, smul_smul, ← Nat.cast_mul,
        ← Nat.factorial_succ]
  have hkill_gen : ∀ (m j : ℕ), j < m → (N ^ m) (w j) = 0 := by
    intro m j hjm
    obtain ⟨t, ht⟩ : ∃ t, m = t + (j + 1) := ⟨m - (j + 1), by omega⟩
    rw [ht, pow_add, Module.End.mul_apply, hkill1, map_zero]
  -- The `p` vectors `w 0, …, w (p-1)` are linearly independent.
  have hli : ∀ n : ℕ, n ≤ p → LinearIndependent k (fun i : Fin n => w (i : ℕ)) := by
    intro n
    induction n with
    | zero => intro _; exact linearIndependent_empty_type
    | succ m ih =>
      intro hmp
      have hmp' : m ≤ p := Nat.le_of_succ_le hmp
      have hmlt : m < p := hmp
      have hfun : (fun i : Fin (m + 1) => w (i : ℕ))
          = Fin.snoc (fun i : Fin m => w (i : ℕ)) (w m) := by
        funext i
        induction i using Fin.lastCases with
        | last => simp
        | cast j => simp
      rw [hfun]
      refine (ih hmp').finSnoc ?_
      intro hmem
      have hzero : (N ^ m) (w m) = 0 := by
        have hsub : Submodule.span k (Set.range (fun i : Fin m => w (i : ℕ)))
            ≤ LinearMap.ker (N ^ m) := by
          rw [Submodule.span_le]
          rintro _ ⟨i, rfl⟩
          simp only [SetLike.mem_coe, LinearMap.mem_ker]
          exact hkill_gen m (i : ℕ) i.isLt
        have hk := hsub hmem
        rwa [LinearMap.mem_ker] at hk
      rw [hval m] at hzero
      rcases smul_eq_zero.mp hzero with h | h
      · exact hfac m hmlt h
      · exact hv0 h
  -- The span of the `p` vectors is a nonzero invariant submodule, hence all of `V`.
  set Wk : Submodule k V := Submodule.span k (Set.range (fun i : Fin p => w (i : ℕ))) with hWk
  have hgen_mem : ∀ i : Fin p, w (i : ℕ) ∈ Wk := fun i => Submodule.subset_span ⟨i, rfl⟩
  have hshift : ∀ t : ℕ, w (p + t) = μ • w t := by
    intro t
    rw [hwv (p + t), hwv t, pow_add, mul_smul, hμ (WeylAlgebra.x k ^ t • v)]
  have hall_mem : ∀ j : ℕ, w j ∈ Wk := by
    intro j
    induction j using Nat.strong_induction_on with
    | _ j ih =>
      by_cases hjp : j < p
      · exact hgen_mem ⟨j, hjp⟩
      · obtain ⟨t, ht⟩ : ∃ t, j = p + t := ⟨j - p, by omega⟩
        subst ht
        rw [hshift]
        exact Wk.smul_mem μ (ih t (by omega))
  have hx_stab : ∀ z ∈ Wk, WeylAlgebra.x k • z ∈ Wk := by
    intro z hz
    rw [hWk] at hz
    induction hz using Submodule.span_induction with
    | mem u hu =>
        obtain ⟨i, rfl⟩ := hu
        show WeylAlgebra.x k • w (i : ℕ) ∈ Wk
        rw [hwv, ← mul_smul, ← pow_succ', ← hwv]
        exact hall_mem ((i : ℕ) + 1)
    | zero => rw [smul_zero]; exact Wk.zero_mem
    | add a b _ _ ha hb => rw [smul_add]; exact Wk.add_mem ha hb
    | smul c a _ ha => rw [smul_comm]; exact Wk.smul_mem c ha
  have hy_stab : ∀ z ∈ Wk, WeylAlgebra.y k • z ∈ Wk := by
    intro z hz
    rw [hWk] at hz
    induction hz using Submodule.span_induction with
    | mem u hu =>
        obtain ⟨i, rfl⟩ := hu
        show WeylAlgebra.y k • w (i : ℕ) ∈ Wk
        have hNexp : N (w (i : ℕ)) = WeylAlgebra.y k • w (i : ℕ) - lam • w (i : ℕ) := by
          rw [hN, LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply,
            Algebra.lsmul_apply]
        have hNwi : N (w (i : ℕ)) ∈ Wk := by
          cases hci : (i : ℕ) with
          | zero => rw [hN0]; exact Wk.zero_mem
          | succ j =>
              rw [hNstep]
              exact Wk.smul_mem _ (hall_mem j)
        have key : WeylAlgebra.y k • w (i : ℕ) = N (w (i : ℕ)) + lam • w (i : ℕ) := by
          rw [hNexp]; abel
        rw [key]
        exact Wk.add_mem hNwi (Wk.smul_mem lam (hall_mem (i : ℕ)))
    | zero => rw [smul_zero]; exact Wk.zero_mem
    | add a b _ _ ha hb => rw [smul_add]; exact Wk.add_mem ha hb
    | smul c a _ ha => rw [smul_comm]; exact Wk.smul_mem c ha
  have ha_stab : ∀ (a : WeylAlgebra k) (z : V), z ∈ Wk → a • z ∈ Wk := by
    intro a
    obtain ⟨a', rfl⟩ := RingQuot.mkAlgHom_surjective k (WeylAlgebraRel k) a
    have ha' : a' ∈ Algebra.adjoin k (Set.range (FreeAlgebra.ι k)) := by
      rw [FreeAlgebra.adjoin_range_ι]; exact Algebra.mem_top
    induction ha' using Algebra.adjoin_induction with
    | mem g hg =>
        obtain ⟨idx, rfl⟩ := hg
        intro z hz
        fin_cases idx
        · exact hx_stab z hz
        · exact hy_stab z hz
    | algebraMap r =>
        intro z hz
        rw [AlgHom.commutes, algebraMap_smul]
        exact Wk.smul_mem r hz
    | add p q _ _ ihp ihq =>
        intro z hz
        rw [map_add, add_smul]
        exact Wk.add_mem (ihp z hz) (ihq z hz)
    | mul p q _ _ ihp ihq =>
        intro z hz
        rw [map_mul, mul_smul]
        exact ihp _ (ihq z hz)
  have hspan_top : ∀ z : V, z ∈ Wk :=
    mem_of_invariant k V Wk ha_stab ⟨v, hw0 ▸ hgen_mem ⟨0, p_pos⟩, hv0⟩
  have hsp : ⊤ ≤ Submodule.span k (Set.range (fun i : Fin p => w (i : ℕ))) := by
    rw [← hWk]; intro z _; exact hspan_top z
  have hli_p : LinearIndependent k (fun i : Fin p => w (i : ℕ)) := hli p le_rfl
  rw [Module.finrank_eq_card_basis (Module.Basis.mk hli_p hsp), Fintype.card_fin]

end Etingof.Problem2_7_4
