import Mathlib
import EtingofRepresentationTheory.Chapter2.Definition2_3_8

/-!
# Problem 2.5.2: Cyclic vectors and cyclic representations

Let `V ≠ 0` be a representation of `A`. A vector `v ∈ V` is **cyclic** if it generates `V`, i.e.
`Av = V`. A representation admitting a cyclic vector is **cyclic**. The problem asks to show:

* **(a)** `V` is irreducible if and only if all nonzero vectors of `V` are cyclic.
* **(b)** `V` is cyclic if and only if it is isomorphic to `A/I`, where `I` is a left ideal in `A`.
* **(c)** Give an example of an indecomposable representation which is not cyclic.

## Formalization

A vector `v` is cyclic when `Submodule.span A {v} = ⊤` (the `A`-submodule it generates is all of
`V`). Irreducibility is `IsSimpleModule A V`. Left ideals of `A` are `Submodule A A`, and `A/I` is
the quotient module.

Parts (a) and (b) are proved sorry-free below, as `irreducible_iff_forall_cyclic` and
`cyclic_iff_isoQuotient` respectively. Part (c) — the explicit example
`A = ℂ[x, y]/I₂` acting on `V = A^*` by `(ρ(a)f)(b) = f(ba)` — requires constructing the coregular
module structure and is deferred to a dedicated follow-up item.
-/

namespace Etingof.Problem2_5_2

variable {A : Type*} [Ring A]

/-- **Problem 2.5.2(a).** A nonzero representation `V` is irreducible if and only if every nonzero
vector of `V` is cyclic (generates `V`). -/
theorem irreducible_iff_forall_cyclic (V : Type*) [AddCommGroup V] [Module A V] [Nontrivial V] :
    IsSimpleModule A V ↔ ∀ v : V, v ≠ 0 → Submodule.span A {v} = ⊤ := by
  constructor
  · -- A simple module: any nonzero `v` spans a nonzero submodule, hence all of `V`.
    intro h v hv
    rcases h.eq_bot_or_eq_top (Submodule.span A {v}) with hbot | htop
    · exfalso
      have hmem : v ∈ Submodule.span A {v} := Submodule.mem_span_singleton_self v
      rw [hbot, Submodule.mem_bot] at hmem
      exact hv hmem
    · exact htop
  · -- Every nonzero submodule contains a nonzero vector, whose span is `⊤`; so it is `⊤`.
    intro h
    exact
      { eq_bot_or_eq_top := fun p => by
          rcases eq_or_ne p ⊥ with hp | hp
          · exact Or.inl hp
          · refine Or.inr ?_
            obtain ⟨v, hvp, hv0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hp
            have hspan : Submodule.span A {v} = ⊤ := h v hv0
            have hle : Submodule.span A {v} ≤ p :=
              Submodule.span_le.mpr (Set.singleton_subset_iff.mpr hvp)
            rw [hspan] at hle
            exact top_le_iff.mp hle }

/-- **Problem 2.5.2(b).** A nonzero representation `V` is cyclic (admits a cyclic vector) if and
only if it is isomorphic to `A/I` for some left ideal `I` of `A`. -/
theorem cyclic_iff_isoQuotient (V : Type*) [AddCommGroup V] [Module A V] [Nontrivial V] :
    (∃ v : V, Submodule.span A {v} = ⊤) ↔
      ∃ I : Submodule A A, Nonempty (V ≃ₗ[A] (A ⧸ I)) := by
  constructor
  · -- A cyclic vector `v` makes `a ↦ a • v` a surjection `A → V`; quotient by its kernel.
    rintro ⟨v, hv⟩
    set f := LinearMap.toSpanSingleton A V v with hf
    have hrange : LinearMap.range f = ⊤ := by
      rw [hf, ← LinearMap.span_singleton_eq_range]; exact hv
    have hsurj : Function.Surjective f := LinearMap.range_eq_top.mp hrange
    exact ⟨LinearMap.ker f, ⟨(LinearMap.quotKerEquivOfSurjective f hsurj).symm⟩⟩
  · -- `A/I` is cyclic (generated by the class of `1`); transport along the equivalence.
    rintro ⟨I, ⟨e⟩⟩
    have h1 : Submodule.span A {(I.mkQ 1 : A ⧸ I)} = ⊤ := by
      rw [eq_top_iff]
      intro x _
      obtain ⟨a, rfl⟩ := I.mkQ_surjective x
      rw [Submodule.mem_span_singleton]
      refine ⟨a, ?_⟩
      rw [← map_smul]; congr 1; simp
    refine ⟨e.symm (I.mkQ 1), ?_⟩
    have hmap : Submodule.span A {e.symm (I.mkQ 1)}
        = Submodule.map e.symm.toLinearMap (Submodule.span A {I.mkQ 1}) := by
      rw [Submodule.map_span]; simp
    rw [hmap, h1, Submodule.map_top]
    exact LinearMap.range_eq_top.mpr e.symm.surjective

end Etingof.Problem2_5_2
