import EtingofRepresentationTheory.Chapter2.Proposition2_7_1
import Mathlib.RingTheory.SimpleRing.Basic
import Mathlib.RingTheory.SimpleModule.Basic
import Mathlib.Algebra.Algebra.Subalgebra.Basic
import Mathlib.Algebra.CharP.Basic
import Mathlib.LinearAlgebra.FiniteDimensional.Defs

/-!
# Problem 2.7.4: Representations and ideals of the Weyl algebra

Let `A` be the Weyl algebra (`Etingof.WeylAlgebra k`, generated by `x, y` with `yx = xy + 1`).

* **(a)** In characteristic `0`: the only finite dimensional representation of `A` is the zero
  representation, and the only two-sided ideals of `A` are `0` and `A` (i.e. `A` is simple).
  (The obstruction to a nonzero finite dimensional module is `Tr(ρ(x)ρ(y) - ρ(y)ρ(x)) = 0`
  versus `Tr(ρ(1)) = dim V`, which forces `dim V = 0` in characteristic `0`.)

* **(b)** In characteristic `p`: `x^p` and `y^p` are central, and the center of `A` is the
  polynomial subalgebra `k[x^p, y^p]`.

* **(c)** In characteristic `p`: every irreducible finite dimensional representation of `A` has
  dimension exactly `p`.

We render the book's *answers* as the statements (spec); proofs are deferred.
-/

namespace Etingof.Problem2_7_4

open Etingof

/-! ## (a) Characteristic zero -/

/-- **(a)** In characteristic `0`, the Weyl algebra has no nonzero finite dimensional
representation: any finite dimensional `A`-module (as a `k`-vector space) is zero. -/
theorem finrank_eq_zero_of_charZero (k : Type*) [Field k] [CharZero k]
    (V : Type*) [AddCommGroup V] [Module k V] [Module (WeylAlgebra k) V]
    [IsScalarTower k (WeylAlgebra k) V] [FiniteDimensional k V] :
    Module.finrank k V = 0 :=
  sorry

/-- **(a)** In characteristic `0`, the Weyl algebra is a simple ring: its only two-sided ideals
are `0` and the whole algebra. -/
theorem isSimpleRing_charZero (k : Type*) [Field k] [CharZero k] :
    IsSimpleRing (WeylAlgebra k) :=
  sorry

/-! ## (b) Characteristic `p`: the center -/

/-- **(b)** In characteristic `p`, `x^p` is a central element of the Weyl algebra. -/
theorem x_pow_char_mem_center (k : Type*) [Field k] (p : ℕ) [CharP k p] :
    WeylAlgebra.x k ^ p ∈ Subalgebra.center k (WeylAlgebra k) :=
  sorry

/-- **(b)** In characteristic `p`, `y^p` is a central element of the Weyl algebra. -/
theorem y_pow_char_mem_center (k : Type*) [Field k] (p : ℕ) [CharP k p] :
    WeylAlgebra.y k ^ p ∈ Subalgebra.center k (WeylAlgebra k) :=
  sorry

/-- **(b)** In characteristic `p`, the center of the Weyl algebra is the polynomial subalgebra
`k[x^p, y^p]` generated by `x^p` and `y^p`. -/
theorem center_charP (k : Type*) [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p] :
    Subalgebra.center k (WeylAlgebra k)
      = Algebra.adjoin k {WeylAlgebra.x k ^ p, WeylAlgebra.y k ^ p} :=
  sorry

/-! ## (c) Characteristic `p`: irreducible representations -/

/-- **(c)** In characteristic `p`, every irreducible finite dimensional representation of the Weyl
algebra has dimension exactly `p`. -/
theorem finrank_irreducible_charP (k : Type*) [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p]
    (V : Type*) [AddCommGroup V] [Module k V] [Module (WeylAlgebra k) V]
    [IsScalarTower k (WeylAlgebra k) V] [FiniteDimensional k V]
    [IsSimpleModule (WeylAlgebra k) V] :
    Module.finrank k V = p :=
  sorry

end Etingof.Problem2_7_4
