import Mathlib.LinearAlgebra.Finsupp.LinearCombination
import Mathlib.LinearAlgebra.Basis.Basic
import Mathlib.LinearAlgebra.Finsupp.Defs
import Mathlib.Algebra.Algebra.Subalgebra.Basic

/-!
# Proposition 2.7.1 (ii): Basis for the q-Weyl algebra

(ii) A basis for the `q`-Weyl algebra `A_q` is `{xⁱyʲ, i, j ∈ ℤ}`.

The `q`-Weyl algebra `A_q` (Discussion 2.7) is the algebra generated by
`x, x⁻¹, y, y⁻¹` with defining relations `yx = qxy` and
`xx⁻¹ = x⁻¹x = yy⁻¹ = y⁻¹y = 1`, where `q ∈ kˣ` is a fixed invertible scalar.
This is the *quantum torus* (quantum `2`-torus).

## Formalization

We realize `A_q` concretely as its (faithful) **left-regular representation** on the
free `k`-module `M = (ℤ × ℤ) →₀ k`. Writing `b(m,n) = single (m,n) 1` for the standard
basis of `M`, the monomial `xⁱyʲ` acts by

  `xⁱyʲ · b(m,n) = q^{j·m} · b(m+i, n+j)`.

This action is faithful for *every* `q` (including roots of unity), so the subalgebra
`A_q := adjoin k {x, x⁻¹, y, y⁻¹} ⊆ End_k M` is genuinely the `q`-Weyl algebra, and the
operators `qMono (i,j)` realizing `xⁱyʲ` form a `k`-basis of it.

The book's proof ("any word can be ordered at the cost of a power of `q`") is captured by
the reordering identity `qMono_mul`:

  `qMono (i,j) * qMono (i',j') = q^{j·i'} • qMono (i+i', j+j')`,

which gives both the spanning property and (via evaluation at `b(0,0)`) the linear
independence.

## Mathlib correspondence

No direct match. The `q`-Weyl algebra / quantum torus is not in Mathlib.
-/

namespace Etingof

open Finsupp

variable (k : Type*) [CommRing k] (q : kˣ)

/-- The underlying free `k`-module `M = (ℤ × ℤ) →₀ k` carrying the regular representation
of the `q`-Weyl algebra. Its standard basis vector `single (m, n) 1` is written `b(m,n)`. -/
abbrev QWeylModule : Type _ := (ℤ × ℤ) →₀ k

/-- The operator realizing the monomial `xⁱyʲ` (`i = p.1`, `j = p.2`) in the regular
representation of the `q`-Weyl algebra on `M = (ℤ × ℤ) →₀ k`. It sends the basis vector
`b(m,n) = single (m,n) 1` to `q^{j·m} · b(m+i, n+j)`. -/
noncomputable def qMono (p : ℤ × ℤ) : Module.End k (QWeylModule k) :=
  Finsupp.lsum k fun mn : ℤ × ℤ =>
    (↑(q ^ (p.2 * mn.1)) : k) • Finsupp.lsingle (mn.1 + p.1, mn.2 + p.2)

/-- The defining action of `qMono` on a basis element:
`xⁱyʲ · (c · b(m,n)) = (q^{j·m} c) · b(m+i, n+j)`. -/
theorem qMono_single (p : ℤ × ℤ) (m n : ℤ) (c : k) :
    qMono k q p (Finsupp.single (m, n) c) =
      Finsupp.single (m + p.1, n + p.2) ((↑(q ^ (p.2 * m)) : k) * c) := by
  rw [qMono, Finsupp.lsum_single]
  simp [Finsupp.smul_single, smul_eq_mul]

/-- The identity monomial `x⁰y⁰` acts as the identity. -/
@[simp] theorem qMono_zero : qMono k q (0, 0) = 1 := by
  apply Finsupp.lhom_ext
  intro a c
  obtain ⟨m, n⟩ := a
  rw [qMono_single]
  simp

/-- **Reordering identity** (the heart of Proposition 2.7.1 (ii)):
`xⁱyʲ · xⁱ'yʲ' = q^{j·i'} · x^{i+i'} y^{j+j'}`. This is the formal content of "any word in
`x, x⁻¹, y, y⁻¹` can be ordered at the cost of multiplying by a power of `q`". -/
theorem qMono_mul (p p' : ℤ × ℤ) :
    qMono k q p * qMono k q p' =
      (↑(q ^ (p.2 * p'.1)) : k) • qMono k q (p.1 + p'.1, p.2 + p'.2) := by
  apply Finsupp.lhom_ext
  intro a c
  obtain ⟨m, n⟩ := a
  rw [Module.End.mul_apply, qMono_single, qMono_single, LinearMap.smul_apply,
    qMono_single, Finsupp.smul_single]
  congr 1
  · ext <;> simp <;> ring
  · -- scalar: q^{j(m+i')} * q^{j'm} * c  =  q^{j i'} * (q^{(j+j')m} * c)
    dsimp only
    have hL : (q ^ (p.2 * (m + p'.1)) * q ^ (p'.2 * m) : kˣ) =
        q ^ (p.2 * m + p.2 * p'.1 + p'.2 * m) := by rw [← zpow_add]; congr 1; ring
    have hR : (q ^ (p.2 * p'.1) * q ^ ((p.2 + p'.2) * m) : kˣ) =
        q ^ (p.2 * m + p.2 * p'.1 + p'.2 * m) := by rw [← zpow_add]; congr 1; ring
    simp only [smul_eq_mul, ← mul_assoc, ← Units.val_mul]
    rw [hL, hR]
