import Mathlib.LinearAlgebra.Finsupp.LinearCombination
import Mathlib.LinearAlgebra.Basis.Basic
import Mathlib.LinearAlgebra.Finsupp.Defs
import Mathlib.LinearAlgebra.Finsupp.VectorSpace
import Mathlib.Algebra.Algebra.Subalgebra.Basic
import Mathlib.RingTheory.Adjoin.Basic

/-!
# Proposition 2.7.1 (ii): Basis for the q-Weyl algebra

(ii) A basis for the `q`-Weyl algebra `A_q` is `{xⁱyʲ, i, j ∈ ℤ}`.

The `q`-Weyl algebra `A_q` (Discussion 2.7) is the algebra generated by
`x, x⁻¹, y, y⁻¹` with defining relations `yx = qxy` and
`xx⁻¹ = x⁻¹x = yy⁻¹ = y⁻¹y = 1`, where `q ∈ kˣ` is a fixed invertible scalar.
This is the *quantum torus* (quantum `2`-torus).

## Formalization

We realize `A_q` concretely as its (faithful) **left-regular representation** on the
free `k`-module `M = (ℤ × ℤ) →₀ k`. Writing `b(m,n) = single (m,n) 1` for the standard
basis of `M`, the monomial `xⁱyʲ` acts by

  `xⁱyʲ · b(m,n) = q^{j·m} · b(m+i, n+j)`.

This action is faithful for *every* `q` (including roots of unity), so the subalgebra
`A_q := adjoin k {x, x⁻¹, y, y⁻¹} ⊆ End_k M` is genuinely the `q`-Weyl algebra, and the
operators `qMono (i,j)` realizing `xⁱyʲ` form a `k`-basis of it.

The book's proof ("any word can be ordered at the cost of a power of `q`") is captured by
the reordering identity `qMono_mul`:

  `qMono (i,j) * qMono (i',j') = q^{j·i'} • qMono (i+i', j+j')`,

which gives both the spanning property and (via evaluation at `b(0,0)`) the linear
independence.

## Mathlib correspondence

No direct match. The `q`-Weyl algebra / quantum torus is not in Mathlib.
-/

namespace Etingof

open Finsupp

variable (k : Type*) [CommRing k] (q : kˣ)

/-- The underlying free `k`-module `M = (ℤ × ℤ) →₀ k` carrying the regular representation
of the `q`-Weyl algebra. Its standard basis vector `single (m, n) 1` is written `b(m,n)`. -/
abbrev QWeylModule : Type _ := (ℤ × ℤ) →₀ k

/-- The operator realizing the monomial `xⁱyʲ` (`i = p.1`, `j = p.2`) in the regular
representation of the `q`-Weyl algebra on `M = (ℤ × ℤ) →₀ k`. It sends the basis vector
`b(m,n) = single (m,n) 1` to `q^{j·m} · b(m+i, n+j)`. -/
noncomputable def qMono (p : ℤ × ℤ) : Module.End k (QWeylModule k) :=
  Finsupp.lsum k fun mn : ℤ × ℤ =>
    (↑(q ^ (p.2 * mn.1)) : k) • Finsupp.lsingle (mn.1 + p.1, mn.2 + p.2)

/-- The defining action of `qMono` on a basis element:
`xⁱyʲ · (c · b(m,n)) = (q^{j·m} c) · b(m+i, n+j)`. -/
theorem qMono_single (p : ℤ × ℤ) (m n : ℤ) (c : k) :
    qMono k q p (Finsupp.single (m, n) c) =
      Finsupp.single (m + p.1, n + p.2) ((↑(q ^ (p.2 * m)) : k) * c) := by
  rw [qMono, Finsupp.lsum_single]
  simp [Finsupp.smul_single, smul_eq_mul]

/-- The identity monomial `x⁰y⁰` acts as the identity. -/
@[simp] theorem qMono_zero : qMono k q (0, 0) = 1 := by
  apply Finsupp.lhom_ext
  intro a c
  obtain ⟨m, n⟩ := a
  rw [qMono_single]
  simp

/-- **Reordering identity** (the heart of Proposition 2.7.1 (ii)):
`xⁱyʲ · xⁱ'yʲ' = q^{j·i'} · x^{i+i'} y^{j+j'}`. This is the formal content of "any word in
`x, x⁻¹, y, y⁻¹` can be ordered at the cost of multiplying by a power of `q`". -/
theorem qMono_mul (p p' : ℤ × ℤ) :
    qMono k q p * qMono k q p' =
      (↑(q ^ (p.2 * p'.1)) : k) • qMono k q (p.1 + p'.1, p.2 + p'.2) := by
  apply Finsupp.lhom_ext
  intro a c
  obtain ⟨m, n⟩ := a
  rw [Module.End.mul_apply, qMono_single, qMono_single, LinearMap.smul_apply,
    qMono_single, Finsupp.smul_single]
  congr 1
  · ext <;> simp <;> ring
  · -- scalar: q^{j(m+i')} * q^{j'm} * c  =  q^{j i'} * (q^{(j+j')m} * c)
    dsimp only
    have hL : (q ^ (p.2 * (m + p'.1)) * q ^ (p'.2 * m) : kˣ) =
        q ^ (p.2 * m + p.2 * p'.1 + p'.2 * m) := by rw [← zpow_add]; congr 1; ring
    have hR : (q ^ (p.2 * p'.1) * q ^ ((p.2 + p'.2) * m) : kˣ) =
        q ^ (p.2 * m + p.2 * p'.1 + p'.2 * m) := by rw [← zpow_add]; congr 1; ring
    simp only [smul_eq_mul, ← mul_assoc, ← Units.val_mul]
    rw [hL, hR]

/-- The `q`-Weyl algebra `A_q`, realized concretely as the subalgebra of `End_k M`
generated by the operators `x = qMono (1,0)`, `x⁻¹ = qMono (-1,0)`, `y = qMono (0,1)`,
`y⁻¹ = qMono (0,-1)`. Since the regular representation on `M` is faithful, this is genuinely
the `q`-Weyl algebra (quantum torus). -/
noncomputable def qWeylAlgebra : Subalgebra k (Module.End k (QWeylModule k)) :=
  Algebra.adjoin k
    {qMono k q (1, 0), qMono k q (-1, 0), qMono k q (0, 1), qMono k q (0, -1)}

/-- The defining relation of the `q`-Weyl algebra: `yx = q · xy`. -/
theorem qMono_relation_yx :
    qMono k q (0, 1) * qMono k q (1, 0) =
      (↑q : k) • (qMono k q (1, 0) * qMono k q (0, 1)) := by
  rw [qMono_mul, qMono_mul]
  simp

/-- The defining relation `xx⁻¹ = 1`. -/
theorem qMono_x_mul_inv : qMono k q (1, 0) * qMono k q (-1, 0) = 1 := by
  rw [qMono_mul]; simp

/-- The defining relation `x⁻¹x = 1`. -/
theorem qMono_inv_mul_x : qMono k q (-1, 0) * qMono k q (1, 0) = 1 := by
  rw [qMono_mul]; simp

/-- The defining relation `yy⁻¹ = 1`. -/
theorem qMono_y_mul_inv : qMono k q (0, 1) * qMono k q (0, -1) = 1 := by
  rw [qMono_mul]; simp

/-- The defining relation `y⁻¹y = 1`. -/
theorem qMono_inv_mul_y : qMono k q (0, -1) * qMono k q (0, 1) = 1 := by
  rw [qMono_mul]; simp

/-- Every monomial `xⁱyʲ` lies in the `q`-Weyl algebra. Proved by reaching `(i, j)` from the
identity `(0, 0)` by repeatedly multiplying by the four generators (a 2-dimensional integer
induction). -/
theorem qMono_mem (p : ℤ × ℤ) : qMono k q p ∈ qWeylAlgebra k q := by
  obtain ⟨i, j⟩ := p
  have hx : qMono k q (1, 0) ∈ qWeylAlgebra k q :=
    Algebra.subset_adjoin (by simp)
  have hx' : qMono k q (-1, 0) ∈ qWeylAlgebra k q :=
    Algebra.subset_adjoin (by simp)
  have hy : qMono k q (0, 1) ∈ qWeylAlgebra k q :=
    Algebra.subset_adjoin (by simp)
  have hy' : qMono k q (0, -1) ∈ qWeylAlgebra k q :=
    Algebra.subset_adjoin (by simp)
  -- First reach the row `(i, 0)`, then move along `j`.
  suffices h0 : ∀ a : ℤ, qMono k q (a, 0) ∈ qWeylAlgebra k q by
    induction j using Int.induction_on with
    | zero => simpa using h0 i
    | succ n ih =>
        have hrec : qMono k q (i, (n : ℤ) + 1) = qMono k q (i, (n : ℤ)) * qMono k q (0, 1) := by
          rw [qMono_mul]; simp
        rw [hrec]; exact mul_mem ih hy
    | pred n ih =>
        have hrec : qMono k q (i, -(n : ℤ) - 1) = qMono k q (i, -(n : ℤ)) * qMono k q (0, -1) := by
          rw [qMono_mul]; simp; ring_nf
        rw [hrec]; exact mul_mem ih hy'
  intro a
  induction a using Int.induction_on with
  | zero => simp only [qMono_zero]; exact one_mem (qWeylAlgebra k q)
  | succ n ih =>
      have hrec : qMono k q ((n : ℤ) + 1, 0) = qMono k q (1, 0) * qMono k q ((n : ℤ), 0) := by
        rw [qMono_mul]; simp [add_comm]
      rw [hrec]; exact mul_mem hx ih
  | pred n ih =>
      have hrec : qMono k q (-(n : ℤ) - 1, 0) = qMono k q (-1, 0) * qMono k q (-(n : ℤ), 0) := by
        rw [qMono_mul]; simp; ring_nf
      rw [hrec]; exact mul_mem hx' ih

/-- The `k`-span of the monomials is closed under multiplication (via `qMono_mul`). -/
private theorem qspan_mul_mem {a b : Module.End k (QWeylModule k)}
    (ha : a ∈ Submodule.span k (Set.range (qMono k q)))
    (hb : b ∈ Submodule.span k (Set.range (qMono k q))) :
    a * b ∈ Submodule.span k (Set.range (qMono k q)) := by
  apply Submodule.span_induction
    (p := fun b (_ : b ∈ Submodule.span k (Set.range (qMono k q))) =>
      a * b ∈ Submodule.span k (Set.range (qMono k q)))
  · rintro x ⟨p', rfl⟩
    apply Submodule.span_induction
      (p := fun a (_ : a ∈ Submodule.span k (Set.range (qMono k q))) =>
        a * qMono k q p' ∈ Submodule.span k (Set.range (qMono k q)))
    · rintro y ⟨p, rfl⟩
      rw [qMono_mul]
      exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨_, rfl⟩)
    · rw [zero_mul]; exact Submodule.zero_mem _
    · intro u v _ _ hu hv; rw [add_mul]; exact Submodule.add_mem _ hu hv
    · intro c u _ hu; rw [smul_mul_assoc]; exact Submodule.smul_mem _ c hu
    · exact ha
  · rw [mul_zero]; exact Submodule.zero_mem _
  · intro u v _ _ hu hv; rw [mul_add]; exact Submodule.add_mem _ hu hv
  · intro c u _ hu; rw [mul_smul_comm]; exact Submodule.smul_mem _ c hu
  · exact hb

/-- The monomials `xⁱyʲ` span exactly the `q`-Weyl algebra as a `k`-submodule. -/
theorem qWeyl_toSubmodule_eq_span :
    (qWeylAlgebra k q).toSubmodule = Submodule.span k (Set.range (qMono k q)) := by
  apply le_antisymm
  · intro a ha
    rw [Subalgebra.mem_toSubmodule] at ha
    replace ha : a ∈ Algebra.adjoin k
        ({qMono k q (1, 0), qMono k q (-1, 0), qMono k q (0, 1), qMono k q (0, -1)} :
          Set (Module.End k (QWeylModule k))) := ha
    induction ha using Algebra.adjoin_induction with
    | mem x hx =>
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
        rcases hx with rfl | rfl | rfl | rfl <;>
          exact Submodule.subset_span ⟨_, rfl⟩
    | algebraMap r =>
        rw [Algebra.algebraMap_eq_smul_one, ← qMono_zero k q]
        exact Submodule.smul_mem _ r (Submodule.subset_span ⟨_, rfl⟩)
    | add x y _ _ ihx ihy => exact Submodule.add_mem _ ihx ihy
    | mul x y _ _ ihx ihy => exact qspan_mul_mem k q ihx ihy
  · rw [Submodule.span_le]
    rintro a ⟨p, rfl⟩
    rw [SetLike.mem_coe, Subalgebra.mem_toSubmodule]
    exact qMono_mem k q p

/-- The monomials `xⁱyʲ` are linearly independent over `k`: evaluating a vanishing linear
combination at the basis vector `b(0,0) = single (0,0) 1` sends `xⁱyʲ ↦ b(i,j)`, and the
`b(i,j)` are independent. This works for *every* `q` (no characteristic or root-of-unity
hypothesis). -/
theorem qMono_linearIndependent : LinearIndependent k (qMono k q) := by
  have hsingle : (fun p : ℤ × ℤ => qMono k q p (Finsupp.single (0, 0) 1)) =
      fun p : ℤ × ℤ => Finsupp.single p 1 := by
    funext p
    obtain ⟨i, j⟩ := p
    rw [qMono_single]; simp
  have hev : LinearIndependent k (fun p : ℤ × ℤ => qMono k q p (Finsupp.single (0, 0) 1)) := by
    rw [hsingle]
    have := (Finsupp.basisSingleOne (ι := ℤ × ℤ) (R := k)).linearIndependent
    rwa [Finsupp.coe_basisSingleOne] at this
  exact hev.of_comp (LinearMap.applyₗ (Finsupp.single (0, 0) 1))

/-- **Proposition 2.7.1 (ii)**: The monomials `{xⁱyʲ : i, j ∈ ℤ}` form a `k`-basis for the
`q`-Weyl algebra `A_q` (the quantum torus). Concretely, the family `qMono : ℤ × ℤ → End_k M`
realizing `xⁱyʲ` is linearly independent and spans exactly `A_q`. -/
theorem Proposition_2_7_1_ii :
    LinearIndependent k (qMono k q) ∧
    (qWeylAlgebra k q).toSubmodule = Submodule.span k (Set.range (qMono k q)) :=
  ⟨qMono_linearIndependent k q, qWeyl_toSubmodule_eq_span k q⟩

end Etingof
