import Mathlib.GroupTheory.FreeAbelianGroup
import Mathlib.GroupTheory.QuotientGroup.Basic
import Mathlib.Algebra.Module.Opposite
import Mathlib.Tactic.Abel

/-!
# Remark 2.11.4: Tensor product over an arbitrary ring

Etingof Remark 2.11.4 notes that the construction of the tensor product
(Definition 2.11.1) generalizes verbatim to the tensor product `V ⊗_A W`, where
`A` is *any* ring (not necessarily commutative), `V` is a right `A`-module, and
`W` is a left `A`-module. Concretely, `V ⊗_A W` is the abelian group obtained as
the quotient of the free abelian group on the formal symbols `v ⊗ w`
(`v ∈ V`, `w ∈ W`) by the subgroup generated by the bilinearity relations
together with the **balancing relation**

```
v a ⊗ w - v ⊗ a w,    a ∈ A.
```

## Mathlib correspondence

There is **no** corresponding construction in Mathlib: `TensorProduct R M N`
requires `R` to be a `CommSemiring`, so the balanced tensor product of a right
module and a left module over a noncommutative ring is genuinely missing. We
build it here directly from the book's description as a quotient of a free
abelian group.

We follow Mathlib's convention that a *right* `A`-module is a left module over
the opposite ring `Aᵐᵒᵖ`, so the right action `v a` is written
`MulOpposite.op a • v`.
-/

namespace Etingof

open MulOpposite

/-- The defining relations for the tensor product `V ⊗_A W` of a right `A`-module
`V` and a left `A`-module `W` (Etingof Remark 2.11.4): additivity in each
variable together with the balancing relation `v a ⊗ w = v ⊗ a w`. -/
def tensorRelations (A : Type*) [Ring A]
    (V : Type*) [AddCommGroup V] [Module Aᵐᵒᵖ V]
    (W : Type*) [AddCommGroup W] [Module A W] :
    Set (FreeAbelianGroup (V × W)) :=
  {x |
    (∃ (v₁ : V) (v₂ : V) (w : W), x = FreeAbelianGroup.of (v₁ + v₂, w)
        - FreeAbelianGroup.of (v₁, w) - FreeAbelianGroup.of (v₂, w)) ∨
    (∃ (v : V) (w₁ : W) (w₂ : W), x = FreeAbelianGroup.of (v, w₁ + w₂)
        - FreeAbelianGroup.of (v, w₁) - FreeAbelianGroup.of (v, w₂)) ∨
    (∃ (v : V) (a : A) (w : W), x = FreeAbelianGroup.of (op a • v, w)
        - FreeAbelianGroup.of (v, a • w))}

/-- The **tensor product over a ring** `V ⊗_A W` of a right `A`-module `V` and a
left `A`-module `W`, for an arbitrary (possibly noncommutative) ring `A`
(Etingof Remark 2.11.4): the quotient of the free abelian group on the formal
symbols `v ⊗ w` by the subgroup generated by `tensorRelations`. -/
def TensorProductOverRing (A : Type*) [Ring A]
    (V : Type*) [AddCommGroup V] [Module Aᵐᵒᵖ V]
    (W : Type*) [AddCommGroup W] [Module A W] : Type _ :=
  FreeAbelianGroup (V × W) ⧸ AddSubgroup.closure (tensorRelations A V W)

namespace TensorProductOverRing

variable (A : Type*) [Ring A]
    (V : Type*) [AddCommGroup V] [Module Aᵐᵒᵖ V]
    (W : Type*) [AddCommGroup W] [Module A W]

instance : AddCommGroup (TensorProductOverRing A V W) :=
  QuotientAddGroup.Quotient.addCommGroup _

variable {V W}

/-- The canonical "elementary tensor" `v ⊗ w`, i.e. the class of the generator
`FreeAbelianGroup.of (v, w)` in the quotient. -/
def tmul (v : V) (w : W) : TensorProductOverRing A V W :=
  QuotientAddGroup.mk (FreeAbelianGroup.of (v, w))

/-- Additivity in the left variable: `(v₁ + v₂) ⊗ w = v₁ ⊗ w + v₂ ⊗ w`. -/
theorem add_tmul (v₁ v₂ : V) (w : W) :
    tmul A (v₁ + v₂) w = tmul A v₁ w + tmul A v₂ w := by
  rw [tmul, tmul, tmul, ← QuotientAddGroup.mk_add,
    QuotientAddGroup.eq_iff_sub_mem]
  refine AddSubgroup.subset_closure (Or.inl ⟨v₁, v₂, w, ?_⟩)
  abel

/-- Additivity in the right variable: `v ⊗ (w₁ + w₂) = v ⊗ w₁ + v ⊗ w₂`. -/
theorem tmul_add (v : V) (w₁ w₂ : W) :
    tmul A v (w₁ + w₂) = tmul A v w₁ + tmul A v w₂ := by
  rw [tmul, tmul, tmul, ← QuotientAddGroup.mk_add,
    QuotientAddGroup.eq_iff_sub_mem]
  refine AddSubgroup.subset_closure (Or.inr (Or.inl ⟨v, w₁, w₂, ?_⟩))
  abel

/-- The **balancing relation**: `v a ⊗ w = v ⊗ a w` for every `a ∈ A`.
Here `v a` is the right action `op a • v`. -/
theorem smul_tmul (v : V) (a : A) (w : W) :
    tmul A (op a • v) w = tmul A v (a • w) := by
  rw [tmul, tmul, QuotientAddGroup.eq_iff_sub_mem]
  exact AddSubgroup.subset_closure (Or.inr (Or.inr ⟨v, a, w, rfl⟩))

end TensorProductOverRing

end Etingof
