import EtingofRepresentationTheory.Chapter2.Proposition2_7_1

/-!
# Remark 2.7.2: the Weyl algebra as polynomial differential operators in one variable

Remark 2.7.2 records an observation made inside the proof of Proposition 2.7.1(i): the Weyl
algebra `A` can be **viewed as the algebra of polynomial differential operators in one variable
`t`**, i.e. the subalgebra of `End_k(k[t])` generated by multiplication-by-`t` and `d/dt`.

We make this precise.

* `polyDiffOp k` is the *algebra of polynomial differential operators on `k[t]`*: the subalgebra
  of `End_k(k[t])` generated by `{polyMulX, derivative}` (multiplication by `t` and `d/dt`).

* `WeylAlgebra.polyRep_range_eq_polyDiffOp` shows, in any characteristic, that the image of the
  polynomial representation `polyRep : A →ₐ[k] End_k(k[t])` is exactly `polyDiffOp k`. So the
  Weyl algebra *surjects* onto the algebra of polynomial differential operators, the two
  generators `x, y` mapping to multiplication-by-`t` and `d/dt`.

* `WeylAlgebra.equivPolyDiffOp` upgrades this to an **algebra isomorphism**
  `A ≃ₐ[k] polyDiffOp k` whenever `polyRep` is faithful (characteristic zero with no zero
  divisors, `WeylAlgebra.polyRep_injective`). This is the precise sense in which "the Weyl
  algebra can be viewed as the algebra of polynomial differential operators in one variable".

The faithfulness in arbitrary characteristic is handled separately by the module
`E = tᵃ k[a][t, t⁻¹]` (`FaithfulWeylModule.lean`); over `k[t]` itself faithfulness genuinely
requires characteristic zero, since `(d/dt)^p = 0` in characteristic `p`.
-/

namespace Etingof

open Polynomial

variable (k : Type*) [CommRing k]

/-- The Weyl algebra `A` is generated as a `k`-algebra by its two generators `x` and `y`. -/
theorem WeylAlgebra.adjoin_x_y_eq_top :
    Algebra.adjoin k {WeylAlgebra.x k, WeylAlgebra.y k} = ⊤ := by
  rw [eq_top_iff]
  -- It suffices to contain every standard monomial `xⁱyʲ`, since those span `A`.
  have hsub :
      Submodule.span k (Set.range (fun p : ℕ × ℕ => WeylAlgebra.monomial k p.1 p.2))
        ≤ (Algebra.adjoin k {WeylAlgebra.x k, WeylAlgebra.y k}).toSubmodule := by
    rw [Submodule.span_le]
    rintro _ ⟨⟨i, j⟩, rfl⟩
    refine Subalgebra.mul_mem _
      (Subalgebra.pow_mem _ (Algebra.subset_adjoin ?_) i)
      (Subalgebra.pow_mem _ (Algebra.subset_adjoin ?_) j)
    · exact Set.mem_insert _ _
    · exact Set.mem_insert_of_mem _ rfl
  intro w _
  exact hsub (WeylAlgebra.monomials_span k (Submodule.mem_top))

/-- The **algebra of polynomial differential operators in one variable `t`**: the subalgebra of
`End_k(k[t])` generated by multiplication-by-`t` (`polyMulX`) and the derivative `d/dt`
(`Polynomial.derivative`). -/
noncomputable def polyDiffOp : Subalgebra k (Module.End k (Polynomial k)) :=
  Algebra.adjoin k {polyMulX k, (Polynomial.derivative : Module.End k (Polynomial k))}

/-- **Remark 2.7.2 (image form).** The image of the polynomial representation
`polyRep : A →ₐ[k] End_k(k[t])` is exactly the algebra of polynomial differential operators
`polyDiffOp k`. The generators `x, y` of `A` map onto multiplication-by-`t` and `d/dt`.

This holds in *any* characteristic: it expresses that `A` surjects onto the algebra of
polynomial differential operators. -/
theorem WeylAlgebra.polyRep_range_eq_polyDiffOp :
    (polyRep k).range = polyDiffOp k := by
  rw [polyDiffOp, ← Algebra.map_top, ← WeylAlgebra.adjoin_x_y_eq_top k, AlgHom.map_adjoin]
  congr 1
  rw [Set.image_insert_eq, Set.image_singleton, polyRep_x, polyRep_y]

/-- **Remark 2.7.2 (isomorphism form).** When the polynomial representation is faithful
(characteristic zero, no zero divisors — `WeylAlgebra.polyRep_injective`), the Weyl algebra is
isomorphic, as a `k`-algebra, to the algebra of polynomial differential operators in one
variable `t`. This is the precise meaning of "the Weyl algebra `A` can be viewed as the algebra
of polynomial differential operators in one variable `t`". -/
noncomputable def WeylAlgebra.equivPolyDiffOp [CharZero k] [NoZeroDivisors k] :
    WeylAlgebra k ≃ₐ[k] polyDiffOp k :=
  (AlgEquiv.ofInjective (polyRep k) (WeylAlgebra.polyRep_injective k)).trans
    (Subalgebra.equivOfEq _ _ (WeylAlgebra.polyRep_range_eq_polyDiffOp k))

@[simp] theorem WeylAlgebra.equivPolyDiffOp_apply [CharZero k] [NoZeroDivisors k]
    (w : WeylAlgebra k) :
    (WeylAlgebra.equivPolyDiffOp k w : Module.End k (Polynomial k)) = polyRep k w := rfl

end Etingof
