import Mathlib.Algebra.FreeAlgebra
import Mathlib.RingTheory.Congruence.Hom
import Mathlib.RingTheory.TwoSidedIdeal.Kernel
import Mathlib.RingTheory.TwoSidedIdeal.Operations

/-!
# Discussion 2.6: Algebras defined by generators and relations

The book's Section 2.6 reads:

> If `f₁, …, f_m` are elements of the free algebra `k⟨x₁, …, x_n⟩`, we say that the algebra
> `A := k⟨x₁, …, x_n⟩ / ⟨{f₁, …, f_m}⟩` is *generated* by `x₁, …, x_n` with *defining relations*
> `f₁ = 0, …, f_m = 0`.

This file formalizes that construction once, for an arbitrary generator type `X` and an arbitrary
family of relators indexed by `R`, rather than re-deriving it for each presentation that later
chapters need.

## Main definitions

* `Etingof.presentedCon` — the two-sided ring congruence on `FreeAlgebra k X` cut out by the
  relators, i.e. the congruence of the two-sided ideal they generate.
* `Etingof.PresentedAlgebra k X R rel` — the presented algebra `k⟨X⟩ / ⟨range rel⟩`.
* `Etingof.PresentedAlgebra.mk` — the canonical quotient algebra homomorphism.
* `Etingof.PresentedAlgebra.gen` — the image `x ↦ x̄` of a generator.
* `Etingof.PresentedAlgebra.lift` — the algebra homomorphism out of the presented algebra induced
  by a relation-respecting assignment of the generators.

## Main results

* `Etingof.PresentedAlgebra.mk_rel` — every relator maps to `0`: the defining relations
  `f₁ = 0, …, f_m = 0` hold in the quotient.
* `Etingof.PresentedAlgebra.lift_gen`, `Etingof.PresentedAlgebra.hom_ext` and
  `Etingof.PresentedAlgebra.existsUnique_lift` — the universal property. An assignment
  `a : X → A` of the generators killing every relator extends to a *unique* algebra
  homomorphism `PresentedAlgebra k X R rel →ₐ[k] A`.
* `Etingof.PresentedAlgebra.lift_rel_eq_zero` — the converse: any algebra homomorphism out of the
  presented algebra arises from an assignment that kills the relators, so the universal property
  characterizes the construction.

The book's finite case is the specialization `X := Fin n`, `R := Fin m`; see
`Etingof.PresentedAlgebra.finPresentation_def` at the end of the file.

## Implementation notes

The quotient of a *noncommutative* algebra by a two-sided ideal is not `Ideal.Quotient` (which is
commutative-only); it is the quotient by the associated ring congruence, `TwoSidedIdeal.ringCon`.
Mathlib's `RingCon` API (`RingCon.mkₐ`, `RingCon.liftₐ`, `RingCon.ker`) supplies the algebra
structure and the lifting machinery, so no new quotient mechanism is built here.

`PresentedAlgebra` is an `abbrev` so that the `Ring` and `Algebra k` instances on the underlying
`RingCon.Quotient` are found by unification without restating them.
-/

namespace Etingof

section Presentation

variable (k : Type*) [CommRing k] (X R : Type*) (rel : R → FreeAlgebra k X)

/-- The two-sided ring congruence on the free algebra `k⟨X⟩` generated by the relators
`rel r`. Quotienting by it imposes the defining relations `rel r = 0`. -/
abbrev presentedCon : RingCon (FreeAlgebra k X) :=
  (TwoSidedIdeal.span (Set.range rel)).ringCon

/-- **The algebra defined by generators and relations.** For a family of relators
`rel : R → FreeAlgebra k X`, this is the book's

`k⟨X⟩ / ⟨{rel r : r ∈ R}⟩`,

the free `k`-algebra on the generators `X` modulo the two-sided ideal generated by the relators.
It is generated by the images of `X` (`PresentedAlgebra.gen`) subject to the defining relations
`rel r = 0` (`PresentedAlgebra.mk_rel`). -/
abbrev PresentedAlgebra : Type _ := (presentedCon k X R rel).Quotient

end Presentation

namespace PresentedAlgebra

variable {k : Type*} [CommRing k] {X R : Type*} (rel : R → FreeAlgebra k X)

/-- The canonical quotient map `k⟨X⟩ → k⟨X⟩ / ⟨rel⟩`, a homomorphism of `k`-algebras. -/
noncomputable def mk : FreeAlgebra k X →ₐ[k] PresentedAlgebra k X R rel :=
  (presentedCon k X R rel).mkₐ k

/-- The canonical map from the free algebra onto the presented algebra is surjective. -/
theorem mk_surjective : Function.Surjective (mk rel) :=
  (presentedCon k X R rel).mkₐ_surjective (α := k)

/-- The image of a generator `x : X` in the presented algebra. -/
noncomputable def gen (x : X) : PresentedAlgebra k X R rel :=
  mk rel (FreeAlgebra.ι k x)

/-- The image of a generator is its image under the canonical quotient map. -/
theorem gen_def (x : X) : gen rel x = mk rel (FreeAlgebra.ι k x) := rfl

/-- The presented algebra is generated as a `k`-algebra by the images of its generators. -/
theorem adjoin_range_gen : Algebra.adjoin k (Set.range (gen rel)) = ⊤ := by
  rw [Algebra.adjoin_range_eq_range_freeAlgebra_lift]
  have h : FreeAlgebra.lift k (gen rel) = mk rel := by
    apply FreeAlgebra.hom_ext
    funext x
    simp [gen_def]
  rw [h, AlgHom.range_eq_top]
  exact mk_surjective rel

/-- **The defining relations hold.** Each relator `rel r` becomes `0` in the presented algebra;
this is the book's `f₁ = 0, …, f_m = 0`. -/
@[simp] theorem mk_rel (r : R) : mk rel (rel r) = 0 := by
  have h : presentedCon k X R rel (rel r) 0 := by
    rw [TwoSidedIdeal.rel_iff, sub_zero]
    exact TwoSidedIdeal.subset_span ⟨r, rfl⟩
  have : (presentedCon k X R rel).mk' (rel r) = (presentedCon k X R rel).mk' 0 :=
    (RingCon.eq _).mpr h
  simpa [mk] using this

section Lift

variable {A : Type*} [Ring A] [Algebra k A]

/-- An assignment of the generators that kills every relator factors through the defining
congruence. This is the hypothesis needed to descend `FreeAlgebra.lift` to the quotient. -/
theorem presentedCon_le_ker (a : X → A) (ha : ∀ r, FreeAlgebra.lift k a (rel r) = 0) :
    presentedCon k X R rel ≤ RingCon.ker (FreeAlgebra.lift k a).toRingHom := by
  have hsub : TwoSidedIdeal.span (Set.range rel) ≤
      TwoSidedIdeal.ker (FreeAlgebra.lift k a).toRingHom := by
    rw [TwoSidedIdeal.span_le]
    rintro _ ⟨r, rfl⟩
    rw [SetLike.mem_coe, TwoSidedIdeal.mem_ker]
    exact ha r
  intro p q hpq
  rw [RingCon.ker_apply]
  change FreeAlgebra.lift k a p = FreeAlgebra.lift k a q
  rw [← sub_eq_zero, ← map_sub]
  exact (TwoSidedIdeal.mem_ker _).1 (hsub ((TwoSidedIdeal.rel_iff _ _ _).1 hpq))

/-- **The universal property, existence half.** An assignment `a : X → A` of the generators
satisfying every defining relation induces an algebra homomorphism out of the presented
algebra. -/
noncomputable def lift (a : X → A) (ha : ∀ r, FreeAlgebra.lift k a (rel r) = 0) :
    PresentedAlgebra k X R rel →ₐ[k] A :=
  (presentedCon k X R rel).liftₐ (FreeAlgebra.lift k a) (presentedCon_le_ker rel a ha)

/-- The lift agrees with the corresponding free-algebra homomorphism after the quotient map. -/
@[simp] theorem lift_mk (a : X → A) (ha : ∀ r, FreeAlgebra.lift k a (rel r) = 0)
    (p : FreeAlgebra k X) : lift rel a ha (mk rel p) = FreeAlgebra.lift k a p := rfl

/-- The lift sends each presented generator to the element assigned to it. -/
@[simp] theorem lift_gen (a : X → A) (ha : ∀ r, FreeAlgebra.lift k a (rel r) = 0) (x : X) :
    lift rel a ha (gen rel x) = a x := by
  rw [gen_def, lift_mk, FreeAlgebra.lift_ι_apply]

/-- **The universal property, uniqueness half.** Two algebra homomorphisms out of the presented
algebra that agree on the generators are equal. -/
theorem hom_ext {F G : PresentedAlgebra k X R rel →ₐ[k] A}
    (h : ∀ x, F (gen rel x) = G (gen rel x)) : F = G := by
  have hcomp : F.comp (mk rel) = G.comp (mk rel) := FreeAlgebra.hom_ext (funext h)
  refine AlgHom.ext fun q => ?_
  obtain ⟨p, rfl⟩ := mk_surjective rel q
  exact congrArg (fun φ : FreeAlgebra k X →ₐ[k] A => φ p) hcomp

/-- **The universal property of a presentation.** For an assignment `a : X → A` of the generators
satisfying `FreeAlgebra.lift k a (rel r) = 0` for every relator, there is a *unique* algebra
homomorphism `F : PresentedAlgebra k X R rel →ₐ[k] A` with `F (gen x) = a x` for every
generator. -/
theorem existsUnique_lift (a : X → A) (ha : ∀ r, FreeAlgebra.lift k a (rel r) = 0) :
    ∃! F : PresentedAlgebra k X R rel →ₐ[k] A, ∀ x, F (gen rel x) = a x :=
  ⟨lift rel a ha, lift_gen rel a ha, fun _ hG => hom_ext rel fun x => (hG x).trans
    (lift_gen rel a ha x).symm⟩

/-- The converse of the relation-respecting hypothesis: the generator assignment underlying any
algebra homomorphism out of the presented algebra automatically kills every relator. Together
with `existsUnique_lift` this says the relation-respecting assignments `X → A` correspond exactly
to the algebra homomorphisms `PresentedAlgebra k X R rel →ₐ[k] A`. -/
theorem lift_rel_eq_zero (F : PresentedAlgebra k X R rel →ₐ[k] A) (r : R) :
    FreeAlgebra.lift k (fun x => F (gen rel x)) (rel r) = 0 := by
  have hcomp : FreeAlgebra.lift k (fun x => F (gen rel x)) = F.comp (mk rel) :=
    FreeAlgebra.hom_ext (funext fun x => FreeAlgebra.lift_ι_apply _ _)
  rw [hcomp]
  simp

end Lift

/-- The book's finite presentation `k⟨x₁, …, x_n⟩ / ⟨{f₁, …, f_m}⟩` is the immediate
specialization `X := Fin n`, `R := Fin m` of the general construction. -/
theorem finPresentation_def (k : Type*) [CommRing k] (n m : ℕ)
    (f : Fin m → FreeAlgebra k (Fin n)) :
    PresentedAlgebra k (Fin n) (Fin m) f =
      (TwoSidedIdeal.span (Set.range f)).ringCon.Quotient := rfl

/-- A worked instance of the book's finite case, showing the construction really does impose the
relations: with two generators `x, y` and the single relator `f₁ = yx − xy − 1`, the presented
algebra `k⟨x, y⟩ / ⟨f₁⟩` satisfies the Weyl relation `ȳx̄ = x̄ȳ + 1`. -/
example (k : Type*) [CommRing k] (rel : Fin 1 → FreeAlgebra k (Fin 2))
    (hrel : rel 0 = FreeAlgebra.ι k 1 * FreeAlgebra.ι k 0
      - FreeAlgebra.ι k 0 * FreeAlgebra.ι k 1 - 1) :
    gen rel 1 * gen rel 0 = gen rel 0 * gen rel 1 + 1 := by
  have h : mk rel (rel 0) = 0 := mk_rel rel 0
  rw [hrel, map_sub, map_sub, map_mul, map_mul, map_one, sub_sub, sub_eq_zero] at h
  simpa [gen_def] using h

end PresentedAlgebra

end Etingof
