import Mathlib.Algebra.Lie.Basic
import Mathlib.Algebra.Lie.OfAssociative
import Mathlib.Algebra.Lie.UniversalEnveloping
import Mathlib.RingTheory.TwoSidedIdeal.Operations
import Mathlib.RingTheory.TwoSidedIdeal.Kernel
import Mathlib.RingTheory.Congruence.Basic
import Mathlib.RingTheory.Congruence.Hom
import EtingofRepresentationTheory.Chapter2.Proposition2_7_1

/-!
# Example 2.9.13: Universal Enveloping Algebra of the Heisenberg Lie Algebra

The algebra U(ℋ), where ℋ is the Heisenberg Lie algebra, is the algebra generated by
x, y, c with the relations:

  yx − xy = c,  yc − cy = 0,  xc − cx = 0.

Note that the Weyl algebra is the quotient of U(ℋ) by the relation c = 1.

## Formalization

The Heisenberg Lie algebra `ℋ` is the 3-dimensional Lie algebra with basis `x, y, c`, the only
nonzero bracket being `⁅y, x⁆ = c` (equivalently `⁅x, y⁆ = -c`), with `c` central. We construct it
concretely as `k × k × k` with the bracket landing in the central `c`-coordinate, and verify the
defining bracket relations.

The content is:

* `Heisenberg` is a Lie algebra with the stated brackets (`bracket_y_x`, `bracket_x_c`,
  `bracket_y_c`);
* inside `U(ℋ)`, the images `X = ι x`, `Y = ι y`, `C = ι c` satisfy the book's relations
  `YX − XY = C`, `YC − CY = 0`, `XC − CX = 0` (`heisenberg_universal_relations`). These are
  specific to the Heisenberg algebra: they are not provable for an arbitrary `L`;
* the quotient `U(ℋ) ⧸ (C − 1)` (`HeisenbergWeylQuot`) has `C` equal to `1` (`weyl_c_eq_one`);
* this quotient is genuinely the Weyl algebra: `heisenbergWeylEquiv` is an explicit `AlgEquiv`
  between `U(ℋ) ⧸ (C − 1)` and the project's `Etingof.WeylAlgebra k` from Proposition 2.7.1
  (the free algebra on `x, y` modulo `yx − xy = 1`), sending the class of `X` to `x` and the
  class of `Y` to `y` (`heisenbergWeylEquiv_X`, `heisenbergWeylEquiv_Y`).

## Mathlib correspondence

Mathlib has `UniversalEnvelopingAlgebra` but the Heisenberg Lie algebra is not defined, so we build
it here. We prove the complete presentation by constructing inverse maps between `U(ℋ)` and the
free-algebra quotient. We also construct the identification of `U(ℋ)/(c−1)` with the Weyl algebra
directly from the universal property of `U(ℋ)` and of the free algebra.
-/

namespace Etingof.Example2_9_13

open UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing

variable {k : Type*} [CommRing k]

/-- The Heisenberg Lie algebra over `k`: the 3-dimensional space `k·x ⊕ k·y ⊕ k·c`, carried by
`k × k × k`. The triple `(a, b, d)` denotes `a·x + b·y + d·c`. -/
def Heisenberg (k : Type*) [CommRing k] : Type _ := k × k × k

instance : AddCommGroup (Heisenberg k) := inferInstanceAs (AddCommGroup (k × k × k))

instance : Module k (Heisenberg k) := inferInstanceAs (Module k (k × k × k))

@[ext] theorem Heisenberg.ext {a b : Heisenberg k}
    (h1 : a.1 = b.1) (h2 : a.2.1 = b.2.1) (h3 : a.2.2 = b.2.2) : a = b :=
  Prod.ext h1 (Prod.ext h2 h3)

-- Projection lemmas for the (componentwise) module structure. They are `rfl` but stated so that
-- `simp` can rewrite through the `Heisenberg` type synonym (whose add/zero/smul instances do not
-- syntactically match the generic `Prod` lemmas).
@[simp] theorem add_fst (a b : Heisenberg k) : (a + b).1 = a.1 + b.1 := rfl
@[simp] theorem add_snd_fst (a b : Heisenberg k) : (a + b).2.1 = a.2.1 + b.2.1 := rfl
@[simp] theorem add_snd_snd (a b : Heisenberg k) : (a + b).2.2 = a.2.2 + b.2.2 := rfl
@[simp] theorem zero_fst : (0 : Heisenberg k).1 = 0 := rfl
@[simp] theorem zero_snd_fst : (0 : Heisenberg k).2.1 = 0 := rfl
@[simp] theorem zero_snd_snd : (0 : Heisenberg k).2.2 = 0 := rfl
@[simp] theorem smul_fst (t : k) (a : Heisenberg k) : (t • a).1 = t • a.1 := rfl
@[simp] theorem smul_snd_fst (t : k) (a : Heisenberg k) : (t • a).2.1 = t • a.2.1 := rfl
@[simp] theorem smul_snd_snd (t : k) (a : Heisenberg k) : (t • a).2.2 = t • a.2.2 := rfl

/-- The Heisenberg bracket: `⁅u, v⁆ = (v₁·u₂ − u₁·v₂)·c`, landing in the central `c`-coordinate.
With the basis convention `(a,b,d) = a·x + b·y + d·c`, this gives `⁅y, x⁆ = c` and `c` central. -/
instance : Bracket (Heisenberg k) (Heisenberg k) where
  bracket u v := ((0 : k), (0 : k), v.1 * u.2.1 - u.1 * v.2.1)

@[simp]
theorem bracket_def (u v : Heisenberg k) :
    ⁅u, v⁆ = ((0 : k), (0 : k), v.1 * u.2.1 - u.1 * v.2.1) := rfl

instance : LieRing (Heisenberg k) where
  add_lie x y z := by
    apply Heisenberg.ext <;>
      simp only [bracket_def, add_fst, add_snd_fst, add_snd_snd] <;> ring
  lie_add x y z := by
    apply Heisenberg.ext <;>
      simp only [bracket_def, add_fst, add_snd_fst, add_snd_snd] <;> ring
  lie_self x := by
    apply Heisenberg.ext <;> simp [bracket_def]
  leibniz_lie x y z := by
    apply Heisenberg.ext <;>
      simp only [bracket_def, add_fst, add_snd_fst, add_snd_snd] <;> ring

instance : LieAlgebra k (Heisenberg k) where
  lie_smul t x y := by
    apply Heisenberg.ext <;>
      simp only [bracket_def, smul_fst, smul_snd_fst, smul_snd_snd, smul_eq_mul] <;> ring

/-- The basis vector `x` of the Heisenberg Lie algebra. -/
def x : Heisenberg k := ((1 : k), (0 : k), (0 : k))

/-- The basis vector `y` of the Heisenberg Lie algebra. -/
def y : Heisenberg k := ((0 : k), (1 : k), (0 : k))

/-- The central basis vector `c` of the Heisenberg Lie algebra. -/
def c : Heisenberg k := ((0 : k), (0 : k), (1 : k))

@[simp] theorem bracket_y_x : ⁅(y : Heisenberg k), (x : Heisenberg k)⁆ = (c : Heisenberg k) := by
  simp [bracket_def, x, y, c]

@[simp] theorem bracket_x_c : ⁅(x : Heisenberg k), (c : Heisenberg k)⁆ = 0 := by
  apply Heisenberg.ext <;> simp [bracket_def, x, c]

@[simp] theorem bracket_y_c : ⁅(y : Heisenberg k), (c : Heisenberg k)⁆ = 0 := by
  apply Heisenberg.ext <;> simp [bracket_def, y, c]

/-- **Example 2.9.13.** The defining relations of `U(ℋ)`: writing `X = ι x`, `Y = ι y`, `C = ι c`
for the images of the Heisenberg generators in the universal enveloping algebra, we have

  `YX − XY = C`,  `YC − CY = 0`,  `XC − CX = 0`.

These are exactly the book's relations `yx − xy = c`, `yc − cy = 0`, `xc − cx = 0`. Unlike the
generic `Algebra k (UniversalEnvelopingAlgebra k L)` statement (which holds for any `L`), these
relations are specific to the Heisenberg presentation. -/
theorem heisenberg_universal_relations (k : Type*) [CommRing k] :
    (ι k (y : Heisenberg k)) * (ι k x) - (ι k x) * (ι k y) = ι k c ∧
    (ι k (y : Heisenberg k)) * (ι k c) - (ι k c) * (ι k y) = 0 ∧
    (ι k (x : Heisenberg k)) * (ι k c) - (ι k c) * (ι k x) = 0 := by
  refine ⟨?_, ?_, ?_⟩
  · rw [← LieRing.of_associative_ring_bracket, ← LieHom.map_lie, bracket_y_x]
  · rw [← LieRing.of_associative_ring_bracket, ← LieHom.map_lie, bracket_y_c, map_zero]
  · rw [← LieRing.of_associative_ring_bracket, ← LieHom.map_lie, bracket_x_c, map_zero]

/-! ## The generators-and-relations presentation

The displayed equations in the book are a presentation, not merely equations that happen to
hold in `U(ℋ)`. We therefore define the algebra with exactly those three relations and prove it
is isomorphic to `U(ℋ)`, with the three generators matching. -/

/-- The three defining relations for the free algebra on `x`, `y`, `c` (indices `0`, `1`, `2`). -/
inductive HeisenbergPresRel (k : Type*) [CommRing k] :
    FreeAlgebra k (Fin 3) → FreeAlgebra k (Fin 3) → Prop
  | yx : HeisenbergPresRel k
      (FreeAlgebra.ι k 1 * FreeAlgebra.ι k 0 - FreeAlgebra.ι k 0 * FreeAlgebra.ι k 1)
      (FreeAlgebra.ι k 2)
  | yc : HeisenbergPresRel k
      (FreeAlgebra.ι k 1 * FreeAlgebra.ι k 2 - FreeAlgebra.ι k 2 * FreeAlgebra.ι k 1)
      0
  | xc : HeisenbergPresRel k
      (FreeAlgebra.ι k 0 * FreeAlgebra.ι k 2 - FreeAlgebra.ι k 2 * FreeAlgebra.ι k 0)
      0

/-- The associative algebra generated by `x`, `y`, `c` subject to exactly the book's three
Heisenberg relations. -/
def HeisenbergPresentation (k : Type*) [CommRing k] : Type _ := RingQuot (HeisenbergPresRel k)

instance : Ring (HeisenbergPresentation k) :=
  inferInstanceAs (Ring (RingQuot (HeisenbergPresRel k)))

instance : Algebra k (HeisenbergPresentation k) :=
  inferInstanceAs (Algebra k (RingQuot (HeisenbergPresRel k)))

/-- The quotient map to the presented Heisenberg enveloping algebra. -/
def heisenbergPresMk (k : Type*) [CommRing k] :
    FreeAlgebra k (Fin 3) →ₐ[k] HeisenbergPresentation k :=
  RingQuot.mkAlgHom k (HeisenbergPresRel k)

/-- The three named generators of the presentation: `0 = x`, `1 = y`, `2 = c`. -/
def heisenbergPresGen (k : Type*) [CommRing k] (i : Fin 3) : HeisenbergPresentation k :=
  heisenbergPresMk k (FreeAlgebra.ι k i)

theorem heisenbergPresRel_yx (k : Type*) [CommRing k] :
    heisenbergPresGen k 1 * heisenbergPresGen k 0 -
        heisenbergPresGen k 0 * heisenbergPresGen k 1 = heisenbergPresGen k 2 := by
  change (RingQuot.mkAlgHom k (HeisenbergPresRel k)) (FreeAlgebra.ι k 1) *
      (RingQuot.mkAlgHom k (HeisenbergPresRel k)) (FreeAlgebra.ι k 0) -
      (RingQuot.mkAlgHom k (HeisenbergPresRel k)) (FreeAlgebra.ι k 0) *
      (RingQuot.mkAlgHom k (HeisenbergPresRel k)) (FreeAlgebra.ι k 1) =
      (RingQuot.mkAlgHom k (HeisenbergPresRel k)) (FreeAlgebra.ι k 2)
  have hrel := RingQuot.mkAlgHom_rel (S := k) (HeisenbergPresRel.yx (k := k))
  simpa only [map_sub, map_mul] using hrel

theorem heisenbergPresRel_yc (k : Type*) [CommRing k] :
    heisenbergPresGen k 1 * heisenbergPresGen k 2 -
        heisenbergPresGen k 2 * heisenbergPresGen k 1 = 0 := by
  change (RingQuot.mkAlgHom k (HeisenbergPresRel k)) (FreeAlgebra.ι k 1) *
      (RingQuot.mkAlgHom k (HeisenbergPresRel k)) (FreeAlgebra.ι k 2) -
      (RingQuot.mkAlgHom k (HeisenbergPresRel k)) (FreeAlgebra.ι k 2) *
      (RingQuot.mkAlgHom k (HeisenbergPresRel k)) (FreeAlgebra.ι k 1) = 0
  have hrel := RingQuot.mkAlgHom_rel (S := k) (HeisenbergPresRel.yc (k := k))
  simpa only [map_sub, map_mul, map_zero] using hrel

theorem heisenbergPresRel_xc (k : Type*) [CommRing k] :
    heisenbergPresGen k 0 * heisenbergPresGen k 2 -
        heisenbergPresGen k 2 * heisenbergPresGen k 0 = 0 := by
  change (RingQuot.mkAlgHom k (HeisenbergPresRel k)) (FreeAlgebra.ι k 0) *
      (RingQuot.mkAlgHom k (HeisenbergPresRel k)) (FreeAlgebra.ι k 2) -
      (RingQuot.mkAlgHom k (HeisenbergPresRel k)) (FreeAlgebra.ι k 2) *
      (RingQuot.mkAlgHom k (HeisenbergPresRel k)) (FreeAlgebra.ι k 0) = 0
  have hrel := RingQuot.mkAlgHom_rel (S := k) (HeisenbergPresRel.xc (k := k))
  simpa only [map_sub, map_mul, map_zero] using hrel

section PresentationTriple

variable {A : Type*} [Ring A] [Algebra k A]

/-- A triple satisfying the Heisenberg relations determines a Lie algebra map out of `ℋ`. -/
def heisenbergLiftTriple (X Y C : A) (hYX : Y * X - X * Y = C)
    (hYC : Y * C - C * Y = 0) (hXC : X * C - C * X = 0) :
    Heisenberg k →ₗ⁅k⁆ A where
  toFun u := u.1 • X + u.2.1 • Y + u.2.2 • C
  map_add' u v := by
    simp only [add_fst, add_snd_fst, add_snd_snd, add_smul]
    abel
  map_smul' t u := by
    simp only [smul_fst, smul_snd_fst, smul_snd_snd, smul_eq_mul, RingHom.id_apply,
      smul_add, smul_smul]
  map_lie' {u v} := by
    obtain ⟨a₁, b₁, d₁⟩ := u
    obtain ⟨a₂, b₂, d₂⟩ := v
    have expand :
        (a₁ • X + b₁ • Y + d₁ • C) * (a₂ • X + b₂ • Y + d₂ • C) -
            (a₂ • X + b₂ • Y + d₂ • C) * (a₁ • X + b₁ • Y + d₁ • C) =
          (b₁ * a₂ - b₂ * a₁) • (Y * X - X * Y) +
            (b₁ * d₂ - b₂ * d₁) • (Y * C - C * Y) +
            (a₁ * d₂ - a₂ * d₁) • (X * C - C * X) := by
      simp only [add_mul, mul_add, smul_mul_smul_comm, smul_sub]
      module
    simp only [LieRing.of_associative_ring_bracket, bracket_def]
    rw [expand, hYX, hYC, hXC]
    module

@[simp] theorem heisenbergLiftTriple_apply (X Y C : A) (hYX : Y * X - X * Y = C)
    (hYC : Y * C - C * Y = 0) (hXC : X * C - C * X = 0) (u : Heisenberg k) :
    heisenbergLiftTriple X Y C hYX hYC hXC u =
      u.1 • X + u.2.1 • Y + u.2.2 • C := rfl

@[simp] theorem heisenbergLiftTriple_x (X Y C : A) (hYX : Y * X - X * Y = C)
    (hYC : Y * C - C * Y = 0) (hXC : X * C - C * X = 0) :
    heisenbergLiftTriple X Y C hYX hYC hXC (x : Heisenberg k) = X := by simp [x]

@[simp] theorem heisenbergLiftTriple_y (X Y C : A) (hYX : Y * X - X * Y = C)
    (hYC : Y * C - C * Y = 0) (hXC : X * C - C * X = 0) :
    heisenbergLiftTriple X Y C hYX hYC hXC (y : Heisenberg k) = Y := by simp [y]

@[simp] theorem heisenbergLiftTriple_c (X Y C : A) (hYX : Y * X - X * Y = C)
    (hYC : Y * C - C * Y = 0) (hXC : X * C - C * X = 0) :
    heisenbergLiftTriple X Y C hYX hYC hXC (c : Heisenberg k) = C := by simp [c]

end PresentationTriple

/-- The Lie map from `ℋ` to its algebra presented by the three displayed relations. -/
def heisenbergToPresLie (k : Type*) [CommRing k] :
    Heisenberg k →ₗ⁅k⁆ HeisenbergPresentation k :=
  heisenbergLiftTriple (heisenbergPresGen k 0) (heisenbergPresGen k 1)
    (heisenbergPresGen k 2) (heisenbergPresRel_yx k) (heisenbergPresRel_yc k)
    (heisenbergPresRel_xc k)

/-- The map `U(ℋ) → HeisenbergPresentation k` induced by the presentation generators. -/
def heisenbergUToPres (k : Type*) [CommRing k] :
    UniversalEnvelopingAlgebra k (Heisenberg k) →ₐ[k] HeisenbergPresentation k :=
  UniversalEnvelopingAlgebra.lift k (heisenbergToPresLie k)

/-- The free-algebra map sending the presentation generators to `ι x`, `ι y`, `ι c`. -/
def heisenbergPresToUFree (k : Type*) [CommRing k] :
    FreeAlgebra k (Fin 3) →ₐ[k] UniversalEnvelopingAlgebra k (Heisenberg k) :=
  FreeAlgebra.lift k ![ι k (x : Heisenberg k), ι k (y : Heisenberg k),
    ι k (c : Heisenberg k)]

@[simp] theorem heisenbergPresToUFree_ι (k : Type*) [CommRing k] (i : Fin 3) :
    heisenbergPresToUFree k (FreeAlgebra.ι k i) =
      ι k (![(x : Heisenberg k), y, c] i) := by
  simp only [heisenbergPresToUFree, FreeAlgebra.lift_ι_apply]
  fin_cases i <;> simp

theorem heisenbergPresToUFree_rel (k : Type*) [CommRing k] :
    ∀ ⦃a b : FreeAlgebra k (Fin 3)⦄, HeisenbergPresRel k a b →
      heisenbergPresToUFree k a = heisenbergPresToUFree k b := by
  rintro a b hab
  obtain _ | _ | _ := hab
  · simpa using (heisenberg_universal_relations k).1
  · simpa using (heisenberg_universal_relations k).2.1
  · simpa using (heisenberg_universal_relations k).2.2

/-- The presentation map induced by `x ↦ ι x`, `y ↦ ι y`, and `c ↦ ι c`. -/
def heisenbergPresToU (k : Type*) [CommRing k] :
    HeisenbergPresentation k →ₐ[k] UniversalEnvelopingAlgebra k (Heisenberg k) :=
  RingQuot.liftAlgHom k ⟨heisenbergPresToUFree k, heisenbergPresToUFree_rel k⟩

@[simp] theorem heisenbergUToPres_ι (k : Type*) [CommRing k] (u : Heisenberg k) :
    heisenbergUToPres k (ι k u) =
      u.1 • heisenbergPresGen k 0 + u.2.1 • heisenbergPresGen k 1 +
        u.2.2 • heisenbergPresGen k 2 :=
  UniversalEnvelopingAlgebra.lift_ι_apply k (heisenbergToPresLie k) u

@[simp] theorem heisenbergPresToU_presGen (k : Type*) [CommRing k] (i : Fin 3) :
    heisenbergPresToU k (heisenbergPresGen k i) =
      ι k (![(x : Heisenberg k), y, c] i) := by
  change RingQuot.liftAlgHom k ⟨heisenbergPresToUFree k, heisenbergPresToUFree_rel k⟩
      (RingQuot.mkAlgHom k (HeisenbergPresRel k) (FreeAlgebra.ι k i)) = _
  rw [RingQuot.liftAlgHom_mkAlgHom_apply, heisenbergPresToUFree_ι]

theorem heisenbergPresToU_comp_uToPres (k : Type*) [CommRing k] :
    (heisenbergPresToU k).comp (heisenbergUToPres k) =
      AlgHom.id k (UniversalEnvelopingAlgebra k (Heisenberg k)) := by
  ext u
  simp only [AlgHom.coe_comp, LieHom.coe_comp, Function.comp_apply, AlgHom.coe_toLieHom,
    AlgHom.coe_id, id_eq, heisenbergUToPres_ι, map_add, map_smul,
    heisenbergPresToU_presGen]
  simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_two,
    Matrix.tail_cons]
  rw [← map_smul, ← map_smul, ← map_smul, ← map_add, ← map_add]
  apply congrArg (ι k)
  apply Heisenberg.ext <;> simp [x, y, c]

theorem heisenbergUToPres_comp_presToU (k : Type*) [CommRing k] :
    (heisenbergUToPres k).comp (heisenbergPresToU k) =
      AlgHom.id k (HeisenbergPresentation k) := by
  apply RingQuot.ringQuot_ext'
  ext i
  fin_cases i
  · change heisenbergUToPres k (heisenbergPresToU k (heisenbergPresGen k 0)) =
      heisenbergPresGen k 0
    simp [heisenbergUToPres, heisenbergToPresLie, x, y, c]
  · change heisenbergUToPres k (heisenbergPresToU k (heisenbergPresGen k 1)) =
      heisenbergPresGen k 1
    simp [heisenbergUToPres, heisenbergToPresLie, x, y, c]
  · change heisenbergUToPres k (heisenbergPresToU k (heisenbergPresGen k 2)) =
      heisenbergPresGen k 2
    simp [heisenbergUToPres, heisenbergToPresLie, x, y, c]

/-- **Example 2.9.13.** The three displayed relations are a complete presentation of `U(ℋ)`. -/
def heisenbergPresentationAlgEquiv (k : Type*) [CommRing k] :
    HeisenbergPresentation k ≃ₐ[k] UniversalEnvelopingAlgebra k (Heisenberg k) :=
  AlgEquiv.ofAlgHom (heisenbergPresToU k) (heisenbergUToPres k)
    (heisenbergPresToU_comp_uToPres k) (heisenbergUToPres_comp_presToU k)

/-- The full presentation assertion implicit in Example 2.9.13, including generator matching. -/
theorem heisenbergPresentationEquiv (k : Type*) [CommRing k] :
    ∃ e : HeisenbergPresentation k ≃ₐ[k] UniversalEnvelopingAlgebra k (Heisenberg k),
      e (heisenbergPresGen k 0) = ι k (x : Heisenberg k) ∧
      e (heisenbergPresGen k 1) = ι k (y : Heisenberg k) ∧
      e (heisenbergPresGen k 2) = ι k (c : Heisenberg k) := by
  refine ⟨heisenbergPresentationAlgEquiv k, ?_, ?_, ?_⟩ <;>
    simp [heisenbergPresentationAlgEquiv]

/-- The two-sided congruence on `U(ℋ)` generated by `C − 1`, defining the Weyl-algebra quotient. -/
abbrev weylCon (k : Type*) [CommRing k] :
    RingCon (UniversalEnvelopingAlgebra k (Heisenberg k)) :=
  (TwoSidedIdeal.span {ι k (c : Heisenberg k) - 1}).ringCon

/-- The quotient `U(ℋ) ⧸ (C − 1)` of the Heisenberg enveloping algebra by the two-sided relation
`c = 1`. This carries a natural `k`-algebra structure (`RingCon.instAlgebra`); we prove below that
it is isomorphic to the project's Weyl algebra `Etingof.WeylAlgebra` (`heisenbergWeylEquiv`). -/
abbrev HeisenbergWeylQuot (k : Type*) [CommRing k] : Type _ := (weylCon k).Quotient

/-- In the quotient `U(ℋ) ⧸ (C − 1)`, the central generator `c` becomes `1`: this is the
relation `c = 1` from the book. -/
theorem weyl_c_eq_one (k : Type*) [CommRing k] :
    (weylCon k).mk' (ι k (c : Heisenberg k)) = (weylCon k).mk' 1 := by
  have h : weylCon k (ι k (c : Heisenberg k)) 1 := by
    rw [weylCon, TwoSidedIdeal.rel_iff]
    exact TwoSidedIdeal.subset_span (Set.mem_singleton _)
  exact (RingCon.eq _).mpr h

/-! ## Identification with the Weyl algebra of Proposition 2.7.1

We now prove the actual content of Example 2.9.13: the quotient `U(ℋ) ⧸ (C − 1)` is the Weyl
algebra. The target is the project's `Etingof.WeylAlgebra k`, the free algebra on two generators
`x, y` modulo `yx = xy + 1`. We build algebra homomorphisms in both directions and show they are
mutually inverse, packaging the result as an `AlgEquiv`.
-/

open scoped Etingof in
/-- The `k`-linear map `ℋ → A` sending `(a, b, d) = a·x + b·y + d·c` to `a·x + b·y + d·1` in the
Weyl algebra `A = Etingof.WeylAlgebra k`. This is the underlying linear map of the Lie algebra
homomorphism `heisenbergToWeyl`. -/
noncomputable def heisenbergToWeylLin (k : Type*) [CommRing k] :
    Heisenberg k →ₗ[k] Etingof.WeylAlgebra k where
  toFun u := u.1 • Etingof.WeylAlgebra.x k + u.2.1 • Etingof.WeylAlgebra.y k + u.2.2 • 1
  map_add' u v := by
    simp only [add_fst, add_snd_fst, add_snd_snd, add_smul]; abel
  map_smul' t u := by
    simp only [smul_fst, smul_snd_fst, smul_snd_snd, RingHom.id_apply, smul_assoc, smul_add]

@[simp] theorem heisenbergToWeylLin_apply (k : Type*) [CommRing k] (u : Heisenberg k) :
    heisenbergToWeylLin k u =
      u.1 • Etingof.WeylAlgebra.x k + u.2.1 • Etingof.WeylAlgebra.y k + u.2.2 • 1 := rfl

section WeylBrackets

variable (k : Type*) [CommRing k]

private theorem lie_y_x_weyl :
    ⁅Etingof.WeylAlgebra.y k, Etingof.WeylAlgebra.x k⁆ = (1 : Etingof.WeylAlgebra k) := by
  rw [LieRing.of_associative_ring_bracket, Etingof.WeylAlgebra.yx_eq]; abel

private theorem lie_x_y_weyl :
    ⁅Etingof.WeylAlgebra.x k, Etingof.WeylAlgebra.y k⁆ = (-1 : Etingof.WeylAlgebra k) := by
  rw [LieRing.of_associative_ring_bracket, Etingof.WeylAlgebra.yx_eq]; abel

private theorem lie_x_one_weyl :
    ⁅Etingof.WeylAlgebra.x k, (1 : Etingof.WeylAlgebra k)⁆ = 0 := by
  rw [LieRing.of_associative_ring_bracket, mul_one, one_mul, sub_self]

private theorem lie_one_x_weyl :
    ⁅(1 : Etingof.WeylAlgebra k), Etingof.WeylAlgebra.x k⁆ = 0 := by
  rw [LieRing.of_associative_ring_bracket, mul_one, one_mul, sub_self]

private theorem lie_y_one_weyl :
    ⁅Etingof.WeylAlgebra.y k, (1 : Etingof.WeylAlgebra k)⁆ = 0 := by
  rw [LieRing.of_associative_ring_bracket, mul_one, one_mul, sub_self]

private theorem lie_one_y_weyl :
    ⁅(1 : Etingof.WeylAlgebra k), Etingof.WeylAlgebra.y k⁆ = 0 := by
  rw [LieRing.of_associative_ring_bracket, mul_one, one_mul, sub_self]

private theorem lie_one_one_weyl :
    ⁅(1 : Etingof.WeylAlgebra k), (1 : Etingof.WeylAlgebra k)⁆ = 0 := by
  rw [LieRing.of_associative_ring_bracket, mul_one, sub_self]

end WeylBrackets

/-- The Lie algebra homomorphism `ℋ → A` (with `A = Etingof.WeylAlgebra k` viewed as a Lie algebra
via `LieRing.ofAssociativeRing`) sending `x ↦ x`, `y ↦ y`, `c ↦ 1`. The bracket relation
`⁅y, x⁆ = c` is sent to `⁅y, x⁆ = 1`, which is the Weyl relation `yx − xy = 1`. -/
noncomputable def heisenbergToWeyl (k : Type*) [CommRing k] :
    Heisenberg k →ₗ⁅k⁆ Etingof.WeylAlgebra k :=
  { heisenbergToWeylLin k with
    map_lie' := fun {u v} => by
      change heisenbergToWeylLin k ⁅u, v⁆ =
        ⁅heisenbergToWeylLin k u, heisenbergToWeylLin k v⁆
      rw [LieRing.of_associative_ring_bracket]
      simp only [heisenbergToWeylLin_apply, bracket_def,
        mul_add, add_mul, smul_mul_assoc, mul_smul_comm, smul_smul, mul_one, one_mul,
        Etingof.WeylAlgebra.yx_eq, smul_add, zero_smul, add_zero, zero_add]
      module }

@[simp] theorem heisenbergToWeyl_apply (k : Type*) [CommRing k] (u : Heisenberg k) :
    heisenbergToWeyl k u =
      u.1 • Etingof.WeylAlgebra.x k + u.2.1 • Etingof.WeylAlgebra.y k + u.2.2 • 1 := rfl

/-- The algebra homomorphism `U(ℋ) → A` obtained from `heisenbergToWeyl` by the universal property
of the enveloping algebra. -/
noncomputable def envToWeyl (k : Type*) [CommRing k] :
    UniversalEnvelopingAlgebra k (Heisenberg k) →ₐ[k] Etingof.WeylAlgebra k :=
  UniversalEnvelopingAlgebra.lift k (heisenbergToWeyl k)

theorem envToWeyl_c (k : Type*) [CommRing k] :
    envToWeyl k (ι k (c : Heisenberg k)) = 1 := by
  rw [envToWeyl, UniversalEnvelopingAlgebra.lift_ι_apply, heisenbergToWeyl_apply, c]
  simp

/-- `envToWeyl` sends `C − 1` to `0`, hence descends to the quotient `U(ℋ) ⧸ (C − 1)`. -/
theorem weylCon_le_ker (k : Type*) [CommRing k] :
    weylCon k ≤ RingCon.ker (envToWeyl k).toRingHom := by
  have hsub : TwoSidedIdeal.span {ι k (c : Heisenberg k) - 1} ≤
      TwoSidedIdeal.ker (envToWeyl k).toRingHom := by
    rw [TwoSidedIdeal.span_le]
    intro z hz
    rw [Set.mem_singleton_iff] at hz
    subst hz
    rw [SetLike.mem_coe, TwoSidedIdeal.mem_ker]
    change envToWeyl k (ι k (c : Heisenberg k) - 1) = 0
    rw [map_sub, map_one, envToWeyl_c, sub_self]
  intro a b hab
  rw [RingCon.ker_apply]
  change envToWeyl k a = envToWeyl k b
  rw [← sub_eq_zero, ← map_sub]
  exact (TwoSidedIdeal.mem_ker _).1 (hsub ((TwoSidedIdeal.rel_iff _ _ _).1 hab))

/-- The forward algebra map `U(ℋ) ⧸ (C − 1) → Etingof.WeylAlgebra k`. -/
noncomputable def toWeyl (k : Type*) [CommRing k] :
    HeisenbergWeylQuot k →ₐ[k] Etingof.WeylAlgebra k :=
  (weylCon k).liftₐ (envToWeyl k) (weylCon_le_ker k)

@[simp] theorem toWeyl_mk (k : Type*) [CommRing k]
    (a : UniversalEnvelopingAlgebra k (Heisenberg k)) :
    toWeyl k ((weylCon k).mkₐ k a) = envToWeyl k a := rfl

/-- The image of `X` (the class of `ι x`) in the quotient `U(ℋ) ⧸ (C − 1)`. -/
noncomputable def Xbar (k : Type*) [CommRing k] : HeisenbergWeylQuot k :=
  (weylCon k).mkₐ k (ι k (x : Heisenberg k))

/-- The image of `Y` (the class of `ι y`) in the quotient `U(ℋ) ⧸ (C − 1)`. -/
noncomputable def Ybar (k : Type*) [CommRing k] : HeisenbergWeylQuot k :=
  (weylCon k).mkₐ k (ι k (y : Heisenberg k))

/-- In `U(ℋ) ⧸ (C − 1)`, the classes of `X` and `Y` satisfy the Weyl relation `YX = XY + 1`,
because `YX − XY = C = 1`. -/
theorem Ybar_mul_Xbar (k : Type*) [CommRing k] :
    Ybar k * Xbar k = Xbar k * Ybar k + 1 := by
  have hrel := (heisenberg_universal_relations k).1
  have hmk : (weylCon k).mkₐ k (ι k (y : Heisenberg k) * ι k x - ι k x * ι k y) =
      (weylCon k).mkₐ k (ι k (c : Heisenberg k)) := by rw [hrel]
  rw [map_sub, map_mul, map_mul] at hmk
  have hc : (weylCon k).mkₐ k (ι k (c : Heisenberg k)) = 1 := by
    change (weylCon k).mk' (ι k (c : Heisenberg k)) = 1
    rw [weyl_c_eq_one]; exact map_one _
  rw [hc] at hmk
  rw [Xbar, Ybar, ← sub_eq_iff_eq_add']
  exact hmk

/-- The generators-to-quotient assignment `x ↦ Xbar`, `y ↦ Ybar` used to build the reverse map. -/
noncomputable def weylGenToQuot (k : Type*) [CommRing k] : Etingof.WeylGen → HeisenbergWeylQuot k :=
  ![Xbar k, Ybar k]

/-- The reverse algebra map `Etingof.WeylAlgebra k → U(ℋ) ⧸ (C − 1)`, obtained from the universal
property of the free algebra and of the Weyl relation, sending `x ↦ Xbar`, `y ↦ Ybar`. -/
noncomputable def ofWeyl (k : Type*) [CommRing k] :
    Etingof.WeylAlgebra k →ₐ[k] HeisenbergWeylQuot k :=
  RingQuot.liftAlgHom k
    ⟨FreeAlgebra.lift k (weylGenToQuot k), by
      rintro a b ⟨rfl, rfl⟩
      simp only [Etingof.weylX, Etingof.weylY, map_mul, map_add, map_one,
        FreeAlgebra.lift_ι_apply, weylGenToQuot, Matrix.cons_val_zero, Matrix.cons_val_one]
      exact Ybar_mul_Xbar k⟩

@[simp] theorem ofWeyl_x (k : Type*) [CommRing k] :
    ofWeyl k (Etingof.WeylAlgebra.x k) = Xbar k := by
  rw [ofWeyl, Etingof.WeylAlgebra.x, Etingof.WeylAlgebra.mk, RingQuot.liftAlgHom_mkAlgHom_apply,
    Etingof.weylX, FreeAlgebra.lift_ι_apply]
  simp [weylGenToQuot]

@[simp] theorem ofWeyl_y (k : Type*) [CommRing k] :
    ofWeyl k (Etingof.WeylAlgebra.y k) = Ybar k := by
  rw [ofWeyl, Etingof.WeylAlgebra.y, Etingof.WeylAlgebra.mk, RingQuot.liftAlgHom_mkAlgHom_apply,
    Etingof.weylY, FreeAlgebra.lift_ι_apply]
  simp [weylGenToQuot]

/-- `toWeyl` sends the class of `X` to the Weyl generator `x`. -/
@[simp] theorem toWeyl_Xbar (k : Type*) [CommRing k] :
    toWeyl k (Xbar k) = Etingof.WeylAlgebra.x k := by
  rw [Xbar, toWeyl_mk, envToWeyl, UniversalEnvelopingAlgebra.lift_ι_apply, heisenbergToWeyl_apply,
    x]
  simp

/-- `toWeyl` sends the class of `Y` to the Weyl generator `y`. -/
@[simp] theorem toWeyl_Ybar (k : Type*) [CommRing k] :
    toWeyl k (Ybar k) = Etingof.WeylAlgebra.y k := by
  rw [Ybar, toWeyl_mk, envToWeyl, UniversalEnvelopingAlgebra.lift_ι_apply, heisenbergToWeyl_apply,
    y]
  simp

/-- `toWeyl` and `ofWeyl` compose to the identity on `Etingof.WeylAlgebra k`; checked on the two
generators `x, y`. -/
theorem toWeyl_comp_ofWeyl (k : Type*) [CommRing k] :
    (toWeyl k).comp (ofWeyl k) = AlgHom.id k (Etingof.WeylAlgebra k) := by
  apply RingQuot.ringQuot_ext'
  apply FreeAlgebra.hom_ext
  funext i
  fin_cases i
  · change toWeyl k (ofWeyl k (Etingof.WeylAlgebra.x k)) = Etingof.WeylAlgebra.x k
    rw [ofWeyl_x, toWeyl_Xbar]
  · change toWeyl k (ofWeyl k (Etingof.WeylAlgebra.y k)) = Etingof.WeylAlgebra.y k
    rw [ofWeyl_y, toWeyl_Ybar]

/-- `ofWeyl` and `toWeyl` compose to the identity on `U(ℋ) ⧸ (C − 1)`; checked on the generating
images `ι x, ι y, ι c` of the enveloping algebra. -/
theorem ofWeyl_comp_toWeyl (k : Type*) [CommRing k] :
    (ofWeyl k).comp (toWeyl k) = AlgHom.id k (HeisenbergWeylQuot k) := by
  -- It suffices to agree after precomposing with the surjective quotient map `mkₐ`.
  have key : ((ofWeyl k).comp (toWeyl k)).comp ((weylCon k).mkₐ k) = (weylCon k).mkₐ k := by
    apply UniversalEnvelopingAlgebra.hom_ext
    apply LieHom.ext
    intro d
    change ofWeyl k (toWeyl k ((weylCon k).mkₐ k (ι k d))) = (weylCon k).mkₐ k (ι k d)
    rw [toWeyl_mk, envToWeyl, UniversalEnvelopingAlgebra.lift_ι_apply, heisenbergToWeyl_apply,
      map_add, map_add, map_smul, map_smul, map_smul, map_one, ofWeyl_x, ofWeyl_y]
    -- RHS: `mkₐ (ι d)` with `d = d.1 • x + d.2.1 • y + d.2.2 • c`, and `mkₐ (ι c) = 1`.
    have hd : ι k d = d.1 • ι k (x : Heisenberg k) + d.2.1 • ι k y + d.2.2 • ι k c := by
      rw [← map_smul, ← map_smul, ← map_smul, ← map_add, ← map_add]
      congr 1
      apply Heisenberg.ext <;> simp [x, y, c]
    have hcbar : (weylCon k).mkₐ k (ι k (c : Heisenberg k)) = 1 := by
      change (weylCon k).mk' (ι k (c : Heisenberg k)) = 1
      rw [weyl_c_eq_one]; exact map_one _
    rw [hd, map_add, map_add, map_smul, map_smul, map_smul, hcbar, ← Xbar, ← Ybar]
  apply AlgHom.ext
  intro q
  obtain ⟨a, rfl⟩ := (weylCon k).mkₐ_surjective (α := k) q
  exact AlgHom.congr_fun key a

/-- **Example 2.9.13.** The quotient `U(ℋ) ⧸ (C − 1)` of the Heisenberg enveloping algebra by the
central relation `c = 1` is isomorphic, as a `k`-algebra, to the Weyl algebra
`Etingof.WeylAlgebra k` of Proposition 2.7.1. The isomorphism sends the class of `X` to `x` and
the class of `Y` to `y`. -/
noncomputable def heisenbergWeylEquiv (k : Type*) [CommRing k] :
    HeisenbergWeylQuot k ≃ₐ[k] Etingof.WeylAlgebra k :=
  AlgEquiv.ofAlgHom (toWeyl k) (ofWeyl k) (toWeyl_comp_ofWeyl k) (ofWeyl_comp_toWeyl k)

@[simp] theorem heisenbergWeylEquiv_X (k : Type*) [CommRing k] :
    heisenbergWeylEquiv k (Xbar k) = Etingof.WeylAlgebra.x k := toWeyl_Xbar k

@[simp] theorem heisenbergWeylEquiv_Y (k : Type*) [CommRing k] :
    heisenbergWeylEquiv k (Ybar k) = Etingof.WeylAlgebra.y k := toWeyl_Ybar k

@[simp] theorem heisenbergWeylEquiv_symm_x (k : Type*) [CommRing k] :
    (heisenbergWeylEquiv k).symm (Etingof.WeylAlgebra.x k) = Xbar k := ofWeyl_x k

@[simp] theorem heisenbergWeylEquiv_symm_y (k : Type*) [CommRing k] :
    (heisenbergWeylEquiv k).symm (Etingof.WeylAlgebra.y k) = Ybar k := ofWeyl_y k

end Etingof.Example2_9_13
