import EtingofRepresentationTheory.Chapter2.FaithfulWeylModule
import Mathlib.RingTheory.SimpleModule.Basic
import Mathlib.LinearAlgebra.Eigenspace.Triangularizable
import Mathlib.Data.Nat.Prime.Factorial
import Mathlib.LinearAlgebra.Trace

/-!
# Problem 2.7.4: Representations and ideals of the Weyl algebra

Let `A` be the Weyl algebra (`Etingof.WeylAlgebra k`, generated by `x, y` with `yx = xy + 1`).

* **(a)** In characteristic `0`: the only finite dimensional representation of `A` is the zero
  representation, and the only two-sided ideals of `A` are `0` and `A` (i.e. `A` is simple).
  (The obstruction to a nonzero finite dimensional module is `Tr(ρ(x)ρ(y) - ρ(y)ρ(x)) = 0`
  versus `Tr(ρ(1)) = dim V`, which forces `dim V = 0` in characteristic `0`.)

* **(b)** In characteristic `p`: `x^p` and `y^p` are central, and the center of `A` is the
  polynomial subalgebra `k[x^p, y^p]`.

* **(c)** In characteristic `p`: every irreducible finite dimensional representation of `A` has
  dimension exactly `p`. The dimension comes from a normal form (`exists_normalForm`): over an
  algebraically closed field such a module has a basis `bᵢ = xⁱ · v` on which `x` acts by a
  twisted cyclic shift and `y` by a scalar plus a lowering operator. `Problem2_7_4_Family.lean`
  turns that normal form into the classification itself — every irreducible module is isomorphic
  to exactly one member of an explicit family `V(α,c)`.

We render the book's answers as the statements.
-/

namespace Etingof.Problem2_7_4

open Etingof

/-! ## Commutator lemmas (used for part (b): `xᵖ`, `yᵖ` central)

From the defining relation `yx = xy + 1` (`WeylAlgebra.yx_eq`) one derives, by induction,
the commutator identities `y·xⁿ⁺¹ = xⁿ⁺¹·y + (n+1)·xⁿ` and `x·yⁿ⁺¹ = yⁿ⁺¹·x − (n+1)·yⁿ`.
In characteristic `p` the coefficient `p` vanishes, so `xᵖ` commutes with `y` and `yᵖ`
commutes with `x`; combined with the trivial fact that `xᵖ` (resp. `yᵖ`) commutes with `x`
(resp. `y`), and that `x, y` generate the algebra, this puts `xᵖ` and `yᵖ` in the center. -/

/-- Commutator identity `y · xⁿ⁺¹ = xⁿ⁺¹ · y + (n+1) • xⁿ` in the Weyl algebra. -/
private lemma y_mul_x_pow_succ (k : Type*) [Field k] (n : ℕ) :
    WeylAlgebra.y k * WeylAlgebra.x k ^ (n + 1)
      = WeylAlgebra.x k ^ (n + 1) * WeylAlgebra.y k + (n + 1) • WeylAlgebra.x k ^ n := by
  induction n with
  | zero => simp only [zero_add, pow_one, pow_zero, one_smul]; exact WeylAlgebra.yx_eq k
  | succ n ih =>
    calc WeylAlgebra.y k * WeylAlgebra.x k ^ (n + 1 + 1)
        = WeylAlgebra.y k * WeylAlgebra.x k ^ (n + 1) * WeylAlgebra.x k := by
          rw [pow_succ, mul_assoc]
      _ = (WeylAlgebra.x k ^ (n + 1) * WeylAlgebra.y k + (n + 1) • WeylAlgebra.x k ^ n)
            * WeylAlgebra.x k := by rw [ih]
      _ = WeylAlgebra.x k ^ (n + 1) * (WeylAlgebra.y k * WeylAlgebra.x k)
            + (n + 1) • WeylAlgebra.x k ^ (n + 1) := by
          rw [add_mul, mul_assoc, smul_mul_assoc, ← pow_succ]
      _ = WeylAlgebra.x k ^ (n + 1) * (WeylAlgebra.x k * WeylAlgebra.y k + 1)
            + (n + 1) • WeylAlgebra.x k ^ (n + 1) := by rw [WeylAlgebra.yx_eq]
      _ = WeylAlgebra.x k ^ (n + 1 + 1) * WeylAlgebra.y k
            + (n + 1 + 1) • WeylAlgebra.x k ^ (n + 1) := by
          rw [mul_add, mul_one, ← mul_assoc, ← pow_succ, add_assoc,
            add_comm (WeylAlgebra.x k ^ (n + 1)) ((n + 1) • WeylAlgebra.x k ^ (n + 1)),
            ← succ_nsmul]

/-- Commutator identity `x · yⁿ⁺¹ = yⁿ⁺¹ · x − (n+1) • yⁿ` in the Weyl algebra. -/
private lemma x_mul_y_pow_succ (k : Type*) [Field k] (n : ℕ) :
    WeylAlgebra.x k * WeylAlgebra.y k ^ (n + 1)
      = WeylAlgebra.y k ^ (n + 1) * WeylAlgebra.x k - (n + 1) • WeylAlgebra.y k ^ n := by
  have hxy : WeylAlgebra.x k * WeylAlgebra.y k = WeylAlgebra.y k * WeylAlgebra.x k - 1 := by
    rw [eq_sub_iff_add_eq]; exact (WeylAlgebra.yx_eq k).symm
  induction n with
  | zero => simp only [zero_add, pow_one, pow_zero, one_smul]; exact hxy
  | succ n ih =>
    calc WeylAlgebra.x k * WeylAlgebra.y k ^ (n + 1 + 1)
        = WeylAlgebra.x k * WeylAlgebra.y k ^ (n + 1) * WeylAlgebra.y k := by
          rw [pow_succ, mul_assoc]
      _ = (WeylAlgebra.y k ^ (n + 1) * WeylAlgebra.x k - (n + 1) • WeylAlgebra.y k ^ n)
            * WeylAlgebra.y k := by rw [ih]
      _ = WeylAlgebra.y k ^ (n + 1) * (WeylAlgebra.x k * WeylAlgebra.y k)
            - (n + 1) • WeylAlgebra.y k ^ (n + 1) := by
          rw [sub_mul, mul_assoc, smul_mul_assoc, ← pow_succ]
      _ = WeylAlgebra.y k ^ (n + 1) * (WeylAlgebra.y k * WeylAlgebra.x k - 1)
            - (n + 1) • WeylAlgebra.y k ^ (n + 1) := by rw [hxy]
      _ = WeylAlgebra.y k ^ (n + 1 + 1) * WeylAlgebra.x k
            - (n + 1 + 1) • WeylAlgebra.y k ^ (n + 1) := by
          rw [mul_sub, mul_one, ← mul_assoc, ← pow_succ, sub_sub,
            add_comm (WeylAlgebra.y k ^ (n + 1)) ((n + 1) • WeylAlgebra.y k ^ (n + 1)),
            ← succ_nsmul]

/-- An element of the Weyl algebra that commutes with both generators `x` and `y` is central.
Since `x, y` generate the algebra (via the surjection from the free algebra), commuting with
the generators is enough to commute with everything. -/
private theorem mem_center_of_comm_gen (k : Type*) [Field k] {z : WeylAlgebra k}
    (hx : z * WeylAlgebra.x k = WeylAlgebra.x k * z)
    (hy : z * WeylAlgebra.y k = WeylAlgebra.y k * z) :
    z ∈ Subalgebra.center k (WeylAlgebra k) := by
  rw [Subalgebra.mem_center_iff]
  intro b
  obtain ⟨a, rfl⟩ := RingQuot.mkAlgHom_surjective k (WeylAlgebraRel k) b
  have ha : a ∈ Algebra.adjoin k (Set.range (FreeAlgebra.ι k)) := by
    rw [FreeAlgebra.adjoin_range_ι]; exact Algebra.mem_top
  induction ha using Algebra.adjoin_induction with
  | mem g hg =>
    obtain ⟨i, rfl⟩ := hg
    fin_cases i
    · exact hx.symm
    · exact hy.symm
  | algebraMap r => rw [AlgHom.commutes]; exact Algebra.commutes r z
  | add p q _ _ ihp ihq => rw [map_add, add_mul, mul_add, ihp, ihq]
  | mul p q _ _ ihp ihq => rw [map_mul, mul_assoc, ihq, ← mul_assoc, ihp, mul_assoc]

/-! ## (a) Characteristic zero -/

/-- **(a)** In characteristic `0`, the Weyl algebra has no nonzero finite dimensional
representation: any finite dimensional `A`-module (as a `k`-vector space) is zero. -/
theorem finrank_eq_zero_of_charZero (k : Type*) [Field k] [CharZero k]
    (V : Type*) [AddCommGroup V] [Module k V] [Module (WeylAlgebra k) V]
    [IsScalarTower k (WeylAlgebra k) V] [FiniteDimensional k V] :
    Module.finrank k V = 0 := by
  -- The action of `A` on `V` gives `k`-linear endomorphisms `X, Y` with `Y * X = X * Y + 1`
  -- (the image of the defining relation `yx = xy + 1`).
  haveI : SMulCommClass (WeylAlgebra k) k V :=
    ⟨fun a c v => by
      simp only [← algebraMap_smul (WeylAlgebra k) c, ← mul_smul, Algebra.commutes]⟩
  let φ : WeylAlgebra k →ₐ[k] Module.End k V := Algebra.lsmul k k V
  set X := φ (WeylAlgebra.x k) with hX
  set Y := φ (WeylAlgebra.y k) with hY
  have hcomm : Y * X = X * Y + 1 := by
    rw [hX, hY, ← map_mul, ← map_mul, ← map_one φ, ← map_add, WeylAlgebra.yx_eq]
  -- Take traces: `Tr(Y*X) = Tr(X*Y)`, but `Y*X = X*Y + 1`, so `Tr(1) = 0`, i.e. `finrank = 0`.
  have htr : LinearMap.trace k V (Y * X) = LinearMap.trace k V (X * Y) :=
    LinearMap.trace_mul_comm k Y X
  rw [hcomm, map_add, LinearMap.trace_one] at htr
  have hfin : (Module.finrank k V : k) = 0 := by linear_combination htr
  exact_mod_cast hfin

/-! ### Inner derivations `ad_x`, `ad_y` and their action on monomials (characteristic-free)

The inner derivations `ad_x(a) = x·a − a·x` and `ad_y(a) = y·a − a·y` and their action on the
standard monomials are characteristic-free (they rely only on the commutator identities
`y_mul_x_pow_succ` / `x_mul_y_pow_succ`). They are shared by the characteristic-zero simplicity
argument (part (a)) and the characteristic-`p` center computation (part (b)). -/

section AdDerivations

variable (k : Type*) [Field k]

open WeylAlgebra

/-- The inner derivation `ad_x = [x, -]`. -/
private noncomputable def adx : WeylAlgebra k →ₗ[k] WeylAlgebra k :=
  LinearMap.mulLeft k (WeylAlgebra.x k) - LinearMap.mulRight k (WeylAlgebra.x k)

/-- The inner derivation `ad_y = [y, -]`. -/
private noncomputable def ady : WeylAlgebra k →ₗ[k] WeylAlgebra k :=
  LinearMap.mulLeft k (WeylAlgebra.y k) - LinearMap.mulRight k (WeylAlgebra.y k)

private lemma adx_apply (a : WeylAlgebra k) :
    adx k a = WeylAlgebra.x k * a - a * WeylAlgebra.x k := by
  simp [adx, LinearMap.mulLeft_apply, LinearMap.mulRight_apply]

private lemma ady_apply (a : WeylAlgebra k) :
    ady k a = WeylAlgebra.y k * a - a * WeylAlgebra.y k := by
  simp [ady, LinearMap.mulLeft_apply, LinearMap.mulRight_apply]

private lemma adx_monomial_zero (i : ℕ) : adx k (WeylAlgebra.monomial k i 0) = 0 := by
  rw [adx_apply, WeylAlgebra.monomial, pow_zero, mul_one, ← pow_succ, ← pow_succ', sub_self]

private lemma adx_monomial_succ (i n : ℕ) :
    adx k (WeylAlgebra.monomial k i (n + 1))
      = (-((n : k) + 1)) • WeylAlgebra.monomial k i n := by
  have hYX : WeylAlgebra.y k ^ (n + 1) * WeylAlgebra.x k
      = WeylAlgebra.x k * WeylAlgebra.y k ^ (n + 1)
        + (n + 1) • WeylAlgebra.y k ^ n := by
    have h := x_mul_y_pow_succ k n; rw [h]; abel
  simp only [adx_apply, WeylAlgebra.monomial]
  rw [← mul_assoc, ← pow_succ', mul_assoc (WeylAlgebra.x k ^ i), hYX, mul_add,
    ← mul_assoc, ← pow_succ, mul_smul_comm, sub_add_eq_sub_sub, sub_self, zero_sub,
    ← Nat.cast_smul_eq_nsmul (R := k) (n + 1)]
  push_cast
  module

private lemma ady_monomial_zero (j : ℕ) : ady k (WeylAlgebra.monomial k 0 j) = 0 := by
  rw [ady_apply, WeylAlgebra.monomial, pow_zero, one_mul, ← pow_succ, ← pow_succ', sub_self]

private lemma ady_monomial_succ (n j : ℕ) :
    ady k (WeylAlgebra.monomial k (n + 1) j)
      = ((n : k) + 1) • WeylAlgebra.monomial k n j := by
  have hYX : WeylAlgebra.y k * WeylAlgebra.x k ^ (n + 1)
      = WeylAlgebra.x k ^ (n + 1) * WeylAlgebra.y k + (n + 1) • WeylAlgebra.x k ^ n :=
    y_mul_x_pow_succ k n
  simp only [ady_apply, WeylAlgebra.monomial]
  rw [← mul_assoc, hYX, add_mul,
    mul_assoc (WeylAlgebra.x k ^ (n + 1)), ← pow_succ', smul_mul_assoc,
    mul_assoc (WeylAlgebra.x k ^ (n + 1)), ← pow_succ,
    add_sub_cancel_left, ← Nat.cast_smul_eq_nsmul (R := k) (n + 1)]
  congr 1
  push_cast; ring

end AdDerivations

/-! ### Simplicity in characteristic zero

The book's argument: a two-sided ideal `I` is closed under the two inner derivations
`ad_x(a) = x·a − a·x` and `ad_y(a) = y·a − a·y`. On the monomial basis `xⁱyʲ` one has
`ad_x(xⁱyʲ) = −j·xⁱyʲ⁻¹` (lowers the `y`-degree) and `ad_y(xⁱyʲ) = i·xⁱ⁻¹yʲ` (lowers the
`x`-degree); in characteristic `0` the leading coefficients `−j`, `i` are nonzero. So from a
nonzero `a ∈ I` we lower the `y`-degree by `ad_x` to reach a nonzero polynomial in `x`, then
lower the `x`-degree by `ad_y` to reach a nonzero scalar, which is a unit; hence `I = ⊤`. -/

section CharZeroSimple

variable (k : Type*) [Field k] [CharZero k]

open WeylAlgebra Module

/-- The monomial basis `{xⁱyʲ}` of the Weyl algebra (Proposition 2.7.1), available over a
characteristic-zero field. -/
private noncomputable def monBasis : Basis (ℕ × ℕ) k (WeylAlgebra k) :=
  Basis.mk (Proposition_2_7_1 k).1 (Proposition_2_7_1 k).2

private lemma monBasis_apply (p : ℕ × ℕ) :
    monBasis k p = WeylAlgebra.monomial k p.1 p.2 :=
  Basis.mk_apply _ _ _

private lemma repr_monomial (i j : ℕ) :
    (monBasis k).repr (WeylAlgebra.monomial k i j) = Finsupp.single (i, j) 1 := by
  rw [← monBasis_apply k (i, j)]; exact (monBasis k).repr_self _

/-- Coordinate formula for `ad_x` in the monomial basis: the `(i, j)` coordinate of `ad_x a`
is `−(j+1)` times the `(i, j+1)` coordinate of `a`. -/
private lemma repr_adx_apply (a : WeylAlgebra k) (i j : ℕ) :
    (monBasis k).repr (adx k a) (i, j)
      = -((j : k) + 1) * (monBasis k).repr a (i, j + 1) := by
  have key :
      (Finsupp.lapply (i, j)).comp (((monBasis k).repr.toLinearMap).comp (adx k))
        = (-((j : k) + 1)) •
            (Finsupp.lapply (i, j + 1)).comp ((monBasis k).repr.toLinearMap) := by
    apply (monBasis k).ext
    rintro ⟨i', j'⟩
    simp only [LinearMap.smul_apply, LinearMap.coe_comp, Function.comp_apply,
      LinearEquiv.coe_coe, Finsupp.lapply_apply, smul_eq_mul]
    rw [monBasis_apply k (i', j'), repr_monomial]
    cases j' with
    | zero =>
      rw [adx_monomial_zero, map_zero]
      simp [Prod.ext_iff]
    | succ n =>
      rw [adx_monomial_succ, map_smul, repr_monomial, Finsupp.smul_apply,
        Finsupp.single_apply, Finsupp.single_apply, smul_eq_mul]
      by_cases h : (i', n) = (i, j)
      · obtain ⟨rfl, rfl⟩ := Prod.mk.injEq _ _ _ _ ▸ h
        simp
      · rw [if_neg h]
        rw [if_neg (by simp only [Prod.ext_iff] at h ⊢; omega)]
        ring
  have := LinearMap.congr_fun key a
  simpa only [LinearMap.smul_apply, LinearMap.coe_comp, Function.comp_apply,
    LinearEquiv.coe_coe, Finsupp.lapply_apply, smul_eq_mul] using this

/-- Coordinate formula for `ad_y` in the monomial basis: the `(i, j)` coordinate of `ad_y a`
is `(i+1)` times the `(i+1, j)` coordinate of `a`. -/
private lemma repr_ady_apply (a : WeylAlgebra k) (i j : ℕ) :
    (monBasis k).repr (ady k a) (i, j)
      = ((i : k) + 1) * (monBasis k).repr a (i + 1, j) := by
  have key :
      (Finsupp.lapply (i, j)).comp (((monBasis k).repr.toLinearMap).comp (ady k))
        = (((i : k) + 1)) •
            (Finsupp.lapply (i + 1, j)).comp ((monBasis k).repr.toLinearMap) := by
    apply (monBasis k).ext
    rintro ⟨i', j'⟩
    simp only [LinearMap.smul_apply, LinearMap.coe_comp, Function.comp_apply,
      LinearEquiv.coe_coe, Finsupp.lapply_apply, smul_eq_mul]
    rw [monBasis_apply k (i', j'), repr_monomial]
    cases i' with
    | zero =>
      rw [ady_monomial_zero, map_zero]
      simp [Prod.ext_iff]
    | succ m =>
      rw [ady_monomial_succ, map_smul, repr_monomial, Finsupp.smul_apply,
        Finsupp.single_apply, Finsupp.single_apply, smul_eq_mul]
      by_cases h : (m, j') = (i, j)
      · obtain ⟨rfl, rfl⟩ := Prod.mk.injEq _ _ _ _ ▸ h
        simp
      · rw [if_neg h]
        rw [if_neg (by simp only [Prod.ext_iff] at h ⊢; omega)]
        ring
  have := LinearMap.congr_fun key a
  simpa only [LinearMap.smul_apply, LinearMap.coe_comp, Function.comp_apply,
    LinearEquiv.coe_coe, Finsupp.lapply_apply, smul_eq_mul] using this

/-- The `y`-degree of an element: the largest `y`-exponent appearing in its basis expansion. -/
private noncomputable def yDeg (a : WeylAlgebra k) : ℕ :=
  ((monBasis k).repr a).support.sup Prod.snd

/-- The `x`-degree of an element: the largest `x`-exponent appearing in its basis expansion. -/
private noncomputable def xDeg (a : WeylAlgebra k) : ℕ :=
  ((monBasis k).repr a).support.sup Prod.fst

private lemma repr_ne_zero_of_ne_zero {a : WeylAlgebra k} (ha : a ≠ 0) :
    (monBasis k).repr a ≠ 0 := fun h => ha (by
  have := (monBasis k).linearCombination_repr a
  rw [h, map_zero] at this; exact this.symm)

private lemma adx_ne_zero {a : WeylAlgebra k} (ha : a ≠ 0) (hy : 0 < yDeg k a) :
    adx k a ≠ 0 := by
  obtain ⟨m, hm⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.pos_iff_ne_zero.mp hy)
  have hsupne : ((monBasis k).repr a).support.Nonempty :=
    Finsupp.support_nonempty_iff.mpr (repr_ne_zero_of_ne_zero k ha)
  obtain ⟨p, hp, hpe⟩ :=
    Finset.exists_mem_eq_sup ((monBasis k).repr a).support hsupne Prod.snd
  have hp2 : p.2 = m + 1 := by rw [← hpe]; exact hm
  intro hzero
  have hval : (monBasis k).repr (adx k a) (p.1, m) = 0 := by rw [hzero, map_zero]; rfl
  rw [repr_adx_apply] at hval
  have hpa : (monBasis k).repr a (p.1, m + 1) ≠ 0 := by
    have : (p.1, p.2) ∈ ((monBasis k).repr a).support := hp
    rw [hp2] at this
    exact Finsupp.mem_support_iff.mp this
  have hcoeff : -((m : k) + 1) ≠ 0 :=
    neg_ne_zero.mpr (by exact_mod_cast Nat.succ_ne_zero m)
  exact (mul_ne_zero hcoeff hpa) hval

private lemma ady_ne_zero {a : WeylAlgebra k} (ha : a ≠ 0) (hx : 0 < xDeg k a) :
    ady k a ≠ 0 := by
  obtain ⟨m, hm⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.pos_iff_ne_zero.mp hx)
  have hsupne : ((monBasis k).repr a).support.Nonempty :=
    Finsupp.support_nonempty_iff.mpr (repr_ne_zero_of_ne_zero k ha)
  obtain ⟨p, hp, hpe⟩ :=
    Finset.exists_mem_eq_sup ((monBasis k).repr a).support hsupne Prod.fst
  have hp1 : p.1 = m + 1 := by rw [← hpe]; exact hm
  intro hzero
  have hval : (monBasis k).repr (ady k a) (m, p.2) = 0 := by rw [hzero, map_zero]; rfl
  rw [repr_ady_apply] at hval
  have hpa : (monBasis k).repr a (m + 1, p.2) ≠ 0 := by
    have : (p.1, p.2) ∈ ((monBasis k).repr a).support := hp
    rw [hp1] at this
    exact Finsupp.mem_support_iff.mp this
  have hcoeff : ((m : k) + 1) ≠ 0 := by exact_mod_cast Nat.succ_ne_zero m
  exact (mul_ne_zero hcoeff hpa) hval

private lemma yDeg_adx_lt {a : WeylAlgebra k} (hy : 0 < yDeg k a) :
    yDeg k (adx k a) < yDeg k a := by
  rw [yDeg, Finset.sup_lt_iff hy]
  intro q hq
  rw [Finsupp.mem_support_iff, repr_adx_apply] at hq
  have hr : (monBasis k).repr a (q.1, q.2 + 1) ≠ 0 := fun h => hq (by rw [h, mul_zero])
  have hle : q.2 + 1 ≤ yDeg k a :=
    Finset.le_sup (f := Prod.snd) (Finsupp.mem_support_iff.mpr hr)
  omega

private lemma xDeg_ady_lt {a : WeylAlgebra k} (hx : 0 < xDeg k a) :
    xDeg k (ady k a) < xDeg k a := by
  rw [xDeg, Finset.sup_lt_iff hx]
  intro q hq
  rw [Finsupp.mem_support_iff, repr_ady_apply] at hq
  have hr : (monBasis k).repr a (q.1 + 1, q.2) ≠ 0 := fun h => hq (by rw [h, mul_zero])
  have hle : q.1 + 1 ≤ xDeg k a :=
    Finset.le_sup (f := Prod.fst) (Finsupp.mem_support_iff.mpr hr)
  omega

private lemma yDeg_ady_eq_zero {a : WeylAlgebra k} (hy : yDeg k a = 0) :
    yDeg k (ady k a) = 0 := by
  rw [yDeg]
  refine Nat.le_zero.mp (Finset.sup_le fun q hq => ?_)
  rw [Finsupp.mem_support_iff, repr_ady_apply] at hq
  have hr : (monBasis k).repr a (q.1 + 1, q.2) ≠ 0 := fun h => hq (by rw [h, mul_zero])
  have hle : q.2 ≤ yDeg k a :=
    Finset.le_sup (f := Prod.snd) (b := (q.1 + 1, q.2)) (Finsupp.mem_support_iff.mpr hr)
  omega

/-- If a nonzero element of a two-sided ideal `I` has `y`-degree `0` (a polynomial in `x`),
then `1 ∈ I`. Proved by lowering the `x`-degree via `ad_y` until a nonzero scalar is reached. -/
private lemma one_mem_of_yDeg_zero (I : TwoSidedIdeal (WeylAlgebra k)) :
    ∀ (n : ℕ) (a : WeylAlgebra k), xDeg k a = n → yDeg k a = 0 → a ∈ I → a ≠ 0 →
      (1 : WeylAlgebra k) ∈ I := by
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    intro a hn hy haI ha
    rcases Nat.eq_zero_or_pos (xDeg k a) with h0 | hpos
    · -- both degrees zero: `a` is a nonzero scalar `c • 1`, hence a unit
      set c : k := (monBasis k).repr a ((0 : ℕ), (0 : ℕ)) with hc_def
      have hsupp : ∀ p ∈ ((monBasis k).repr a).support, p = (0, 0) := by
        rintro ⟨q1, q2⟩ hp
        have h1 : q1 ≤ xDeg k a := Finset.le_sup (f := Prod.fst) hp
        have h2 : q2 ≤ yDeg k a := Finset.le_sup (f := Prod.snd) hp
        rw [h0] at h1; rw [hy] at h2
        simp only [Prod.mk.injEq]
        exact ⟨Nat.le_zero.mp h1, Nat.le_zero.mp h2⟩
      have hc : c ≠ 0 := by
        have hne := repr_ne_zero_of_ne_zero k ha
        have hsupne := Finsupp.support_nonempty_iff.mpr hne
        obtain ⟨p, hp⟩ := hsupne
        have hp0 : p = (0, 0) := hsupp p hp
        rw [hp0] at hp
        exact Finsupp.mem_support_iff.mp hp
      have hrepr : (monBasis k).repr a = Finsupp.single (0, 0) c := by
        ext p
        rw [Finsupp.single_apply]
        by_cases hp : p = (0, 0)
        · rw [hp, if_pos rfl]
        · rw [if_neg (Ne.symm hp), Finsupp.notMem_support_iff.mp (fun h => hp (hsupp p h))]
      have hone : monBasis k (0, 0) = (1 : WeylAlgebra k) := by
        rw [monBasis_apply, WeylAlgebra.monomial]; simp
      have ha1 : a = c • (1 : WeylAlgebra k) := by
        have h := (monBasis k).linearCombination_repr a
        rw [hrepr, Finsupp.linearCombination_single, hone] at h
        exact h.symm
      have hmem : c⁻¹ • a ∈ I := by
        rw [Algebra.smul_def]; exact I.mul_mem_left _ _ haI
      rwa [ha1, smul_smul, inv_mul_cancel₀ hc, one_smul] at hmem
    · -- lower the x-degree with ad_y
      have hlt : xDeg k (ady k a) < n := hn ▸ xDeg_ady_lt k hpos
      have hne : ady k a ≠ 0 := ady_ne_zero k ha hpos
      have hy' : yDeg k (ady k a) = 0 := yDeg_ady_eq_zero k hy
      have hmem : ady k a ∈ I := by
        rw [ady_apply]
        exact I.sub_mem (I.mul_mem_left _ _ haI) (I.mul_mem_right _ _ haI)
      exact ih _ hlt (ady k a) rfl hy' hmem hne

/-- Every nonzero element of a two-sided ideal `I` forces `1 ∈ I`. Proved by lowering the
`y`-degree via `ad_x` down to the `yDeg = 0` case. -/
private lemma one_mem_of_mem (I : TwoSidedIdeal (WeylAlgebra k)) :
    ∀ (n : ℕ) (a : WeylAlgebra k), yDeg k a = n → a ∈ I → a ≠ 0 →
      (1 : WeylAlgebra k) ∈ I := by
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    intro a hn haI ha
    rcases Nat.eq_zero_or_pos (yDeg k a) with h0 | hpos
    · exact one_mem_of_yDeg_zero k I (xDeg k a) a rfl h0 haI ha
    · have hlt : yDeg k (adx k a) < n := hn ▸ yDeg_adx_lt k hpos
      have hne : adx k a ≠ 0 := adx_ne_zero k ha hpos
      have hmem : adx k a ∈ I := by
        rw [adx_apply]
        exact I.sub_mem (I.mul_mem_left _ _ haI) (I.mul_mem_right _ _ haI)
      exact ih _ hlt (adx k a) rfl hmem hne

/-- **(a)** In characteristic `0`, the Weyl algebra is a simple ring: its only two-sided ideals
are `0` and the whole algebra. -/
theorem isSimpleRing_charZero : IsSimpleRing (WeylAlgebra k) := by
  have hnt : (0 : WeylAlgebra k) ≠ 1 := by
    intro h
    have h2 := congrArg (polyRep k) h
    rw [map_zero, map_one] at h2
    have h3 := congrArg (fun f : Module.End k (Polynomial k) => f Polynomial.X) h2
    simp only [LinearMap.zero_apply, Module.End.one_apply] at h3
    exact Polynomial.X_ne_zero h3.symm
  haveI : Nontrivial (WeylAlgebra k) := ⟨0, 1, hnt⟩
  apply IsSimpleRing.of_eq_bot_or_eq_top
  intro I
  rw [or_iff_not_imp_left]
  intro hI
  obtain ⟨a, haI, ha⟩ :=
    SetLike.exists_of_lt (bot_lt_iff_ne_bot.mpr hI : (⊥ : TwoSidedIdeal (WeylAlgebra k)) < I)
  rw [TwoSidedIdeal.mem_bot] at ha
  exact (I.one_mem_iff).mp (one_mem_of_mem k I (yDeg k a) a rfl haI ha)

end CharZeroSimple

/-! ## (b) Characteristic `p`: the center -/

/-- **(b)** In characteristic `p`, `x^p` is a central element of the Weyl algebra. -/
theorem x_pow_char_mem_center (k : Type*) [Field k] (p : ℕ) [CharP k p] :
    WeylAlgebra.x k ^ p ∈ Subalgebra.center k (WeylAlgebra k) := by
  apply mem_center_of_comm_gen
  · exact (Commute.refl (WeylAlgebra.x k)).pow_left p
  · -- `xᵖ` commutes with `y`: the commutator `(p) • xᵖ⁻¹` vanishes in characteristic `p`.
    cases p with
    | zero => simp
    | succ n =>
      have h := y_mul_x_pow_succ k n
      have hz : (n + 1 : ℕ) • WeylAlgebra.x k ^ n = 0 := by
        rw [← Nat.cast_smul_eq_nsmul (R := k), CharP.cast_eq_zero, zero_smul]
      rw [hz, add_zero] at h
      exact h.symm

/-- **(b)** In characteristic `p`, `y^p` is a central element of the Weyl algebra. -/
theorem y_pow_char_mem_center (k : Type*) [Field k] (p : ℕ) [CharP k p] :
    WeylAlgebra.y k ^ p ∈ Subalgebra.center k (WeylAlgebra k) := by
  apply mem_center_of_comm_gen
  · -- `yᵖ` commutes with `x`: the commutator `(p) • yᵖ⁻¹` vanishes in characteristic `p`.
    cases p with
    | zero => simp
    | succ n =>
      have h := x_mul_y_pow_succ k n
      have hz : (n + 1 : ℕ) • WeylAlgebra.y k ^ n = 0 := by
        rw [← Nat.cast_smul_eq_nsmul (R := k), CharP.cast_eq_zero, zero_smul]
      rw [hz, sub_zero] at h
      exact h.symm
  · exact (Commute.refl (WeylAlgebra.y k)).pow_left p

/-! ### Char-free monomial coordinates (for the center in characteristic `p`)

The characteristic-zero simplicity argument above uses the monomial basis `monBasis`, built
from `Etingof.Proposition_2_7_1` and therefore only available over a characteristic-zero field.
For the center in characteristic `p` we need the same coordinate formulas over the char-free
monomial basis `monBasisP`, built from `Etingof.Proposition_2_7_1_charFree` (which holds in any
characteristic via the faithful module `E`). The inner-derivation monomial lemmas
`adx_monomial_zero/succ` and `ady_monomial_zero/succ` are already characteristic-free, so only
the basis and the two coordinate formulas need to be re-established here. -/

section CharPCenter

variable (k : Type*) [Field k]

open WeylAlgebra Module

/-- The characteristic-free monomial basis `{xⁱyʲ}` of the Weyl algebra (Proposition 2.7.1,
char-free form), available in any characteristic. -/
private noncomputable def monBasisP : Basis (ℕ × ℕ) k (WeylAlgebra k) :=
  Basis.mk (Proposition_2_7_1_charFree k).1 (Proposition_2_7_1_charFree k).2

private lemma monBasisP_apply (p : ℕ × ℕ) :
    monBasisP k p = WeylAlgebra.monomial k p.1 p.2 :=
  Basis.mk_apply _ _ _

private lemma repr_monomialP (i j : ℕ) :
    (monBasisP k).repr (WeylAlgebra.monomial k i j) = Finsupp.single (i, j) 1 := by
  rw [← monBasisP_apply k (i, j)]; exact (monBasisP k).repr_self _

/-- Coordinate formula for `ad_x` in the char-free monomial basis: the `(i, j)` coordinate of
`ad_x a` is `−(j+1)` times the `(i, j+1)` coordinate of `a`. -/
private lemma repr_adx_applyP (a : WeylAlgebra k) (i j : ℕ) :
    (monBasisP k).repr (adx k a) (i, j)
      = -((j : k) + 1) * (monBasisP k).repr a (i, j + 1) := by
  have key :
      (Finsupp.lapply (i, j)).comp (((monBasisP k).repr.toLinearMap).comp (adx k))
        = (-((j : k) + 1)) •
            (Finsupp.lapply (i, j + 1)).comp ((monBasisP k).repr.toLinearMap) := by
    apply (monBasisP k).ext
    rintro ⟨i', j'⟩
    simp only [LinearMap.smul_apply, LinearMap.coe_comp, Function.comp_apply,
      LinearEquiv.coe_coe, Finsupp.lapply_apply, smul_eq_mul]
    rw [monBasisP_apply k (i', j'), repr_monomialP]
    cases j' with
    | zero =>
      rw [adx_monomial_zero, map_zero]
      simp [Prod.ext_iff]
    | succ n =>
      rw [adx_monomial_succ, map_smul, repr_monomialP, Finsupp.smul_apply,
        Finsupp.single_apply, Finsupp.single_apply, smul_eq_mul]
      by_cases h : (i', n) = (i, j)
      · obtain ⟨rfl, rfl⟩ := Prod.mk.injEq _ _ _ _ ▸ h
        simp
      · rw [if_neg h]
        rw [if_neg (by simp only [Prod.ext_iff] at h ⊢; omega)]
        ring
  have := LinearMap.congr_fun key a
  simpa only [LinearMap.smul_apply, LinearMap.coe_comp, Function.comp_apply,
    LinearEquiv.coe_coe, Finsupp.lapply_apply, smul_eq_mul] using this

/-- Coordinate formula for `ad_y` in the char-free monomial basis: the `(i, j)` coordinate of
`ad_y a` is `(i+1)` times the `(i+1, j)` coordinate of `a`. -/
private lemma repr_ady_applyP (a : WeylAlgebra k) (i j : ℕ) :
    (monBasisP k).repr (ady k a) (i, j)
      = ((i : k) + 1) * (monBasisP k).repr a (i + 1, j) := by
  have key :
      (Finsupp.lapply (i, j)).comp (((monBasisP k).repr.toLinearMap).comp (ady k))
        = (((i : k) + 1)) •
            (Finsupp.lapply (i + 1, j)).comp ((monBasisP k).repr.toLinearMap) := by
    apply (monBasisP k).ext
    rintro ⟨i', j'⟩
    simp only [LinearMap.smul_apply, LinearMap.coe_comp, Function.comp_apply,
      LinearEquiv.coe_coe, Finsupp.lapply_apply, smul_eq_mul]
    rw [monBasisP_apply k (i', j'), repr_monomialP]
    cases i' with
    | zero =>
      rw [ady_monomial_zero, map_zero]
      simp [Prod.ext_iff]
    | succ m =>
      rw [ady_monomial_succ, map_smul, repr_monomialP, Finsupp.smul_apply,
        Finsupp.single_apply, Finsupp.single_apply, smul_eq_mul]
      by_cases h : (m, j') = (i, j)
      · obtain ⟨rfl, rfl⟩ := Prod.mk.injEq _ _ _ _ ▸ h
        simp
      · rw [if_neg h]
        rw [if_neg (by simp only [Prod.ext_iff] at h ⊢; omega)]
        ring
  have := LinearMap.congr_fun key a
  simpa only [LinearMap.smul_apply, LinearMap.coe_comp, Function.comp_apply,
    LinearEquiv.coe_coe, Finsupp.lapply_apply, smul_eq_mul] using this

end CharPCenter

/-- **(b)** In characteristic `p`, the center of the Weyl algebra is the polynomial subalgebra
`k[x^p, y^p]` generated by `x^p` and `y^p`. -/
theorem center_charP (k : Type*) [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p] :
    Subalgebra.center k (WeylAlgebra k)
      = Algebra.adjoin k {WeylAlgebra.x k ^ p, WeylAlgebra.y k ^ p} := by
  apply le_antisymm
  · -- `center ⊆ k[xᵖ, yᵖ]`: write a central `z` in the monomial basis; centrality forces the
    -- `x`- and `y`-degrees of every nonzero coefficient to be divisible by `p`.
    intro z hz
    -- Centrality gives `ad_x z = 0` and `ad_y z = 0`.
    have hadx : adx k z = 0 := by
      rw [adx_apply, sub_eq_zero]
      exact Subalgebra.mem_center_iff.mp hz (WeylAlgebra.x k)
    have hady : ady k z = 0 := by
      rw [ady_apply, sub_eq_zero]
      exact Subalgebra.mem_center_iff.mp hz (WeylAlgebra.y k)
    set c := (monBasisP k).repr z with hc
    -- Vanishing of `ad_x z` forces `(j+1)·c(i,j+1) = 0` for all `i, j`.
    have hcoefY : ∀ (i j : ℕ), 1 ≤ j → (j : k) * c (i, j) = 0 := by
      intro i j hj
      obtain ⟨j, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (by omega : j ≠ 0)
      have h := repr_adx_applyP k z i j
      rw [hadx, map_zero, Finsupp.zero_apply] at h
      have h2 : ((j : k) + 1) * c (i, j + 1) = 0 :=
        neg_eq_zero.mp (by rw [← neg_mul]; exact h.symm)
      rw [show ((j + 1 : ℕ) : k) = (j : k) + 1 by push_cast; ring]
      exact h2
    -- Vanishing of `ad_y z` forces `(i+1)·c(i+1,j) = 0` for all `i, j`.
    have hcoefX : ∀ (i j : ℕ), 1 ≤ i → (i : k) * c (i, j) = 0 := by
      intro i j hi
      obtain ⟨i, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (by omega : i ≠ 0)
      have h := repr_ady_applyP k z i j
      rw [hady, map_zero, Finsupp.zero_apply] at h
      have h2 : ((i : k) + 1) * c (i + 1, j) = 0 := by rw [← h]
      rw [show ((i + 1 : ℕ) : k) = (i : k) + 1 by push_cast; ring]
      exact h2
    -- Every point in the support has both coordinates divisible by `p`.
    have hsupp : ∀ q ∈ c.support, p ∣ q.1 ∧ p ∣ q.2 := by
      rintro ⟨i, j⟩ hq
      have hne : c (i, j) ≠ 0 := Finsupp.mem_support_iff.mp hq
      refine ⟨?_, ?_⟩
      · rcases Nat.eq_zero_or_pos i with hi | hi
        · rw [hi]; exact dvd_zero p
        · have hik : (i : k) = 0 :=
            (mul_eq_zero.mp (hcoefX i j hi)).resolve_right hne
          exact (CharP.cast_eq_zero_iff k p i).mp hik
      · rcases Nat.eq_zero_or_pos j with hj | hj
        · rw [hj]; exact dvd_zero p
        · have hjk : (j : k) = 0 :=
            (mul_eq_zero.mp (hcoefY i j hj)).resolve_right hne
          exact (CharP.cast_eq_zero_iff k p j).mp hjk
    -- Reassemble `z` from its basis expansion; each surviving monomial lies in `k[xᵖ, yᵖ]`.
    have hz_eq : z = c.sum (fun q a => a • monBasisP k q) := by
      rw [hc, ← Finsupp.linearCombination_apply, (monBasisP k).linearCombination_repr]
    rw [hz_eq, Finsupp.sum]
    apply Subalgebra.sum_mem
    rintro ⟨i, j⟩ hq
    obtain ⟨hd1, hd2⟩ := hsupp (i, j) hq
    -- The surviving monomial `xⁱyʲ = (xᵖ)^{i/p} (yᵖ)^{j/p}` lies in `k[xᵖ, yᵖ]`.
    have hmem : WeylAlgebra.monomial k i j ∈
        Algebra.adjoin k {WeylAlgebra.x k ^ p, WeylAlgebra.y k ^ p} := by
      have hxpS : WeylAlgebra.x k ^ p ∈
          Algebra.adjoin k {WeylAlgebra.x k ^ p, WeylAlgebra.y k ^ p} :=
        Algebra.subset_adjoin (Set.mem_insert _ _)
      have hypS : WeylAlgebra.y k ^ p ∈
          Algebra.adjoin k {WeylAlgebra.x k ^ p, WeylAlgebra.y k ^ p} :=
        Algebra.subset_adjoin (Set.mem_insert_of_mem _ rfl)
      have hx1 : WeylAlgebra.x k ^ i = (WeylAlgebra.x k ^ p) ^ (i / p) := by
        rw [← pow_mul, Nat.mul_div_cancel' hd1]
      have hy1 : WeylAlgebra.y k ^ j = (WeylAlgebra.y k ^ p) ^ (j / p) := by
        rw [← pow_mul, Nat.mul_div_cancel' hd2]
      rw [WeylAlgebra.monomial, hx1, hy1]
      exact mul_mem (pow_mem hxpS _) (pow_mem hypS _)
    rw [monBasisP_apply]
    exact Subalgebra.smul_mem _ hmem _
  · -- `k[xᵖ, yᵖ] ⊆ center`: both generators are central.
    apply Algebra.adjoin_le
    intro w hw
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hw
    rcases hw with rfl | rfl
    · exact x_pow_char_mem_center k p
    · exact y_pow_char_mem_center k p

/-! ## (c) Characteristic `p`: irreducible representations -/

/-- A `k`-submodule of a simple `WeylAlgebra k`-module `V` that is stable under the action of
every algebra element and contains a nonzero vector is all of `V`. This packages the
"nonzero invariant submodule is the whole simple module" step. -/
private lemma mem_of_invariant (k : Type*) [Field k] (V : Type*) [AddCommGroup V] [Module k V]
    [Module (WeylAlgebra k) V] [IsScalarTower k (WeylAlgebra k) V]
    [IsSimpleModule (WeylAlgebra k) V] (Wk : Submodule k V)
    (hstab : ∀ (a : WeylAlgebra k) (z : V), z ∈ Wk → a • z ∈ Wk)
    (hne : ∃ z ∈ Wk, z ≠ 0) : ∀ z : V, z ∈ Wk := by
  let WA : Submodule (WeylAlgebra k) V :=
    { carrier := Wk
      add_mem' := fun ha hb => Wk.add_mem ha hb
      zero_mem' := Wk.zero_mem
      smul_mem' := fun a z hz => hstab a z hz }
  have hbot : WA ≠ ⊥ := by
    obtain ⟨z, hz, hz0⟩ := hne
    intro h
    apply hz0
    have hzWA : z ∈ WA := hz
    rw [h, Submodule.mem_bot] at hzWA
    exact hzWA
  have hWA : WA = ⊤ := (eq_bot_or_eq_top WA).resolve_left hbot
  intro z
  have : z ∈ WA := hWA ▸ Submodule.mem_top
  exact this

/-- A central element of the Weyl algebra acts as a `k`-scalar on a simple finite dimensional
module over an algebraically closed field (Schur's lemma via eigenvalue existence). -/
private lemma central_smul_scalar (k : Type*) [Field k] [IsAlgClosed k] (V : Type*)
    [AddCommGroup V] [Module k V] [Module (WeylAlgebra k) V] [IsScalarTower k (WeylAlgebra k) V]
    [FiniteDimensional k V] [IsSimpleModule (WeylAlgebra k) V]
    (z : WeylAlgebra k) (hz : z ∈ Subalgebra.center k (WeylAlgebra k)) :
    ∃ μ : k, ∀ w : V, z • w = μ • w := by
  haveI : Nontrivial V := IsSimpleModule.nontrivial (WeylAlgebra k) V
  obtain ⟨μ, hμ⟩ := (Algebra.lsmul k k V z).exists_eigenvalue
  refine ⟨μ, ?_⟩
  have hstab : ∀ (a : WeylAlgebra k) (w : V),
      w ∈ Module.End.eigenspace (Algebra.lsmul k k V z) μ →
      a • w ∈ Module.End.eigenspace (Algebra.lsmul k k V z) μ := by
    intro a w hw
    rw [Module.End.mem_eigenspace_iff, Algebra.lsmul_apply] at hw ⊢
    calc z • (a • w) = (a * z) • w := by
              rw [← mul_smul, ← Subalgebra.mem_center_iff.mp hz a]
      _ = a • (z • w) := by rw [mul_smul]
      _ = a • (μ • w) := by rw [hw]
      _ = μ • (a • w) := by rw [smul_comm]
  obtain ⟨w0, hw0⟩ := hμ.exists_hasEigenvector
  have hmem := mem_of_invariant k V (Module.End.eigenspace (Algebra.lsmul k k V z) μ)
    hstab ⟨w0, hw0.1, hw0.2⟩
  intro w
  have hw := hmem w
  rw [Module.End.mem_eigenspace_iff, Algebra.lsmul_apply] at hw
  exact hw

/-- In `Fin p` with `p` prime, adding one is addition of naturals reduced mod `p`. Packaged
because the `Fin (n+1)`-shaped lemmas in Mathlib do not apply to the variable modulus `p`. -/
private lemma val_add_one (p : ℕ) [Fact (Nat.Prime p)] (i : Fin p) :
    ((i + 1 : Fin p) : ℕ) = ((i : ℕ) + 1) % p := by
  haveI : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩
  rw [Fin.val_add, Fin.val_one', Nat.mod_eq_of_lt (Fact.out : p.Prime).one_lt]

/-- The two cases of `i + 1` in `Fin p`: either `i` is the top index and `i + 1` wraps to `0`,
or `i + 1` is computed without reduction. -/
private lemma add_one_cases (p : ℕ) [Fact (Nat.Prime p)] (i : Fin p) :
    ((i : ℕ) + 1 = p ∧ (i + 1 : Fin p) = 0) ∨
      ((i : ℕ) + 1 < p ∧ ((i + 1 : Fin p) : ℕ) = (i : ℕ) + 1) := by
  haveI : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩
  have hval := val_add_one p i
  rcases Nat.lt_or_ge ((i : ℕ) + 1) p with h | h
  · exact Or.inr ⟨h, by rw [hval, Nat.mod_eq_of_lt h]⟩
  · have hp : (i : ℕ) + 1 = p := le_antisymm i.isLt h
    refine Or.inl ⟨hp, Fin.ext ?_⟩
    rw [hval, hp, Nat.mod_self, Fin.val_zero]

/-- **Normal form for a finite dimensional simple Weyl-algebra module in characteristic `p`.**

Over an algebraically closed field of characteristic `p`, every finite dimensional simple
`WeylAlgebra k`-module `V` has a basis `b₀, …, b_{p-1}` on which the generators act by the
book's model `k[t]/(tᵖ - α)` with `y` acting as `d/dt + c`:

* `x · bᵢ = b_{i+1}`, cyclically, with the wraparound `x · b_{p-1} = α · b₀`;
* `y · b_{i+1} = c · b_{i+1} + (i+1) · bᵢ`, so `y` is `c` plus the lowering operator.

The construction is the hint of Problem 2.7.4(c): take an eigenvector `v` of `y` with
eigenvalue `c` (this needs `k` algebraically closed), set `bᵢ = xⁱ · v`, and let `α` be the
scalar by which the central element `xᵖ` acts. `Problem2_7_4_Family.lean` turns this into the
statement that `V ≅ V(α, c)`, and `finrank_irreducible_charP` below reads off `dim V = p`. -/
theorem exists_normalForm (k : Type*) [Field k] [IsAlgClosed k] (p : ℕ)
    [Fact (Nat.Prime p)] [CharP k p]
    (V : Type*) [AddCommGroup V] [Module k V] [Module (WeylAlgebra k) V]
    [IsScalarTower k (WeylAlgebra k) V] [FiniteDimensional k V]
    [IsSimpleModule (WeylAlgebra k) V] :
    ∃ (α c : k) (b : Module.Basis (Fin p) k V),
      (∀ i : Fin p,
        WeylAlgebra.x k • b i = (if (i + 1 : Fin p) = 0 then α else 1) • b (i + 1)) ∧
      (∀ i : Fin p,
        WeylAlgebra.y k • b (i + 1) = c • b (i + 1) + (((i : ℕ) + 1 : ℕ) : k) • b i) := by
  haveI : Nontrivial V := IsSimpleModule.nontrivial (WeylAlgebra k) V
  have p_pos : 0 < p := (Fact.out : p.Prime).pos
  have hfac : ∀ m : ℕ, m < p → ((m.factorial : ℕ) : k) ≠ 0 := by
    intro m hm
    rw [ne_eq, CharP.cast_eq_zero_iff k p, Nat.Prime.dvd_factorial Fact.out]
    exact Nat.not_le.mpr hm
  -- Eigenvector `v` of the action of `y`, with eigenvalue `lam`.
  obtain ⟨lam, hlam⟩ := (Algebra.lsmul k k V (WeylAlgebra.y k)).exists_eigenvalue
  obtain ⟨v, hv⟩ := hlam.exists_hasEigenvector
  have hyv : WeylAlgebra.y k • v = lam • v := by
    have h := Module.End.mem_eigenspace_iff.mp hv.1
    rwa [Algebra.lsmul_apply] at h
  have hv0 : v ≠ 0 := hv.2
  set w : ℕ → V := fun i => WeylAlgebra.x k ^ i • v with hwdef
  have hwv : ∀ i, w i = WeylAlgebra.x k ^ i • v := fun _ => rfl
  have hw0 : w 0 = v := by rw [hwv, pow_zero, one_smul]
  -- `xᵖ` acts as a scalar `μ`.
  obtain ⟨μ, hμ⟩ := central_smul_scalar k V (WeylAlgebra.x k ^ p) (x_pow_char_mem_center k p)
  -- The lowering operator `N = ρ(y) - lam`.
  set N : Module.End k V := Algebra.lsmul k k V (WeylAlgebra.y k) - lam • 1 with hN
  have hNstep : ∀ i : ℕ, N (w (i + 1)) = ((i + 1 : ℕ) : k) • w i := by
    intro i
    rw [hwv (i + 1), hN, LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply,
      Algebra.lsmul_apply, ← mul_smul, y_mul_x_pow_succ k i, add_smul, mul_smul, hyv,
      smul_comm (WeylAlgebra.x k ^ (i + 1)) lam v,
      ← Nat.cast_smul_eq_nsmul k (i + 1) (WeylAlgebra.x k ^ i), smul_assoc, hwv i]
    abel
  have hN0 : N (w 0) = 0 := by
    rw [hwv, hN, LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply,
      Algebra.lsmul_apply, pow_zero, one_smul, hyv, sub_self]
  have hkill1 : ∀ i : ℕ, (N ^ (i + 1)) (w i) = 0 := by
    intro i
    induction i with
    | zero => rw [pow_one]; exact hN0
    | succ n ih => rw [pow_succ, Module.End.mul_apply, hNstep, map_smul, ih, smul_zero]
  have hval : ∀ i : ℕ, (N ^ i) (w i) = ((i.factorial : ℕ) : k) • v := by
    intro i
    induction i with
    | zero => rw [pow_zero, Module.End.one_apply, hw0, Nat.factorial_zero, Nat.cast_one, one_smul]
    | succ n ih =>
      rw [pow_succ, Module.End.mul_apply, hNstep, map_smul, ih, smul_smul, ← Nat.cast_mul,
        ← Nat.factorial_succ]
  have hkill_gen : ∀ (m j : ℕ), j < m → (N ^ m) (w j) = 0 := by
    intro m j hjm
    obtain ⟨t, ht⟩ : ∃ t, m = t + (j + 1) := ⟨m - (j + 1), by omega⟩
    rw [ht, pow_add, Module.End.mul_apply, hkill1, map_zero]
  -- The `p` vectors `w 0, …, w (p-1)` are linearly independent.
  have hli : ∀ n : ℕ, n ≤ p → LinearIndependent k (fun i : Fin n => w (i : ℕ)) := by
    intro n
    induction n with
    | zero => intro _; exact linearIndependent_empty_type
    | succ m ih =>
      intro hmp
      have hmp' : m ≤ p := Nat.le_of_succ_le hmp
      have hmlt : m < p := hmp
      have hfun : (fun i : Fin (m + 1) => w (i : ℕ))
          = Fin.snoc (fun i : Fin m => w (i : ℕ)) (w m) := by
        funext i
        induction i using Fin.lastCases with
        | last => simp
        | cast j => simp
      rw [hfun]
      refine (ih hmp').finSnoc ?_
      intro hmem
      have hzero : (N ^ m) (w m) = 0 := by
        have hsub : Submodule.span k (Set.range (fun i : Fin m => w (i : ℕ)))
            ≤ LinearMap.ker (N ^ m) := by
          rw [Submodule.span_le]
          rintro _ ⟨i, rfl⟩
          simp only [SetLike.mem_coe, LinearMap.mem_ker]
          exact hkill_gen m (i : ℕ) i.isLt
        have hk := hsub hmem
        rwa [LinearMap.mem_ker] at hk
      rw [hval m] at hzero
      rcases smul_eq_zero.mp hzero with h | h
      · exact hfac m hmlt h
      · exact hv0 h
  -- The span of the `p` vectors is a nonzero invariant submodule, hence all of `V`.
  set Wk : Submodule k V := Submodule.span k (Set.range (fun i : Fin p => w (i : ℕ))) with hWk
  have hgen_mem : ∀ i : Fin p, w (i : ℕ) ∈ Wk := fun i => Submodule.subset_span ⟨i, rfl⟩
  have hshift : ∀ t : ℕ, w (p + t) = μ • w t := by
    intro t
    rw [hwv (p + t), hwv t, pow_add, mul_smul, hμ (WeylAlgebra.x k ^ t • v)]
  have hall_mem : ∀ j : ℕ, w j ∈ Wk := by
    intro j
    induction j using Nat.strong_induction_on with
    | _ j ih =>
      by_cases hjp : j < p
      · exact hgen_mem ⟨j, hjp⟩
      · obtain ⟨t, ht⟩ : ∃ t, j = p + t := ⟨j - p, by omega⟩
        subst ht
        rw [hshift]
        exact Wk.smul_mem μ (ih t (by omega))
  have hx_stab : ∀ z ∈ Wk, WeylAlgebra.x k • z ∈ Wk := by
    intro z hz
    rw [hWk] at hz
    induction hz using Submodule.span_induction with
    | mem u hu =>
        obtain ⟨i, rfl⟩ := hu
        change WeylAlgebra.x k • w (i : ℕ) ∈ Wk
        rw [hwv, ← mul_smul, ← pow_succ', ← hwv]
        exact hall_mem ((i : ℕ) + 1)
    | zero => rw [smul_zero]; exact Wk.zero_mem
    | add a b _ _ ha hb => rw [smul_add]; exact Wk.add_mem ha hb
    | smul c a _ ha => rw [smul_comm]; exact Wk.smul_mem c ha
  have hy_stab : ∀ z ∈ Wk, WeylAlgebra.y k • z ∈ Wk := by
    intro z hz
    rw [hWk] at hz
    induction hz using Submodule.span_induction with
    | mem u hu =>
        obtain ⟨i, rfl⟩ := hu
        change WeylAlgebra.y k • w (i : ℕ) ∈ Wk
        have hNexp : N (w (i : ℕ)) = WeylAlgebra.y k • w (i : ℕ) - lam • w (i : ℕ) := by
          rw [hN, LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply,
            Algebra.lsmul_apply]
        have hNwi : N (w (i : ℕ)) ∈ Wk := by
          cases hci : (i : ℕ) with
          | zero => rw [hN0]; exact Wk.zero_mem
          | succ j =>
              rw [hNstep]
              exact Wk.smul_mem _ (hall_mem j)
        have key : WeylAlgebra.y k • w (i : ℕ) = N (w (i : ℕ)) + lam • w (i : ℕ) := by
          rw [hNexp]; abel
        rw [key]
        exact Wk.add_mem hNwi (Wk.smul_mem lam (hall_mem (i : ℕ)))
    | zero => rw [smul_zero]; exact Wk.zero_mem
    | add a b _ _ ha hb => rw [smul_add]; exact Wk.add_mem ha hb
    | smul c a _ ha => rw [smul_comm]; exact Wk.smul_mem c ha
  have ha_stab : ∀ (a : WeylAlgebra k) (z : V), z ∈ Wk → a • z ∈ Wk := by
    intro a
    obtain ⟨a', rfl⟩ := RingQuot.mkAlgHom_surjective k (WeylAlgebraRel k) a
    have ha' : a' ∈ Algebra.adjoin k (Set.range (FreeAlgebra.ι k)) := by
      rw [FreeAlgebra.adjoin_range_ι]; exact Algebra.mem_top
    induction ha' using Algebra.adjoin_induction with
    | mem g hg =>
        obtain ⟨idx, rfl⟩ := hg
        intro z hz
        fin_cases idx
        · exact hx_stab z hz
        · exact hy_stab z hz
    | algebraMap r =>
        intro z hz
        rw [AlgHom.commutes, algebraMap_smul]
        exact Wk.smul_mem r hz
    | add p q _ _ ihp ihq =>
        intro z hz
        rw [map_add, add_smul]
        exact Wk.add_mem (ihp z hz) (ihq z hz)
    | mul p q _ _ ihp ihq =>
        intro z hz
        rw [map_mul, mul_smul]
        exact ihp _ (ihq z hz)
  have hspan_top : ∀ z : V, z ∈ Wk :=
    mem_of_invariant k V Wk ha_stab ⟨v, hw0 ▸ hgen_mem ⟨0, p_pos⟩, hv0⟩
  have hsp : ⊤ ≤ Submodule.span k (Set.range (fun i : Fin p => w (i : ℕ))) := by
    rw [← hWk]; intro z _; exact hspan_top z
  have hli_p : LinearIndependent k (fun i : Fin p => w (i : ℕ)) := hli p le_rfl
  -- Package the `p` vectors as a basis and read off the two structure relations.
  refine ⟨μ, lam, Module.Basis.mk hli_p hsp, ?_, ?_⟩
  · intro i
    simp only [Module.Basis.mk_apply]
    have hstep : WeylAlgebra.x k • w (i : ℕ) = w ((i : ℕ) + 1) := by
      rw [hwv, hwv, ← mul_smul, ← pow_succ']
    rcases add_one_cases p i with ⟨hp, h0⟩ | ⟨hlt, hval⟩
    · rw [h0, if_pos rfl, hstep, hp, Fin.val_zero, hw0]
      exact hμ v
    · have hne : (i + 1 : Fin p) ≠ 0 := by
        intro h
        rw [h, Fin.val_zero] at hval
        omega
      rw [if_neg hne, one_smul, hval, hstep]
  · intro i
    simp only [Module.Basis.mk_apply]
    rcases add_one_cases p i with ⟨hp, h0⟩ | ⟨_, hval⟩
    · -- Wraparound: `y` fixes `w 0` up to `lam`, and the coefficient `p` vanishes in `k`.
      rw [h0, Fin.val_zero, hw0, hyv, hp, CharP.cast_eq_zero k p, zero_smul, add_zero]
    · -- Interior: this is exactly the lowering relation `N (w (i+1)) = (i+1) • w i`.
      have hN' := hNstep (i : ℕ)
      rw [hN, LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply,
        Algebra.lsmul_apply, sub_eq_iff_eq_add'] at hN'
      rw [hval, hN']

/-- **(c)** In characteristic `p`, over an algebraically closed field, every irreducible finite
dimensional representation of the Weyl algebra has dimension exactly `p`.

The hypothesis `[IsAlgClosed k]` is required: without it the statement is false (over a
non-closed field the Weyl algebra is Azumaya of rank `p²` over its center `k[xᵖ,yᵖ]`, and a
simple module attached to a closed point of residue degree `d` has `k`-dimension `p·d`). The
book (Etingof, Problem 2.7.4(c)) works under the standing convention that `k` is algebraically
closed; the eigenvector of `y` used in the hint exists only then. -/
theorem finrank_irreducible_charP (k : Type*) [Field k] [IsAlgClosed k] (p : ℕ)
    [Fact (Nat.Prime p)] [CharP k p]
    (V : Type*) [AddCommGroup V] [Module k V] [Module (WeylAlgebra k) V]
    [IsScalarTower k (WeylAlgebra k) V] [FiniteDimensional k V]
    [IsSimpleModule (WeylAlgebra k) V] :
    Module.finrank k V = p := by
  obtain ⟨_, _, b, _, _⟩ := exists_normalForm k p V
  rw [Module.finrank_eq_card_basis b, Fintype.card_fin]

end Etingof.Problem2_7_4
